### ISSUE TITLE
Fix formatting for "DMP Templates" PDF and DOCX files

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1003]
related issue #712 for Public DMPs files

Content:
- Delete cover page - this is only appropriate for Public DMPs, not for DMP Templates
- Delete "DMP" from the template page that follows it (screenshot 1 below). The heading should be the Funder/Org name: Template name (e.g., Arts and Humanities Research Council (AHRC): AHRC Technical Plan).
- Beneath the title, DMP Templates should contain Section headings, Questions, and any Guidance provided by the funder as part of the template. Currently the Guidance is missing (see screenshot for DOD template from current DMPTool compared w/DMP2 stage versions below).

Style:
- Formatting style (fonts, sizes, etc) should be consistent for Public DMPs and DMP Templates PDFs (this looks to be the case already)
- Formatting style should be as close as possible between PDF and DOCX files for exported DMP Templates. Sans serif font, boldface for Title, section headings, questions are good, regular text for guidance. DOCX files should not use all caps for Project title and section headings as in screenshot 3 below - please make initial caps only.
- if easy to implement, insert a line below the template title for PDF and DOCX files as in screenshot 2 below (but this isn't necessary if it proves to be complicated for either format)

1 - AHRC Template exported as PDF from Roadmap stage
![screen shot 2018-01-05 at 9 40 37 am](https://user-images.githubusercontent.com/12703638/34621078-94f87be2-f1fc-11e7-8935-30c60848ab56.png)

2 - DOD Template exported as DOCX from DMPTool
![screen shot 2018-01-05 at 9 30 57 am](https://user-images.githubusercontent.com/12703638/34620917-fd5a42b6-f1fb-11e7-9ac2-37e44818b56c.png)

3 - DOD Template exported as DOCX from DMP2-stage/Roadmap
![screen shot 2018-01-05 at 9 29 37 am](https://user-images.githubusercontent.com/12703638/34620924-00909430-f1fc-11e7-900e-a5ddd5e00828.png)

**Comment by briri** [comment]
Updated the public template PDF

![screen shot 2018-01-19 at 2 49 27 pm](https://user-images.githubusercontent.com/1204467/35175323-012352fc-fd28-11e7-9bdf-bb440624a5c1.png)

'Example answer' would appear similar to Guidance.

Note that I am working against a local database that does not reflect the actual NSF templates on dmp2-stg.

**Comment by stephaniesimms** [comment]
this looks great to me @briri - we don't have any funder templates that include example answers (to my knowledge) but I think it would be helpful to have them here if we did.

**Comment by stephaniesimms** [comment]
DOCX formatting looks good @briri - no changes there.

for the PDF please make same changes as those requested for Public DMPs PDFs #712 :
- reduce left and right margins
- reduce font size
- revise footer text as follows: "Template created using the %ApplicationName%. Last modified %Date%."

**Comment by stephaniesimms** [comment]
files look good @briri - please just remove the time from "Last modified" in the footer (screenshot below). date is sufficient.

![screen shot 2018-01-31 at 4 28 29 pm](https://user-images.githubusercontent.com/12703638/35654839-d2d9def4-06a3-11e8-8e3e-f9e30636c1dc.png)

**Comment by stephaniesimms** [comment]
there's a funny line in the middle of the NSF EAGER PDF but that appears to be bad/old data. downloading newly created public plans looks good. closing issue.

**Comment by sjDCC** [comment]
I'm not able to export to PDF (error thrown)
![pdf-export](https://user-images.githubusercontent.com/6169940/36148313-7609a3f2-10b3-11e8-9e63-7ef25c1613d9.PNG)

It does download to docx though and I have a small request for change here. Can the question text be aligned with the section headings and answers please. Not sure why it is inset. 

![doc-export](https://user-images.githubusercontent.com/6169940/36148263-452fbafa-10b3-11e8-8e23-4791402df0ad.PNG)

I think indenting can work for the guidance text (as in your AHRC template screengrab above) but I'd like the actual question to be left-aligned with the other key elements.

**Comment by stephaniesimms** [comment]
formatting abilities are somewhat limited because of the gem but @briri can advise. I just wanted to follow up and request that we try to fix the hyperlinks in DOCX download too. after lots of data editing and downloading recently i noticed that they all look bad with extra long underlining (see screenshot "Datacite organisation")

![screen shot 2018-02-12 at 4 48 29 pm](https://user-images.githubusercontent.com/12703638/36160679-9e81ce58-1096-11e8-9c40-79160a508323.png)

**Comment by sjDCC** [comment]
We've had that url problem before. I think @xsrust may have fixed it previously so can possibly help. 

The indenting should be fine to correct I think, as this will be a setting we have predefined.

**Comment by briri** [comment]
@sjDCC I can't recreate indented question text you noted above. The ones I looked at were not indented. Perhaps its just bad data roadmap-stg is really out of sync.

**Comment by stephaniesimms** [comment]
created new issue to fix link formatting post MVP #1185 - closing this issue.
