### ISSUE TITLE
Duplicate DOM element ids on Edit Profile page

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1009]
Receiving the following error in the console on the Edit Profile page:
![screen shot 2018-01-08 at 11 57 52 am](https://user-images.githubusercontent.com/1204467/34689667-33967e64-f46b-11e7-88a3-a7075d60096d.png)

**Comment by sjDCC** [comment]
Have tested this and the console tab remains empty when refreshing on firefox and chrome. Thanks @jollopre for explaining how to check. Closing out

![console-empty](https://user-images.githubusercontent.com/6169940/34942373-5ac3f0a0-f9ef-11e7-89b7-028aa7cbd1b9.PNG)
