### ISSUE TITLE
Reinstate + to expand accordions on template pages

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1011]
With Bootstrap we seem to have lost the + signs to expand accordions on template pages - it's not clear to users that they have to click to expand sections. Please reinstate the + on the right side of the section bars in the screenshots below (e.g., on "Data Management Plan" bar under Template details and on subsequent page for sections 1-5):

![screen shot 2018-01-08 at 1 27 28 pm](https://user-images.githubusercontent.com/12703638/34693391-2e573ef4-f478-11e7-9970-94fd2aa12464.png)

![screen shot 2018-01-08 at 1 28 49 pm](https://user-images.githubusercontent.com/12703638/34693377-1e142bc4-f478-11e7-8d49-ecada32063a1.png)

**Comment by stephaniesimms** [comment]
+ signs look good on main template editing page @xsrust . can you also add one to the "Template details" tab so users know they can expand the "Data Management Plan" bar in the first screenshot above?

**Comment by xsrust** [comment]
+/- added to template details page in above commit

Expand/collapse all to be refactored in #1092  So I suggest adding it within that ticket

**Comment by stephaniesimms** [comment]
all looks great now. i don't see a need for refactoring since everything works as expected. closing this issue.

**Comment by sjDCC** [comment]
Looks good. Removing from board
