### ISSUE TITLE
Should not show Org Plans if user belongs to default other org

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1012]
If a user is associated with the default `is_other = true` Org (e.g. 'Other' for DMPonline and 'Non Partner Institution' for DMPTool) they should NOT see the Organisational Plans table on their dashboard page

![screen shot 2018-01-08 at 1 30 49 pm](https://user-images.githubusercontent.com/1204467/34693439-60489b60-f478-11e7-98ce-36ba63c950cd.png)

**Comment by stephaniesimms** [comment]
@briri - I'm not seeing an Org table at all now. to recreate/test I just created a plan for Univ of Edinburgh and set to Org visibility (screenshot below). when I sign in as a different user w/the same Org affiliation there's no Org table on My Dashboard.

![screen shot 2018-01-11 at 12 37 45 pm](https://user-images.githubusercontent.com/12703638/34846205-457440c2-f6cc-11e7-88b3-8f89b49114dd.png)

**Comment by briri** [comment]
@stephaniesimms  I think it may be a case of both user's being collaborators on the plan. If it appears in the table at the top we currently don't show it in the table below.

I just tested on Roadmap stage with a plan that is not shared with anyone and it seems to be working. Please let me know if this plan shows up when you log in.
![screen shot 2018-01-11 at 2 40 46 pm](https://user-images.githubusercontent.com/1204467/34851173-bc836ab0-f6dd-11e7-912b-ced558dc4fe9.png)

**Comment by stephaniesimms** [comment]
I see your plan @briri ! the previous test was a brand new plan w/a single owner and I'm still not sure why you can't see it in this same table. i just created another UoE plan w/a different user account, set it to Org visibility, and it's still not showing up... maybe if i try testing under a different Org...
 
![screen shot 2018-01-11 at 3 22 08 pm](https://user-images.githubusercontent.com/12703638/34852394-3f29851c-f6e3-11e7-995c-f09a2a9cd56d.png)

**Comment by stephaniesimms** [comment]
working as expected now. closing issue.
