### ISSUE TITLE
Status (Progress bar) restructuring

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#103]
Status both refreshes the page and shows pages left but currently generates lots of queries.

**Comment by raycarrick-ed** [comment]
First draft of fixing this in
https://github.com/DigitalCurationCentre/roadmap/commit/a43aaa884e913e5ec7c75f8ffa577b9c35b7280d

This reduces the number of queries to 3 for the plan.status where it was nearer 25-50 depending on the plan. Will need revisited at some point but this will do for now.

**Comment by stephaniesimms** [comment]
Performance of plan page is lightning fast compared to pre-refactoring and status bar is working as expected. Closing this issue.
