### ISSUE TITLE
Revise email text for Org visibility

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1035]
Please make the following one-word change to the auto-email that we send when a user selects "Organisation" visibility:

(full email text in screenshot below) in the first line after the salutation, change "institutional" to "organisational"

![screen shot 2018-01-11 at 1 22 01 pm](https://user-images.githubusercontent.com/12703638/34848167-ac843492-f6d2-11e7-8804-f71edc52cac7.png)

**Comment by sjDCC** [comment]
All fixed. Thanks @jollopre Closing out
