### ISSUE TITLE
Template visibility settings incorrectly displaying on institutional templates 

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1042]
We added template visibility settings under 'edit template details' but my understanding was that these were only to apply to funder templates, not all templates. It was added for the USGS use case where the funder has public and internal-only templates.

This is what is currently seen. 
![template-visibility](https://user-images.githubusercontent.com/6169940/34941453-b0f2a984-f9eb-11e7-9482-37322dd67222.PNG)

The guidance and tooltip don't make much sense as we only list funder templates on the public 'DMP Templates' page, not all institutional templates. We also don't want to make institutional templates private or internal-only which checking this box would indicate. If a user from another organisation wants to use the Edinburgh template (e.g. if a collaborative project was being led from there) they should be able to access the Edinburgh template, despite not belonging to that org

I also noticed that any actions on the template page take you back to the 'All templates' tab which is a bit annoying when you're editing the 'X (organisation) templates' or 'Customisable templates' content. It would be best if you were redirected back to the tab that was active on page refresh. 

![capture](https://user-images.githubusercontent.com/6169940/34945968-f42e6a2e-f9fc-11e7-8687-4d342707c51a.PNG)

**Comment by stephaniesimms** [comment]
the tickbox only appears on org/funder templates (e.g. USGS). not on institutional templates. i think this is working as expected now. closing issue but leaving on board for @sjDCC to verify.

**Comment by sjDCC** [comment]
The institutional templates don't have the tickbox any longer which is great. Thanks @briri 

The 'view all templates' button still takes you back to the original table view though with the 'All templates' tab selected. It would be better if this worked like a back button (as stated above) so people who were editing institutional templates or customisable templates are taken back there instead. I found I kept having an extra click when I was editing uni templates, which was annoying.

I have reopened the ticket to do this part of it, but if that action is not feasible for some reason, close it out and remove it from board please.

**Comment by stephaniesimms** [comment]
just noting here that @briri confirmed he will address new request to make "View all templates" function as a back button as part of this issue. moving back to in progress.

**Comment by briri** [comment]
once deployed this should fix the issue with the 'view all templates' button not remembering what tab the user was on

**Comment by stephaniesimms** [comment]
working as expected now. closing issue.

**Comment by sjDCC** [comment]
Looks great - thanks @briri Removing from board
