### ISSUE TITLE
Legacy downtime message

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1044]
When testing #1009 I came across some legacy html warning text

![legacy-html-warning](https://user-images.githubusercontent.com/6169940/34942434-89b1f470-f9ef-11e7-9cd7-8ffafb0d0153.PNG)

This appeared when the page was refreshed when inspecting the element on 'edit profile'. It's hidden from the user but should probably be deleted just in case since it's referring to downtime in 2015.

**Comment by vyruss** [comment]
Merged, I think we can close this one
