### ISSUE TITLE
Editing/customising templates in multiple browser tabs breaks versioning

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#1050]
This is something that has appeared in `roadmap/master` code in the past, we need to check if it happens with `roadmap/development` (MVP) too

**Expected behaviour:** Ability to edit templates in multiple browser tabs

**Actual behaviour:** Tabs edit different "versions" of the same template, annotations "vanish" as they belong to the other version.

**Steps to reproduce:**  Customise a template and open a second browser tab customising the same template?

**Comment by jollopre** [comment]
The latest changes ONLY create a new template if the latest template version is published. Bear in mind that this action is not thread safe and therefore we can end up creating multiple versions (see line https://github.com/DMPRoadmap/roadmap/blob/development/app/controllers/org_admin/templates_controller.rb#L69)

Note, this action is addressing more than one responsibility and we should refactor the piece that creates a new version and redirect to that newly created version when the current template is published.

**Comment by briri** [comment]
will be addressed as part of #1340
