### ISSUE TITLE
Add search bar above remaining tables

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1051]
A search should be applied above the following tables:

- Public  DMPs page
- Organisation tables (super-admin view) - page to come?
- themes (super-admin page)
- guidance (replace existing filter box)
- plans (on admin side not front end) - replace existing filter box

This is the same as was done in ticket #815 

Adding a search on the templates table is already covered in #1026

**Comment by stephaniesimms** [comment]
ah. i didn't find this on the project board and created a duplicate issue. closing this one, replaced by #1055
