### ISSUE TITLE
Create Super Admin page to manage Orgs

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1056]
Add a page "Organizations" in the Admin menu for users with Super Admin privileges (screenshot 1). Super Admins need to be able to see a complete list of Orgs, create new Orgs, and manage basic info. When a user clicks the "Create Organization" button they should be taken to the Org details page (screenshot 2) where they can add/save a new Org. 

This same Org details page can then be edited by users from that org w/Org Admin privileges. But the Org Configuration details (Shib) section at the bottom will be grayed out and read only for Org Admins (only Super Admins can edit this info).

Make sure to implement same pagination and search box logic if the list exceeds 10 records #1055 

Two notes though based on how it currently works in DMPonline:
1. The org type should display textual categories (i.e. 'funder' 'institution') to select from. Currently we just have codes for each 0, 1 etc
2. The only mandatory field on creating an org should be 'name'. Previously you were forced to enter a contact email to save changes but this may have been removed now.

1 - Organizations page
![screen shot 2018-01-17 at 7 19 59 am](https://user-images.githubusercontent.com/12703638/35050103-df99f442-fb56-11e7-9a4d-c0c3aea6aeb8.png)

2 - Org details page
![screen shot 2018-01-17 at 7 26 10 am](https://user-images.githubusercontent.com/12703638/35050531-e88e313e-fb57-11e7-82ed-9112747dee8d.png)

**Comment by sjDCC** [comment]
Sounds like it captures the main functionality to me. Two notes though based on how it currently works:
1. The org type should display textual categories (i.e. 'funder' 'institution') to select from. Currently we just have codes for each 0, 1 etc
2. The only mandatory field on creating an org should be 'name'. Previously you were forced to enter a contact email to save changes but this may have been removed now...

**Comment by stephaniesimms** [comment]
looking good @briri - some things i noticed while testing that need attention:

- when creating a new Org 3 fields should be required and marked with an asterisk: Org full name, Org abbreviated name, and at least one Org type (e.g. Institution). Currently I can create an Org w/only the full name.
- I tested on both roadmap and stage and like that I can select two Org types for, e.g. USGS. but the behavior is strange here - if i tick two boxes (e.g. Funder, Org) and click Save it only saves one selection. but if I tick all three boxes and click Save it saves 2 selections. desired behavior is to allow Super Admins to make a selection of Funder, Org and save this on the first attempt.
- for Super Admin users it would be nice to have a Back button to return to the main list of Orgs. If it's low effort, please add a "View all organisations" button on the upper right of the Org details page.
- again if it's low effort add sorting to "Organisation" column using the first word of the Org in the main Orgs table (like Jose did for first name in Users table). but only if it doesn't cause problems w/searching the full table content - see related bug issue

**Comment by stephaniesimms** [comment]
mostly working as expected now @briri - two things that need attention:
- please add asterisks to the mandatory fields: Org full name, Org abbreviated name, Org type
- As a Super Admin I can't edit my own Org. I get the error msg below when I try to Edit the Univ of Edinburgh.

![screen shot 2018-02-01 at 9 22 55 am](https://user-images.githubusercontent.com/12703638/35693109-026693f4-0732-11e8-8633-b7d783932f54.png)

**Comment by briri** [comment]
I'm reluctant to add asterisks for required fields to this specific page since we're not doing that elsewhere. Is this something we want to have for any required field across the site?

**Comment by stephaniesimms** [comment]
yes it is and i though we had implemented it ... apologies if i haven't noticed the omission elsewhere. ok hold off for now and we can make a decision to do a global implementation of asterisks later.

**Comment by sjDCC** [comment]
We did used to have asterisks on the edit profile page but these seem to have been lost 

![capture](https://user-images.githubusercontent.com/6169940/35859799-5e037b54-0b39-11e8-8c20-a7c9905ed8cc.PNG)

**Comment by stephaniesimms** [comment]
sounds good to me @sjDCC. @briri please address the first two bullets above.

**Comment by briri** [comment]
They were removed at some point when we started bootstrapping. We should be able to make it happen site wide by adding a CSS `[aria-required]:before { ... }` rule.
Do we want to have them appear before or after the label text? (e.g. 'Organisation *' vs '* Organisation')

**Comment by stephaniesimms** [comment]
Edinburgh org data is working now - no more error. But none of the filters work for table columns @briri . Can you confirm if these are being addressed by another issue? If so we can close this one.

**Comment by sjDCC** [comment]
I searched orgs and then reordered data and it worked on so I think this is good to close out. By all means reopen though if not
