### ISSUE TITLE
Ability to remove Annotations when editing Templates

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#1063]
We are currently not able to delete an Annotation that has already been entered when editing a Template's Questions:

**Expected behaviour:** Removing the text from an Annotation should make it go away when the Question is saved.

**Actual behaviour:** Template reloads, and Annotation is still there.

**Steps to reproduce:** 
1. Edit Template
2. Edit Question that has Annotation
3. Delete Annotation text and save

**Things to consider:**
* It's better to replace the text with a blank string (`''`) rather than delete the original Annotation (that way we can recover user mistakes from the DB - which is a request we often get).
* If the above is implemented, we need to insert logic that ignores empty Annotations, so we don't get an annotation with no text appearing during Template preview/Plan editing.

EDIT: @jollopre has found the culprit: https://github.com/DMPRoadmap/roadmap/blob/development/app/controllers/questions_controller.rb#L55

**Comment by stephaniesimms** [comment]
deleting annotations is working as expected now. closing issue.

**Comment by sjDCC** [comment]
Looks good - removing from board
