### ISSUE TITLE
Duplicate DOM ids for home page

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#1064]
Please complete the following fields as applicable:

**Expected behaviour:**
DOM ids must be unique across the entire page
**Actual behaviour:**
![dom](https://user-images.githubusercontent.com/7393044/35148536-791caad8-fd0a-11e7-8fbb-308e4f88ec48.png)

**Steps to reproduce:** (for Chrome)
1. Right click mouse
2. Click inspect
3. Go to home page for a non-login in user

**Comment by stephaniesimms** [comment]
looks good upon inspection. closing issue.
