### ISSUE TITLE
Migration step 2 fails

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#107]
Ran into the following issue when running the second migration step:
```shell
Brians-MacBook-Pro:roadmap briley$ rake db:migrate
rake aborted!
Could not load configuration. No such file - /Users/briley/Documents/workspace/roadmap/config/branding.yml
/Users/briley/Documents/workspace/roadmap/config/application.rb:100:in `<class:Application>'
/Users/briley/Documents/workspace/roadmap/config/application.rb:21:in `<module:DMPRoadmap>'
/Users/briley/Documents/workspace/roadmap/config/application.rb:20:in `<top (required)>'
/Users/briley/Documents/workspace/roadmap/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by briri** [comment]
Got past it by creating an empty branding.yml. It then failed because mysql2 is not a part of the Gemfile. I think we need to add it back since most existing installations will be using mysql2
```shell
Brians-MacBook-Pro:roadmap briley$ touch config/branding.yml
Brians-MacBook-Pro:roadmap briley$ rake db:migrate
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at /Users/briley/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/less-rails-2.7.1/lib/less/rails/railtie.rb:15)
rake aborted!
Gem::LoadError: Specified 'mysql2' for database adapter, but the gem is not loaded. Add `gem 'mysql2'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
/Users/briley/Documents/workspace/roadmap/config/environment.rb:9:in `<top (required)>'
Gem::LoadError: mysql2 is not part of the bundle. Add it to Gemfile.
/Users/briley/Documents/workspace/roadmap/config/environment.rb:9:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

**Comment by briri** [comment]
Uncommented the mysql2 gem in the Gemfile and things began working properly.

**Comment by briri** [comment]
I'm not sure of the best approach to splicing these back into the commit history now that they've been tagged. You can re-point a tag at a different commit and I think you can also go back and revise a commit but I've never done that before so can't recommend the best course of action.

I think others though are likely to encounter the same issue. I ran this today on my laptop. I'll run again tomorrow on my work machine to see if I get the same errors

**Comment by briri** [comment]
This was unfortunately an issue again when running through the steps on my work machine so we should decide how to address it. 

I think its ok to add a 'touch config/branding.yml' line to the instructions for the first bit but we should probably un-comment the mysql2 gem. If we're going to make changes to the git history then we should probably just add a stub branding.yml in. I noted that the file existed in the old_schema tag and then disappeared when switching to the transitional_schema tag.

**Comment by vyruss** [comment]
see #108 for possible course of action

**Comment by briri** [comment]
Added a pkey to the users_perms table:
  https://github.com/CDLUC3/roadmap/commit/9682648804aaf808496fe79712acd68242d82797

**Comment by briri** [comment]
Closing this one since we've been discussing the entire migration process steps1-3 in #108
