### ISSUE TITLE
Remove Advanced Table Properties in text editor

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1079]
The "Advanced" tab in the Table properties editor for TinyMCE is not useful. Most users won't know what to input in these fields anyway. If possible we should remove this tab, if @sjDCC agrees

![remove-advanced-table](https://user-images.githubusercontent.com/12703638/35362784-a7208750-011b-11e8-912c-320d5ed83e06.png)

**Comment by sjDCC** [comment]
I've never noticed this to be honest and assumed you'd need to enter some code for colours but I tested with words and it worked.

![capture](https://user-images.githubusercontent.com/6169940/35480575-f849451e-0408-11e8-9fb4-2fb620e78646.PNG)

I can't really see any reason why people would need this, but equally it's intuitive to use and isn't really worth our time to remove when it's there by default.

I'm going to just close this out as I don't think it's worth wasting time on for MVP.

**Comment by stephaniesimms** [comment]
i also assume that it wanted me to input something tricky here and had no idea what to do when confronted with these options. since you figured it out and it's working appropriately i agree that it's not needed for MVP. will reopen the issue and retain it as a suggestion for post MVP in the event that others have trouble.

**Comment by sjDCC** [comment]
If we're able to adjust that page, perhaps all we need to do is add a tooltip that people should just enter colours e.g. 'red'

**Comment by briri** [comment]
I think this is no longer and issue (at least I can't find the advanced settings on the write plan tab). Is it ok to close @sjDCC and @stephaniesimms ?

**Comment by stephaniesimms** [comment]
yes ok to close @briri
