### ISSUE TITLE
Org/funder template flag not working as expected

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1083]
I did some more testing on DMP stage @briri and found the following problems when trying to set the "for internal use only" flag on the USGS templates. the setting does not stick and wires appear to be crossed somewhere. it was definitely working at one point so i'm not sure what changes introduced this bug:
- if I tick the box "for internal use only" on the edit template details page and click Save I get a message that my changes were saved. but after I publish the changes, then go back to the template details page I see that the template is available to the public (screenshot below). when i click to edit template details, the box is no longer ticked so it appears to not be saving this setting anymore.
- also all USGS templates appear in the public DMP Templates list regardless of my attempts to set them to internal visibility
- but when i try to create a new plan I can only get the public USGS template despite all templates appearing in the public list and regardless of setting my Org affiliation to USGS (screenshot 2)

![screen shot 2018-01-25 at 12 44 38 pm](https://user-images.githubusercontent.com/12703638/35411418-86ea9b12-01cd-11e8-834e-8c95402a66ce.png)

![screen shot 2018-01-25 at 12 46 46 pm](https://user-images.githubusercontent.com/12703638/35411492-d5b7d214-01cd-11e8-9dbc-04ccd58080f4.png)

**Comment by briri** [comment]
hmm ok. it might be versioning the template when the box is ticked. I'll take a look

**Comment by stephaniesimms** [comment]
i still don't really understand what triggers a new version. i thought we could edit template details and not have to create and publish a new version. but that doesn't seem to be the case here...

**Comment by stephaniesimms** [comment]
this is working as expected now. I can make changes to template details w/o creating a new version and having to publish the changes. And the DMP Templates list reflects the changes automatically. Create plan logic is working as expected now too - I get the appropriate mix of public and/or internal templates based on Org and Funder selections for USGS. thanks @briri ! closing issue.

**Comment by sjDCC** [comment]
I did a test of the whole workflow for USGS too and this works fine. Am also happy with the 'template details' being editable without creating a new version as it's only metadata and links

Removing from board
