### ISSUE TITLE
Replace "Institution" w/ "Organisation"

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1085]
There are some artifacts of my indecision re institutions and orgs. Now that we decided to go with orgs, we need to make sure the language is consistent in the UI. I noticed at least one place where we need to change "Institution" to "Organisation" (in the Visibility column on My Dashboard, screenshot below). @sjDCC - please note if you find any other occurrences.

![institution-org](https://user-images.githubusercontent.com/12703638/35413711-3349c50c-01d5-11e8-820c-3e6ad8966baa.png)

**Comment by sjDCC** [comment]
Will do. Are the devs able to do a query of the code to see where institution displays in UI too? If not we can just spot and change as we go through.

**Comment by stephaniesimms** [comment]
find and replace is complete. you should confirm if you want all references to "institutional credentials" changed to "organisational credentials" @sjDCC (screenshots below of DMPonline sign in vs. roadmap). dmptool is using a custom workflow so this doesn't affect it. there are some other places where it might not be appropriate to replace institution w/org (e.g., text on the About page) but i didn't notice anything else that requires immediate attention.

![screen shot 2018-01-29 at 10 17 54 am](https://user-images.githubusercontent.com/12703638/35527088-6b8d9806-04de-11e8-9f46-f50f8c3a97a1.png)

![screen shot 2018-01-29 at 10 18 25 am](https://user-images.githubusercontent.com/12703638/35527092-6ffe394a-04de-11e8-8a42-44cbe6ef934b.png)

**Comment by sjDCC** [comment]
We shouldn't replace "institutional credentials" with "organisational credentials" so please override the find>replace in this case

**Comment by stephaniesimms** [comment]
"institutional credentials" is reinstated for login and profile pages. closing issue.
