### ISSUE TITLE
Delete phase does not ask for confirmation

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#1089]
Please complete the following fields as applicable:

**Expected behaviour:**
When clicking in delete phase within a template editing, a confirmation message should be displayed.
**Actual behaviour:**
Clicking in delete action destroys the phase for a template
**Steps to reproduce:**
Explained above

**Comment by sjDCC** [comment]
Where is the delete phase button @jollopre I've only been able to edit not delete

![delete-phase](https://user-images.githubusercontent.com/6169940/35825400-9c5042b6-0aad-11e8-89d3-b4f9c154c26a.PNG)

**Comment by jollopre** [comment]
You can see the delete action on the template details page where an overview of phases for that template is displayed. Note, the action is only visible if that phase has been marked as modifiable.

![phases](https://user-images.githubusercontent.com/7393044/35852640-54a417e6-0b23-11e8-8fcd-f24751ab7483.png)

**Comment by sjDCC** [comment]
Great, I see it now! Had actually been planning to raise a ticket to add a 'delete phase' button as I couldn't find a way to do it ;-)

You're right that this action needs a confirmation

**Comment by stephaniesimms** [comment]
confirmation message working as expected now. closing issue.
