### ISSUE TITLE
Make First & Last Name mandatory in User Profile

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#109]
U of Melbourne have asked us to make entering a First & Last Name mandatory in User Profile.
- Is this something we want by default or do we make it a per-installation setting?

**Comment by stephaniesimms** [comment]
this is going to be part of the new account creation process. after registering, the user will be driven to their profile page to enter First Name, Last Name, backup email.

**Comment by sjDCC** [comment]
I agree this should be default. It hasn't been mandatory in DMPonline though so we perhaps need to prompt users to enter on first sign in post-migration? Or does it not matter is some data are missing values?

Also, should entering names be part of sharing plan, or do we leave this as email only and just ask the user to enter names when they register?

**Comment by sjDCC** [comment]
Since this will be part of the UX redesign, I'm removing it from this sprint / project board. It's not needed for DCC to migrate services to roadmap code

**Comment by briri** [comment]
this is related to #344

**Comment by stephaniesimms** [comment]
this is working as expected

**Comment by sjDCC** [comment]
Works fine. Users are forced to add these details on account creation and can't save profile if fields are blank. Closing out.
