### ISSUE TITLE
User is only able to open the 1st phase of a plan

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1091]
The user is not able to open all of the phases on the plan edit screen. Regardless of which phase tab they click on they are brought to the first phase.

The following line needs to be updated:
https://github.com/DMPRoadmap/roadmap/blob/1659587387f27127b0b5c19f017ce6feae9b55bd/app/controllers/phases_controller.rb#L15

This issue affects the master branch only.

**Comment by stephaniesimms** [comment]
per mtg on 30 Jan @xsrust may have submitted PR that fixes this issue in DMPonline. cross check to verify.
