### ISSUE TITLE
Refactor expand all/collapse all

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1092]
Update the expand all/collapse all functionality
- refactor the html code into a sharable partial
- update JS so that 'expand all' is not visible if elements are already expanded and 'collapse all' is not visible when all elements are collapsed

**Comment by stephaniesimms** [comment]
@briri - i just tested related issue #1081 and everything looks great and is intuitive for users. i don't see the need to hide one or the other link. this seems like a trivial optimization - maybe remove MVP label if it's something you really think we need?
