### ISSUE TITLE
Add privileges info to profile page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1094]
As an admin my privileges aren't listed anywhere that I can see them. In the DMPTool we list them on the user profile page (screenshot 2 below "My roles") - it seems like the best place for Roadmap too unless @sjDCC has another suggestion?

If a user has admin privileges, then display an extra field below "Language" on the Edit Profile page for "My privileges" and list "Organizational Admin" or "Super Admin" (same as on the User accounts page under Admin menu)

1 - Roadmap Edit profile page
<img width="730" alt="screen shot 2018-01-26 at 2 30 28 pm" src="https://user-images.githubusercontent.com/12703638/35463443-8118fffc-02a5-11e8-85a7-af6644f2a06c.png">

2 - DMPTool profile page
<img width="854" alt="privileges-profile" src="https://user-images.githubusercontent.com/12703638/35463414-5682c44e-02a5-11e8-88e7-1eaa3ff2a617.png">

**Comment by sjDCC** [comment]
What is this functionality for? If it's just to display permissions I'm fine with that but I don't want users to have the ability to edit their own as we're likely to get helpdesk tickets from inadvertent removal ;-)

Edit profile page makes most sense for this. Happy for it to be post MVP if we're pushed on time. It's not an essential.

**Comment by stephaniesimms** [comment]
@sjDCC - yes this is just to display permissions. all of the functionality for granting permissions is in place and working well on the admin user accounts page. devs can confirm but this should require minimal effort, which is why i included for MVP.

**Comment by sjDCC** [comment]
sounds good

**Comment by stephaniesimms** [comment]
this looks good. closing issue.
