### ISSUE TITLE
Search doesn't work as expected for tables w/concatenated sorting

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1101]
It seems that adding the filter function for the Name column (filter by first name) in the users table (screenshots below) prevents being able to search by the full name. Desired behavior is to be able to search by first and last name, or any other text for a given record in any table. 

If it's not possible to have both the filter/sort function and search the full name, I would prefer that users be able to find what they're looking for using the search box (so remove the filtering if we can't have both).

1 - searching by first and last name returns nothing
![screen shot 2018-01-30 at 6 50 12 am](https://user-images.githubusercontent.com/12703638/35572995-b5fe8da8-058a-11e8-89f2-29cf5b5801e6.png)

2 - searching by first name only
![screen shot 2018-01-30 at 6 50 39 am](https://user-images.githubusercontent.com/12703638/35573006-b8d98d5c-058a-11e8-8333-55b555e217b3.png)

**Comment by jollopre** [comment]
The search mechanism now looks for firstname<space>surname combination when a search term is inserted.

Note, the sorting of "Name" column is still tight to firstname ONLY. If we want to sort by the combination firstname/surname we will need to:

- Create a scope method at models/user.rb that sorts by firstname surname
- Extend the paginable concern to sort against scope methods apart from field's sorting

**Comment by stephaniesimms** [comment]
this is working as expected now. we only need to sort by first name. but great that i can now search by any combination of first, last, first+last. closing issue.

**Comment by sjDCC** [comment]
Search is working nicely. Thanks @jollopre Removing from board
