### ISSUE TITLE
Cannot sort columns when tables are expanded

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1105]
Paginated tables appear as expected, alphabetized by the first word in the first column. But if I click "View All" to expand the list the ordering gets shuffled (screenshot below). Then if I try to sort any of the columns, the table reverts back to a paginated view.

Desired behavior is to retain the original alphabetized order when a user clicks "View All". In addition a user should be able to sort columns while viewing the expanded list. There are only a few tables where the number of records is so large that this action will be slow (e.g. Super Admin tables of users or plans). We need to fix this to improve usability for the majority of users.

![screen shot 2018-01-30 at 10 24 49 am](https://user-images.githubusercontent.com/12703638/35583850-0caa15f6-05a8-11e8-8213-8862c7e0e273.png)

**Comment by sjDCC** [comment]
Happy for this to be done and if we find it has a big performance hit, we can rethink later. 

The org users and plans tables are going to get quite long too so there may be more non-super-admin cases than we first expect.

**Comment by jollopre** [comment]
This ticket will address:
- Retain View All (if enabled) when sorting is requested
- Add default sorting to paginable concern if no sorting request is made

**Comment by stephaniesimms** [comment]
sorting is working beautifully for all tables now. a word of caution for @sjDCC - as a Super Admin we can't 'View All' to expand the lists for Users and Orgs (these queries overload things and blow up the server). I'll create a post MVP issue to handle them separately.

**Comment by sjDCC** [comment]
Noted!
