### ISSUE TITLE
Restrict Sign-Up dropdown to one Organisation

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#111]
U of Melbourne have asked us to restrict Sign-Up dropdown to just UoM.
- Currently this does not exist in Roadmap code tree.
- Could be implemented as a per-instance setting with a list of allowed values?

**Comment by briri** [comment]
shelving this one for now. the create account form no longer has an org dropdown. If there is really a need to restrict the list, then they could use the new shibboleth discovery service feature and modify the controller to pass the user through to the single org via a check on the number of org's who's shib entityID is registered in the new org_identifiers table

**Comment by vyruss** [comment]
Melbourne specifically doesn't have Shibboleth but since the workflow is redesigned, I agree this is no longer as relevant. What we do need though is a way to create accounts with a default affiliation.

**Comment by vyruss** [comment]
@briri Not really, closing
