### ISSUE TITLE
Users can overwrite each others changes to template phases/sections/questions

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1111]
If you log in as 2 different users and edit the same template you are able to overwrite your own changes. For example:

- UserA logs in and edits the first question on TemplateOne
- UserB logs in and edits the same question on TemplateOne before UserA saves their changes
- UserB saves their changes
- UserA saves their changes

In the scenario above UserB's changes are lost because they were overwritten by UserA's copy of the template content. We would ideally switch to auto-saving on this page and introduce a locking message like we have done on the plan edit page.

For now though, as a short term aid to help prevent this edge case we should add a message to the screen to let the user know that someone else has/is editing the same template phase.

**Comment by briri** [comment]
Added a method that records which users are editing a phase and stores them in the Rails.cache for 15 minutes. The user is then presented with the following message and the responsibility is left to them to coordinate with the other admin.

![screen shot 2018-01-31 at 2 11 43 pm](https://user-images.githubusercontent.com/1204467/35650759-1086bbc6-0692-11e8-832c-72637bd5e4b0.png)

Caveat: All cache information is likely lost when restarting the Rails server

**Comment by stephaniesimms** [comment]
I think this is a decent solution @briri and it works as expected. Can you just revise the msg text and make it an error color (red or yellow or whatever we're using for non-success actions):

- Warning: Brian Riley also appears to be editing this phase! Your changes may not be saved.
- change message color and make it an "x" instead of a checkmark
