### ISSUE TITLE
Resolve "Sign in" vs "Sign up" confusion

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#112]
Annotating original issue w/ up to date UX Wireframes @JEK-III  - http://h90c3m.axshare.com/#g=1&p=home

New language is: Sign in / Create account
Related issue #305 

Support staff has reported a number of users have been confused by the similarity between _Sign in_ and _Sign up_ and create unnecessary helpdesk calls.
- This will only get worse as the tool(s) see more usage.
- Propose new lingo for this, such as:
  - _Log in_ and _Sign up_
  - _Log in_ and _Register_

**Comment by stephaniesimms** [comment]
the UX team is working on this as we speak. we can review which MVP features we asked them to assess/redesign for us. they're documented in Pivotal — we'll be transferring those tickets over to GitHub Issues asap.

**Comment by briri** [comment]
From pivotal ticket: https://www.pivotaltracker.com/story/show/132209329

"During accessibility testing, it was noted that the registration to first login to profile view flow is complicated involves email validation and unnecessary field entry. Re-think flow of activities so that users can have a streamlined entry experience when registering and using Roadmap for the first time."

Here is link to wireframes (http://h90c3m.axshare.com/).

**Comment by vyruss** [comment]
As beta testing date draws closer, can I propose that for now we replace verb "Sign Up" with "Register" which is unambiguous and will help non-native English speakers who use the site in English? 

Reference: http://uxmovement.com/buttons/why-sign-up-and-sign-in-button-labels-confuse-users/

**Comment by stephaniesimms** [comment]
UX Wireframes recommend "Create Account" - http://h90c3m.axshare.com/#g=1&p=home 
This is not an immediate priority and will be addressed for the larger MVP

**Comment by stephaniesimms** [comment]
"Sign In / Create Account" language should also be used for the link in upper right corner on appropriate public pages (screenshot)

![screen shot 2017-06-05 at 12 14 56 pm](https://cloud.githubusercontent.com/assets/12703638/26799343/05e03a72-49ea-11e7-9ca2-9ef47d8cec51.png)

**Comment by briri** [comment]
It now says 'Create account' on the new sign in/create account workflow pages.

@vyruss I just submitted a PR that replaces them all for you on the development branch.

**Comment by stephaniesimms** [comment]
there is some potential for confusion when following the links to Sign In or Create Account in the upper right corner. If a new user selects Create Account, they won't be presented w/the option to sign in using institutional credentials. it might be necessary to drive them to the homepage instead where they can see both options (sorry @briri , now that you got the modals working...) . 

we also need to add some guidance to prevent users from selecting "Create Account" when they might have the option to sign in with institutional credentials. we handle this in the DMPTool by collapsing the process into a single "Login" workflow ... step 1 is to select your institution and the appropriate sequence follows from there depending on whether Shib is enabled. 

@sjDCC For DMPonline users, does everyone have Shib/institutional credentials?

**Comment by sjDCC** [comment]
I think it could get very confusing if we add the shibboleth link to both poup boxes, especially how it's currently phrased, but will defer to @JEK-III on usability.

Currently they see this if they're going to sign in:
![signin-popup](https://user-images.githubusercontent.com/6169940/27081688-79405286-5039-11e7-8cf7-bc32cbe8eb4c.PNG)

And this if they're creating an account:
![create-account-popup](https://user-images.githubusercontent.com/6169940/27081695-7e7f0cc4-5039-11e7-84af-19c962449fa8.PNG)

I guess we want to avoid them creating a basic DMP account (i.e. not using institutional credentials) if we can avoid it. One option might be to add a secondary button / route to the create account popup so there are two options:
1. Create an account using my institutional credentials (effectively same as signing in with them for first time)
2. Standard create account webform to add email, org, password etc

Not all UK users have institutional credentials. Some unis use openathens or other local sign ons that I'm not sure are shibboleth compliant... 

Will you still ask unis to submit LDAP details and once that's done their single sign on works. Do we need to add this step or is the current redirection to UK Access Federation sufficient on our end?

**Comment by briri** [comment]
@sjDCC we setup our filtered list of institutions as something you can turn on/off in the application's configuration. If its turned off it will let shibboleth send you through to the federation. If its turned on it will provide the filtered list of institutions. 
We set that up in the same way we did for users (anticipating orgs needing to have multiple ids for things like crossref, etc.) so we will have a new org_identifiers table. The super admin section will have a way to manage that table and those connections.

**Comment by sjDCC** [comment]
Given that this ticket is mainly about just changing terms, I think it can be closed out. The sign in workflows and SSO still need some work, but that's addressed in ticket #305 Referencing that here so notes from this ticket can be considered there.
