### ISSUE TITLE
Move create plan button to top of table

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1120]
Move the 'Create Plan' button on My Dashboard page so that it appears above the table like we have on other pages (templates, guidances, etc.)

**Comment by sjDCC** [comment]
Hi @briri the button is below the table in every case so closing this out so we keep it consistent

![create-guidance](https://user-images.githubusercontent.com/6169940/35825918-324d68d8-0aaf-11e8-9798-e65c857d4394.PNG)

![create-template](https://user-images.githubusercontent.com/6169940/35825926-38699570-0aaf-11e8-9fa8-ae2d1f3e24b4.PNG)
