### ISSUE TITLE
Error message on downloading PDFs of shared institutional plans

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1126]
Downloading the PDF of plans presented in the shared institutional plan table under 'My Dashboard' sometimes throws a "You are not authorised to perform this action" error.

Perhaps there's a permission issue or something has changed in the visibility of these plans and wrong ones are being presented in the table? 

It only happens on some entries not all

![error](https://user-images.githubusercontent.com/6169940/35859594-a44c0ef6-0b38-11e8-9093-a787f3aaeabd.PNG)

**Comment by stephaniesimms** [comment]
i tested by creating new plans (in case this is a product of bad data) but it still gives me the Error msg (see screenshot below). it seems I can't download any Org plans.

![screen shot 2018-02-14 at 8 57 19 pm](https://user-images.githubusercontent.com/12703638/36241211-ac6b5956-11c9-11e8-8cef-bf3550f51116.png)

**Comment by stephaniesimms** [comment]
seems to be fixed now. i got one error but assume it's bad data. all newer plans are working. closing issue.
