### ISSUE TITLE
Template versioning

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#1128]
Also see related issue #1251 
The current code we have for template versioning is not thread safe, i.e. if more than one thread access simultaneously to the action template#edit, we can end up having multiple template versions with the same version number.

**Expected behaviour:**
A new template version should be created ONLY when **structural** changes are made to any published template. These may be:
- question#update, question#create, question#delete
- section#create, section#delete
- phase#create, phase#delete

In contrast changes made at:
- template#update (title, description, etc)
- phase#update (title, description, etc)
- section#update (title, description, etc)

do not really need to create a new version.

Since the behaviour has to be thread safe and reused in all the structural endpoints above mentioned, I propose the creation of a Rails concern to address this problem.

**Actual behaviour:**
A new template version is created when the current template is published regardless of whether a structural change has been made or not.

**Comment by vyruss** [comment]
Agreed. Additionally:
- Updating a **published** template's title/description, phase title/description, section title/description does not result in a new version
- Making structural changes to a **published** template results in a new draft version ("unpublished changes")
- Making structural changes to a **draft** ("unpublished changes") template does not result in a new version

**Comment by dsisu** [comment]
I think it is becoming urgent we address this issue. Template versioning keeps popping up behind user queries and it takes time to fix errors related to it because it frequently requires manual tweaks in the database.

**Comment by dsisu** [comment]
Hi all, for your info, org admins can now see several copies of a template version. We need to fix this urgently so that users don't lose trust in our data.

![image](https://user-images.githubusercontent.com/2138956/37841228-1eddd7ca-2eb7-11e8-8644-67b91df1afc7.png)

**Comment by stephaniesimms** [comment]
template versioning behaving properly after refactor. closing issue.
