### ISSUE TITLE
Add asterisks beside required fields in forms

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1129]
Required fields in forms (create account, create organization, edit profile) should be marked with a red (or another bright color) asterisk. These were lost during Bootstrapping and need to be replaced throughout the site.

**Comment by briri** [comment]
We should be able to make it happen site wide by adding a CSS `[aria-required]:before { ... }` rule.
Do we want to have them appear before or after the label text? (e.g. 'Organisation *' vs '* Organisation')

**Comment by stephaniesimms** [comment]
awesome @briri - I assume after as in the screenshot below from DMPonline:

![capture](https://user-images.githubusercontent.com/6169940/35859799-5e037b54-0b39-11e8-8c20-a7c9905ed8cc.PNG)

**Comment by briri** [comment]
We now display an asterisk for required fields. There is a separate ticket to make fields required if they are not but should be #1326
