### ISSUE TITLE
Display of bullets in H2020 template

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#113]
The H2020 template includes bullets in the questions. These don't display correctly in the current roadmap code and the html tags show on the plan summary 
![melbourne-h2020-no-bullets](https://cloud.githubusercontent.com/assets/6169940/23409595/0c7ced70-fdc4-11e6-8864-cd30cf80005f.PNG)
![melbourne-h2020-summary](https://cloud.githubusercontent.com/assets/6169940/23409597/0cac202c-fdc4-11e6-977f-85515bad134b.PNG)

**Comment by briri** [comment]
should be able to correct the display issue by using the rails '.html_safe' method

**Comment by xsrust** [comment]
This bug does not appear in the current roadmap codebase on my machine.  
Perhaps it has been fixed since we last updated the code on the live servers?

**Comment by sjDCC** [comment]
Possibly yes. I noticed it when I added the H2020 template to the Melbourne instance yesterday, which is on an earlier version of the roadmap code. This template uses html tags in the question area as this isn't a rich-text box. We did have a hack in place on DMPonline but it's possibly fixed now. Maybe wait til we migrate Melbourne or Tuuli to new code to confirm as both have this problem

**Comment by briri** [comment]
Yes, I believe this was one of the bugs listed in the document @sjDCC and @stephaniesimms created back when we were working on the Rails 4 upgrade over the summer

**Comment by sjDCC** [comment]
@sjDCC to check on staging server

**Comment by sjDCC** [comment]
Checked code on roadmap staging server and this is displaying correctly
