### ISSUE TITLE
Cannot download CSV list of plans

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1138]
Cannot download the CSV list of plans from the org admin plans page if one of the plans was created by a user who's org affiliation in NULL:

![screen shot 2018-02-08 at 2 40 05 pm](https://user-images.githubusercontent.com/1204467/36002220-3af4bfd2-0cde-11e8-9a69-44452cee58d5.png)

**Comment by stephaniesimms** [comment]
this seems to be fixed. i can't find an org that throws an error when i download plans anyway. closing out.

**Comment by sjDCC** [comment]
Could also download for a few different orgs. Removing from board
