### ISSUE TITLE
Upgrade to Rails 5.2

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#114]
This might be a low-priority issue worth looking at after MVP just to avoid obsolescence.
[Upgrading from Rails 4.2 to Rails 5.0](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-2-to-rails-5-0)

**Comment by mxsstrong** [comment]
suggested by @paulwalk to wait for stable release of Rails

**Comment by briri** [comment]
duplicate of #826
