### ISSUE TITLE
Add download button for Usage reports

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1149]
- add a download button for the full CSV reports (at top of wireframe below)
- the full usage report should contain the data itemized below for a user's affiliated Org. in addition we want to provide some insight into global usage for admins to compare against (global numbers represented in lefthand boxes in wireframe - it's more useful to have them on the dashboard than in the CSV report but having both would be great).

Org admins want to know the following (per @sjDCC comments on Edinburgh reports):
* new users per month
* total users for their org
* total DMPs per month
* DMPs per template per month
* evaluate DMPonline/Roadmap API queries for reuse in usage dashboard

![screen shot 2018-01-22 at 4 47 34 pm](https://user-images.githubusercontent.com/12703638/35252260-778a7c40-ff94-11e7-9181-1a03e8d53f87.png)

**Comment by jollopre** [comment]
Since generating a unique CSV enclosing all the topic sounds not sensible, I have decided to generate separated export files for each topic. These buttons are placed right-top above each yearly graph and basically its CSV associated represents the same data. @stephaniesimms and @sjDCC  let me know what do you think...

If you are happy with the changes, I can extend the Usage dashboard to include a third graph for no. plans for each template (from my org) in a yearly basis too.

**Comment by stephaniesimms** [comment]
- revise Export button label to "Download" for consistency
- download works well, but we want to provide the complete history of user and plan data (not just the data for the past year displayed in the graph). please update the CSV reports to include all data for a given Org per month.

**Comment by sjDCC** [comment]
I thought the reports were just meant to be data per month with yearly totals. I think this would be enough rather than all data from beginning of time. We separate the Edinburgh stats out on an annual basis.

**Comment by stephaniesimms** [comment]
hi @jollopre - i missed your note above about adding a third graph for no. plans for each template (from my org) in a yearly basis too. that would be great.

it's a requirement for DMPTool to include all data in the CSV reports (per month since the Org joined). this provides trends for the Org over more than just the past year. and otherwise there's no way for an Org to assess previous year's data without contacting us. so please include everything in the CSVs.

**Comment by jollopre** [comment]
@stephaniesimms, is there any problem if we postpone that big download to after MVP release?

Right now as we wanted something workable, the CSV files are calculated on demand, i.e. any time you press download in any topic, 12 queries to the db are send, one for each month. The ideal solution for this would be to have history tables that are updated automatically each month (e.g. cron job). That would mean that we would reduce from 12 to 1 query, however this is big chunk of work todo right now when multiple bugs addressing basic functionality are still on board.

Can we create a high-priority ticket to implement this after MVC, please?

**Comment by sjDCC** [comment]
As I understand it, the DMPTool approach is to have reports pre-generated each month so these don't need to be done on the fly. That would be better, but agree with post-MVP implementation is your users can wait a week or two for full stats @stephaniesimms?

**Comment by stephaniesimms** [comment]
If this is how the reports are being generated now then we can move the full report to post MVP @jollopre - I assumed it was already one query. will add to the post MVP board. thanks for the explanation.

**Comment by stephaniesimms** [comment]
download buttons are implemented for 2 reports. additional usage dashboard work on post MVP board. closing this issue.

**Comment by sjDCC** [comment]
Looks nice thanks @jollopre We can finesse this post MVP
