### ISSUE TITLE
Revise create plan page

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#116]
UX are drawing up plans for revising this page. Perhaps having multiple pathways in e.g. 
- create a DMP for a funder (fundref look up)
- create a DMP for your institution (choice of one or more uni templates)
- create a plan from an existing one

This issue is just to note that in some cases there's a desire to disable / remove one of the paths e.g. in Canada and Australia where there are no funder templates.

**Comment by briri** [comment]
can we close this one @sjDCC? The fundref idea is captured here #96 and maybe something we'd just want to add to the org details page to allow orgs to identify themselves for us like we do with users and ORCID?

**Comment by stephaniesimms** [comment]
closing this outdated issue.
