### ISSUE TITLE
Implement Autosave throughout the site

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1160]
USABILITY TESTING FEEDBACK
Autosave does not work if you change the title of a plan. Must click submit button. Unclear when you must click Submit button. 

- implement autosave on Project Details page, on Admin pages
- use autosave consistently throughout the site

**Comment by dstuckey-uoe** [comment]
Reviewed by DMPRoadmap team, and decided to close as it is not a priority (plus autosave might be cause of bug in issue https://github.com/portagenetwork/roadmap/issues/789).
