### ISSUE TITLE
Display tooltip below form fields on Create plan page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1161]
USABILITY TESTING FEEDBACK
Only saw tip after he typed… didn’t realize it was for Project Title so he goes back and amends it.
Didn't notice mock project checkbox because it was hidden by tip.
- on create plan page display tooltips below the field instead of out to the right (screenshot)

![screen shot 2018-07-09 at 11 37 55 am](https://user-images.githubusercontent.com/12703638/42469493-c1a1b0f8-836c-11e8-8dce-13db04ecb1ec.png)

**Comment by briri** [comment]
mainly an issue on the create plan page. Display below the field if possible

**Comment by johnpinto1** [comment]
@briri  @xsrust This code is in current development. So I think it should be available for UAT.

**Comment by sjDCC** [comment]
Looks good, thanks @johnpinto1 Closing out
