### ISSUE TITLE
Change links to icons for file download 

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1164]
On DMP Templates, Public DMPs, and Org plans (located on My Dashboard) tables use icons for PDF and DOCX instead of hyperlinks to make it easier for users to identify downloadable items (cf. old DMPTool screenshot 1). For DMP Templates where both file formats are available, display the icons side by side (screenshot 2).

![screen shot 2018-02-14 at 3 47 12 pm](https://user-images.githubusercontent.com/12703638/36234165-7762e6dc-119e-11e8-99c1-b440281c865a.png)

![screen shot 2018-02-14 at 3 43 59 pm](https://user-images.githubusercontent.com/12703638/36234100-192af1e0-119e-11e8-8a4d-66d77f217e59.png)

![screen shot 2018-02-14 at 3 44 15 pm](https://user-images.githubusercontent.com/12703638/36234108-1f4690ca-119e-11e8-8f6e-9405ab5394af.png)

**Comment by johnpinto1** [comment]
@stephaniesimms @sjDCC I have done some preliminary work on this replacing the links with Fontawesome icons which we use for "Download", "Total Users" and "Total Plans" on the Usage page.

![iconsforlinks](https://user-images.githubusercontent.com/8876215/47721813-d7bc5480-dc48-11e8-9e5e-c4e01cd931c4.jpeg)

**Comment by stephaniesimms** [comment]
thanks for implementing the fontawesome icons @johnpinto1 - can you try placing them side-by-side and possibly make them a bit smaller?

**Comment by stephaniesimms** [comment]
I'm not sure if the latest code has been deployed to roadmap stage. The icons on the DMP Templates page are still large and stacked vertically (screenshot). The screenshot @johnpinto1 provided above looks nice - just need this code to be merged and deployed for UAT.

![screen shot 2018-11-19 at 4 07 49 pm](https://user-images.githubusercontent.com/12703638/48742835-7e2ac280-ec15-11e8-9df9-f316dc819b7f.png)

**Comment by johnpinto1** [comment]
PR based on suggestions by @briri . Note all table date columns are now set to min-width; 120px.

**Comment by stephaniesimms** [comment]
this looks and works great @johnpinto1 - thanks. closing issue.
