### ISSUE TITLE
Public Plan PDFs should not include questions

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1165]
The behavior for Public Plans changed -  I think related to issue #1127 that involves standardizing code for all file formats?

Now the public plans contain questions - remove these. The PDF should only contain the cover page, Project Title at the top of the second page, Sections headings, and Answers.

**Comment by stephaniesimms** [comment]
public plans are good now. closing issue.

**Comment by sjDCC** [comment]
I'm re-opening this as it doesn't work for DMPonline. Most of our funders have minimal or non-existent section headings so we need the actual questions included in downloads too. The content will be meaningless without them.

I think we agreed to have this as an export setting (i.e. section headings only or include questions) so it could be configured by default to each tool. Can we use these setting to determine what happens on public plans too?

Looking at download settings, we perhaps need to separate out options so you can have section heading without question text 

![capture](https://user-images.githubusercontent.com/6169940/36610462-45a752aa-18c8-11e8-889b-d93feaadb951.PNG)

Happy for this to be addressed post-MVP. We can live with partial download in meantime as they are no public DMPs!

**Comment by stephaniesimms** [comment]
DMPTool funder templates also have minimal section headings. The valuable content for public plans are the answers, and this is all that researchers submit with their grant proposals anyway (especially for DMPs with page limits). I'll create a new post MVP issue to evaluate content for public plans, but at the moment it's working as expected per the current DMPTool public plans functionality.
