### ISSUE TITLE
Resolve issue with Guidance subgroups

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1166]
More background/detail in related issue #944

Going to leave the optional subset as is for MVP. Although its not ideal its the safest approach to display all of the guidance groups under the org when selecting guidance rather than adding code in to force a hierarchy onto data that may or may not adhere to it. I propose we truly fix the issue after MVP (update the guidances page so that there can be only one top level group per org).

**Comment by pherterich** [comment]
Part of Rachael's UX work, to be addressed as part of that

**Comment by dstuckey-uoe** [comment]
Issue is stale, so we decided to close it.
