### ISSUE TITLE
Create Usage reports that include all org data for users and plans

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1173]
Usage Dashboard:
Right now as we wanted something workable, the CSV files are calculated on demand, i.e. any time you press download in any topic, 12 queries to the db are send, one for each month. The ideal solution for this would be to have history tables that are updated automatically each month (e.g. cron job). That would mean that we would reduce from 12 to 1 query.

- History tables that are updated monthly   
- Each table should capture monthly aggregates per organisation for the following topics:   
    - Users joined   
    - Plans created   
    - Plans by template (will be done in #1679)   
- Note, the rows are sorted descending by date for each topic   
- The data (since the organisation was created in the service) must be CSV downloadable. The file could have the following format for no. users joined:

Date | No. users joined
-- | --
June 2018 | ...
May 2018 | ...
April 2018 | ...
... | ...

Date | No. plans created
-- | --
June 2018 | ...
May 2018 | ...
April 2018 | ...
... | ...

**Comment by jollopre** [comment]
@sjDCC, @stephaniesimms can we mark this issue as completed? There is no much to test from your side right now, however there is plenty of test in place to satisfy the DoD.

**Comment by sjDCC** [comment]
Yes, fine by me. This is incorporated into the tickets you're working on
