### ISSUE TITLE
Connect your ORCID styling incorrect

### ISSUE THREAD

**Issue by mxsstrong** [DMPRoadmap/roadmap#1179]
Please complete the following fields as applicable:

**Expected behaviour:**
OCRID has specific instructions on how to display connecting your ORCID.  Should display a button according to their style guidelines.  https://members.orcid.org/api/resources/graphics

![screen shot 2018-02-20 at 11 18 32 am](https://user-images.githubusercontent.com/810543/36444247-d1c4a120-162f-11e8-9b9c-adca30d1a077.png)

**Actual behaviour:**
There is a link displayed which should be replaced by a button

![connectyourorcid](https://user-images.githubusercontent.com/810543/36444191-a889ef68-162f-11e8-8b2f-9653c60c34df.png)

**Steps to reproduce:**
Log in, go to your profile to connect to ORCID.

**Comment by vyruss** [comment]
@mxsstrong according to their page, it doesn't need to be a button but can be a simple link styled with their recommendations - better that way as it doesn't clash with our site's design. Implementing below:

**Comment by stephaniesimms** [comment]
styling correct now - contains logo. closing issue.

**Comment by sjDCC** [comment]
Looks good. Removing from board
