### ISSUE TITLE
Only export answered questions

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#118]
For some templates, questions are optional or there's an expectation that not all will be answered.

If questions have been left unanswered, ideally the export view would show these unchecked and only export completed responses. The user could override this and choose to export them all, but currently they're not alerted to which are answered and not. All are automatically selected for export

**Comment by vyruss** [comment]
Definitely sounds like an option and not something we should do without asking. It could be implemented as a tickbox when exporting:
- [x] Export unanswered questions

**Comment by sjDCC** [comment]
Currently users see a summary of all sections / questions with everything pre-selected to export. It would make sense to uncheck unanswered questions as these typically won't be needed. Very few template owners force users to answer every single question. 
Alternatively, we could let template owners define what should be pre-checked. There's only one case in the UK (the AHRC) where they specify that these exact headings and questions should be followed and replicated in full. 
![export-settings](https://cloud.githubusercontent.com/assets/6169940/23502154/b0d32d88-ff2e-11e6-8110-b3e1b35a55ff.PNG)

**Comment by briri** [comment]
this is an option now on the download page
