### ISSUE TITLE
'View all templates' button reloads wrong tab

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1180]
Please complete the following fields as applicable:

**Expected behaviour:**
When I click the button to 'View all templates' after editing any template for my Org (located in the second tab on main templates page) I would expect to be taken back to to my Org templates tab. Likewise, after customizing a template and clicking 'View all templates' I would expect to go back to the Customizable templates tab. The 'View all templates' button should work as a back button

**Actual behaviour:**
Current behavior when I click 'View all templates' (as a Super Admin) is to take me back to the last active tab (UCOP tab is white in screenshot below) but the table displays 'All templates.' I have to select a different tab and then reselect the UCOP Templates tab in order to see the correct list of templates. This is true for Org Admins as well - clicking 'View all templates' displays the Own templates list regardless of which tab is highlighted.

1 - Actual behavior when I click 'View all templates' after editing a UCOP/Org template
![screen shot 2018-02-20 at 7 20 25 pm](https://user-images.githubusercontent.com/12703638/36461825-8ebf3d0a-1674-11e8-9ed3-5577ea4bf955.png)

2 - Desired behavior when I click 'View all templates' after editing a UCOP/Org template
![screen shot 2018-02-20 at 7 23 26 pm](https://user-images.githubusercontent.com/12703638/36461851-b0756ab4-1674-11e8-852f-93bcc42fcdc9.png)

**Comment by stephaniesimms** [comment]
this is working as expected for Super Admins - clicking 'View all templates' takes me back to the appropriate tabs.

As an Org Admin it's doing something weird when I click 'View all templates' after customizing a template. The button takes me back to a page with Own templates and Customizable templates tabs stacked (screenshot below). This only happens for Org Admins and only for the Customizable templates tab.

![screen shot 2018-02-22 at 9 55 52 am](https://user-images.githubusercontent.com/12703638/36555635-6fb72e2e-17b7-11e8-8b2b-52ec65186d5f.png)

**Comment by stephaniesimms** [comment]
almost fixed. the only problem now is that as an Org Admin (only) when I first navigate to the Templates page I see blank tabs with no table content (screenshot 1). If I click either tab, then the tables appear (screenshot 2). all other behavior working as expected. please just fix the behavior to display the table content when a user first navigates to the Templates page.

![screen shot 2018-02-23 at 8 35 51 am](https://user-images.githubusercontent.com/12703638/36605223-f2a18e70-1874-11e8-87b3-43aed95b4140.png)

![screen shot 2018-02-23 at 8 36 07 am](https://user-images.githubusercontent.com/12703638/36605224-f584e74a-1874-11e8-8681-fa3a9ff0d400.png)

**Comment by stephaniesimms** [comment]
this is working as expected now. closing.

**Comment by sjDCC** [comment]
I just tried customising a template, clicking 'view all templates' and it took me back to the 'all templates' tab, not the 'customisable templates' one I was in. 

It seems to work as a back button when you're making a change on your own templates but not on the customisable ones. I'm reopening as this should work as a back button too I think.

**Comment by stephaniesimms** [comment]
this code must be super brittle since that was not working then fixed now not working again. every small fix seems to break something else. moved back to in progress.
