### ISSUE TITLE
Make Template names an actionable link cf. Project title in My Dashboard

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1182]
For consistency and usability, Org admins should be able to click the 'Template Name' for editable and customizable templates in the same manner that users can click 'Project title' to open/edit a plan from My Dashboard (screenshot 1). 
- Make Template names a hyperlink that opens the template details page for all Org templates and Customizable templates (screenshots 2-3)

![screen shot 2018-07-10 at 10 03 15 am](https://user-images.githubusercontent.com/12703638/42525677-a402ab12-8428-11e8-8d54-f4acece5441f.png)

![screen shot 2018-07-10 at 10 02 00 am](https://user-images.githubusercontent.com/12703638/42525666-9c1036ea-8428-11e8-8ce2-896f6ae95142.png)

![screen shot 2018-07-10 at 10 02 25 am](https://user-images.githubusercontent.com/12703638/42525673-a0d1d972-8428-11e8-9613-b50cad240c2c.png)

**Comment by johnpinto1** [comment]
Screen shots of visibility of links under the 
![selection_127](https://user-images.githubusercontent.com/8876215/52857597-8ebcdd00-311f-11e9-94f2-c8de7e139e5e.png)
![selection_128](https://user-images.githubusercontent.com/8876215/52857602-92e8fa80-311f-11e9-9206-7278942331ce.png)

*Template Name* column on Templates page:

**Comment by sjDCC** [comment]
Perfect. Thanks @johnpinto1 Closing out
