### ISSUE TITLE
Can't edit/remove all themes from a question

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1183]
When I uncheck themes for any question while editing a template and click Save, it remove some but not all of the themes. Every time I uncheck and click Save at least one theme remains checked after the page reloads. Overall the behavior is erratic, sometimes saving my changes and other times retaining all of the checked themes. If I click Delete, it deletes the entire question.

Desired behavior is to allow the user to Save a question with the desired themes or uncheck all boxes and have no themes.

![screen shot 2018-02-20 at 7 51 59 pm](https://user-images.githubusercontent.com/12703638/36462355-b578e68c-1677-11e8-8920-8cdf13544a63.png)

**Comment by stephaniesimms** [comment]
Now I can remove all but one theme. It doesn't allow me to uncheck all themes and Save the selection. Each time I try it retains the last checked theme. Desired behavior is to allow users to remove all themes and save the question.

**Comment by briri** [comment]
ah ok. fixed it for the Guidances page didn't update the edit template questions page. I can't tell from the screenshot where you are though

**Comment by stephaniesimms** [comment]
thanks for catching the Guidance page. I was focused on templates - issue mentions themed "question" but that is definitely not clear enough. apologies @briri

**Comment by stephaniesimms** [comment]
working as expected now for template questions. closing issue.

after paying closer attention to Guidance themes, I noted that it doesn't make sense to have un-themed guidance because this won't display on any templates. it's not a bug, just a usability issue to allow admins to not apply themes to Guidance. i'll create a new issue to address this post MVP.

**Comment by sjDCC** [comment]
Theme selection / deselection works fine now. Removing from board.

You're right @stephaniesimms that it makes no sense to have guidance without a theme. It should always be tagged with one so there should be a rule to prevent saving otherwise. The only case where themes don't apply is annotations on a specific quidance (i.e. the former 'guidance by question' data)
