### ISSUE TITLE
Use proper labels for guidance resources on Funder Template PDFs

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1184]
Currently the downloadable PDFs for funder templates use the label "Guidance" for all additional info attached to the template question. In the example below, the Guidance label is repeated for Example Answer and Guidance (text). Desired behavior is to use the proper labels for different kinds of guidance. 

First 'Guidance' section should be labeled 'Example Answer'
![screen shot 2018-02-20 at 7 59 11 pm](https://user-images.githubusercontent.com/12703638/36462475-8f512568-1678-11e8-86d9-c5f0faca21bb.png)

**Comment by stephaniesimms** [comment]
labels look good. closing issue.

**Comment by sjDCC** [comment]
I assume this is a US-specific thing as it seems to be labels / headings you are applying within existing pieces of themed guidance. Is that right? It isn't the difference between themed guidance and example answers which are two separate fields in the database and entered in different places in the tool. 

In terms of data integrity I assume you would be best taking this 'Example answer' text and saving it as actual example answers according to the data model (@vyruss correct me here if I'm wrong) but I guess that's not an easy switch if the guidance doesn't pertain to specific questions.

Not sure how to UAT this one as I'm not familiar enough with the data to find an example to review. Have added it to agenda so you can run us through what's happening tomorrow.

**Comment by sjDCC** [comment]
Ah, I get you. This is coming from the two separate fields (guidance and example answer) but was wrongly labelled in the PDF export. It looked like a full piece of guidance from you so I mistakenly thought you were  changing headings within an existing piece of guidance.
