### ISSUE TITLE
Fix link formatting in DOCX files

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1185]
The hyperlinks in DOCX downloads of funder templates are all wonky with extra long underlining (see screenshot "Datacite organisation"). @briri suggested swapping the current gem for the one we use in DMPTool.

![screen shot 2018-02-13 at 8 19 14 am](https://user-images.githubusercontent.com/12703638/36160728-bcc4ef58-1096-11e8-95fe-f7f477acba63.png)

**Comment by vyruss** [comment]
Duplicate of #592 , closing older issue

**Comment by vyruss** [comment]
@briri PR submitted upstream as karnov/htmltoword#70 . Until they merge it in, we can put this in our gemfile to fix the situation:
`gem 'htmltoword', :git => 'https://github.com/vyruss/htmltoword'`

**Comment by stephaniesimms** [comment]
links still appear with white space in DOCX templates and plans

**Comment by briri** [comment]
@stephaniesimms I updated the gemfile as @vyruss mentions above on roadmap-stg. Can you see if the issue is resolved? We will need to wait until the owner of the htmltoword gem accepts the fix before releasing this, but we can at least verify that its working as expected.

**Comment by stephaniesimms** [comment]
now things are looking good. links are formatted correctly and are functional. should i leave this issue open until the gem owner accepts the fix?

**Comment by sjDCC** [comment]
Looks good. No funny underscores around sides, but doesn't format as a URL either (i.e. blue)

@vyruss can you confirm re: the gem?

**Comment by stephaniesimms** [comment]
ready to test on roadmap stage when the PR comes through @vyruss @briri

**Comment by vyruss** [comment]
@stephaniesimms @briri I can confirm that this has gone through, I just tested it and it works. The current `Gemfile` does not reference my fork therefore a ```bundle update htmltoword``` will just bring in `htmltoword 1.0.0` which includes my fix.

**Comment by stephaniesimms** [comment]
links look lovely now. closing issue.
