### ISSUE TITLE
Clicking 'View All' for Users and Orgs as Super Admin blows up server

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1186]
The queries for the Users and Organizations tables include a join to provide plan and template counts - these queries are overloading the server when a Super Admin clicks the link to 'View All' in these tables (I got a proxy error for both)

Disable View All for Super Admin users on these tables - updated per @sjDCC and my confirmation that this is a good solution

**Comment by sjDCC** [comment]
Yeah, @jollopre expressed concern about how big some of these queries would be. I’m not sure we need the ‘view all’ so let’s just disable it for superadmin.

**Comment by stephaniesimms** [comment]
View All link is no longer present on Users page at all. Desired behavior is to remove the link for Super Admins only and retain it for Org Admins. In the latter case it's unlikely that the number of users will cause issues and admins want to be able to expand the table to see an overview of all their users.

please reinstate the ability to View All users for Org Admins @jollopre

**Comment by stephaniesimms** [comment]
looks good now on roadmap stage. closing issue.
