### ISSUE TITLE
Allow template owners to make questions mandatory and set routing

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#119]
Some template owners would like to make certain questions compulsory or set routing through templates e.g. if yes, skip to section X

Main requirements here come from ZonMw, but several have asked for mandatory questions

**Comment by stephaniesimms** [comment]
USGS began using the mandatory question option on DMPTool templates. We can discuss whether this should be included in MVP.

**Comment by Yu-Chieh-Henry-Yang** [comment]
@briri @stephaniesimms 
Are we looking forward to implement the feature for template owner to make a question mandatory soon? (Or maybe this feature is already built in?)
If not, how would you suggest one go about building such feature?

**Comment by sjDCC** [comment]
hi @Yu-Chieh-Henry-Yang This is just a suggestion for now, but something we'd certainly be interested in as users have requested it. If you are considering adding such a feature please let us know so we can collaborate and bring this in. It's great to get code contributions from externals like you

**Comment by magdalenadrafiova** [comment]
@xsrust can we also close this?
