### ISSUE TITLE
Add asterisk to mandatory fields

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1197]
Add asterisk to mark mandatory form fields via CSS. Try red asterisks cf. DMPtool (screenshot below).

![screen shot 2018-02-21 at 4 20 52 pm](https://user-images.githubusercontent.com/12703638/36513179-38ae48ac-1723-11e8-84d8-06ed0219e033.png)

**Comment by briri** [comment]
a CSS solution won't work for this. We should be able to add some JS to the ariatiseForm.js and validation.js though to add in the asterisk. Just need to determine how best to apply it to regular input fields vs checkboxes and radio buttons. Maybe something like:
```javascript
const addAsterisk = (el) => {
  if (isObject(el) && el.attr('aria-required') === 'true') {
    if (el.attr('type') === 'checkbox') {
      el.after(' * ');
    } elseif (el.attr('type') === 'radio') {
        el.closest('.form-group').before('* ');
      } else {
        const label = el.closest('.form-group').find('label');
        if (isObject(label)) {
          label[0].before('* ');
        }
      }
    }
  }
};
```
An example of required radio buttons can be found on the share plan page and example of a required checkbox can be found on the create account page

**Comment by briri** [comment]
Updated to add asterisks to any fields marked with `aria-required="true"` which drives our form validations. 
@stephaniesimms and @sjDCC it looks though like we don't require all of the fields we should be requiring. For example in the Template and Guidance pages in particular there are a lot of fields I would expect to be required (e.g. Question text, Section title, etc.) We should probably go through all of the admin pages and create a new ticket for making any of these fields required (can all be listed on one ticket).

**Comment by stephaniesimms** [comment]
asterisks look good @briri - @sjDCC and I can go through all pages and create a new issue for any additional fields that should be required. 

for now, there's just a tiny html issue that crept in on the Edit Profile page. see screenshot below and remove <p> tag

![screen shot 2018-03-25 at 6 41 53 pm](https://user-images.githubusercontent.com/12703638/37883020-dc0502d2-305c-11e8-8ee4-69bceabc089d.png)

**Comment by jollopre** [comment]
After adding asterisks, I've just noticed that create plans has changed. Is that the layout desired?
![untitled](https://user-images.githubusercontent.com/7393044/37895571-9d9531ac-30d9-11e8-9852-eb828412cdb5.png)

**Comment by sjDCC** [comment]
This isn't desired and I'm sure was unintended. The question text on 'create plan' page should come above the combo-select box.

In terms of admin, I'm sure question text and section title did used to be mandatory as I've had error messages before refusing to save if this is blank. Good to raise tickets to reinstate them if this logic has been lost. I think they're the only two cases and email & name on edit profile.

I see the <p> tag too on edit profile page now so this and the create plan adjustments need to be fixed.

Having a red asterisk looks good though and is clear for end users.

**Comment by stephaniesimms** [comment]
thanks for catching that @jollopre - we don't want asterisks on the create plan page, which also messed up the layout. to summarize remaining work for this issue @briri :

- remove html tags from Edit profile page and Guidance page
- remove red asterisks from Create plan page 

I created a new issue to identify fields that should be mandatory (either those that were previously and have been lost or new mandatory fields). please add anything else you find to it @sjDCC #1326

**Comment by briri** [comment]
Just want to note that the `<p>` paragraph tags are coming through the app.po files. I will update the code to allow for embedded HTML. We may start seeing this happen more as people start updating their translations

**Comment by stephaniesimms** [comment]
create plan page looks good now, as do other pages with mandatory fields marked w/asterisks. thanks for removing the html tags @briri and for alerting us to the app.po source. closing this issue.
