### ISSUE TITLE
Expand phase accordion by default on template details page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1199]
When user clicks to edit or customize a template we should load the template details page with the phase accordion expanded by default. i think this was a request @sjDCC made in the #791 . for templates with multiple phases, just expand the first phase (e.g. NERC, H2020).

![screen shot 2018-02-22 at 3 22 30 pm](https://user-images.githubusercontent.com/12703638/36569856-464dff72-17e4-11e8-9019-02ff2121040f.png)

**Comment by briri** [comment]
already fixed
