### ISSUE TITLE
I shouldn't be able to edit historical versions of templates

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1207]
As an admin, when I navigate to template history and click the link to "View' a historical version I see a friendly notice that I won't be able to edit historical templates. However, if I click to open the version I see Edit/Delete action buttons everywhere. I am able to make changes to the historical version but if I publish any changes later only the most recent version is reflected.

To avoid confusion, admins should not see the edit buttons at all when viewing a historical version (screenshot below). Remove all edit/delete buttons.

![screen shot 2018-02-22 at 5 54 21 pm](https://user-images.githubusercontent.com/12703638/36574334-1b0e0990-17fa-11e8-8a86-5ec873e056a2.png)

**Comment by stephaniesimms** [comment]
no more edit buttons for historical templates. closing issue.

**Comment by sjDCC** [comment]
Looking good now. No edit buttons appear. Removing from board
