### ISSUE TITLE
Themed guidance not displaying on 'customise template' preview

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1209]
When org-admin users customise funder templates, they should see any existing themed guidance that is associated with a question. This clarifies what guidance will already be visible to their users so they know what additional, question-specific annotations they wish to apply (if any). 

At present the themed guidance is not pulling through and displaying when the user click to edit / customise a funder template.
![themed-guidance-missing](https://user-images.githubusercontent.com/6169940/36603522-f247ee0e-18b2-11e8-9a29-cb1e6641bbe7.PNG)

This is how it looks on live DMPonline
![from-live-dmponline](https://user-images.githubusercontent.com/6169940/36603525-f5a547b8-18b2-11e8-9d5f-a64c2397590c.PNG)

**Comment by vyruss** [comment]
@sjDCC can you please check if this is still an issue now?

**Comment by sjDCC** [comment]
University themed guidance is still missing from the preview when an admin user is customising a funder template. It would be helpful for them to see what themed guidance will display to determine whether question-specific annotations are needed

**Comment by johnpinto1** [comment]
Screen shots of changes:
![selection_125](https://user-images.githubusercontent.com/8876215/52857058-f40fce80-311d-11e9-8b8f-4629755e6be5.png)
![selection_125](https://user-images.githubusercontent.com/8876215/52857065-f96d1900-311d-11e9-9442-7b9892df9e20.png)

**Comment by sjDCC** [comment]
Thanks @johnpinto1 Great to see the themed guidance appearing again. I think it would be best if we just showed the themed guidance block though and removed the advisory text above and below this. Is that possible? Where there is no themed guidance it is better if this panel is completely blank.

![capture](https://user-images.githubusercontent.com/6169940/53096241-97922200-3516-11e9-8262-5d56986c4ca2.PNG)
![capture2](https://user-images.githubusercontent.com/6169940/53096242-97922200-3516-11e9-889d-394e5e2c7aec.PNG)
