### ISSUE TITLE
Verify all rake tasks are present and working

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1210]
- Verify that all new DB fields have corresponding rake tasks.
- Verify that rake tasks are working and note what order they should be run in
- Remove all limits from schema.rb file
- Rename 'bugfix' rake file to 'upgrade'
- Brian send PR for broken API token task

**Comment by briri** [comment]
Hey @jollopre, make sure the following fields have a default value when you migrate:
- plans.visibility - 3   (privately_visible)
- templates.links - '{"funder":[], "sample_plan":[]}'
- orgs.links - '{"org":[]}'

All of the other new fields are strings or don't require a default val

**Comment by vyruss** [comment]
fixing typo in `bugfix:set_template_visibility`

**Comment by briri** [comment]
closing this one as there is no UAT needed
