### ISSUE TITLE
Including ORCID in project metadata on plan download cover sheet

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1211]
Which fields from 'project details' are coded to be included in the optional coversheet on plan download? It seems most come through if completed, but the ORCID definitely doesn't and given other plans we have around leveraging PIDs, this is definitely a good one to include.
![metadata-for-project-coversheet](https://user-images.githubusercontent.com/6169940/36604361-755c646c-18b5-11e8-94ae-333c5e21fcf0.PNG)

![capture](https://user-images.githubusercontent.com/6169940/36604376-7a14cb2a-18b5-11e8-9deb-92b5c2b89b6d.PNG)

Result:
![resulting coversheet](https://user-images.githubusercontent.com/6169940/36604392-802bd468-18b5-11e8-8b3b-e3b88016688a.PNG)

I assume the contact details aren't included and I'm ok with that. @stephaniesimms do you have a strong preference?

**Comment by stephaniesimms** [comment]
I agree with including ORCID when available. But would prefer not to include contact details as users may not want people emailing asking them how to write a DMP. Admins here use public plans in workshops too so less dissemination of personal details is better.

**Comment by briri** [comment]
Added ORCID iD. We also show the Grant Number if its available.

**Comment by stephaniesimms** [comment]
ORCID appears on cover sheet when available. closing issue.

**Comment by sjDCC** [comment]
Looks good. Thanks @briri Removing form board
