### ISSUE TITLE
Require admins to apply exactly one theme to Guidance

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1212]
as part of bug issue #1183 we accidentally enabled admins to remove all themes from Guidance. reinstate the requirement to apply at least one theme for each piece of Guidance - it doesn't make sense to create un-themed Guidance because this will never display on templates.

**Comment by vyruss** [comment]
While we're fixing this, I think we should change this to be "exactly one Theme to Guidance". After discussion with @sjDCC we came to the conclusion that it makes no sense to apply multiple Themes to one piece of Guidance.

This requires:
- Changing the data model Themes <-> Guidance relationship from HABTM to FK
- Changing the guidance tickboxes so that only one can be selected 
- Changing the controller so that it only accepts exactly one theme per guidance
    - Updating the controller with the appropriate warning messages

**Comment by briri** [comment]
fixed as part of #1326. It made sense to address it at the same time as adding in the validations

**Comment by stephaniesimms** [comment]
after testing I am able to create and publish guidance with no themes (screenshot 1). once i apply a theme and save it, then uncheck the box and save, my changes are not applied so it appears to be requiring at least one theme at that point. i can still apply multiple themes.

- desired behavior is to mark the field "Themes" with a red asterisk and require users to apply one theme only before allowing them to save guidance.
- also need to revise the tooltip (screenshot 2) with the following proposed text (@sjDCC can confirm): "Select one theme that is relevant to this guidance. This will display your generic organization-level guidance, or any Schools/Departments for which you create guidance groups, across all templates that have questions with the corresponding theme tags."

![screen shot 2018-06-13 at 3 55 11 pm](https://user-images.githubusercontent.com/12703638/41382819-b1038b8a-6f22-11e8-921f-97b1e8b29a7d.png)

![tooltip](https://user-images.githubusercontent.com/12703638/41382823-b52e23e6-6f22-11e8-9321-3ce39106b967.png)

**Comment by stephaniesimms** [comment]
tooltip looks good. but when I create a new piece of guidance the Text area doesn't recognize that I've input text and won't allow me to save. I get the field validation message (screenshot below) the first time I click Save. I have to click Save a second time and then it allows me to proceed. Please amend so it saves after the first click.

![screen shot 2018-06-18 at 1 37 04 pm](https://user-images.githubusercontent.com/12703638/41560693-c3aa3a08-72fc-11e8-8b53-71f1ed78dad6.png)

**Comment by stephaniesimms** [comment]
@briri noted that this is a more complicated problem w/this tinyMCE editor in the Guidance section. will create a separate bug issue and consider this issue to be closed.
