### ISSUE TITLE
Guidance by question still in view on 'themed guidance' page

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1213]
Legacy guidance by question data was migrated into 'annotations' on the customisable templates view in an earlier release, but is still visible under the themed guidance view on org-admin pages too.

To see an example check university of Glasgow guidance related to MRC q7.

Here is the view on the template customisation showing it correctly as an annotation, but it also wrongly shows in the themed guidance list. 

![capture2](https://user-images.githubusercontent.com/6169940/36606316-3beb818a-18bb-11e8-9c88-6a57c1a49386.PNG)

![capture](https://user-images.githubusercontent.com/6169940/36606319-3f85a6ae-18bb-11e8-8263-cee7b7ba1c11.PNG)

**Comment by xsrust** [comment]
@sjDCC Is this still an issue?
I think it's been fixed by the overhaul of these views

**Comment by sjDCC** [comment]
yes, appears so. Closing out
