### ISSUE TITLE
Only alert the main helpdesk when a request for feedback on a DMP is received

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1217]
Make helpdesk contact email a mandatory field on the organisation details page. We should only be alerting this central address, not every admin user for the organisation. I spammed Glasgow users when testing and doing demos last week!

Note: this issue needs to be addressed with related issue #1197 and confirm that contact email field is required on Org details page.
![capture](https://user-images.githubusercontent.com/6169940/36608379-92a7ce74-18c1-11e8-977b-f7d7ed568f43.PNG)

We have an opt out email notification setting that I guess needs to be removed if we add logic to only email the central helpdesk. Individual admin users wouldn't be alerted so it doesn't make sense to let them untick this box.
![picture1](https://user-images.githubusercontent.com/6169940/36608392-97c8bc92-18c1-11e8-86bc-0530a4959c33.png)

**Comment by briri** [comment]
just a note that we should still add the `:reviewer` role for all of the org admins even though we're no longer sending them an email.

**Comment by stephaniesimms** [comment]
#1326 this issue needs to be addressed at the same time. we need to make the Admin contact email a mandatory field so that someone receives the Request feedback emails. noting here that we should move these two issues to the next sprint.

**Comment by stephaniesimms** [comment]
this appears to be working as expected now. i tested as a couple of different orgs and emails only went to the main org contact. @sjDCC should double check to confirm but i'll go ahead and close it.
