### ISSUE TITLE
Make sure plan export options match plan details fields

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#122]
From Pivotal ticket: https://www.pivotaltracker.com/story/show/132614119

Review the fields for all Included Elements > Admin details on the Export plans page (this page was created by external developers and is not consistent with other info in the Plan details page). Screenshots below.

Inconsistent use of terms “plan details” “project details” “plan name” “project name” “Title/DMP title” - this is confusing and needs to be standardized throughout the tool

Related ticket to add ORCID to Admin details https://www.pivotaltracker.com/story/show/120801699

**Comment by stephaniesimms** [comment]
this is addressed in new wireframes and related issues #491 #498
