### ISSUE TITLE
Admins should not be able to comment on plans unless invited

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1220]
As an Org Admin or Super Admin I can open and view all plans in read only mode, which includes adding comments. I should only have access to comment on plans for which users have requested feedback (these plans appear in the notifications panel at the top of the Plans page). 

Correct behavior is to set permissions so admins can only view plans but disallow commenting for plans in the main table (screenshot). Plans that a user submits for feedback should appear in the Notifications panel above this table with read only permissions that permit commenting.

<img width="1014" alt="screen shot 2018-02-23 at 1 33 31 pm" src="https://user-images.githubusercontent.com/12703638/36618103-b668e956-189e-11e8-9574-e4f17138bbe4.png">

**Comment by briri** [comment]
Ok will Remove the link to the plan from the table. 

Feedback seems to be working properly for me. I think the issue you see is a timing thing. 
When a user requests feedback it makes all admins for that Org a reviewer. If a user becomes an admin after the request for feedback has been made though they would not see the plan in their notification list because they were not an admin at the time the user requested feedback.

**Comment by stephaniesimms** [comment]
feedback is working again, thanks! sarah created an issue to notify the Org contact email when feedback is requested, but it's fine as is for now. the most important thing is that admins can no see links to open all plans - only those for which feedback has been requested.

**Comment by stephaniesimms** [comment]
this is working as expected now. closing.

**Comment by sjDCC** [comment]
Hi @briri I'm reopening this issue as we had intentionally made the plan names clickable links and allowed the admins to view the contents. We had a whole long discussion about it in ticket #434 

On 5th December @stephaniesimms said:

"sorry, i got confused. @sjDCC is correct that yes, we do want to make the plan name a link to enable org admins to open & read the plan. per our discussion on the check-in call, we need to create an exception in the code that enables admins to see plan content but not comment or perform any actions (a true read-only access w/no commenting privileges). admins should only have the ability to provide comments when a plan owner has requested feedback.

related issue #876 reflects this desired functionality"

This was a desired new feature and the T&Cs allow for it. I've also promoted and demoed this

**Comment by briri** [comment]
ok. Its a very easy thing to revert:
https://github.com/DMPRoadmap/roadmap/pull/1224/files

**Comment by briri** [comment]
ok. I think this may have been a non-issue all along. I reinstated the links and when testing found that as an org admin I could not comment on any plans or edit them. The only situation where I was able to comment/edit was when the plan plan had previously been shared with my org admin account which makes sense.

**Comment by stephaniesimms** [comment]
i revised the issue according to slack discussions @briri - and maybe the problems i was finding last week w/plans not appearing in the notifications panel and being able to comment on plans from the main table were a result of bad data..? whatever the case thanks for sorting it out and we can all confirm that it works as expected when deployed on Mon.

**Comment by sjDCC** [comment]
Sounds good. Thanks for sorting this.

**Comment by stephaniesimms** [comment]
i can open and view plans, but not comment on them which is working as expected. but i can download all plans as well, which i don't think i should be able to do freely as an admin. moving this back to in progress w/a request to disable plan download @briri . @sjDCC should also confirm that this is the desired functionality.

**Comment by briri** [comment]
moving this to the new board since we're waiting on confirmation

**Comment by sjDCC** [comment]
Sorry for the delay from my end. I'm not too concerned either way, so if you would prefer to disable download for now that's fine by me @stephaniesimms. 

tbh we haven't asked in detail what the UK admin user community wants. We just know that access to the actual content of plans in some form is desired so they can use the intel to inform service delivery. Ultimately I think they will need download (perhaps in aggregate?) so they can mine the info and pull out salient details e.g. data volumes, but lets flesh out that functionality at a later date as we work up machine-actionable use cases in full.

**Comment by stephaniesimms** [comment]
since it's ok w/ @sjdcc i'd prefer to disable download for now. we can address bulk data mining and reporting later yes.

**Comment by stephaniesimms** [comment]
i am still able to download all plans for which feedback has been requested. desired behavior is to disable or hide the Download tab @briri

**Comment by briri** [comment]
Ok. Didn't realize we wanted to restrict this from reviewers as well

**Comment by stephaniesimms** [comment]
this is working as expected now. as an admin reviewer i can only see project details and write plan in read only mode, plus add comments. download tab is hidden. closing issue but leaving here for @sjDCC to confirm that it meets her requirements too.

**Comment by sjDCC** [comment]
I still see a download button on the admin > plans page on roadmap-stage. I wonder if this is because my affiliation is an org rather than a uni? I tried changing it on edit profile but was warned I'd lose admin rights so didn't proceed.

Perhaps check and if all is ok just remove from board.

![capture](https://user-images.githubusercontent.com/6169940/37925006-6e0253b4-312b-11e8-8f22-eb0770c6fdbf.PNG)
