### ISSUE TITLE
Evaluate customization of public plan content 

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1227]
@sjDCC would like to include questions for DMPonline public plan download. Evaluate possibility of customizing the default public plan content to include questions for a given instance.

Notes from related issue #1165 
Looking at download settings, we perhaps need to separate out options so you can have section heading without question text 

![capture](https://user-images.githubusercontent.com/6169940/36610462-45a752aa-18c8-11e8-889b-d93feaadb951.PNG)

Happy for this to be addressed post-MVP. We can live with partial download in meantime as they are no public DMPs!

DMPTool funder templates also have minimal section headings. The valuable content for public plans are the answers, and this is all that researchers submit with their grant proposals anyway (especially for DMPs with page limits).

**Comment by stephaniesimms** [comment]
make download settings customizable for different installations - default checkboxes and potentially also public dmps default

**Comment by sjDCC** [comment]
Reviewing this again, I'm less concerned about the public DMPs displaying questions. The section headings is sufficient. 

Currently DMPonline (and DMPTool / DMPRoadmap core code?) exports question text as well as headings on standard export. I'm happy for this to be configurable by installation to suit each community needs so perhaps we should rework this ticket in that vein? 

Public plan export / download looks good as it is currently

**Comment by stephaniesimms** [comment]
since we're both happy with public plan export i'll close this for now. and just create a new issue to make the default download settings for individual plans configurable since we've had requests for that.
