### ISSUE TITLE
New Org not displayed in Orgs list

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1239]
If you create a new Org via the Super Admin page they do not appear in the list of orgs on the Super Admin Orgs page.

I believe its due to the join on the templates table (a new org would have none). This join speeds up the query but will not work for this scenario since orgs need not have a template.

`render 'index', locals: { orgs: Org.includes(:templates, :users).joins(:templates, :users) }`

**Comment by cpwillett** [comment]
It's not just new orgs. I see a lot of institutions missing. There were 226 institutions in the database that we migrated, but only 76 appear in the list at https://dmptool.org/super_admin/orgs

**Comment by briri** [comment]
yes, in attempt to optimize the query a join was added to the templates and users tables to get their counts. The type of join that is being used though will ignore an org if it has no users or templates.

Fix for this is coming today

**Comment by stephaniesimms** [comment]
this is working as expected now. all Orgs appear in the list and I can see new Orgs when I add them. closing.
