### ISSUE TITLE
Update seeds file for usage stats

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1243]
Update the `db/seeds.rb` so that the default super admin and org admin accounts have access to the usage stats API.

- Verify that the 'use_api' perm is in place
- Verify that the 'statistics' api_token_type is in place
- Create an API token for the users and give them access to 'use_api' via the roles table

**Comment by briri** [comment]
closing this one since there is no UAT involved

**Comment by Ebrahim1010** [comment]
@briri we updated the Update the db/seeds.rb and now have access to run my own filter but cannot generate any stats.
<img width="1270" alt="Screen Shot 2019-11-26 at 15 34 21" src="https://user-images.githubusercontent.com/47170940/69637953-6543c100-1062-11ea-9898-615544fe0221.png">

**Comment by briri** [comment]
Hi @Ebrahim1010,

It looks like you need to run the `rake stat:build` rake task. This will generate all of the statistics for your installation and stores them in special tables in the database. The usage statistics page uses those tables. We run that rake task (via CRON on our servers) on the first day of the month. I would recommend that you do something similar so that the job gathers all of the latest stats for you each month. Please note that the task may take a while to finish and you may want to run it when your system does not have a lot of usage.
