### ISSUE TITLE
Fix formatting of DOCX plans

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1245]
there's still some weird indentation going on (screenshot below). 

the cover page plan title is fine but the main plan title is still indented. so is the subtitle on the cover page "A plan created..." these titles can either be centered or left justified. whichever is easier to implement is fine - just make it consistent.

![screen shot 2018-03-02 at 10 00 17 am](https://user-images.githubusercontent.com/12703638/36914042-be15c0c2-1e00-11e8-86b1-15e5ff6d58ae.png)

**Comment by stephaniesimms** [comment]
@briri text and csv download work but other file formats produce the error below:

![screen shot 2018-03-07 at 11 09 41 am](https://user-images.githubusercontent.com/12703638/37112727-3045bbd4-21f8-11e8-93d3-42edd9149eea.png)

**Comment by briri** [comment]
same issue as #1247

**Comment by stephaniesimms** [comment]
i can download DOCX now. formatting looks good enough. there are still small rogue indentations but i understand that these downloads are a nightmare. and since you mentioned the possibility of swapping out the download gem i think we're good enough for now. closing.
