### ISSUE TITLE
PDF formatting settings don't work

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1247]
None of the PDF formatting settings (font type, size, margins) are working. Everything I test produces the same default formatting.

**Comment by briri** [comment]
still having issues 
![screen shot 2018-03-07 at 8 53 13 am](https://user-images.githubusercontent.com/1204467/37105933-4da1d3e2-21e5-11e8-93b1-01700698bea0.png)

**Comment by stephaniesimms** [comment]
working as expected now. closing issue.
