### ISSUE TITLE
Add Org & Date created columns to Users table 

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1248]
- add "Organization" column to main User accounts table after Email column 
- add "Created date" column after "Org" and before "Last activity" (for date account was created)

from Perry Willett:
this is probably also just a superadmin issue, but when I get requests from new institutions to make someone an admin, I need to know if they're affiliated with the institution in the db, or if they're still a "non-partner". The old DMPTool included the institution on this page: https://dmptool.org/org/admin/users/admin_index

from dmptool admin:
I would also add that we find it useful to be able to know when an individual user created their account. Sometimes we see a surge of account creations from admins in a specific department, for example. That helps us to target certain outreach. I know in the Users list, we can sort by Last Activity, which is useful, but that account creation date also has value.

![dmptool-userlist](https://user-images.githubusercontent.com/1558172/36863163-c845f47c-1d3d-11e8-82a5-247f36a4c798.jpg)

**Comment by stephaniesimms** [comment]
table looks good. closing issue.

**Comment by sjDCC** [comment]
Looks good. Removing from board
