### ISSUE TITLE
TinyMCE toolbar icons not displaying correctly

### ISSUE THREAD

**Issue by pgmccann** [DMPRoadmap/roadmap#1263]
Please complete the following fields as applicable:

**Expected behaviour:**
TinyMCE formatting icons display in the TinyMCE toolbar when editing a plan

**Actual behaviour:**
Placeholders displayed - icons don't appear to load.

<img width="287" alt="image" src="https://user-images.githubusercontent.com/1590010/37202355-38c08bb4-2382-11e8-9784-8c5b412556ab.png">

**Steps to reproduce:**
Edit a plan in DMPonline (https://dmponline.dcc.ac.uk) using Firefox 58.0.2 on macOS 10.13.3

**Comment by pherterich** [comment]
It's the same for me using Firefox (52.4.1) and Chrome (64.0.3282.186) (displays differently but still doesn't show icons) on Windows 7 Enterprise.

**Comment by vyruss** [comment]
@pherterich @pgmccann thank you, we are working on the issue as we speak.

**Comment by vyruss** [comment]
issue resolved
