### ISSUE TITLE
Questions displayed twice when editing a plan

### ISSUE THREAD

**Issue by pgmccann** [DMPRoadmap/roadmap#1264]
Please complete the following fields as applicable:

**Expected behaviour:**
Question displayed once above the textarea for response when editing a plan.

**Actual behaviour:**
Question displayed twice above the textarea for response when editing a plan.

<img width="253" alt="image" src="https://user-images.githubusercontent.com/1590010/37202684-1363c312-2383-11e8-970f-2efa82ef67c7.png">

**Steps to reproduce:**
Edit a plan on DMPonline (https://dmponline.dcc.ac.uk) using Firefox 58.0.2 on macOS 10.13.3.

**Comment by vyruss** [comment]
Thanks @pgmccann, we are rolling out the fix as we speak.
