### ISSUE TITLE
Evaluate the color combinations used

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#127]
Re-assess color combinations for DMPRoadmap. Keep current DMPRoadmap logo. Address color contrast issues raised in accessibility testing.

Color contrast fixes from accessibility review:
- White against orange in the logo passes color contrast guidelines for large text.
- Combination of orange/white on rest of page doesn't pass for small text.
- Combination of orange against gray ("signed in as [username]" doesn't pass either.
- Use color contrast tool to evaluate any other color combinations. (http://www.webaxe.org/color-contrast-tools/

From pivotal ticket: https://www.pivotaltracker.com/story/show/131322529

**Comment by briri** [comment]
Just focus on non org-admin/super-admin pages for this first pass. Use the new scss files when possible

**Comment by rhu001** [comment]
Iteration #1:
1.	Put in DMP logo (white)
2.	Put in dark green (darkened version of Dark green above- 36421a) for global nav area
3.	Change global nav text to white (ffffff)
4.	Add Dark green for header text (36421a)
5.	Add Dark green border around white form field boxes (36421a)

We can revisit the color combinations and layout closer to release for further refinement.

**Comment by stephaniesimms** [comment]
per mtg w/ UX and @sjDCC on 21/22 Jun decided to choose a neutral/generic color for Roadmap code (dark gray proposed). this will help distinguish the shared open source codebase from each of the services based on it, and alleviate confusion when testing different instances. all may then color and style as they choose. can you please suggest a color @rhu001 ?

**Comment by rhu001** [comment]
@briri Try this charcoal gray color. (4f5253)

**Comment by stephaniesimms** [comment]
Closing this issue. Accessible color combos for roadmap (stage) and DMPTool (dev) implemented for now. DMPonline will handle color/styling independently. We can revisit closer to release for further refinement as noted above.
