### ISSUE TITLE
Enable super-admins to edit user profiles

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1275]
Make the entry in the name column in the 'users' table a link to their profile page so super-admins can change org affiliation before granting admin permissions. Currently it is not possible to change their org affiliation to the correct one (e.g. to a new org that has been added to enable admin use). A separate ticket is addressing the ability to view the org #1248 
![picture1](https://user-images.githubusercontent.com/6169940/37296550-36ae28f2-2613-11e8-8343-c2f387e2db49.png)

Many DMPonline admins come from overseas unis that aren't currently listed in the tool so we need to add them as an org and affiliate the user to this before assigning admin permissions. The 'edit privileges' column now just pops up a modal with admin permission settings rather than opening their user profile where affiliation can also be set. Please make the name a link where we can access their full profile and change the org affiliation before granting permissions. Adding the 'org' column in the user table is also very helpful so we can ensure they have the correct affiliation before granting rights. This will be addressed under the related ticket.

**Comment by briri** [comment]
Are there other pieces of information or tasks a super admin should be able to perform for users on this page?
- [x] Change org affiliation
- [x] Change privileges?
- [ ] Change email address /name?
- [ ] Unlink institutional credentials?
- [ ] Change email notification prefs?
- [ ] Change/Reset password?
- [ ] Disable/Deactivate account (requires new field on table - Devise may offer something for this)

**Comment by stephaniesimms** [comment]
@briri - the only other thing i might want to be able to do is disable/deactivate an account. i'm mainly thinking about bouncing emails, but this isn't a high priority so not something we need to solve now. for dmptool users we want to place the onus of managing accounts on the users themselves so i prefer not to be able to do all the things. but i'll let @sjDCC confirm if there's anything else she needs to be able to do as super admin.

**Comment by briri** [comment]
Tasks needed:
- [x] Add active flag to users table
- [x] Update scopes in Users model to look at new flag
- [x] Override Devise authentication method in User model to prevent deactivated users from logging in
- [x] Add checkbox column to Admin -> Users page to allow admins to activate/deactivate users
- [x] Make user name column a clickable link for Super Admins so that they can edit the user's profile
- [ ] Update profile page to allow super admins access to other users' profiles
- [ ] Update mailer to skip users who are inactive
- [ ] Add unit tests for new active flag, and functional tests for controller methods

**Comment by stephaniesimms** [comment]
super admins can now edit user profile info and activate/deactivate accounts. closing but leaving here for @sjDCC to confirm all looks good.

**Comment by stephaniesimms** [comment]
make sure you're testing as a super admin @sjDCC 
![screen shot 2018-03-26 at 11 49 40 am](https://user-images.githubusercontent.com/12703638/37926293-d1611d5e-30eb-11e8-84a0-d3a8c6f01541.png)
