### ISSUE TITLE
Downloading plans

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#1293]
Please complete the following fields as applicable:

**Expected behaviour:**

Question text and section headings should download if selected in option plan components

**Actual behaviour:**

Section headings download but not question text. 

Unanswered questions download all the time, irrespective of whether selected or not.

**Steps to reproduce:**

Download plan

**Comment by dsisu** [comment]
It certainly happens on the 'Datamanagement ZonMw' template. Not sure how widely spread it is. AHRC DMP template seems to download question text.

**Comment by vyruss** [comment]
@dsisu which format are you downloading as please?

**Comment by dsisu** [comment]
Tried both pdf and Word

**Comment by dsisu** [comment]
Some clarifications:
It seems to happen in questions with multiple-choice answers. See attached plan. Question 1.1. downloads because it's not a multiple-choice answer question. Questions 1.2 and 1.3 are multiple choice and don't download correctly.
[Testing_ZonMw_after_Roadmap_release.pdf](https://github.com/DMPRoadmap/roadmap/files/1818896/Testing_ZonMw_after_Roadmap_release.pdf)

**Comment by vyruss** [comment]
@dsisu has this been fixed now?

**Comment by dsisu** [comment]
Yes. Tested on NERC and ZonMw templates.
