### ISSUE TITLE
Plan editor & read only do not see 'share' link in actions menu

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1294]
If you share a plan and make the person an Editor, they do not see the 'Share' option when they click on the list of available Actions on their My Dashboard page. They do however have access to the Share tab when they click to edit the plan.

We should update the logic so that its consistent for both. @sjDCC and @stephaniesimms which is the correct behavior? Should someone with editor access be able to access the Share tab?

**Comment by stephaniesimms** [comment]
Editor privileges include the ability to comment and make changes. They cannot invite others/share the plan. So they shouldn't see the "Share" option in the Actions menu for a plan where they only have Editor access. And they should not be able to perform any of the actions on the Share tab. If it's easy to update the logic it would be better to hide the Share tab altogether @briri - yes.

**Comment by briri** [comment]
Ok. thanks for the clarification @stephaniesimms.

**Comment by stephaniesimms** [comment]
almost working as expected @briri - Read only and Reviewer roles are okay. But as an Editor I shouldn't see the Share action or have access to that tab either (see screenshot below). Editors and Read Only privileges should be the same with regard to sharing.

![screen shot 2018-03-27 at 12 08 10 pm](https://user-images.githubusercontent.com/12703638/37989195-9d27513a-31b7-11e8-898a-d6c26cbc4201.png)

**Comment by sjDCC** [comment]
Permissions and views all look good to me now. Closing out
