### ISSUE TITLE
Sample answer display in AHRC DMP template

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#1296]
Please complete the following fields as applicable:

**Expected behaviour:**

Uni of Edinburgh/AHRC DMP template - sample answers should display within text box

**Actual behaviour:**

Sample answers expand beyond box, to the right

![image](https://user-images.githubusercontent.com/2138956/37475519-cfc25ec4-286a-11e8-89f9-585500fc6311.png)

**Steps to reproduce:**
View/Edit UoE customised AHRC DMP Template

**Comment by stephaniesimms** [comment]
i can't reproduce this on roadmap stage. maybe good to retest now that template customization fixes are in place @dsisu and @sjDCC

**Comment by sjDCC** [comment]
I've tried to test this but Edinburgh doesn't have any sample answers for AHRC as far as i can see. Perhaps this was linked in with another bug?

@dsisu could you test and close this out please?

**Comment by dsisu** [comment]
Doesnt seem to be happening any more. Tried both Mozilla Firefox and Google Chrome.
