### ISSUE TITLE
BBSRC template - adding example answers (annotations)

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#1297]
Please complete the following fields as applicable:

**Expected behaviour:**

UoE/Customised BBSRC template should display example answers entered by org admin (Kerry Miller)

**Actual behaviour:**

Kerry Miller entered example answers twice, saving after every entry. Example answers do not display.

**Steps to reproduce:**

Not sure. Check database to see if Kerry is editing an older version (draft) but viewing another. BBSRC template appears not to be customised.

**Comment by dsisu** [comment]
I was able to reproduce the error. Customised the template by adding a sample answer. Saved it, could view the answer. Tried to create a plan based on the template, answer wasn't available. Went back to customising the BBSRC template, example answer had gone.

**Comment by stephaniesimms** [comment]
this should be fixed by recent template customization bug fixes. can you confirm @dsisu and @sjDCC ? if so we can close this issue.

**Comment by sjDCC** [comment]
This seems fine to me so closing out. @dsisu by all means check the specific BBSRC data to validate too
