### ISSUE TITLE
Migration to en_GB for existing sites

### ISSUE THREAD

**Issue by raycarrick-ed** [DMPRoadmap/roadmap#130]
seeds.db has en_GB in it but existing sites will need a migration to change existing language table.

**Comment by xsrust** [comment]
DigitalCurationCentre/roadmap@95510d3c76e3ec7c34904e500c097972a2d9ff78 

fixed the rake migrate:seed task to properly seed the table with languages for the future

added rake migrate:fix_languages to replace the incorrectly formatted languages with correctly formatted ones, and ensure all languages are in the db.

**Comment by xsrust** [comment]
this rake task will need to be added to the migration instructions for existing sites

**Comment by vyruss** [comment]
Updated (instructions in wiki)[https://github.com/DMPRoadmap/roadmap/wiki/Upgrading-from-DMPonline_v4/].

**Comment by briri** [comment]
This looks good @raycarrick-ed.

**Comment by briri** [comment]
I don't think this one requires any UI testing so I am closing

**Comment by Ebrahim1010** [comment]
#Error we get when running rake db:migrate in step 1 of the migration - DMPonline to DMProadmap migration

D, [2019-03-25T10:41:07.666885 #23753] DEBUG -- : (14.8ms) SELECT COUNT() FROM languages WHERE languages.default_language = 1
D, [2019-03-25T10:41:07.695116 #23753] DEBUG -- : Language Load (0.3ms) SELECT languages. FROM languages WHERE languages.default_language = 1 ORDER BY languages.id ASC LIMIT 1
rake aborted!
I18n::InvalidLocale: :en_GB is not a valid locale
/var/lib/gems/2.3.0/gems/i18n-0.7.0/lib/i18n.rb:284:in enforce_available_locales!' /var/lib/gems/2.3.0/gems/i18n-0.7.0/lib/i18n.rb:151:in translate'

Workaround?

**Comment by vyruss** [comment]
@Ebrahim1010 perhaps try to run `migrate:seed` before `db:migrate` or add a row with `en_GB` in the `languages` table manually?

**Comment by Ebrahim1010** [comment]
@vyruss Thank you! I've managed to get past that step. I now have a new error:
01465524@devubudmp001:/opt/roadmap$ sudo bundle exec rake db:migrate
/var/lib/gems/2.4.0/gems/sprockets-3.7.0/lib/sprockets/digest_utils.rb:47: warning: constant ::Fixnum is deprecated
/var/lib/gems/2.4.0/gems/sprockets-3.7.0/lib/sprockets/digest_utils.rb:51: warning: constant ::Bignum is deprecated
/var/lib/gems/2.4.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:110: warning: constant ::Fixnum is deprecated
/var/lib/gems/2.4.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:111: warning: constant ::Bignum is deprecated
/var/lib/gems/2.4.0/gems/concurrent-ruby-1.0.2/lib/concurrent/map.rb:206: warning: constant ::Fixnum is deprecated
/var/lib/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:21: warning: constant ::Fixnum is deprecated
rake aborted!
TypeError: wrong argument type Class (expected Module)
/var/lib/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:23:in `include'
/var/lib/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:23:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:22:in `class_eval'
/var/lib/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:22:in `block in <top (required)>'
/var/lib/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:21:in `each'
/var/lib/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:21:in `<top (required)>'
/var/lib/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8.rb:22:in `require'
/var/lib/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8.rb:22:in `<top (required)>'
/var/lib/gems/2.4.0/gems/therubyracer-0.12.2/lib/therubyracer.rb:1:in `require'
/var/lib/gems/2.4.0/gems/therubyracer-0.12.2/lib/therubyracer.rb:1:in `<top (required)>'
/var/lib/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `require'
/var/lib/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/var/lib/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'
/var/lib/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'
/var/lib/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'
/var/lib/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'
/var/lib/gems/2.4.0/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
/opt/roadmap/config/application.rb:18:in `<top (required)>'
/opt/roadmap/Rakefile:5:in `require'
/opt/roadmap/Rakefile:5:in `<top (required)>'
/var/lib/gems/2.4.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by vyruss** [comment]
@Ebrahim1010 are you perhaps missing some dependency or didn't run `bundle install`? If that doesn't work, please open a new issue describing exactly what steps you are taking to migrate, so that the team can help you.

**Comment by xsrust** [comment]
@Ebrahim1010 It looks like your ruby version is 2.4.0 whereas the Gemfile for that branch specifies 2.2.2.  I think I remember getting a similar issue in the past.

**Comment by Ebrahim1010** [comment]
I'm following the steps provided on the roadmap site - https://github.com/DMPRoadmap/roadmap/wiki/Upgrading-from-DMPonline_v4

**Comment by Ebrahim1010** [comment]
@xsrust I tried that, not working for me
