### ISSUE TITLE
Enable API for org admins to generate usage statistics

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#1301]
Please complete the following fields as applicable:

**Expected behaviour:**

Org admins should be able to generate usage statistics

**Actual behaviour:**

They can't generate stats because they don't have API enabled

![image](https://user-images.githubusercontent.com/2138956/37480407-17dbd08a-2877-11e8-9ac2-34e07bbafc0d.png)

One user query has already been received.

**Steps to reproduce:**

N/A

I guess the solution is to find all org_admins and enable API for them.

**Comment by briri** [comment]
@xsrust had built a script to provide all of the Org Admins with access to the API. If this is a new user, or they were made an admin after the new code was deployed, that script would have missed them.
You can add the appropriate API access to the user on the Admin -> Users page. Its one of the privileges in the Org Admin section.

**Comment by dsisu** [comment]
@briri Thanks! Didn't know this. Unless anybody has anything else to say, we can close this I guess?

**Comment by vyruss** [comment]
I can confirm it's been done @dsisu

**Comment by Ebrahim1010** [comment]
@briri I added the API access on the user admin section. I still see the notification about the API when trying to generate the stats.
<img width="1267" alt="Screen Shot 2019-11-26 at 13 57 24" src="https://user-images.githubusercontent.com/47170940/69629135-b6e54f00-1054-11ea-900a-140fa2e82a47.png">

**Comment by xsrust** [comment]
@Ebrahim1010 

I'm responding on your more-recent comment reguarding this issue you're having as it seems more up to date:
https://github.com/DMPRoadmap/roadmap/issues/1243

In future, could you open a new issue to keep the concerns about the problem your having in the one place?   You can reference other issues by typing `#` followed by the issue number, i.e. #1243   to link to the related  issues.
