### ISSUE TITLE
Plan#readable_by?(user_id) method needs refactoring

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#1305]
**Expected behaviour:**
A plan readable by an user should look for one of the following roles (creator, administrator, editor, commenter) in roles table ONLY. 
**Actual behaviour:**
It is doing that but also checking if:
- user.can_super_admin?
- user.can_org_admin? && belongs to the same org of any owner or coowner

A more adequate place to locate the extra lines (https://github.com/DMPRoadmap/roadmap/blob/master/app/models/plan.rb#L379) should be to include these as part of a policy. Note, if these lines are repeated in multiple policy methods, the creation of a concern would be a better candidate.

**Comment by briri** [comment]
just noting that the 'reviewer' role should also be able to read a plan

**Comment by jollopre** [comment]
We need to prioritise this ticket ASAP. One of our instances running the code has strict private rules that prevent org_admins to see anything from a plan. We could do the following:
1. at readable_by? leave only the code that checks roles against the user
2. Add a new perm (e.g. read_org_plans)
3. Modify plan_policy#edit to include use.super_admin? || user.read_org_plans?

**Comment by Bodacious** [comment]
@briri Is this ticket still priority?

**Comment by magdalenadrafiova** [comment]
@briri is this still an issue? Org admins, super admins can see the plans when shared, the user can assign different collaborators so I am not sure whether this is still applicable or whether I understand this issue correctly

**Comment by briri** [comment]
not sure @magdalenadrafiova. @xsrust there is a comment above about one of your instances having an issue. If that is no longer an issue I think we can close.

**Comment by xsrust** [comment]
Looks like the current code for this takes into consideration the `super_admins_read_all` and `org_admins_read_all` variables from the branding-file, so our needs should be met there.
https://github.com/DMPRoadmap/roadmap/blob/58f6b7692c29e2d1af4a189ae244a55a8557e495/app/models/plan.rb#L380-L401
