### ISSUE TITLE
View all (templates, users, etc) button should take user back to previous page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1308]
Currently, when I click to edit a user account, template, etc and then use the 'View all' button to go back to the main table it reloads the full table from page 1. Desired behavior is to have the 'View all' button take me back to the specific page I started from so I can view the updated/changed user, template, etc.

This may be a separate issue, but:
I would also expect to be taken back to the specific page I started from when I complete an action by clicking Save or Submit (e.g. Publish a template, save user or org profile details, etc). Current behavior for most of these actions reloads the full table from page 1 and I have to go searching to find the updated record.

**Comment by stephaniesimms** [comment]
this might be fixed after template refactoring. leaving here to test and verify before closing.

**Comment by sjDCC** [comment]
Closing out. Is fixed.

**Comment by xsrust** [comment]
Just tested this on DMPOnline-Test, and I do not get this page caching behavior as detailed in  the ticket.

To reproduce:
- Go to Admin Users Page
- Visit page 5 and select a random user to Edit
- Hit view all Users
- You are returned to page 1, not page 5 which had the user you were editing

@sjDCC is this no longer desired, or do we want to re-open this?

**Comment by sjDCC** [comment]
When we tested this, it was working for templates which seemed more important as you need to return to the 'view all' page to publish. It wasn't working for users but we closed out nonetheless as we couldn't think of a case when you would need to view that specific user again. When you make any changes in the account the page is reloaded and saved changes are visible already before you click 'view all'.

If it's trivial we can re-open and implement so user is returned to the specific 'view all' page with content they were editing. That would ensure consistency. Happy to ignore though if it's not a quick fix. In your court to decide @xsrust
