### ISSUE TITLE
Super Admin: Define minimum functionality

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#131]
What is the minimum functionality that the Super Admin interface must offer?

- Edit Users table
- Edit Templates table
- Edit Orgs table
- Edit Guidance table (?)

**Comment by sjDCC** [comment]
It's possibly only the user and orgs tables we need to use to add new organisations and administer accounts. If I ever edit templates or guidance, I do it via the admin (by changing my affiliation to the relevant funder/org), not super admin area. The only thing I do related on super admin is adjust settings for templates (page limit, font size etc) but we have another issue to add this functionality to the admin area.

**Comment by vyruss** [comment]
Note that the new super admin area is very flexible and we can add/remove models to its menu at will in a matter of minutes.
