### ISSUE TITLE
Display a spinner when waiting for AJAX requests to be completed

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1310]
Users have reported confusion when they click, e.g., to expand all accordions on the write plan page or edit a template, and the action takes a long time to be completed. Currently there is no indication that anything is happening. On Tues call we discussed adding a spinner to notify users that the AJAX request is being processed.

**Comment by jollopre** [comment]
@stephaniesimms just to clarify, the loading of the pages should not really need any spinning wheel, if they are slow we have to look at other WHYS (e.g. loading too much data into THE DOM that is not really necessary, heavy functions in JS side that block the main thread, #1263, etc).

This issue should be described as "Display spinning wheel while awaiting for AJAX requests to be completed" (e.g. anytime we move across pages in paginable tables)

**Comment by stephaniesimms** [comment]
ok @jollopre, I updated the name and description to clarify
