### ISSUE TITLE
Update roadmap from DMPonline_v4

### ISSUE THREAD

**Issue by jafamo** [DMPRoadmap/roadmap#1312]
I am trying to update to roadmap from DMPonline following the guide, but these commands are not available on step 4 in my server ( ubuntu 16.04 )

> ruby 2.3.1p112
> rails 4.2.7
> bundler 1.16.1

[wiki Upgrading-from-DMPonline_v4 ](https://github.com/DMPRoadmap/roadmap/wiki/Upgrading-from-DMPonline_v4)
```
rake migrate:init_plan_visibility
rake migrate:plan_data_contacts:
rake migrate:move_shibs
rake upgrade:v0_3_3
```

What was he supposed to do at this point?
Can I continue without this commands?

**Comment by jollopre** [comment]
@xsrust updated the documentation at [wiki](https://github.com/DMPRoadmap/roadmap/wiki/Upgrading-from-DMPonline_v4) and the user was able to continue with the steps until the issue #1315.
