### ISSUE TITLE
Search is case sensitive

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#1319]
Please complete the following fields as applicable:

**Expected behaviour:**
In the admin interface, searching for organisation 'edinburgh' (all lowercase) should return University of Edinburgh and all other organisations containing the word 'edinburgh'.

**Actual behaviour:**
If you enter 'edinburgh' in the search box, all lowercase, it finds no results. If you enter 'Edinburgh' (title case) it returns three organisations. 

Same happens if you search for users.

**Steps to reproduce:**

**Comment by stephaniesimms** [comment]
related issue #1235 will address search and sorting issues for tables.
I can't find any tables (Orgs or others) while testing on roadmap stage where search is case sensitive, however. Closing issue for now but please add a note in the related issue above if you find something in roadmap that should fixed at the same time.
