### ISSUE TITLE
Create/reinstate mandatory fields

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1326]
This needs to be addressed together with #1217 to ensure someone receives the feedback request emails. 

Make the following fields mandatory (marked with red asterisk):
- Organization details: Admin contact email, Contact link text (if link was entered), Org Config Info/Org Type
- Templates: Template title, Phase title, Section title, Question text, Question format
- Guidance (related #1212 to require one theme) - Guidance group name, Guidance text

**Comment by briri** [comment]
Drop formtastic gem and ensure no forms are using it

**Comment by stephaniesimms** [comment]
Org details page has a few issues:
- the Org URL and link text should NOT be mandatory fields
- is there some way to ensure a user inputs a valid contact email? currently i can enter anything and save successfully (see screenshot)

![screen shot 2018-06-13 at 10 13 52 am](https://user-images.githubusercontent.com/12703638/41367063-d3a6af12-6ef2-11e8-97d8-2120ff7ff287.png)

**Comment by briri** [comment]
The URLs are a bit tricky I guess. IF the user has entered a value into either of the boxes it displays the red asterisks. The validation though is just enforcing that if you enter a URL that you also add text and vice versa. Try adding a new link (line appears without asterisks), add some text to either box (asterisks appear), delete the text from both boxes (asterisks disappear)

**Comment by stephaniesimms** [comment]
Ah ok @briri - as long as the red asterisks don't appear for a first-time user navigating to this page to enter Org details (will test to confirm). I understand now that I'm seeing asterisks because these fields already have content. No need to devise fancy solutions.

The other issue with validating the contact email, if possible, is more important anyway.

**Comment by stephaniesimms** [comment]
now i see what's happening with section asterisks. they disappear after I click to Save the Section title. it would be better if they don't disappear after clicking Save since the Phase and Question asterisks above and below the Section are always visible. this is a small point but better to be consistent so as not to confuse users.

Asterisks appear when creating Section
![screen shot 2018-06-18 at 1 44 33 pm](https://user-images.githubusercontent.com/12703638/41561096-d31cb1d6-72fd-11e8-9f09-8e01d98bb37e.png)

Asterisks for Section disappear after I click Save
![screen shot 2018-06-18 at 1 44 57 pm](https://user-images.githubusercontent.com/12703638/41561101-d603b980-72fd-11e8-971d-e3386dd0f9f5.png)

**Comment by stephaniesimms** [comment]
@briri noted that this is a more complicated problem w/this tinyMCE editor in the Guidance section. will create a separate bug issue and consider this issue to be closed.
