### ISSUE TITLE
Template Versioning - Migration and task

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#1331]
Two columns for the current templates table have to be renamed:

- migrated: Used to migrate from DMPv4 to roadmap
- dmptemplate_id: Random integer generated anytime a new template is created. Essentially, permits differentiate the different family of templates that the system has.

At our dev-meetings, we agreed to create a migration task that renames migrated to archived and dmptemplate_id to family_id. Below the purpose of the renamed columns:

- archived: To accommodate those templates inherited from the previous DMPv4 code and also to permit "deleting" a template from the site.
- family_id: this field can be either nil (for a new template created) or an existing id from the templates table. Effectively is a self-join relation.

We also have to create a task to curate the data from the table accordingly. For instance, change the values for each new family_id to refer to a valid template id.

And refactor any reference to migrated or dmptemplate_id to use archived or family_id instead. 

This ticket relates to #1128

**Comment by jollopre** [comment]
dirty column has to go away too since we are proposing deferring the template versioning until an action that changes the status of an object happens.

**Comment by briri** [comment]
Based on Dev discussion on 4/4/18:
We will not change the way the dmptemplate_id (family_id) is created or managed while cloning templates. We will only rename it to 'family_id' and add it into a transaction. We can reevaluate switching it to use the template row id at a later date.

**Comment by stephaniesimms** [comment]
closing issues that can't be tested in the UI
