### ISSUE TITLE
Reload Customizable templates tab after publishing

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1338]
When I publish a customization, the page reloads the Org templates table/tab (note the wrong tab is selected in the screenshot below). This occurs for both Super Admins and Org Admins.

Desired behavior is to reload the Customizable templates table so users can see that their customization has been published.

![screen shot 2018-03-29 at 1 42 34 pm](https://user-images.githubusercontent.com/12703638/38112542-1f92f2d2-3357-11e8-9ad1-2886955daaf2.png)

**Comment by stephaniesimms** [comment]
this is working on dmptool stage as i'm testing. i'm going to reopen just so we can UAT everything together on roadmap stage and confirm.

**Comment by stephaniesimms** [comment]
this is working as expected now on roadmap stage. closing issue.

**Comment by sjDCC** [comment]
all works
