### ISSUE TITLE
rake gettext:find not collecting everything

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1339]
The `rake gettext:find` task doesn't seem to be picking up everything.

The following 'Private: ...' section is not found in the app.pot file but the 'Organisation:' and 'Private:' ones are.

```ruby
    <div class="form-group col-xs-8">
      <div class="radio">
        <%= f.label :visibility_privately_visible, raw("#{f.radio_button :visibility, :privately_visible}\
        #{_('Private: visible to me, specified collaborators and administrators at my organisation')}") %>
      </div>
      <div class="radio">
        <%= f.label :visibility_organisationally_visible, raw("#{f.radio_button :visibility, :organisationally_visible} #{_('Organisation: anyone at my organisation can view')}") %>
      </div>
      <div class="radio">
        <%= f.label :visibility_publicly_visible, raw("#{f.radio_button :visibility, :publicly_visible} #{_('Public: anyone can view')}") %>
      </div>
    </div>
    <div class="col-xs-8">
      <%= f.submit(_('Update'), style: 'display:none') %>
    </div>
```

Interestingly though, some older versions are still in the app.pot:
```yaml
msgid "Private: restricted to me and my collaborators"
msgstr ""

msgid "Private: restricted to me and people I invite."
msgstr ""
```

**Comment by briri** [comment]
Thanks to @stephaniesimms for pulling together this list of strings that are being missed.

**Emails**
There is code in place that forces the system to use the default language when creating email messages. We should switch this to use the recipient's preferred language (or the default if none is specified)

**Notification messages**
Notification messages all partial and strange (some screenshots below)
![screen shot 2018-04-05 at 10 53 14 am](https://user-images.githubusercontent.com/12703638/38382757-a185bbd6-38bf-11e8-83b7-7bd5d878c7e9.png)
![screen shot 2018-04-05 at 10 59 26 am](https://user-images.githubusercontent.com/12703638/38383113-779a142e-38c0-11e8-83c3-e0459f3772ee.png)
![screen shot 2018-04-05 at 11 12 13 am](https://user-images.githubusercontent.com/12703638/38383771-398820c0-38c2-11e8-8d6c-d783e6bee437.png)

**Checkboxes and Radio buttons**
We've been using string interpolation as a practice to create Bootstrapped checkboxes and radio buttons that still make use of Rails' ActionView form helpers to create these elements. We will need to adjust this by either using a '+' to combine the strings or set the label text as a variable 
this is happening for these elements across the entire site. Some examples:
![screen shot 2018-04-05 at 11 08 05 am](https://user-images.githubusercontent.com/12703638/38383573-b8838320-38c1-11e8-83f5-4be22de434ed.png)
![screen shot 2018-04-05 at 11 19 55 am](https://user-images.githubusercontent.com/12703638/38384211-676eab5c-38c3-11e8-85ef-5b53a1c9def7.png)

**Specific areas of text**
The following text is likely not properly marked up for Gettext: 

'See the full list' link for guidance selection
![screen shot 2018-04-05 at 11 10 39 am](https://user-images.githubusercontent.com/12703638/38383745-2b518ab4-38c2-11e8-8b09-345f919843a1.png)

Autosave message temporal text 'just now' ... 'less than a minute ago'
![screen shot 2018-04-05 at 11 15 11 am](https://user-images.githubusercontent.com/12703638/38383960-b82c4870-38c2-11e8-8304-bc7516bb4894.png)

Some headers on static pages (Terms of Use & Privacy e.g.)
![screen shot 2018-04-05 at 11 27 50 am](https://user-images.githubusercontent.com/12703638/38384601-73460258-38c4-11e8-90e6-e0105008e685.png)

Public plans description
![screen shot 2018-04-05 at 11 29 07 am](https://user-images.githubusercontent.com/12703638/38384689-aca3e556-38c4-11e8-998f-a525ab29e8bb.png)

New columns added to Users table
![screen shot 2018-04-05 at 11 34 28 am](https://user-images.githubusercontent.com/12703638/38384940-5eb5aa68-38c5-11e8-83b5-2b06fbba6241.png)

Headings for Edit user privileges modal
![screen shot 2018-04-05 at 11 35 16 am](https://user-images.githubusercontent.com/12703638/38384975-7a19c8c0-38c5-11e8-8cee-731183209e1c.png)

Header and button text for editing user profile
![screen shot 2018-04-05 at 11 36 48 am](https://user-images.githubusercontent.com/12703638/38385061-b4ecbe8a-38c5-11e8-9605-07cd5afc9fad.png)

Header for 'Usage statistics'
![screen shot 2018-04-05 at 11 38 35 am](https://user-images.githubusercontent.com/12703638/38385131-ed4ed31c-38c5-11e8-9430-7e04b0d05175.png)

Missed link text for Templates page 'All' 'Published' etc... but yes for Customization tab links???
![screen shot 2018-04-05 at 11 39 15 am](https://user-images.githubusercontent.com/12703638/38385165-0a739568-38c6-11e8-897a-4a716069acca.png)
![screen shot 2018-04-05 at 11 40 07 am](https://user-images.githubusercontent.com/12703638/38385213-26c2c90a-38c6-11e8-9247-833f754e3709.png)

'Add' and 'Edit' for buttons in template customization
![screen shot 2018-04-05 at 1 53 27 pm](https://user-images.githubusercontent.com/12703638/38391350-d9ce3950-38d8-11e8-974c-126090cdacb7.png)

**Comment by briri** [comment]
The timeago.js files are also not getting discovered by gettext. We also peg the language to en_GB but should instead add the current user's language of choice to the json object defined at the bottom of application.rb and so that its available in the constants.js file.

**Comment by briri** [comment]
also related to #166 which would pull the bootstrap, devise and contact_us strings into the app.pot

**Comment by briri** [comment]
found a case where the label_tag was using a symbol instead of translatable text in the 'views/users/_admin_grant_permissions.htmlerb'
`<%= label_tag :organisational_admin_privileges %>` should be `<%= label_tag _('Organisational admin privileges') %>`

**Comment by benjaminfaure** [comment]
Hello, when migrating from roadmap 0.3 to 1.0 I had some issues with the French version. I had the following error : 
```
I18n::MissingTranslationData - translation missing: fr.date.formats.default:
  i18n (0.9.5) lib/i18n.rb:326:in `handle_exception'
  i18n (0.9.5) lib/i18n.rb:172:in `translate'
  i18n (0.9.5) lib/i18n/backend/base.rb:81:in `localize'
  gettext_i18n_rails (1.8.0) lib/gettext_i18n_rails/backend.rb:30:in `method_missing'
  i18n (0.9.5) lib/i18n.rb:258:in `localize'
```

Unless I missed it, there is no task to update the abbreviation in the database from `fr `to `fr_FR`. I had to update the row in the db. (In the seed file, the abbreviation is `fr` too).

Some YML file are still using "fr" as a prefix for the French language.  Some files may not be used anymore : 
    - `config/locales/devise/devise.fr.yml` => this one is used for devise notifications.
    - `config/locales/contact_us/contact_us.fr.yml`
    - `config/locales/devise/devise_invitable.fr.yml`
    - `config/locales/bootstrap/fr.bootstrap.yml`
You should probably change the prefix in these files (and update the name).

**Comment by stephaniesimms** [comment]
can't test UI but will verify as i monitor changes to the portuguese translation in dmptool. closing issue.
