### ISSUE TITLE
Template Versioning -  Slimming down controllers 

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#1340]
Below are the actions associated to each controller that have to be carefully refactored:

**Templates controller:** 
  - templates_controller#edit has to be refactored to just serve the edit.html.erb view, i.e. the logic to generate a new version should go be called at templates_controller#update
  - templates_controller#destroy only allows to delete a template if is the latest (e.g. current) and has no plans associated. This action should be renamed to archive and should allow to archive any template regardless of whether it has plans associated or not.
  - templates_controller#customize has to be re-factored (e.g. remove generate a unique dmptemplate_id identifier, remove dirty flag, remove deep assignment modifiable to false for phases, sections, questions)
  - templates_controller#transfer_customization (ports over changes applied to the template is customised_of, the fuzzy logic to determine new phases, sections or questions added needs a check)
  - templates_controller#copy (e.g. remove generate a unique dmptemplate_id identifier)
  - templates_controller#publish (e.g. remove dirty flag assignment)

**Phases controller:**
  - phases_controller#admin_add (should be renamed to admin_new)
  - phases_controller#admin_update (should share the logic to generate a new template version if template is published)
  - phases_controller#admin_create (should share the logic to generate a new template version if template is published, remove dirty flag, modifiable flag should be default true)

**Sections controller:**
  - sections_controller#admin_create (should share the logic to generate a new template version if template is published)
  - sections_controller#admin_update (should share the logic to generate a new template version if template is published)

**Questions controller:**
  - questions_controller#admin_create (should share the logic to generate a new template version if template is published)
  - questions_controller#admin_update (should share the logic to generate a new template version if template is published)

**Annotations controller:**
  - annotations_controller#admin_update (should share the logic to generate a new template version if template is published)

**Use adequate http verbs for**
 - use POST instead of GET for templates_controller#customize
 - use POST instead of GET for templates_controller#copy
 - use PUT instead of GET for templates_controller#publish
 - use PUT instead of GET for templates_controller#unpublish

**Comment by briri** [comment]
I'd also like to see us move away from the 'admin_' naming convention for the phase/section/question/annotation controllers. We should just use the verbs. This would require moving some of the actions in those controllers to a more appropriate place (e.g. phases_controller#edit generates the edit plan page. That method belongs in the plans_controller)

**Comment by jollopre** [comment]
I'm happy to add the renaming from 'admin_' to new controllers at org_admin folder as part of this issue...

**Comment by briri** [comment]
closing this one since it was broken down into multiple tickets
