### ISSUE TITLE
Template Versioning - Refactoring template model

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#1341]
- Renamed scope methods:
   - archived instead of valid,
   - latest instead of current
   - published instead of live. NOTE, published scope method could accept family_id to merge live and published methods into just one.
- Adds customize class method to accommodate the customization action for templates controller.
- Adds transfer_customisation class method to accommodate the transfer_customization action for templates controller
- Adds keep_or_generate_version(family_id) class method to be reused across multiple controllers (e.g. template, phase, section, question, annotation)
- deep_copy add options as an splat argument to tweak the cloning (e.g. modifiable flag, published, is_default, etc)
- refactor set_creation_defaults method, i.e. remove the random generation of dmptemplate_id

**Comment by briri** [comment]
when and where would the family_id/dmptemplate_id be created if we remove that functionality from the set_creation_defaults method?

**Comment by jollopre** [comment]
the family_id is nil for a new template and for a versioning is the column id autogenerated by the db. Does it make sense?

**Comment by briri** [comment]
also update the Plan model and remove the 'dmptemplate' it seems unnecessary (also update any references to it!) and move the 'base_template' method from there to the Template model if its even necessary.

**Comment by stephaniesimms** [comment]
closing issues that can't be tested in the UI
