### ISSUE TITLE
Add Funder & Org abbreviation before "Guidance" word in customised templates

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#1343]
Please complete the following fields as applicable:

**Expected behaviour:** Guidance when using a customised template should show the origin of the guidance

**Actual behaviour:** Funder guidance appears as issued from customising organisation 

**Screenshot:**
![image](https://user-images.githubusercontent.com/18707439/38319798-a60e4d34-382a-11e8-957c-52adb3f444b3.png)

**Comment by stephaniesimms** [comment]
testing on dmptool stage and here is what i see @briri (screenshot below):
- the appropriate funder or org name appears before "guidance", but the tab is still renamed with the org name when it should retain the funder name. so in the example below, the first tab should still be "NIH" (instead it's changed to the customizing org - UCD)

![screen shot 2018-04-05 at 9 59 49 am](https://user-images.githubusercontent.com/12703638/38380521-dcaa97e2-38b8-11e8-8a12-3bad0f3e51ea.png)

**Comment by stephaniesimms** [comment]
working as expected now on roadmap stage. closing issue.

**Comment by sjDCC** [comment]
guidance all showing right for me now
