### ISSUE TITLE
Customisation example answers do not appear when editing plan

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#1344]
**Expected behaviour:** When you edit a plan using a customised template, you should see either:
    * Both the funder's and the customising org's example answers
    * The customising org's example answer

**Actual behaviour:** You only see the funder's example answer and the other one is never displayed

**Screenshot:**
![image](https://user-images.githubusercontent.com/18707439/38319966-2893ee80-382b-11e8-9d60-f1cd5f36d91c.png)

**Comment by stephaniesimms** [comment]
testing on dmptool stage and here is what i see @briri  (screenshot below):
- example answers now appear w/appropriate org label, but there is also a label w/the funder name and a blank space if there's no funder-provided sample answer below every question. desired behavior is to only display an example answer for the funder or the org if one has been provided.

![screen shot 2018-04-05 at 9 59 49 am](https://user-images.githubusercontent.com/12703638/38380437-8c372078-38b8-11e8-9cec-c893cea82000.png)

**Comment by stephaniesimms** [comment]
this now works as expected on roadmap stage. closing issue.

**Comment by sjDCC** [comment]
Yay! This is fantastic to see. We've been asked to display multiple example answers in the past so we've added a new feature here. One to promote in the release notes and blog ;-)

Looks great!
![example-answers](https://user-images.githubusercontent.com/6169940/38814600-c3b05310-4189-11e8-9a2d-e5cc000d240d.PNG)
