### ISSUE TITLE
Set focus to response messages

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#135]
The site does not draw focus to messages that appear after the user makes a form submission (e.g. profile updated) and so a screen reader does not notify the user of the result of the their submission.

We should set the focus to these messages so that a screen reader notifies the user.

From old Pivotal ticket: https://www.pivotaltracker.com/story/show/131688927

**Comment by vyruss** [comment]
This is implemented via [aria-roles and aria-attributes](https://www.w3.org/TR/html-aria/#allowed-aria-roles-states-and-properties), I believe

**Comment by briri** [comment]
Just focus on non org-admin/super-admin pages for this first pass

**Comment by briri** [comment]
related to #175 and #457

**Comment by briri** [comment]
It may be enough to just give the messages the `role="alert"` attribute
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role

**Comment by briri** [comment]
Gave the standard `roadmap-info-box` and `roadmap-alert-box` the status and alert roles.

We will need to go into the forms and add `role=alert` to any JS triggered error messages (see how I implemented this on the `javascripts/views/plans/index.js` and `role=status` to tooltips. It would be nice if this could be made generic and attached to those elements on the `javascripts/dmproadmap/utils.js` file

**Comment by sjDCC** [comment]
Not entirely sure how to test this, but expect it will be covered sufficiently by accessibility test

**Comment by stephaniesimms** [comment]
closing pending accessibility test
