### ISSUE TITLE
Organisational logo appears blurry (resized more than once)

### ISSUE THREAD

**Issue by tomhigginsuom** [DMPRoadmap/roadmap#1357]
When an organisational logo is uploaded by an org admin the logo is initially resized to be 75px tall by Dragonfly.

When the logo is later displayed to a user it is resized again to be 100px tall, resulting in a blurry image.

Both sizes of logo can be viewed on the 'Organisation details' page - note that the logo at the top appears blurry:

<img width="800" alt="org-logo-display" src="https://user-images.githubusercontent.com/11716796/38503517-2cb59e18-3c0a-11e8-96bc-2414690f8a52.png">

I tested by uploading a logo which was already 100px tall - the resulting 100px tall image displayed to the user is of noticeably lower quality than the source image:

![logo-100px](https://user-images.githubusercontent.com/11716796/38503501-25ee23b6-3c0a-11e8-98b4-98d722724bcb.png)

**Comment by briri** [comment]
thanks @tomhigginsuom. We have noticed similar behavior on the DMPTool site. 

It may be a good idea to make both the Dragonfly and CSS/HTML sizing configurable in the `config/branding.yml` file.

**Comment by briri** [comment]
removing this from the board since its included now in v1.0.4
