### ISSUE TITLE
Download plan as text file failing

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1358]
Users are unable to export their plans as Text.  

![screen shot 2018-04-09 at 8 30 15 am](https://user-images.githubusercontent.com/1204467/38507035-48f0743e-3bd0-11e8-88be-818cbbd608b2.png)

**Comment by stephaniesimms** [comment]
tested on roadmap stage and working now.

**Comment by sjDCC** [comment]
working fine for me too
