### ISSUE TITLE
Customized version of funder template not being used

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1363]
Please complete the following fields as applicable:

**Expected behaviour:** 
The user is given the customized version of the funder template (if one is available for the research org they select)

**Actual behaviour:**
The user is sometimes given the base funder templates.

**Steps to reproduce:**
This may be specific to the deployment and its Ruby/Rails versions.
- As an org admin, login and customize a funder template
- Publish your customization
- Create a new plan (select the customizing org as the research org and then select the funder)

**Comment by briri** [comment]
The issue is with the way we were gathering available templates. If a customization was found for a particular template we were replacing it within the same array we are iterating over.
```ruby
# Load the funder's template(s)
templates = Template.valid.publicly_visible.where(published: true, org_id: funder_id).to_a

unless org_id.blank?
  # Swap out any organisational cusotmizations of a funder template
  templates.each do |tmplt|
    customization = Template.valid.find_by(published: true, org_id: org_id, customization_of: tmplt.dmptemplate_id)
    if customization.present? && tmplt.created_at < customization.created_at
      templates.delete(tmplt)
      templates << customization
    end
  end
end
```

**Comment by sjDCC** [comment]
All working fine on our end
