### ISSUE TITLE
Issues in Internet Explorer

### ISSUE THREAD

**Issue by pherterich** [DMPRoadmap/roadmap#1365]
Please complete the following fields as applicable:

**Expected behaviour:** Users can use DMPOnline in Internet Explorer 11 as this is the browser installed on standard university machines.

**Actual behaviour:** Text fields that provide editing options don't show.
![dmponline_iexplorer_issue](https://user-images.githubusercontent.com/8457675/38546564-e3a80eea-3ca4-11e8-8819-be74cf971df7.png)
 
**Steps to reproduce:** Log into DMPOnline in Internet Explorer and try to edit a DMP.

If Internet Explorer isn't supported by DMPOnline, a notification like the one provided by GitHub would be nice to let users know.
![github_iexplorer_notification](https://user-images.githubusercontent.com/8457675/38546706-3e5d62b8-3ca5-11e8-9dae-f0c28f928d37.png)

**Comment by vyruss** [comment]
I can confirm this occurs on IE11.

**Comment by vyruss** [comment]
Nice catch, well done @jollopre !

**Comment by vyruss** [comment]
Tested working on DMPonline

**Comment by stephaniesimms** [comment]
found a crossbrowsertesting.com tool and confirmed that all is working on roadmap stage. closing issue.
