### ISSUE TITLE
Make question text an html heading

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#137]
In the "Answer Questions" area, the questions might be cumbersome to navigate via screen reader. Change the questions to headings.

From old pivotal ticket: https://www.pivotaltracker.com/story/show/131647527

**Comment by briri** [comment]
This would be difficult to do due to the way Bootstrap uses heading tags to denote accordion sections. We should though set them as the labels for their corresponding text areas.

**Comment by sjDCC** [comment]
@briri - could you check whether this is done. we think so

**Comment by briri** [comment]
I think so. The questions are at least labels now so screen readers should properly connect them to the appropriate answer field.
