### ISSUE TITLE
Refactor Sections controller

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1373]
Refactor the phases controller:
- Move the controller code to a new namespaced controller `org_admin/sections_controller.rb` 
- remove the `admin_` prefix from those actions
- update the routes.rb file and policies according to the above changes
- update all of the `old_route_path` references to the `new_route_path`
- update the tests

related to #1340

**Comment by stephaniesimms** [comment]
closing issues that can't be tested in the UI
