### ISSUE TITLE
Add a new Versionable concern

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1376]
Add a new Versionable concern that can be used by the Phases, Sections, Questions and Annotations controllers. This concern should use the newly refactored template model's `new_version` method when the user actually updates, creates or destroys a phase, section, question or annotation.

Versioning should occur regardless of whether or not the template is a customization.

Also add tests!

related to #1340

**Comment by stephaniesimms** [comment]
closing issues that can't be tested in the UI
