### ISSUE TITLE
DB Cleanup

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1382]
this ticket is derived from #170 

These are some general cleanup tasks for the DB that we should perform:
- Remove the old friendly_id gem from the Gemfile and drop its DB elements
  - Drop table `friendly_id_slugs`
  - Drop field `plans.slug`
- Drop the following tables which as no longer used: `file_types`, `file_uploads`, `regions`, `splash_logs`
- Remove the `sections.published` field. Templates are published, not individual sections
- Remove the `orgs.banner_text` field since it is no longer used.
- Remove the `guidances.question_id` column (and update model if necessary). Guidances stored in this table are associated with themes not questions
- Drop the old `admin` and `org_admin` records from the `perms` table and also any references to them in `users_perms` these are the old permission types which have been replaced by our more granular permissions
- Drop the `orcid_id` and `shibboleth_id` fields from the `users` table. These identifiers have been moved to the `user_identifiers` table. If necessary create a rake task to port existing data to the new DB table

Copying more notes from a duplicate issue to drop the following unused tables. There may be overlap w/bullets above:
We should drop the following tables from the database and any controllers/models/routes associated with them since they are no longer used:
- file_types
- file_uploads,
- friendly_id_slugs
- question_format_labels (part of dmptool migration that is no longer used)
- regions
- splash_logs

**Comment by Bodacious** [comment]
# Schema descriptions

This list below is the current schema for the app. I've added a description for each model and column that I was able to, and left questions where I wasn't.

## annotations
  Annotations offer guidance notes for a given Question to help Users understand the question.
  
- question_id (integer)
  Foreign key for the associated question
  
- org_id (integer)
  Indicates which Org uses this Annotation. May be different for the same question for different Orgs.
  
- text (text)
  Text content of the annotation.
  
- type (integer)
  Indicates whether this annotation is an example answer, or tips for how the question should be answered.
  
## answers
  
  Represents a particular User's answer to a particular Question.
    
- text (text)
   Content of an answer

- plan_id (integer)
  Which plan the answer is for.
  - Why is this required if we have question_id?

- user_id (integer)
  The User who left the Answer

- question_id (integer)
  The Question the Answer is in response to
  
- lock_version (integer)
  - What is this?

## answers_question_options
  Join table between Answers and QuestionOptions
  
- answer_id (integer)
  The Answer these options apply to
  
- question_option_id (integer)
  The QuestionOption that has been selected
  
## exported_plans
  
  Records instances of Users downloading Plans.
  
-  plan_id (integer)
  Foreign key for the Plan being downloaded
  
- user_id (integer)
  Foreign key for the User downloading this Plan
  
- format (string)  
  The format of the download? (e.g. "pdf")
  
- phase_id (integer)
  - What is this and why is this necessary?
  
## file_types

### Is this table used at all?

- name (string)

- icon_name (string)

- icon_size (integer)

- icon_location (string)

## file_uploads

### Is this table used at all?

- name (string)

- title (string)

- description (text)

- size (integer)

- published (boolean)

- location (string)

- file_type_id (integer)

## guidance_groups
    
### What are these and how are they used?

- name (string)

- org_id (integer)

- optional_subset (boolean)

- published (boolean)
 
## guidances
  This class keeps the information organisations enter to support users when answering questions.
  
### How is this used differently from Annotations?
  
- text (text)
  The text content provided with the Guidance
  
- guidance_group_id (integer)
  Foreign key. Which GuidanceGroup does this belong to?
  
- question_id (integer)
  Foreign key. Which Question does this Guidance apply to?
  
- published (boolean)
  Indicates whether this Guidance is viewable by non-admin Users in an Org.
    
## identifier_schemes

### What is this model for?

- name (string)

- description (string)

- active (boolean)

- logo_url (text)

- user_landing_url (text)

## languages

Represents a spoken Language recognised by the Sytem.

- abbreviation (string)
  The ISO 639-1 code and dialect modifier (if applicable) for the Language
  
- description (string)
  A human-readable descrpition of the Language
  
- name (string)
  The human name for a given Language, written in its local form (e.g. Español)
  
- default_language (boolean)
  Indicates wheher this Language is the default (English, GB) or not

## notes
    
Notes are added to Answers by Users.

### Which User Roles add Notes to an Answer? 

### How are these used exactly?

- user_id (integer)
  Foreign key, the User creating the Note
  
- text (text)
  Text content of the Note
  
- archived (boolean)
  Indicates whether this Note has been archived or not
  
- answer_id (integer)
  Foreign key, the answer this Note applies to
  
- archived_by (integer)
  Foreign key, which User archived this Note
  
## notification_acknowledgements

Join table between users and notifications. Indicates that a User has acknowledged a Notification.

- user_id (integer)
  Foreign key. The User who acknowledged this Notification.
  
- notification_id (integer)
  Foreign key. The Notification that has been acknowledged.
  
## notifications
  
Notifications are displayed on screen to Users to provide them with important information. Notifications will be displayed to Users until they are acknowledged by the User.

### Are these used at all in the System?

- notification_type (integer)

  The type of notification. 
  - Is this _always_ **global?**

- title (string)
  The main header of the Notification.
  
- level (integer)
  The importance level of the Notification (e.g. info, warning, danger)
  
- body (text)
  Main text body of a Notification.
  
- dismissable (boolean)
  May the User dismiss a Notification?
  - How is this used, exactly?
  - Are they always false?
  
- starts_at (date)
  The date and time at which a Notification should begin being displayed
  
- expires_at (date)
  The date and time at which a Notification should stop being displayed
  
## org_identifiers

### Are these used at all in the System? 
### What do they do?

- identifier (string)

- attrs (string)

- org_id (integer)

- identifier_scheme_id (integer)

## org_token_permissions

### Are these used at all in the System?
### What do they do?

- org_id (integer)
  
- token_permission_type_id (integer)

## orgs
  
An organisation (e.g. University) represented within the System

- name (string)
  Name of the Org
  
- abbreviation (string)
  The shorter name of an Org
  - This seems to be used inconsistently within the database. Are there any rules for how it should be used?
  
- target_url (string)
  Desired landing page for a given Org to direct its Users to
  
- wayfless_entity (string)
  - Is this used at all?
  
- parent_id (integer)
  - Is this used at all? There only seems to  be one record on the database.
  
- is_other (boolean)
  - Is this used at all? Almost all of the records are `false`
  
- sort_name (string)
  The name column used to sort Orgs by.
  - Why is this needed?
  
- banner_text (text)
  -  Is this used at all in the code? Can we get rid of it?
  
- logo_file_name (string)
  -  Is this used at all in the code? Can we get rid of it?
  
- region_id (integer)
  -  Is this used at all in the code? Can we get rid of it?
  
- language_id (integer)
  - Is this required? Almost all of the records are `nil`. The rest are `1` (the default)
  
- logo_uid (string)
  String of the file name for a logo image
  - Does this relate to local files, or are these files stored remotely?
  
- logo_name (string)
  String of the file name for a logo image
  - Does this relate to local files, or are these files stored remotely?
  - How does this differ from `logo_uid`
  
- contact_email (string)
  Contact email address for a given Org.
  - Why do we have so many records that have no contact email?
  
- org_type (integer)
  Enum column representing the type of organization
  
- links (text)
  A Hash of links related to this Org.
  - How is this used?
  - Why is this a serializable column?

- contact_name (string)
  Contact name for a given Org.
  - Why do we have so many records that have no contact name?

- feedback_enabled (boolean)
  Indicates whether this Org allow Users to request feedback on their Plan
  
- feedback_email_subject (string)
  The default subject of a feeback request email for this Org
  
- feedback_email_msg (text)
  The default message of a feeback request email for this Org
  
## perms

Represents a User permission to access certain features within the system

- name (string)
  The name, or main identifier for this permission

## phases
    
Represents a study phase of a given project. 

- title (string)
  The name of the Phase
  
- description (text)
  A description of the Phase
  
- number (integer)
  The position of the Phase within its Plan
  
- template_id (integer)
  Foreign key. The Template a Phase belongs to.
  
- slug (string)
  - Not used. Can this be removed?
  
- modifiable (boolean)
  Indicates whether this Phase may be edited or not by org users
  
## plans

The central model object within this domain. Represents a Data Management Plan for a research project

- title (string)
  The name of the Plan, nominated by the User

- template_id (integer)
  The Template Used by the User to construct this Plan
  
- slug (string)
  - Not used, can be removed?
  
- grant_number (string)
  Official reference number for this research project's grant funding
  
- identifier (string)
  - How is this used? Values seem to vary widely
  
- description (text)
  Description of the data management Plan
  
- principal_investigator (string)
  The full name of the person who should investigate this Plan before completion
  
- principal_investigator_identifier (string)
  The unique identifier for Principal investigators. 
  - These values seem to vary. What should it be?

- data_contact (string)
  - How is this used?
  - What should this value be? Seems to vary.
  
- funder_name (string)
  The name of the organisation to fund this research project
  
- visibility (integer)
  How visible should this Plan be to other Users of the system

- data_contact_email (string)
  I understand this is a contact email but...
  - How should this be used?
  - Is this field widely used? 

- data_contact_phone (string)
  I understand this is a contact phone number but...
  - How should this be used?
  - Is this field widely used? 

- principal_investigator_email (string)
  Email address of the principle person investigating this DMP.
    
- principal_investigator_phone (string)
  Phone number of the principle person investigating this DMP.
  
- feedback_requested (boolean)
  Indicates whether the User has requested feedback for this Plan
  
- complete (boolean)
  Indicates whether the User has completed the Plan or not
  
## plans_guidance_groups
  
Join table between plans and guidance groups
  
- guidance_group_id (integer)
  Foreign key, The GuidanceGroup for the given Plan  
  
- plan_id (integer)
  Foreign key, The Plan 
  
## prefs

### Are these used? There aren't many records on the database.
    
- settings (text)

- user_id (integer)

## question_formats
  
The format of a given question. Determines how a question is presented on the page, and how the data should be structured.
 
- title (string)
  The name of the format

- description (text)
  A text description of the format
  
- option_based (boolean)
  Indicates whether this question format offers multiple options

- formattype (integer)
  Enum column for the question format type (e.g. "dropdown")

## question_options

Represents one available option for a given Question

- question_id (integer)
  Foreign key, the Question ID
  
- text (string)
  The text content of the option
  
- number (integer)
  The position the option should be presented in for the question
  
- is_default (boolean)
  Indicates this is a default option
  
## questions

A single Question within a given Section

- text (text)
  The question being asked of the participant
  
- default_value (text)
  The default value of the question answer
  
- number (integer)
  The position of this Question within its Section
    
- section_id (integer)
  Foreign key, the Section the Question belongs to
    
- question_format_id (integer)
  Foreign key, the QuestionFormat for this Question
  
- option_comment_display (boolean)
  Indicates an option question with optional text area
    
- modifiable (boolean)
  Indicates this Question may be modified when editing the template

## questions_themes
    
### How are themes used within the system?

- question_id (integer)
    
- theme_id (integer)

## regions

Represents geographical regions within the sytem.
    
- abbreviation (string)
    An ISO, two-digit abbreviation of a region name
    
- description (string)
    A text description of the region for clarity
        
- name (string)
    The name of the region
    
- super_region_id (integer)
  Foreign key. A parent region this Region may be a sub-region of
  
## roles

The roles a User may have within the system

- user_id (integer)
  Foreign key. The User this Role is assigned to
    
- plan_id (integer)
  Foreign key. The Plan this Role refers to
  
- access (integer)
  Bit field column (enum) for the access type
  
- active (boolean)
  Is this Role active?
  
## sections

Represents a Section of Questions within a  Phase

- title (string)
  The title of the Section
  
- description (text)
  A brief text description of the Section
  
- number (integer)
  The position of the Section within the Phase
  
- published (boolean)
  Indicates the Section has been published
  
-  phase_id (integer)
  Foreign key, the Phase this Section belongs to
  
-  modifiable (boolean)
  Indicates this Section may be modified when editing the Template
  
## settings

### How is this table used? There's no corresponding model!

- var (string)
    
- value (text)
    
- target_id (integer)
    
- target_type (string)

## splash_logs
  
### Is this model still used?

- destination (string)

## templates

Templates provide a pre-made structure of Phases, Sections, and Questions for a new Plan.

- title (string)
    The name of the Template
    
- description (text)
    A description of this Template
    
- published (boolean)
    Has this Template been published for Users to apply to a Plan?
    
- org_id (integer)
    Foreign key. Which Org this Template belongs to.
    
- locale (string)
    Which Language this Template is written in.
    - This seems to be always either `nil`, or `"en"`
    
- is_default (boolean)
  - How is this Template used?
        
- version (integer)
  The version of this Template. Templates cannot be edited once pubished, so a new version is duplicated.
  
- visibility (integer)
  - How is this field used?
    
- customization_of (integer)
  When a Template is a customisation of another Template, this field is populated with the Family ID of the source Template.
    
- family_id (integer)
  Represents the grouping this template belongs to. Persists Templates related to eachother by a common ID.
    
- archived (boolean)
  Identifies whether the Template is visible for selection on new Plans.
  
- links (text)
  - How is this used?
  
## themes
    
### What are Themes and how are they used within the System?

- title (string)

- description (text)  

- locale (string)

## themes_in_guidance
    
### What is a ThemeInGuidance and how are they used within the System?

- theme_id (integer)
  
- guidance_id (integer)

## token_permission_types
    
### What is a TokenPermissionType and how are they used within the System?

- token_type (string)

- text_description (text)
    
## user_identifiers

### What is a UserIdentifier and how are they used within the System?

- identifier (string)
  
- user_id (integer)
  
- identifier_scheme_id (integer)

## users

This is the main model for all users of the system. 

- firstname (string)
  User's first name
  
- surname (string)
  User's last name
  
- email (string)
  User's email address
  
- orcid_id (string)
  - What is this?
  
- shibboleth_id (string)
  User ID within the shibboleth system
    
- encrypted_password (string)
  User's password, encrypted
    
- reset_password_token (string)
  Used by devise, token for reset password URLs
     
- reset_password_sent_at (datetime)
  Used by devise, timestamp when password reset requested
    
- remember_created_at (datetime)
  Used by devise, timestamp when asked to remember session
  
- sign_in_count (integer)
  Used by devise, number of times the User has signed in
  
- current_sign_in_at (datetime)
  Used by devise, the datetime the User signed in at
  
- last_sign_in_at (datetime)
  Used by devise, the datetime the User last signed in at
  
- current_sign_in_ip (string)
  Used by devise, the IP address of the User's current session
    
- last_sign_in_ip (string)
  Used by devise, the IP address of the User's last session
  
- confirmation_token (string)
  Used by devise, the token for account confirmation URLs

- confirmed_at (datetime)
  Used by devise, timestamp when User account was confirmed
      
- confirmation_sent_at (datetime)
  Used by devise, timestamp when User was sent a confirmation email
      
- invitation_token (string)
  Used by devise, the token for invitation URLs 
  
- invitation_created_at (datetime)
  Used by devise, the timestamp when the User was invited
      
- invitation_sent_at (datetime)
  Used by devise, the timestamp when the User was sent an invitation email
  
- invitation_accepted_at (datetime)
  Used by devise, the timestamp when the User accepted an invitation
  
- other_organisation (string)
  - What is this?
  
- accept_terms (boolean)
  Has the User accepted the terms and conditions?
    
- org_id (integer)
  Foreign key for the Org this User belongs to
    
- api_token (string)
  Access token for certain users who have access to the API endpoints
    
- invited_by_id (integer)
  The foreign key ID of the record who sent an invitation to this User
  
- invited_by_type (string)
  The model name of the record who sent an invitation to this User  
  
- language_id (integer)
  Foreign key for the Language record for this User
  
- recovery_email (string)
  Used by devise, a seconday email for this User to acces thier account
    
- active (boolean)
  Determines whether this User is still active on the system or not.
  - Is this field used anywhere?
  
## users_perms
  Join table between users and permissions
  
- user_id (integer)
  The User we're joining
  
- perm_id (integer)
  The Perm we're joining

**Comment by Bodacious** [comment]
Can `orgs.wayfless_entity` be removed from the database?

**Comment by Bodacious** [comment]
Speaking to @xsrust , it seems we're not making use of the `orgs.parent_id` column. Any thoughts on this?

**Comment by briri** [comment]
Yes I think they can both go. Do a quick search through the code though for any references if you haven't already. I'm guessing the wayfless was for a gem that's no longer used.

**Comment by Bodacious** [comment]
We currently have three attrs on the `orgs` table that refer to logos

- **logo_file_name**
- **logo_uid**
- **logo_name**

It appears `logo_file_name` is old and possibly redundant. @briri can you confirm?

**Comment by briri** [comment]
Yes, I believe that's an old unused column. We use the dragonfly gem to manage logos for the site. If you remove it, you can verify that things are working properly by uploading a new Org logo on the Admin -> Organization page (when logged in as an Org or Super admin)

http://markevans.github.io/dragonfly/rails

**Comment by Bodacious** [comment]
@briri In our database, we notice that almost all of the `orgs.language_id` columns are nil. The four records that have a value are set to 1 (the default English).

Are you happy for us to set 1 as a default value, so that we don't have any nils?

**Comment by Bodacious** [comment]
@briri @xsrust Any thoughts on replacing the `orgs.links` column with an `OrgLink` model? This would be a more idiomatic solution

**Comment by briri** [comment]
I'd prefer to hold off on that for now. We have a similar approach to storing links on the templates model as well. There is some complex JS managing them on the UI side and we've had ongoing issues with the way they're handled in the DB.

**Comment by Bodacious** [comment]
@briri Is the `settings` table used anywhere?

**Comment by briri** [comment]
safe to close this one out after dev team discussion

**Comment by nicolasfranck** [comment]
Wouldn't it be handy to copy this model documentation to the wiki so developers have some technical documentation?

**Comment by briri** [comment]
Yes, that's a great idea @nicolasfranck. We use annotate on the models themselves to list what fields are available buut it would be a nice reference to explain where and how all of the fields are used in a wiki doc.

**Comment by briri** [comment]
See updated ticket #2818

@nicolasfranck  I spent some spare time building out the [DB Schema wiki page](https://github.com/DMPRoadmap/roadmap/wiki/DB-Schema). Thanks for the suggestion. It was helpful in uncovering a bit of cleanup work we need to do in the future. 👍🏻

**Comment by nicolasfranck** [comment]
@briri nice! Thanks for the extensive information ;-) Well appreciated.
