### ISSUE TITLE
Add alt text to images

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#139]
Unlabeled graphic on homepage. Just says "home page graphic." Add proper alt text to the image. 

Verify other images have alt text as well.

From old pivotal ticket: https://www.pivotaltracker.com/story/show/131334291

**Comment by briri** [comment]
Just focus on non org-admin/super-admin pages for this first pass

**Comment by briri** [comment]
added alt text to the few images throughout the site.

Also added Aria tags to all of the fontawesome icons per the instructions found here: http://fontawesome.io/accessibility/

**Comment by stephaniesimms** [comment]
Closing this issue for now pending next round of accessibility testing.
