### ISSUE TITLE
Bug in template versioning when a uni customises it

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1390]
Multiple different unis can add annotations when customising a funder template, but when one does, it displays the warning that the funder template has been updated to others... It hasn't thought. It's just another uni doing a customisation. There seems to be an error in the funder template versioning as a different organisation customising it is creating a new template version. The two entities should be separate.

![bug](https://user-images.githubusercontent.com/6169940/38815481-ef461652-418b-11e8-9f7f-22db3aaa57da.PNG)

I added example answers to the Sloan template for UCSD and American Uni

@briri confirmed that "If multiple Unis customize a funder template it should create individual template versions for them so that adding things like annotations or new sections to one customized template should not affect this status message of related customized templates. Only changes to the base funder template should cause this status message to change."

**Comment by stephaniesimms** [comment]
appears to be fixed by template refactoring. closing.

**Comment by sjDCC** [comment]
Working well now. Versioning of customisations and versioning of funder templates are separate.
