### ISSUE TITLE
More specific selector for usage statistics export button

### ISSUE THREAD

**Issue by Sudiukil** [DMPRoadmap/roadmap#1391]
[Current selector][1] for the usage statistics export button is too generic and conflicts with other features making use of the *data-url* HTML attribute and should be made more specific.

[1]: https://github.com/DMPRoadmap/roadmap/blob/88560603acf7e3f246007722fff47c78f608427a/lib/assets/javascripts/views/usage/index.js#L97-L116

**Comment by stephaniesimms** [comment]
apologies for the delayed reply @Sudiukil - we want to improve the usage statistics #1173 as part of a future sprint and can address this at that time. thanks for the feedback!

**Comment by sjDCC** [comment]
@xsrust this is linked to a closed ticket. Can you validate whether it is needed anymore please. I assume it can be closed

**Comment by briri** [comment]
this JS has been removed as part of https://github.com/DMPRoadmap/roadmap/pull/2336
