### ISSUE TITLE
Cannot submit contact us form when logged in

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1394]
Please complete the following fields as applicable:

**Expected behaviour:**
User can no longer submit the contact us form when they are logged in. 

**Actual behaviour:**
User receives an invalid recaptcha message
![screen shot 2018-04-18 at 9 51 45 am](https://user-images.githubusercontent.com/1204467/38946570-b982dab4-42ee-11e8-9f1f-f083796fe2bd.png)

**Steps to reproduce:**
- Log into the tool
- Go to the contact us page
- submit the form

There is logic that hides the recaptcha widget if the user is logged in the `views/contact_us/contacts/_new_left.html.erb` partial. We need to either disable the recaptcha check when the user is logged in or display it at all times. This is related to the work done on #501

**Comment by sjDCC** [comment]
I'm re-opening this as I have just done UAT on roadmap-stage and still get the recaptcha error message. Has the fix not been deployed yet?

**Comment by sjDCC** [comment]
Works fine now thanks @briri
