### ISSUE TITLE
Too many redirections in Sign Up

### ISSUE THREAD

**Issue by andresf01** [DMPRoadmap/roadmap#1397]
Hi, I found a error while working on ORCID authentication. I'm working on v1.0.3 but It occurss too in last release.

**Expected behaviour:** Fill fields in sign_up page and successfull login

**Actual behaviour:** Too many redirections after sign up (user is created in db but not redirecto to plans)

**Steps to reproduce:** Sign up in dmproadmap/users/sign_up

**Comment by vyruss** [comment]
@andresf01 sorry, I don't understand, are you trying to:

1. Login via ORCID `->`
2. The system tells you your ORCID login is not known and asks you to `->`
  1. Link your existing account `or`
  2. Create a new account
3. You create a new account and this logs you in but `->`
4. Your new account is not linked to the ORCID you used?

**Comment by andresf01** [comment]
Sorry, the problem is that if I want to sign up via dmproadmap/users/sign_up route, application has too many redirections, although user is registered in database.

**Comment by vyruss** [comment]
@andresf01 I cannot replicate this, would you be able to share some Rails logs? That may give us some clues.

**Comment by andresf01** [comment]
@vyruss sure, https://codeshare.io/5QAk7R

**Comment by vyruss** [comment]
@andresf01 we spotted what was going wrong and #1400 should fix it

**Comment by andresf01** [comment]
@vyruss Sign up is working now, issue could be close
