### ISSUE TITLE
Refactor template edit page

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1406]
Refactor the template edit view
- Rename `_show_template.html.erb` to `_show.html.erb` and update controller action
- Remove `_edit_template.html.erb` in favor of `_edit.html.erb` and update controller
- Setup container and show/edit pages so that they only load the template and phases so that the tabbed nav can be properly created (do not pull down sections/questions/etc.
- Update JS where applicable

**Comment by stephaniesimms** [comment]
closing issues that can't be tested in the UI
