### ISSUE TITLE
Switch existing help/tooltips from click to hover events

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#141]
Tooltips: user has to click to turn these on/off and screen can get crowded if they are all are on. It is a standard and would be preferable if the tooltips appeared when the user hovers over the item with their mouse.

From pivotal: https://www.pivotaltracker.com/story/show/131576749

**Comment by briri** [comment]
Just focus on non org-admin/super-admin pages for this first pass

**Comment by briri** [comment]
@JEK-III should we display tooltips like the example below when the user hovers over the item or when the item gains focus? My suspicion is that on focus is preferable for accessibility since some users do not use a mouse.

**Comment by JEK-III** [comment]
@briri On focus– for exactly that reason.

**Comment by vyruss** [comment]
Agree with on focus - as some people will use this on a touchscreen enabled device which does not support hover.

**Comment by stephaniesimms** [comment]
This appears to be working as expected. Closing issue.
