### ISSUE TITLE
Usage statistics don't work from July 2017

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#1410]
Please complete the following fields as applicable:

**Expected behaviour:**

Usage statistics. Filter query and chart should display new users per month.

**Actual behaviour:**

Usage statistics inaccurate. Chart does not display number of new users starting from July 2017. The filger query doesn't work either. Both filter and chart seem to work for period prior to July 2017.

Statistics for plans works fine.

**Steps to reproduce:**

**Comment by briri** [comment]
reopening for UAT

**Comment by stephaniesimms** [comment]
tested on roadmap stage and working as expected now. closing issue.

**Comment by jafamo** [comment]
HI,
I am using roadmap version 1.0.5. My user is super_admin with all checked privileges (API,etc...) 
In my console log with this URL:
https://my-dmp/api/v0/statistics/users_joined?api_token=Uy9m4J9pA_pbRGST6e-jJQ&topic=users&start_date=&end_date=&org_id=15

`On Status Code: 302 Moved Temporarily`

My statistics are not working properly.
I attach an image:

![image](https://user-images.githubusercontent.com/3945078/47286338-8845ab00-d5ee-11e8-8e41-c7470a39ea2e.png)

Any idea ?
Regards.
