### ISSUE TITLE
Default template losing 'publicly visible' status when versioned

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1415]
Please complete the following fields as applicable:

**Expected behaviour:**
The default template should still be visible on the 'Customizable templates' tab of the templates page and available to researchers when they create a plan.

**Actual behaviour:**
When the default template is versioned, it's visibility is set to 'organisationally visible' if the org that owns it is not a funder

**Comment by stephaniesimms** [comment]
@briri when i test on roadmap stage the customized default (Digital Curation Centre) template remains visible in the customizable templates table for admins and available to end users creating a new plan. but now I can also see the customized version in the public DMP Templates list (see screenshot). the customized version of the template should not appear in the public list.

![screen shot 2018-04-25 at 5 06 37 pm](https://user-images.githubusercontent.com/12703638/39279019-6ffb7f64-48ab-11e8-8f73-b4b384560ed4.png)

**Comment by briri** [comment]
ok. this is a larger issue than I originally anticipated. I can exclude the default template from the public templates page, but the current logic behind the create plan page would never find a customized version of the default template.

**Comment by stephaniesimms** [comment]
after further discussion, closing this issue and @briri is creating two new issues to address after template versioning is done
