### ISSUE TITLE
Make sure default tab ordering of page elements is logical

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#142]
Make sure that the user can tab through each page in a logical order.

http://webaim.org/techniques/keyboard/tabindex

**Comment by briri** [comment]
Just focus on non org-admin/super-admin pages for this first pass

**Comment by briri** [comment]
Lets hold off on this one for now and wait for specific recommendations from the accessibility team. I've done some reading on tab ordering of elements and its complicated. I don't think any of us have much experience with screen readers either so we're not in a good position to guess what would work best.
http://webaim.org/techniques/keyboard/tabindex

**Comment by briri** [comment]
waiting on our accessibility test report to determine if this is still an issue

**Comment by stephaniesimms** [comment]
replaced by new accessibility issues. closing.
