### ISSUE TITLE
Clean unused Gems from the gemfile

### ISSUE THREAD

**Issue by bhavi** [DMPRoadmap/roadmap#1420]
In the process of Ruby Upgrade v2.4.1 its advisable to first clean up the unused Gems from the Gemfile.
Related to #826. 

This would include but not limited to:
#rolify for roles
gem 'rolify', '~> 5.1.0'

#API
gem 'swagger-docs', '>= 0.2.9 '

CODE DOCUMENTATION
gem 'yard', '>= 0.9.5'
gem 'redcarpet', '>= 3.3.4'

**Comment by briri** [comment]
You should also be able to get rid of the following:
- friendly_id
- yaml_db
- capybara (also try dropping the others in that section (not sure we're using them all)
- jbuilder (@jollopre and @xsrust is this one really needed for the API?)

**Comment by bhavi** [comment]
Skipping 'jbuilder' and 'administrate' gems for now as they are still used in the API.

**Comment by stephaniesimms** [comment]
closing issues that can't be tested in the UI
