### ISSUE TITLE
Upgrade gems in the Gemfile to work with Ruby upgrade to v2.4.1

### ISSUE THREAD

**Issue by bhavi** [DMPRoadmap/roadmap#1421]
The gems in the Gemfile need to support Ruby upgrade to v2.4.1. Thus, the gems and their dependancies should be individually upgraded as well.

Commonly noted issues with any of the Gems (if any) during the upgrade should also be handled like deprecation warnings, exception errors, etc.  

Note: Since the Gemfile contains considerable collection of Gems, the upgrade would be in chunks (2-3) gems at a time, deployed and tested on dev/stage and then proceed further.

**Comment by bhavi** [comment]
Each gem upgraded individually with 'bundle update -- conservative' option and then again with 'bundle update' command. 

**Below listed is the older and latest version of the each gem as per the current Gemfile.**
Ruby --> v2.4.1   (was 2.2.2)
Rails --> 4.2.10 (was 4.2.7)

Mysql2 --> 0.4.10  (was 0.3.18)
flag_shih_tzu --> 0.3.19 (was 0.3)

devise --> 4.4.3 was(4.2.0)
devise_invitable --> 1.7.4 (was 1.7.0)
omniauth --> 1.8.1 (was 1.3.2)
omniauth-shibboleth --> 1.3.0 (was 1.2.1)
omniauth-orcid --> 2.1.1 (was 2.0)

recaptcha --> 4.8.0 (was 4.1.0)
dragonfly --> 1.1.5 (was1.0.12)
formtastic --> 3.1.5  (was 3.1.4)
kaminari --> 1.1.1 (was 1.0.1)

wkhtmltopdf-binary --> 0.12.3.1  (was 0.12.3)
thin --> 1.7.2 (was 1.7.0)
htmltoword --> 0.7.0 (was 0.5.1)
feedjira --> 2.1.4 (was 2.0.0)

gettext_i18n_rails --> 1.8
gettext_i18n_rails_js --> 1.3.0 (was 1.2.0)
gettext --> 3.2.9  (was 3.2.2)

minitest-reporters --> 1.2.0  (was 1.1.11)
webmock --> 3.4.1  (was 2.1.0)
sqlite3 --> 1.3.13 (was 1.3.12)
simplecov --> 0.16.1 (was  0.12)

better_errors --> 2.4.0 (was 2.1.1)
binding_of_caller --> 0.8.0 (was 0.7.2)
web-console --> 3.3.0 (was 2.3.0)
rack-mini-profiler --> 1.0.0 (was 0.10.1)
byebug --> 10.0.2 (was 9.0)_

**Comment by bhavi** [comment]
**Gems that remained in the same version after Ruby upgrade:** 
ledermann-rails-settings --> 2.4.2
pundit --> 1.1.0
ruby_dig --> 0.0.2
contact_us --> 1.2.0
wicked_pdf --> 1.1.0
rack-test --> 0.6.3

**Gems not upgraded** 
pg ~> 0.19.0  
PostGres latest version 1.0.0 has an - [Open issue noted with rails](https://github.com/rails/rails/issues/31673)
jbuilder ~> 2.6.0
(Used only for API currently)

**Comment by stephaniesimms** [comment]
closing issues that can't be tested in the UI
