### ISSUE TITLE
UKRI Future Leaders Fellowship template

### ISSUE THREAD

**Issue by pherterich** [DMPRoadmap/roadmap#1424]
UKRI seems to have launched some grant opportunities such as the Future Leaders Fellowship scheme which includes a new [DMP template](https://www.ukri.org/funding/funding-opportunities/future-leaders-fellowships/) Are there plans to include this as a new centrally offered template?

**Comment by stephaniesimms** [comment]
@sjDCC - question for you?

**Comment by pherterich** [comment]
Just realised it's the same as the MRC template, but that's only clear when you've seen a lot of them, so the average user wouldn't know. Maybe the MRC template could be cloned and the clone renamed to UKRI Fellowship template?

**Comment by sjDCC** [comment]
Yes, that's right @pherterich We're happy to add other funder templates.

Will let you know when we have this in DMPonline

Thanks!

**Comment by stephaniesimms** [comment]
closing this issue as it doesn't pertain to roadmap code

**Comment by sjDCC** [comment]
Hi @pherterich This is in DMPonline now thanks to @dsisu . Hope that helps :smile:
