### ISSUE TITLE
JS compatibilities for IE 

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#1429]
Since we are providing support for IE, we have to make sure that any JS function we use, has compatibility with IE. I came across with two functions that are not supported by IE and therefore prevent seeing the usage stats:

- Object.assign (can be replaced with $.extend)
- Array.prototype.fill (can be replaces with a polyfill, if used a lot)

Every JS has to be inspected in order to detect potential functions not supported by IE.

**Comment by dsisu** [comment]
Comments are still not saving when editing via Internet Explorer. May be related to this issue.

**Comment by vyruss** [comment]
Tested working on DMPonline

**Comment by stephaniesimms** [comment]
all working as expected on roadmap stage. closing issue.
