### ISSUE TITLE
Clean up Wiki Contributions/Developer sections

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#144]
I'm thinking we should simplify the Contributing/Developer guide wiki sections which are currently found here:
1.  https://github.com/DMPRoadmap/roadmap/wiki/get-involved#5-contribute-code
2. https://github.com/DMPRoadmap/roadmap/wiki/Developer-guide
3. https://github.com/DMPRoadmap/roadmap/wiki/Contributing

We could perhaps consolidate them into 2 pages ("Developer" - "Non developer") and make their link names consistent from every other page.

**Comment by stephaniesimms** [comment]
Agreed that we can revise and reorganize wiki contents as needed. But we created the existing guide in order to get feedback before/at IDCC. So in the short term we should not make substantive changes to this part of the wiki unless flagged in feedback from external contributors.
