### ISSUE TITLE
Add <fieldset> markup to radio buttons and check boxes

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1448]
Add a `<fieldset>` tag to all of the radio and checkbox groupings across the site (e.g. only necessary for groups of these items). If there is a label or heading above the current group, remove it and use the text as the `<legend>` for the `<fieldset>`.

Also remove the 'for' attribute for any check boxes or radio buttons that are embedded within the `<label>` tag since it can confuse screen readers. 

This feedback was provided from the UCOP electronic accessibility review. It was defined as having 'High' priority.

**Comment by stephaniesimms** [comment]
all radio buttons and checkboxes appear to be working as expected, including when i tab through. closing issue.

**Comment by sjDCC** [comment]
Agree - works fine
