### ISSUE TITLE
User not associated with Org after Sign-up

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#145]
I just migrated the database and am running the system using the codebase in DMPRoadmap/roadmap development.

I created an account for myself and selected DCC from the organisation dropdown. When I logged in I had no org affiliation and noticed that User.org_id was empty in the DB.

**Comment by raycarrick-ed** [comment]
Recreated error. Applied fix. Verfified fixed. looks good.

**Comment by stephaniesimms** [comment]
Working as expected now.
