### ISSUE TITLE
Headings should follow proper hierarchical ordering

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1451]
We seem to be using the `<h#>` tags on some of the pages to specify a desired font size. Screen readers though use these headings to create navigation aides. They can sometimes become confused when they are used out of order. 

We should make sure that we follow this pattern on all of our pages:
`<h1>Page title (e.g. Guidance)</h1>`
`<h2>Subsection (e.g. Guidance group list)</h2>`
`<h3> -> <h5>` can then be used sequentially as needed 

Note that modal dialogs should use their own `<h1>` and `<h2>` headings since they are technically new windows/pages to the screen reader.

Adjust the `overrides.scss` file if we need to alter the font size of these headings on specific pages

This feedback was provided from the UCOP electronic accessibility review. It was defined as having 'Low' priority.

**Comment by mariapraetzellis** [comment]
@martaribeiro will tackle this one as it is a good way to get an overview of the current system/pages

**Comment by mariapraetzellis** [comment]
Marta has started this and will continue when she returns from jury duty.

**Comment by magdalenadrafiova** [comment]
half way through atm

**Comment by magdalenadrafiova** [comment]
I do not know how to test this one - probably for devs to only have a look

**Comment by sjDCC** [comment]
@xsrust can you advise. I assume we can't test this and can just close it out on devs say so?

**Comment by xsrust** [comment]
I think that the original ticket came out of an accessibility review for screen readers as they use the headings to create a table of contents.  
We've re-styled some of the headers after changing their value, so I'd just keep a look out for any headings you don't like the size of.  It's definitely fine to close this one out and open new tickets to address any of the stylistic concerns.

**Comment by sjDCC** [comment]
OK, I vote we close this one out. I haven't noticed any weirdly sized headings on UAT
