### ISSUE TITLE
Create email notification system

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#146]
Create email notification system
* new tab under Edit Profile for 'Notification Preferences' (see blue notepad in UX wireframes for functional specs)

UX wireframes @JEK-III : http://h90c3m.axshare.com/#g=1&p=profile

Pivotal ticket: https://www.pivotaltracker.com/story/show/119416081

![dmponline_userprofile](https://cloud.githubusercontent.com/assets/12703638/23564817/6525cfb2-0000-11e7-9d7f-6d29e86153a2.png)

DMPTool notifications - review/revise this list
![dmptool_user_profile_notifcation_preferences](https://cloud.githubusercontent.com/assets/12703638/23564912/6e37846a-0000-11e7-89f7-9fd78f580165.png)

**Comment by stephaniesimms** [comment]
Add an email notice for when a plan is added to / removed from the Public DMPs list

**Comment by stephaniesimms** [comment]
@JEK-III please update wireframe w/following changes http://h90c3m.axshare.com/#g=1&p=profile__first_login

- add third tickbox under "All users" for: "A plan has been shared with me"
- change second title to: "DMP owners and co-owners"
- delete second tickbox under that title "I have been made co-owner of a DMP"
-add third tickbox under "DMP Administrators" for: "A user has requested feedback on a DMP"

**Comment by stephaniesimms** [comment]
email notification text for actions on this menu:

```
COMMENT ADDED    
Email title: [TOOL NAME]: A new comment was added to [PLAN TITLE]   

Hello someone@tester.org   

[COMMENTER NAME] has commented on the plan [PLAN TITLE]:   

To view the comments, please visit the My plans page in [TOOL NAME] and open your plan.    

All the best   
The [TOOL NAME] team   

You may change your notification preferences on your profile page. Please do not reply to this email. If you have any questions or need help, please contact us at [INSERT HELPDESK EMAIL] or visit [INSERT CONTACT US URL]
```

**Comment by stephaniesimms** [comment]
wireframe revision still pending. @bhavi I tested the current implementation and can't save changes. anything I do to change my selections produces the error message in the screenshot below.

![screen shot 2017-06-16 at 2 27 43 pm](https://user-images.githubusercontent.com/12703638/27245479-8f299558-52a0-11e7-8d00-8dbc1a954b77.png)

**Comment by JEK-III** [comment]
Wireframe updated and re-named to reflect updates to the login workflow:
http://h90c3m.axshare.com/#g=1&p=profile

**Comment by stephaniesimms** [comment]
@bhavi wireframe is ready for revision to Notification Preferences menu.

I re-tested the save functionality: now it only allows me to save changes if ALL info in all tabs of my profile menu is complete. So I changed something in my email preferences, clicked Save, and received a message that the save was unsuccessful because I needed to specify an Org in my Personal Details page. 

The desired behavior is for each tab menu to have independent save/update functionality.

**Comment by stephaniesimms** [comment]
@bhavi When I click to save changes on my Notification Preferences, currently it takes me to the Personal Details page and displays a message that my changes were saved. Desired behavior is for the same tab/page to reload for whenever a user changes something in their profile. So I would expect to still be on the Notification Preferences page after my changes are saved w/the message displayed above it. And likewise for changes to the Personal Details or Password pages. 

![profile-page-layout](https://user-images.githubusercontent.com/12703638/27556974-b50e15f4-5a6c-11e7-90a6-56e659ddd074.png)

**Comment by bhavi** [comment]
Tab reload issue fixed. Also added the minor CSS fixes and deployed on dev.

**Comment by briri** [comment]
Clicking save produces an error `undefined method `[]=' for nil:NilClass`

**Comment by xsrust** [comment]
Investigated the save error and it seems to be due to a key which is expected in the hash, but is not found.  Since the new  approach in #481 will be to only store deviations from the defaults, It should be robust to missing keys, so This ticket can potentially be closed

**Comment by stephaniesimms** [comment]
This is working as expected now. Closing issue.
