### ISSUE TITLE
Upgrade from DMPOnline to DMPRoadmap changes plans.updated_at for all plans

### ISSUE THREAD

**Issue by MinkaKaraivanova** [DMPRoadmap/roadmap#1460]
Following upgrade [procedure to upgrade from DMPOnline to DMPRoadmap](https://github.com/DMPRoadmap/roadmap/wiki/Upgrading-From-DMPOnline_v4), after ` rake db:migrate `is run at step 3, plans.updated_at is changed to current timestamp. plans.created_at is unchanged.
There are no errors in the output of `rake db:migrate`.

Our users expect plans timestamp not to be affected by the upgrade.

**Comment by briri** [comment]
Hi @MinkaKaraivanova we migrated our users over from the DMPTool which was a completely different codebase so our migration process was different. I can see where it is occurring in the migration scripts: https://github.com/DMPRoadmap/roadmap/blob/1f8c3a8b83d3014076692d13b54700996bce39e6/db/migrate/20161122152339_new_plan_template_structure.rb#L177

@benjaminfaure did you experience a similar issue when migrating your system to the new Roadmap? DCC is using Postgres and did not encounter it. I wonder if it is specific to mySQL installations.

**Comment by jafamo** [comment]
Hi @MinkaKaraivanova , I migrated DMPOnline to Roadmap with mysql server version: 5.7.22 and I have the same problem.

**Comment by stephaniesimms** [comment]
addressing some database clean-up and migration issues separately. closing this one.
