### ISSUE TITLE
Create plan wizard provides all funder templates, no default template

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1473]
This bug seems related to issue #1470 
When I select a funder for question 3 in the create plan wizard I get a dropdown containing all funder templates regardless of my selection (screenshot 1). there is no association between funder and template.

if i check the boxes for no Org and no Funder for questions 2 and 3 I get the error in screenshot 2. it can't find the default template

if my Org has templates then I do get those when I make the appropriate selection. However if I try to Write plan I get the error in screenshot 3 (same missing template error from #1470)

![screen shot 2018-05-09 at 1 12 18 pm](https://user-images.githubusercontent.com/12703638/39837636-e5e75a5a-538b-11e8-9278-c3aa350f57e6.png)

![default](https://user-images.githubusercontent.com/12703638/39837442-646da3bc-538b-11e8-9da3-440f6bc43a59.png)

![screen shot 2018-05-09 at 1 20 14 pm](https://user-images.githubusercontent.com/12703638/39837572-bdd753da-538b-11e8-9ee7-69c2e1d8a94b.png)

**Comment by stephaniesimms** [comment]
I can get the default template now, but I still see the full list of funder template in a dropdown regardless of which funder I select @briri

**Comment by sjDCC** [comment]
This all seems to be working fine now. Closing out
