### ISSUE TITLE
Revise text on create plan for when the funder isn't listed

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1479]
Change the text on the ‘Create a new plan’ screen under the ‘Select the primary funding organisation’ heading (screenshot). This is causing a lot of confusion for researchers who are applying to funders who do not have a templates.

For consistency change text for the second and third checkboxes as follows:
- 'No research organisation associated with this plan or my research organisation is not listed'
- ‘No funder associated with this plan or my funder is not listed’

![capture](https://user-images.githubusercontent.com/6169940/39877813-c9b42028-546e-11e8-8341-2885f821b4e0.PNG)

**Comment by stephaniesimms** [comment]
looks good on roadmap stage. closing issue.
