### ISSUE TITLE
I cannot download my plan after submitting for feedback

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1483]
This is related to #1430 and can be addressed at the same time

As a user when I click the 'Request feedback' button on the Share tab while writing my plan, then Download tab disappears (screenshot below) and I can no longer download my plan until an admin finishes providing feedback. The desired behavior is for plan authors to always have the ability to download plans.

#1430 referenced above should enable admins to download the plan if feedback has been requested

![no-download](https://user-images.githubusercontent.com/12703638/39939441-2792892c-550b-11e8-9cd5-1683b9dd61d6.png)

**Comment by sjDCC** [comment]
Can still download. Closing out
