### ISSUE TITLE
Delete user and plan and comment option 

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1489]
Users occasionally ask for accounts to be deleted. It would be good to add an option to super-admin to do this - and maybe even on the 'edit profile' page so users can do it themselves? This would go beyond 'deactivating' users to:
- delete email (replace with a generic stem email?)
- remove name
- remove org affiliation

We need to remove any personal and identifiable data for GDPR but don't want a hard delete as this could leave orphaned plans or affect other user data.

And co-owned plans shouldn't be deleted as others still need access to them, and potentially the institution too?

Notes / comment that the user has added could be deleted I think.

@stephaniesimms @dsisu - can we define what we want in terms of functionality?

**Comment by dsisu** [comment]
Looks fine to me.

**Comment by sjDCC** [comment]
Pulling this one up the list of priorities as I realise we don't even have a deactivate button anymore. Super-admins can't do anything to deactivate / remove / delete accounts when requests come in

**Comment by asconrad** [comment]
In Denmark, we would highly appreciate this feature to be implemented!

**Comment by dsisu** [comment]
Maybe we should move this issue a bit higher up the list of priorities. Requests to delete users keep coming up. Currently we have to ask Sam to do this. Ideally, super-admins should be able to remove a user too. We must be able to do this on request. We should put this on the table for discussion and agree on procedures - users must approach us in writing and we must agree what to do with regards to plans that are co-owned.

**Comment by sjDCC** [comment]
I found the "Archive" button on the edit user page below
![Capture-2](https://user-images.githubusercontent.com/6169940/65811847-72eddf00-e1b6-11e9-9751-ad7e05ebffd6.PNG)

However when I clicked it I got an error. Can someone investigate what's wrong.
![Capture3](https://user-images.githubusercontent.com/6169940/65811850-987ae880-e1b6-11e9-8bd7-40b1fedb174e.PNG)

**Comment by magdalenadrafiova** [comment]
I was able to merge two accounts 
![image](https://user-images.githubusercontent.com/47178106/65869683-d0c72600-e372-11e9-965d-55a455437989.png)

**Comment by sjDCC** [comment]
just re-tested this and the 'Archive' button still throws an error. Tested on DMPonline-dev this time

![Capture](https://user-images.githubusercontent.com/6169940/69042123-9419c180-09e8-11ea-9dcf-b6a9726c2c46.PNG)

**Comment by mariapraetzellis** [comment]
@briri will take a look

**Comment by magdalenadrafiova** [comment]
So I tested this, when i clicked on archive button this appeared: 
![image](https://user-images.githubusercontent.com/47178106/69867683-788fa000-129f-11ea-911c-7f65c4547fa8.png)
Then when i confirmed this appeared: 
![image](https://user-images.githubusercontent.com/47178106/69867689-7decea80-129f-11ea-9ba3-059ce5c8bd87.png)
And this is how the profile appears afterwards: 

![image](https://user-images.githubusercontent.com/47178106/69867745-a1179a00-129f-11ea-9276-659d5bd2b6ac.png)

**Comment by magdalenadrafiova** [comment]
I think it works well - closing out
