### ISSUE TITLE
Copy plan option to create a new one

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#149]
Add option to copy an existing plan to plan creation workflow as in DMPTool
* add "Duplicate" button to My plans page (last screenshot below)

See UX wireframes @JEK-III : http://h90c3m.axshare.com/#g=1&p=my_plans__ideal

* later/future enhancement we want to be able to toggle guidance on/off during plan creation, adding more guidance after plan has been started, etc. (post-MVP)
Pivotal ticket: https://www.pivotaltracker.com/story/show/120864879

Screenshot of DMPTool create plan workflow
![dmptool_create_copy_plan](https://cloud.githubusercontent.com/assets/12703638/23565621/392220fc-0003-11e7-8c99-4847e738866c.png)

Screenshot of current DMPonline create plan workflow
![dmponline_create_plan](https://cloud.githubusercontent.com/assets/12703638/23565627/4145711c-0003-11e7-8fbf-c9b3f89e9bf2.png)

DMPonline screenshot of potential Copy button location on My plans page
![dmponline_dashboard_copybutton](https://cloud.githubusercontent.com/assets/12703638/23565634/49072d64-0003-11e7-9f6c-5adefaefcb84.png)

**Comment by JEK-III** [comment]
Add "Duplicate" button to plan actions in "My Datasets" table.
Wireframe: http://h90c3m.axshare.com/#g=1&p=my_plans__ideal

**Comment by briri** [comment]
follow the `Template.deep_copy` approach

**Comment by stephaniesimms** [comment]
tested and this is working as expected on Dev. I'll check w/ @sjDCC to see if we want to drive the user to edit the plan details immediately, as opposed to having to click on the "Edit plan details" button. this would prompt them to change the plan title. there are some issues with guidance selections not being displayed when you click through to answer questions, but I think these are being addressed via other issues.

![screen shot 2017-05-25 at 11 21 45 am](https://cloud.githubusercontent.com/assets/12703638/26464365/6749e332-413c-11e7-85fd-f9ed8efdb403.png)

**Comment by stephaniesimms** [comment]
@bhavi just following up to confirm that we do want to drive the user to edit the plan details immediately after clicking to Duplicate their plan

**Comment by stephaniesimms** [comment]
Clicking Duplicate throws the error below. This occurs for plans based on all templates. Also I can only create a new plan using the default template. If I select any funder from the list the "Create plan" button remains grayed out and will not allow me to continue @briri . I think this is a template error.

![screen shot 2017-06-01 at 2 00 00 pm](https://cloud.githubusercontent.com/assets/12703638/26700607/d4d69a08-46d2-11e7-95fd-05b295dac15c.png)

**Comment by stephaniesimms** [comment]
I can successfully Duplicate a plan now. @bhavi  we do want to drive the user to edit the plan details immediately after clicking to Duplicate their plan.

**Comment by stephaniesimms** [comment]
This is working as expected now.

**Comment by sjDCC** [comment]
I guess the copy plan function is 'duplicate' in this list? 
![copy-plan](https://user-images.githubusercontent.com/6169940/27613697-ec39eb60-5b94-11e7-8acf-73c025fd7a94.PNG)

The term 'copy plan' might be better. 'Duplicate' to me suggests replicating as a backup, not necessarily copying to edit or create a plan from an existing one. Maybe we should check terminology with users? The dropdown flickered on and off for me too. It didn't stay open when you clicked it. I think this is still being implemented though so probably in hand.

I got an error when clicking duplicate. Not sure if this is because I've only just created plan and it has no content in. Worth checking if it still works for you @stephaniesimms or if another bit of code has knocked this off
![copy-plan-error](https://user-images.githubusercontent.com/6169940/27613767-5bc30f34-5b95-11e7-8039-ebc7c9259145.PNG)

**Comment by stephaniesimms** [comment]
I get the error now too. @briri is going to check on it tomorrow. 
@JEK-III can you chime in about why you recommend "Duplicate" ?

**Comment by JEK-III** [comment]
I think Duplicate is slightly better because Copy sounds like step one of Copy/Paste. 

Google docs uses "Make a copy"–  we could certainly say that instead.

**Comment by sjDCC** [comment]
'Make a copy' sounds good to me, unless we want to keep it all one action word so dropdown list is comparable throughout.

@dsisu - as a non-native English speaker, is one clearer to you than another?

**Comment by vyruss** [comment]
_Make a copy_ sounds good to me too.

**Comment by jollopre** [comment]
_Make a copy_ seems more natural to me too. I tend to associate duplicate to inconsistencies in data.

**Comment by briri** [comment]
This should be working now. Changed the language to 'Make a copy'

**Comment by stephaniesimms** [comment]
that was a hot topic. will update copy template related issue #148 accordingly. everything looks good on stage now. closing this issue.
