### ISSUE TITLE
Paginable actions not working on templates pages

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1495]
The search and sort functions are not working on the templates pages: owned and customizable (when there are more than 10 templates in the list). 

Clicking on sorts or search results in which seems to be an issue with the chaining of scopes:
``ActiveRecord::StatementInvalid - Mysql2::Error: Unknown column 'orgs.name' in 'order clause': SELECT  `templates`.* FROM `templates` WHERE `templates`.`archived` = 0 AND `templates`.`published` = 1 AND `templates`.`family_id` IN (1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1894, 1895, 1896, 1903, 1907, 1911, 1912, 1932, 1936, 1940, 1941, 1947, 1949, 1950, 1951, 1952, 1953, 1962, 1964, 1965, 1971, 1977, 1979, 1984, 1986, 1992, 1993, 2000, 2001, 2005, 2008, 2009, 2016, 2019, 538382351, 756435778, 1936) AND `templates`.`visibility` = 1  ORDER BY orgs.name ASC LIMIT 10 OFFSET 0:```

**Comment by jollopre** [comment]
@sjDCC I sent a PR #1511 before that solves the problem when attempting to sort by 'funder' or org however it is still pending to be reviewed/deployed...

**Comment by stephaniesimms** [comment]
I can sort by all columns except Status. The Status column does sort properly when I test as a Super Admin only for the "All templates" tab but not the other two tabs. It doesn't sort for either tab when I test as an Org admin.

And now the search function is no longer working for a list of more than 10 items in the same pattern described for Status column sorting above. I can create a new issue for this bug if it should be handled separately?

**Comment by briri** [comment]
No, its likely related. All of those links fire Javascript. An unfortunate side-effect of many javascript failures is that all remaining javascript on the page stops working. I think its probably what's happening.

What steps did you take to create the issue? Click sort on the status column and then search?

**Comment by stephaniesimms** [comment]
i was toggling across tabs so no particular order to produce the issue with Status sort and Search. Every time I test them in whatever order neither works.

**Comment by jollopre** [comment]
@stephaniesimms, @sjDCC the status column that we see in the UI table does not 'always' correspond to the status (published attribute) stored in the db table. At the database level, that attribute only captures 0 (non-published) and 1 (published), however we enhance it logically by adding three more statuses: 
- Draft (a template version created after a published one)
- Non Customised (a funder template that an org never customised)
- Original funder template has changed (a funder template has a newer published version that a customised template did not port over those changes)

and that's the reason the sorting or search seems to not work adequately, although it purely does.

I suggest to keep the status as it is, i.e. a boolean condition and add next to it an icon that provides further information (draft, non-customised, original funder template has changed) when logically it does. What do you think?

**Comment by sjDCC** [comment]
That makes sense. Thanks @jollopre 

Yes, keeping just two statuses and introducing icons like we are doing elsewhere would be good

**Comment by briri** [comment]
Will fix as part of #1507 when I switch the column status to the binary Published/Unpublished.

**Comment by briri** [comment]
@sjDCC and @stephaniesimms we are not going to be able to sort on the Status column at this time. We can revisit in #1235. The pagination logic only allows for simple database ordering and published is either true or false. A draft is unpublished in the database (one of its prior versions is published) but we display the label 'Published' on the page, so it will not sort correctly until we allow for more complex logic.
