### ISSUE TITLE
Manage plan visibility

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#151]
Add public/organizational/private visibility options > Public DMPs appear under new tab as in DMPTool https://www.pivotaltracker.com/story/show/119417249
* add radio buttons for Public/Org/Private within Plan details page
* add button when you finish answering questions, “Publish/Public” next to “Export” button
* Include confirmation message "do you want to share/publish your completed plan in the Public DMPs list?" 
* need to share individual plan phases publicly within a project, not the whole project (e.g., phases for Horizon 20/20)

Pivotal ticket: https://www.pivotaltracker.com/story/show/120868221

Screenshots of DMPonline pages where Public/Private selector could be added
<img width="1222" alt="dmponline_plan_edit2" src="https://cloud.githubusercontent.com/assets/12703638/23567523/7ffc68fe-000b-11e7-97a9-ad10664478ca.png">
<img width="1219" alt="dmponline_plan_export" src="https://cloud.githubusercontent.com/assets/12703638/23567527/83ad3e38-000b-11e7-9759-911481ef334b.png">

Screenshots of DMPTool Overview page where users can adjust visibility setting
![dmptool_plan_overview](https://cloud.githubusercontent.com/assets/12703638/23567542/97b9ec1e-000b-11e7-9f40-23b33c0ac218.png)

**Comment by stephaniesimms** [comment]
For current implementation, please update the visibility options w/the following language. Probably best to just put Public, Institutional, Private next to radio buttons and a tooltip with the full explanation. Will create a separate issue for new Plan/Project Details page design.

Public - anyone can view, copy, or download the plan. It will appear on the Public DMPs page of this site.
Institutional - anyone logged in from your institution can view, copy, or download the plan.
Private - only owners, co-owners, and others with whom you shared your plan directly can view the plan. Administrators at your institution can view all plans for program development purposes. See Terms of Use.

![screen shot 2017-06-16 at 1 33 02 pm](https://user-images.githubusercontent.com/12703638/27244745-cc7079d0-529c-11e7-9261-0636448f6762.png)

**Comment by briri** [comment]
The text for each visibility option has been updated @stephaniesimms

**Comment by stephaniesimms** [comment]
updated labels look good @briri . and I suppose we can wait to decide about standardized display of help and error messages? i can see the explanations for each viz option when I hover over it. but we use tooltips elsewhere...

**Comment by stephaniesimms** [comment]
http://h90c3m.axshare.com/#g=1&p=write_plan
@JEK-III please update the wireframe with a tooltip (as opposed to hover-over) that explains visibility options. per our meeting on 19 Jun - existing messages that appear when a user tabs through form fields are good as they are. but for these radio buttons we need something more obvious to call attention to what options mean. The text should also be updated/revised with the following:

- Public: anyone can view, copy, or download the plan. It will appear on the Public DMPs page of this site.
- Institutional: anyone logged in from your institution can view, copy, or download the plan.
- Private: only owners, co-owners, and others with whom you shared your plan directly can view the plan. Administrators at your institution can view all plans for program development purposes. See Terms of Use [hyperlink to Terms].

**Comment by JEK-III** [comment]
@stephaniesimms My understanding was that users would only be able to copy their *own* plans. Is that correct?

**Comment by stephaniesimms** [comment]
yes, @JEK-III that is correct. and only plans created with templates that are still published (the Duplicate feature will be disabled for plans created with outdated/obsolete templates)

**Comment by briri** [comment]
related to #417 and 
Visibility settings have been moved to the share and export tabs

**Comment by briri** [comment]
Closing because this has morphed into the tickets mentioned above
