### ISSUE TITLE
Duplicated 'default' guidance on selections panel

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1512]
If the default guidance belong to an organisation (not institution-type), and that's your affiliation too, it comes up twice in the guidance selections. This is because the logic always A) shows the default and then B) whatever guidance was 'selected' by the user. It doesn't check to see if those entries match to de-duplicate.

![capture](https://user-images.githubusercontent.com/6169940/40190300-75c5e34c-59f6-11e8-95c4-627d0541521a.PNG)

The actual guidance only shows up once though.

**Comment by stephaniesimms** [comment]
@sjDCC what action did you take to produce the duplicate guidance? i wasn't able to see two entries for UCOP like in your screenshot above until after you did more testing. did you say that you had to edit guidance or themes and publish it?

**Comment by sjDCC** [comment]
No, the editing makes no difference. It's down to your affiliation under edit profile. If this is set at the default AND the default is an organisation not an institution, then it displays twice.

To replicate this on Roadmap-stage I set UCOP as an org
________________________________

**Comment by stephaniesimms** [comment]
@briri says it should be a simple fix to remove duplicates before displaying tickboxes

**Comment by sjDCC** [comment]
Edge case - just for those whose org is the same as the default so closing out
