### ISSUE TITLE
Changes to shared theme partial break edit Guidance layout

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1513]
Updated the layout of the shared themes section for the template refactoring. This unfortunately broke the layout of the edit Guidance page.

![screen shot 2018-05-17 at 2 11 12 pm](https://user-images.githubusercontent.com/1204467/40204158-62be0212-59dc-11e8-8451-eb495f8706b6.png)

Check ordering of `<div>` tags

**Comment by raycarrick-ed** [comment]
I spent an hour looking at this today and it looks ok to me. I can't see an issue. For clarity, I was looking at the "edit guidance" page and the generation of columns for the themes in that. I can't find any mismatched divs in there so may be ok or fixed elsewhere.

**Comment by briri** [comment]
Hi @raycarrick-ed! Were you looking in the 'sprint2' branch and/or on roadmap-stg? Jose and I have been working within that branch over the past month (should be merging to development early next week)

**Comment by stephaniesimms** [comment]
editing guidance page layout looks good now. closing issue.
