### ISSUE TITLE
Notification Preferences can't be updated 

### ISSUE THREAD

**Issue by benjaminfaure** [DMPRoadmap/roadmap#1514]
Hello, 

It seems that a **non super_admin** user can't update his notification preferences on his profile page. 
The following message is displayed : 
![image](https://user-images.githubusercontent.com/18717040/40220349-25a4cefe-5a79-11e8-9f7e-ed3929dc62a9.png)

**Comment by stephaniesimms** [comment]
i tested on Roadmap stage servers and DMPTool production and encountered no problems with saving notification preferences for any role (super admin, org admin, user)

**Comment by stephaniesimms** [comment]
ok with the new release deployed to roadmap stage and dmptool stage I'm getting the same error for non super admin user types as @benjaminfaure reported above. moving this to sprint board to address asap.

**Comment by briri** [comment]
correction. this is happening for non-super admin users in production currently (before v1.1.0)

**Comment by stephaniesimms** [comment]
this is working now anyway. thanks @briri - closing
