### ISSUE TITLE
Export plan comments/notes

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#152]
Add function to export all questions, answers, and comments. Rethink comment/review workflow after MVP. but make sure language about commenting is consistent throughout the tool (e.g., consider renaming "Share Note" box)

Pivotal ticket: https://www.pivotaltracker.com/story/show/120871479

Screenshot of DMPTool plan comments summary
<img width="1221" alt="dmptool_review_comments" src="https://cloud.githubusercontent.com/assets/12703638/23567694/5f4d82ea-000c-11e7-8238-4362c4caedd2.png">

Screenshots of DMPonline question-level comments > this will be different w/Substance editor
![dmponline_plan_questions_sharenote](https://cloud.githubusercontent.com/assets/12703638/23567741/9a0d18f0-000c-11e7-832e-be909e2a5287.png)

**Comment by briri** [comment]
can this one be closed @stephaniesimms? It seems to be 2 separate issues: A) include comments on plan downloads (probably want this to be an optional checkbox on the download screen) and B) evaluate/change the display of comments on the write plan page

**Comment by stephaniesimms** [comment]
i think we should close this stale issue and create new ones if/when we turn attention to comments
