### ISSUE TITLE
Edit customization from History page takes me to edit template details

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1536]
As an org admin editing a customization I shouldn't be able to edit template details. this was fixed in a previous bug issue, but I noticed that I can still get to a page to edit template details with the following steps:
- select History from Actions menu for a customized template on customizable templates tab
- click Edit link for most recent version of customization
- this opens the page in the screenshot below where I can edit template details

Fix is to make template details read only

![history-edit-customization-details](https://user-images.githubusercontent.com/12703638/40385042-3700d92e-5dba-11e8-8141-e9524984719e.png)

**Comment by stephaniesimms** [comment]
the original issue is fixed - i can no longer edit template details. but i noticed something else: i shouldn't be able to edit a historical version of a customization. currently when i click History > View customizations (for an historical version) i see the option to Add a section at the bottom of the page. if i enter and try to save something it doesn't allow me to edit. 

but it would be better to remove the option altogether. so for historical versions of customizations, please remove Add a new section (screenshot below) @briri 

![screen shot 2018-05-22 at 3 27 28 pm](https://user-images.githubusercontent.com/12703638/40393538-b0bfda20-5dd4-11e8-9a30-c221d27d4e95.png)

**Comment by briri** [comment]
Fixed and in PR. Need to upgrade the ruby version on roadmap-stg from 2.4.1 to 2.4.4 tomorrow though before we can deploy
