### ISSUE TITLE
Generate usage stats

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#154]
Adapt the prototype DMPTool dashboard
* carry this over to new platform as a replacement for DMPTool API queries to get usage stats
* evaluate DMPonline/Roadmap API queries for reuse in usage dashboard
* provide ability to export CSVs
* add visualizations that show: 1) time, 2) how org stats compare to global stats

Org admins want to know the following (per @sjDCC comments on Edinburgh reports):
* new users per month
* total users for their org
* total DMPs per month
* DMPs per template per month

Example of what this could look like in Roadmap - for discussion. Note that 'Date Range' field should be constrained to monthly, annual, and/or total reports. Under 'Institution' (change to Org) a user can select to display their own Org usage or "All Orgs."
![screen shot 2018-01-22 at 4 47 34 pm](https://user-images.githubusercontent.com/12703638/35252260-778a7c40-ff94-11e7-9181-1a03e8d53f87.png)

Screenshot of DMPTool Usage dashboard
![screen shot 2017-03-03 at 12 45 44 pm](https://cloud.githubusercontent.com/assets/12703638/23568441/5b1e51c4-000f-11e7-9be9-7d28d3278d44.png)

**Comment by sjDCC** [comment]
Details on the API can be seen at: https://github.com/DMPRoadmap/roadmap/wiki/API-Documentation

You can:
-  Query the number of registered users within an optional date range
-  Query the number of plans using a template owned by your organisation
-  Retrieve number of plans organised by template
-  Retrieve metadata on all plans from an organisation’s users

For reference the stats we pull for Edinburgh each month cover:
- new users per month
- total users for the org
- total number of DMPs per month**
- DMPs per template per month**

** these last two are in a table with funders along one side and months across the other and running total for DMPs per funder and DMPs per month at ends

It would be good to set these stats into wider context as the DMPTool dashboard above does

**Comment by briri** [comment]
@stephaniesimms and @sjDCC is allowing a custom date range instead of predefined combobox options (e.g. last 7 days, annual, etc.) ok? After discussing in the dev meeting today we have determined that it would be easier to just let the user select their own range.

**Comment by stephaniesimms** [comment]
that sounds great to me. admins have asked for this and will appreciate being able to tailor the reports using a specific date range. if it's possible to default to something like "last 30 days" that would be good and then allow them to customize from there.

**Comment by sjDCC** [comment]
Yes, agree. Much better to be able to let them generate reports to desired date range if that's not too much of a load on us.

**Comment by jollopre** [comment]
See screenshot below for the first mockup working. As I described yesterday:
- It will be displayed yearly stats sorted by month (starting always at last month from today) for each of the topics (joined users, num. completed plans, etc).
- and after is provided a filter form to get numbers according to the data range specified, compared to totals till today (not sure how useful that bit).

![dashboard](https://user-images.githubusercontent.com/7393044/35930382-a69368ca-0c29-11e8-928d-7701539a7c8e.png)

Note that organisation select is only available for super admins and by default your organisation gets selected from the list.

Any feedback will be appreciated to perform any enhancement.

**Comment by stephaniesimms** [comment]
yay for data visualizations! my initial feedback is that we need to add some text or tooltip with basic instructions, but that's easy enough. i'll think on it and provide any additional comments by the Tues call.

**Comment by mxsstrong** [comment]
Usage Dashboard requires an API Token.  Should we put in text noting this?

**Comment by briri** [comment]
We have an error message that displays if the admin does not have an API token. It currently reads "You don't have access to use the API. An api token is needed to generate usage statistics.". 

Since we don't have a super admin function yet that will create these I think we should just add an additional line to that message like: 'Contact the %{helpdesk_email} to request an API token for your organisation.'.

**Comment by stephaniesimms** [comment]
after some more tinkering I definitely think it would be better to have the filters at the top of the page since that's where most of the actions are happening. the graph looks great and i think it's fine to keep as a static feature or only change with the topic variable selection, but i keep expecting something to happen when I click Go. 

I can only display Users data at the moment. 
the date range selection is awesome! and please add a download button for the full CSV reports here too, either above as in the wireframe or to the right of the filters. 


unless it's interactive it shouldn't be the first

**Comment by stephaniesimms** [comment]
looking good @jollopre - a few changes:
"completed plans" isn't meaningful at present since we haven't defined a plan status. please change the language about this as follows:
- change "Completed plans" to just "Plans" in filter dropdown
- change boxes below to "Plans" and "Total plans"
- change axis label on lower graph to "No plans created during last year"
- revise Export to "Download" for consistency
- we should set a standard value range for the y-axis, I estimate a max of ca. 50-80 would be reasonable for users and plans per month for power user Orgs but that's just a guess based on DMPTool data
- it would also be better not to display a graph at all when an Org has no data for either category (so hide the lower graph in the screenshot below because there are zero plans)


![screen shot 2018-02-14 at 9 49 29 pm](https://user-images.githubusercontent.com/12703638/36242480-11929a90-11d1-11e8-90a6-7dddaeb68e34.png)

**Comment by jollopre** [comment]
thanks for the comments @stephaniesimms. The amendments are part of #1167.

**Comment by sjDCC** [comment]
In response to your comment @stephaniesimms 

"in addition to global usage we might only want to provide downloadable usage data for a user's affiliated Org - not sure if you have a preference/requirement regarding this @sjDCC ?"

Org admins should just download their own data, but I guess for superadmins they could download data for all orgs if it's not too big a query or volume of data to represent. Otherwise reports according to org-affiliation should suffice for now. We can always add more functions post MVP.

**Comment by stephaniesimms** [comment]
@jollopre I like the smaller side-by-side graphs and other changes look good - this is great for now. 

we just need to add some explanatory info about being able to view stats from any Org using the filters at the top, but the graphs and CSV download are only available for an admin's own Org. I'll suggest some text in a new issue. closing this one.

**Comment by Ebrahim1010** [comment]
Usage stats page not working....
Message received: 'You don't have access to use the API. An api token is needed to generate usage statistics' 
See screenshot.
How do we resolve this issue?
<img width="1247" alt="Screen Shot 2019-10-31 at 08 35 19" src="https://user-images.githubusercontent.com/47170940/67924715-0cdfe780-fbba-11e9-94d6-c5172ebf826a.png">
