### ISSUE TITLE
Update homepage content

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#155]
* for generic Roadmap code replace video block on DMPonline homepage with bullet list of What is DMP? 1. Learn, 2. Create > these list items could contain links to other info resources within platform
* for DMPTool consider live blog Newsfeed instead of video block
* we like prominence of Sign Up/Sign In to bring people into tool
* rethink/rename tabs at top of page (e.g., Roadmap > Resources)
* create consistency in global nav from not logged in to logged in/My plans area
* once you log in Dashboard/Plans should be most prominent and easy to find to keep things simple inside
* Consider different branding options

Navigation design related to plan and admin areas - need to coordinate these stories, figure out how to modularize 

Homepage wireframe @JEK-III : http://h90c3m.axshare.com/#g=1&p=home
Header options wireframes @rhu001 : http://h90c3m.axshare.com/#g=1&p=header_options

Homepage draft content (text) in Google doc: https://docs.google.com/document/d/1RpN3Ur8usdyNtNNzoFb5405D9Bvv8JhK9gWWxL7fouE/edit

Pivotal ticket: https://www.pivotaltracker.com/story/show/121149471

**Comment by sjDCC** [comment]
I really like the idea to have more background info and routes in on the homepage. Much clearer than just the screencast. The news updates would be good too.

I'm happy to explore something that works for Roadmap + DMPTool + DMPonline if achievable. That would also help translation wise if main static text pages were similar.

**Comment by stephaniesimms** [comment]
it's important to consider this issue in the context of global nav. if we opt for a blog/newsfeed on the homepage, e.g., then it wouldn't necessarily need to be included in the top nav menu. i like the idea for directing users to the DMPTool blog feed at least and imagine it could work well for DCC/DMPonline blog as well.

**Comment by dsisu** [comment]
Whatever links we insert to replace the screen cast, they must be useful for the new user too. The home page is meant to draw users in. Taking the novice user away from the main business of the tool to a blog page isn't useful. It would be good to have a 'get started' link in there.

**Comment by stephaniesimms** [comment]
since we no longer have UX resources on this, we should focus on the quickest solution for the Roadmap generic codebase and each handle our respective service content separately. DMP Assistant and other local deployments are instructive here (https://assistant.portagenetwork.ca/). We can assume others will replace/customize the homepage for their needs.

**Comment by vyruss** [comment]
Currently working on:
- Abstracting left pane content into a separate `_welcome.erb` partial in `app/views/home/`.
- Populating partial with "Getting started checklist" and helpful links.
- Increasing prominence of right pane's "Sign in / Create account".

**Comment by stephaniesimms** [comment]
looks good to me. closing issue. @sjDCC can confirm and remove from board.

**Comment by sjDCC** [comment]
This is fine for the general roadmap code - we'll each need to brand it with relevant links or content for our context. Thanks @vyruss
