### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1550]
Need to run `rake gettext:find` after latest v1.1.0 release to capture newly added text.
- Run rake task to gather new strings
- Update the en_GB, en_US translation files.
- Notify community of new strings and request translations

**Comment by benjaminfaure** [comment]
Do you reupload each translation from the pootle files in the Github ? 
We had some issues with some translations that were being replaced by old translations.

**Comment by stephaniesimms** [comment]
as far as i can tell things are up to date. closing this issue. and yes @benjaminfaure we've had various difficulties w/translation files: replacing things when we makes changes to the code and also missing strings from the translation files. the latter is documented in issue #1369
