### ISSUE TITLE
Themed guidance stacking on write plan page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1551]
Under the following conditions, the themed guidance is stacked on the write plan page. It's a low priority bug since this does not occur on a majority of templates:
- when a question does not include guidance (this tab is then selected by default in guidance panel), and a user has made Org guidance selection(s), the write plan page loads w/o an Org tab selected so themed guidance is stacked for multiple Orgs (screenshot 1) 
- if i select an Org tab i see the appropriate themed guidance for each Org in its own tab (screenshot 2)
- solution is to select the first tab by default when the write plan page loads, regardless of the source of the guidance (integral to template or themed Org guidance)

![screen shot 2018-05-25 at 10 27 27 am](https://user-images.githubusercontent.com/12703638/40558254-99f55830-6007-11e8-8b97-7a24b1b8bdde.png)

![screen shot 2018-05-25 at 10 27 40 am](https://user-images.githubusercontent.com/12703638/40558258-9c8f8ef8-6007-11e8-8ca4-95327a01a551.png)

**Comment by xsrust** [comment]
Worth checking if the display changes in #1409 fixes this issue

**Comment by briri** [comment]
this is likely tied to the accessibility work that added an HTML `<fieldset>` around the checkboxes/radio buttons. Probably just need to add a class to the fieldset or tweak the scss file

**Comment by stephaniesimms** [comment]
this is working as expected now. closing issue.
