### ISSUE TITLE
Retain asterisks for mandatory fields on template pages & revise error

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1553]
Red asterisks appear next to Phase/Section/Question title and order fields as expected when I am creating new items. But after I save a new section the asterisk disappears (screenshot below). We need to retain the asterisks to make it clear to users that this field is required.

In addition the error messaging doesn't make sense when i try to delete the section title and save (I receive a message that it can't create a new version - screenshot 2). Instead the error should occur at the field validation and highlight the missing field in red.

![screen shot 2018-05-25 at 12 47 44 pm](https://user-images.githubusercontent.com/12703638/40563646-6073d240-601a-11e8-9965-f8ba503e15ed.png)

![screen shot 2018-05-25 at 12 51 57 pm](https://user-images.githubusercontent.com/12703638/40563659-712f7a80-601a-11e8-8f4f-42350b39d980.png)

**Comment by briri** [comment]
closing this as it will be addressed as part of the work done on #1326
