### ISSUE TITLE
Explore branding options

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#156]
Consider different branding options.
Logos, color schemes, fonts, hostnames, internationalization files, config files, etc.

* Look at the way DMPAssistant has modified their system and also reference DMPTuuli for examples of prior customization

Pivotal ticket: https://www.pivotaltracker.com/story/show/125261911

**Comment by stephaniesimms** [comment]
we like the DMP Assistant approach to replace Portage logo w/institutional logo when available (screenshots below for U of Alberta).

https://github.com/DigitalCurationCentre/roadmap/pull/2
PR containing this customization also referenced here

![portage-branding](https://cloud.githubusercontent.com/assets/12703638/25251380/0c3ef7d6-25ce-11e7-91f3-0419a5497164.png)

![dmp-assistant-inst-branding](https://cloud.githubusercontent.com/assets/12703638/25251383/0f8ea27e-25ce-11e7-8a59-38b567106c78.png)

**Comment by briri** [comment]
can we close this one @stephaniesimms? Seems like its getting covered in #161

**Comment by stephaniesimms** [comment]
@briri I think so. Just noting here that the institutional branding/logo upload needs to be addressed in #161 or possibly a new, separate issue.
