### ISSUE TITLE
Tooltips for clarity across the site

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#1562]
The purpose of this ticket is to highlight areas of the site where we can add tooltips to help guide users without their needing to consult the manual.

**Comment by xsrust** [comment]
One item which was flagged in our meeting was the confusing area of Guidance/Themes.  There have been repeated queries by our users who are confused about how their different guidance will display on questions.  Tooltips using a similar language of 'tagging' on both the themed guidance and the theme portion of questions were suggested as a potential solution.

**Comment by stephaniesimms** [comment]
happy to add tooltips @xsrust - but trying to keep the backlog focused on actionable issues. i'm going to close this one but please go ahead and create a new one with specific instructions for tooltips to add.

**Comment by Yu-Chieh-Henry-Yang** [comment]
I'm coming from #1596, found theme confusing when I first start learning this project.
Also is there a page that introduce new people to this project about how this project work? (https://github.com/DMPRoadmap/roadmap/wiki/Data-model is very useful) Like what does theme, template do? And some tips and subtle behaviours related to them.

**Comment by stephaniesimms** [comment]
@Yu-Chieh-Henry-Yang we also have a community Slack channel that is great for these discussions. i encourage you to join here: https://join.slack.com/t/dmproadmap/shared_invite/enQtMzI0NTIyODA4NjU4LWJiMDQxM2IyMDhkNmRmM2FhZWZmOGFlMThiNWI3MTJkZmNkYWRjOTc3M2M5MGI4N2Q4YjM3YzgzZTUwODg0MWY

the dmptool wiki contains a user guide for administrators, including info on themes https://github.com/CDLUC3/dmptool/wiki/Help-for-Administrators
and the dmptool app has a quick start guide for researchers https://dmptool.org/help

**Comment by gjacob24** [comment]
Closing this issue because the application uses more tooltips now. Any new or specific tooltips required in the future should be described in a new issue.
