### ISSUE TITLE
Notifications fields should not be required

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1568]
I'm unable to erase and save an empty notification message. All fields appear to be required including a valid date so I can't remove a notification but instead have to wait for it to expire (see screenshot). Desired behavior is to make all fields optional and allow super admins to save them as empty to remove old/ test messages. Alternatively I need to be able to delete the entire record.

![screen shot 2018-06-01 at 6 22 51 am](https://user-images.githubusercontent.com/12703638/40842950-48444282-6564-11e8-8ee1-3f86c99b68f4.png)

**Comment by briri** [comment]
There is a delete button on the bottom right when you edit the message.
![screen shot 2018-06-01 at 7 45 30 am](https://user-images.githubusercontent.com/1204467/40846989-efbb53b0-656f-11e8-9c65-a85f6547d8f8.png)
