### ISSUE TITLE
Remove Orphaned Routes

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#1570]
Check which routes are in use by controller actions and ensure those are the only ones exposed in `config/routes.rb`.
NOTE, will need to limit/remove default actions for most controllers

**Comment by xsrust** [comment]
Possibly an opportunity to look at the hierarchy of URLs in our site and feed back if anything needs changed/improved

**Comment by briri** [comment]
Just a note, we could consider combining `super_admin` and `org_admin` namespaces into a combined `admin` namespace now that administrate is gone and no longer using that one.

**Comment by xsrust** [comment]
@briri, I think combining the two namespaces make sense, especially with our combined admin interface views.

**Comment by briri** [comment]
safe to close this one out after dev team discussion
