### ISSUE TITLE
Export funder templates

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#158]
Build functionality to export funder templates only. Funder templates are available as public resources as in DMPTool.
- Add "DMP Template" under "Explore" menu tab on homepage as in UX wireframe @rhu001 http://h90c3m.axshare.com/#g=1&p=global_nav_variations   
- Create table for funder template info modeled on DMPTool ["DMP Requirements"](https://dmptool.org/guidance) (screenshot below)
- Table includes columns for Template name, Funder name, Links to funder requirements, Links to funder-provided sample plans (optional, if provided by funder)
- Include a tooltip for Sample plans with the following text: "Sample plans are provided by a funder, an institution, or a trusted party."
- Provide ability to export templates as DOCX and PDF files - preferred to have both, but minimum requirement is DOCX to provide an editable file in a user-preferred format
- Provide ability to search the list
- Do not include the A-Z links as shown in screenshot below

![screen shot 2017-07-18 at 2 17 10 pm](https://user-images.githubusercontent.com/12703638/28340556-0d00160e-6bc5-11e7-947e-557c08ec6d3e.png)

Open question about including guidance and/or adding separate guidance export functionality. This is more complicated to bundle w/template export since this should not require a user to be logged in. Therefore guidance needs to be selected separately for export (post-MVP).

Pivotal ticket: https://www.pivotaltracker.com/story/show/119417249

Screenshot of DMPTool homepage w/DMP Requirements and Public DMPs tabs - should be available without logging in
https://dmptool.org/guidance
https://dmptool.org/public_dmps
![dmptool_homepage](https://cloud.githubusercontent.com/assets/12703638/23570669/2878dfa4-001a-11e7-98d2-16b74ad19897.png)

**Comment by xsrust** [comment]
Implemented:
 - index page for template export with template_name, org_name, and downloads fields
 - Docx/PDF export for templates
 - Searching the list via real-time filtering table

Discussion:
 - Currently no guidance is being exported with the PDF/DOCX
 - We could add in annotations/example answers, but the formatting of the documents will need to be considered, same with themed guidance
 - For option based questions, I am currently listing all options.  Should the question type additionally be listed, e.g. datepicker, multiselect, radio?
 - Other than adding centering to the title, I have not done much additional styling on the documents, so formatting/layout may need work.(currently mimics our other export's layout/look/feel)

Don't currently exist in Roadmap DB:
 - Funder Links
 - Sample Plans

**Comment by briri** [comment]
Found issue after deploying the latest. Seems as though the Pundit policy requires a second argument. The page is open to the public so just removing the policy for now. Submitted in PR 

@xsrust you can add back later if you feel its necessary.
![screen shot 2017-07-27 at 2 48 15 pm](https://user-images.githubusercontent.com/1204467/28693742-214e3830-72db-11e7-9def-79bd1f118d89.png)

**Comment by briri** [comment]
The public templates page is done. Closing this ticket. If any new issues arise we can open new tickets
