### ISSUE TITLE
ActiveModel::MassAssignmentSecurity::Error: Can't mass-assign protected attributes for Template: migrated, dmptemplate_id

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#1581]
**Expected behaviour:**
When running `rake db:seed`, should seed the database without error.

**Actual behaviour:**
Running `rake db:seed RAILS_ENV=development` gives
```
rake aborted!
ActiveModel::MassAssignmentSecurity::Error: Can't mass-assign protected attributes for Template: migrated, dmptemplate_id
```

**Steps to reproduce:**
Follow the instruction on https://github.com/DMPRoadmap/roadmap

**Comment by Yu-Chieh-Henry-Yang** [comment]
`rake db:seed RAILS_ENV=development` works after I remove the following lines from `seeds.rb`:
-   migrated: false,
-   dmptemplate_id: 1,
-   migrated: false,
-   dmptemplate_id: 2,
-   migrated: false,
-   dmptemplate_id: 3,
because from the code (db/migrate folder and schema.rb file) I don't see such columns been created. But I'm not sure why this happen.

**Comment by jollopre** [comment]
thanks for reporting this issue @Yu-Chieh-Henry-Yang. From version 1.1.0 the template model is as follows:
```
Template(id: integer, title: string, description: text, published: boolean, org_id: integer, locale: string, is_default: boolean, created_at: datetime, updated_at: datetime, version: integer, visibility: integer, customization_of: integer, family_id: integer, archived: boolean, links: text)`
```
and therefore I suspect that's the reason the seeds raises that Exception. Thanks again for providing as how did you fix it. We will have to remove old attributes from db/seeds.rb

**Comment by briri** [comment]
When we look into this ticket. I propose that we drop the seeds.rb entirely and just create a rake task to add only the data necessary (e.g. language, question formats, etc.). That would require an update of the test_helper.rb as well though

**Comment by Yu-Chieh-Henry-Yang** [comment]
Cool, thanks for the replies @jollopre @briri
