### ISSUE TITLE
Gemfile ruby cannot be a range (Unknown ruby interpreter version (do not know how to handle): >=2.4.4.)

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#1585]
**Expected behaviour:**
cd into project directory should switch to correct ruby version 2.4.4 since I'm using RVM and has ruby 2.4.4 installed

**Actual behaviour:**
```
$ cd roadmap
RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
you can ignore these warnings with 'rvm rvmrc warning ignore /Users/a1646259/dev/roadmap/Gemfile'.
To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.

Unknown ruby interpreter version (do not know how to handle): >=2.4.4.
```

**Steps to reproduce:**
Follow the instructions on [wiki installation page](https://github.com/DMPRoadmap/roadmap/wiki/Installation)

**Note**
In Gemfile, ruby version should not be a range, see [this StackOverflow post](https://stackoverflow.com/questions/23116456/specify-a-range-in-bundler-ruby-version/23116552#23116552).

**Comment by xsrust** [comment]
Looking at the [documentation for bundler](https://bundler.io/v1.12/gemfile_ruby.html), it looks like version opperators should be supported for the ruby version as well as for other gems.  RVM however [does not currently support](https://github.com/rvm/rvm/issues/3737) this feature and complains, but in my experience continues to work.  
Is this preventing commands from running, or just throwning a warning before continuing to work? 
I'll flag this for discussion at our dev meeting.

**Comment by Yu-Chieh-Henry-Yang** [comment]
When gemfile ruby version is a range

I get `Unknown ruby interpreter version (do not know how to handle): >=2.4.4.` and my ruby version automatically become 2.5.1 (the latest ruby version in my Mac I think)

didn't see any problem yet

**Comment by Bodacious** [comment]
You should be able to add a file to your local repo called `.ruby-version` with the string `2.4.4`. RVM should load this instead of the Gemfile and you won't have any more problems.
