### ISSUE TITLE
/Users/my-user-name/.rvm/rubies/ruby-2.4.4/bin/ruby: warning: shebang line ends with \r may cause a problem

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#1586]
**Expected behaviour:**
rails s should not give warning

**Actual behaviour:**
```
$ rails s
/Users/my-user-name/.rvm/rubies/ruby-2.4.4/bin/ruby: warning: shebang line ends with \r may cause a problem
```
**Steps to reproduce:**
Follow [wiki installation instructions](https://github.com/DMPRoadmap/roadmap/wiki/Installation)
Note: I use OSX, RVM, Ruby 2.4.4

**Comment by xsrust** [comment]
Hi,

This error looks related to your rvm setup, not necessarily to the codebase.

**Comment by briri** [comment]
I can confirm that I see this as well on OSX with rbenv as well
