### ISSUE TITLE
Personalize email notification for sharing a DMP

### ISSUE THREAD

**Issue by pherterich** [DMPRoadmap/roadmap#1587]
One of our academics has queried if the notification email she received when a DMP was shared with me as she wasn't sure if it was spam.

Could

"A colleague has invited you to contribute to their Data Management Plan in DMPonline 
Click here to accept the invitation, (or copy LINK into your browser). If you don't want to accept the invitation, please ignore this email. 
All the best 
The DMPonline team"

become

"Your colleague [name] has invited you to contribute to their Data Management Plan in DMPonline 
Click here to accept the invitation, (or copy LINK into your browser). If you don't want to accept the invitation, please ignore this email. 
All the best 
The DMPonline team" ?

If the message was personalised with a name, it would make judgement easier. I maybe should mention that we are pushing DMPOnline to most of our PHD students and they might share with their supervisors (busy academics) without giving them much of a heads up, so a better automated email would really help.

Many thanks!

**Comment by stephaniesimms** [comment]
@briri confirmed that this is easy to add. we can update the email in an upcoming sprint.

**Comment by sjDCC** [comment]
Looks great, thanks @Bodacious  Closing out.

**Comment by briri** [comment]
Reopening for verification after git cherry-pick

**Comment by sjDCC** [comment]
email looks good
