### ISSUE TITLE
Move ORCID identifiers to new table

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#159]
Move the existing 'valid' ORCIDs from the users.orcid_id table to the new user_identifiers table and insert ORCID into the identifier_schemes table post migration.

**Comment by briri** [comment]
Debating whether this should be part of the DCC MVP since we have added the ORCID functionality in already. 

It won't harm anything if we don't do it, users would just need to reconnect themselves manually. That may not be a bad thing since there can be a lot of garbage in that field in the table (e.g. email addresses. numbers that do not follow the ORCID conventions, etc.).

**Comment by vyruss** [comment]
Rake task is in place in current code.
