### ISSUE TITLE
How do I create a new default template so that user can use it?

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#1596]
How do I set a new default template through user interface? (I can set a new default template by modifying it programmatically or directly in database) Is this documented somewhere in wiki? I can't find it.

**Expected behaviour:**
As a normal user, I should be able to see the template created by super admin of same organisation listed in the following page:
top navigation bar: Reference > DMP template

**Actual behaviour:**
As a normal user, I cannot see the template created by super admin of same organisation in the following page:
top navigation bar: Reference > DMP template.

**Steps to reproduce:**
1. Make Super admin belongs to <Uni ABC> organisation
2. Super admin create a new template called <Test Template No. 22>
3. Create new normal user, belongs to <Uni ABC> organisation
4. Logged in as normal user, go to top navigation bar: Reference > DMP template.
5. I can only see <My Curation Center's Default Template>, but I expected to see <Test Template No. 22>

Also, if I create a new plan, it will default to <My Curation Center's Default Template>, but I want it to default to <Test Template No. 22>. How do I do this?

**Others**

1. What's the difference between Customizable templates and other templates that belong to certain organisation?
2. What is theme? How is that related to a plan? Is this documented somewhere?

**Comment by xsrust** [comment]
I dont believe that there is a way to set the default through the UI at the moment.  This can be done by changing the corresponding `is_default` column of any record you want to be default to `True` in the database or through rails console.  Please make sure there is only 1 default set at a time.

The page you are listing, `Reference > DMP template`, is the list of 'public templates'
Currently, this looks for orgs of org_type funder, finds their templates, and displays any of these with a visibility of public.  The page additionally always shows the default template.

With the current implementation, only orgs who are funders can have their templates displayed in this section, and only publicly visible templates can be displayed.

1) Only templates from organizations who are funders can be customized. 
The process of customization allows organisations (generally universities) to add custom sections with their own questions to a template.  They can also add guidance or example answers (saved as annotations on the back end) to any of the existing questions in the template.  

2) Themes are effectively tags.  questions are 'tagged' with a theme, and so are guidances.  This allows us to show guidance which is related to the question on the front end.  We agree that this area is confusing and not well explained to the end user.  Perhaps you can share your thoughts on https://github.com/DMPRoadmap/roadmap/issues/1562

**Comment by stephaniesimms** [comment]
closing as this seems to be addressed now
