### ISSUE TITLE
Improve navigation between Plan and Admin areas

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#160]
Create a more intuitive way to switch between plan and admin areas by, e.g.:
* add "Admin area" tab to main menu bar
* remove "Admin area" from top right drop-down menu
* add "Plan area" or "View plans" tab to main menu bar when in Admin area
It's not clear to users that DMPonline logo takes you back to My plans dashboard (after signing in)

Pivotal ticket: https://www.pivotaltracker.com/story/show/120873081

Screenshots of DMPonline Plan and Admin areas
![dmponline_dashboard_adminarea](https://cloud.githubusercontent.com/assets/12703638/23570800/cad353ce-001a-11e7-8ab5-f641bb3e1834.png)

![dmponline_dashboard_admin](https://cloud.githubusercontent.com/assets/12703638/23570803/cd7595e2-001a-11e7-8f43-1812e4f13979.png)

**Comment by briri** [comment]
closing as this is encompassed by changes within #161
