### ISSUE TITLE
I cannot upload new organisation logo

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#1602]
**Expected behaviour:**
I should be able to upload logo to my newly created organisation

**Actual behaviour:**
After I upload a new organisation logo, and press save, it gives the following error:
```
Command failed ('identify' '-ping' '-format' '%m %w %h' '/var/folders/0w/vcldfsd14p73f91xrzw_7s_c0000gn/T/RackMultipart20180613-18540-1y7vkv6.png') with exit status 127 and stderr sh: identify: command not found
```

![screen shot 2018-06-13 at 5 01 02 pm](https://user-images.githubusercontent.com/19463606/41336443-70c0b1a2-6f2b-11e8-88d7-ab5b6fd70aa3.png)

The image I'm trying to upload:
![plain-logo](https://user-images.githubusercontent.com/19463606/41336455-7c12bd20-6f2b-11e8-996f-8e33c68de516.png)

**Steps to reproduce:**
Start a new app following wiki installation steps, Create a new organisation, add a new logo to it and press save

**Comment by briri** [comment]
Hi @Yu-Chieh-Henry-Yang. Make sure you have ImageMagick installed on your system. The dragonfly gem uses it to alter and manage images.

**Comment by Yu-Chieh-Henry-Yang** [comment]
Thanks, for future people, the way I install ImageMagick on my mac is by running `brew install imagemagick`
