### ISSUE TITLE
Is there a feature to add nested question?

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#1604]
This is not a bug.

When user selects an option to a question, I want they to provide details 

```
(Question) "Do you have funding money?"
> (radio option 1) Yes
>> (Nested question) Where does the funding come from?
>>> (textfield) [      ]
> (radio option 2) No
```

Is this feature implemented or going to be implemented?
If not, can I ask for advices on how the feature could be implemented?

**Comment by stephaniesimms** [comment]
we don't plan to implement nested questions @Yu-Chieh-Henry-Yang - but the tool does support grouping related questions like this into sections. we have some instructions for creating templates on the dmptool wiki that may be helpful - https://github.com/cdluc3/dmptool/wiki/creating-templates
