### ISSUE TITLE
Revise global navigation

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#161]
Non-logged-in version: https://wireframe.cc/BatUuz
Logged-in version: https://wireframe.cc/FgAwAU

Menu items Google doc: https://docs.google.com/document/d/1iMOP6wU6Qv7RObjM8El9EeZzDyeyke62qewS8qZx4-0/edit

Pivotal ticket: https://www.pivotaltracker.com/story/show/131906263
related ticket https://www.pivotaltracker.com/story/show/120873081

**Comment by briri** [comment]
implemented changes found in the wireframes and deployed to dev and stage

**Comment by stephaniesimms** [comment]
per UX call 12 Jul - transfer screenshot and logo variance comments from #424

**Comment by vyruss** [comment]
It's not clear to me how to reinstate current-page highlighting in the navbar (for DMPonline CSS)

**Comment by briri** [comment]
@vyruss The `views/layouts/_navigation.html.erb` still uses the `isActivePage()` method to determine what page the user is on. This method sets the `active` class on the menu item.

Right now the CSS does the following:
```css
/* Standard menu item */
color: $header-text-color;
background-color: $primary-color;

/* Active menu item */
color: $primary-color;
background-color: $white;
```
The two variables, `$primary-color` and `$white` are set in your dmproadmap.scss file. 

If you find that you need to be more granular than that feel free to create 2 new variables in dmproadmap.scss and reference them in the dmproadmap/base.scss file.

**Comment by sjDCC** [comment]
I really like the icons in this wireframe:

![icons](https://user-images.githubusercontent.com/6169940/28792337-24c96b70-7627-11e7-9bb2-16200f4d3762.PNG)

If we have space to include those that would be great. It brings it back to one click for actions not two, which is preferable

**Comment by stephaniesimms** [comment]
we all like the icons @sjDCC . i think the main reason for not using them is real estate - this table is extremely crowded as is and the dropdown Actions menu seemed like the best solution. @JEK-III also provided some rationale for the use of icons - if we introduce them here we should do so throughout the tool for consistency and that would require more time and effort (correct me if i'm wrong here). open for discussion though.

**Comment by sjDCC** [comment]
Yeah, I figured space may preclude it. Nevermind.

**Comment by sjDCC** [comment]
Does this ticket have any work left to do in it? Doesn't seem so to me from reading though. Close out?

**Comment by stephaniesimms** [comment]
this predates Bootstrap work and seems moot now. i'm going to close.
