### ISSUE TITLE
Create documentation for code conventions

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1613]
For external contributors guide, create documentation for code conventions. This will also be useful for onboarding to the core dev team.

**Comment by Bodacious** [comment]
Hi all,

The following is a collection of suggestions to kick-start the discussion on code conventions for this project. I've added each item as a separate issue to allow the group to discuss each suggestion separately. I encourage you to leave some feedback and suggestions for changes/improvements.

Thanks!

---

# Ruby / Rails code convention suggestions

## Tools for general hygiene

The following suggestions should help us maintain a healthy codebase over time.

### Use Rubocop

Developers work better together when they can easily recognise and understand what another developer has written.

[Rubocop](http://docs.rubocop.org/en/latest/) provides a Ruby style guide that is generally recognised and observed by the Ruby and RoR community. You can read the general guidelines here: https://github.com/rubocop-hq/ruby-style-guide

Some of these rules might seem unusual at first, but there's normally a very good reason _why_, that isn't always immediately apparent.

By adhering to a common style guide, all contributors will benefit from the improvements in readability over time.

Discussion: https://github.com/DMPRoadmap/roadmap/issues/1670

### Use Code Climate (or Ruby Critic)

[Code Climate](https://codeclimate.com) provides a grade score (A-F), just like in highschool, for each of the files within the codebase. This helps stakeholders, **including non-developers**, get a snapshot of the overall health of the code, as well as an indication to whether it's getting better or worse.

Code Climate can be integrated with a test coverage tool like SimpleCov (currently in use) to provide an additional report on the test coverage.

If we don't want code quailty scores to be made public (as they are with Code Climate's free repos) we can use the [Ruby Critic](https://github.com/whitesmith/rubycritic) gem locally to generate similar reports.

Discussion: https://github.com/DMPRoadmap/roadmap/issues/1671

### Install annotate gem for better automated documentation

The [annotate](https://github.com/ctran/annotate_models) gem automatically updates each model file with documentation showing the schema structure. This is very helpful for developers to refer to while they're getting to know the code.

The schema info is automagically updated with each database migration.

Annotate also provides annotations for the gems within the `Gemfile`, automatically adding a description and github URL for each gem.

Discussion: https://github.com/DMPRoadmap/roadmap/issues/1672

### Use DelayedJob for asynchonous tasks

Certain functions do not need to be run in-line, and we can provide a better user experience by performing these asynchronously. The most obvious example of this in this repository is email delivery. Emails are currently delivered inline, meaning the user has to wait for an email to be sent before being redirected to the next page.

[DelayedJob](https://github.com/collectiveidea/delayed_job) is a gem that runs jobs asynchronously in a background queue. This should be used for email delivery, and can be employed in future to handle expensive operations (e.g. image processing, data manipulation, etc.)

There are a few other services (e.g. Sidekiq) that offer this same functionality, but DelayedJob is one of the few that doesn't require an additional service such as redis to be installed.

Discussion: https://github.com/DMPRoadmap/roadmap/issues/1673

### Decide on documentation syntax

Most methods outside of controller actions should have some level of documentation to describe their purpose.

The Yard syntax has been used well on some of the code, but this has not been used consistenly across the whole codebase.

[TomDoc](https://tomdoc.org) is a lightweight documentation syntax for Ruby that is used by many notable teams including GitHub. TomDoc provides the same features as yard, but is easier to write (and is more likely to be written).

TomDoc [can be parsed by Yard](https://github.com/rubyworks/yard-tomdoc) to create the same automatically generated HTML documentation for developer reference.

We should decide on one of these documentation syntaxes (or RDoc) and enforce their use throughout the whole application.

Discussion: https://github.com/DMPRoadmap/roadmap/issues/1674

### Use Bullet to detect N+1

[Bullet](https://github.com/flyerhzm/bullet) is a gem that provides visual feedback to developers (in development mode) when a page contains N+1 queries or redundant eager-loading calls.

Discussion: https://github.com/DMPRoadmap/roadmap/issues/1675

---

## Principles for best practice

### Extract RESTful resources

There seems to be a few areas in the code that can be dramatically simplified by identifying new abstractions and extracting these as RESTful resources.

Currently, one illustrative example is the `#request_feedback` action to create a new feedback request. This is currently defined as a GET request, and handled by the Plans controller.

A more RESTful solution would be to create a **feedback request** resource. This would be handled by its own `FeedbackRequestsController`, and use the standard CRUD actions.

As a general rule of thumb: any time we define an action on a controller that is not one of the 7 CRUD actions this should prompt a rethink. The only real exceptions to this rule are state change methods and actions for static content (e.g. "terms_and_conditions").

Discussion: https://github.com/DMPRoadmap/roadmap/issues/1676

### Observe SOLID design principles

[SOLID design principles](https://en.wikipedia.org/wiki/SOLID) are generally good guidelines for preserving the quality of OO code over time.

It might be beneficial for us to document these, and include a short checklist for reviewers when reviewing a new PR.

Discussion: https://github.com/DMPRoadmap/roadmap/issues/1677

**Comment by stephaniesimms** [comment]
this is delightfully clear and readable. many gold stars for you @Bodacious for taking the reins on documentation. i'll leave it to others to comment on content. i'm happy for it to be transferred to the wiki.

**Comment by sjDCC** [comment]
Great to see this on wiki - thanks @Bodacious Closing out
