### ISSUE TITLE
cannot view phase for a plan of a template with a phase without question

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#1615]
**Expected behaviour:**
Should be able to view phase for a plan of a template with a phase without question

**Actual behaviour:**
cannot view phase for a plan of a template with a phase without question

**Steps to reproduce:**
Create a template with a phase without question
Create a plan and click that phase
see that you cannot view that phase, you get this error instead
![screen shot 2018-06-15 at 2 56 00 pm](https://user-images.githubusercontent.com/19463606/41451490-47be5250-70ac-11e8-823b-946d629602b7.png)
The problem is that the code in the image evaluate to this
```
SELECT plans.* FROM plans
INNER JOIN templates ON templates.id = plans.template_id
INNER JOIN phases ON phases.template_id = templates.id
INNER JOIN sections ON sections.phase_id = phases.id
INNER JOIN questions ON questions.section_id = sections.id
WHERE (plans.id = '8' AND phases.id = '14')
```
and as you can see it requires us to have section and question in a phase to view it:
```
INNER JOIN sections ON sections.phase_id = phases.id
INNER JOIN questions ON questions.section_id = sections.id
```

**Comment by stephaniesimms** [comment]
this doesn't sound like a bug @Yu-Chieh-Henry-Yang since a template that lacks sections and questions is essentially empty/blank

**Comment by Yu-Chieh-Henry-Yang** [comment]
Yes, @stephaniesimms and @briri , thank you two for the feedback!
