### ISSUE TITLE
Improve navigation for Admin area

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#162]
NOTE: This is potentially superseded by new global nav design in related issue #161 . Links to alternative requirements in Google doc below.
* Redesign top nav menu for switching from homepage to plans area
* Also for admins switching from plans area to admin area
* add "Admin area" tab to main menu bar
* remove "Admin area" from top right drop-down menu
* add "Plan area" or "View plans" tab to main menu bar when in Admin area
* Super Admin tab and/or functions will become part of the Admin area

Non-logged-in version: https://wireframe.cc/BatUuz
Logged-in version: https://wireframe.cc/FgAwAU

Menu items Google doc: https://docs.google.com/document/d/1iMOP6wU6Qv7RObjM8El9EeZzDyeyke62qewS8qZx4-0/edit

Pivotal ticket: https://www.pivotaltracker.com/story/show/131906525
related tickets:
#120873081
#131906263

**Comment by dsisu** [comment]
It's easier to revise navigation if you look at key screens, decide what their main function is, then place the necessary buttons there. Same goes for #161 .

**Comment by rhu001** [comment]
Since change in global nav design, this issue is no longer relevant.
