### ISSUE TITLE
Create toggle on/off for email signature

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1631]
I noticed this while testing on dmptool stage. Now that we changed the functionality for the request feedback emails we need to be able to disable the signature currently applied to all emails that tells users they can change their notification preferences. In this case they can't opt not to receive this email since it goes to the main org contact no matter what.

![screen shot 2018-06-20 at 1 33 53 pm](https://user-images.githubusercontent.com/12703638/41683149-b066bcc6-748e-11e8-804c-8afee9f3827f.png)

**Comment by sjDCC** [comment]
I just tested this on roadmap-staging but the email to admins of a plan request still has the configuration options on.
![capture](https://user-images.githubusercontent.com/6169940/42316104-e0d6823e-8040-11e8-9468-420f3f79f787.PNG)

The email out to users that their plan has been submitted was unusually brief, but maybe the text was intentionally adjusted as this is a staging / test area?
![text](https://user-images.githubusercontent.com/6169940/42316115-e60d71ae-8040-11e8-88c0-51f22bad2992.PNG)

**Comment by stephaniesimms** [comment]
It looks like you just need to switch off the signature for the email to admins of a request for feedback  @briri . that's the only email message where we don't want the signature currently.

@sjDCC the second email to users in your screenshot above contains whatever text is entered for your Org on the Org details page. so likely just brief testy text, yes.

**Comment by stephaniesimms** [comment]
functionality and email all working as expected now. closing issue.

**Comment by briri** [comment]
Reopening for verification after git cherry-pick

**Comment by stephaniesimms** [comment]
still good. closing again.
