### ISSUE TITLE
Investigate efficiency of current JS/CSS dependency management

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#164]
We are currently using gems to pull in JS and CSS dependencies. This allows them to be pulled into the Rails sprockets asset management framework but it leaves us relying on 3rd parties to maintain those gems and keep them up to date with the JS/CSS library authors.

There are multiple approaches we can take here. We can use bower, npm or other some other package manager but they remain outside of the normal Rails asset pipeline. We could also use the new rails-assets gem which uses bower underneath to retrieve the most current stable releases of the dependencies and integrates them into the pipeline. https://rails-assets.org/#/

**Comment by vyruss** [comment]
- According to JS developer opinions I read, npm works better than bower and @jollopre agrees
    - Initially I was worried that node.js (which npm requires) might be too big a dependency, but then again bower is an external dependency too. 
- Browserify can help us maintain our frontend dependencies through npm:
    - https://github.com/browserify-rails/browserify-rails
    - https://github.com/endenwer/npm-rails

**Comment by briri** [comment]
We moved to webpack and npm to manage our assets
