### ISSUE TITLE
Reduce vertical space between themes on Guidance and Templates pages

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1650]
I'm assuming this is related to accessibility fix #1448

Reduce vertical spacing between radio buttons for themes on the Guidance page and checkboxes for themes on the Templates page. Revert to previous spacing (see before/desired and after screenshots).

Before (revert to this spacing)
![screen shot 2018-06-20 at 12 57 49 pm](https://user-images.githubusercontent.com/12703638/41681510-a895e85a-7489-11e8-9e0c-e3ae52c924eb.png)

After/now
![screen shot 2018-07-03 at 11 41 47 am](https://user-images.githubusercontent.com/12703638/42238591-3ce38950-7eb6-11e8-9e58-549169cf73bf.png)

**Comment by briri** [comment]
Reopening for verification after git cherry-pick

**Comment by stephaniesimms** [comment]
the layout looks good currently. but i think this is related to #1448 @briri which you held back from the release. leaving it up to you whether to include this now.

**Comment by sjDCC** [comment]
spacing looks fine
