### ISSUE TITLE
HTML form labels aren't clickable

### ISSUE THREAD

**Issue by Bodacious** [DMPRoadmap/roadmap#1656]
On the HTML radio and checkboxes: 

When a user clicks on labels in the forms it should automatically select the checkbox or radio that it relates to. But I see quite a few instances where that isn’t happening.

One example is on the Plans *Share* tab.  The *Permissions* radio buttons are only selectable if you click the actual _pip_. The labels should also be clickable.

**Comment by stephaniesimms** [comment]
this is likely related to accessibility issue #1448

**Comment by johnpinto1** [comment]
Only fixed labels for the **Permissions** radio buttons on the **Plan Share tab.**
All radio buttons and checkboxes on the **Write Plan** appear clickable.

![Selection_044](https://user-images.githubusercontent.com/8876215/68224231-1ddb8f00-ffe6-11e9-95ff-bc2bc91cb1d1.png)

**Comment by magdalenadrafiova** [comment]
The permissions radio buttons on the plan share tab work well 
![image](https://user-images.githubusercontent.com/47178106/69868428-93631400-12a1-11ea-8776-47903f647149.png)
![image](https://user-images.githubusercontent.com/47178106/69868434-9a8a2200-12a1-11ea-9108-f8d648982606.png)
![image](https://user-images.githubusercontent.com/47178106/69868453-a37af380-12a1-11ea-9009-aa1a290a430c.png)
closing this
