### ISSUE TITLE
plan policy logic

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#1659]
In app/policies/plan_policy.rb initialize method

we have this line
`plan || plan.publicly_visible?`

Shouldn't it be `plan && plan.publicly_visible?`

because we will only get to the `.publicly_visible?` part only if plan exist but the logic state if plan exist then just return true so the second part is redundant.

**Comment by Bodacious** [comment]
@Yu-Chieh-Henry-Yang agreed, this logic is wrong.

https://github.com/DMPRoadmap/roadmap/blob/master/app/policies/plan_policy.rb#L7

@xsrust @briri Shouldn't a Plan also be visible to some Users when its visibility is `organisationally_visible?`.

**Comment by magdalenadrafiova** [comment]
@briri @xsrust not sure whether this is still an issue? can we close?
