### ISSUE TITLE
Configure Plan readability through branding.yml

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#1661]
Currently, plans are readable by a super_admin, an admin of any of the organizations to which co-owners belong, or to any user with a role in the plan.  

For some services, it is not wanted for org-admins to be able to view the full text of any plan within their organization, and this should be restricted to super-admins, or org-admins with requested reviews.
Note that a user requesting a review adds a role for the associated org-admin users on the plan.

We should add a configuration option for whether or not org-admins can view plans from users of their org. This will affect whether the plans at /org_admin/plans have active links to the full DMP content or not. Where all plans can't be viewed by org admins, they will only have access to plans where a specific review has been requested (see notification panel above plans table)

![plans-view](https://user-images.githubusercontent.com/6169940/42315159-a7760822-803e-11e8-9f12-03e72b21b42f.PNG)

**Comment by stephaniesimms** [comment]
i tested as a super admin and org admin for UCSF and noted some weird behaviors:
- as a super admin I see the notifications panel w/many plans awaiting feedback (screenshot 1). i can also click the links to open each plan below and view the content.
- as an org admin I don't see the notifications panel, but I should (screenshot 2). when i click the links to open the plans in the main table i receive an error msg (screenshot 3) and am taken to My Dashboard.

desired behavior is to make the default configuration to give Org Admins authorization to open and view plans. I think this was a requirement for UK unis in fact, and is the current behavior. Org Admins should always see plans awaiting feedback in the Notifications panel regardless of the configuration setting. 

if the tool is configured to prevent Org Admins from viewing the contents of all plans, the error message should not redirect them to My Dashboard. instead they should stay on the Plans page.

Super Admin UCSF view of plans page
![super-admin](https://user-images.githubusercontent.com/12703638/42529067-4919521e-8432-11e8-8436-4d6d59f5056e.png)

Org Admin UCSF view of plans page
![org-admin](https://user-images.githubusercontent.com/12703638/42529084-56fa5c02-8432-11e8-9c93-8eb6d9129d53.png)

Error message when I click the link to view a plan as an Org Admin
![not-authorized](https://user-images.githubusercontent.com/12703638/42529109-68c075f2-8432-11e8-8ebb-622e082027a2.png)

**Comment by stephaniesimms** [comment]
default configuration looks good now. will just need to keep an eye on whether newly privileged admins can see a complete list of plans awaiting feedback. closing issue.
