### ISSUE TITLE
Static pages content moved out from YAML files

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#167]
The static pages content is currently allocated into YAML files (one for each language). It has been agreed that locatised views will be less clumsy and consequently easier to maintain. The localised views is proposed at rails guides http://guides.rubyonrails.org/i18n.html#localized-views

**Comment by jollopre** [comment]
TODO:
- Adding msgid and msgstr for .pot an .po files. I'm facing problems spaces in URLs in the .po and .pot files auto-generated. I have tried escaping spaces by replacing %20 with \%20 and %%20 but these are not working either (it needs further investigation).
- I have found a bug in https://github.com/DMPRoadmap/roadmap/blob/development/app/controllers/static_pages_controller.rb#L42 which prevents from rendering view(s) at /public_export/:id. I will fix as part of replacing the view public_export.html.erb to gettext.

**Comment by briri** [comment]
could be a case where its being double-escaped. where are the issues occurring? when you do `raw _('text')`?

**Comment by jollopre** [comment]
@briri the YAML files used to create .pot and .po files had encoded spaces (e.g. %20) for URLs. These encoded spaces raised ArgumentError: unnumbered(1) mixed with named which basically means that any time '%' is found, it is expected a keyword associated to it.
Removing the encoded spaces and just typing the space keyword has solved the problem.

Note, I had to remove some translations for the French language since they were specific for Portage (Canada instance of DMP Online). I suggest to revisit the entire translations files because there is high probability of having translations that are tied to specific DMP instances.

**Comment by briri** [comment]
yes I completely agree with revisiting those translation files. I've added it to our post migration cleanup ticket #170

**Comment by briri** [comment]
This all looks good @jollopre. I removed the link to the public DMPs page from the main nav bar since we have decided to implement it at a later date.

**Comment by briri** [comment]
I don't think this one requires and UI testing so I am closing
