### ISSUE TITLE
Install DelayedJob for asynchronous task handling

### ISSUE THREAD

**Issue by Bodacious** [DMPRoadmap/roadmap#1673]
Certain functions do not need to be run in-line, and we can provide a better user experience by performing these asynchronously. The most obvious example of this in this repository is email delivery. Emails are currently delivered inline, meaning the user has to wait for an email to be sent before being redirected to the next page.

[DelayedJob](https://github.com/collectiveidea/delayed_job) is a gem that runs jobs asynchronously in a background queue. This should be used for email delivery, and can be employed in future to handle expensive operations (e.g. image processing, data manipulation, etc.)

There are a few other services (e.g. Sidekiq) that offer this same functionality, but DelayedJob is one of the few that doesn't require an additional service such as redis to be installed.

#### Pros:

- Offers better user experience
- Fully supported by Rails
- Doesn't require additional software to be installed on servers

#### Cons:

- Requires an additional background worker to be running on the server

**Comment by benjaminfaure** [comment]
Job management is now handled by Rails natively : https://guides.rubyonrails.org/active_job_basics.html
