### ISSUE TITLE
Extract non-RESTful controller actions into their own resources

### ISSUE THREAD

**Issue by Bodacious** [DMPRoadmap/roadmap#1676]
There seems to be a few areas in the code that can be dramatically simplified by identifying new abstractions and extracting these as RESTful resources.

Currently, one illustrative example is the `#request_feedback` action to create a new feedback request. This is currently defined as a GET request, and handled by the Plans controller.

A more RESTful solution would be to create a **feedback request** resource. This would be handled by its own `FeedbackRequestsController`, and use the standard CRUD actions.

As a general rule of thumb: any time we define an action on a controller that is not one of the 7 CRUD actions this should prompt a rethink. The only real exceptions to this rule are state change methods and actions for static content (e.g. "terms_and_conditions").

#### Pros:

- Keeps controller classes simpler
- Focusses each controller on a single responsibility
- Makes it much easier to understand the domain concepts and logic

#### Cons:

- Introduces more domain concepts for the developer to learn

**Comment by gjacob24** [comment]
Closing this issue because this is mentioned in our Coding Conventions wiki and will make an effort to enforce the same while coding.
