### ISSUE TITLE
Redesign usage graphs to display total users and total plans

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1678]
Related issue #1173 
Redesign the graphs to integrate the filter selections with displayed data as in the wireframe below (screenshot 1). The graphs need to accommodate complete historical data for users and plans (screenshot 2 of current graphs below). If possible these should change dynamically based on filters. As discussed previously, it's not necessary to enable custom date selections; fine to constrain these by monthly usage numbers similar to the dropdown example in the wireframe below. It's just important to enable users to visualize broad changes/trends over time. 

DMPTool power user Orgs have data from 2011-2018/present, up to n = 300 users and n = 350-400 plans. DMPonline power user data for Edinburgh up to n = 700 users and n = 900 plans.
- Change graph title based on filter selection "Users" and "Plans" - or choose a generic title depending on final design
- If possible, add option to visualize plans/template data (related issue #1679 )
- Extend the y-axis to at least 1500? w/larger increments (try every 50 or 100?). Or better if this could be dynamic.
- For the x-axis make the bars narrower and display data by month/year depending on selections. Alternatively use a line graph - just need to show trends.
- I prefer to keep things simple with a single graph display. Admins can produce more sophisticated visualizations from raw CSV data if desired. But see @sjDCC comments below about possible 2-graph display with annual data (or whatever filter selections are made) alongside total data.

Integrated filters and single dynamic graph
![screen shot 2018-01-22 at 4 47 34 pm](https://user-images.githubusercontent.com/12703638/35252260-778a7c40-ff94-11e7-9181-1a03e8d53f87.png)

Current usage dashboard - it's confusing for users to make filter selections that aren't reflected in the graphs. Find a way to integrate these two elements.
![screen shot 2018-07-05 at 12 06 00 pm](https://user-images.githubusercontent.com/12703638/42343203-279c42f6-804d-11e8-8e99-0facbd5aaa60.png)

**Comment by sjDCC** [comment]
Thanks @stephaniesimms 

Looks like Edinburgh has just short of 700 users and 900 plans so probably cap each at 1000 for now? Might be worth running queries to ensure nobody exceeds this though.

I personally like the year view as you can identify peak months / periods so would retain this, as well as adding a multi-year 2010-2018 view. It would be great to allow people to switch between years to look at the annual data for each.

Perhaps the devs could provide some ideas about alternative views? Even just having the total user & plan numbers as a table or line graph with annual figures for 2010-2018 alongside the single year monthly breakdown could be good. Whatever visualization works best.

**Comment by sjDCC** [comment]
The filters and the graph should also be linked so the parameters set are then displayed visually

**Comment by johnpinto1** [comment]
Marta will be taking on this.

**Comment by mariapraetzellis** [comment]
Closing out this issue and making a new one with agreed upon changes.
