### ISSUE TITLE
undefined method `funder_id' for #<Plan:0x0000000b046e00>

### ISSUE THREAD

**Issue by jdddog** [DMPRoadmap/roadmap#168]
I get the following error when I try to create a new plan on a local installation:

```
Showing /home/user/workspace/roadmap/app/views/plans/_dropdowns_new_plan.html.erb where line #19 raised:

undefined method `funder_id' for #<Plan:0x0000000b046e00>
Did you mean?  funder
```

```ruby
        <div class="control-group" id="funder-control-group">
          <div class="controls">
            <%= f.input :funder_id,
                :as => :select,
                :collection => @funders,
                :label => t('helpers.project.create_page.funders_question'),
```

I'm using the latest release, have created and seeded the development database and can log in with the super user account.

**Comment by briri** [comment]
Thank you for reporting this @jdddog. We will add it to the queue. 

We're currently finishing up some optimization work which involved a refactoring of some of the core tables including how funder organisations are defined.  

We should be updating the development branch within the next few weeks.

**Comment by briri** [comment]
This appears to have been fixed at some point during the refactoring work done performed by @raycarrick-ed over the past few weeks. The plan.funder_id method currently exists in the DCC fork of the codebase and will be brought over as part of a pull request in a few days.

**Comment by stephaniesimms** [comment]
Not sure how to test so closing this pending ability to test on local installations
