### ISSUE TITLE
Unable to create a new user account 

### ISSUE THREAD

**Issue by Bodacious** [DMPRoadmap/roadmap#1680]
**Expected behaviour:**
When I fill in the form and click the "Create account" button, it should create an account, sign me in, and redirect me to the root path

**Actual behaviour:**
When I click the button, nothing happens. Nothing changes on the page, and no requests are sent to the server.

**Steps to reproduce:**
- Visit the sign up page http://localhost:3000/#create-account-form and fill in the form with valid data
- Click the "Create account" button

**Comment by stephaniesimms** [comment]
i can successfully create a new account. working as expected now. closing.

**Comment by briri** [comment]
Reopening for verification after git cherry-pick

**Comment by stephaniesimms** [comment]
this is working as expected. closing again.
