### ISSUE TITLE
Add validations to Sections Model

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#1681]
On the sections model, we need to validate that for a given phase, it's sections numbers are unique.
Essentially, the combination of section.phase_id and section.number should be unique.

This could be added to the database as a migration adding an index on these fields.
Validation should also be added on the rails side.

Finally, a rake task should be added to ensure that the data matches the validation.
This will need to be run before the index can be added.

As an example, the DMPonline dataset has 528 cases of matching section numbers within the same phase.

Some discussion/further thought may be needed on how the rake task decides the new ordering

Related to #1574 (requirements capturing)
Related to #1371

**Comment by briri** [comment]
@Bodacious we've been adding rake tasks to the `lib/tasks/upgrade.rake` file and including a `v1_2_x` task that runs through any scripts that an admin would need to run when upgrading to the latest version. It would be great if you could add any rake tasks needed to sort out bad data that would violate the new validation rules.

**Comment by briri** [comment]
we may need to back this one out since #1371 is having issues in MySQL

**Comment by stephaniesimms** [comment]
I can create sections with duplicate numbers so this doesn't appear to be validating properly. There also doesn't seem to be a pattern to how the sections are ordered - neither database order nor... in the screenshot below w/all 3 sections labeled with 1, I created Section A first, then the top 'duplicate section 1' then the middle 'duplicate section 1 again'. they are displayed in different orders when i edit the template and create a plan with this template.

![screen shot 2018-07-12 at 2 58 14 pm](https://user-images.githubusercontent.com/12703638/42661854-5d4b8104-85e4-11e8-9b2c-8a1ab96e1925.png)

**Comment by briri** [comment]
@Bodacious, this and #1371 both reference the same open PR but the issue @stephaniesimms has reported seems to be related. I'm not sure where exactly the changes were made and unfortunately don't have time to find the appropriate commits to revert things safely/cleanly.

I'm going to hold off on creating the release. It would be great if you can prioritize these 2 tomorrow. Once they're done we can create the release and move onto the next sprint.

**Comment by Bodacious** [comment]
Sorry both, I didn't realise this was being run on MySQL. 

Both of those issues should be fixed with the latest changes to #1715

**Comment by sjDCC** [comment]
I now get an error if I try to create a section for a number that is already taken so this seems to be fixed. Closing out
