### ISSUE TITLE
Usage stats for funder view

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1682]
The current usage page provides number of users and number of plans for the organisation. This makes sense for universities, but funders would want to see all DMPs using their template, irrespective of which organisations the creating users belong to.

Can the view be adjusted by org type so that funders see the following:

1. Usage: total DMP figures by template for the template(s) they own (see related ticket #1679). This may need to be a separate graph specific to funders to differentiate it from the proposed plan/template graph for org-affiliated users

2. Plans: a list (and download) of all plans created using their template(s)

**Comment by sjDCC** [comment]
Consider permissions for funder to download plan
1. User has a setting to grant permission (default on)
2. Only allow it to be shared after 50% complete

**Comment by mariapraetzellis** [comment]
We will consult with Dutch and Irish funders to flesh this out. Have meetings scheduled in Jan & Feb

Agreed actions:
Consult with existing funders
Simple usage dashboard, similar to organisation one focusing on plans and template
Access to actual plan content can only come when the DMP has been marked as complete or accessible to funder, not in draft

**Comment by xsrust** [comment]
I've done a first-pass on this by re-using the plans_by_template chart (bottom of current usage-dashboard page).  I've also generated the information for all organisations, as we may  determine down the line that we want to expose tool-wide usage of every org's templates.  

UI-wise, the view for a funder has become quite busy:
![usage_statistics_1](https://user-images.githubusercontent.com/7352616/76213897-8e4c2400-6203-11ea-9465-dc489249808c.png)

We could use one of our existing motifs to clean this up, either accordions or tabs.  I lean towards a view with accordions for each section.  I quite like the idea of putting the `Statistics on your Templates` accordion both first and open for Funders, and putting the `Statistics on your Users` first and open for universities.  If we decide not to show the `statistics on your templates` section to normal orgs, we could just omit the accordion markup entirely.

@sjDCC @magdalenadrafiova @mariapraetzellis   Let me know your thoughts on UI, as well as if this information would be interesting to all organisations, rather than just funders.

**Comment by magdalenadrafiova** [comment]
@xsrust 

Is it possible to see the plan by the individual user - can they go into the plan and read the plan? Would that be a separate functionality for which we should raise a ticket?  

We do not want the funder to see an empty template. Is this selecting only plans that were completed by at least 50%? Or is this taking all the plans, even if they are empty.

**Comment by xsrust** [comment]
@magdalenadrafiova 
The new chart functions the same as the below one for 'No. plans by template' so the admin-user can hover over and see the number of usages of an individual template, but they cannot click into the plan from this dashboard.

org-admins can see the list of their users plans from another page, and it's a different feature to expose the plans to funders.

Neither chart is currently considering the completeness of the plans, just the creation/existence.

**Comment by mariapraetzellis** [comment]
In answer to the question re accordions vs. tabs, I vote accordions. 

Regarding getting funders access to the actual plans that @magdalenadrafiova mentioned, we'll discuss this new feature w/ @sjDCC and can make a new issue once we've defined the requirements.

**Comment by xsrust** [comment]
I've added the accordions now.  For simplicity, I've left the new template in for all organisations.  If the organization is a funder, the templates accordion will default to open, otherwise, the users accordion will default to open.  

I've also moved the download buttons above the accordions, and the custom filter below.

**Comment by sjDCC** [comment]
Hey @xsrust Thanks for starting this. A few thoughts from me:

- Seeing the stats for plans created using their template is the primary use case for funders. I don't think they need to see details for their users and perhaps not even the filter unless this can be re-scoped to work on the template data somehow. Can we comment out / change the usage stats page based on org type so funders just see their template data?

- Accordions is preferable to me too, but as I say I'm not sure of the value of showing the 'user' data for the funder unless it was somehow scoped to the users writing plans for their templates e.g. which unis do these users come from etc

- I think funders would like to get beyond the simple '10 DMPs in March' using this template. They'll want to know by whom - which researchers, which unis etc. Perhaps this could be the second accordion tab in place of the standard 'user' data for funders

- The "Download monthly usage" data button seems irrelevant for funders unless we change it to be a download of the template data

- I think some unis will be interested in stats for their own templates so good to leave it for all, but open up the user tab first like you have done as that is richer data

- Agree that for now we just give funders stats. Ideally we would scope that to show complete or shared plans in future and determine some way for them to be permitted to access content if desired, but this is a new feature

**Comment by xsrust** [comment]
Hi @sjDCC I'll try to address each of these.
> Can we comment out/change the page so funders just see their template data?

Definitely, I'd thought the plan/user level statistics would potentially be interesting to funders as they could use the tool like a normal organization, and thus their users could generate statistics potentially.  I can either remove it alltogether, or make it configurable per-instance.

> Funders will want to know which researchers from which uni's have created plans based off their templates, and to be able to interrogate that information.

As you've mentioned in your last point, We don't have an explicit 'share with funder' interaction with the user.  I think that as they've not opted-in, with our current T's and C's, we'd be unable to share information about which researchers are creating plans based off their templates, as sharing their names, emails, or ORCiDs would be a GDPR violation.  We could probably do counts aggregated by university, but that would require a new visual-device to display, and some thinking about which types of aggregate statistics it makes sense to generate.  
I think if we want this type of functionality, we should build it into a new ticket with some requirements gathering from both sides (DCC/CDL) to ensure relevance, a check into the GDPR implications for us, and some thought given to the UI in both the Dev and Tuesday calls.

> Download monthly usage irrelevant to funders excluding template data

I didn't want to assume funders would be unable to use the tool as a regular organization, so I'd left this in.  Happy to hide for funders, or to make this configurable for each instance.

**Comment by xsrust** [comment]
Changes made:
- Remove the `Monthly Usage Download` button for funders
- remove accordions and only display template usage data for funders
- Swap accordion order for non-funders so user-statistics show first

**Comment by sjDCC** [comment]
All looks good. Closing out
