### ISSUE TITLE
Display issue (cropped answers & whitespace) when reviewing DMPs

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1683]
A few admins have experienced issues when reviewing DMPs. The answers are in read-only mode and sometimes get cropped to only show half of someone's answer (you need to reload page to open in full) or show whitespace afterwards. This has happened on Chrome for all users. 

Email text from enquirer below:

The first screen shot image attached shows that the answer has been cut off halfway through (I've just created a test template to avoid sharing our actual plans), whereas the second screenshot shows the full answer after refreshing the page four times. We get this a lot when reviewing DMPs and sometimes we don't always realise that an answer has been cut if it happens to show a full sentence.

![answer - cut off](https://user-images.githubusercontent.com/6169940/42382876-797eb6ea-812d-11e8-8f46-6686ef7a3f64.JPG)
After refreshing page:
![answer - full](https://user-images.githubusercontent.com/6169940/42382880-7c1a02ba-812d-11e8-9998-734be7e5989c.JPG)

Other answers end up with a load of blank space after them which means a lot of scrolling before we get to the next question (shown in third screenshot - you can see the end of an answer at the top of the page with a load of blank space afterwards.)
![answer - blank space](https://user-images.githubusercontent.com/6169940/42382896-8671b83e-812d-11e8-8a50-a21ddab8ed42.JPG)

@xsrust and I have looked into this but can't replicate it, but since multiple people have experienced it it warrants further troubleshooting though to see if we can identify what's happening

Further update from Hannah:
"I tried using Firefox and Explorer as well as Chrome and had the same issues with the answer boxes being cut off or being far too long."

**Comment by sjDCC** [comment]
This issue has been reported again so it still causing some users trouble. User says:

"when I click inside the answer box, it fails to expand, I’ve had to select all text and copy and paste into another system to read it (that sentence continues and there’s another one after).
 
I’m working in Firefox 61.0.1 (64-bit)."

@Bodacious any chance you could see if you could replicate this one? We couldn't isolate the issue to pursue a fix before

**Comment by stephaniesimms** [comment]
Here's some more info from a DMPTool user w/the same issue
![screenshot](https://user-images.githubusercontent.com/37444768/44151461-a7ff5918-a070-11e8-987e-819c12a7da5b.jpg)

When I review a DMP, the window in which the text was written for each part of the DMP doesn't expand to show me all the text. Some of it gets cut off past the window and I can't see it. If I copy with Control-A, Control-C, then paste into something like Notepad, then I can see all the text. See screenshot. There is at least one more line of text not showing up. I'm using Chrome on Windows 10. I also tried it on the Edge browser and it acts the same way.

**Comment by sjDCC** [comment]
This seems to be working. I can't see any examples where text is being lopped off and I don't know that would be feasible now with the way we are presenting it.

One thing I spotted which may need adjustment before we close this out (@xsrust to advise) - any section added by the institution still presents questions in the old-style i.e. a read-only version of TinyMCE. Technically I guess this means there could be an issue of truncated text if any answers are particularly long. Should we apply the new presentation style to custom sections too?

See screengrabs below of new presentation of answers to funder questions, and old-style view still in use on Manchester custom section.

![funder-question-answer](https://user-images.githubusercontent.com/6169940/51900468-4b3b4280-23ad-11e9-8d61-2bfba4132e93.PNG)
![manchester-own section](https://user-images.githubusercontent.com/6169940/51900479-51312380-23ad-11e9-9aaa-615d5f62c864.PNG)

**Comment by johnpinto1** [comment]
@sjDCC @xsrust The code for option-based questions in read-only mode are still using the text area tags: app/views/questions/_new_edit_question_option_based.html.erb

**Comment by johnpinto1** [comment]
A PR to fix the issue of option based question answers https://github.com/DMPRoadmap/roadmap/pull/2052 
The display from Manchester Custom section mentioned in https://github.com/DMPRoadmap/roadmap/issues/1683#issuecomment-458481147 now looks like this:

![selection_114](https://user-images.githubusercontent.com/8876215/52053947-c1c57500-2552-11e9-9c98-c4b02c7a4c79.png)

**Comment by sjDCC** [comment]
New read-only view is looking good. Closing out.
