### ISSUE TITLE
Themes Deleted when saving anotations

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#1684]
Themes get cleared out when saving an annotation as a customiser.

Think this is due to the change to radio buttons on the form and this line in the controller:
https://github.com/DMPRoadmap/roadmap/commit/fd474099557f29e69aefb9b7e693d8e04d5624f3#diff-3ff836668353b0b5108a5dd58c9c7aafR74

**Comment by xsrust** [comment]
originally flagged in #1409

**Comment by stephaniesimms** [comment]
working as expected now. closing issue.

**Comment by stephaniesimms** [comment]
this is fixed. closing again.

**Comment by sjDCC** [comment]
themes no longer deleting
