### ISSUE TITLE
Make default download settings configurable

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1688]
DMPTool users mainly want to download answers and nothing else, especially when there are page limits. Other users have requested to download section headings but no question text. We would like to:
- Make the default download settings configurable for different installations
- Add a fourth checkbox and separate 'section headings' from 'question text.' The order of boxes would be: 1) project details coversheet, 2) section headings, 3) question text, 4) unanswered questions

![capture](https://user-images.githubusercontent.com/6169940/36610462-45a752aa-18c8-11e8-889b-d93feaadb951.PNG)

**Comment by aaronskiba** [comment]
Closing this issue as it is quite old now. Will reopen if users express interest for this configuration ability.
