### ISSUE TITLE
Create global usage report for all users, plans for all Orgs

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1689]
Related #1173 
Admins want aggregate usage info for total users and total plans for each Org using the tool to help them benchmark their Org against others. Create a CSV report that includes all Orgs (Org name) with total n users and total n plans for each one.

- The CSV data file should include ONLY aggregates for each org. Monthly data and growth patterns should not be shared.
- The totals should reflect the most recent month for which the query is run. it's fine to run it at the end of the month so most recent today would be June 2018.

Organisation | Total n users | Total n plans
-- | -- | --
University of Edinburgh | ... | ...
University of Glasgow | ... |  
UCL | ... |  
... | ... |

**Comment by jollopre** [comment]
@sjDCC, @stephaniesimms, I believe this functionality is already deployed in any development server. Can you test in order to see whether or not satisfies the requirements? Thanks

**Comment by sjDCC** [comment]
Yes, this looks perfect. Thanks!

Closing out :)
