### ISSUE TITLE
Create single menu or button to download all usage reports

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1690]
Provide a dropdown menu with different downloadable CSV reports or single button for a zipped file instead of multiple buttons. Wireframe below contains proposed location of button/menu at the top of the Usage page. Comprehensive list of reports:
- All orgs users and plans (global usage report #1689)
- Org users per month
- Org plans per month
- Org plans by template #1679
- Org plans downloads and shares #1745 
- Org plans for which feedback was requested #1759

Should cover all historical data for the org, numbers/month

![screen shot 2018-01-22 at 4 47 34 pm](https://user-images.githubusercontent.com/12703638/35252260-778a7c40-ff94-11e7-9181-1a03e8d53f87.png)

**Comment by mariapraetzellis** [comment]
Moved applicable points over to https://github.com/DMPRoadmap/roadmap/issues/2345.
