### ISSUE TITLE
Refactor code to avoid global constants

### ISSUE THREAD

**Issue by Bodacious** [DMPRoadmap/roadmap#1696]
We should really be avoiding the need for global constants for configuration and references values throughout the code.

Instead, these should be defined in a semantic namespace that provides more meaning to the constants, and keeps them in their proper place.

**Bad**
`MANY_LANGUAGES = LANGUAGES.length > 1`

**Good**
`Langage.sorted_by_abbreviation.many?`

**Comment by briri** [comment]
If I recall the conversations about this correctly, the original concern was that the same DB query would be run on every page load with a very minimal likelihood that any of the data had changed. Would be good to discuss in our dev call. I'm all for getting rid of global constants 👍
