### ISSUE TITLE
Refactor getter and setter methods to use idiomatic Ruby

### ISSUE THREAD

**Issue by Bodacious** [DMPRoadmap/roadmap#1697]
There are several methods within the code that use a non-idiomatic method names for getters and setters.

In Ruby, it's generally unusual to prefix method names with `get_` and `set_`. This is also violates [most Ruby style guides](https://github.com/rubocop-hq/ruby-style-guide/issues/423).

I suggest we deprecate, and rename these methods.

**Comment by aaronskiba** [comment]
Closing this issue. I the best practices and rubocop rules do not recommend prefixing methods with `get_` and `set_`.
