### ISSUE TITLE
Post migration cleanup

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#170]
Trying to keep a running list of some things we should consider post migration:
- Remove old 'admin' and 'org_admin' perms if they are no longer necessary
- Move user.orcid_id to user_identifiers (see [migrate:move_orcids](https://github.com/CDLUC3/roadmap/blob/5d3ec89f9326207509b203d99d407a00b8ff397b/lib/tasks/migrate.rake)) and then need to drop that users.orcid_id column #

**Comment by jollopre** [comment]
@briri consider also plan.project_id, I spotted it today

**Comment by briri** [comment]
reevaluate the translation files. @jollopre noticed some old Portage DMPAssistant specific language. I would also imagine that some of the German, French and Spanish translations are missing for newer text strings

**Comment by briri** [comment]
Review any bad emails and see if the accounts can be deleted see log/migration.log

**Comment by briri** [comment]
Go through models once testing is complete and remove any commented out code.

**Comment by briri** [comment]
@jollopre suggests to remove the .yml files placed at config/locales/*.yml later on so that we avoid any confusion for external contributors. Meanwhile, it is safe to keep them there in case there are more lines such as I18n or t(...).

**Comment by briri** [comment]
drop the friendly_id_slugs table since we have removed the friendly_id gem

**Comment by briri** [comment]
Remove the old `admin_` prefixed controller endpoints and replace with standard ones. See the Templates controller and the available routes as an example:
```shell
admin_templates GET           /admin/templates(.:format)                      admin/templates#index
admin_index_template GET      /org/admin/templates/:id/admin_index(.:format)  templates#admin_index
``` 
Ideally we would just have
```shell
templates GET    /templates(.:format)      templates#index
```

**Comment by briri** [comment]
Review the routes.rb file and get rid of anything that is no longer in use or is not necessary. For example we have controller endpoints attached to the new Administrate super admin area that have no page on the site:
```shell
         admin_plan_guidance_groups GET      /admin/plan_guidance_groups(.:format)                              admin/plan_guidance_groups#index
                                    POST     /admin/plan_guidance_groups(.:format)                              admin/plan_guidance_groups#create
      new_admin_plan_guidance_group GET      /admin/plan_guidance_groups/new(.:format)                          admin/plan_guidance_groups#new
     edit_admin_plan_guidance_group GET      /admin/plan_guidance_groups/:id/edit(.:format)                     admin/plan_guidance_groups#edit
          admin_plan_guidance_group GET      /admin/plan_guidance_groups/:id(.:format)                          admin/plan_guidance_groups#show
                                    PATCH    /admin/plan_guidance_groups/:id(.:format)                          admin/plan_guidance_groups#update
                                    PUT      /admin/plan_guidance_groups/:id(.:format)                          admin/plan_guidance_groups#update
                                    DELETE   /admin/plan_guidance_groups/:id(.:format)                          admin/plan_guidance_groups#destroy
```

We should also consider shutting down non-html formats right in the controller (except for api endpoints)

**Comment by briri** [comment]
Remove references to Guidance.question in views (e.g. guidances/admin_show.html.erb)

**Comment by briri** [comment]
Clean out old guidance.question_id field as described in #221

**Comment by stephaniesimms** [comment]
reopening as this is still active
