### ISSUE TITLE
Show password not working on create account

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1702]
When I check the box to "Show password" on the create account page, nothing happens (pw still obscured - screenshot). This is only happening on this page.

![screen shot 2018-07-10 at 11 20 02 am](https://user-images.githubusercontent.com/12703638/42536536-3724108e-8447-11e8-8a59-c68169e54dad.png)

**Comment by stephaniesimms** [comment]
working as expected. closing.

**Comment by briri** [comment]
Reopening for verification after git cherry-pick

**Comment by stephaniesimms** [comment]
working as expected. closing again.
