### ISSUE TITLE
Add health-check endpoint for app

### ISSUE THREAD

**Issue by Bodacious** [DMPRoadmap/roadmap#1704]
Suggested at an earlier dev meeting:

We might like to have a more useful `/health-check` endpoint on the app. This would allow us to check at a glance how the various services were functioning.

I would suggest the action does the following:
- Check the DB connection is working fine
- Check the cache is working fine
- Check the server is responding fine (implied by a successful *200* response)

Are there security requirements we have to consider?

Thanks.

(Examples:)

``` ruby
def db_ok?
  ActiveRecord::Base.connection # instantiate connection
  ActiveRecord::Base.connected?
end

# Something like:
def cache_ok?
  Rails.cache.fetch("health-check") { Time.current } < Time.current
end
```

@raycarrick-ed @xsrust @briri

**Comment by magdalenadrafiova** [comment]
@briri and @xsrust is still still relevant?

**Comment by briri** [comment]
yes, this is covered by the new `api/v1/heartbeat` endpoint
