### ISSUE TITLE
Funders are unable to create new templates

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1710]
Funders cannot create a new template.

Login as super admin and go to the Admin -> Templates page. Change your Org affiliation to a funder org. Click the 'Create template' button. You will receive the following error:

![screen shot 2018-07-11 at 12 21 41 pm](https://user-images.githubusercontent.com/1204467/42594823-3a471978-8505-11e8-94f3-b9e9ed73fcbf.png)

**Comment by stephaniesimms** [comment]
this appears to be fixed now. i can also add links to funder templates again. closing issue.
