### ISSUE TITLE
Can't remove checkbox for internal template use only

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1712]
For funder/orgs (e.g. DCC, USGS) once a template has been marked for internal use only, I can't remove the status. Each time I uncheck the box and click Save, I receive a message that my change was successfully saved, but when I navigate away from the template details page and then return to it I find that the box is still checked for internal use only (screenshot). Correct behavior is to enable admins to remove the internal status.

![screen shot 2018-07-11 at 3 04 18 pm](https://user-images.githubusercontent.com/12703638/42601908-2453893c-851c-11e8-96b4-0469fd1b34b6.png)

**Comment by sjDCC** [comment]
Hi @briri I can't find this box to test. I think it may only show for a special category of organisation which is both a funder and an institution like USGS.

Can you advise how to generate test data, or can you point @mariapraetzellis to a way to test on your end?

**Comment by sjDCC** [comment]
Found a way to test this. Made one of our funders a funder and an org and could check box on and off. All saving correctly so closing out
![Capture](https://user-images.githubusercontent.com/6169940/68219455-ec5ec580-ffdd-11e9-9125-21a2a937c613.PNG)
