### ISSUE TITLE
Email change not working

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1714]
Users are not able to change their email on edit profile. An error is displayed that the save was unsuccessful. You need to re-enter the password to confirm the change but a modal isn't being displayed and longer - I'm pretty sure one used to pop-up.

**Comment by briri** [comment]
Hmm. So this is working for me. I am challenged with the password popup when I try to change my email. I get a failure message if the password I enter is incorrect but otherwise it saves my changes.

**Comment by sjDCC** [comment]
This is what I get on roadmap-stage. No modal pops-up to enter password.

![capture](https://user-images.githubusercontent.com/6169940/42806193-bdea8f4a-89a5-11e8-832f-8b982b606e88.PNG)

**Comment by stephaniesimms** [comment]
i can change my email address and save the change so this appears to be fixed. if i try to change it to another email that's already registered i get an unhelpful error msg (screenshot). will create a new issue to revise the error msg so users understand why the save was unsuccessful. closing this issue.

![screen shot 2018-07-18 at 4 18 09 pm](https://user-images.githubusercontent.com/12703638/42912918-c765bdf4-8aa6-11e8-9b99-9f12d1df28d6.png)
