### ISSUE TITLE
Entering an invalid email on Org details causes an error

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#172]
If you login and edit the organisation details and use an invalid email address (e.g. john.doe@somewhere.a) you receive an HTTP 500 error page.

Likely just not redirecting properly after the failed save.

**Comment by briri** [comment]
Code was failing when trying to attach the error message to flash[:notice]

**Comment by raycarrick-ed** [comment]
looks good. Moving to PR

**Comment by stephaniesimms** [comment]
Working as expected, but error message contains incomplete html tag/looks weird (see screenshot)

![screen shot 2017-04-10 at 9 47 28 pm](https://cloud.githubusercontent.com/assets/12703638/24893268/79a558e0-1e37-11e7-9592-04b52b9fbc7f.png)

**Comment by briri** [comment]
closing and opening as a new issue #234 because this may have an impact on all screens.
