### ISSUE TITLE
Text field should be mandatory for option based questions

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1725]
If I create a template with option-based questions (checkbox, dropdown, multi select, radio button) and don't enter anything into the Text field (screenshot 1), then publish the template, I don't see any options displayed when I create a plan with the template (screenshot 2). The Text field should be mandatory and marked with an asterisk to prevent admins from forgetting to enter something here.

1 - Creating a question with 2 checkboxes but nothing entered in the text field
![screen shot 2018-07-12 at 2 43 08 pm](https://user-images.githubusercontent.com/12703638/42662716-8e1febb4-85e7-11e8-9def-592bddf5cb9a.png)

2 - Creating a plan with this template; nothing is displayed under the question text
![screen shot 2018-07-12 at 2 41 40 pm](https://user-images.githubusercontent.com/12703638/42662718-91cec104-85e7-11e8-8041-5d8eabd95ad6.png)

**Comment by xsrust** [comment]
to clarify, this would be text for the question-options?

**Comment by stephaniesimms** [comment]
yes @xsrust - currently admins can create a bunch of options without question text and publish them. users then see the blank options when they go to write a plan with that template. it would be good to prevent this from happening by making the question text a mandatory field like we do for regular, text-based template questions.

**Comment by stephaniesimms** [comment]
testing on roadmap stage: 
- Question Number and Question Text lost the red asterisks marking them as mandatory fields. Need to reinstate asterisks (screenshot 1)
- also need to add an asterisk to the Text field next to radio buttons and other option-based questions per the original request above
- I am prevented from creating a question without text when I try to save, as expected. Revise the error message slightly for clarity and style (screenshot 2) as follows: 

Error: Unable to create the question.
- You must have at least one option.
- Option Text can't be blank.

![screen shot 2018-11-19 at 4 00 45 pm](https://user-images.githubusercontent.com/12703638/48742705-df05cb00-ec14-11e8-8578-b3892c369b22.png)

![screen shot 2018-11-19 at 4 01 34 pm](https://user-images.githubusercontent.com/12703638/48742709-e331e880-ec14-11e8-84d3-dae057478977.png)

**Comment by johnpinto1** [comment]
@stephaniesimms The error message above refers to two different problems:

-  the first one refers to the Question option for a checkbox or dropdown
- the second one refers to the missing Question text.

So I have changed the first text as suggested and clarified the second text 
as 'Text' is always appended to message at present and I can't work out how to remove it.
![error_message_for_questions](https://user-images.githubusercontent.com/8876215/48772299-e92ed480-ecbb-11e8-895f-25eb2613f0be.png)

We can change these messages.

The disappearance of the mandatory fields asterisks is something that is proving trickier to debug. The appropriate aria-label="true" no longer works. Perhaps @xsrust and @briri might be able to help me here.

**Comment by johnpinto1** [comment]
@briri I made the message changes above which @stephaniesimms agreed with at the last Tuesday meeting. However, I am still having trouble trying to get the * asterisk to appear for mandatory fields like Question text and options even though 'aria-required': true in code. Perhaps you can see a way of fixing that. I not going to look at it again until December 2nd.

**Comment by sjDCC** [comment]
Hi all. Functionality works correctly and message text looks good. There isn't an asterisk next to the text field for the dropdown options so I guess it remained unfeasible to do this. I'm ok without it if so as the error message tells you what's wrong. Closing out.
![asterisk](https://user-images.githubusercontent.com/6169940/49464575-2b473280-f7f3-11e8-9fc8-43727def939a.PNG)

**Comment by stephaniesimms** [comment]
Without the red asterisk the error message isn't precise enough to tell me why I was unable to create a question (screenshot below). I would suggest the following minor revision to the error msg:

"You must have at least one option with accompanying text."

![screen shot 2018-12-05 at 1 54 29 pm](https://user-images.githubusercontent.com/12703638/49546608-82054880-f895-11e8-8961-e1a6601d5178.png)

**Comment by johnpinto1** [comment]
![selection_091](https://user-images.githubusercontent.com/8876215/49583394-f8668100-f94f-11e8-881b-f303561ba750.png)

![selection_092](https://user-images.githubusercontent.com/8876215/49583434-1d5af400-f950-11e8-80a6-61f68669d573.png)
@sjDCC & @stephaniesimms I was able to make the changes requested thanks to @briri 's fix of the required fields javascript code and now that I have a better understanding on how it works. See attached images

**Comment by sjDCC** [comment]
Asterisk is now displaying and logic works correctly and brings up error if no text is entered.

Thanks @johnpinto1 - and for the screengrabs :)

**Comment by stephaniesimms** [comment]
yes both adjustments look good @johnpinto1 !
