### ISSUE TITLE
creating new account: 'my organisation isn't listed' doesn't select 'other'

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#1729]
Please complete the following fields as applicable:

**Expected behaviour:**

On 'create account' form, ticking 'my organisation isn't listed' should automatically select 'other' for organisation field 

**Actual behaviour:**
Organisation field remains empty and prompt message appears 'Please select an organisation from the list, or click the "My organisation isn't listed" link and enter your organisation's name.'

**Steps to reproduce:**

Create new account and click 'my organisation isn't listed'. 

Note: if you look at this issue today, 13/07/2018, please note that the account form doesn't work. By this I mean, when you fill in all fields correctly (and enter an organisation rather than choose other) and click 'create account' the form stays open on screen. New account isn't created. Apparently, this is a known issue and will be fixed when the new code is released.

**Comment by magdalenadrafiova** [comment]
@pherterich @mariapraetzellis this should be resolved with RoR if I am not mistaken - can we close?

**Comment by xsrust** [comment]
yep, this looks to be super-seeded by the RoR work
