### ISSUE TITLE
Email change bug on user profile page

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#173]
A user was unable to change his email address on the current live DMPonline service. The page saves but the value doesn't change. Check this bug doesn't exist in roadmap code

**Comment by briri** [comment]
related to #171

**Comment by briri** [comment]
The system requires the user to enter their 'Current Password' in when changing their email address. The page is just not displaying any error messages.

We should hold off on this fix until the fastgettext localisation work is complete and in DMPRoadmap/roadmap development branch. 

The solution to this issue should work towards solving the larger #175

**Comment by xsrust** [comment]
logic for changing email (and all other user attributes) updated in https://github.com/DigitalCurationCentre/roadmap/commit/970d646f0fe8db0198eb2013077d03edc2271b53.  Additionally, error messages were added to the page.

**Comment by briri** [comment]
this looks good. We may want to consider putting some messaging on the form, `/views/devise/registrations/edit.html.erb` to let the user know that the password will be required. That way they won't need to wait until they submit and we get the error response back from the server.

Once we get this out on the servers for testing we can ping the UX team and have them take a look. It might make more sense to reorganize the form layout.

**Comment by stephaniesimms** [comment]
Messages implemented. Everything working as expected. Agreed that we should ask UX team to evaluate the form layout--will ping them.
