### ISSUE TITLE
As a Super Admin saving Request Feedback page deletes Shib info

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1732]
As a Super Admin, if I make any changes to the Request Feedback tab on the Org details page and click Save it deletes the Shib configuration info for that Org

**Comment by sjDCC** [comment]
This sounds like #1684 when themes were deleted when saving customisations. Possibly worth seeing if similar fix applies

**Comment by stephaniesimms** [comment]
this is fixed, no more deleting shib info. closing.
