### ISSUE TITLE
Reset other_organisation name when a User changes org

### ISSUE THREAD

**Issue by Bodacious** [DMPRoadmap/roadmap#1736]
When a User changes from one Org to another, the System should reset the `other_organization` column to prevent stale data from lingering.

**Comment by sjDCC** [comment]
Not sure if we can UAT this, but the other org box disappears under edit profile when I switch to a listed institution

**Comment by stephaniesimms** [comment]
I observed the same behavior as @sjDCC when adjusting org affiliation under edit profile. that seems to be all we can test in the UI. closing issue.
