### ISSUE TITLE
Reinstate ability to add multiple themes to Guidance

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1742]
We changed the way admins apply themes to Guidance mainly to prevent having no themes - #1212 . But the restriction on applying only one theme per individual piece of Guidance turns out to be undesirable for users. @briri confirmed that it's not technically difficult to reinstate the ability to apply multiple themes. 

Many DMPtool users have requested this but if it poses problems for DCC services @sjDCC we can make this configurable. See screenshot below for an example of why users want to be able to apply multiple themes still. Previously UCSF could have one piece of Guidance with the themes "Data repository, Preservation, Data sharing" that ensured their suggested language about the IR would appear on any template with a question related to data preservation. Now they have to create 3 pieces of guidance to achieve the same.

![screen shot 2018-07-17 at 11 53 32 am](https://user-images.githubusercontent.com/12703638/42839308-3501bfec-89b8-11e8-8633-92c0093d4bb7.png)

**Comment by briri** [comment]
The call to the shared partial that handles the display of theme options takes an `as_radio` argument which defaults to false so it should be as simple as changing that flag to false here: https://github.com/DMPRoadmap/roadmap/blob/c62704337e7dc66fb8a4b519327e75d04ec9871b/app/views/guidances/new_edit.html.erb#L17

A thorough test should be done though to be certain.

**Comment by sjDCC** [comment]
Agree that we can allow multiple themes to be assigned to a piece of guidance. We allow multiple themes to be selected per question when adding templates so a similar model could be applied to guidance.

**Comment by stephaniesimms** [comment]
this turns out to be a bug. one example: a since a single piece of guidance (e.g. about the UC IR) that previously had multiple themes (Preservation, Data repo, Data sharing) is now duplicated as 3 pieces of guidance, with one theme for each. if a template question is tagged with more than one of these themes, the same guidance appears multiple times. it was a hot topic of discussion during the admin webinar today and something i promised we would revert back to allowing for multiple themes. thanks for the confirmation @sjDCC that this works for you too.

**Comment by stephaniesimms** [comment]
@briri i can still only select one theme at a time. also the tooltip should be revised slightly as follows:
- Select one or more themes that are relevant to this guidance...

![screen shot 2018-07-18 at 4 02 29 pm](https://user-images.githubusercontent.com/12703638/42912401-1a4e9c28-8aa4-11e8-8822-ffd20b144b61.png)

**Comment by stephaniesimms** [comment]
back to checkboxes and i can now select multiple themes. the only problem now is that nothing happens when i hover over the Themes tooltip @briri (i.e. no message pops up)
