### ISSUE TITLE
Request feedback message field should be mandatory

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1743]
On the admin interface, users can choose to switch on the option of offering feedback on plans. If so they need to enter a message to display to end users. This field is marked as mandatory but it is possible to save it without an entry, meaning a blank box is shown on the interface.

Ideally, the stock message would pre-populate the box and be available to edit. You can't copy and paste from the tooltip as it only displays on hover-over.

![default-message](https://user-images.githubusercontent.com/6169940/42878344-a890e510-8a84-11e8-9038-329706af7a08.png)

**Comment by johnpinto1** [comment]
It looks like saving an empty feedback message was already fixed since the bug was recorded. So I added the *Sample Message* from the tooltip to the page
![selection_121](https://user-images.githubusercontent.com/8876215/52857247-7ef0c900-311e-11e9-85f3-143d4a5d780f.png)

**Comment by magdalenadrafiova** [comment]
Hiya - this is fixed and looks brilliant - however would it be possible to change the msg to message please? please see image 
![msg-20022019](https://user-images.githubusercontent.com/47178106/53096997-56027680-3518-11e9-919a-5704b9768f31.PNG)
@johnpinto1

**Comment by briri** [comment]
Hi @johnpinto1,

If you want to get Rails to show better name for attributes like the one above, `orgs.email_msg`, you can add a replacement to the I18n locale files in `config/locales/[language].yml` in the active_record section. For example:
```yaml
en-GB:
  activerecord:
    attributes:
      org:
        email_msg: "Email Message"
  ...
```
https://github.com/DMPRoadmap/roadmap/blob/4d9665ef8c76736ac750fe6ed0763da26be2a0f3/config/locales/en-GB.yml#L3

Be sure to update all of the various locales. You can likely use Google translate for that.

**Comment by johnpinto1** [comment]
PR for change requested by @magdalenadrafiova

![Selection_026](https://user-images.githubusercontent.com/8876215/59029804-2bce8d80-8857-11e9-9990-418a1ea62754.png)

**Comment by sjDCC** [comment]
Looks good. Closing out
