### ISSUE TITLE
Potential queries to include in usage statistics

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1745]
Hi @stephaniesimms @jollopre 

I wanted to share some ideas from a user request for additional statistics. See below. I suspect most of these will be too difficult to generate and will fall out of scope, but since we're adding functionality, now is the time to consider it. 

We may be able to give total downloads per plan, or quantify how many times a plan has been shared, but I guess this would be difficult to calculate per period. I also can't think if a way in which we'd assess the use of the guidance.

Thoughts welcome on whether we can and want to add any of this

A few additional questions/wishes.

To get an indication of the “seriousness” of a plan, we would like to know:
-	the number of downloads of plans: per period, per plan
-	the number of plans that are shared – per period.
I expect that those data would not be too difficult to produce, am I right?

Furthermore, we have a few wishes
It would be very nice if we could monitor the use of our template, more specific: 
-	which questions are left open most frequently – per period
-	how many times the guidance of a specific question is used – per period
This will give us information about the usefulness of our template and guidance.

**Comment by briri** [comment]
we do have an `exported_plans` table which records every time a plan is downloaded. As far as I know its never used for anything so it would be good to start using it here :)

we should also be able to determine shares per period as well, but @jollopre can verify if its within scope as it may require some fancy SQL to keep the query from taking a very long time to run.

**Comment by jollopre** [comment]
@sjDCC we can use JS libraries that track and report web traffic (e.g. google analytics) for:
- total downloads per plan
- how many times a plan has been shared
- the number of downloads of plans: per period, per plan
- the number of plans that are shared – per period
- ...

that way we don't need to store and retrieve data from our db. In addition these libraries provide fancy interfaces to query data per periods nicely. If we decide to go for this route, it would be a matter of adding tracking events for links such as (download plan, share a plan, etc). As a drawback, these interfaces would be outside of our service.

**Comment by sjDCC** [comment]
Given that these are feasible it sounds like they could be useful additions to get a sense of depth of use. What do you think @stephaniesimms

**Comment by mariapraetzellis** [comment]
Integration w/ Google Analytics (#2344 ) addressed these issues so closing this ticket.
