### ISSUE TITLE
Revise error message for failed attempt to change email address

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1749]
related bug fix #1714 
When a user tries to change their email address to one that is already registered they receive a vague error message (screenshot below). Revise the error text as follows:
- Error: Save unsuccessful. That email address is already registered. You must enter a unique email address.

![capture](https://user-images.githubusercontent.com/6169940/42806193-bdea8f4a-89a5-11e8-832f-8b982b606e88.PNG)

The problem may be that the email I was changing it to was already known by the system though.

**Comment by sjDCC** [comment]
@xsrust @briri can you confirm whether this code has been deployed. I still get the old 'Save unsuccessful' text on DMPonline-test and roadmap-stage

**Comment by sjDCC** [comment]
All working as expected now. Closing out.
