### ISSUE TITLE
Themes tooltip not working on Guidance page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1750]
Nothing pops up when I hover over the question mark next to Themes while creating Guidance

Text for tooltip should read:
- Select one or more themes that are relevant to this guidance...

![screen shot 2018-07-19 at 12 55 34 pm](https://user-images.githubusercontent.com/12703638/42966785-12060f38-8b53-11e8-91d6-a253c98ea0c0.png)

**Comment by sjDCC** [comment]
I think this is fixed so closing out. Tooltip displays on current live site
