### ISSUE TITLE
Consolidate JS validation code

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1752]
We currently have 2 JS files that deal with form field validations. The original and most heavily used is `utils/ariatiseForm.js`. This file though only allows for validations to occur on form submit and does not allow for us to make fields 'validatable' based on certain scenarios (e.g. link text only becomes required when a user enters a link URL). 

To deal with that scenario we created a `utils/validations.js` file which allows you to 'enable/disable' validations on a given control. With the intent of updating all form validations so that they use this new file and trigger a validation check when the user tabs off the field as well as when the form is submitted.

Our JS validation alerts are also not accessible #1446. We should address that while reconciling these 2 files.

These files are beginning to become out of sync and I fear will become maintenance nightmares as time goes by and new devs enter the mix. We should refactor `utils/validations.js` so that it is properly handling all use cases and then update all of the individual form js files to use it.

**Comment by briri** [comment]
Discussed with the team and we will be removing the JS field validation logic and instead allow Rails to process validations and report back to the user. Now that we have proper model level validations in place this will simplify maintenance going forward.

Need to:
- Update controller logic to return field level validation errors so that they can be displayed in the normal notification area.
- Update JS to only provide support for the accessible autocomplete controls and to add the required field asterisks
- Ensure that all necessary aria tags are on the appropriate fields

**Comment by sjDCC** [comment]
Am unsure if we can UAT this. Please advise what we should test if so

**Comment by stephaniesimms** [comment]
i dont think we can UAT exactly but would notice issues w/field form validations, etc if things were amiss. will close this issue and just be vigilant when testing all the things.
