### ISSUE TITLE
Add a button to download a list of users

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1754]
Feedback from DMPTool admin webinar:
Is it possible for administrators to get a dynamic or downloadable up to date list of users versus screen scraping the list we see on the admin page? This will also help us identify resources and outreach more programmatically and hopefully greater adoption of the DMPTool. 

- Add a 'Download users' button to create a CSV report from the Admin Users page, just as we have on the Plans page.

**Comment by sjDCC** [comment]
This works fine - thanks for adding. Could we put the button in the same place as the 'plans' page though and call it 'Download users' to keep things consistent? I couldn't spot it at first. Thanks

![download-users](https://user-images.githubusercontent.com/6169940/46549581-76fc5f00-c8ca-11e8-8a6a-5854bf523bc8.PNG)
![download-users2](https://user-images.githubusercontent.com/6169940/46549580-76fc5f00-c8ca-11e8-8ede-8c5a88aee8aa.PNG)

**Comment by stephaniesimms** [comment]
i second @sjDCC request to move and rename the button for consistency with the plans page (screenshot above). otherwise it's great @johnpinto1 
- move button to upper right above the table
- change button text to 'Download users'

**Comment by sjDCC** [comment]
hi @johnpinto1 Sorry to be finnicky about this, but could we ensure buttons are aligned so it looks slick and change the text to "Download users" for consistency please. Thanks :)

![align](https://user-images.githubusercontent.com/6169940/46687154-0e76f000-cbf2-11e8-8078-3aa175bf4db1.PNG)
![align2](https://user-images.githubusercontent.com/6169940/46687155-0e76f000-cbf2-11e8-8740-a46863ad0eb2.PNG)

**Comment by stephaniesimms** [comment]
button and functionality are mostly working as expected now. the only issue i noticed is with date formats, which i expect is a configuration setting. will create a new issue for that. closing this one.

**Comment by johnpinto1** [comment]
@stephaniesimms At present the date format is hard-coded '%d.%m.%Y' in the code at present. I forgot that the US have a different date format. I can look at this tomorrow as part of this. Perhaps @xrust, @Bodacious, @briri could suggest how I get round date format issue depending on locale the issue in ***models/user/at_csv.rb***: 


```
def to_csv
      CSV.generate(headers: true) do |csv|
        csv << HEADERS
        @users.each do |user|
          name = "#{user.firstname} #{user.surname}"
          email = user.email
          created = user.created_at.strftime('%d.%m.%Y')
          last_activity = user.updated_at.strftime('%d.%m.%Y')
          plans = user.plans.size
          active = user.active ? 'Yes' : 'No'
      
          if user.can_super_admin?
            current_privileges = 'Super Admin'
          elsif  user.can_org_admin?
            current_privileges = 'Organisational Admin'
          else
            current_privileges = ''
          end
          
          csv << [ name, email, created, last_activity, plans, current_privileges,  active ]
        end
      end
    end
```

**Comment by briri** [comment]
Hi @johnpinto1 we maintain a small subset of the I18n localization files in the config/locale directory. You should be able to pull in the appropriate one by using the following:
`l (user.created_at, format: :short)`

**Comment by Bodacious** [comment]
@briri @johnpinto1 already done in #1948 :)
