### ISSUE TITLE
Remove multi select box as an answer format?

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1771]
We've had confusion from some admin users about what the multi-select box option is. Essentially this is the same as checkboxes, but displays all options in a dropdown where you use command / control to select multiple. It used to be used for the theme selection but we have changed this to simple checkboxes now for usability.

@stephaniesimms I think you had some issues selecting multiple via Mac previously. The user has reported not being able to select multiple too. 

Is there a desire to retain this or should we remove it? I'm not sure it's used anywhere in the services but we should obviously check that before deciding

**Comment by stephaniesimms** [comment]
@briri can you check dmptool data to see if anyone implemented multi select boxes? if not i'm happy to remove them as an answer format @sjDCC . and if just a few folks are using them we should be able to reformat those questions as checkboxes and remove still.

**Comment by sjDCC** [comment]
@xsrust @Bodacious If you could check our services too that would be great. I have a hunch they're not much used though too

**Comment by briri** [comment]
@stephaniesimms we have 16 templates that use the multi-select box but none of them appear to have any values defined. So unless they have the 'additional info' checkbox ticked then there's actually nowhere for the user to answer the question. I'll send you the list on Slack

**Comment by sjDCC** [comment]
This still shows up when you edit existing template questions and create new ones.
![multi-select](https://user-images.githubusercontent.com/6169940/46548411-ea9c6d00-c8c6-11e8-8c6b-12eedd6fe98c.png)

Once we remove, can we also check data for DMPonline and other DCC services please @xsrust to ensure it doesn't throw any validation errors. If there is any existing data I assume we can switch it to multiple choice instead. That's the same functionality but different display

**Comment by sjDCC** [comment]
This all looks good to me. Thanks @johnpinto1 

I wasn't sure of which templates used the mutli-select box but if you know that @stephaniesimms you may want to check their data looks ok too

Closing out
