### ISSUE TITLE
Temporary workaround to allow new user to setup the application without encountering migration issue

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#1774]
I see that we have this issue: https://github.com/DMPRoadmap/roadmap/issues/85, but in the mean while new user still cannot setup the app without encountering migration errors, for example I see this when trying to migrate the migrations:
`uninitialized constant ChangeVersionsPublished::Version
`

Would it be valuable to have a temporary workaround to bypass this issue, so new user can set up the app and get it running without facing migration error?
I went into the migration and comment out and change a few lines, but I'm not sure if it breaks anything:

db/migrate/20131118094629_change_versions_published.rb
-    if table_exists?('versions')
-      Version.reset_column_information # make the new column available to model methods
-      Version.all.each do |v|
-        v.published_tmp = v.published == 't' ? true : false
-        v.save
-      end
-    end

db/migrate/20161206122926_add_foreign_keys.rb
-      UsersPerm.includes(:user).all.each do |u|
+      Perm.includes(:user).all.each do |u|

-          UsersPerm.delete_all(user_id: u.user_id)
+          Perm.delete_all(user_id: u.user_id)

db/migrate/20170702012742_ensure_indexes_in_place.rb
-    add_index :annotations, :question_id

db/migrate/20180313120831_add_required_indices.rb
-    add_index :plans_guidance_groups, [:guidance_group_id, :plan_id]

db/migrate/20180405151713_rename_template_fields.rb
-    rename_column :templates, :migrated, :archived
-    rename_column :templates, :archived, :migrated

**Comment by briri** [comment]
Hi @Yu-Chieh-Henry-Yang,

The db migrations are problematic and we are aware of this. The installation instructions ask you to use `rake db:schema:load` when setting up a new installation. Once the `schema:load` process has run it records all of the migrations in your database so that they are not run in the future.

**Comment by Yu-Chieh-Henry-Yang** [comment]
@briri  
Thank you for the reply!
Do you know how soon this will be fix completely?

**Comment by briri** [comment]
Hi @Yu-Chieh-Henry-Yang 

We have no immediate plans to clean up the old migrations. We also use Capistrano to deploy our instance of the DMPTool and have no issues. I you use `db:schema:load` it will create your initial DB and 'remember' which migration files were in the directory when it was run. The next time `db:migrate` is run it will only run new migrations.

For more information on ActiveRecord migrations please refer to: https://edgeguides.rubyonrails.org/active_record_migrations.html

The `dump_schema_after_migration` configuration is false by default in `production.rb`. You shouldn't need it. The Rails engine does not use it when starting up your server. It is only used to build your test DB and to document what your DB schema looked like the last time `db:migrate` or `db:schema:dump` was run.
