### ISSUE TITLE
TinyMCE form broken on template edit page

### ISSUE THREAD

**Issue by Bodacious** [DMPRoadmap/roadmap#1777]
Please complete the following fields as applicable:

**Expected behaviour:**
When I add a new section to a template, the section's description field should load as a TinyMCE editor

**Actual behaviour:**
When I add a new section to a template, the section's description field loads as a standard HTML textarea with HTML inside.

**Steps to reproduce:**
Add a new section to a Template. NOTE: This doesn't seem to affect the existing sections that are loaded via AJAX

![screen shot 2018-08-03 at 12 40 03](https://user-images.githubusercontent.com/73998/43641121-66f166fa-971a-11e8-99bd-cc0ce504d589.png)

**Comment by stephaniesimms** [comment]
I just tested and when I create a new section the TinyMCE editor loads as expected, but after i enter a description and click Save i see the HTML area as reported above  (screenshot below). 

a perhaps related issue, I cannot add questions to the section. after I click to 'Add Question' enter question text and click 'Save' there is no record of my question and no error msg.

![screen shot 2018-08-16 at 8 27 35 am](https://user-images.githubusercontent.com/12703638/44218461-97136b80-a12e-11e8-8d6f-4441aa358052.png)

**Comment by Bodacious** [comment]
Hi @stephaniesimms 

I noticed that issue with the forms not loading as proper TinyMCE a few days ago.

Fixed today as part of 736a17dbd119c0b90038db1e0515d919189e3b83

**Comment by stephaniesimms** [comment]
thanks @Bodacious - we both noticed it too while testing. will check again once it's deployed.

**Comment by sjDCC** [comment]
Looks good now. Closing out
