### ISSUE TITLE
Change Submit buttons to Save on Project details page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1781]
Usability testing feedback from DataONE researchers at Ecological Society of America meeting:
"the “Submit’ button on the project details page was off-putting because they didn’t want to be sending it anywhere. On other pages you ‘Save’ which they were more comfortable with." 

Change the labels on the two "Submit" buttons to "Save" for consistency, as well as for the reason stated above. 

![screen shot 2018-08-06 at 11 27 40 am](https://user-images.githubusercontent.com/12703638/43734189-d3c9c40e-996b-11e8-9605-4de224d25d54.png)

**Comment by sjDCC** [comment]
Sure, happy for these to be ‘save’ buttons instead

**Comment by stephaniesimms** [comment]
i noticed this change has been implemented. closing issue.
