### ISSUE TITLE
Why doesn't `npm run bundle — -p` (webpack -p) compile the asset for my rails app?

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#1782]
**Reproducing the issue:**
1) I forked this rails project (https://github.com/DMPRoadmap/roadmap) and I set it up and start the server using rails s

2) Before I compile its asset by running npm run bundle (should equal to webpack, because my package.json file's scripts section ask bundle to call webpack), the website doesn't show image and layout properly

3) so I compile its asset by running npm run bundle, the website now is showing image and layout properly

4) I close the webpack by pressing CTRL + C, the website is still showing image and layout properly

5) I run npm run bundle -- -p which should be equal to webpack -p, the website does not display the images and layout properly anymore.

**Issue:**
Why is npm run bundle -- -p (which is webpack -p) not compiling the asset properly? I thought it is the daemon version of npm run bundle (which is webpack) and daemon means running in background (I thought daemon is the same as service?)?

Please correct me if I understand the concept incorrectly or use the term incorrectly anywhere.

Thank you!

**Comment by briri** [comment]
Hi @Yu-Chieh-Henry-Yang I'm not sure what you are trying to do. Are you trying to run the system locally in a development mode or in a production environment?

When you run `webpack -p` (or in our case `npm run bundle -- -p`) its simply telling webpack to bundle up your JS and CSS resources for production. This means that it minifies all of the files into a single application-[fingerprint].js and application-[fingerprint].css (after compile your SCSS files and fathering all of the necessary JS files together). The files it generates are then copied into the `public/javascripts` and `public/stylsheets` directories.

It doesn't run webpack as a daemon that watches for changes to your files. 

In development, I run `rails s` in one terminal window and `npm run bundle` in a separate window (Mac OSX). This start ups webpack and has it watch your files. As you make changes you can then see the changes in your browser when you refresh the page (after a short delay for the compiler and linter to run).

**Comment by Yu-Chieh-Henry-Yang** [comment]
Hi @briri 

The reason I thought `webpack -p` will run webpack as a daemon that watches my file change is because the [installation page](https://github.com/DMPRoadmap/roadmap/wiki/Installation) says:

> (If you prefer to daemonize Webpack please use npm run bundle -- -p instead)

I misunderstand how webpack works and was confused, thank you for explaining it and clarify it.

**Comment by briri** [comment]
Ah thank you for point that out @Yu-Chieh-Henry-Yang. I will update our documentation

**Comment by Yu-Chieh-Henry-Yang** [comment]
Hi @briri, Thank you for updating the wiki installation guide:

> If you are deploying to a production or staging server we recommend adding '-p' arg to the `npm run bundle -- -p` command. This will compile your assets and add a unique fingerprint id to the files (Webpack will not continue to run and watch your files).

However, the -p option doesn't seem to work correctly in production environment currently

I cloned this project, follow the installation guide, use `npm run bundle -- -p` instead of `npm run bundle` and startup the rails server by using `rails s -e production`. I expect to see the website to show up normally with asset correctly displayed, but that's not the case:

![screen shot 2018-08-09 at 3 38 06 pm](https://user-images.githubusercontent.com/19463606/43881385-2f68810c-9beb-11e8-9a9d-9440854acf42.png)

For files inside `public/javascripts` and `public/stylesheets`, if I remove the `-fingerprint` part in their filename, then the pages shows correctly.

but `def fingerprinted_asset(name)` seems to work correctly, which is strange

**Comment by Bodacious** [comment]
Closing this issue. Latest question has been raised and addressed in a separate issue:
#1799
