### ISSUE TITLE
Ability to upload images as part of DMPs

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#179]
In the past we've been asked to have an image upload facility as part of DMPs. This would be useful for example on AHRC templates where projects are asked to provide a gantt chart. The Finns share an example of an image provided in one of their DMPs 

![picture1](https://cloud.githubusercontent.com/assets/6169940/24056764/d105bcd2-0b3c-11e7-9fb4-1ba0f7699ada.jpg)

**Comment by stephaniesimms** [comment]
ok to move this to future enhancements wiki @sjDCC ?

**Comment by sjDCC** [comment]
Actually we've been asked for this several times so I'd like to understand how big a task it is before we siphon it off. The option to display multiple suggested answers was also a key feature request but was done with a small amount of effort in ticket #1344 

What is the process for allowing images to be displayed? Is there a TinyMCE option we can enable? If this is a few days work I'd leave it in the post-MVP tasks so we have some small features that are desired as well as bug fixes in the next few releases.

**Comment by jollopre** [comment]
TinyMCE seems to have a plugin to insert images into the tinymce area (e.g. https://www.tinymce.com/docs/plugins/image/). I can see two options right now:
- Adding this plugin and permit linking to image in remote locations
- Enabling support in our server to upload images which might require any sort of antivirus to check the file passed and decide what's best to store it (directory, db blob, ...). (not that quick)

**Comment by pherterich** [comment]
Same as #2233 so closing this one
