### ISSUE TITLE
JS errors on create plan page

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#180]
There is a JS error on the create plan page. If you click on the funder dropdown and select a funder a JS error occurs. The error is on the lib/assets/javascripts/projects.js file. It references a function that no longer exists `getTemplateList()`.

Its possible that this has been fixed on the local dev instance in a copy of the file in **app**/assets/javascripts/. Those files override the default ones in **lib**/assets/javascripts/ but are ignored by git to prevent local branding from mixing with the core repository

**Comment by stephaniesimms** [comment]
tested and working as expected
