### ISSUE TITLE
Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#1806]
**Expected behaviour:**
For DB, brew install with mariadb@10.1 should work, since installation guide said require

> PostgreSQL >= 9.2 or MySQL / MariaDB >= 5.5

and according to https://mariadb.com/kb/en/library/server-client-software/mariadb-releases/compatibility-differences/mariadb-vs-mysql-compatibility/, mariadb 10.1 is greater than 5.5 and should be okay

**Actual behaviour:**

It fails with error

**Steps to reproduce:**

1) On a Mac, install mariadb@10.1 using `brew install mariadb@10.1`
2) Follow wiki installation guide
3) fail at `rake db:schema` load with this error:

> ActiveRecord::StatementInvalid: Mysql2::Error: Specified key was too long; max key length is 767 bytes: CREATE UNIQUE INDEX `index_settings_on_target_type_and_target_id_and_var`  ON `settings` (`target_type`, `target_id`, `var`)

Possible Solution:
Change index for settings and users in schema to the following:
```
  add_index "settings", ["target_type", "target_id", "var"], name: "index_settings_on_target_type_and_target_id_and_var", unique: true, length: {"target_type"=>191, "target_id"=>nil, "var"=>191}, using: :btree

  add_index "users", ["email"], name: "index_users_on_email", unique: true, length: {"email"=>191}, using: :btree
```

**Note**
In README:
1 - the `bundle install` step need to come before the `rake secret` step
2 - the `rake db:create` step need to be taken before `rake db:schema:load`

In seed.rb file,
3 - Should we remove lines with `dmptemplate_id` and `migrated` so that seed loading will work?

This post might be helpful: https://github.com/turnkeylinux/tracker/issues/985

Also, I don't know why the schema completely changed after I do a `rake db:migrate`, does anyone know why?

**Comment by Bodacious** [comment]
Hi @Yu-Chieh-Henry-Yang 

Thanks for bringing this to our attention. Unfortunately, the documentation is wrong or out of date. We don't support MariaDB as a database adapter. 

I'll update the documentation now.

We do support MySQL and PostgreSQL. So if you're having problems with either of those, please open an issue and we'll have a look.
