### ISSUE TITLE
Error creating new templates

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1818]
When I click to create a new template and enter a name, I hit this error
![template-create-error](https://user-images.githubusercontent.com/6169940/44218889-90a6e300-a172-11e8-9c0c-cddbc925baeb.PNG)

**Comment by Bodacious** [comment]
this should be fixed on -dev since the database has been updated.

**Comment by Bodacious** [comment]
Closing

**Comment by xsrust** [comment]
Looks to be working on -dev at the moment
