### ISSUE TITLE
Section description box reverting to old style

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1820]
We had changed all text boxes to be TinyMCE but the section description box is reverting to the old style. I noticed this when adding section on the 'customise template' view, but see it's happening when you edit existing templates too
![tinymce-box](https://user-images.githubusercontent.com/6169940/44219004-d95e9c00-a172-11e8-9e92-1f6130173543.PNG)

**Comment by stephaniesimms** [comment]
copying to duplicate issue #1777
