### ISSUE TITLE
Super-admin organisation switcher not working

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1835]
The templates page on the admin interface has a place for Stephanie and I to change affiliation. This is currently throwing an error. You can successfully change organisation via edit profile though.

Please note that this should only display for super-admin users.

![ord-switcher](https://user-images.githubusercontent.com/6169940/44477223-ec211700-a631-11e8-8889-e7b63570cfa3.PNG)

**Comment by stephaniesimms** [comment]
this works for me on roadmap stage @sjDCC

**Comment by sjDCC** [comment]
I don't think @briri has deployed the latest fixes yet so best to double-check when in sync. We agreed to deploy to DMPonline-dev to keep moving in interim

**Comment by stephaniesimms** [comment]
now that the latest code is deployed on roadmap stage i can confirm that this is not working. moving issue to current sprint board.

**Comment by sjDCC** [comment]
Works fine now thanks. Closing out
