### ISSUE TITLE
Can't download public or org DMPs

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1841]
When I click to download a pdf for any plan listed in the Public DMPs list https://uc3-roadmap-stg.cdlib.org/public_plans or in the Org plans table on My Dashboard (screenshot 2) I get the error message below 

![screen shot 2018-08-24 at 2 08 37 pm](https://user-images.githubusercontent.com/12703638/44608115-7f2f8d80-a7a7-11e8-9802-f566f1bcbb6a.png)

![screen shot 2018-08-24 at 2 17 31 pm](https://user-images.githubusercontent.com/12703638/44608438-9327bf00-a7a8-11e8-8f92-7bbb56c5db32.png)

**Comment by sjDCC** [comment]
Plans are downloading but we have font errors for Arial it seems as the display is a page of symbols.

@xsrust it seems there are 4 pages where this occurs:
- public DMP page
- DMP templates page (PDF)
- My plans dashboard (org plans)
- Plan download (since preset is Arial)

**Comment by Bodacious** [comment]
This should be working now, @sjDCC 

@xsrust has installed the missing fonts on the server.

**Comment by stephaniesimms** [comment]
no more wingdings! public plans look good. i'll verify that org plans are working too before closing this out. thanks @Bodacious

**Comment by stephaniesimms** [comment]
the PDFs should use Arial font for both public and org plans. currently they're in Times New Roman or some other serif font. please just switch to Arial and then this will be fixed.

**Comment by stephaniesimms** [comment]
just confirmed that PDF download is working for public and org plans. but currently they're in Times New Roman. please just switch default font to Arial and then this will be fixed.

**Comment by xsrust** [comment]
@stephaniesimms This issue is related to the installed fonts on our testing server and is not a roadmap issue, so I'm closing this one out.
