### ISSUE TITLE
Recaptcha form on Contact page not working

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1842]
I can't submit the contact form because the Recaptcha isn't working. I get the error message in screenshot 2 when I click submit.

![screen shot 2018-08-24 at 2 14 49 pm](https://user-images.githubusercontent.com/12703638/44608282-18f73a80-a7a8-11e8-88de-4cfe7862d7c6.png)

![screen shot 2018-08-24 at 2 13 50 pm](https://user-images.githubusercontent.com/12703638/44608264-08df5b00-a7a8-11e8-95e2-01359fec51e9.png)

**Comment by briri** [comment]
This is likely just a deployment issue. will take a look on roadmap-stg

**Comment by briri** [comment]
I can't replicate this issue @stephaniesimms. I tried when logged in and when not and both worked without issue.

**Comment by stephaniesimms** [comment]
ok this was in Chrome when not logged in but now that you redeployed it's working. closing.
