### ISSUE TITLE
Can't create plans w/funder or Org templates

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1843]
I can only create a new plan with the default template: if I check the box for "No funder" and there are no Org templates. 

If I try to use an Org template I get the error message in screenshot 1. If I try to select a funder, the appropriate selections appear in the combobox but I get the error message in screenshot 2.

![screen shot 2018-08-24 at 2 23 06 pm](https://user-images.githubusercontent.com/12703638/44608691-75a72500-a7a9-11e8-9f63-618753dd27d5.png)

![screen shot 2018-08-24 at 2 20 26 pm](https://user-images.githubusercontent.com/12703638/44608696-79d34280-a7a9-11e8-8699-ce1b7275b667.png)

**Comment by sjDCC** [comment]
All working now. Can get funder and institutional templates. Closing out
