### ISSUE TITLE
Downloading my own plans produces empty files

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1844]
For all file formats I get an empty file with just the Project Title when I try to download a plan. The project details coversheet info is populated correctly if I select that box (screenshot) but all answers and other content are missing. https://roadmap-stg.cdlib.org/plans/12849/download

![screen shot 2018-08-24 at 2 29 00 pm](https://user-images.githubusercontent.com/12703638/44608843-2f9e9100-a7aa-11e8-99fb-cccec199a406.png)

**Comment by sjDCC** [comment]
I'm still experiencing this on legacy plans but not new ones

**Comment by stephaniesimms** [comment]
Similar to what @sjDCC noted above, I still don't get any plan content (only coversheet info) when I try to download existing plans. This remains the case after editing questions.

**Comment by stephaniesimms** [comment]
I can now download my plans in all file formats with full content @Bodacious - the only change required is that default font setting for PDF and HTML should be Arial. currently it's Times New Roman. I also noted the default font correction in related issue #1841.

**Comment by stephaniesimms** [comment]
the plan content is there now but the download setting selections are not actionable. for new and existing plans i get the same contents for all plan download attempts in all file formats regardless of the boxes i select in the download settings. the default download seems to include: 
- the project details coversheet
- section headings and answers
- unanswered questions

desired behavior is to always include answers, but then allow the user to select the desired optional plan components. i can close this issue and raise a new one to address the remaining problems if you prefer @xsrust

**Comment by xsrust** [comment]
Found a pre-existing issue in the controller logic which was causing this behavior.  Should be fixed now.

It was just an auth change, so worth checking if there's other issues with the download format as well.
I would say to add them as new issues so they can be tracked as they will likely be separate to the work for this issue.

**Comment by stephaniesimms** [comment]
all plan download behavior seems to be working as expected now. i didn't find anything else amiss so nothing new to report at the moment @xsrust - but we'll keep a lookout. thanks. closing issue.
