### ISSUE TITLE
User receives error msg when requesting feedback on a plan

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1845]
When I click the button to request feedback on a plan in the Share tab, I get the error message below. The plan is submitted, however, and appears in the Admin menu Plans table as expected (screenshot 2). The Request feedback button is also grayed out as expected (screenshot 3). 

The bug appears to lie with the error message, which should instead be a success message. Also the admin does not receive an email notification that the plan was submitted.

![screen shot 2018-08-24 at 2 35 47 pm](https://user-images.githubusercontent.com/12703638/44609281-ddf70600-a7ab-11e8-9bb7-c07d2486c1c1.png)

![screen shot 2018-08-24 at 2 40 17 pm](https://user-images.githubusercontent.com/12703638/44609331-1991d000-a7ac-11e8-91a9-c6a26e037892.png)

![screen shot 2018-08-24 at 2 35 57 pm](https://user-images.githubusercontent.com/12703638/44609337-1f87b100-a7ac-11e8-9843-f0d09d992bfc.png)

**Comment by sjDCC** [comment]
This seems to be working now. I could submit a plan for feedback. I received the correct notice message and the email was distributed. Closing out.
![message](https://user-images.githubusercontent.com/6169940/45599207-4fa72600-b9df-11e8-93c6-3f08d5889e39.PNG)
