### ISSUE TITLE
Guidance page: publish, Add, View, Edit guidance

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#185]
1. during testing I unchecked the box for Publish guidance for DCC (UK) guidance - published status changed to "No" as expected

however, I can't republish the guidance from the View or Edit menus. when I click the button to "Publish" I receive the message that "Guidance group was successfully updated" but the status remains "No" (see screenshots below)

![edit-guidance](https://cloud.githubusercontent.com/assets/12703638/24119452/78435684-0d6e-11e7-8683-761033958714.png)

![publish-guidance](https://cloud.githubusercontent.com/assets/12703638/24119312/f0e8fe6e-0d6d-11e7-992f-e95850689599.png)

2. clicking "Add guidance" button next to Guidance List throws the error below

![add-guidance](https://cloud.githubusercontent.com/assets/12703638/24119731/76c6b2e6-0d6f-11e7-9d59-e6c0d7eec8e0.png)

![sorry](https://cloud.githubusercontent.com/assets/12703638/24119807/a51a4ee6-0d6f-11e7-8563-fc50fc54c21b.png)

3. clicking "View" in Actions column throws the "We're sorry something went wrong" error

4. after editing guidance, I cannot save it. Clicking Save produces a pop-up (screenshot below) but after clicking "Ok" changes are not saved.

![edit-guidance](https://cloud.githubusercontent.com/assets/12703638/24120086/962618ec-0d70-11e7-973a-869d78a4eddc.png)

5. clicking "Add guidance" on editing page also throws "We're sorry" error

![add-guidance-error](https://cloud.githubusercontent.com/assets/12703638/24120155/d3ae937e-0d70-11e7-88c9-4f40927eaa1b.png)

**Comment by briri** [comment]
The error behind the "We're sorry, but something went wrong" page above is:
```shell
App 660 stdout: I, [2017-03-20T15:28:32.691981 #660]  INFO -- : Completed 500 Internal Server Error in 4ms (ActiveRecord: 1.4ms)
App 660 stdout: F, [2017-03-20T15:28:32.692827 #660] FATAL -- : 
App 660 stdout: ActiveRecord::AssociationNotFoundError (Association named 'question' was not found on Guidance; perhaps you misspelled it?):
App 660 stdout:   app/controllers/guidances_controller.rb:16:in `admin_show'
App 660 stdout: 
App 660 stdout: 
```

**Comment by briri** [comment]
Add guidance not loading because of missing question mark character in the include method call:
```ruby
		@phases = nil
		@templates.includes(:phases).each do |template|
			if @phases.nil? then
				@phases = template.phases.all.order('number')
			else
```
guidances_controller.rb line 29

Should be `@templates.include?`

**Comment by briri** [comment]
@jollopre did we make any decisions on how to pull the Fastgettext translations into our JS files? See the screenshot above that mentions the missing I18n translation.

**Comment by jollopre** [comment]
@briri, we didn't agree anything regarding the JS translations. This repo https://github.com/webhippie/gettext_i18n_rails_js (recommended by gettext_i18n_rails) translates the .pot and .po files into json files under assets. 

I think is worth to try how it works. I have quickly read its README although I'm not totally convinced about Jed library for retrieving the json files. 

We should create a new issue to explore the JS translations ...

**Comment by vyruss** [comment]
@briri @jollopre agree about creating a issue. I'm not worried about Jed right now, from the description the solution sounds quite clean and we can always revisit in the future.

**Comment by briri** [comment]
Agreed. Just created a new ticket #204

**Comment by stephaniesimms** [comment]
Publish/unpublish guidance working as expected.
