### ISSUE TITLE
Update template customisation to prevent duplicates

### ISSUE THREAD

**Issue by Bodacious** [DMPRoadmap/roadmap#1853]
When updating a Template via `upgrade_customization!`, there's a risk that duplicate sections and annotations might be added. 

This bug may happen in cases where the Template has customised versions where the number value of sections, phases, and annotations might have changed.

Add a new attribute to these models that is persisted across Template versions and represents the position of the record within the parent.

**Comment by sjDCC** [comment]
Hi @Bodacious is this validation related to transferring customisations when a funder template is updated? I tried to test that and hit an error. Here's what I did on DMPonline-dev:

1. Customised the AHRC template for Glasgow School of Art by adding a section before and after the main funder template. Reordering worked fine and all presented well as an end user writing plans.

2. Edited the AHRC template by adding a new funder section

3. Returned as a GSA admin to transfer my customisation. Error was thrown saying customisation couldn't be transferred. I then got an option to 'edit customisation' but all I see if the new AHRC template, not my two sections

**Comment by Bodacious** [comment]
Hi @sjDCC, yes, this Issue was for work related to the customisation updates.

Let me have a look at this this morning...

**Comment by Bodacious** [comment]
@sjDCC 

Was able to transfer customisations just now. 

<img width="1436" alt="screen shot 2018-09-18 at 15 14 37" src="https://user-images.githubusercontent.com/73998/45694018-44c2d180-bb56-11e8-8d04-d79c164e1b81.png">

I think we'll need more info to get to the bottom of this one.

**Comment by Bodacious** [comment]
@sjDCC Can you please provide more info on this issue? @xsrust and I have both tried to reproduce the error and haven't been able to.

I've added automated tests to check for the behaviour and those pass. It's not clear what the conditions are under which it doesn't work.

**Comment by sjDCC** [comment]
hi both. I've just tried this again and I'm not getting the error now but the customisations still aren't transferring. Here's what I did to replicate it.

Step 1: Edit an existing funder template and publish changes. Initially I added sections to test that the ordering still worked, but as a second test I just edited existing questions.

Step 2: Change affiliation to a university which has published the chosen funder template. i switched to Manchester as they have added a section to all funder templates. You should now see the status has changed to alert you to the new funder template.
![step2](https://user-images.githubusercontent.com/6169940/46546575-4f54c900-c8c1-11e8-8f79-c2bde5e5614e.PNG)

Step 3: Select to transfer the customisation. Each time I did this, it saved but no content was copied through. The Manchester section was not visible on the new funder template awaiting publishing. I'd originally wanted to check that the section ordering still worked and put theirs first regardless of changes to the number of funder sections, but no content is copying over irrespective of the type of changes made.

Happy to talk this though on phone if needed

**Comment by stephaniesimms** [comment]
I tested this following the steps @sjDCC listed above and the behavior remains the same. As an org admin I am able to transfer customizations and receive a message that they are successfully published. But when I try to create a plan with that template I don't see any of the customizations. Moving back to in progress...

**Comment by sjDCC** [comment]
I can't replicate this @stephaniesimms 

I just edited the Sloan template, transferred customisations from Berkeley and republished and they were there when I created a new plan.

@Bodacious I'd prioritise tickets in pending column and come to this last

**Comment by briri** [comment]
@stephaniesimms was the upgraded customization published when you tried it?

**Comment by stephaniesimms** [comment]
it was probably user error (my bad) owing to testing after brain capacity hours. everything re transfer customizations is working as expected now. closing issue.

**Comment by sjDCC** [comment]
Looking good to me too :)
