### ISSUE TITLE
New plan details API for reporting purposes

### ISSUE THREAD

**Issue by tomhigginsuom** [DMPRoadmap/roadmap#1854]
We are currently using the plan statistics API to get a daily summary of created DMPs (by requesting a date range from https://dmponline.dcc.ac.uk/api/v0/statistics/plans).

However, the plan details that are visible through the API are quite limited. From the documentation (https://github.com/DMPRoadmap/roadmap/wiki/API-Documentation) the fields are as follows:
* id
* grant_number
* title
* template
* funder
* principal_investigator
* data_contact
* description

This gives a useful summary but does not allow more sophisticated reporting. We would like to report on some of the custom fields that we have added to the funder plans.

For example, if we had a question which asked whether the research was related to sensitive data we could check this flag via the API and generate a notification email for follow-up with the researcher.

One solution would be to add a new API endpoint to retrieve a JSON representation of the complete plan data by plan ID.

The full plan information is already available to us via the organisational web dashboard but cannot be easily exported, searched or reported on.

**Comment by mariapraetzellis** [comment]
We have this available now via the full-text API.
