### ISSUE TITLE
Themes: implement new themes in Roadmap

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#186]
@sjDCC is it part of DCC MVP to implement the new themes? Flagging this now as Roadmap MVP.

**Comment by sjDCC** [comment]
No, I thought we should implement the themes as the full joint release when you also migrate over. We'll need to do a fair bit of work to enable existing themed guidance to be migrated through and I don't want that to delay work now. I figured we could allocate time to this while you're busy with your migration. 

I expect we need some way for institutional admins to see their existing guidance that pertains to themes that have been deleted or merged, and be given some suggestions as to how to rework this e.g. add documentation guidance in with metadata. We can't do things automatically (it'll need some manual input from admins) but I'd like to be able to present them with some form of summary so it's clear what will no longer be visible so they can decide how to act

**Comment by stephaniesimms** [comment]
thanks for clarification and outlining a game plan @sjDCC - I'm also conscious of the fact that I'll have to do some manual curation for templates, guidance, etc when we migrate. so we can do it all together - I'll include it in our migration plan.

**Comment by vyruss** [comment]
## Theme changes
### Mapping table
old theme                      | new theme                     | Explanation of change
---|---|---
ID                             | none                          | theme deleted
Project description            | none                          | theme deleted
Data type                      | none                          | theme deleted - concept rolled into Data description
Existing data                  | none                          | theme deleted - concept rolled into Data description
Relationship to existing data  | none                          | theme deleted - concept rolled into Data description
Data quality                   | none                          | theme deleted - concept rolled into Data collection|
Documentation                  | none                          | theme deleted - concept rolled into Metadata & Documentation
Discovery by users             | none                          | theme deleted - concept rolled into Metadata & Documentation
Data security                  | none                          | theme deleted - concept rolled into Storage & security
Data selection                 | none                          | theme deleted - concept rolled into Preservation
Period of preservation         | none                          | theme deleted - concept rolled into Preservation
Expected reuse                 | none                          | theme deleted - concept rolled into Data sharing
Timeframe for data sharing     | none                          | theme deleted - concept rolled into Data sharing
Restrictions on data sharing   | none                          | theme deleted - concept rolled into Data sharing
Managed access procedures      | none                          | theme deleted - concept rolled into Data sharing
Related policies               | Related policies              | theme retained - associated guidance shortened
Data description               | Data description              | theme retained - associated guidance shortened
Data format                    | Data format                   | theme retained - associated guidance shortened
Data volumes                   | Data volume                   | theme retained - name changed & associated guidance shortened
Data capture methods           | Data collection               | theme retained - name changed & associated guidance shortened
Metadata                       | Metadata & documentation      | theme retained - name changed & associated guidance shortened
Ethical issues                 | Ethics & privacy              | theme retained - name changed & associated guidance shortened
IPR ownership and licensing    | Intellectual Property Rights  | theme retained - name changed & associated guidance shortened
Storage and backup             | Storage & security            | theme retained - name changed & associated guidance shortened
Preservation plan              | Preservation                  | theme retained - name changed & associated guidance shortened
Data repository                | Data repository               | theme retained - associated guidance shortened|
Method for data sharing        | Data sharing                  | theme retained - name changed & associated guidance shortened
Responsibilities               | Roles & responsibilities      | theme retained - name changed & associated guidance shortened
Resourcing                     | Budget                        | theme retained - name changed & associated guidance shortened

### Notes on merging:
29 themes have become 14. Most of this has been done by merging concepts as noted below. 2 themes have been deleted completely (ID and project description) and 13 have been deleted via merging into broader concepts as noted below. 14 themes have been retained, sometimes with name changes to encompass broader concepts.

New theme                       | Old theme names encompassed in this revised version
---|---
Data description                | Data description, Existing data, Relationship to existing data and Data type (4 to 1)
Data collection                 | Data capture methods and Data quality (2 to 1)
Metadata & documentation        | Metadata, Documentation, and Discovery by users (3 to 1)
Storage & security              | Storage and backup, and Data security (2 to 1)
Preservation                    | Preservation plan, Data selection, and Period of preservation (3 to 1)
Data sharing                    | Method for data sharing, Expected reuse, Timeframe for data sharing, Restrictions on data sharing, and Managed access procedures (5 to 1)

8 additional themes were retained without merging other concepts into them. Their names sometimes changed. These are:
- Related polcies
- Data format
- Data volume
- Ethics & privacy
- Intellectual Property Rights
- Data repository
- Roles & responsibilities
- Budget

**Comment by stephaniesimms** [comment]
@vyruss will add script to documentation
