### ISSUE TITLE
Unable to create new Orgs

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1860]
Please complete the following fields as applicable:

**Expected behaviour:**
Super Admin is able to create a new Org

**Actual behaviour:**
User is unable to create an Org because they cannot provide all the necessary info via the form. The Language field is required by the model but there is no language selector on the form.

**Steps to reproduce:**
- Login as a super admin
- Go to Admin -> Organisations
- Click 'New Organisation'
- Fill in required fields
- Submit the form

<img width="1193" alt="screen shot 2018-09-05 at 11 44 41 am" src="https://user-images.githubusercontent.com/1204467/45114288-745aee00-b101-11e8-8a46-122deee54e59.png">

We can either default the value to the installation's default language pref or add a selector. This value currently has no bearing on the rest of the system. I think the original intention may have been for it to determine new user's default language pref.

**Comment by stephaniesimms** [comment]
i can successfully create a new org now. except i noticed that there are now red asterisks next to the URL and Link Text fields suggesting that they are mandatory but they shouldn't be (see screenshot). I was able to create the Org without entering info into these fields. so it doesn't seem that they're being validated but they do need the red asterisks to be removed @briri . after that small detail is fixed all should be okay.

![screen shot 2018-09-27 at 9 39 56 pm](https://user-images.githubusercontent.com/12703638/46188493-51ee6780-c29e-11e8-94bc-5d05dad55c56.png)

**Comment by sjDCC** [comment]
Works fine and asterisks are all in right place. Closing out.
