### ISSUE TITLE
Sort by columns wrong color and display field name

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1861]
Please complete the following fields as applicable:

**Expected behaviour:**
'Sort by' is indicated by white ascending/descending arrows

**Actual behaviour:**
'Sort by' is indicated by blue text (e.g. 'Sort by updated_at'). 

**Steps to reproduce:**
- Login
- Look at My Dashboard table(s)

**Comment by stephaniesimms** [comment]
I experienced the same behavior as @dsisu - the arrows and color are restored. but functionality is not quite right: we are only able to sort each column once and only ascending order

desired behavior is to be able to sort any column an unlimited number of times either ascending or descending, toggling back and forth.

**Comment by sjDCC** [comment]
This seems fine for me on My Dashboard and most pages. I had issues with the users table though as a super-admin. Not of these arrows would sort / change data. Perhaps there's too much in the table?

The original ticket seems sorted so closing out. @stephaniesimms if you also have issues on the users table should we raise a new ticket?
