### ISSUE TITLE
Refactor CSS assets for easier management

### ISSUE THREAD

**Issue by Bodacious** [DMPRoadmap/roadmap#1862]
The CSS assets are not organised very neatly. We need to refactor these to make it easier to support custom branding.

- [x] Move CSS assets back to Rails's asset pipeline
- [x] Add support for LibC Sass (faster compilation)
- [x] Refactor CSS file structure for maintainability
- [ ] Normalise CSS variables

**Comment by sjDCC** [comment]
haven't noticed any issues in display with branding so assume this is ok. this is just based on general visual checks as I have done overall UAT. @xsrust @briri Can you advise if there are specific things I should test?

**Comment by briri** [comment]
Anything that includes Javascript (e.g. questions load when you expand a section, etc.) and the site's look and feel (CSS).

**Comment by sjDCC** [comment]
All looks good to me. Table sort and search works well and all accordians open. Only issue I spotted is that links open in same window. We used to have it force a new window to be opened. Will raise a ticket for that and close this one out
