### ISSUE TITLE
Templates: edit, preview   

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#187]
1. clicking Edit or View takes me to Template details (screenshot below) where nothing on page works. Most buttons and Generic DMP tab throw "We're sorry" error message. "Edit template details" button takes me to a page (second screenshot) where I still cannot edit anything

![template-errors](https://cloud.githubusercontent.com/assets/12703638/24120715/cdfc9a46-0d72-11e7-9c72-08ce3312592c.png)
![template-loop-errors](https://cloud.githubusercontent.com/assets/12703638/24120723/d23c5178-0d72-11e7-8974-caaa5eaba411.png)

**Comment by briri** [comment]
The following error appears in the log when you click on the 'Generic DMP' phase in the example above:
```shell
App 660 stdout: NoMethodError (undefined method `template' for #<Phase::ActiveRecord_Relation:0x0055d27ce737f0>):
App 660 stdout:   app/policies/phase_policy.rb:17:in `admin_show?'
App 660 stdout:   app/controllers/phases_controller.rb:103:in `admin_show'
```

**Comment by briri** [comment]
related to the following tickets:
- #191 
- #192 
- #193 
- #194

**Comment by stephaniesimms** [comment]
tested and appears to be fixed
