### ISSUE TITLE
Update Comment notification text

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#1872]
Please complete the following fields as applicable:

**Expected behaviour:**
A user should be able to follow a link to the question which has been commented on from the notification email. 

**Actual behaviour:**
There is no link, even to the plan, nor mention of the question/section/phase of the comment in the email.  

**Desired Action**
Minimum write the question number, section number/title, and phase(if applicable)
Minimum link to the edit plan page (preferably correct phase)
Ideally link to the question with the added comment

**Comment by johnpinto1** [comment]
Email examples:
Plan has several phases
![comment-email-01](https://user-images.githubusercontent.com/8876215/51385827-40b0bb80-1b18-11e9-80b7-6eacf44acf3c.png)
Plan ha a single phase
![comment-email-02](https://user-images.githubusercontent.com/8876215/51385861-5aea9980-1b18-11e9-822d-c0de83ac6fdb.png)

**Comment by johnpinto1** [comment]
I think the wording will need to be changed.

**Comment by sjDCC** [comment]
@sjDCC to check wording

**Comment by sjDCC** [comment]
Hi @johnpinto1 

I think it's really unlikely that anyone would comment on two phases at the one time. Also, most templates only have one phase and users are unfamiliar with the concept of phases (even admins!) so I think we should avoid this terminology in the interface. 

I suggest the following for the email:

Hello [name OR email if no name]

[reviewer name] has commented on your plan [plan name]. To view the comments, follow the link to the DMP below, or navigate to the plan via My Dashboard page in [tool name].

Below is a summary of the sections and questions which have comments. You can see the comments in the right-hand panel, adjacent to the guidance for each question.

DMP: [insert link to DMP phase] - if comments provided on more than one phase, replicate this whole entry
<repeatable element if there is one or more reviewer comments>
Section name:
Question number:
</end repeat>

All the best
[insert usual sign off]

I don't think we need to tell them the number of comments as it will usually be 1

@dsisu @magdalenadrafiova would be good to get your opinions on the wording of this too. Does the approach make sense?

**Comment by johnpinto1** [comment]
This is now in the development branch. @xsrust & @briri Not sure if it is in UAT

**Comment by dsisu** [comment]
Got notification with link to the plan and an indication of which question was commented upon.

![image](https://user-images.githubusercontent.com/2138956/55476346-3ded3f00-560e-11e9-8bca-b7be65470d8c.png)

**Comment by dsisu** [comment]
Link takes you to the 'write plan' tab.

**Comment by dsisu** [comment]
By the way: this plan belonged to my diana.sisu@ed.ac.uk user ID. When I first clicked on the link, I was logged in with my @yahoo ID. Link took me to my dashboard. Just in case you hear someone mentioning this behaviour.
