### ISSUE TITLE
Guidance links don't wrap in Chrome

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1876]
A dmptool user reported that the guidance links don't display/wrap correctly in the right-hand panel when writing a plan. This only appears to be happening in Chrome (screenshot 1). Screenshot 2 is correct display in Firefox. 

![screen shot 2018-09-13 at 10 59 47 am](https://user-images.githubusercontent.com/12703638/45506627-ae04a800-b744-11e8-82d8-9eaf41010cef.png)

![screen shot 2018-09-13 at 11 05 41 am](https://user-images.githubusercontent.com/12703638/45506747-06d44080-b745-11e8-9c36-c44adf142e42.png)

**Comment by johnpinto1** [comment]
Tester will need to test long links in Comments and Answer sections of Plans, including shared read-only Plans.

**Comment by johnpinto1** [comment]
@xsrust and @briri The code for this is in commit 93f4432208ea63022bc4d5fc1ed7b7654f3d09f8 which is in the development branch I got added  with Issue #1749. So I have moved it to UAT.

**Comment by sjDCC** [comment]
All looks good. Closing out
