### ISSUE TITLE
Autosave not working on write plan page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1878]
Expected behavior is the following: previously the system would autosave anything I input into a text editor (for questions only, not comments) on the write plan page as soon as I moved focus away from the editor. This action was accompanied by the timestamp appearing below the editor (screenshot 1). 

Now I can enter text and click around, opening and closing accordions, etc without autosave being triggered and no timestamps (screenshot 2). If I navigate to a different tab and return to 'Write plan' my answers are lost. I have to click the 'Save' button in order to save my answers now. This is happening for all existing and new plans. Desired behavior is to reinstate autosave for questions.

![screen shot 2018-09-16 at 2 59 01 pm](https://user-images.githubusercontent.com/12703638/45601410-34c5b900-b9c1-11e8-8492-a79653ca12bc.png)

![screen shot 2018-09-16 at 2 53 50 pm](https://user-images.githubusercontent.com/12703638/45601413-38594000-b9c1-11e8-93a9-dfed44e74319.png)

**Comment by sjDCC** [comment]
I can still open and close accordions without answers being saved. They stay in the text box unsaved (I think due to browser caching) but if I navigate to another tab and force page reload (i.e. from write plan > project details) any unsaved answers are lost.

**Comment by sjDCC** [comment]
Working well thanks @briri Closing out

**Comment by nicolasfranck** [comment]
I noticed that the autosave is not working if you leave the page, for example by clicking on a tab link.
In the past (dmponline_v4) a user was warned for this with a dialog, but now with autosave, shouldn't we autosave
all the rest too?

**Comment by briri** [comment]
The current implementation of autosave is problematic. That is the only screen that has an autosave and it uses some complex JS logic using the blur/focus events. The 'Save' buttons below the answer are also confusing and we've had users be surprised that it autosaved their change.

The development temas have had discussions in the past about switching the entire site over to autosave but have not had the bandwidth to tackle such a large project. Now that we're on Rails 5+ it would be good to use Rails' UJS functionality along with some js.erb templating.

**Comment by nicolasfranck** [comment]
wouldn't it be better to alert the user that there are unsaved changes (like before in dmponline_v4),
instead of saving (unwanted?) without asking?
