### ISSUE TITLE
Unable to upload Org logo

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1879]
On the org details page, any logo files I try to upload and click 'Save' produce the error below:

![screen shot 2018-09-16 at 3 54 20 pm](https://user-images.githubusercontent.com/12703638/45601891-19f74280-b9c9-11e8-9dd7-6ac3b55f3f73.png)

**Comment by xsrust** [comment]
we didnt have one of the dependancies, ImageMagic, installed on the server with DMPOnline-dev on it. 
The issue should be resolved now

**Comment by stephaniesimms** [comment]
this is working now. closing issue.
