### ISSUE TITLE
Improve formatting of plan downloads

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#1893]
Please complete the following fields as applicable:

**Expected behaviour:**
Question text and question-related content should be distinctive in some way from the answer. Formatted in bold as per user interface, perhaps?

**Actual behaviour:**

In the online user interface, question text and any explanatory notes appear in bold. They are not downloaded in bold.

For example, see question on Data Summary in the Horizon2020 template. The 'State the purpose of the data collection/generation' is bold on screen but not in the downloaded plan. This makes it indistinguishable from the content of the answer. See screenshots below.

![image](https://user-images.githubusercontent.com/2138956/46010135-8654fe80-c0b9-11e8-876f-3b97e4d5fff6.png)

and

![image](https://user-images.githubusercontent.com/2138956/46010266-ef3c7680-c0b9-11e8-80e9-50605b9a5851.png)

**Steps to reproduce:**

Download a completed plan.

**Comment by sjDCC** [comment]
Formatting looks great on PDF and HTML - much clearer to have larger bold heading, bold questions and plain text answer. I get an error with docx though. See below. Should this be raised as a new ticket?
![docx1](https://user-images.githubusercontent.com/6169940/51899555-2e9e0b00-23ab-11e9-8016-60d2d062a7c9.PNG)
![docx2](https://user-images.githubusercontent.com/6169940/51899556-2e9e0b00-23ab-11e9-9bd9-6789bf7f4476.PNG)

**Comment by johnpinto1** [comment]
@sjDCC @xsrust and @briri I get the same issue on the DMPOnlineTest when i download the Word Document and try to read it in Microsoft Word online. LibreOffice opens the document without complains. Will debug to identify cause.

**Comment by johnpinto1** [comment]
@briri and @xsrust The docx error is still occuring when trying to open the it in Microsoft Word.

**Comment by johnpinto1** [comment]
@sjDCC The **docx** export should open in Word without the errors mentioned above.
![selection_115](https://user-images.githubusercontent.com/8876215/52405701-d14d3c80-2ac3-11e9-8c46-5247974f1b79.png)

**Comment by sjDCC** [comment]
Docx downloads fine now and the formatting makes it clear what is a question. Thanks @johnpinto1
