### ISSUE TITLE
permissions error

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1908]
I've just received the following error when trying to assign org-admin permissions to a secondary account I created. I'm a super-admin on the tool so should be able to grant permissions to any user.
![permissions-error](https://user-images.githubusercontent.com/6169940/46547927-6f868700-c8c5-11e8-9d11-677a10a05670.PNG)

When I go to assign permissions to most users in the list it works and I get the correct display box (below). However when I search for the account, all three of the search results generate the error above. Perhaps this issue is linked to the search somehow rather than the account being new or different org affiliation etc

![permissions](https://user-images.githubusercontent.com/6169940/46548047-d310b480-c8c5-11e8-9c8d-1b79825aa670.PNG)
![org-admin](https://user-images.githubusercontent.com/6169940/46548046-d310b480-c8c5-11e8-9efa-5889d4ebaaf7.PNG)

**Comment by sjDCC** [comment]
Update: after checking again, this is happening on roadmap-stage but not dmponline-dev. I'm not sure if that is due to development code @Bodacious pushed recently or if we had something different in data migration files. Noticed all our questions are showing as 1 not 0 in numbering so that may be it. May want to confer to troubleshoot @briri

**Comment by briri** [comment]
Ah yes. It appears to be a data cleanup issue. All of the sections are set to zero in the database. 

If its working on dmnponline I would say go ahead and close it out. I will be rerunning the data cleanup scripts tomorrow and will double check to make sure this is resolved once I've run through that again.

**Comment by stephaniesimms** [comment]
let's leave this open until we verify that it is, in fact, a data cleanup issue. we can confirm tomorrow that it's fixed on roadmap-stage.

**Comment by briri** [comment]
just realized I commented on the wrong ticket 🙃 This comment about the section numbers was meant for #1909

**Comment by briri** [comment]
for whoever works on this, it looks like the JS behind this link isn't getting wired up after any of the pagination/sort or search calls fire.

We should either delegate the JS event to an element higher up in the Dom tree or see if there's a more Rails-y way of handling it.

**Comment by stephaniesimms** [comment]
permissions are all working as expected now. closing.
