### ISSUE TITLE
Validation error on question / section numbering

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1909]
When I was testing the transfer of customisations, I hit a couple of save errors.

It seems that existing sections and questions are being saved as '0' which throws a validation error. Is there a way to ensure they save as '1' as the '0' was reserved to let unis put their section at the start of funder templates.

![error-saving](https://user-images.githubusercontent.com/6169940/46601212-57d91980-cae4-11e8-891f-7978c5b99e2b.PNG)

![customise-question](https://user-images.githubusercontent.com/6169940/46601208-57408300-cae4-11e8-9098-7f9c87727985.PNG)
![defaulting-0](https://user-images.githubusercontent.com/6169940/46601209-57408300-cae4-11e8-9ea6-a223e41a3475.PNG)
![edit-question](https://user-images.githubusercontent.com/6169940/46601210-57d91980-cae4-11e8-8f74-e87b53fbb8b9.png)

**Comment by briri** [comment]
Ah yes. It appears to be a data cleanup issue. All of the sections are set to zero in the database.

If its working on dmnponline I would say go ahead and close it out. I will be rerunning the data cleanup scripts tomorrow and will double check to make sure this is resolved once I've run through that again.

**Comment by Bodacious** [comment]
Just saw your comment now @briri. Will move this back to Pending for now
