### ISSUE TITLE
Possible redundant app/views/users/admin_grant_permissions.html.erb?

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#1914]
It seems like [app/views/users/admin_grant_permissions.html.erb](https://github.com/DMPRoadmap/roadmap/blob/master/app/views/users/admin_grant_permissions.html.erb) is not used by the system, can someone confirm this and deletes it? Or can someone explains how it is used by the system?

**Comment by magdalenadrafiova** [comment]
@xsrust @briri the link does not work and I am not sure whether this is still relevant?

**Comment by briri** [comment]
this form is used by the modal dialog that allows you to change a user's permissions.
