### ISSUE TITLE
All hyperlinks should open in a new tab

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1916]
While testing autosave (related issue #1878 ) on the write plan page I experienced some weird behavior related to hyperlinks. When I click a Guidance link (screenshot 1) it opens in the same tab. Then if I try to navigate back to the write plan page the browser seems to think I'm in a new session and doesn't display any of my previously answered and autosaved questions (screenshot 2). I have to reload the entire plan to recover my answered questions.

The desired behavior is to open links in a new tab anyway. Reinstating this behavior should avoid the problem.

<img width="935" alt="screen shot 2018-10-09 at 12 15 09 pm" src="https://user-images.githubusercontent.com/12703638/46692807-09e41480-cbbd-11e8-8d87-15212504cbf2.png">

<img width="950" alt="screen shot 2018-10-09 at 12 11 55 pm" src="https://user-images.githubusercontent.com/12703638/46692867-2da75a80-cbbd-11e8-8ca2-77426b317609.png">

**Comment by stephaniesimms** [comment]
working as expected now. closing issue.

**Comment by sjDCC** [comment]
Looks good. Thanks @briri
