### ISSUE TITLE
Clicking 'Edit details' on template results in blank details section

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#192]
When you click on 'Template details' from the edit template page you end up with a blank details section and no option other than going back to 'view all templates'.

![screen shot 2017-03-21 at 2 37 04 pm](https://cloud.githubusercontent.com/assets/1204467/24172041/0736f67c-0e44-11e7-8284-4017fc9b3430.png)

This happens as well when editing a customization.

**Comment by briri** [comment]
Clicking the 'Edit details' button resulted in NO JS console errors and no traffic within the log so its not making a hit on the server. So probably something wrong with the JS. There are no assets that appear to have had trouble loading (all HTTP 200 or 304)

**Comment by briri** [comment]
The issue was related to only allowing funder orgs to edit templates. Updated the if statement controlling whether or not the edit details section was visible so that org_admins can maintain their own org's templates.

Also updated the controller so that it stays on the same page after editing details. It was sending the user to the 'view all templates' page after saving

**Comment by stephaniesimms** [comment]
tested and working as expected.
