### ISSUE TITLE
Share plan emails

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1931]
We've had a helpdesk enquiry asking if users can be directed to the create account page more obviously when a plan is shared and they don't already have an account. I thought we made it explicit that they needed to create an account, but it doesn't seem so from the email and I'm struggling to test the workflow. I have accounts for all my emails already on DMPonline and the token on roadmap stage is misdirecting.

@stephaniesimms Could you test how this works to ensure users get directed to create an account to view the plan and correct my suggestions below accordingly.

![email-to-unknown-user](https://user-images.githubusercontent.com/6169940/46915014-974cad80-cf9d-11e8-8be2-92f9beba402d.PNG)

I think 3 actions are needed:

1. Update the emails to make it clear who has shared the plan. We did this in #1587 but the change seems to have been lost. Or maybe it was only done in the email generated by the devise gem?

2. Amend the email text to make it clear an account needs to be created, when the plan is shared with a user who doesn't already have an account

3. Ensure the link in the latter plan goes to a create account page, not the general home page / sign in

**Suggested email text:**

SHARED PLAN [devise]

Email title: A Data Management Plan in [TOOL NAME] has been shared with you

Hello [USER NAME]

Your colleague [NAME] has invited you to contribute to their Data Management Plan in [TOOL NAME]

Click here [here: hyperlink] to accept the invitation, (or copy http://roadmap-stg.cdlib.org/users?invitation=ABCDEG into your browser). If you don't want to accept the invitation, please ignore this email.

All the best
The [TOOL NAME] team

Please do not reply to this email. If you have any questions or need help, please contact us at [HELPDESK EMAIL] or visit [CONTACT US URL].

SHARED PLAN, USER MUST CREATE ACCOUNT FIRST

Email title: A Data Management Plan in [TOOL NAME] has been shared with you

Hello someone@tester.org

Your colleague [NAME] has invited you to contribute to their Data Management Plan in [TOOL NAME]

As you don't yet have an account in [TOOL NAME] click here [here: hyperlink] to create one and accept the invitation, (or copy http://roadmap-stg.cdlib.org/users?invitation=ABCDEG into your browser). If you don't want to accept the invitation, please ignore this email. 

All the best
The [TOOL NAME] team

Please do not reply to this email. If you have any questions or need help, please contact us at [HELPDESK EMAIL] or visit [CONTACT US URL].

**Comment by johnpinto1** [comment]
@sjDCC One issue i noticed with the email line when the inviter name is not a person e.g., "Data Library" here

> Your colleague **Data Library** has invited you to contribute to  their Data Management Plan in DMPRoadmap

The code for PR will show the above.

**Comment by sjDCC** [comment]
Thanks for this @johnpinto1 I'm ok with the text displaying a non-person name as hopefully whatever name the user has entered will be workable. We did at one point replace names with FIRST NAME SURNAME though to prompt people to populate details and ensure blank entries weren't throwing validation issues. @xsrust, would these pull through to share plan emails? If so, that doesn't look as good.

I've tried sharing plans to a few accounts but haven't received any emails. Will test again tomorrow to see if this was a server issue or quirk

**Comment by sjDCC** [comment]
Tested this on roadmap stage and the email came out fine so guess we have a config issue on DMPonline-test. Text in share plan email looks good but noticed both links to plan (click here and full URL text) both throw an error. Is this config issue too or a bug? Can open as new ticket if needed

![error](https://user-images.githubusercontent.com/6169940/49465624-f8526e00-f7f5-11e8-80cd-04d266fd9b26.PNG)

**Comment by stephaniesimms** [comment]
i created an issue for @briri to update the server URL #2002- that should fix the outstanding problems noted in screenshot above

**Comment by Ebrahim1010** [comment]
Where is the email for sharing a plan being generated from - The file location? 
I'm trying to update the details of the email being sent.

**Comment by johnpinto1** [comment]
@Ebrahim1010 All the templated for email are in  `app/views/devise/mailer`.
You need to change `app/views/devise/mailer/invitation_instructions.html.erb`.

**Comment by Ebrahim1010** [comment]
Thanks @johnpinto1 
Do you know where these variables are set?
<%= sanitize(_('%{click_here} to accept the invitation, (or copy %{link} into your browser). If you don\'t want to accept the invitation, please ignore this email.') % {
      click_here: link_to(_('Click here'), link), link: link

**Comment by johnpinto1** [comment]
@Ebrahim1010 

Devise does the magic https://github.com/plataformatec/devise

The following files just extend or use the Devise classes:
`config/routes.rb` (see Devise config at start)
`app/mailers/user_mailer.rb `
`app/controllers/users/invitations_controller.rb`

> `rake routes | grep accept`
   `accept_user_invitation GET      /users/invitation/accept(.:format)  `

So link set in `app/views/devise/mailer/invitation_instructions.html.erb`:
`link = accept_invitation_url(@resource, :invitation_token => @token)`
