### ISSUE TITLE
OrgIdentifier model has an unnecessary validation

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1934]
Discovered issue with OrgIdentifier validation when going through the output of the data_cleanup:find_known_invalidations task. The OrgIdentifier was checking for the unstopped uniqueness of the 'identifier' field. DMPTool has a scenario though where 2 institutions point to the same Shib IdP.

Remove the validation since its not necessary. The uniqueness check for org_id + identifier_scheme_id will prevent multiple entries.

**Comment by stephaniesimms** [comment]
can't test in UI. closing issue.
