### ISSUE TITLE
Guidance default configurations lost

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1935]
This may just be a configuration issue, but when I create a new plan the guidance behavior is incorrect. 
- I should see the "DMPTool"/UCOP guidance group checked by default and my organizational affiliation guidance also checked. Currently I only get my org guidance if there is any by default (screenshot 1 - )
- I should not see "Non partner institution" in the full list of guidance (screenshot 2)

<img width="311" alt="screen shot 2018-10-15 at 3 24 02 pm" src="https://user-images.githubusercontent.com/12703638/46981727-744df680-d08e-11e8-89cd-c0416925816b.png">

<img width="351" alt="screen shot 2018-10-15 at 3 00 14 pm" src="https://user-images.githubusercontent.com/12703638/46980944-11a72b80-d08b-11e8-9dff-fe4d3e93f286.png">

**Comment by stephaniesimms** [comment]
great thanks @briri - we can address the DMPTool label issue independently. UCOP guidance group is back as a default checked guidance option. but "Non Partner Institution" should never appear in the list. this may be another thing we address for DMPTool data independently...? closing issue.

**Comment by briri** [comment]
Ah. the non-partner fix is in review
