### ISSUE TITLE
Standardize/configure date format for CSV files for plans, users

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1936]
I should see the same formatting for dates in all downloaded CSV files. Current date format is configured correctly for US plans data (screenshot 1 - MM/DD/YY). It should be the same for US users data (screenshot 2). And DD/MM/YY for UK plans and users data.

if you prefer a different format @sjDCC i'm fine with anything as long as it's standardized for all CSVs.

US plans CSV file
<img width="632" alt="screen shot 2018-10-15 at 3 48 04 pm" src="https://user-images.githubusercontent.com/12703638/46982787-9ba6c280-d092-11e8-9f63-2e62800d7349.png">

US users CSV file (incorrect date formatting)
<img width="504" alt="screen shot 2018-10-15 at 3 47 46 pm" src="https://user-images.githubusercontent.com/12703638/46982811-b6793700-d092-11e8-9dbd-915732007f0f.png">

**Comment by sjDCC** [comment]
I would prefer them to be DD/MM/YY. Just checked on DMPonline and that's what we use in My Dashboard
![my-dashboard](https://user-images.githubusercontent.com/6169940/46998122-89bc3280-d119-11e8-8ab2-7fc63fc01c13.PNG)

Given that a different mode is prevalent in each of our contexts, should we write out months with an abbreviated form instead (e.g. 23 Oct 2018) or make this a variable to configure per instance (if not too difficult / lots of work)?

Agree that it should be consistent across all tables and downloads

**Comment by stephaniesimms** [comment]
date field config looking good. closing issue.
