### ISSUE TITLE
Usage statistics page needs minor layout changes 

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1937]
The placement of the 'Download all usage' button is confusing since this produces global usage (total users, total plans) for all orgs. It needs to be separated from the rest of the usage stats on the page which are all Org stats. 

We could go ahead and implement a dropdown for all downloadable files on this page as described in issue #1690 . Then we just need to label each file appropriately so users understand what info each contains. The alternative is to remove this button for now and not provide global usage info until the rest of the usage dashboard is redesigned. What are your thoughts @sjDCC ?

The "Go" button next to the adjustable filters needs to be realigned.

<img width="1013" alt="screen shot 2018-10-15 at 3 39 04 pm" src="https://user-images.githubusercontent.com/12703638/46983018-82524600-d093-11e8-9a53-27f3848b1504.png">

**Comment by sjDCC** [comment]
I think if we moved the button to top right hand corner and renamed it to 'Download global usage' that would work. Perhaps we could add hover-over help or a small piece of help text underneath to clarify that this is total usage and total plans for all orgs. 

It makes sense sitting alongside the two icons (total users and total plans) as it's contextualising these figures in terms of overall tool usage.

**Comment by xsrust** [comment]
Updated text/location of 'Download Global Usage button, updated spacing of 'Go' Button
<img width="1154" alt="screen shot 2018-10-16 at 15 07 21" src="https://user-images.githubusercontent.com/7352616/47022502-8d6daa80-d155-11e8-8b10-c5010f986303.png">

**Comment by sjDCC** [comment]
Thanks for the screengrab @xsrust Before this is reviewed / merged, can you change the text so it's "Download global usage" i.e. small letter for global and usage. That keeps it consistent with all other buttons. Ta :)

**Comment by stephaniesimms** [comment]
layout changes looking good. closing issue.

**Comment by sjDCC** [comment]
Looks great, thanks @xsrust
