### ISSUE TITLE
Section ordering error when editing funder templates

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1939]
While testing related issue #1909 I noticed the following strange behavior for funder template editing:
- the drag and drop functionality for all sections is nice to have when editing funder templates but as a super admin I should be able to place any section in any position freely. I received an error (screenshot 1) when I attempted to move any lower section into the first position. If I understand correctly, the first section for any funder template should be Order 1 in the database but I should still be able to edit the template by dragging a different section to position 1.

![screen shot 2018-10-15 at 9 28 34 pm](https://user-images.githubusercontent.com/12703638/46993113-75991680-d0c2-11e8-879f-eb4461fb6683.png)

**Comment by stephaniesimms** [comment]
section ordering for funder templates is working as expected now. closing issue.

**Comment by sjDCC** [comment]
Editing fine as a funder - great!
