### ISSUE TITLE
Phase numbering error when I try to add a phase description to funder template

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#1941]
As a super admin editing a funder template I receive the error below on the first attempt only to add a phase description. On all subsequent attempts I am able to add a description and save it successfully. This appears to be a phase numbering and/or versioning bug of some kind. It's an edge case but not desired/correct behavior.

![screen shot 2018-10-15 at 9 47 16 pm](https://user-images.githubusercontent.com/12703638/46993715-92831900-d0c5-11e8-9a32-1737f8600184.png)

**Comment by xsrust** [comment]
@briri, this one looks a bit wierd.  you might be able to better investigate the interaction wiht your data as I cant get this to occur within our data
The validation on this just states that per template_id (individual to each version of each template), the number on phases has to be unique.  I cant see how it would trigger with just one phase.

**Comment by xsrust** [comment]
I figured this one out.
We're updating the phase with params passed in from the page and not filtering out the template_id.
While the new version gets generated, our validation prevents us updating the published version with that first edit. (which is what the code was previously doing)

**Comment by stephaniesimms** [comment]
yes you did @xsrust ! it is working as expected now. closing issue.
