### ISSUE TITLE
Able to drag 2 custom sections to top of funder template

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#1942]
Currently I'm able to drag two custom sections to the top of a funder template, if I drag the second to second position. If it put it first the error message is raised as expected.

Previously the tool prevented two from sitting at the top. If you tried to drag a second there it was returned to its original location. In the screengrab below you can see the two sections. If I go to preview I see the two, but when I return, only 1 is visible on the editable interface. The other disappears.

![able-to-drag-2](https://user-images.githubusercontent.com/6169940/46998679-2af7b880-d11b-11e8-8d63-5df599174d75.PNG)

Thoughts @Bodacious?

**Comment by briri** [comment]
Hey @sjDCC, no the 'Other' org shouldn't be allowed to customize templates. With that said though I don't think any of those admin menu functions are available to users who belong to the 'other' org. This is likely just an unusual scenario for you testing as a Super Admin who has switched to the 'other' org. 

With that said though, it wouldn't hurt to add a check to prevent the templates pages from loading for users belonging to the 'other' org. Maybe just a redirect back to the dashboard with a 'You are not authorized' message.

**Comment by sjDCC** [comment]
Hi @briri. I created myself an org admin account as 'other / non-partner institution' and although the permission assign correctly, the logic is preventing the menu from displaying. I suspect you're right that this is a quirk of me being a super-admin so probably nothing needed to fix this

**Comment by stephaniesimms** [comment]
drag and drop for customized sections is working as expected now. will consult w/ @briri about whether we should add a check to prevent users w/ "Other" affiliation from editing even though it sounds like this could be a super admin edge case... closing this issue

**Comment by sjDCC** [comment]
Working nicely again like before. Thanks @Bodacious
