### ISSUE TITLE
Languages with standard ISO abbreviations not working

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1949]
Update the records in the DB to use the ISO format (e.g. pt-BR instead of pt_BR). Then start the server and try to change the locale via the UI menu. There is no error but the language does not change. 

Update the DB record to the underscore version of the abbreviation and restart the application. Then try switching the language again. It works in this scenario.

We likely just missed a spot in the applicationController for using the new functions that swap between the I18n and FastGettext versions.

**Comment by stephaniesimms** [comment]
languages appear to be working as expected. will keep a lookout when testing on dmptool stage too @briri . closing issue.

**Comment by sjDCC** [comment]
Translations work well
