### ISSUE TITLE
Plan#show fails on customized template

### ISSUE THREAD

**Issue by raycarrick-ed** [DMPRoadmap/roadmap#195]
customization_of is being treated as a relationship when it isn't so

customization_of.org fails in _plan_details.html.erb

**Comment by raycarrick-ed** [comment]
fixed by https://github.com/DigitalCurationCentre/roadmap/commit/e73a0fa47db69b243731c2d6a94ace918c58e836

**Comment by sjDCC** [comment]
Not sure if there's anything @stephaniesimms or I can test on this one so good to close?

**Comment by stephaniesimms** [comment]
Not sure how to test either so closing
