### ISSUE TITLE
Editing issues under super admin

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#196]
It doesn't seem to be possible to edit anything under super admin. Attempting to adjust the language tags e.g. fr > French and editing my own profile to change to Helsinki uni both threw up errors.

Related to active admin change #132?
![active-admin](https://cloud.githubusercontent.com/assets/6169940/24196882/51663dee-0ef7-11e7-9702-4594340e80c5.PNG)
![edit-user](https://cloud.githubusercontent.com/assets/6169940/24196888/5947104c-0ef7-11e7-8a2d-9c65f23f1cb6.PNG)

**Comment by vyruss** [comment]
Upstream bug found thoughtbot/administrate/issues/417
possible fix thoughtbot/administrate/pull/465

**Comment by stephaniesimms** [comment]
I can edit things under all the menu items. Most of it doesn't make much sense to me however...so I'll leave it to @sjDCC to confirm that this meets short-term super admin needs.

**Comment by vyruss** [comment]
Closing this one as bug was fixed upstream.
