### ISSUE TITLE
statistics not working(Plans or Users)

### ISSUE THREAD

**Issue by jafamo** [DMPRoadmap/roadmap#1964]
**Expected behaviour:**
Count users,plans and print results as in https://github.com/DMPRoadmap/roadmap/issues/1937

**Actual behaviour:**
Only show graphics without data 

**Steps to reproduce:**
I am using roadmap version 1.0.5 migrated from DMPOnlinev4.
I am login with user ( super_admin privileges).

In my console log with this URL:
https://my-dmp/api/v0/statistics/users_joined?api_token=Uy9m4J9pA_pbRGST6e-jJQ&topic=users&start_date=&end_date=&org_id=15

`On Status Code: 302 Moved Temporarily`

This is what happend when I am trying to generate  Plans or User statisics. I attached an image with the result

![](https://user-images.githubusercontent.com/3945078/47286338-8845ab00-d5ee-11e8-8e41-c7470a39ea2e.png)

If I download a statistics, I can see on my .csv an HTML from homepage.

Any idea ?

Regards.

**Comment by magdalenadrafiova** [comment]
closing out this was already fixed

**Comment by xsrust** [comment]
@jafamo 
The API endpoint//page have both been refactored quite a bit since this ticket was raised.
Just double-checking that this ended up being fixed for you by those changes.  If not, feel free to raise a new ticket and we'll try to point you in the right direction.
