### ISSUE TITLE
Can we remove save button on each answer since they are autosaved when changing focus?

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#1967]

**Comment by xsrust** [comment]
I think this is actually a really good question.
We've had confusing from end-users before about the manual vs autosave within the application, as we implement both paradigms in different places.

When editing a plan, this can be particularly confusing as both auto and manual save functionality exists on the same form, many times per-page.
@magdalenadrafiova @mariapraetzellis   Do we have a separate ticket around making auto-save consistent?

**Comment by magdalenadrafiova** [comment]
@xsrust We do not have a separate ticket - I will keep this then
