### ISSUE TITLE
Clean up assets directory

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#1973]
We should go through our assets directory and remove any image and video files that are no longer in use.

**Comment by magdalenadrafiova** [comment]
@briri is this still relevant? where is the assets directory?

**Comment by briri** [comment]
Cleaned this up as part of the Rails5 upgrade. The asset directories are [app/assets/](https://github.com/DMPRoadmap/roadmap/tree/master/app/assets) and [/public](https://github.com/DMPRoadmap/roadmap/tree/master/public). They contain a bunch of old logos and other unused files.
