### ISSUE TITLE
Add support for Amazon S3 file storage

### ISSUE THREAD

**Issue by Bodacious** [DMPRoadmap/roadmap#1976]
Application should provide *optional* support for using Amazon S3 as a file store.

This should gracefully fall-back if users do not want to deploy with amazon S3.

**Comment by sjDCC** [comment]
Unsure how to test this - should a dev close out? @briri @xsrust

**Comment by briri** [comment]
Nothing on the UI to test unless @xsrust has S3 setup already for DMPonline test

**Comment by xsrust** [comment]
Graceful fallback is working and I can test the S3 setup early next week.

As any issues would be with using the new functionality and not with the continued use of the local filesystem for these assets, it's relatively non-risky to include if we release before it gets tested.

**Comment by sjDCC** [comment]
Closing out based on @xsrust comment
