### ISSUE TITLE
Delete / deactivate institutions and organisations?

### ISSUE THREAD

**Issue by Falco-KUB** [DMPRoadmap/roadmap#1978]
I'm not sure whether this has been discussed before, at least I couldn't find it, but if so, please let me know.

We're looking for a way to delete or at least deactivate organisations and institutions. One of the reasons is that we in Denmark had two research libraries merged into one and we don't want people to be able to sign up with one that doesn't exist anymore - so we want it to disappear from the list of suggested organisations when creating an account. Any ideas?

**Comment by jarifriman** [comment]
This would be a desired feature also in DMPTuuli. In Finland there are two universities merging into a one starting from January 2019. Also, we don't want new users to able to select an institution that doesn't exist anymore.

**Comment by xsrust** [comment]
Hi @jarifriman @RDM-DTU, 
We havent discussed the concept before.  It sounds like more than a deactivated institution, the desire is to be able to merge organisations via the super-admin interface.  Deletion can be achieved by merging into the 'other' org, which serves as a default.

Would that be sufficient, or is there a desire to have an org to which users are associated, but people cannot switch to or create an account with?

@sjDCC @stephaniesimms.  This would be simple enough to add.  We can re-associate all users, templates, guidance, and annotations with the passed new organisation.

If we dont want that to be a feature available from the frontend, we could atleast codify the behavior into a rake-task to make it easier for anybody who manages a roadmap installation to do this housekeeping task.

**Comment by RDM-DTU** [comment]
@xsrust I think your idea would work for our purposes.
Whether users are re-associated with a new organisation or left with the old organisation that is not listed anymore, would not matter for us.

**Comment by sjDCC** [comment]
Hi @xsrust @Falco-KUB I think this is a change on the backend then rather than a new feature. The devs should be able to run a task to migrate users from the redundant uni into the new merged affiliation. Closing this out.
