### ISSUE TITLE
Users cannot create an account when a plan is shared with them

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#1986]
Currently, when a plan is shared with a user who does not have an account, a new account is created for them and an invitation sent out.  
It looks like devise-invitable skips validations when it creates a user, so when they follow the link and fill in a password, their save gets prevented as they dont have a firstname, surname, or org.  

Fix 1)  pass extra arguments to the call to `User.invite!` to setup a default name/org.
Fix 2)  add extra fields on the form to ask them to fill in their org, firstname, and surname, as well as password

**Comment by xsrust** [comment]
@sjDCC @briri @stephaniesimms 
Would you perfer the defalt name and org (based off org of the plan sharer) or asking the user to fill these in before they can finish creating their account?

**Comment by briri** [comment]
I think forcing them to provide their name and then select their org would be a good approach @xsrust. 

What does the workflow do with password currently? Does it prompt them to set one? If so, should we give them them an option to sign in via Shib or email/password? We might be able to just reroute them to those account creation workflows. The only worry would be that it retains the tie to the plan (and their role) from the invitation

**Comment by stephaniesimms** [comment]
related issue #2002 should unblock for testing

**Comment by sjDCC** [comment]
Tested now and works fine. Like the fact that first and last name were added to form as mandatory field

Closing out
