### ISSUE TITLE
Generic plan option not working

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#199]
Clicking the link to 'select here to write a generic plan' doesn't respond

![capture](https://cloud.githubusercontent.com/assets/6169940/24205037/28f0b5cc-0f12-11e7-9bc0-6dd3bfd1f6df.PNG)

**Comment by stephaniesimms** [comment]
@sjDCC I don't see an option to select the Generic template at all now.
![screen shot 2017-04-24 at 5 34 54 pm](https://cloud.githubusercontent.com/assets/12703638/25364059/61b481b0-2914-11e7-955b-9b860e7590bf.png)

**Comment by sjDCC** [comment]
I think there are a couple of issues here:

1. The strange Academy of Finland DMP checkbox is because the full template description field is being pulled as well as the name. I think we should only display the name in the template selection list.

2. It's not clear to users what's happening when they fill in that initial create plan question. I've suggested bringing in the institutional question too in ticket #261 I think this would help. 

3. Reinstating the text to create a generic plan would help too. "If you aren't responding to specific requirements from a funder or an institution, select here to write a generic DMP based on the most common themes."

**Comment by jollopre** [comment]
Agree with @sjDCC that this ticket should tackle the removal of the description field when choosing a template.

The rest will be tackled by #261

**Comment by sjDCC** [comment]
Description field removed correctly. The messaging could be improved, but is this already addressed in another ticket? 

This is the message when there is more than one institutional template:
![institutional-template](https://cloud.githubusercontent.com/assets/6169940/26005684/c10d7c9a-3731-11e7-94d2-b236efc61cdd.PNG)

And this is the message when there is more than one funder template:
![funder-template](https://cloud.githubusercontent.com/assets/6169940/26005685/c47c0c0c-3731-11e7-9e03-aa5da083edca.PNG)

Perhaps make this consistent and better formatted by changing text to:

"There is more than one institutional template" OR "There is more than one funder template"

Very minor point. Does it need a new ticket @vyruss?

**Comment by briri** [comment]
I wouldn't bother updating the code in the shared repo yet. This changes quite a bit in the new create plan page
![screen shot 2017-05-12 at 8 45 51 am](https://cloud.githubusercontent.com/assets/1204467/26005918/77e27436-36ef-11e7-8901-7c5107780b52.png)

**Comment by briri** [comment]
The messaging that then appears at the top of the page after the plan is created looks like this:
- This plan is based on the default template.
- This plan is based on the Horizon2020 template.
- This plan is based on the Horizon2020 template with customisations by the University of Helsinki.
- This plan is based on the University of Helsinki DMP template

**Comment by briri** [comment]
Then there's additional info that appears on the plan page afterward so they always know what template they are using:
![screen shot 2017-05-12 at 8 50 04 am](https://cloud.githubusercontent.com/assets/1204467/26006107/1c3cb082-36f0-11e7-9a87-2f854580a8f3.png)

**Comment by stephaniesimms** [comment]
@briri I agree that these changes should solve the issue, but will let @sjDCC confirm

**Comment by sjDCC** [comment]
Ok let's close this out.
