### ISSUE TITLE
Uncheck the last checkbox has no effect

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#1999]
Please complete the following fields as applicable:

**Expected behaviour:**
Uncheck the last checkbox should remove the last checkbox

**Actual behaviour:**
Uncheck the last checkbox has no effect

**Steps to reproduce:**

1. create a plan with a question with many checkboxes
2. create a plan and check 1 checkbox
3. save the answer
4. refresh to see that you indeed select 1 checkbox
5. uncheck that checkbox
6. refresh the page and see that the checkbox is still checked

Fix:
In answers_controller.rb, in `permitted_params`, after the `permitted` variable assignment, add
```
      if params[:answer][:question_option_ids].nil? # If no question options has been chosen
        permitted[:question_option_ids] = []
      end
```

**Comment by rosiehigman** [comment]
Hi, we've experienced the same problem and have had a user report this to us. It's come up in a few plans and is causing a bit of confusion.

**Comment by sjDCC** [comment]
Unchecking fine now. Closing out. Thanks @johnpinto1 and @Yu-Chieh-Henry-Yang
