### ISSUE TITLE
Can't download institutional plans

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2001]
From the My Dashboard page, the icons to download institutionally-shared plans throw a 'something went wrong error' Perhaps this is to do with a permissions setting or other mis-configuration?

![download-error](https://user-images.githubusercontent.com/6169940/49466668-8e879380-f7f8-11e8-9d6b-9af7917b46cc.PNG)

**Comment by briri** [comment]
Hey @sjDCC,

I can't replicate this issue. I did just deploy some recent changes which might have addressed the underlying issue. If you're still experiencing it let me know if you're logged in as a super/org admin or a regular user

**Comment by briri** [comment]
Doesn't happen for every plan. 

The error seems to be a nil value for `@selected_phase`

```ruby
      <% if phase[:title] == @selected_phase.title %>
```

**Comment by sjDCC** [comment]
Download working fine on both. Closing out
