### ISSUE TITLE
Update server URL for roadmap stage

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#2002]
we're encountering some problems testing email notifications, etc owing to an outdated server URL for roadmap stage. it needs to be updated to https://roadmap-stg.cdlib.org/

**Comment by briri** [comment]
Yep, due to some configuration changes in the past two months. I've updated the Capistrano deploy scripts so it should have the correct hostname now.

**Comment by sjDCC** [comment]
All working now - thanks @briri
