### ISSUE TITLE
Plan owner should not be a reviewer

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2011]
If the owner of a plan is an Org Admin and they click 'Request Feedback' button for their plan, they are added to the reviewer role for the plan. This removes the plan from their 'My Dashboard' list. 

We should not add the reviewer role for the current user

**Comment by sjDCC** [comment]
I think logic was added to fix this one so it can possibly be closed out as a legacy issue

**Comment by briri** [comment]
yes. we no longer use roles behind the scenes to manage who is a reviewer, so this ticket is no longer applicable
