### ISSUE TITLE
Users cant create an account via shibboleth

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#2014]
JS is broken on the create-account-form when creating an account via shibboleth.

Users are also unable to link accounts to shibboleth via this form and recieve a 404

**Comment by xsrust** [comment]
Create account form needs to be wrapped in a div with id "create-account-form".

Sessions controller throwing error when setting shibboleth_id on the user as this no longer exists.

**Comment by sjDCC** [comment]
This is workig fine on DMPonline-test and I didn't get any errors on roadmap-stage either for the amount of the workflow I have the right info to follow. Suspect it's fixed on both so closing out
