### ISSUE TITLE
Do not show Guidance selections when the plan has no applicable guidance

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2020]
If the template that a plan was created from does not have any themed guidance (e.g. none of its questions have themes) then do not display the guidance selection area on the plan details page. Currently this area lets the user know that they can select up to 6 guidance groups but there are no selectable options.

**Comment by sjDCC** [comment]
Hi @briri I have tried to replicate this but am not sure I can. There will always be DMPTool or DMPonline themed guidance so the choice to choose selections will come up.
![themed-guidance](https://user-images.githubusercontent.com/6169940/51901692-272d3080-23b0-11e9-8e86-63af3642d0fe.PNG)

Or is your issue how many institutions come up in the list? This should be filtered to only include those that have themed guidance to offer. I was surprised how many were there for the USA. Interestingly, UC Davis who I was testing with wasn't in the list. I had deleted their one piece of themed guidance and unpublished the guidance group.
![institutions](https://user-images.githubusercontent.com/6169940/51901677-1e3c5f00-23b0-11e9-86dc-7afa48a26399.PNG)

Have we at some point implemented a rule to auto-create an institutional guidance group when creating the organisation? Do you recall @xsrust? This may be why so many unis are showing in list despite not actually having themed guidance

**Comment by briri** [comment]
The issue is an edge case but possible. It occurs when a user creates a plan from a **template** whose questions have no themes. Therefore there is no way to attach themed guidance to any questions when the user edits the plan.

To replicate the scenario:
- Login to roadmap-stg
- Create a new plan (research org = 'UCOP', funder = no funder)
- This should create a plan based on the 'Unthemed template' 
- You should see a "There is no additional guidance for this template." under the "Select Guidance" section. 

It was showing all of the normal text before but had no checkboxes available and no entries in the pop-up modal form

**Comment by sjDCC** [comment]
Just created a template with no themes and this works as expected. Thanks for advising my how to test @briri Had total brain fail ;-)

![Capture](https://user-images.githubusercontent.com/6169940/55016550-e7b54600-4fe6-11e9-92bc-3db4d086df4a.PNG)

**Comment by briri** [comment]
thanks @sjDCC :)
