### ISSUE TITLE
Default sort behavior lost when clicking 'View all' or 'View less'

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2027]
@stephaniesimms discovered this while testing on the DMPTool.

"I first noticed that the default sort behavior changes when I click the link to 'View All' on the Funder Requirements page. Default on that page should be alphabetical sorting by template name (screenshot below).

The sorting changes on all other tables I tested when I click 'View All' - all previous default sorting rules need to be reinstated. E.g., Public plans and My Dashboard plans should display most recent edited date at the top of the list. Templates tables should be alphabetized by template name. Etc."

<img width="1330" alt="screen shot 2018-12-14 at 8 38 52 am" src="https://user-images.githubusercontent.com/12703638/50015917-9e337480-ff7c-11e8-92a8-de9f3613f08f.png">

**Comment by sjDCC** [comment]
Ordering working as expected now. Thanks @briri
