### ISSUE TITLE
Non-unique DOM elements on the My Dashboard page

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2028]
If you login and go to the My Dashboard page (you must have more than one plan), you will see the following warning in the console:

<img width="1072" alt="screen shot 2018-12-18 at 8 38 29 am" src="https://user-images.githubusercontent.com/1204467/50168562-94718000-02a0-11e9-901e-1718b1f0ac09.png">

We should update the identifiers by giving the forms a namespace

The same is also happening on the Users page

**Comment by sjDCC** [comment]
I don't think this is an issue anymore - possibly after the validations work.
![Capture](https://user-images.githubusercontent.com/6169940/70257526-5952b000-1782-11ea-9bcd-69834ffa4aaa.PNG)

Close out if legacy.

**Comment by briri** [comment]
agreed. I'm not seeing these errors any longer
