### ISSUE TITLE
Share with organisation is open to any user who registers with that organisation

### ISSUE THREAD

**Issue by asconrad** [DMPRoadmap/roadmap#2030]
Please complete the following fields as applicable:

**Expected behaviour:**
Share DMP with organisation should be limited to users actually belonging to that organisation.

**Actual behaviour:**
Any user can register or change organisation to any other organisation. In this way they get access to plans belonging to that other organisation. This perspective is not in any way clear to the user, when selecting to share internal with own organisation. Universities are upset about this and treat it as a breach of information security. As anybody is free to register an account, in effect Share with organisation is the same as publish.

**Steps to reproduce:**
Login to any user account and go into "Edit profile". Change Organisation into any organisation having some users check Share -> "Organisation: anyone at my organisation can view". Go to "My Dashboard" and all plans by the selected organisation are now listed under own plans.

**Comment by sjDCC** [comment]
Hi @asconrad This is intentional. We didn't want to impose SSO style restrictions per org and allow users flexibility to change and view guidance etc from others.
