### ISSUE TITLE
Replace contact_us gem

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2032]
The contact_us gem is sending out duplicate emails when a user fills out the form when not logged in. While investigating I noticed that the gem is not well maintained and that we would likely be better off switching to something different of simply building out our own form.

**Comment by magdalenadrafiova** [comment]
@briri is this still an issue?

**Comment by briri** [comment]
We still use the gem and for now, it has not been an issue. I think we can close this ticket and re-raise if the maintainer of the code does not keep up with it.
