### ISSUE TITLE
Why does config/initializers/dragonfly.rb have secret in code in plain text?

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#2036]
Why does `config/initializers/dragonfly.rb` have `secret` in code in plain text?

Should we hide that secret into `config/secret.yml`?

**Comment by magdalenadrafiova** [comment]
@briri @xsrust one of many I want to check with you whether this is still relevant and should be assigned to backlog?

**Comment by briri** [comment]
We will be cleaning this up as part of the Rails 5.2 upgrade which stores secrets in an encrypted file. Refer to #2467 for the work to move this secret to the encrypted file
