### ISSUE TITLE
Provide JS access to .po and .pot localization files

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#204]
Investigate using the Gettext-I18n JS repo, https://github.com/webhippie/gettext_i18n_rails_js (recommended by gettext_i18n_rails), to translate the .pot and .po files into json files under assets.

Then update all of the old I18n references in the javascript files so that they use this new approach.

**Comment by briri** [comment]
related to an issue about missing translations on #185

**Comment by raycarrick-ed** [comment]
related to https://github.com/DMPRoadmap/roadmap/issues/182

**Comment by raycarrick-ed** [comment]
when this ticket gets tackled it will need to take into account the i18N of the various statuses (plan, section, answer) which get generated by JS in places. I think there are all in views/answers/update.js.erb.  I have left TODO markers for them

**Comment by briri** [comment]
I added the gem mentioned above and did the following:get checked into source code
- added the include statements to the `application.js` file
- added the current `Fastgettext.locale` to the main `<html>` tag
- replaced all of the I18n references in the js files
- added jquery.timeago text to the pot/po files

We will need to run `rake gettext:po_to_json` whenever we update the pot/po files. This task generates the json equivalents.

Won't be able to thoroughly test though until the recent export and plans fixes are merged in.

**Comment by briri** [comment]
@stephaniesimms and @sjDCC this fix has been deployed to the server.  There were a few places on the plans page that I wasn't able to thoroughly test for this missing translation fix. You can see it working though on the guidance page if you click save without filling everything out. Please open a new ticket if you find further instances of 'missing translation' messages

**Comment by stephaniesimms** [comment]
I can't find any instances of missing translations so closing for now.
