### ISSUE TITLE
seeds.rb file appears to be out of date

### ISSUE THREAD

**Issue by colingor** [DMPRoadmap/roadmap#2041]
Running rake db:seed results in an error, presumably because seeds.rb needs updated:

>    (0.5ms)  SELECT "languages"."abbreviation" FROM "languages"  ORDER BY "languages"."abbreviation" ASC
  Language Load (0.3ms)  SELECT  "languages".* FROM "languages" WHERE "languages"."default_language" = $1  ORDER BY "languages"."id" ASC LIMIT 1  [["default_language", "t"]]
   (0.4ms)  SELECT "languages"."abbreviation" FROM "languages"  ORDER BY "languages"."abbreviation" ASC
  Language Load (0.4ms)  SELECT  "languages".* FROM "languages" WHERE "languages"."default_language" = $1  ORDER BY "languages"."id" ASC LIMIT 1  [["default_language", "t"]]
  Language Load (0.4ms)  SELECT  "languages".* FROM "languages" WHERE "languages"."default_language" = $1  ORDER BY "languages"."id" ASC LIMIT 1  [["default_language", "t"]]
  Language Load (0.3ms)  SELECT  "languages".* FROM "languages" WHERE "languages"."default_language" = $1  ORDER BY "languages"."id" ASC LIMIT 1  [["default_language", "t"]]
  ActiveRecord::SchemaMigration Load (0.3ms)  SELECT "schema_migrations".* FROM "schema_migrations"
rake aborted!
ArgumentError: Factory not registered: identifier_scheme
/usr/local/bundle/gems/factory_bot-4.11.1/lib/factory_bot/registry.rb:24:in `find'
/usr/local/bundle/gems/factory_bot-4.11.1/lib/factory_bot/decorator.rb:10:in `method_missing'
/usr/local/bundle/gems/factory_bot-4.11.1/lib/factory_bot.rb:100:in `factory_by_name'
/usr/local/bundle/gems/factory_bot-4.11.1/lib/factory_bot/factory_runner.rb:12:in `run'
/usr/local/bundle/gems/factory_bot-4.11.1/lib/factory_bot/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
/opt/src/dmp/db/seeds.rb:43:in `block in <top (required)>'
/opt/src/dmp/db/seeds.rb:43:in `map'
/opt/src/dmp/db/seeds.rb:43:in `<top (required)>'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `block in load'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/local/bundle/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:268:in `load'
/usr/local/bundle/gems/railties-4.2.10/lib/rails/engine.rb:547:in `load_seed'
/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/tasks/database_tasks.rb:253:in `load_seed'
/usr/local/bundle/gems/activerecord-4.2.10/lib/active_record/railties/databases.rake:173:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:seed

**Comment by magdalenadrafiova** [comment]
@briri @xsrust one of many I want to check with you whether this is still relevant and should be assigned to backlog?

**Comment by briri** [comment]
yes this has been resolved in the later releases of the code
