### ISSUE TITLE
Don't present abbreviation code on User Interface

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2047]
When plans are submitted for review, the email notification that will be issued is presented in the UI. You can see in the screengrab below that this sometimes includes the abbreviation code for user names etc. 
![feedback-1](https://user-images.githubusercontent.com/6169940/51900659-c7ce2100-23ad-11e9-8582-484019ee759d.PNG)

Once the 'Request feedback' button is clicked, the notification panel at the top presents the text properly (see screengrab 2). Since we know the user etc, can we ensure it always displays as proper text.
![dmp-feedback](https://user-images.githubusercontent.com/6169940/51900668-cc92d500-23ad-11e9-9055-1659b44e8cc6.PNG)

**Comment by johnpinto1** [comment]
The abbreviations should no longer appear.
![selection_119](https://user-images.githubusercontent.com/8876215/52857367-e60e7d80-311e-11e9-8b81-9382a551c81d.png)
![selection_120](https://user-images.githubusercontent.com/8876215/52857395-f45c9980-311e-11e9-88a0-a7649f6ee928.png)

**Comment by sjDCC** [comment]
Looks good, thanks @johnpinto1 Closing out
