### ISSUE TITLE
Update wiki installation instructions for CSS assets and anything affected by Javascript changes

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2048]
Updated the Branding, Installation and Troubleshooting Wiki pages to reflect the new changes. 

Those changes look good to @xsrust, moving to UAT

**Comment by sjDCC** [comment]
I've converted this to an issue and put in pending as we have changed from pootle since so will need to update wiki

That can happen in next sprint though

**Comment by sjDCC** [comment]
Sorry - had misread this as translation not installation, hence converting to issue to update text on pootle approach. I assume this is good to close out though @xsrust as installation guidelines are ok?

**Comment by xsrust** [comment]
closing as guidelines look ok
