### ISSUE TITLE
Do not show expand/collapse all links if there is only one item

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2049]
Please complete the following fields as applicable:

**Expected behaviour:**
If there is only one themed guidance for a question on the edit plan page, the user should not be presented with the expand/collapse all links

**Actual behaviour:**
The expand/collapse all links appear regardless of how many themed guidance sections are available

**Steps to reproduce:**
- Login 
- Edit a plan (make sure you have selected guidance from DMPTool/DMPonline)
- Expand sections until you find a question with only one themed guidance 

<img width="1191" alt="screen shot 2019-01-29 at 10 25 42 am" src="https://user-images.githubusercontent.com/1204467/51930816-41ffa500-23b0-11e9-9ae4-f874985a7114.png">

**Comment by johnpinto1** [comment]
Mistakenly assumed item still open.

**Comment by magdalenadrafiova** [comment]
Works well for me - this seems to be fixed to me - 
![expand-all-guidance-03042019](https://user-images.githubusercontent.com/47178106/55470622-e2b45000-55ff-11e9-9016-1fbfa2e0bfc3.PNG)

**Comment by dsisu** [comment]
This works OK for me. UoE template - question on Integrity has one theme so I don't get expand all/collapse all; question on Confidentiality and IPR has two themes so I get the expand all/collapse all option.

**Comment by magdalenadrafiova** [comment]
The same here – I suggest we can close the ticket ..
