### ISSUE TITLE
Link Users to their plans on the Users page

### ISSUE THREAD

**Issue by rosiehigman** [DMPRoadmap/roadmap#2057]
**Expected behaviour:**
When I look up a user as an Org Admin it would be really helpful if I could then click through to view that users' plans. Most weeks we have enquiries where we are trying to match a user to their plans, or similar, and this would make it much easier to do this.

**Actual behaviour:**
When I look up a user I can see how many plans they have but I have no way of then finding these plans, see screenshot below:

![image](https://user-images.githubusercontent.com/15738325/52959662-a77efa00-338e-11e9-859d-83a4baebad12.png)

**Comment by sjDCC** [comment]
Thanks @rosiehigman Good point. it would be good if this linked to a list of plans for the user. I'm not sure if we already have that view for admins (it's probably just on the users own dashboard) but @xsrust and @briri can probably suggest options

**Comment by sjDCC** [comment]
This was discussed more in user group. We would need to add a new view for admin users of users and their plans. 

Potentially other info could be added to this page too to help track uptake and usage e.g.
- last login
- collaborators (other users plans are shared with - name & institution)

For now just add a simple table view of plans for that user (like My Dashboard) and other info could be added in time

**Comment by sjDCC** [comment]
Closing out as this is covered by ticket #2240 which should be deployed next week.
