### ISSUE TITLE
Send email on completion of review only rather than one per comment

### ISSUE THREAD

**Issue by jessn-h** [DMPRoadmap/roadmap#2059]
Is it possible to change settings at an institution level so that DMP owners only receive an email upon completion of the review rather than one email per comment?

We have received feedback the some DMP owners feel the number of emails they receive is unnecessary.

**Comment by briri** [comment]
Hi @jessn-h. The system currently does not have a way to distinguish between comments made to a plan by a reviewer and those made by collaborators.

Users do have the ability to turn off certain types of email notifications in their user profile (see screenshot below). If they deactivate the 'A new comment has been added to my DMP' option they will stop receiving those notices but will still be notified when the review period is over.
<img width="618" alt="screen shot 2019-02-25 at 9 21 57 am" src="https://user-images.githubusercontent.com/1204467/53355987-32a44680-38df-11e9-86e8-02b118965966.png">

While not ideal, I hope it can at least help reduce the volume of communications your users are receiving from the tool.

**Comment by jessn-h** [comment]
Thanks @briri I thought that may be the case but just wanted to check I hadn't missed something. We will advise DMP owners to amend their notification settings.

**Comment by briri** [comment]
thanks @jessn-h. I will leave this ticket in our backlog because I think it may be worth distinguishing between these types of comments at some point.

**Comment by sjDCC** [comment]
Yes, agree it would be good to distinguish between these @briri 

. One quick fix in interim could be to set the email notifications for plan comments as off automatically so it's opt-in rather than opt-out

**Comment by johnpinto1** [comment]
@briri + @xsrust  
   The branding.yml will need to be altered to set the following item to false:
```
preferences:
      email:
          users:
              new_comment: false
```
@sjDCC Only a new user will have the chekbox **'A new comment has been added to my DMP'** unticked by default.

**Comment by magdalenadrafiova** [comment]
I created a new account but all was still ticked for me -
![new-user-03042019](https://user-images.githubusercontent.com/47178106/55471154-06c46100-5601-11e9-8e86-21c414da8369.PNG)

**Comment by johnpinto1** [comment]
@xsrust  has the property been changed in the *branding.yaml* on UAT`preferences:
     
```
preferences:
      email:
          users:
              new_comment: false
```  That might explain @magdalenadrafiova  issue above.

**Comment by dsisu** [comment]
They are all ticked by default for me too

**Comment by xsrust** [comment]
This has been fixed and should run-through as the default for any users who have not explicitly changed their notification settings

**Comment by dsisu** [comment]
Hi, this works for me now. The default appears to be with notifications off. I'm going to close this issue. However, an ideal solution would be to have a notifications digest function, with users having the option to select timings for notifications - every 4 hours, daily, weekly, monthly.

**Comment by jessn-h** [comment]
Thank you all so much for your help with this issue
