### ISSUE TITLE
Error we get when running rake db:migrate in step 1 of the migration - DMPonline to DMProadmap migration 

### ISSUE THREAD

**Issue by Ebrahim1010** [DMPRoadmap/roadmap#2069]
Please complete the following fields as applicable:

**Expected behaviour:**
Run through the migration
**Actual behaviour:**
Full Error
 
D, [2019-03-25T10:41:07.666885 #23753] DEBUG -- :    (14.8ms)  SELECT COUNT(*) FROM `languages` WHERE `languages`.`default_language` = 1
D, [2019-03-25T10:41:07.695116 #23753] DEBUG -- :   Language Load (0.3ms)  SELECT  `languages`.* FROM `languages` WHERE `languages`.`default_language` = 1  ORDER BY `languages`.`id` ASC LIMIT 1
rake aborted!
I18n::InvalidLocale: :en_GB is not a valid locale
/var/lib/gems/2.3.0/gems/i18n-0.7.0/lib/i18n.rb:284:in `enforce_available_locales!'
/var/lib/gems/2.3.0/gems/i18n-0.7.0/lib/i18n.rb:151:in `translate'
**Steps to reproduce:**
Upgrade Step 1

Tasks: transition to Rails 4.2, new user permissions and seed new lookup tables

    git fetch --all
    git checkout dmponline4_upgrade_step1
    git pull origin dmponline4_upgrade_step1 This is not necessary if you have just cloned the repo
    Comment out the pg or mysql2 gem in the Gemfile if necessary
    bundle install
    rake db:migrate
    rake migrate:seed
    rake migrate:permissions
    rake migrate:data_integrity WARNING: this step will replace invalid user email addresses with a temporary email address. If it does, it will record the invalid email and the user info in the log/migration.log file. Please review this log after running the script. You may need to contact the user or their organisational admin to get their correct email address. If this file is empty or missing that means that no invalid email addresses were found and all data migrated successfully.
    git stash

**Comment by xsrust** [comment]
Hi,
I'd like to help out with this as I wrote those migrations a few years ago.

After which command did this present the above error?

**Comment by Ebrahim1010** [comment]
Thanks, I've resolved this issue

**Comment by xsrust** [comment]
How did you resolve it? 
just in case anybody runs into the same problem down the line and are searching the repo for a solution.

Thanks
