### ISSUE TITLE
Inform user when creating Plan: which Template has been selected (if no choice)

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#207]
If you don't select a funder when creating a Plan you automatically get:
- your institution's Template (if there is only one)*
- a choice if your institution has multiple Templates

    *this might be confusing because it might seem like the user has not selected a Template, so let's notify the user that "Template _blah_ has been selected"

**Comment by raycarrick-ed** [comment]
Addressed in https://github.com/DigitalCurationCentre/roadmap/commit/70fe8a14d3f1df8d566ba82773360d4dd5811504
Add in a "No Funder" option to handle that option without additoinal buttons/links.
The selection logic should be explained if a customised template is used or the base template for your institution or the installation default template.
I think this also addresses https://github.com/DMPRoadmap/roadmap/issues/199

**Comment by briri** [comment]
👍 I like the approach of removing the link and just providing the user with enough information to proceed using the drop downs.

**Comment by briri** [comment]
This one looks good Ray, just localize that one 'Customised from' text in views/plans/_plan_details.html.erb and it will be ready fro PR

**Comment by briri** [comment]
added localization for the line referenced above.

**Comment by stephaniesimms** [comment]
There is now only a funder selection drop-down and no possibility of selecting an institutional template, or generic template (also see related issue #199 ). It appears that the user must select "No funder" from the drop-down, which generates a weird list of options (screenshot)

![screen shot 2017-04-24 at 6 14 40 pm](https://cloud.githubusercontent.com/assets/12703638/25364900/62b72c10-291a-11e7-942a-477c6444b8b9.png)

**Comment by sjDCC** [comment]
Looking at this, the user is now given one of 3 messages I think. 

The first occurs when they pick a funder template which the institution has customised in some way.
![funder-template](https://cloud.githubusercontent.com/assets/6169940/25385142/f6551798-29ba-11e7-86e8-074ad1ec83bb.PNG)

The second occurs when there is no funder and they are given the default, generic template as there isn't an institutional one. Perhaps this one shows too when there is only one institutional template?
![generic-template](https://cloud.githubusercontent.com/assets/6169940/25385180/19f8eaf8-29bb-11e7-95fe-e623cd42163c.PNG)

The third basic message occurs either where there's a funder template without institutional customisations, or where there is a choice of institutional templates so the user has selected from a secondary dropdown
![funder template-no-org](https://cloud.githubusercontent.com/assets/6169940/25385263/6a997d10-29bb-11e7-9e5b-96a50fbf12ae.PNG)

The messaging isn't that transparent. We should maybe clarify the template name e.g. 

Plan successfully created. This plan is based on the Wellcome Trust template with customisations by the University of Edinburgh.
OR
Plan successfully created. This plan is based on the University of Edinburgh template.
OR 
Plan successfully created. This plan is based on the default template. (for when there is no funder or institutional template)

**Comment by briri** [comment]
Updated the messaging to match @sjDCC suggestions above

**Comment by sjDCC** [comment]
Great, thanks @briri!

**Comment by sjDCC** [comment]
All looks good. Closing out
