### ISSUE TITLE
Tables view issue in example answers

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2071]
There is a styling issue with tables in the example answers field. If admins add tables in the TinyMCE fields,  gridlines for the table don't show. See the screenshot below.

![tables](https://user-images.githubusercontent.com/6169940/55071031-74134780-507f-11e9-89a9-aa6585f3517d.jpg)

You can see an example in question 1 of the TU Delft questions about personal research data management. As the issue was reported by Delft so they should be alerted once fixed.

**Comment by martateperek** [comment]
There is also an issue with the answers. if a researcher asks for feedback, the reviewer has no way to see the content:
![image](https://user-images.githubusercontent.com/10851024/55703901-2da4dd80-59db-11e9-91a9-c1695ed3e7a2.png)

**Comment by sjDCC** [comment]
Hi @johnpinto1. Thanks for working on this. There are still some issues with display. The tables in example answers now have gridlines and don't overlap the box but tables in other areas are misformatted, specifically:

- default answers are displaying in html
- tables in guidance are displaying without gridlines
- tables in section description have no gridlines
- tables in phase description have no gridlines

Could you please apply fix to other areas?

![Capture](https://user-images.githubusercontent.com/6169940/56306928-a6bed600-613b-11e9-8b2b-d33f01b8e3f7.PNG)
![PHASE-DESCRIPTION](https://user-images.githubusercontent.com/6169940/56306949-ae7e7a80-613b-11e9-85e7-20ced8a25f34.PNG)

**Comment by sjDCC** [comment]
Have just tested this in review mode too and the text isn't overlapping boxes then. Ironically the table displays with gridlines in the review read-only mode. 
![cap2](https://user-images.githubusercontent.com/6169940/56307338-8c392c80-613c-11e9-89d6-b65f1ddcd673.PNG)

When I tried to save an answer in the box with html, I got this response. We need to fix this before release
![Capture](https://user-images.githubusercontent.com/6169940/56307352-92c7a400-613c-11e9-94c8-6a011c14e864.PNG)

**Comment by johnpinto1** [comment]
@sjDCC The code is not on UAT yet, but is on DEV.

**Comment by johnpinto1** [comment]
@sjDCC @xsrust @briri  I think I have fixed the issues mentioned and related ones. However, I was unable to replicate the *save* bug mentioned above https://github.com/DMPRoadmap/roadmap/issues/2071#issuecomment-484181030
![Selection_204](https://user-images.githubusercontent.com/8876215/56419394-04fdcd00-6292-11e9-8837-fe3f8ba68ed6.png)

Saved html and viewed in preview:
![Selection_205](https://user-images.githubusercontent.com/8876215/56419380-f57e8400-6291-11e9-837b-d1290d1d72ec.png)

**Comment by sjDCC** [comment]
The default answers are no longer showing html so the save bug isn't occurring. 

Comments and section/phase description aren't rendering tables correctly, but all other areas look good

**Comment by johnpinto1** [comment]
@sjDCC & @xsrust working on fixing outstanding bugs. I have make sure I catch all the various scenarios correctly. Hopefuly done by 2pm.

**Comment by johnpinto1** [comment]
@sjDCC Updated code and hopefully, fixed all outstanding bugs. 
Currently, in review by @xsrust and @briri
Some screen s
![Selection_206](https://user-images.githubusercontent.com/8876215/56424796-a04e6c80-62a9-11e9-9714-93c6d16032ac.png)
![Selection_207](https://user-images.githubusercontent.com/8876215/56424799-a3e1f380-62a9-11e9-8c80-e198b8f8b876.png)

hots of changes:

**Comment by johnpinto1** [comment]
Res-styled readonly tables with cell padding and missing styling for Phase description.
![Selection_211](https://user-images.githubusercontent.com/8876215/56428378-14434180-62b7-11e9-95b3-7c14f77a4dc2.png)
![Selection_210](https://user-images.githubusercontent.com/8876215/56428380-14434180-62b7-11e9-82fb-348794798fba.png)

**Comment by sjDCC** [comment]
All working. This was left open by error
