### ISSUE TITLE
Cannot answer questions 

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#208]
Clicking Answer questions button throws the error below. Blocking numerous issues/testing.

![answer-questions](https://cloud.githubusercontent.com/assets/12703638/24381372/ee28af2a-1304-11e7-8609-b3664adfcdae.png)

**Comment by raycarrick-ed** [comment]
"Answer Questions" link was the old url still. Fixed by https://github.com/DigitalCurationCentre/roadmap/commit/9820cbdc2fdbfd36c316752314652fb28847effe
This link goes to same place as phase tabs at the top of page so was also accessible through that route. Should now work with either route.

**Comment by xsrust** [comment]
I tested this locally on multiple templates and it was working

**Comment by stephaniesimms** [comment]
Working as expected
