### ISSUE TITLE
The Usage page "No of plans during last year" and "No. plans by template" total for some months differ slightly.

### ISSUE THREAD

**Issue by johnpinto1** [DMPRoadmap/roadmap#2083]
**Expected behaviour:**
The **No of plans during last year** for a given month should be equal to *No. plans by template* total for the same month period.

**Actual behaviour:**
In some cases the figures differ. See the **Feb-19** in images below. The figures are **5** and a total of **8** respectively.
![NoofPlansLastYear](https://user-images.githubusercontent.com/8876215/56036887-e9d90d80-5d25-11e9-80b1-86f94297c44b.jpeg)
![noOfTemplates](https://user-images.githubusercontent.com/8876215/56037225-aa5ef100-5d26-11e9-89ac-ba1adfa4ead8.jpeg)

The calls 
http://localhost:3000/api/v0/statistics/created_plans?range_dates... returns
{"Apr-18":47,"May-18":98,"Jun-18":116,"Jul-18":0,"Aug-18":0,"Sep-18":0,"Oct-18":3,"Nov-18":0,"Dec-18":0,"Jan-19":1,**"Feb-19":5**,"Mar-19":2}
http://localhost:3000/stat_created_plans_by_template?start_date=2018-04-30 (
[{"count":2,"date":"2019-03-31","by_template":[ ... **{"count":8,"date":"2019-02-28","by_template":[{"name":"AHRC Data Management Plan","count":6},{"name":"Standard CRUK Template","count":1},{"name":"Hartstichting","count":1}]}**, ...

**Steps to reproduce:**
Choose the **Time period** _"Last 12 months"_ for **No. of Plans by template**. Now total the number of plans for each month by moving the mouse over the stacked bar. Compare these figures with the the corresponding months on the **No. plans during last year**.
Or you can compare the Ajax requests

**Comment by raycarrick-ed** [comment]
I think the reworking moving the logic from JS to ruby looks good and could serve as a model for AJAX calls going forward.
@briri 

Two very small points:

in _filter.html.erb the "Go" button can overlap with the organisation menu when that menu is quite wide (i.e there are long org names) would it be better perhaps on the next line?

The "Download" buttons all have "open in a new window" attached to them when they in fact open a popup dialog. Is this worthwhile or better just left off as it's not really what it's doing?

that's it. The rest all looks fine.

**Comment by briri** [comment]
thanks @raycarrick-ed. I had done most of my testing as an org admin so didn't notice the issue with the Org dropdown. 

Agreed the download buttons should probably not show the 'open in a new window' message. I will address both.

**Comment by briri** [comment]
Moved the org selection in the filter down to its own row (beneath the topic and date filters). We should be able to move it back up next to the dates once we take #2343 which removes that 'topic' filter.

Also removed the 'opens in a new window' class from the download buttons

**Comment by magdalenadrafiova** [comment]
this still seem to be an issue see ticket #2119

**Comment by magdalenadrafiova** [comment]
This works well now - I logged in and had my org set up as University of Manchester and the numbers were consistent. Closing this

**Comment by mariapraetzellis** [comment]
Looks like there is a bug for super admins. When I change the organization in the drop down list it does not update the graphs. 

We also need a refresh of data on dmponline dev because it makes it hard to look for stats w/ old data.

![BugForSUperAdmin](https://user-images.githubusercontent.com/27511575/74551146-84d2e300-4f07-11ea-9a6a-c0c8fe9c0d2a.png)

**Comment by briri** [comment]
We haven't worked on #2343 yet (which involves making those filters update the charts).

Does it display the User/Plan counts if you select an Org and enter dates?

**Comment by xsrust** [comment]
Closing this out as the Plan/User counts are filtering correctly based on the org when I try this locally.
I've actually moved the `Run your own filter` section away from the charts in the PR for #1682 so it does not imply to the user that it will affect the charts.
