### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by norman-smith** [DMPRoadmap/roadmap#2085]
Hi Sam

I’m having an issue finding these invalid records. Could you assist perhaps.

Checking Language records
  0 records with a empty name field
  0 records that are an invalid length for fields [:name] should be <= 20
  0 records with a empty abbreviation field
  0 records that are not unique per (abbreviation)
  0 records that are an invalid length for fields [:abbreviation] should be <= 5
  5 records that do not have valid [:abbreviation]
  0 records that do not have a valid value for [:default_language], should be [true, false]
Checking Note records
  0 records with a empty text field
  3 orphaned records due to nil or missing answer
  0 orphaned records due to nil or missing user
  0 records that do not have a valid value for [:archived], should be [true, false]

Regards
Norman

https://github.com/DMPRoadmap/roadmap/issues/2070#issuecomment-483601670_

**Comment by norman-smith** [comment]
Hi 

I managed to fix the 3 orphaned records.
The rake task find_invalid_records completes with no problems, but the upgrade V2.0.0_part_1 finds issues with the languages.
Is it safe to continue?

**Comment by xsrust** [comment]
Closing this as from  #2104 it sounds like you got past the problem.
But please post your solution so others who run into similar issues can learn from your progress.
