### ISSUE TITLE
Create a separate admin permission for plan reviewer

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2087]
Currently there is not a distinct admin permission for plan reviewers so you need to assign all rights to get this. Since many unis have several people doing reviews but not editing templates / guidance etc, it's desirable to separate this permission out.

Reviewers should get notified of new requests and should have permission to view and comment on these plans.

**Comment by sjDCC** [comment]
I tried testing this but couldn't figure out the functionality. We have a duplicate permission. I assume the last one is 'plan review' and is just mislabelled. I assigned one of my other accounts this permission and submitted a DMP from that org for feedback but no options appeared in my admin menu.

![Capture](https://user-images.githubusercontent.com/6169940/57641259-7b999c00-75ac-11e9-84bb-a05b94e731a7.PNG)

Should we run through it together tomorrow @xsrust as this would be a good one to discuss on Wednesday at the drop-in.

Also noticed that the Tenant didn't change for me from TU Delft when I had changed my org to Imperial to test this. Perhaps something got lost in latest rewrite so worth us retesting this before deploying too.

**Comment by xsrust** [comment]
There's a PR which got merged last night to fix the labeling issue.  I'll deploy this and ping you.

**Comment by sjDCC** [comment]
This looks good and is now labelled correctly. It sends emails out correctly, however, reviewers don't see the plans page on the admin interface (they should at least have access to this) so can't tick to complete a review.

Please can you add this @xsrust 

![Capture](https://user-images.githubusercontent.com/6169940/57708224-dee50600-7660-11e9-815e-90ab6928a2ae.PNG)

**Comment by magdalenadrafiova** [comment]
I cannot test this, I do not think I have admin privileges.

**Comment by sjDCC** [comment]
I just gave you review permissions for Delft @magdalenadrafiova and submitted a plan for review. You should now get an email and see the 'plans' page in your dropdown admin menu. There should be a notifications panel to do the review and complete it if you want to test this.

![Capture](https://user-images.githubusercontent.com/6169940/57934844-67a9af00-78b8-11e9-871c-9a3376955a26.PNG)

All looking good to me now thanks @xsrust If you follow the links Magdalena and all works please close this out

**Comment by magdalenadrafiova** [comment]
works well :) closing
