### ISSUE TITLE
Pre-fill ID on the plan details page

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2089]
The 5 digit ID used in the URL acts as a unique ID in the tool. This should be automatically pre-filled in the ID field on the plan details page.

![ID](https://user-images.githubusercontent.com/6169940/56212406-dabdcc80-6051-11e9-9692-46b3fa46862e.PNG)

**Comment by xsrust** [comment]
@sjDCC 
Do we want to do this for all pre-existing plans which do not have anything set in this ID field?

**Comment by sjDCC** [comment]
I would say so. Do any have anything in the ID field? I don't think it's being actively used

**Comment by briri** [comment]
We have hidden that field in the DMPTool. I don't recall what it was used meant for. Perhaps an internal Uni identifier?

**Comment by sjDCC** [comment]
It was intended as a plan ID but we never used it. Manchester uni do actively use it now so we plan to pre-populate. I guess this shouldn't have any knock-on effect for you if it's hidden but good to flag any ways in which code needs to be implemented if so.

**Comment by magdalenadrafiova** [comment]
Hiya all, 

I do not still see the ID being filled automatically after saving my plan... 
![Pre-fill ID on the plan details page #2089](https://user-images.githubusercontent.com/47178106/57528762-0ff4cc00-732b-11e9-81f6-e2eadd99a34f.PNG)

**Comment by johnpinto1** [comment]
@magdalenadrafiova This will only work for newly created plans. We don't want to overwrite ids of plans if they have been added.

**Comment by magdalenadrafiova** [comment]
I understand - but when I follow the steps to create a new plan it does not create the id again another example - not sure whether I might be doing something wrong and maybe therefore it is not generating it 
![example-2-10052019-2089](https://user-images.githubusercontent.com/47178106/57529162-1df71c80-732c-11e9-9eaa-cb0a2eaf29e4.PNG)

**Comment by magdalenadrafiova** [comment]
Works perfectly - 
![2089 - pre fill](https://user-images.githubusercontent.com/47178106/57530085-5e579a00-732e-11e9-912b-efce02d4d0ea.PNG)

**Comment by xsrust** [comment]
@johnpinto1 
I actually added a rake task:
https://github.com/DMPRoadmap/roadmap/blob/0f24533af50726c7a66e88230e6ff42d0dcacf11/lib/tasks/upgrade.rake#L670-L672

To auto-fill any blank identifiers

**Comment by johnpinto1** [comment]
Great @xsrust

**Comment by sjDCC** [comment]
Looks great. Closing out
