### ISSUE TITLE
Horizon2020 template in DMPTuuli

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#209]
Hi all

Jari Friman has created a new Horizon2020 template on DMPTuuli. When he exports plans based on it, the questions (only the questions not the answers) reveal their html. It is only the Horizon2020 template that does this. Tuuli DMP template doesn't do it. See attached downloads for a couple of my plans.
[Some plan (Horizon 2020 DMP) - DMP title.pdf](https://github.com/DMPRoadmap/roadmap/files/876149/Some.plan.Horizon.2020.DMP.-.DMP.title.pdf)
[Some other plan (Tuuli DMP).pdf](https://github.com/DMPRoadmap/roadmap/files/876151/Some.other.plan.Tuuli.DMP.pdf)

Diana

**Comment by vyruss** [comment]
This sounds suspiciously like #113 .Duplicate?

**Comment by dsisu** [comment]
I don't know whether this is ticket is a duplicate or not.

I think the Horizon2020 template has generated errors before. It is probably down to the fact that this template is in 3 parts and something in the html code doesn't flow correctly. **I emphasise again: the questions only reveal their html, not the answers.** I inserted tables and lists in some of my answers and they still downloaded correctly. This is why I believe there is something wrong with the way the template is constructed.

Ray suggested that the export function may not work but that wouldn't explain why the plan based on the TuuliDMP template downloaded correctly.

I would appreciate it if you would take a look at this asap. There have been too many errors on DMPTuuli recently and we don't want to look bad.

Thanks!

**Comment by briri** [comment]
Not sure which version of the code they are running, but see if app/views/plans/export.pdf.erb line 40 looks like this:
```ruby
   <h3><%= raw question.text %></h3>
```
I enjoyed your answers an the sample plan @dsisu! 🐔

**Comment by vyruss** [comment]
Thanks @briri, I updated the file on Tuuli. @dsisu can you/they check if it works?

**Comment by dsisu** [comment]
Thank you very much. That has fixed the error in the download. What is now happening is that the template displays html for questions *before* you edit the plan (or 'answer questions'). That appears to be happening to 'Initial DMP' section only. I'll insert a print screen here if I can.

![image](https://cloud.githubusercontent.com/assets/2138956/24494131/16ccb14e-1529-11e7-8735-93b728a23825.png)

**Comment by vyruss** [comment]
Does #349 fix this?

**Comment by jollopre** [comment]
This issue is for when the plan is exported as HTML. Note that the current codebase should display the question text correctly, i.e. without HTML markup (e.g. https://github.com/DMPRoadmap/roadmap/blob/development/app/views/plans/export.html.erb#L45). 

The issue #349, in contrast, fixes the question.text for when the plan is exported as docx.

**Comment by sjDCC** [comment]
The plan details summary on Tuuli still has html in the display but this has been removed from export
![capture](https://cloud.githubusercontent.com/assets/6169940/26553175/6d0484b4-4482-11e7-83b0-071096d9b492.PNG)

**Comment by sjDCC** [comment]
Will be superceded by roadmap code. Closing out
