### ISSUE TITLE
Allow org admins to view 'share plan' page

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2090]
Currently org admins can't view the 'share plan' tab to see who collaborators are on a plan. They shouldn't have edit rights to this, but like the main pages, it should be visible in read-only style if they have permissions to view the plan

**Comment by sjDCC** [comment]
I can't test this currently as I only have permission to view my own plans. From the 'plans' page on the admin interface, only my own plans are linked. They should all be accessible in read-only mode.

![Capture](https://user-images.githubusercontent.com/6169940/57641752-acc69c00-75ad-11e9-9d5a-95a486e84f00.PNG)

**Comment by xsrust** [comment]
I had the config wrong on -dev so org-admins cannot read plans.
Updated this now

**Comment by sjDCC** [comment]
Yay - looking good. Thanks @johnpinto1 Closing out
