### ISSUE TITLE
Amend footer in export to correct date

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2094]
The footer in the export misreads currently for DMPonline. The "the" should be removed and the date should be displayed in a way that work for both UK/US. ISO had been suggested but I think we should ensure the display reads well for end users.

@briri are you happy for us to write out the month. That should work for all use cases i.e.

"Created using [tool name]. Last modified 21 May 2018"
![Capture](https://user-images.githubusercontent.com/6169940/56268244-bd880d00-60e8-11e9-809d-1e1e4f552fbc.PNG)

**Comment by briri** [comment]
Yes, good idea @sjDCC.

**Comment by magdalenadrafiova** [comment]
Hiya all, 

THe date seems ok but it still shows 'the' 
![Amend footer in export to correct date #2094](https://user-images.githubusercontent.com/47178106/57528292-e2f3e980-7329-11e9-902f-f1ed14358842.PNG)

**Comment by johnpinto1** [comment]
Will correct that @magdalenadrafiova

**Comment by johnpinto1** [comment]
@magdalenadrafiova and @xsrust looks like this code is not deployed to server being tested. As the date should read.

**Comment by magdalenadrafiova** [comment]
Works perfectly now - my fault - I was testing through a wrong link 

![2094](https://user-images.githubusercontent.com/47178106/57529970-146eb400-732e-11e9-92ed-6a054ad1a856.PNG)

**Comment by sjDCC** [comment]
Perfect. Closing out
