### ISSUE TITLE
Issue:counter of questions answered is incorrect in the 'request feedback' 

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2095]
It has been reported that the progress bar the numbers do not display correctly, please see below: 

In the Initial DMP tab, there are no numbers over the blue progress bar (I make it 9/9 though):

![Blue progress bar](https://user-images.githubusercontent.com/47178106/56281659-1bc2e900-6105-11e9-854f-b079a54d568c.jpg)

In the Detailed DMP tab, the user has cleverly answered 40 of 31 questions J (I think it’s 31/31 – I guess the first counter added the previous 9)
![Progress bar - should be 31 from 31](https://user-images.githubusercontent.com/47178106/56281675-241b2400-6105-11e9-884b-88fa24c3ba47.jpg)

And in the Final review DMP section, it still says 40/31 though they haven’t answered any questions (0/31):
![Should be 0 from 31](https://user-images.githubusercontent.com/47178106/56281685-29786e80-6105-11e9-9e0f-47708740869a.jpg)

**Comment by sjDCC** [comment]
Number counts seem to be fixed now on DMPonline-test. Could you check and validate too please @mariapraetzellis @magdalenadrafiova 

Closing out

**Comment by magdalenadrafiova** [comment]
I started to create a plan and it was updating my answers as I was adding them. looks good to me

**Comment by xsrust** [comment]
Reopening this as we have yet to merge @briri's PR for it: #2244
