### ISSUE TITLE
Cannot edit Org details

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#210]
When I click on the Organization details tab in the admin area, I receive the error below:

![screen shot 2017-03-28 at 8 20 30 am](https://cloud.githubusercontent.com/assets/12703638/24413181/85bd595a-138f-11e7-8a55-708a0806d690.png)

**Comment by xsrust** [comment]
fixed in https://github.com/DigitalCurationCentre/roadmap/commit/57ae8a277e8333ef853741e6357226a3d93c0162

**Comment by xsrust** [comment]
and in https://github.com/DigitalCurationCentre/roadmap/commit/c51695a974a60a611202147003188571e0b2fdec

**Comment by xsrust** [comment]
a commit removing the depricated "attr_accessible" from the model for orgs has broken the functionality as it relies on the update_attributes function

Replacing with permitted params according to rails's strong parameters
https://github.com/rails/strong_parameters/

**Comment by xsrust** [comment]
solved the above in 
https://github.com/DigitalCurationCentre/roadmap/commit/7460fddc037ca09919e97fd652a1d1fbfaf82071

**Comment by stephaniesimms** [comment]
Working as expected
