### ISSUE TITLE
Cannot access admin, reference, language tabs

### ISSUE THREAD

**Issue by Ebrahim1010** [DMPRoadmap/roadmap#2104]
Hi Guys,

We have completed the migration successfully, we are now in the process of versioning.

When I sign in to the platform I cannot access the admin/superadmin, language or reference tabs.

Thanking you in advance!

**Comment by xsrust** [comment]
Hi @Ebrahim1010 

I'm glad to hear that.  What release have you got up to, and what browser are you using to test?
  It sounds like you're having issues with your asset-compilation for JavaScript. We had some issues recently which affected the output for IE.
Does `rake assets:precompile` complete without issues?

**Comment by Ebrahim1010** [comment]
Hi Sam, 

We've got to v2.0.0. 
I've tried it on Chrome, Firefox and Safari, no luck.
Yes it does complete without any issues

**Comment by xsrust** [comment]
If your planning on continuing upgrading through to v2.1.1 (and the v2.1.2 which will be packaged/tagged later today), then it's probably not worth trying to debug JS compile issues as we re-work the assets from webpack to webpacker.  There's also a fairly significant restructuring to the CSS, and the latest notes on the wiki detail these changes.

**Comment by Ebrahim1010** [comment]
Please point us to the Wiki pages because 1 Wiki page stipulates to run upgrade task v2_1_0 but doesn't exist so following the Wiki has brought about a few mixed feelings

**Comment by xsrust** [comment]
I think your talking about the release notes,
Your right, a quick look at `lib/tasks/upgrade.rake` shows there's a typo on that task and it's accidentally named `v2_1_9`
[Those release notes](https://github.com/DMPRoadmap/roadmap/releases/tag/v2.1.0) do say to avoid it however, and to refer to the [following release](https://github.com/DMPRoadmap/roadmap/releases/tag/v2.1.1) which reccomends you run the, now renamed, task.

Try following the instructions there (and having a look at the notes linked from v2.1.1 about how we've re-factored the branding)
Finally, the notes in the [wiki page on installation](https://github.com/DMPRoadmap/roadmap/wiki/Installation#installation) mention running `rake webpacker:yarn_install`  You'll need to ensure you do this to be able to compile assets from v2.1.1 onward

**Comment by Ebrahim1010** [comment]
01465524@devubudmp002:/opt/roadmap/lib/assets$ rake webpacker:yarn_install

(in /opt/roadmap)

rake aborted!

Don't know how to build task 'webpacker:yarn_install' (see --tasks)

(See full trace by running task with --trace)

it seems there isn't a webpacker task for rake

**Comment by xsrust** [comment]
Have you moved to a release where `webpacker` is in your `Gemfile`?
Which one are you up to now?
Did you `bundle install` to ensure that the gem is installed?
Try `rake --tasks` to see which tasks are available

**Comment by Ebrahim1010** [comment]
Webpacker isn't in my Gemfile.

[12:56] Norman Smith
    


rake about                                                       # List versions of all Rails frameworks and the environment

rake assets:clean[keep]                                          # Remove old compiled assets

rake assets:clobber                                              # Remove compiled assets

rake assets:environment                                          # Load asset compile environment

rake assets:precompile                                           # Pre-compile assets for production

rake cache_digests:dependencies                                  # Lookup first-level dependencies for TEMPLATE (like messages/show or comments/_comment.html)

rake cache_digests:nested_dependencies                           # Lookup nested dependencies for TEMPLATE (like messages/show or comments/_comment.html)

rake clean                                                       # Remove any temporary products

rake clobber                                                     # Remove any generated files

rake clobber_rdoc                                                # Remove RDoc HTML files

rake contact_us:copy_locales                                     # Copy only locale files (part of install, but useful for updates when only assets are needed)

rake contact_us:copy_views                                       # Copy only view files (part of install, but useful for updates when only assets are needed)

rake contact_us:install                                          # Install contact_us

rake data_cleanup:clean_invalid_records                          # Clean invalid records on the database

rake data_cleanup:find_invalid_records                           # Check each record on the DB is valid and report

rake data_cleanup:find_known_invalidations                       # Check records for validation errors

rake db:create                                                   # Creates the database from DATABASE_URL or config/database.yml for the current RAILS_ENV (use db:create:all to create all databases in the config). Without RAILS_ENV ...

rake db:drop                                                     # Drops the database from DATABASE_URL or config/database.yml for the current RAILS_ENV (use db:drop:all to drop all databases in the config). Without RAILS_ENV it def...

rake db:fixtures:load                                            # Load fixtures into the current environment's database

rake db:migrate                                                  # Migrate the database (options: VERSION=x, VERBOSE=false, SCOPE=blog)

rake db:migrate:status                                           # Display status of migrations

rake db:populate                                                 # Fill database with sample data

rake db:rollback                                                 # Rolls the schema back to the previous version (specify steps w/ STEP=n)

rake db:schema:cache:clear                                       # Clear a db/schema_cache.dump file

rake db:schema:cache:dump                                        # Create a db/schema_cache.dump file

rake db:schema:dump                                              # Create a db/schema.rb file that is portable against any DB supported by AR

 

​[12:56] Norman Smith
    
rake db:schema:load                                              # Load a schema.rb file into the database

rake db:seed                                                     # Load the seed data from db/seeds.rb

rake db:setup                                                    # Create the database, load the schema, and initialize with the seed data (use db:reset to also drop the database first)

rake db:structure:dump                                           # Dump the database structure to db/structure.sql

rake db:structure:load                                           # Recreate the databases from the structure.sql file

rake db:version                                                  # Retrieves the current schema version number

rake doc:app                                                     # Generate docs for the app -- also available doc:rails, doc:guides (options: TEMPLATE=/rdoc-template.rb, TITLE="Custom Title")

rake factory_bot:lint                                            # Verify that all FactoryBot factories are valid

rake gettext:add_language[language]                              # add a new language

rake gettext:find                                                # Update pot/po files

rake gettext:pack                                                # Create mo-files

rake gettext:po_to_json                                          # Convert PO files to JS files

rake gettext:store_model_attributes                              # write the model attributes to <locale_path>/model_attributes.rb

rake initialize_data:rda_ques                                    # Add RDA Question Type

rake log:clear                                                   # Truncates all *.log files in log/ to zero bytes (specify which logs with LOGS=test,development)

rake logos:resize_all                                            # Resize all of the logos based on the settings in `models/org.rb`

rake middleware                                                  # Prints out your Rack middleware stack

rake migrate:cleanup                                             # perform all post-migration tasks

​[12:56] Norman Smith
    


rake migrate:fix_languages                                       # replaces languages in incorrect formats and seeds all correct formats

rake migrate:init_plan_visibility                                # Initialize plans.visibility to the default specified in application.rb

rake migrate:move_orcids                                         # Move old ORCID from users table to user_identifiers

rake migrate:move_shibs                                          # Move old Shibboleth Ids from users table to user_identifiers

rake migrate:org_target_url_to_links                             # convert orgs.target_url to JSON array

rake migrate:permissions                                         # TODO

rake migrate:plan_data_contacts                                  # Move old plans.data_contact to data_contact_email and data_contact_phone

rake migrate:prep_for_1_0                                        # migrate to 1.0

rake migrate:remove_duplicate_annotations                        # remove duplicate annotations caused by bug

rake migrate:seed                                                # seed database with default values for new data structures

rake migrate:setup                                               # perform entire data migration

rake migrate:single_published_template                           # enforce single published version for templates

rake migrate:to_04                                               # migrate to 0.4

rake notes                                                       # Enumerate all annotations (use notes:optimize, :fixme, :todo for focus)

rake notes:custom                                                # Enumerate a custom annotation, specify with ANNOTATION=CUSTOM

rake notifications:create_types                                  # Create some notifications types

rake rails:template                                              # Applies the template supplied by LOCATION=(/path/to/template) or URL

rake rails:update                                                # Update configs and some other initially generated files (or use just update:configs or update:bin)

rake rdoc                                                        # Build RDoc HTML files

rake rerdoc                                                      # Rebuild RDoc HTML files

rake routes                                                      # Print out all defined routes in match order, with names

rake secret                                                      # Generate a cryptographically secure secret key (this is typically used to generate a secret for cookie sessions)

rake spec                                                        # Run all specs in spec directory (excluding plugin specs)

rake spec:features                                               # Run the code examples in spec/features

rake spec:lib                                                    # Run the code examples in spec/lib

rake spec:mixins                                                 # Run the code examples in spec/mixins

rake spec:models                                                 # Run the code examples in spec/models

rake spec:requests                                               # Run the code examples in spec/requests

rake spec:services                                               # Run the code examples in spec/services

rake stat:build                                                  # Build all stats

 

​[12:56] Norman Smith
    
rake stat:create:created_plan                                    # Creates created plan stats for every org since they joined

rake stat:create:joined_user                                     # Creates joined user stats for every org since they joined

rake stat:create_last_month:created_plan                         # Creates created plan stats for today's last month for every org

rake stat:create_last_month:joined_user                          # Creates joined user stats for today's last month for every org

rake stats                                                       # Report code statistics (KLOCs, etc) from the application or engine

rake templates:clean_up_excess_versions                          # Cleanup excess versions

rake templates:clean_up_published_flags                          # Cleanup published flags

rake templates:set_dirty_flags                                   # Initializes the dirty flag on templates

rake test                                                        # Runs all tests in test folder

rake test:all                                                    # Run tests quickly by merging all types and not resetting db

rake test:all:db                                                 # Run tests quickly, but also reset db

rake test:db                                                     # Run tests quickly, but also reset db

rake time:zones:all                                              # Displays all time zones, also available: time:zones:us, time:zones:local -- filter with OFFSET parameter, e.g., OFFSET=-6

rake tmp:clear                                                   # Clear session, cache, and socket files from tmp/ (narrow w/ tmp:sessions:clear, tmp:cache:clear, tmp:sockets:clear)

rake tmp:create                                                  # Creates tmp directories for sessions, cache, sockets, and pids

rake tomdoc:app                                                  # Builds documentation in the ./doc directory

rake tomdoc:clear                                                # Removes the docs from the ./doc directory

rake tomdoc:open                                                 # Builds documentation in the ./doc directory

rake translatable:add_language_to_db[code,name,is_default]       # Add the specified language to the database

rake translatable:diffs[code]                                    # Find diffs between main app.pot and specified locale

rake translatable:find[domain]                                   # Find all translatable text and update all pot/po files

rake translatable:remove_language_from_db[code]                  # Remove the specified language from the database

rake upgrade:add_default_values_v2_0_0                           # Apply default column values for v2.0.0

rake upgrade:add_missing_token_permission_types                  # Add the missing token_permission_types

rake upgrade:add_other_org                                       # Add the 'other' org if it is not present

rake upgrade:add_versioning_id_to_templates                      # Add verisoning_id to published Templates

rake upgrade:check_for_guidance_multiple_themes                  # The system now only allows for one theme selection per guidance, so check for violations

rake upgrade:check_org_contact_emails                            # Org.contact_email is now required, sets any nil values to the helpdesk email defined in branding.yml

rake upgrade:fix_question_formats                                # Add the missing formattype to the question_formats table

rake upgrade:normalize_language_formats                          # Update Language abbreviations to use ISO format

rake upgrade:remove_admin_preferences                            # Remove admin preferences

rake upgrade:remove_duplicate_answers                            # Remove Duplicate Answers

rake upgrade:remove_duplicated_customised_template_versions      # Remove duplicated customised template versions

rake upgrade:remove_duplicated_non_customised_template_versions  # Remove duplicated non customised template versions

rake upgrade:remove_duplicated_template_versions                 # Remove duplicated template versions

rake upgrade:set_org_links_defaults                              # Set all orgs.links defaults

rake upgrade:set_plan_complete                                   # Sets completed for plans whose no

rake upgrade:set_template_links_defaults                         # Set all template.links defaults

rake upgrade:set_template_visibility                             # Set all funder templates (and the default template) to 'public' visibility and all others to 'organisational'

rake upgrade:single_guidance_for_theme                           # Concatenate Guidance which refers to the same Theme as a result of merges

rake upgrade:stats_api_org_admin                                 # Allow Statistics API Usage for Org Admin Users

rake upgrade:theme_deduplicate_questions                         # Deduplicate multiple associations resulting from Theme merges

rake upgrade:theme_delete_deprecated                             # Remove deprecated themes

rake upgrade:theme_new_themes                                    # Create new Theme list

rake upgrade:theme_remove_migrated                               # Delete migrated themes and their associations

rake upgrade:theme_transform                                     # Transform existing themes and their associations into new theme list

rake upgrade:v0_3_3                                              # Bug fixes for version v0.3.3

rake upgrade:v1_0_0                                              # Upgrade to 1.0

rake upgrade:v1_1_2                                              # Upgrade to v1.1.2

rake upgrade:v2_0_0_part_1                                       # Upgrade to v2.0.0: Part 1

rake upgrade:v2_0_0_part_2                                       # Upgrade to v2.0.0: Part 2

 


​

**Comment by xsrust** [comment]
well webpacker would need to be in the Gemfile.

See the other two questions[ asked in my previous comment](https://github.com/DMPRoadmap/roadmap/issues/2104#issuecomment-485763079).
Given you don't have any upgrade tasks past v2.0.0, that would suggest to me that your on the wrong version of the code.  You need to upgrade through to v2.1.1 in order to use webpacker.  Instructions to migrate from v2.0.0 forward can be found in the [releases](https://github.com/DMPRoadmap/roadmap/releases)

Also, triple back-tics wrapping the block can be used to format code more concisely in case you need to post code or a stack-trace again.  They help with readability, ex:
```
def example
    return "formatted"
```

**Comment by Ebrahim1010** [comment]
Hi Sam,

Thanks again! 
We Running into issues now.

We can't seem to run the upgrade task
01465524@devubudmp002:/opt/roadmap$ sudo rake upgrade:v2_1_0

rake aborted!

Don't know how to build task 'upgrade:v2_1_0' (see --tasks)

/var/lib/gems/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'

(See full trace by running task with --trace)

01465524@devubudmp002:/opt/roadmap$

--------
Neither the upgrade to v2.1.1

01465524@devubudmp002:/opt/roadmap$ sudo rake upgrade:v2_1_2

rake aborted!

Don't know how to build task 'upgrade:v2_1_2' (see --tasks)

/var/lib/gems/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'

(See full trace by running task with --trace)

**Comment by xsrust** [comment]
Hey,
It sounds like you've pulled the code from the wrong release if those tasks don't exist.  In particular, it looks like you've pulled the tag for `v2.1.0` [which has a typo in the rake task and advises to skip to the next release and re-run the task](https://github.com/DMPRoadmap/roadmap/releases/tag/v2.1.0). That would explain the lack of existance of either of those tasks.
If you let me know which version of code you've pulled locally, that would help me debug from where you are at.

Alternatively, you can run the following which should be able to upgrade your service.
Note that the following assumes you've successfully migrated up to v2.0.0 and created/run your scripts to cleanup your data:
```
$ git checkout tags/v2.1.1
$ rake upgrade:v2_1_0 
$ git checkout tags/v2.1.2
$ rake upgrade:v2_1_2
$ rake stat:build
```

**Comment by Ebrahim1010** [comment]
01465524@devubudmp002:/opt/roadmap$ sudo git checkout tags/v2.1.1

error: pathspec 'tags/v2.1.1' did not match any file(s) known to git.

01465524@devubudmp002:/opt/roadmap$ sudo git checkout tags/v2.1.0

error: pathspec 'tags/v2.1.0' did not match any file(s) known to git.

01465524@devubudmp002:/opt/roadmap$ sudo git checkout tags/v2.0.0

HEAD is now at f0d0659... fixed issue with args in translatable:find (#1963)

01465524@devubudmp002:/opt/roadmap$

it seems there's only a checkout for v2.0.0

**Comment by Ebrahim1010** [comment]
01465524@devubudmp002:/opt/roadmap$ git status

HEAD detached at v2.0.0

Untracked files:

  (use "git add <file>..." to include in what will be committed)


 


        .browserslistrc

        Gem

        app/javascript/

        babel.config.js

        bin/webpack

        bin/webpack-dev-server

        config/branding.yml.old

        config/webpack/

        config/webpacker.yml

        db/migrate/.20161206122926_add_foreign_keys.rb.swp

        lib/data_cleanup/rules/

        old_modules/

        package.json

        postcss.config.js

        yarn.lock


 


nothing added to commit but untracked files present (use "git add" to track)

**Comment by xsrust** [comment]
Interesting,
It looks like you've pulled from v2.0.0
You should be able to checkout the other tags.
Try `git fetch --all` before pulling the tags down
This will refresh all info from the remote

Either way, you're currently at the v2.0.0 and you'll need to follow through the rest of the upgrades from that release

**Comment by Ebrahim1010** [comment]
01465524@devubudmp002:/opt/roadmap$ git tag

v0.2.1

v0.2.10-beta

v0.2.11-beta

v0.2.12-beta

v0.2.13-beta

v0.2.14

v0.2.2

v0.2.3

v0.2.4

v0.2.5

v0.2.6

v0.2.7

v0.2.8-beta

v0.2.9-beta

v0.3.0

v0.3.1

v0.3.2

v0.3.3

v0.3.4

v0.3.5

v0.3.6

v0.3.7

v0.3.8

v1.0.0

v1.0.1

v1.0.2

v1.0.3

v1.0.4

v1.0.5

v1.1.0

v1.1.1

v1.1.2

v1.1.3

v1.1.4

v2.0.0

**Comment by Ebrahim1010** [comment]
01465524@devubudmp002:/opt/roadmap$ git branch

* (HEAD detached at v2.0.0)

  dmponline4_upgrade_step1

  dmponline4_upgrade_step2

  dmponline4_upgrade_step3

  master


-so I can't move past v2.0.0 according to the tags I see

**Comment by xsrust** [comment]
hi @Ebrahim1010 

You've made a fork of the DMPRoadmap/roadmap repository, which is a copy at the time you forked.
As you say, [your fork](https://github.com/norman-smith/roadmap/releases) does not have any tags past 2.0.0.  I'm assuming that this is your problem, but please double check that your fork is your remote.

Assuming your remote is your fork of the roadmap repo, Try to re-sync your fork (master branch) with DMPRoadmap/roadmap, or add DMPRoadmap/roadmap as a remote to your local git.
