### ISSUE TITLE
Cannot share plan

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#211]
When I click to Share plans I receive the error below:

![screen shot 2017-03-28 at 8 27 31 am](https://cloud.githubusercontent.com/assets/12703638/24413525/8a34bdc4-1390-11e7-91b3-400388d65fbf.png)

**Comment by briri** [comment]
Simple fix. Just removed redundant `=>` from raw _('<p>You can ...') % {application_name: => ...`

**Comment by xsrust** [comment]
I can confirm that the share plan page now loads. 

The functionality of this page is bugged as described in #219 and #220

**Comment by stephaniesimms** [comment]
Share plan button and functionality is working as expected, but creating a new ticket to reflect problem with making changes to existing permissions
