### ISSUE TITLE
Email notification for owners and co-owners of the plan 

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2110]
When a reviewer sends a notification/feedback to owners and co-owners of the plan on DMPonline, it is not clear whether the co-owner receives the email too for the reviewer. Could the template email to co-owners include also the following message:

You are receiving this notification as you were made a co-owner of this DMP

**Expected behaviour:**
It is not clear who receives reviewer notification after the review has been sent. It will be helpful to include the template email to co-owners saying: You are receiving this notification as you were made a co-owner of this DMP.

**Comment by sjDCC** [comment]
See also #2109 which mentions email notifications. @magdalenadrafiova fix here is much simpler. Just tell co-owners why they are receiving it

**Comment by magdalenadrafiova** [comment]
@sjDCC - thank you - shall I close this ?

**Comment by sjDCC** [comment]
No, I would leave this one open as it's a simpler fix. The devs can ignore the request for email text to make amendments in #2109

**Comment by magdalenadrafiova** [comment]
Close out - rolled into #2019
