### ISSUE TITLE
Creation of tooltip on share tab - explanation of the permissions (co-owner, editor, read only)

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2111]
When the owner of the plan creates co-owner of the project (essentially people with the ability to share the plan with others) it is not clear whether editors and read-only receives any notifications when the reviewer sends e.g. feedback on the plan. It would be useful for the users to explain the permissions and practical implications so the owner of the plan will know which role to choose for people who collaborate with her/him on the project. 

Would it be possible to create e.g. a tooltip on the share tab by the choice of permissions? 

Co-owner: Has admin-rights to the plan (can invite other users, view the plan, answer questions, or comment)
Editor: Has edit-rights to the plan (can view the plan, answer questions, or comment)
Read Only: Has read-rights to the plan(can view the plan or comment)

**Comment by magdalenadrafiova** [comment]
@pherterich @mariapraetzellis I am closing this as I think with reworking the plans page we will have the 'contributros' or collaborators page where certain defintions/permisions will be defined

**Comment by xsrust** [comment]
Re-opening this one as the contributors/collaborators page provides maDMP functionality and attribution via the CREDiT taxonomy, while the share_plan page will continue to provide the access-rules for our plans.

**Comment by xsrust** [comment]
That being said, it looks like the tool tips have already been implemented so this can remain closed

![share_plan_tooltip](https://user-images.githubusercontent.com/7352616/86911244-e8f27f80-c112-11ea-8d9e-abc170122421.png)
