### ISSUE TITLE
Employ designer for layout of Usage page

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#2114]
Please complete the following fields as applicable:

Usage page is an important one for org admins. The overall design is very poor. We added new features, new reports and inserted new buttons for them wherever we could easily fit them on the screen at the time, which is understandable. We need to re-order items on the screen too 'download global statistics' is a very prominent top right whereas the main purpose of the page is intended for org statistics (and this makes people wonder what 'global' means in this context). This will require some development work to implement the design. I could take the lead on this by approaching a designer. A designer could also advise on how to position and display the plan per template chart.

**Expected behaviour:**

Usage page should be more user friendly and look more like the rest of the screens - plans, templates, guidance.

**Actual behaviour:**

Page has grown organically, with elements added to it as and when completed.

**Steps to reproduce:**

View Usage page and compare against various screens - Users, Plans, Templates, Guidance.

**Comment by sjDCC** [comment]
Closed as reworked usage dashboard
