### ISSUE TITLE
Add additional validations to Template publish action

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#2115]
Got an error when trying to load the edit plans page for a template which has any of the following:

1) Template with no phases
2) Phase with no sections
3) Section with no questions

We should add validation to prevent this sort of template from being published in the future.

Error thrown by: `/opt/src/dmponline/app/models/plan.rb`line 198 in `load_for_phase`
Error Text: `NoMethodError: undefined method `template' for nil:NilClass`

**Comment by briri** [comment]
agreed better to just prevent publication in the first place

**Comment by sjDCC** [comment]
I just tried this on DMPonline-test and could edit and publish an existing template with bad data (new section with no question). I also tried creating a new template and could publish it with no phases, sections or questions

**Comment by sjDCC** [comment]
Just realised I should have been testing on DMPonline-dev. Doh!

All works perfectly. Thanks @xsrust Closing out
