### ISSUE TITLE
Date range restriction for Statistics API breaks on empty/invalid date passed

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#2116]
If an empty date is passed, this should handle the error and default to open-ended search.
If an invalid date is passed, this should inform the user.

**Comment by xsrust** [comment]
This is specifically affecting the new-plans org-admin usage dashboard

**Comment by magdalenadrafiova** [comment]
works well 
![image](https://user-images.githubusercontent.com/47178106/73654262-24c87b00-4683-11ea-813f-2bc1f0e0f472.png)
