### ISSUE TITLE
Roles controller throws error when inviting a user with a capital letter

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#2117]
Devise is configured (on DMPonline) to support email case-insensitivity.

The implimentation of this is to downcase the email before saving.

When the roles-controller looks for the email(with capitals) it will not find the user and errors.

**Comment by magdalenadrafiova** [comment]
Hiya Sam, 

This one seems to be working - but it always jumps first to the 'page unavailable' after I typed your email address with capitals, and then when I refresh I can see it was sent to you. 

![2117](https://user-images.githubusercontent.com/47178106/57529443-cefdb700-732c-11e9-8627-47636907dc81.PNG)

![collaborators - 2117](https://user-images.githubusercontent.com/47178106/57529479-e8066800-732c-11e9-9993-f1f752fcc4ea.PNG)

**Comment by magdalenadrafiova** [comment]
![2117 - sharing plan with capital letters](https://user-images.githubusercontent.com/47178106/57530299-da51e200-732e-11e9-8541-9fc1438baf9b.PNG)

works perfectly :)

**Comment by sjDCC** [comment]
Works for me too. Closing out
