### ISSUE TITLE
Template Export Does not render useful error messaging for bad id's

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#2118]
Please complete the following fields as applicable:

**Expected behaviour:**
- User gets a flash-message to let them know the id they have asked to download is bad
**Actual behaviour:**
- User gets a generic 404
**Steps to reproduce:**
pass a non-existant template_id to the template-export action of the public pages

**Comment by sjDCC** [comment]
Now get error message that I'm not authorised to export that template. Looks good. Closing out
