### ISSUE TITLE
Usage Dashboard Plans by template broken on 9,12 months

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#2119]
Please complete the following fields as applicable:

**Expected behaviour:**
Dashboard should update for the 12 and 9 months ago options
**Actual behaviour:**
Dashboard does not update
**Steps to reproduce:**
Go to usage dashboard and change the range for the plans_by_template to 9 or 12 months.

Issue currently happening at line 24 in `statcreatedplan.rb`
```
24    if self.details.present?
25      by_template = self.details["by_template"]
26    end
```

**Comment by magdalenadrafiova** [comment]
![image](https://user-images.githubusercontent.com/47178106/73653714-bf27bf00-4681-11ea-9595-f20b2211bfc5.png)

it works well for November 2019 and for the last 12 months but something is happening when I select 9 months and compare the data - in the table it says there were 14 but when I hover with the mouse below it only shows 13 

![image](https://user-images.githubusercontent.com/47178106/73654086-b08dd780-4682-11ea-826b-5f77208dfafa.png)

![image](https://user-images.githubusercontent.com/47178106/73654120-c9968880-4682-11ea-9bff-f39f6de2fc86.png)

**Comment by mariapraetzellis** [comment]
Seeing a similar issue Magdalena mentioned above.

**No. plans during last year for May 19 gives 8 plans** 
<img width="1127" alt="Screen Shot 2020-02-03 at 3 21 16 PM" src="https://user-images.githubusercontent.com/27511575/73699593-14bb9600-4699-11ea-8acb-0b17cf75dca9.png">

**No. plans by template gives 7 plans for May 19**
<img width="1135" alt="Screen Shot 2020-02-03 at 3 23 32 PM" src="https://user-images.githubusercontent.com/27511575/73699704-5a785e80-4699-11ea-91b8-42b774e88c52.png">

Also, **can we make the default view for the chart to display the last 12 months**?  Right now it is the Last Month and generally gets a "No Data To Display" message.

**Comment by xsrust** [comment]
The "No Data  to  Display" may be  more to our dev server being out-of-sync with the live data.  
I've made the change now and created a PR.  I also  reversed the order  of the options in the select-box.

That being said,  it may make more sense to just remove the  select-box/endpoint, since we're  always showing the maximum length, and it'd be pointless to scope to fewer months as the data is already on the  page.
https://github.com/DMPRoadmap/roadmap/pull/2378

**Comment by sjDCC** [comment]
We should leave the options open as for some orgs with lots of plans it's hard to read the data on 12 months

**Comment by sjDCC** [comment]
This is defaulting fine and looks ok, but there's not much recent data on -dev to test with.

Closing out

**Comment by mariapraetzellis** [comment]
Looks good to me as well.

**Comment by magdalenadrafiova** [comment]
This works well now - I logged in and had my org set up as University of Manchester and the numbers were consistent. CLosing this
