### ISSUE TITLE
Guidance administration not accessible after deleting a question linked to a guidance.

### ISSUE THREAD

**Issue by benjaminfaure** [DMPRoadmap/roadmap#213]
In DMPOnline V4

**How to reproduce :** 
- In the guidance administration, edit a guidance, select "by question" in the "Should this guidance apply : " dropdown and choose a specific question in a template.
- Delete this question in the specific template>phase>version>section.
- Go back to the guidance administration should cause the following error : 
```
An ActionView::Template::Error occurred in guidances#admin_index:

  undefined method 'text' for nil:NilClass
  app/views/guidances/admin_index.html.erb:133:in 'block in _app_views_guidances_admin_index_html_erb__365803286381586758_45327620'
```
**Cause :** 
It seems that the method deleting the question from the database doesn't remove the question_id from the guidance linked to this question, causing this bug.

**Comment by briri** [comment]
closing this since the guidance in the Admin -> Guidances section is no longer associated with specific questions. @benjaminfaure please reopen if its still an issue with the current codebase
