### ISSUE TITLE
Typeahead on Project Details for Research Grant ID

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2134]

**Comment by sjDCC** [comment]
This works well, thanks @Bodacious 

I have a few suggestions for usability and to fit use cases where the API doesn't apply:

1. Can we enter some text in the box as a prompt so people know it's a typeahead, or a help note adjacent to it like on the 'create plan' wizard. See example from Zenodo and DMPonline page
![Capture](https://user-images.githubusercontent.com/6169940/57638953-c31d2980-75a6-11e9-8a12-fb864d79dad7.PNG)
![Picture2](https://user-images.githubusercontent.com/6169940/57640315-1a70c900-75aa-11e9-8d62-7bffbd4f7b8f.png)

2. It would be better for the grant ID to be placed in the box rather than below it. Can the typeahead box be placed above/below and labelled as a way to find / select the grant ID instead of replacing this field? 
![Capture](https://user-images.githubusercontent.com/6169940/57640267-f1503880-75a9-11e9-892f-e86462c17247.PNG)

3. It should be possible to clear the entry if desired. You can delete the text but this does not remove the associated grant ID. Perhaps an X adjacent to the box to clear the entry like on other pages?
![Capture](https://user-images.githubusercontent.com/6169940/57639129-1f804900-75a7-11e9-8d3a-51e4add74763.PNG)
![Capture](https://user-images.githubusercontent.com/6169940/57640361-4724e080-75aa-11e9-82b4-be915e6c2caf.PNG)

4. Does the API data filter grant names by funder? I ask to understand whether a different subset of search options is shown for EC as opposed to Wellcome Trust for example. It doesn't seem so. I don't think all funders are covered by the API so we need this to be an option rather than the only way to answer.

5. It should also be possible for users to enter a value not available in the API as not all funders are covered by it. I just tried to enter a random number and it saved as the nearest entry in the API. Can we give both routes somehow?

**Comment by magdalenadrafiova** [comment]
works well for me - 
![2134-typeahead on project details-16052019](https://user-images.githubusercontent.com/47178106/57843579-70ba5380-77c6-11e9-9aef-43a1348749a1.PNG)

**Comment by Bodacious** [comment]
Hi @sjDCC 

I've implemented 1,2,3 as requested above. These changes should now support point 5.

Re: point 4, not as far as I can tell. The narrowest scope we can filter is all of the H2020 on the API.

The API doesn't provide any more info than the description. Here's an example of a record from the API:

```<pair>
<displayed-value>
115797 - INNODIA - Translational approaches to disease modifying therapy of type 1 diabetes: an innovative approach towards understanding and arresting type 1 diabetes – Sofia ref.: 115797
</displayed-value>
<stored-value>info:eu-repo/grantAgreement/EC/H2020/115797/EU</stored-value>
</pair>```

We effectively get a URI, and a long string with the description. In the code, I pluck out the ID, in this case "115797" to make the code easier.

Is there another marker there that we could filter by?

Here is the full URL:
https://api.openaire.eu/projects/dspace/H2020/ALL/ALL

**Comment by sjDCC** [comment]
Hi @Bodacious Updated version looks great - thanks.

Is it possible to set this so it only shows when the H2020 template is being used? The projects listed are all EC H2020 ones so it's not relevant to show for AHRC, BBSRC plans etc

We should also add a help icon to explain where this content comes from. Suggested text:
"This list shows projects supported by the European Commission"

**Comment by sjDCC** [comment]
This looks great and filters perfectly now. Thanks @Bodacious Closing out
