### ISSUE TITLE
Wrong affiliation for default template

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2135]
When testing the Metadata Standards Directory work on DMPonline-dev I adjusted the default DCC template. This belongs to DCC but the text under plan details is showing incorrectly.
![weird](https://user-images.githubusercontent.com/6169940/57642430-34f97100-75af-11e9-9280-1c5c8847800f.PNG)

Everything is correct on DMPonline live site but worth ensuring this isn't a bug which will be deployed.

**Comment by johnpinto1** [comment]
@sjDCC Not sure if this is still an issue. On https://dmponline-test.dcc.ac.uk/ I created a plan with the **"DCC Template"**  It had _This plan is based on the "DCC Template" template provided by Digital Curation Centre.
![Selection_039](https://user-images.githubusercontent.com/8876215/60281237-7a25f800-98fc-11e9-81d9-20fd6fffde7b.png)
_

**Comment by sjDCC** [comment]
Can't replicate this now either so closing out
