### ISSUE TITLE
Cannot export plan as PDF

### ISSUE THREAD

**Issue by Ebrahim1010** [DMPRoadmap/roadmap#2139]
Hi,

I cannot export my plan as PDF.
This is the error: Processing by PlanExportsController#show as PDF

  Parameters: {"utf8"=>"✓", "export"=>{"form"=>"true", "question_headings"=>"true", "unanswered_questions"=>"true", "formatting"=>{"font_face"=>"Arial, Helvetica, Sans-Serif", "font_size"=>"10", "margin"=>{"top"=>"25", "bottom"=>"20", "left"=>"12", "right"=>"12"}}}, "phase_id"=>"1175", "button"=>"", "plan_id"=>"821"}

***************WICKED***************

  Rendered shared/export/_plan_styling.erb (0.5ms)

  Rendered shared/export/_plan.erb (97.8ms)

  Rendered plan_exports/show.erb (104.7ms)

Completed 500 Internal Server Error in 317ms (ActiveRecord: 74.8ms)

 

RuntimeError (Bad wkhtmltopdf's path: /var/lib/gems/2.4.0/gems/wkhtmltopdf-binary-0.12.4/bin/wkhtmltopdf_linux_x64):

  app/controllers/plan_exports_controller.rb:76:in `show_pdf'

  app/controllers/plan_exports_controller.rb:44:in `block (2 levels) in show'

  app/controllers/plan_exports_controller.rb:39:in `show'

Thank you

**Comment by xsrust** [comment]
The runtime error you got:
> RuntimeError (Bad wkhtmltopdf's path: /var/lib/gems/2.4.0/gems/wkhtmltopdf-binary-0.12.4/bin/wkhtmltopdf_linux_x64):

Would suggest that your rails app cannot find the wkhtmltopdf binary.
It's looking for it at `/var/lib/gems/2.4.0/gems/wkhtmltopdf-binary-0.12.4/bin/wkhtmltopdf_linux_x64`.

**Comment by Ebrahim1010** [comment]
Thank you!
