### ISSUE TITLE
DMPonline Logo

### ISSUE THREAD

**Issue by Ebrahim1010** [DMPRoadmap/roadmap#2145]
Hi Guys,

![image](https://user-images.githubusercontent.com/47170940/58332145-e8c5f080-7e3a-11e9-8ae4-50181e5f0e40.png)

How do I remove the Roadmap logo? I want to replace it with the DMPonline logo.

Thanks

**Comment by xsrust** [comment]
Hi. 

See https://github.com/DMPRoadmap/roadmap/wiki/Branding#images for instructions on how to replace any of the images we use in the project

**Comment by Ebrahim1010** [comment]
Hi Sam,

Thank you for this information. 

I want to use the DMPonline logo at the top and place my Institutional logo at the bottom next to DCC.

Is this an option, if so can you send me the DMPonline logo that's on the DCC's DMPonline website?

**Comment by sjDCC** [comment]
Hi @ebrahim1010 DMPonline is a registered trademark so we prefer people us a different name for their own instances. 

We certainly appreciate acknowledgement of the open source codebase. In the past people have done a footer saying something like "Powered by [DMPonline logo]"

We can provide the file for this purpose. Just tell us where to send it

Hope that helps

**Comment by Ebrahim1010** [comment]
Hi @sjDCC thank you very much.
Please send it to my email: yaqub.ebrahim@uct.ac.za

Thank you

**Comment by Ebrahim1010** [comment]
Hi Sarah,

Please can you send me the DMPonline Logo

Thank you

**Comment by sjDCC** [comment]
Hi

Since you're using the DMPRoadmap codebase it's best to credit that not DMPonline specifically. 

Here's the logo

![roadmap-logo](https://user-images.githubusercontent.com/6169940/59866102-9b2d9c80-9382-11e9-85c9-277aa95d3dd9.png)
