### ISSUE TITLE
Replacing Attr_accessible with permitted params

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#215]
In rails 4, the old `attr_accessible` syntax became depricated and it's functionality replaced with [Strong Parameters](https://github.com/rails/strong_parameters/).  
This functionality is allowed in our application by the gem [protected_attributes](https://github.com/rails/protected_attributes), which will stop being supported as of rails 5.

In preparation for this, we should remove the `attr_accessible` from the models, and add strong parameters to any controllers which do an `record.update_attributes(params)`.

**Comment by briri** [comment]
duplicate of #100
