### ISSUE TITLE
Versioning of templates

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2157]
When an institutions publish a template, and few days later they change it and publish again - it is very difficult to see at the front end - which version of the template is being used by which users. 

**Expected behaviour:**
Expose the version of the template if possible. Add possibly version number and date when that template was created? It will be good to know for the administrators which version of which template is being used by the users. 

**Actual behaviour:**

**Steps to reproduce:**

**Comment by johnpinto1** [comment]
@magdalenadrafiova @sjDCC Is this what your looking for. Note the first template version is 0.
![Selection_030](https://user-images.githubusercontent.com/8876215/60173996-f8ed3900-9807-11e9-84c0-914e315d5b43.png)
![Selection_031](https://user-images.githubusercontent.com/8876215/60174021-060a2800-9808-11e9-9b6f-5bcbdd44a925.png)

**Comment by sjDCC** [comment]
Yes, this works @johnpinto1 It would be good to add the published date too e.g.

"Template version 1, published on 10 July 2018"

**Comment by magdalenadrafiova** [comment]
Looks good - thanks @johnpinto1 Closing out
