### ISSUE TITLE
How to display usage stats on home page

### ISSUE THREAD

**Issue by Ebrahim1010** [DMPRoadmap/roadmap#2162]
How do I display my usage stats on the home page like this:
<img width="783" alt="Screen Shot 2019-06-18 at 11 54 06" src="https://user-images.githubusercontent.com/47170940/59672537-f5323480-91bf-11e9-8adb-1bfcc63ce3e8.png">

Currently my front page looks like this:
<img width="774" alt="Screen Shot 2019-06-18 at 11 55 54" src="https://user-images.githubusercontent.com/47170940/59672618-1abf3e00-91c0-11e9-8316-be4d44e34a28.png">

Thank you

**Comment by xsrust** [comment]
Hi @Ebrahim1010 

To do this, or any other changes to pages, you can override the views which are used to render them.  for more detail on how to do this, [checkout the wiki](https://github.com/DMPRoadmap/roadmap/wiki/Branding#views).

The page you want to change is `app/views/home/_welcome.html.erb`
As for generating the stats, you can query your database to gather this information.
And the icons are using the [fontawesome library](https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use)
An example to generate the user-icon from your screenshot would be: 
`<i class="fa fa-user fa-5x" style="font-size:5em;color:#333;"></i>`

**Comment by Ebrahim1010** [comment]
Hi @xsrust 

Thanks for the help! I was able to execute this command.
Does the code allows for an image to be placed on the home page like a dynamic feature or edge-to-edge slide

Thank you

**Comment by xsrust** [comment]
Yep, the homepages (and the rest of the site) are just HTML with some ruby-markup in them, so you can add or replace whatever content you want that way.  You will, of course, need to do the styling/etc to your own liking though.
