### ISSUE TITLE
change colour nav bar top and bottom

### ISSUE THREAD

**Issue by Ebrahim1010** [DMPRoadmap/roadmap#2164]
Hi guys,

We are trying to change the top navbar to a different colour but we can't find the location/path for the item. We've managed to change the colour for all other menus under app/assets/stylesheets/variables path. 

<img width="2544" alt="Screen Shot 2019-06-19 at 10 25 57" src="https://user-images.githubusercontent.com/47170940/59749107-b31af880-927c-11e9-9add-e61ce5970dea.png">

Kindly assist

**Comment by briri** [comment]
Hi @Ebrahim1010,

If you use either Firefox or Chrome browsers, you can right click on the area on the page and select 'Inspect element'. This will show you the underlying HTML and CSS that is being rendered. For example, in the screenshot below you can see that the navigation bar is picking up its background color from the '.navbar-inverse' class. 
<img width="1236" alt="Screen Shot 2019-06-19 at 8 56 04 AM" src="https://user-images.githubusercontent.com/1204467/59781447-a4c6df80-9270-11e9-8ec6-252e8bfa2121.png">

If yours also indicates that it is picking up the styling for `.navbar-inverse`, then the simplest way to update it to use the colors defined in the variables css file would be to change that `navbar-inverse` to `navbar-branding` in the view file:
https://github.com/DMPRoadmap/roadmap/blob/a08d7516c452f7c9b68a9014e5f38be61f3d2d08/app/assets/stylesheets/blocks/_navbars.scss#L52
