### ISSUE TITLE
Use a yellow outline to indicate where a user has tabbed 

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2170]
From the accessibility testing another issue is that  we should implement a yellow outline to indicate where a user has tabbed rather than a dotted outline to make navigation by keyboard only easier and consider adding a skip to main content link

**Comment by johnpinto1** [comment]
Attached screen shot of issue on IE 
![Selection_067](https://user-images.githubusercontent.com/8876215/62529278-3ea11680-b836-11e9-99c7-ca4cece72de9.png)
![Selection_066](https://user-images.githubusercontent.com/8876215/62529279-3ea11680-b836-11e9-9e31-f3d23929e20f.png)
![Selection_065](https://user-images.githubusercontent.com/8876215/62529280-3ea11680-b836-11e9-8376-33b03927619f.png)

**Comment by johnpinto1** [comment]
@magdalenadrafiova @dsisu  @sjDCC @xsrust @briri 
Please give feedback that this is what we want or not (cf., screen shots of Roadmap on IE11)
I can implement this change with a simple CSS changes: 

- add yellow to __colours.scss_

`$color-yellow: #ff0;
// Focus colors
$color-focus: $color-yellow;
`
- add to __accessibility.scss_
`a, button, input,
  .form-control {
  &:focus,
  &:hover,
  &:active {
    outline-style: solid !important;
    outline-color: $color-focus !important;
    outline-width: 4px !important;
  }
}`

![Yellow109](https://user-images.githubusercontent.com/8876215/62622167-a11d1400-b915-11e9-9bd8-0cd89766b8d5.png)
![Yellow108](https://user-images.githubusercontent.com/8876215/62622168-a11d1400-b915-11e9-8d87-341359dbaa45.png)
![Yellow107](https://user-images.githubusercontent.com/8876215/62622169-a1b5aa80-b915-11e9-9dcb-dd7672b41ce6.png)
![Selection_106](https://user-images.githubusercontent.com/8876215/62622170-a1b5aa80-b915-11e9-9b70-9c234d2a2025.png)
![Yellow105](https://user-images.githubusercontent.com/8876215/62622171-a1b5aa80-b915-11e9-89f7-334016b03205.png)
![Yellow104](https://user-images.githubusercontent.com/8876215/62622172-a1b5aa80-b915-11e9-9040-5ccc99b31ec9.png)
![Yellow103](https://user-images.githubusercontent.com/8876215/62622173-a24e4100-b915-11e9-9f4b-340425f8cd93.png)
![Yellow102](https://user-images.githubusercontent.com/8876215/62622174-a24e4100-b915-11e9-8907-75a409921014.png)
![Yellow101](https://user-images.githubusercontent.com/8876215/62622175-a24e4100-b915-11e9-9796-d67662dabda1.png)
![Yellow100](https://user-images.githubusercontent.com/8876215/62622176-a24e4100-b915-11e9-9a88-259d330a68f7.png)
![Yellow099](https://user-images.githubusercontent.com/8876215/62622177-a24e4100-b915-11e9-887c-db3b55d8ac30.png)
![Yellow098](https://user-images.githubusercontent.com/8876215/62622178-a2e6d780-b915-11e9-85ee-bafe1f84382b.png)
![Yellow097](https://user-images.githubusercontent.com/8876215/62622179-a2e6d780-b915-11e9-9e8a-08296e51da14.png)
![Yellow096](https://user-images.githubusercontent.com/8876215/62622180-a2e6d780-b915-11e9-81b2-f872c6f5d54e.png)
![Yellow095](https://user-images.githubusercontent.com/8876215/62622182-a2e6d780-b915-11e9-868b-0f9d7f9fb2b5.png)
![Yellow094](https://user-images.githubusercontent.com/8876215/62622183-a37f6e00-b915-11e9-9074-47a6643b230c.png)
![Yellow093](https://user-images.githubusercontent.com/8876215/62622184-a37f6e00-b915-11e9-9b1d-9e115a78e8c2.png)
![Yellow092](https://user-images.githubusercontent.com/8876215/62622185-a37f6e00-b915-11e9-9f8b-f74f50e6ed62.png)
![Yellow091](https://user-images.githubusercontent.com/8876215/62622186-a37f6e00-b915-11e9-96bf-c211d5d61a22.png)
![Yellow090](https://user-images.githubusercontent.com/8876215/62622188-a37f6e00-b915-11e9-93fd-fed53117fb99.png)

**Comment by johnpinto1** [comment]
@magdalenadrafiova @dsisu @sjDCC @xsrust @briri @killiandunne2 After this morning discussion changed highlighting to "Darkest Alice Blue" (which we use for links).
![Selection_125](https://user-images.githubusercontent.com/8876215/62859352-c2ef1000-bcf4-11e9-913b-afa554e726fc.png)
Here are some screen shots of results:
![Test Bullets 2 - Write plan - Chromium_124](https://user-images.githubusercontent.com/8876215/62859382-e0bc7500-bcf4-11e9-8857-95580f8ccb51.png)
![Test Bullets 2 - Write plan - Chromium_123](https://user-images.githubusercontent.com/8876215/62859384-e0bc7500-bcf4-11e9-84a4-e2cef6edc45a.png)
![Test Bullets 2 - Write plan - Chromium_121](https://user-images.githubusercontent.com/8876215/62859385-e0bc7500-bcf4-11e9-9f57-27548658660b.png)
![Test Bullets 2 - Write plan - Chromium_120](https://user-images.githubusercontent.com/8876215/62859386-e0bc7500-bcf4-11e9-8e99-b18793dda554.png)
![Test Bullets 2 - Share - Chromium_119](https://user-images.githubusercontent.com/8876215/62859387-e0bc7500-bcf4-11e9-83bc-8bea7247c255.png)
![Test Bullets 2 - Share - Chromium_118](https://user-images.githubusercontent.com/8876215/62859388-e1550b80-bcf4-11e9-9d67-1eb410831aaa.png)

**Comment by sjDCC** [comment]
Looks good. Thanks @johnpinto1

**Comment by johnpinto1** [comment]
@xsrust has pointed out an issue with highlighting links in a table. He pointed out that it would be better to highlight the table cell in such cases. So will try to see if I can sort this out.

**Comment by johnpinto1** [comment]
Following @xsrust 's suggesttion I have added an outline to table cells when in focus. Attached are sone screen shots. We might want to discuss this change.
![Ex1_tab_ouline](https://user-images.githubusercontent.com/8876215/64694376-6e74b700-d491-11e9-8651-66c012b81f55.png)
![Ex2_tab_outline](https://user-images.githubusercontent.com/8876215/64694379-72083e00-d491-11e9-8659-3c0755891d6d.png)

**Comment by sjDCC** [comment]
Looks good. Closing out

**Comment by magdalenadrafiova** [comment]
Looks good
