### ISSUE TITLE
Add an accessibility statement

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2171]
From our accessibility testing it was pointed out that we need to add an accessibility statement specific to DMP - which includes other ways of contacting the team other than just email

**Comment by briri** [comment]
We should probably put a generic accessibility statement in the footer somewhere:
<img width="1254" alt="Screen Shot 2019-09-25 at 7 56 31 AM" src="https://user-images.githubusercontent.com/1204467/65612965-10a09e80-df6a-11e9-9d0d-ab79f2eeb1f2.png">

@magdalenadrafiova for your DMPonline and DMPTuuli you can customize the text to highlight/cover any specifics related to EU and UK rules. Our DMPTool accessibility link drives our users out to a common accessibility statement/contact form that is shared by many of our products: https://www.cdlib.org/about/accessibility.html
