### ISSUE TITLE
Improve compatibility with ZoomText and Widows Magnifier magnification functionality

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2172]
Improve compatibility with ZoomText and Widows Magnifier magnification functionality

it was reported that there is some distortion when using these when using crl +

**Comment by johnpinto1** [comment]
We can't test with *zoomText* as it is licensed product costing. But *Windows Magnifier* is on all Windows machines. Here is a example of distortion mentioned in bug:

![rdesktop - dlib-touch edina ac uk_141](https://user-images.githubusercontent.com/8876215/64119068-de4bb900-cd90-11e9-857a-ee697425bdf7.png)

**Comment by johnpinto1** [comment]
@xsrust and I went back to the *UOE* page and used the *Windows Magnifier* again and now we noticed similar distortion of text in *Window's Edge*
![rdesktop - dlib-touch edina ac uk_146](https://user-images.githubusercontent.com/8876215/64124449-f75b6680-cd9e-11e9-8dad-a37ec71fc60f.png)

**Comment by johnpinto1** [comment]
https://www.realpointdesign.co.uk/1572/choosing-fonts-for-your-website-for-accessibility/
The above article recommends Verdana for Accessibility:

```
Our standard recommendations for on-screen typefaces are:
    Verdana (when on screen legibility is of prime importance)
    Trebuchet (when a slightly more interesting style is looked for)
    Arial / Helvetica (the stalwarts of the typeface world)

```

**Comment by johnpinto1** [comment]
@xsrust @briri @magdalenadrafiova @sjDCC @dsisu 
The question is do we set the default font-family to say
`font-family: Verdana, Trebuchet, "Helvetica Neue", Helvetica, Arial, sans-serif;`
Feedback requested. I will add some screenshots with this this afternoon.

Currently default font-family  style used by *Roadmap* comes from Bootstrap:
In the style file  file https://github.com/twbs/bootstrap/blob/v3.4.1/dist/css/bootstrap.css the font-family is set
`font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;`
See **line 1084** onwards
```
body {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
 ...
}
```
See **line 6068** onwards
```
.tooltip {
  position: absolute;
  z-index: 1070;
  display: block;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-style: normal;
  font-weight: 400;
...
}
```
See **line 6068** onwards:
```
.popover {
  position: absolute;
  top: 0;
  left: 0;
  z-index: 1060;
  display: none;
  max-width: 276px;
  padding: 1px;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-style: normal;
  font-weight: 400;
...
}
```

**Comment by xsrust** [comment]
I'd be happy to change that font to the more accessible one for the Roadmap project.
I'm not entirely sure we need to though, as Helvetica was listed on the accessible fonts from the article linked.

**Comment by sjDCC** [comment]
New text scales well for me. Looks good. Closing out

**Comment by sjDCC** [comment]
By the way @johnpinto1 I really appreciate all the screengrabs you put in. Helps to know what we're testing :-)
