### ISSUE TITLE
Provide a different way of pop up guidance 

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2174]
It has been also reported that we need to remove the pop up guidance provided by the fields and provide this in another way such as text description under the question so it is compatible with assistive technology

**Comment by sjDCC** [comment]
I guess this is an example of that. Looks good

![link](https://user-images.githubusercontent.com/6169940/65812060-e6452000-e1b9-11e9-809c-1e5b1154d335.PNG)

**Comment by magdalenadrafiova** [comment]
Looks good
