### ISSUE TITLE
Give warnings when links open in new windows

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2175]
When new windows are opened the user do not get warning. We need to add warning when link will open in a new window.

**Comment by johnpinto1** [comment]
@magdalenadrafiova @sjDCC @dsisu @xsrust @killiandunne2 
The coding is done but must await @briri (who is on holidays) as I have changed some important code of his slightly.

There are screen shots of this change based on  recommendations from 
The solution is based on the recommendation in "Techniques for WCAG 2.0" section
"G201: Giving users advanced warning when opening a new window":
"Example 2: Using CSS to provide a warning before opening a new window"
(cf., https://www.w3.org/TR/WCAG20-TECHS/G201.html)
![My Dashboard - Chromium_131](https://user-images.githubusercontent.com/8876215/63014794-43457a80-be87-11e9-99d4-a613fdf9b2b9.png)
![Welcome to DMPRoadmap  - Chromium_130](https://user-images.githubusercontent.com/8876215/63014795-43457a80-be87-11e9-9124-90ba283526f2.png)
![Welcome to DMPRoadmap  - Chromium_129](https://user-images.githubusercontent.com/8876215/63014796-43457a80-be87-11e9-82e6-fe2b1b9b21c3.png)
![Test old Bu - Download - Chromium_128](https://user-images.githubusercontent.com/8876215/63014797-43457a80-be87-11e9-945c-27760f242c79.png)

Changes affect: 
Pages affected:
app/assets/stylesheets/blocks/_new_window_popup.scss
app/javascript/utils/externalLink.js
app/views/contact_us/contacts/new.html.erb **(Contact Us)**
app/views/layouts/_branding.html.erb **(Organisation link on page.)**
app/views/layouts/_footer.html.erb   **(Footer external links)**
app/views/org_admin/plans/index.html.erb (**Org Admin Plans page, Download plans button)**
app/views/paginable/plans/_organisationally_or_publicly_visible.html.erb **(DMP Templates, Download pdf and Word links)**
app/views/paginable/plans/_publicly_visible.html.erb **(Public DMPs, Download pdf links)**
app/views/paginable/templates/_publicly_visible.html.erb
app/views/plans/_download_form.html.erb **(Plans Download tab)**
app/views/static_pages/about_us.html.erb **(about us page all external links luke DMPOnlie and DMPTool and Githhub Issues.)**
app/views/static_pages/termsuse.html.erb **(Terms of Use,  DCC , CDL and DCC main website  links)
app/views/usage/index.html.erb **(usage page "Download All" button)**

**Comment by johnpinto1** [comment]
@xsrust has pointed out an issue with highlighting links in a table. He pointed out that it would be better to highlight the table cell in such cases. So will try to see if I can sort this out.

**Comment by sjDCC** [comment]
Spotted this earlier in header. Looks good

**Comment by magdalenadrafiova** [comment]
Looks good to me
