### ISSUE TITLE
Tinymce changes not being recognized

### ISSUE THREAD

**Issue by raycarrick-ed** [DMPRoadmap/roadmap#218]
When edits are made to tinymce textareas these should be registered and the questions marked as having changed to do all the "Do you want to quit without saving stuff". It's not happening just now.

**Comment by raycarrick-ed** [comment]
fixed by https://github.com/DigitalCurationCentre/roadmap/commit/3503c5cff178f8ea744f4c8d0f5550109addeed9

**Comment by stephaniesimms** [comment]
Working as expected
