### ISSUE TITLE
Requesting feedback on copied plan - email is not generated 

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2180]
If you create a plan, request feedback and then copy the plan then the copied plan goes into the list of plans awaiting feedback in DMPonline but an email is not generated. This is confusing as institutions don’t know if researchers genuinely want feedback on the copies of their plans, is it possible to get this fixed?

**Comment by cmgib** [comment]
For consistency of user experience can we suggest that a plan should go into the list of plans awaiting feedback and generate an email only when a researcher selects the "Request feedback" button (under the Share tab). This would apply to all plans, whether a new plan or a copy of a plan. Hope this makes sense!

**Comment by xsrust** [comment]
I agree with @cmgib on this one.  
When a plan is coppied, we should remove the feedback-requested attribute from it so it does not show up on the admin-plans dashboard.  Requests for feedback should be explicit.

**Comment by briri** [comment]
Updated the code that copies a plan so that the new copy always sets the `feedback_requested` flag to false.

**Comment by cmgib** [comment]
Thanks @briri - just to confirm it's working as planned

**Comment by mariapraetzellis** [comment]
Will test when on DMPOnline testing environment.

**Comment by sjDCC** [comment]
This is on DMPonline-test now.

Have created a plan as Edinburgh, submitted for review. Completed review. Then copied DMP and re-submitted for review. All notifications came as expected. Thanks @raycarrick-ed Closing out
