### ISSUE TITLE
Tooltip - data contact person 

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2183]
We have received a request to add an explanatory text on what we consider a Data Contact Person. “Person responsible for the project’s data management and data quality (ensuring its completeness, consistency and accuracy)”

Sam also raised a great point whether this should be configurable per org/installation, or if the text can be the same for everybody. Any thoughts on this will be great.

**Comment by mariapraetzellis** [comment]
I think this is no longer relevant due to changes to the Contributors section (https://github.com/DMPRoadmap/roadmap/issues/2349). Are we okay to close this @magdalenadrafiova?

**Comment by magdalenadrafiova** [comment]
I agree - closing here
