### ISSUE TITLE
Additional Guidance

### ISSUE THREAD

**Issue by Ebrahim1010** [DMPRoadmap/roadmap#2185]
How do I implement the addtional guidance from the code?

Currently my site is set up and looks like this: 
<img width="1331" alt="Screen Shot 2019-07-16 at 11 36 46" src="https://user-images.githubusercontent.com/47170940/61283830-07eb5980-a7be-11e9-906a-0453323636f1.png">

I want to include addtional guidance to the my plans such like this:
<img width="491" alt="Screen Shot 2019-07-16 at 08 45 34" src="https://user-images.githubusercontent.com/47170940/61283893-25202800-a7be-11e9-86cc-d5eb7a1d7b9e.png">

Kindly assist

**Comment by briri** [comment]
Hi @Ebrahim1010,

You need to update the abbreviation (and should update all of the organization information) in your copy of the `config/branding.yml` file. The abbreviation you use here should match the abbreviation of the organization that owns the guidance.

https://github.com/DMPRoadmap/roadmap/blob/a08d7516c452f7c9b68a9014e5f38be61f3d2d08/config/branding.yml.sample#L7

**Comment by Ebrahim1010** [comment]
Hi @briri,

Thank you for the assistance.
So I've updated the abbreviation to our organization abbreviation.
This only worked for one of the templates and not all. It also does not allow me to select guidance from multiple templates.

See attached. 
<img width="1123" alt="Screen Shot 2019-07-18 at 10 07 24" src="https://user-images.githubusercontent.com/47170940/61440474-ed42ed00-a943-11e9-8cd6-52f0ceade5be.png">

**Comment by briri** [comment]
Hi @Ebrahim1010,
Guidance has associated themes defined (e.g. Budget, Data Collection, etc.). A template's question's also have associated themes. The 'Select Guidance' list will only show you guidance that is relevant to the template, so if the template's questions do not have any themes that match up with your guidance, then the guidance would not appear in the list.

The following links are specific to the DMPTool (our branded version of DMPRoadmap) but they should give you some context. We provide these instructions to administrators who will be setting up guidance and templates for their institutions:
- List of Themes and corresponding guidance that DMPonline and DMPTool use: https://github.com/cdluc3/dmptool/wiki/themes
- Creating Guidance: https://github.com/cdluc3/dmptool/wiki/creating-guidance
- Creating Templates: https://github.com/cdluc3/dmptool/wiki/creating-templates
- Customizing Funder Templates: https://github.com/cdluc3/dmptool/wiki/customizing-funder-templates

I'm not sure how you will be managing your system, Our tool is used by many institutions and we maintain templates for multiple funders (USGS, NSF, etc.) for that audience. The institutions in turn, have administrators that often create their own supplemental guidance and customizations to those funder templates (e.g. they want to add additional questions or an additional section to a funder template). It can get a bit complicated.

If you're audience is just within your local institution, then you can ignore the 'Customizing Funder Templates' link and just work with your own templates and guidance.

**Comment by Ebrahim1010** [comment]
@briri,

Thank you, this was really helpful!
