### ISSUE TITLE
Roles and Plan Sharing

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#219]
There currently does not exist a role for a read only collaborator on a plan (they get set as a creator).

After talking to @raycarrick-ed , we determined that since the roles use bitflags for determining a collaborator's permissions on a project, it makes sense to extend this approach for the read only collaborator.  

### Database
The proposal would be to make the bitflags for roles behave more like the permissions:
1 - creator (initially created the plan)
2 - administrator (has the ability to add other collaborators to the plan)
3 - editor (has the ability to edit answers on a plan)
4 - commenter (has the ability to edit notes on the plan) (newly added)

### Logic
The advantage to this approach is that it will clean up the logic around display and authentication for actions.  For example, in the current code, to validate that a user can edit a page, the following statement would be needed:
`if @role.creator? || @role.administrator? || @role.editor?`
If the roles behaved as permissions, the logic would be as follows:
`if @role.editor?`
Since each bitflag would directly correspond to one ability of the user.

### Front End
The front-end for plan sharing would remain the same with the options being: Co-Owner, Editor, Read Only (should this be Reviewer or Commenter?).  
A Co-Owner will have permissions 2, 3, 4
An Editor: permissions 3, 4
and Read only: permission 4

A separate ticket will be added to update the authorization and display logic for plan editing to follow this behavior.

**Comment by briri** [comment]
This sounds like a good approach. Be sure to update the unit tests as you make these changes in test/unit/user_test.rb.

The majority of the permission related tests in that file have been commented out because of an issue with the original implementation.

**Comment by sjDCC** [comment]
This sounds good @xsrust Just to clarify, the initial creator of a plan will be the owner so will have permissions 2, 3 & 4

**Comment by xsrust** [comment]
yes, along with permission 1 to denote that they created it

**Comment by xsrust** [comment]
2 distinct pieces of work will be involved in fixing this ticket: (and thus need to be tested later)
- implimenting in the current "development" code
- fixing migration_step_3 to reflect new implimentation

**Comment by stephaniesimms** [comment]
Share plan button and functionality is working as expected, but creating a new ticket to reflect problem with making changes to existing permissions

**Comment by stephaniesimms** [comment]
Reopening. Closed wrong ticket accidentally.

**Comment by xsrust** [comment]
migration step 3 fixed in https://github.com/DMPRoadmap/roadmap/commit/626a7369fb1cf1adb22491db942c2831a3cfd6eb

**Comment by briri** [comment]
@xsrust got the migration piece sorted out. Go ahead and push this through in the next PR and I'll work through any broken tests

**Comment by stephaniesimms** [comment]
@xsrust thanks for thorough documentation here! we should use Commenter/Read-only (not Reviewer). UX is evaluating language for MVP. Everything working as expected in the UI. Closing out.

**Comment by stephaniesimms** [comment]
Reopening: with Read-only access I can only view the plan details page or export the plan. I cannot view the answers or add comments to the plan. @sjDCC this could use some more testing to make sure roles enable expected actions.

**Comment by sjDCC** [comment]
Yes, moving this back to pending. 

The read-only role should be able to access the plan to view it and add comments. Currently when you click that tab you're taken back to the 'my plans' page/table. The only tabs that open for you are plan details and export.

Other roles seem to function correctly.

**Comment by xsrust** [comment]
I think that the comments from @stephaniesimms  and @sjDCC are actually related to #220 which was supposed to be the ticket pertaining to the authorization and display logic for plan editing.  This ticket was for the backend migration and assigning of roles

**Comment by xsrust** [comment]
fixed by https://github.com/DigitalCurationCentre/roadmap/commit/d7c338ca170e96af72d14a17966c73e3c417ade5

**Comment by sjDCC** [comment]
Read-only functionality work as expected. Closing out
