### ISSUE TITLE
DMP template tab

### ISSUE THREAD

**Issue by Ebrahim1010** [DMPRoadmap/roadmap#2193]
Hi guys,

Thanks for the support, as always great work.

Can you please point me the correct location for the attached page. I want change the positioning of these templates. (eg. I want the Gender, Health and Justice Research Unit to appear on top).

Thank you
<img width="2197" alt="Screen Shot 2019-07-25 at 15 52 18" src="https://user-images.githubusercontent.com/47170940/61879929-3e2e8480-aef4-11e9-8d66-1c0a342ded87.png">

**Comment by xsrust** [comment]
Not a problem @Ebrahim1010 

The controller responsible for that page is  at https://github.com/DMPRoadmap/roadmap/blob/a08d7516c452f7c9b68a9014e5f38be61f3d2d08/app/controllers/public_pages_controller.rb#L9-L16 

The controller sets the @templates variable, which then is displayed on the page.  We're just ordering by title at the moment, but feel free to adjust the logic as you see fit.

The view being rendered is:
https://github.com/DMPRoadmap/roadmap/blob/master/app/views/public_pages/template_index.html.erb, 

You'll see we pass this into the paginable_renderise & sort by title here as well, so you'll likely need to adjust this to get the behavior you desire.
