### ISSUE TITLE
Successful installation, but font-awesome displays squares

### ISSUE THREAD

**Issue by mirkh** [DMPRoadmap/roadmap#2197]
I installed DMP roadmap, and have it working on my webserver.

But the font-awesome symbols don't display properly, what could I have missed during installation? 

They look like for example:  (fa-circle-o:before)

If this is not the place for such a question, please point me to a better one. :)

**Comment by mirkh** [comment]
My problem was solved when I learned that I should specify environment when compiling assets. Closing issue.

**Comment by xsrust** [comment]
@mirkh 
I was just about to ask you if you were running in development or production mode.
Thanks for posting back with your solution!

This is definitely the place for such questions as people with similar problems will be able to view old issues, so it creates a resource for them in the future.
