### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by aninder** [DMPRoadmap/roadmap#2198]
After installing DMPRoadmap trying to run tests with the command, 
**bundle exec rspec spec** 
and 5 tests are failing. 

1. All the failing tests are feature tests(capybara).
2. All the failing tests have a pattern of testing for the existence of the text, "answered just now" , after filling and saving a answer for a question in a plan.
3. I was expecting the page which is tested to be HTML but it's a encoded hash

#Failing tests are,
rspec ./spec/features/questions/radiobuttons_questions_spec.rb:18 # Questions::Tadio button questions User answers a radio button question
rspec ./spec/features/questions/checkbox_questions_spec.rb:20 # Questions::Check box questions User answers a check box question
rspec ./spec/features/questions/textarea_questions_spec.rb:18 # Questions::Text area questions User answers a Text Area question
rspec ./spec/features/questions/dropdown_questions_spec.rb:20 # Questions::Dropdown questions User answers a dropdown select question
rspec ./spec/features/questions/textfield_questions_spec.rb:18 # Questions::Text Field questions User answers a Text field question.

**The detailed trace is,**

  1) Questions::Tadio button questions User answers a radio button question
     Failure/Error: expect(page).to have_text "Answered just now"
       expected to find text "Answered just now" in "{\"question\":{\"id\":41,\"answer_lock_version\":1,\"locking\":null,\"form\":\"\\u003c!--\\n  This partial creates a form for each type of question. The local variables are: plan, answer, question, readonly\\n--\\u003e\\n\\u003c!-- Question text --\\u003e\\n\\n\\u003cform data-autosave=\\\"41\\\" class=\\\"form-answer\\\" id=\\\"edit_answer_1\\\" action=\\\"/answers/create_or_update?question_id=41\\\" accept-charset=\\\"UTF-8\\\" method=\\\"post\\\"\\u003e\\u003cinput name=\\\"utf8\\\" type=\\\"hidden\\\" value=\\\"\\u0026#x2713;\\\" /\\u003e\\n    \\u003cinput type=\\\"hidden\\\" value=\\\"1\\\" name=\\\"answer[plan_id]\\\" id=\\\"answer_plan_id\\\" /\\u003e\\n    \\u003cinput type=\\\"hidden\\\" value=\\\"41\\\" name=\\\"answer[question_id]\\\" id=\\\"answer_question_id\\\" /\\u003e\\n    \\u003cinput type=\\\"hidden\\\" value=\\\"1\\\" name=\\\"answer[lock_version]\\\" id=\\\"answer_lock_version\\\" /\\u003e\\n  \\u003cfieldset \\u003e\\n            \\u003clabel class=\\\"control-label\\\" for=\\\"answer_question_option_ids\\\"\\u003eRepudiandae praesentium possimus. Voluptatem non a. Voluptates rem non.\\u003c/label\\u003e\\n        \\u003cdiv class=\\\"radio\\\"\\u003e\\n            \\u003clabel\\u003e\\n                \\u003cinput id=\\\"answer_option_ids_2\\\" type=\\\"radio\\\" value=\\\"2\\\" checked=\\\"checked\\\" name=\\\"answer[question_option_ids]\\\" /\\u003e\\n                Vero aliquid nisi odio.\\n            \\u003c/label\\u003e\\n        \\u003c/div\\u003e\\n        \\u003cdiv class=\\\"radio\\\"\\u003e\\n            \\u003clabel\\u003e\\n                \\u003cinput id=\\\"answer_option_ids_3\\\" type=\\\"radio\\\" value=\\\"3\\\" name=\\\"answer[question_option_ids]\\\" /\\u003e\\n                Accusamus dolores voluptatem eveniet.\\n            \\u003c/label\\u003e\\n        \\u003c/div\\u003e\\n\\u003cdiv class=\\\"form-group\\\"\\u003e\\n\\u003c!-- Comment text area for option_based questions --\\u003e\\n    \\u003clabel class=\\\"control-label\\\" for=\\\"answer_text\\\"\\u003eAdditional Information\\u003c/label\\u003e\\n      \\u003ctextarea name=\\\"answer[text]\\\" id=\\\"answer-text-41\\\" class=\\\"form-control tinymce_answer\\\"\\u003e\\n\\u003c/textarea\\u003e\\n\\u003c/div\\u003e\\n\\n    \\u003cbutton name=\\\"button\\\" type=\\\"submit\\\" class=\\\"btn btn-default\\\"\\u003eSave\\u003c/button\\u003e\\n  \\u003c/fieldset\\u003e\\n  \\u003c!--Example Answer area --\\u003e\\n\\u003c/form\\u003e\",\"answer_status\":\"\\u003c!-- Partial for handling the answer status (e.g. saving, error-saving, data-status) --\\u003e\\n\\u003cspan class=\\\"label label-info status\\\" style=\\\"display:none;\\\" data-status=\\\"saving\\\"\\u003eSaving...\\u003c/span\\u003e\\n\\u003cspan class=\\\"label label-warning status\\\" style=\\\"display: none;\\\" data-status=\\\"error-saving\\\"\\u003e\\u003c/span\\u003e\\n    \\u003cspan class=\\\"label label-info status\\\" data-status=\\\"saved-at\\\"\\u003e\\n      Answered \\u003ctime class=\\\"timeago\\\" datetime=\\\"2019-08-01T01:50:33Z\\\"\\u003e\\u003c/time\\u003e\\n       by donnetta@example.org\\n    \\u003c/span\\u003e\\n\"},\"section\":{\"id\":39,\"progress\":\"\\u003c!-- Partial template for showing the progress for a section, i.e. the valid answers --\\u003e\\n\\u003cspan class=\\\"right section-status\\\"\\u003e\\n  (1 / 1)\\n\\u003c/span\\u003e\"},\"plan\":{\"id\":1,\"progress\":\"\\u003cdiv class=\\\"progress-bar\\\" role=\\\"progressbar\\\"\\n  aria-valuenow=\\\"100.0\\\"\\n  aria-valuemin=\\\"0\\\" aria-valuemax=\\\"100\\\"\\n  style=\\\"min-width: 7em; width: 100.0%;\\\"\\u003e\\n    1/1 answered\\n\\u003c/div\\u003e\\n\\n\\n\"}}"
     # ./spec/features/questions/radiobuttons_questions_spec.rb:39:in `block (2 levels) in <top (required)>'

  2) Questions::Check box questions User answers a check box question
     Failure/Error: expect(page).to have_text "Answered just now"
       expected to find text "Answered just now" in "{\"question\":{\"id\":3,\"answer_lock_version\":1,\"locking\":null,\"form\":\"\\u003c!--\\n  This partial creates a form for each type of question. The local variables are: plan, answer, question, readonly\\n--\\u003e\\n\\u003c!-- Question text --\\u003e\\n\\n\\u003cform data-autosave=\\\"3\\\" class=\\\"form-answer\\\" id=\\\"edit_answer_1\\\" action=\\\"/answers/create_or_update?question_id=3\\\" accept-charset=\\\"UTF-8\\\" method=\\\"post\\\"\\u003e\\u003cinput name=\\\"utf8\\\" type=\\\"hidden\\\" value=\\\"\\u0026#x2713;\\\" /\\u003e\\n    \\u003cinput type=\\\"hidden\\\" value=\\\"1\\\" name=\\\"answer[plan_id]\\\" id=\\\"answer_plan_id\\\" /\\u003e\\n    \\u003cinput type=\\\"hidden\\\" value=\\\"3\\\" name=\\\"answer[question_id]\\\" id=\\\"answer_question_id\\\" /\\u003e\\n    \\u003cinput type=\\\"hidden\\\" value=\\\"1\\\" name=\\\"answer[lock_version]\\\" id=\\\"answer_lock_version\\\" /\\u003e\\n  \\u003cfieldset \\u003e\\n            \\u003clabel class=\\\"control-label\\\" for=\\\"answer_question_option_ids\\\"\\u003eNumquam facilis laudantium. A delectus voluptatem. Cumque dolorum rem.\\u003c/label\\u003e\\n        \\u003cdiv class=\\\"checkbox\\\"\\u003e\\n            \\u003clabel\\u003e\\n                \\u003cinput type=\\\"checkbox\\\" value=\\\"1\\\" checked=\\\"checked\\\" name=\\\"answer[question_option_ids][]\\\" id=\\\"answer_question_option_ids_1\\\" /\\u003e\\n                Maiores hic culpa nam.\\n            \\u003c/label\\u003e\\n        \\u003c/div\\u003e\\n        \\u003cdiv class=\\\"checkbox\\\"\\u003e\\n            \\u003clabel\\u003e\\n                \\u003cinput type=\\\"checkbox\\\" value=\\\"2\\\" name=\\\"answer[question_option_ids][]\\\" id=\\\"answer_question_option_ids_2\\\" /\\u003e\\n                Mollitia laborum in sit.\\n            \\u003c/label\\u003e\\n        \\u003c/div\\u003e\\n\\u003cdiv class=\\\"form-group\\\"\\u003e\\n\\u003c!-- Comment text area for option_based questions --\\u003e\\n    \\u003clabel class=\\\"control-label\\\" for=\\\"answer_text\\\"\\u003eAdditional Information\\u003c/label\\u003e\\n      \\u003ctextarea name=\\\"answer[text]\\\" id=\\\"answer-text-3\\\" class=\\\"form-control tinymce_answer\\\"\\u003e\\n\\u003c/textarea\\u003e\\n\\u003c/div\\u003e\\n\\n    \\u003cbutton name=\\\"button\\\" type=\\\"submit\\\" class=\\\"btn btn-default\\\"\\u003eSave\\u003c/button\\u003e\\n  \\u003c/fieldset\\u003e\\n  \\u003c!--Example Answer area --\\u003e\\n\\u003c/form\\u003e\",\"answer_status\":\"\\u003c!-- Partial for handling the answer status (e.g. saving, error-saving, data-status) --\\u003e\\n\\u003cspan class=\\\"label label-info status\\\" style=\\\"display:none;\\\" data-status=\\\"saving\\\"\\u003eSaving...\\u003c/span\\u003e\\n\\u003cspan class=\\\"label label-warning status\\\" style=\\\"display: none;\\\" data-status=\\\"error-saving\\\"\\u003e\\u003c/span\\u003e\\n    \\u003cspan class=\\\"label label-info status\\\" data-status=\\\"saved-at\\\"\\u003e\\n      Answered \\u003ctime class=\\\"timeago\\\" datetime=\\\"2019-08-01T01:51:25Z\\\"\\u003e\\u003c/time\\u003e\\n       by dustin_dach@example.org\\n    \\u003c/span\\u003e\\n\"},\"section\":{\"id\":1,\"progress\":\"\\u003c!-- Partial template for showing the progress for a section, i.e. the valid answers --\\u003e\\n\\u003cspan class=\\\"right section-status\\\"\\u003e\\n  (1 / 1)\\n\\u003c/span\\u003e\"},\"plan\":{\"id\":1,\"progress\":\"\\u003cdiv class=\\\"progress-bar\\\" role=\\\"progressbar\\\"\\n  aria-valuenow=\\\"100.0\\\"\\n  aria-valuemin=\\\"0\\\" aria-valuemax=\\\"100\\\"\\n  style=\\\"min-width: 7em; width: 100.0%;\\\"\\u003e\\n    1/1 answered\\n\\u003c/div\\u003e\\n\\n\\n\"}}"
     # ./spec/features/questions/checkbox_questions_spec.rb:43:in `block (2 levels) in <top (required)>'

  3) Questions::Text area questions User answers a Text Area question
     Failure/Error:
             page.execute_script <<~JS
               var editor = tinyMCE.get('#{id}');
               editor.setContent('#{with}');
               editor.fire('change');
             JS
     
     Selenium::WebDriver::Error::JavascriptError:
       javascript error: Cannot read property 'setContent' of null
         (Session info: headless chrome=75.0.3770.100)
     0 0x5589741d17a9 <unknown>
 
  4) Questions::Dropdown questions User answers a dropdown select question
     Failure/Error: expect(page).to have_text "Answered just now"
       expected to find text "Answered just now" in "{\"question\":{\"id\":3,\"answer_lock_version\":1,\"locking\":null,\"form\":\"\\u003c!--\\n  This partial creates a form for each type of question. The local variables are: plan, answer, question, readonly\\n--\\u003e\\n\\u003c!-- Question text --\\u003e\\n\\n\\u003cform data-autosave=\\\"3\\\" class=\\\"form-answer\\\" id=\\\"edit_answer_1\\\" action=\\\"/answers/create_or_update?question_id=3\\\" accept-charset=\\\"UTF-8\\\" method=\\\"post\\\"\\u003e\\u003cinput name=\\\"utf8\\\" type=\\\"hidden\\\" value=\\\"\\u0026#x2713;\\\" /\\u003e\\n    \\u003cinput type=\\\"hidden\\\" value=\\\"1\\\" name=\\\"answer[plan_id]\\\" id=\\\"answer_plan_id\\\" /\\u003e\\n    \\u003cinput type=\\\"hidden\\\" value=\\\"3\\\" name=\\\"answer[question_id]\\\" id=\\\"answer_question_id\\\" /\\u003e\\n    \\u003cinput type=\\\"hidden\\\" value=\\\"1\\\" name=\\\"answer[lock_version]\\\" id=\\\"answer_lock_version\\\" /\\u003e\\n  \\u003cfieldset \\u003e\\n            \\u003clabel class=\\\"control-label\\\" for=\\\"answer_question_option_ids\\\"\\u003eExplicabo nostrum quaerat. Alias voluptatem nulla. Deserunt et nihil.\\u003c/label\\u003e\\n    \\u003cselect name=\\\"answer[question_option_ids]\\\" id=\\\"answer_question_option_ids\\\" class=\\\"form-control\\\"\\u003e\\u003coption value=\\\"\\\"\\u003e\\u003c/option\\u003e\\u003coption value=1 selected=\\\"selected\\\"\\u003eTempore autem fugiat dicta.\\u003c/option\\u003e\\u003coption value=2\\u003eIste et blanditiis voluptatem.\\u003c/option\\u003e\\u003c/select\\u003e\\n\\u003cdiv class=\\\"form-group\\\"\\u003e\\n\\u003c!-- Comment text area for option_based questions --\\u003e\\n    \\u003clabel class=\\\"control-label\\\" for=\\\"answer_text\\\"\\u003eAdditional Information\\u003c/label\\u003e\\n      \\u003ctextarea name=\\\"answer[text]\\\" id=\\\"answer-text-3\\\" class=\\\"form-control tinymce_answer\\\"\\u003e\\n\\u003c/textarea\\u003e\\n\\u003c/div\\u003e\\n\\n    \\u003cbutton name=\\\"button\\\" type=\\\"submit\\\" class=\\\"btn btn-default\\\"\\u003eSave\\u003c/button\\u003e\\n  \\u003c/fieldset\\u003e\\n  \\u003c!--Example Answer area --\\u003e\\n\\u003c/form\\u003e\",\"answer_status\":\"\\u003c!-- Partial for handling the answer status (e.g. saving, error-saving, data-status) --\\u003e\\n\\u003cspan class=\\\"label label-info status\\\" style=\\\"display:none;\\\" data-status=\\\"saving\\\"\\u003eSaving...\\u003c/span\\u003e\\n\\u003cspan class=\\\"label label-warning status\\\" style=\\\"display: none;\\\" data-status=\\\"error-saving\\\"\\u003e\\u003c/span\\u003e\\n    \\u003cspan class=\\\"label label-info status\\\" data-status=\\\"saved-at\\\"\\u003e\\n      Answered \\u003ctime class=\\\"timeago\\\" datetime=\\\"2019-08-01T01:54:53Z\\\"\\u003e\\u003c/time\\u003e\\n       by malcolm_bins@example.net\\n    \\u003c/span\\u003e\\n\"},\"section\":{\"id\":1,\"progress\":\"\\u003c!-- Partial template for showing the progress for a section, i.e. the valid answers --\\u003e\\n\\u003cspan class=\\\"right section-status\\\"\\u003e\\n  (1 / 1)\\n\\u003c/span\\u003e\"},\"plan\":{\"id\":1,\"progress\":\"\\u003cdiv class=\\\"progress-bar\\\" role=\\\"progressbar\\\"\\n  aria-valuenow=\\\"100.0\\\"\\n  aria-valuemin=\\\"0\\\" aria-valuemax=\\\"100\\\"\\n  style=\\\"min-width: 7em; width: 100.0%;\\\"\\u003e\\n    1/1 answered\\n\\u003c/div\\u003e\\n\\n\\n\"}}"
     # ./spec/features/questions/dropdown_questions_spec.rb:41:in `block (2 levels) in <top (required)>'

  5) Questions::Text Field questions User answers a Text field question
     Failure/Error: expect(page).to have_text "Answered just now"
       expected to find text "Answered just now" in "{\"question\":{\"id\":1,\"answer_lock_version\":1,\"locking\":null,\"form\":\"\\u003c!--\\n  This partial creates a form for each type of question. The local variables are: plan, answer, question, readonly\\n--\\u003e\\n\\u003c!-- Question text --\\u003e\\n\\n\\u003cform data-autosave=\\\"1\\\" class=\\\"form-answer\\\" id=\\\"edit_answer_1\\\" action=\\\"/answers/create_or_update?question_id=1\\\" accept-charset=\\\"UTF-8\\\" method=\\\"post\\\"\\u003e\\u003cinput name=\\\"utf8\\\" type=\\\"hidden\\\" value=\\\"\\u0026#x2713;\\\" /\\u003e\\n    \\u003cinput type=\\\"hidden\\\" value=\\\"6\\\" name=\\\"answer[plan_id]\\\" id=\\\"answer_plan_id\\\" /\\u003e\\n    \\u003cinput type=\\\"hidden\\\" value=\\\"1\\\" name=\\\"answer[question_id]\\\" id=\\\"answer_question_id\\\" /\\u003e\\n    \\u003cinput type=\\\"hidden\\\" value=\\\"1\\\" name=\\\"answer[lock_version]\\\" id=\\\"answer_lock_version\\\" /\\u003e\\n  \\u003cfieldset \\u003e\\n        \\u003cdiv class=\\\"form-group\\\"\\u003e\\n    \\u003clabel class=\\\"control-label\\\" for=\\\"answer_text\\\"\\u003eConsequatur sunt at. Aliquam beatae autem. Explicabo eos molestiae.\\u003c/label\\u003e\\n    \\u003cinput type=\\\"text\\\" name=\\\"answer[text]\\\" id=\\\"answer_text\\\" value=\\\"My test answer\\\" class=\\\"form-control\\\" /\\u003e\\n\\u003c/div\\u003e\\n    \\u003cbutton name=\\\"button\\\" type=\\\"submit\\\" class=\\\"btn btn-default\\\"\\u003eSave\\u003c/button\\u003e\\n  \\u003c/fieldset\\u003e\\n  \\u003c!--Example Answer area --\\u003e\\n\\u003c/form\\u003e\",\"answer_status\":\"\\u003c!-- Partial for handling the answer status (e.g. saving, error-saving, data-status) --\\u003e\\n\\u003cspan class=\\\"label label-info status\\\" style=\\\"display:none;\\\" data-status=\\\"saving\\\"\\u003eSaving...\\u003c/span\\u003e\\n\\u003cspan class=\\\"label label-warning status\\\" style=\\\"display: none;\\\" data-status=\\\"error-saving\\\"\\u003e\\u003c/span\\u003e\\n    \\u003cspan class=\\\"label label-info status\\\" data-status=\\\"saved-at\\\"\\u003e\\n      Answered \\u003ctime class=\\\"timeago\\\" datetime=\\\"2019-08-01T01:55:09Z\\\"\\u003e\\u003c/time\\u003e\\n       by edris@example.org\\n    \\u003c/span\\u003e\\n\"},\"section\":{\"id\":1,\"progress\":\"\\u003c!-- Partial template for showing the progress for a section, i.e. the valid answers --\\u003e\\n\\u003cspan class=\\\"right section-status\\\"\\u003e\\n  (1 / 1)\\n\\u003c/span\\u003e\"},\"plan\":{\"id\":6,\"progress\":\"\\u003cdiv class=\\\"progress-bar\\\" role=\\\"progressbar\\\"\\n  aria-valuenow=\\\"100.0\\\"\\n  aria-valuemin=\\\"0\\\" aria-valuemax=\\\"100\\\"\\n  style=\\\"min-width: 7em; width: 100.0%;\\\"\\u003e\\n    1/1 answered\\n\\u003c/div\\u003e\\n\\n\\n\"}}"
     # ./spec/features/questions/textfield_questions_spec.rb:39:in `block (2 levels) in <top (required)>'

**Comment by aninder** [comment]
Tests are green. 
Rebase from master branch seems to have fixed the issue.

**Comment by xsrust** [comment]
Thanks for the updated @aninder 
I think the failing tests were related to the timeago.js package, so likely fixed by:
https://github.com/DMPRoadmap/roadmap/commit/1bb59b7dc7f98c014417226e7a61a79dfa10d339
