### ISSUE TITLE
Plan details template published date wrong

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#2199]
Issue reported by @aninder 

**Expected behaviour:**
Plan overview page shows the template version and published date

**Actual behaviour:**
Plan overview page shows the template publish date  as the date of the last update to the plan.

**Steps to reproduce:**
Go to plan overview page & compare publish date listed there with `updated_at` on the template

**Fix:**
Update line 19 here:
https://github.com/DMPRoadmap/roadmap/commit/acda03b97dabcd1f69aae4fc5cd8c1d500b8df04#diff-83e5cbda3ea9f16b975d66cc32da8bfc
to state
`published_date : l(plan.template.updated_at.to_date, format: :readable) } %>`

**Comment by aninder** [comment]
sorry just trying to understand , what if the template is updated but not published . Wont then with your suggested fix the published date be out of sync with the template version that is being shown?

**Comment by xsrust** [comment]
Not a problem.

Once a template is published, it can no-longer be modified and a new version must be created, so the 'updated_at' field will be the time it was published.

In the inverse situation, when a template is updated and not published, it will not be possible to create a plan based off of it until it is published.  This situation is therefore not reachable

**Comment by aninder** [comment]
yup sounds good, thanks for the clarification.
