### ISSUE TITLE
changing title & logo of website

### ISSUE THREAD

**Issue by Ebrahim1010** [DMPRoadmap/roadmap#2203]
Hi guys,

Please point me to the path to change the title and logo at the top of the website (see screenshot) and also the link(url) to the footer item (see screenshot
![Screen Shot 2019-08-07 at 11 35 10](https://user-images.githubusercontent.com/47170940/62612381-9065a180-b907-11e9-9217-ac7addb1e6bf.png)
)
![Screen Shot 2019-08-07 at 11 31 33](https://user-images.githubusercontent.com/47170940/62612257-58f6f500-b907-11e9-95fd-56ad44bf185c.png)

**Comment by briri** [comment]
those are both driven by the values you have in your `config/branding.yml` file
