### ISSUE TITLE
Published DMPs should export question text as well as sections

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2205]
In the UK context, public DMPs rarely make sense without the questions being exported too. We should adjust to the code to either:

1. Export questions by default
OR
2. Make the choice of exporting question configurable per instance

This is for the data at: https://dmponline.dcc.ac.uk/public_plans

@briri @mariapraetzellis do you have a preference? I think you only want sections in DMP export in USA

**Comment by akhmerov** [comment]
I believe this was recently fixed :tada:, at least both the example link works fine (as well as our dmponline).

**Comment by briri** [comment]
Related to https://github.com/DigitalCurationCentre/DMPonline-Service/issues/491
