### ISSUE TITLE
Enable SSL

### ISSUE THREAD

**Issue by Ebrahim1010** [DMPRoadmap/roadmap#2212]
Hi all,

Please provide me with a guideline for enabling SSL with the new website

Thank you

**Comment by xsrust** [comment]
Hi,

SSL is handled outside this webapp via a web server (such as nginx or Apache).  See instructions for configuring on their respective sites:
https://httpd.apache.org/docs/2.4/ssl/ssl_howto.html
https://nginx.org/en/docs/http/configuring_https_servers.html

Note, you'll also need a certificate for your domain to make this work.  If you don't have one already, check out https://letsencrypt.org/ to generate one for free.
