### ISSUE TITLE
Download users should show also the school/department field

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2213]
With new feature where the admins can add the departments/faculties to their organisation they should be also able to be able to download user files. This field is already shown in the list of users but not in the download yet.
 
![image](https://user-images.githubusercontent.com/47178106/63082730-e73e2d00-bf3e-11e9-9a62-00b13c4ffa80.png)

**Comment by xsrust** [comment]
Expected behavior:
The download (from the users-index page) of the list of users for an organisation should show each user's department.

Current behavior:
The download has no column (it's CSV) for department

**Comment by magdalenadrafiova** [comment]
I tested on TUDelft - made myself org admin added 'test department' added this into my profile and went to download users. I was able to see a new column and my defined department. Worked well.

**Comment by mariapraetzellis** [comment]
Tested this as well on York University and was able to download a list of users including their departments.

**Comment by sjDCC** [comment]
Perfect. Is working. Closing out
