### ISSUE TITLE
Removing debug message 

### ISSUE THREAD

**Issue by Ebrahim1010** [DMPRoadmap/roadmap#2215]
Good day,

How do I remove the debug message at the top left of my website.
<img width="659" alt="Screen Shot 2019-08-20 at 13 01 26" src="https://user-images.githubusercontent.com/47170940/63341976-ad0fc980-c34a-11e9-9c4f-00a5695c8670.png">

Thank you

**Comment by briri** [comment]
Hi @Ebrahim1010, the debug message should go away if you run your application in the 'production' environment. Rails runs in development mode by default.

You may find this resource helpful: https://guides.rubyonrails.org/configuring.html
