### ISSUE TITLE
Full Text Plans API Filtering

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#2217]
When querying the Full-Text plans API `api/v0/plans`, users would like to be able to filter the content.

Suggested filterable fields are:
1) Dates (creation and update)
2) Users (scope to a list of users's plans)
3) Funders (only Plans on a specific funder's templates) 
4) ID (pass a single, or list of IDs to export)

**Comment by briri** [comment]
merged in with latest release
