### ISSUE TITLE
Allow Document Upload at the Plan Level

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#2219]
We had a request to upload documents which pertain to the entire DMP, in-order to keep all DMP content in the one place.  (This would be separate to per-question uploads)

This seems feasible to handle through Dragonfly for now, and to refactor over to ActionStorage when we upgraid to Rails 5.

We will still need to think about:
Where/how to display/preview uploaded documents.
How to handle the export of DMPs with attached documents across our various formats.

**Comment by sjDCC** [comment]
Added to #2233 - duplicate issue
