### ISSUE TITLE
Installation Failure at "rake webpacker:yarn_install"

### ISSUE THREAD

**Issue by rimatzki-gfz-potsdam** [DMPRoadmap/roadmap#2220]
Please complete the following fields as applicable:

I get an error when setting up DMP Roadmap in installation step 6: 
_Install npm (node package manager) and Webpack and then bundle the assets (requires the installation of node.js). To install node dependencies, run the Webpacker rake task:

rake webpacker:yarn_install_

**Behaviour:**
$ rake webpacker:yarn_install
/home/rimatzki/.rvm/gems/ruby-2.6.3/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object/duplicable.rb:111: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
Usage: yarn [options]

yarn: error: no such option: --no-progress

**Steps to reproduce:**
$ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
$ rails --version
Rails 4.2.11.1
$ npm --version
6.10.2
$ npm install webpacker
[...]
+webpacker@4.4.0
$ yarn --version          
0.32

**Comment by xsrust** [comment]
Hi @rimatzki-gfz-potsdam 

I think your NPM version is the culprit,
I had a look and we're using `v8.x`

Thanks for pointing this out,  I'll make sure to update the installation instructions

**Comment by rimatzki-gfz-potsdam** [comment]
The lastes available version is 6.11.2, to which I updated now. The error still stays. As far as I can tell the --no-progress Option is not available to yarn anymore.

**Comment by rimatzki-gfz-potsdam** [comment]
$ nodejs --version
v8.10.0
$ node --version
v12.9.0

Forgot those.

**Comment by twei55** [comment]
If you have node version 12.9.0, your npm version should be 6.10.2. The yarn version seems to be  outdated, current version is 1.17.3, which supports the `--no-progress` option.

**Comment by xsrust** [comment]
I can also confirm that I'm using yarn 1.17.3.
Let me know if updating that fixes your problems, and I can update the wiki page

**Comment by aninder** [comment]
I was also getting an error during, 
rake webpacker:yarn_install
though a different error(node-sass was looking for python and failing)
my node version was 12.10.0
But when I moved to node version 10.14.1, it worked ok

**Comment by aninder** [comment]
currently my environment,
npm --version
6.4.1

ruby --version 
ruby 2.5.6p201


node --version
v10.14.1

nvm --version
0.34.0

./node_modules/.bin/yarn --version
1.17.3

**Comment by briri** [comment]
seems to no longer be a problem in the latest Rails 5 version
