### ISSUE TITLE
How to ammend text on create plan wizard

### ISSUE THREAD

**Issue by Ebrahim1010** [DMPRoadmap/roadmap#2221]
How does one change the text appearing in the create plan wizard?
for instance if I want to add an extra piece of information to this sentence 'No research organisation associated with this plan or my research organisation is not listed'.

I'm looking for the location for this file. I thought it was under the app/views/plans folder.

**Comment by xsrust** [comment]
Hi @Ebrahim1010 
You're looking in exactly the right spot.

For future reference, you can check the URL and then compare to the output of `rake routes` to find the controller-action responsible for rendering the HTML, and then follow through the chain of view-partials until you find the corresponding file.

In this case lvh.me/plans/new, corresponds to the `new` action of the `PlansController`
A quick look at that controller, and it renders the default form, so we're looking for `app/views/plans/new.html.erb`.

An alternative approach would be to use your editor of choice (or `grep`) to search for the text you want to modify.  We use gettext markup `_("<text>")`, so the text from the english version of the page should be easy to find within the code.
