### ISSUE TITLE
Rails 5.2 upgrade

### ISSUE THREAD

**Issue by benjaminfaure** [DMPRoadmap/roadmap#2228]
Hello everyone,

It seems that Rails 4 is no longer maintained, do you have a plan to upgrade DMPRoadmap to Rails 5.2 (or 6) ?

**Comment by weiweishi** [comment]
I am wondering if you have a timeline on this migration? Asking as we prepare for our new infrastructure needed for the roadmap migration. Much appreciated. @sjDCC

**Comment by weiweishi** [comment]
Along the same line if there's a plan to upgrade to current version of Ruby? (2.6 or 2.7?) thanks!

**Comment by mariapraetzellis** [comment]
We're working on doing this right now and will be our next release. This next release will include a Ruby upgrade to 2.6.
