### ISSUE TITLE
Relocate 'request feedback' button

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2234]
Many users don't see the 'request feedback' button as they don't consider sharing their plan until it is complete, Perhaps we could have a button or link in the uni header area which opens up this section of the UI.

We suggest this becomes its own top tab in between 'Write plan' and 'Share'
![Picture2](https://user-images.githubusercontent.com/6169940/65909894-7608eb00-e3c1-11e9-97e6-6582c553ecb9.png)

**Comment by johnpinto1** [comment]
Code in review .
**Screenshots:**

**Orgs that allow Feedback requests**
![Selection_037](https://user-images.githubusercontent.com/8876215/67766749-05e49800-fa47-11e9-9098-2b5fc5281c32.png)
![Selection_036](https://user-images.githubusercontent.com/8876215/67766757-0b41e280-fa47-11e9-9563-09e954b7df4c.png)

**Org that does not allow Feedback requests**
![Selection_038](https://user-images.githubusercontent.com/8876215/67766898-6b388900-fa47-11e9-9912-2adee6df8bff.png)

**Comment by sjDCC** [comment]
This looks really good. Thanks @johnpinto1 Closing out
