### ISSUE TITLE
Improving search function in admin area

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2236]
The admin > plans view only allows search by title. We should expand the search so it also allows the author name to be search, and displays the dept and searches this if in use by uni.
![Capture](https://user-images.githubusercontent.com/6169940/65237541-be2b3200-dad2-11e9-9a29-d86df3e4ba37.PNG)

In addition, the author names should be links so you can navigate through to see all the plans created by one user.

**Comment by xsrust** [comment]
I think this ticket should stick to improving the search options, and maybe offering some filtering options to enhance this functionality beyond text-matching.

(along with adding the links to the owner's edit profile page)
I've added #2240 to cover the list of user's plans, and other changes to the admin view of the user's profile.

**Comment by sjDCC** [comment]
Search is so much better now! Really great to be able to search by stems and across fields.

Closing out
