### ISSUE TITLE
Allow xml export

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2237]
Stockholm university want to get DMPs exported as XML to allow them to run them through a validator locally to test compliance with certain requirements.

Can we allow plans to be exported as XML

**Comment by pherterich** [comment]
We now have json download enabled which I believe is used to run any local validation scripts (potentially via a json to xml script, but well...), my assumption is that the json export going forward will address most use cases and I thus suggest closing this issue.
