### ISSUE TITLE
FastGettext locale setting error

### ISSUE THREAD

**Issue by raycarrick-ed** [DMPRoadmap/roadmap#224]
After a load and migration the FastGettext local setting looks bizarre. I changed the code in application.b as follows:

```
  def set_gettext_locale
    logger.debug ">>>>>>>>> SESSION LOCALE=" + session[:locale].pretty_inspect
    logger.debug ">>>>>>>>> FASTGETTEXT DEFAULT=" + FastGettext.default_locale.to_s
    #FastGettext.locale = session[:locale] || FastGettext.default_locale
    if session[:locale].present?
      logger.debug "seeing from session"
      FastGettext.locale = session[:locale]
    else
      logger.debug "seeing from default"
      FastGettext.locale = FastGettext.default_locale
    end
    logger.debug ">>>>>>>>> END LOCALE=" + FastGettext.locale.pretty_inspect
  end
```
and the resulting log output looks like this:

```
 >>>>>>>>> SESSION LOCALE="en_GB" 
 >>>>>>>>> FASTGETTEXT DEFAULT=
 seeing from session
>>>>>>>>> END LOCALE="de"
```
so the session setting is correct. As far as I can tell the way the locale is set is correct but it still comes out as 'de'

**Comment by raycarrick-ed** [comment]
after the migration as stands the languages are the old style en-GB and so it doesn't find en_GB which is in the session. rake migrate:fix_languages fixes it but it should be in the migration by default without an extra step

**Comment by briri** [comment]
This corrected my local version as well. Thanks @raycarrick-ed

**Comment by xsrust** [comment]
I updated the post-migration steps to reflect this

**Comment by vyruss** [comment]
Merged, closing (no UI component)
