### ISSUE TITLE
Improve admin view of users

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#2240]
- [Org, Super] Admins should be able to view, and visit, a list of user's plans
- [Org, Super] Admins should be able to update a user's department

**Comment by johnpinto1** [comment]
Code for review. Some screenshots of views:


**Super Admins' View:**
![Selection_029](https://user-images.githubusercontent.com/8876215/67292149-89980500-f4da-11e9-9b00-aafbb3607dfd.png)

**Org Admins' Views:**
![Selection_028](https://user-images.githubusercontent.com/8876215/67292257-b2b89580-f4da-11e9-9479-bd47681f601b.png)
![Selection_027](https://user-images.githubusercontent.com/8876215/67292259-b3512c00-f4da-11e9-9287-949da6c507e8.png)
![Selection_026](https://user-images.githubusercontent.com/8876215/67292262-b3e9c280-f4da-11e9-81f3-c765dcdb1f7b.png)

**Comment by sjDCC** [comment]
These look great, thanks @johnpinto1 

Two small improvement requests.
1. Can the Dept box be extended to align with the other fields
![align](https://user-images.githubusercontent.com/6169940/68217584-c683f180-ffda-11e9-9928-cb23f318acbc.PNG)

2. Can the number of plans column in the 'users' table link through to where admins can see the list of plans. They may not spot this otherwise
![Plan-link](https://user-images.githubusercontent.com/6169940/68217598-cb48a580-ffda-11e9-9742-62c76d4a3f3d.PNG)

**Comment by johnpinto1** [comment]
@sjdcc @xsrust Work in progress on this 
![Selection_050](https://user-images.githubusercontent.com/8876215/69154066-3dd77c00-0ad7-11ea-8576-70a79aa58205.png)
![Selection_051](https://user-images.githubusercontent.com/8876215/69154087-4465f380-0ad7-11ea-90ed-870d6320d1da.png)

Have a query with @xsrust about plans numbers that needs to be sorted before I push.

**Comment by magdalenadrafiova** [comment]
Could we make the department or school to expand like the other fields @xsrust @briri @raycarrick-ed  
![image](https://user-images.githubusercontent.com/47178106/69872678-fc508900-12ad-11ea-84b8-3c48fb2ad762.png)

the plans to be 'clickable' works well

**Comment by xsrust** [comment]
Odd.  This looks fixed in John's PR (and screenshots) from a few days ago.

There, John appears to be an org-admin.  Have you checked the functionality as a super-admin or as an org-admin?  In theory it should apply for both, but maybe it's been limited to one.  Different logic applies to each class of user, so its always best to ensure it's working for both classes of user.

**Comment by magdalenadrafiova** [comment]
@xsrust 
When I log in as super admin this is when the field is not expanded 
![image](https://user-images.githubusercontent.com/47178106/69956440-e7ffcc80-14f7-11ea-850a-5f85e6fba1bc.png)
but works for org admin 
![image](https://user-images.githubusercontent.com/47178106/69956557-3b721a80-14f8-11ea-9b36-b20a04cc2cb1.png)

**Comment by xsrust** [comment]
Thanks, There must be a discrepancy between the org-admin and super-admin views for that.
Since the ticket was John's, I'll have a look at this today & ping when there's a fix out
