### ISSUE TITLE
Remove Organisation

### ISSUE THREAD

**Issue by Ebrahim1010** [DMPRoadmap/roadmap#2241]
Hi guys,

I'm not getting the option to remove an organisation. I have removed organisations in the past.
Is there a reason for this and/or is there another way to get them removed? I'm only seeing the 'edit option'
<img width="1521" alt="Screen Shot 2019-09-23 at 13 09 37" src="https://user-images.githubusercontent.com/47170940/65421312-bab1e680-de03-11e9-9c0c-e74c6dcb9f97.png">

**Comment by briri** [comment]
Hi @Ebrahim1010, 

The option to delete an Org will only appear if the Org has no Users and no Templates. This is in place to prevent orphaned records from being created. If you would like to delete an Org you should first delete all of it's templates, guidance and then reassign its users to another organization.

**Comment by Ebrahim1010** [comment]
Great.
Is there a workaround for deleting the template?
<img width="1312" alt="Screen Shot 2020-01-31 at 07 38 54" src="https://user-images.githubusercontent.com/47170940/73515356-ae671700-43fd-11ea-9106-1e7574e1fdd3.png">

**Comment by xsrust** [comment]
@Ebrahim1010 
The rationelle for the org not having any templates, guidance, or users is to ensure no reccords are orphaned.

If you're removing an organisation, but you want to retain it's templates, you can just change the org_id on all of those templates in the database, the same as the users and guidances.

If instead, you'd like to `remove` the template from the front-end, but allow users who made plans based  on it to retain that access, you could associate the template with a different org, and then  set  the `archived`  flag on the template to true, hiding it from the front-end.

Finally, if you'd like to remove the template and not retain access to the users plans, you could just  destroy the template and any other objects which reference it (plans), along with any objects with reference to anything you've removed (roles, answers, notes).

Does that help at  all?
