### ISSUE TITLE
User is unable to download DMP into word

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2242]
We have received an email from a user saying that the download of word does not work. The errror message was: parsing error Position: Komponente word/document.xml The download to pdf works perfectly.

**Comment by briri** [comment]
I just gave this a try with a few plans and could not reproduce the error. Its possibly something specific to DMPonline or even a specific plan/template.

**Comment by magdalenadrafiova** [comment]
I will close this here and raise with Sam
