### ISSUE TITLE
Dowloading a docx export of a plan with non-latin chars gives a crazy filename

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2249]
Issue: Dowloading a docx export of a plan with non-latin chars gives a crazy filename

Description: Unicode not being used? 

Desired behaviour: Filename should fully match the plan title

**Comment by briri** [comment]
this is likely related to #2248

**Comment by sjDCC** [comment]
Covered in #2251 Closing out
