### ISSUE TITLE
Cannot save answers for a new plan based on a new template

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#225]
I created a new template with the following configuration:
- One phase (e.g. phase1)
- One section (e.g. section1 within phase1)
- and 7 question (e.g. textarea, textfield, radiobuttons, checkbox, dropdown, multiselectbox and date within section1).

Later I created a plan based on that template and when I was about answering the questions, the following error was raised:

![untitled](https://cloud.githubusercontent.com/assets/7393044/24746521/4a95b6be-1ab1-11e7-967d-2c5dd75352af.png)

which I fixed by changing from question.options to question.question_options (according to the Question model). However, it raises later on another error:
![untitled](https://cloud.githubusercontent.com/assets/7393044/24746609/a6300e16-1ab1-11e7-91f4-5bd01f2cb61e.png)

which I tried to fix too but I think, it involves more than a quick fix.

**Comment by vyruss** [comment]
@jollopre is this fixed by the time of PR #358 ?

**Comment by jollopre** [comment]
Yes, it has been fixed as part of #352
