### ISSUE TITLE
Downloads with long names of unusual non-latin characters don't have a filename extension

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2251]
Issue: Downloads with long names of unusual non-latin characters don't have a filename extension

Description: Can't open the file locally until filename extension is added manually

Desired behaviour: Make sure extension is added, by truncating the name if necessary

**Comment by sjDCC** [comment]
This seems to be working fine now. @magdalenadrafiova can you validate that the test I did matched the issue you encountered. if so, please close out.

![Capture](https://user-images.githubusercontent.com/6169940/68217903-575acd00-ffdb-11e9-9d2e-b0fba2a02c01.PNG)

![Capture](https://user-images.githubusercontent.com/6169940/68218083-ac96de80-ffdb-11e9-836f-f0038d0b512d.PNG)

**Comment by nicolasfranck** [comment]
Should we even try to use the plan title as the file name?
Why not simply use something like `plan_<plan_id>_phase_<phase_id>.pdf`?

It is more opaque, but at least more condense, readable, and it leaves
nothing up to surprise (maybe someone will add emoticons to their title?)

cf. https://github.com/DMPRoadmap/roadmap/blob/cabe6d3201c76f51a5a9ac278bfcd2c8e694fdf2/app/controllers/plan_exports_controller.rb#L101

Users already refer to the plan url, which includes the id.
