### ISSUE TITLE
DMPRoadmap integration with research systems

### ISSUE THREAD

**Issue by norman-smith** [DMPRoadmap/roadmap#2254]
Please complete the following fields as applicable:
Hi, 

I'd like to determine if DMPRoadmap has the capability of integrating with an application called Converis which is a research management information system developed by Clarivate analytics.

I look forward to your feedback.

Regards
Norman

**Comment by mariapraetzellis** [comment]
Hi Norman,
Thanks for reaching out. I'm the product manager for the DMPTool, one of the primary partners in the DMPRoadmap. 

Can we set up a call to discuss what type of integration you think would be useful for Converis? We are doing a lot of work currently with integrations, APIs, and machine actionable data management plans, so it is quite possible that some sort of collaboration would be possible. You can reach me directly at maria.praetzellis@ucop.edu.

Look forward to hearing from you,
Maria

**Comment by norman-smith** [comment]
Hi Maria

Thanks so much for your response.
I will be in touch.

Regards
Norman
