### ISSUE TITLE
Plan sharing with users who don't have an account

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#2260]
Please complete the following fields as applicable:

**Expected behaviour:**

User shares plan with project peer who doesn't have an account on DMPonline. Project peer receives email notification and follows links to create new account. When they log in, they see shared plan on their list of plans.

**Actual behaviour:**

One recent user from the University of Manchester said she followed the links within the notification to create new account but when she logged in, she couldn't see the plan.

**Steps to reproduce:**

Share plan with new user (perhaps one of us but with different email address, if any of us has any spare email addresses left to create a new user). Follow links in notification to check out the workflow and try to figure out where confusion may occur. I shared a plan with myself. The link within the notification email took me to the DMPonline home page with the 'sign-in' tab on display. If the system is able to tell that it's dealing with a new user, maybe the link should take them to the 'create new account' tab instead? Not sure. 

Sam said the workflow is as follows:
- when a plan is shared with a person who doesn't have an account, a 'dummy account' is created on the system, with the email address that has been used for sharing
- this 'dummy account' will be validated when the new account is created
- if the person who receives the plan sharing notification doesn't follow the links within the notification to create a new account, the 'dummy account' is deleted. The plan is shared with the 'dummy account' and therefore the new user can't see it, even though they are using the right email address.

I hope this makes sense.

I remember receiving queries like these before. On a quick search of the mailbox there was one in May last year from a user Greg Simpson at Royal Holloway. I couldn't find a corresponding issue on github; maybe we didn't raise one at the time.

Not sure whether it's worth re-thinking the workflow or just living with the problem.

Diana

**Comment by sjDCC** [comment]
Close out
