### ISSUE TITLE
Linking shibboleth account, but getting same sign in form

### ISSUE THREAD

**Issue by mirkh** [DMPRoadmap/roadmap#2278]
We configured shibboleth and got the button "Sign in with your institutional credentials" as we should. Were able to use the sign in form under "Do you have a DMPRoadmap account?" to login.

I get a notice
Your account has been successfully linked to your institutional credentials. You will now be able to sign in with them.

When I logout, every **second** time I don't get the option "Sign in with your institutional credentials", and can only sign in using the system credentials, and every other second time I can link my institutional credentials. 

I never get the option to sign in using my institutional credentials. How does that sign in form look like?

This is just like in this issue #2182 except for that I have the correct password.

I think we have missed something in our setup and would like to know if you have any ideas of what to do to learn what we missed. We [used the guide](https://github.com/DMPRoadmap/roadmap/wiki/OAuth-Providers). Did not add anything in the locale file though.

**Comment by briri** [comment]
Hi @mirkh,

Can you check in your database to see if the system has actually stored your shibboleth id (also known as an EPPN) in the `user_identifiers` table? After a successfully Shibboleth login it should be placing that identifier in the table and connected to your correct user account.

When you say that "you do not get the option" to sign in with institutional credentials after logging out do you mean that the button does not appear on the screen?  If you could also upload a few screen shots it might help us better understand the situation you are dealing with.

**Comment by mirkh** [comment]
Thanks for your reply @briri 
I realize that we have not gotten our config correct yet. The linking of institutional credentials never goes further to shibboleth. No data is saved in the user_identifiers table. I was probably too fast in sending a question here. I'll be back when I understand it better. :)

**Comment by mirkh** [comment]
When I am logged in and click "Link your institutional credentials" I never get to the IDP. I just get a notice that my account is linked. When I turn on debug, HTTP_SHIB_HANDLER: shows https://mysite/Shibboleth.sso which is there and working.

**Comment by briri** [comment]
Hi @mirkh,

Have you added the organization's Shibboleth entityID into the `org_identifiers` table? Shib needs that to figure out which IdP to send the user to. If that is set up you can also turn up your logging for shibd to see if you can get more specific error information on its side. Here is the info on that. Its been really helpful for us in the past with figuring out what's going on with the Shib handshakes: https://wiki.shibboleth.net/confluence/display/SP3/Logging

**Comment by mirkh** [comment]
Hi @briri 
No, nothing in org_identifiers at all. Where can I find documentation about that?

But we got one step further. Apache config was preventing /users/auth/shibboleth/callback from redirecting to our IDP. Fixed that, and now get through to IDP.

Got a new problem, Shibboleth.sso is not responding anymore, but I get a 404 error.

Thanks for the tip about debug from shibd.

**Comment by mirkh** [comment]
Ok, got Shibboleth.sso response again after adding ProxyPass to apache config.
Next problem is maybe because of the config in devise.rb. I authenticate with shibboleth, but it is not saved.

**Comment by mirkh** [comment]
Hi again. I have got it working now.
Added ShibUseHeaders to apache config.
After restarting apache and DMP I finally could see real data coming from the idp, and was able to see what the variables/attributes are called. Added them to devise.rb, restarted, and was finally getting the forms/pages in the correct order:

1. On DMP page there is a login button for shibboleth
2. Clicking there sends me to logging in via shibboleth
3. On DMP page, I see the form to login to my DMP account and link it to my org credentials
4. I get info that my accounts have been linked.

**Comment by briri** [comment]
excellent. glad you were able to get this working. Shib can be a difficult set up. 

Also, thanks for letting us know what you had to do to get it working. I'm going to add some of this to our troubleshooting wiki page. It will likely help others in the future!

**Comment by briri** [comment]
@mirkh  Updated the troubleshooting guide with some Shibboleth specific info.

https://github.com/DMPRoadmap/roadmap/wiki/Troubleshooting

If you have a chance to review and let me know if you can think of any other useful debug/troubleshooting info, we would greatly appreciate it!
