### ISSUE TITLE
Template phase details title details not updating

### ISSUE THREAD

**Issue by Ebrahim1010** [DMPRoadmap/roadmap#2279]
Please complete the following fields as applicable:

**Expected behaviour:**
The title of phase details section should change when updating it
**Actual behaviour:**
Ttile does not change after editing and saving. The change exists under preview changes but not when creating a new plan using this template. Instead of saying 'CeBER Student Outline DMP', it says 'write plan' See screenshots.

<img width="1234" alt="Screen Shot 2019-11-13 at 13 45 49" src="https://user-images.githubusercontent.com/47170940/68761163-2eaa8700-061c-11ea-8da5-1ba0504ae33f.png">
<img width="1270" alt="Screen Shot 2019-11-13 at 13 46 08" src="https://user-images.githubusercontent.com/47170940/68761164-2f431d80-061c-11ea-9ea9-f256176438e7.png">

**Comment by sjDCC** [comment]
Hi @Ebrahim1010 This is a default in the code. It only gives the title when there is more than one phase. Closing out
