### ISSUE TITLE
Automatically uncheck institutional questions (customisations) on funder template export

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#228]
If researchers are writing a DMP for their funder, any additional questions asked by their institution (i.e. customisations of the template by adding a section with questions) should be automatically unchecked on export. Some funders are very specific about what is included in a DMP so these guidelines should be adhered to. I'm pretty sure this setting used to be in place but it doesn't appear to be working now.

**Comment by vyruss** [comment]
`modifiable` flag in `section`s can tell us which sections come from the original funder template so we can only select those.

**Comment by briri** [comment]
closing as this is part of the overall changes being made by @xsrust for #498
