### ISSUE TITLE
Is the reCAPTCHA supposed to be involved in user registration?

### ISSUE THREAD

**Issue by mirkh** [DMPRoadmap/roadmap#2281]
I don't see any setting to enable reCAPTCHA. 

Is there supposed to be a reCAPTCHA to prevent robot registrations?

Is there any documentation for how to enable it?

---
Ok, I just found the recaptcha.rb.example

I'll check it out and if I don't get it working I'll be back tomorrow :)

Thanks,
Maria

**Comment by briri** [comment]
Hi @mirkh, the recaptcha functionality is currently only on the 'contact us' page. It should be fairly easy to add to the new user registration if you'd like. 

We gladly welcome contributions to the codebase, so if you do intend to add it to your new user registration page, consider sending us a PR. 

If you are willing to send a PR, here are a few suggestions:
- Add a new variable that will enable/disable the display of the recaptcha (see example below)
- Move the recaptcha code currently on the contact_us partials into a new partial in the 'views/shared/'  dir and have both the contact_us and new user registration views defer to the new partial
- Make sure any related tests are still passing

**Comment by mirkh** [comment]
@briri thanks for your reply! You wrote "see example below", did you forget to add something, or was the stuff underneath your example?

**Comment by briri** [comment]
oh ha ha! :) Sorry about that. Here is the example of how we handle optional functionality in the codebase:

Add a new variable to config/application.rb
```ruby
module DMPRoadmap
  class Application < Rails::Application

    # Display a reCaptcha on the new user registration form. The default is 'false'
    config.show_recaptcha_on_user_registration = false

    ...

  end
end
```
Then on the view you can do the following (using the recaptcha stuff has been moved into a new shared partial):
```ruby
<% if Rails.application.config. config.show_recaptcha_on_user_registration %>
  <%= render partial: 'shared/recaptcha' ... etc. %>
<% end %>
```

**Comment by briri** [comment]
If you do send us a PR, please note this issue number in the PR. Thanks @mirkh

**Comment by mirkh** [comment]
Thanks a lot @briri! I'm not going to be able to do anything useful in getting reCAPTCHA for registration this year at least, very busy with all our systems. I know this is not the correct thread, but that thread is closed: I wanted to say that the stuff you added for extra help with getting shibboleth working was good, but I still miss some information. If I'd like to contribute to it or write some comments, where should I do that?

Another question, maybe should be its own thread, it's about user registration though. Is there a way to disable the current user registration and go 100% with the organization's own credentials via shibboleth? Via shibboleth you get a lot of data about the person, and we would like only users who have an organization account to be able to register.

**Comment by briri** [comment]
hi @mirkh.

I'm not sure what the best approach would be to have you contribute suggestions to our Shibboleth wiki page. Github doesn't allow PRs for those pages unfortunately. Can you open a new ticket and let us know what your suggestions are?

There's not a way to disable the regular email/password login option in the app configuration. The system however is setup to allow you to easily customize views. We added some code to the base ApplicationController class that forces it to first look in the `app/views/branded/' directory for any views or partials. 
So for example, if you copy `app/views/shared/_access_controls.html.erb` into `app/views/branded/shared/_access_controls.html.erb`. You could then just have it render the institutional credentials button and add any messaging that's appropriate.

That's also a good approach to adding the reCaptcha to the registration page. Here's some more info on branding/customizing your installation:
https://github.com/DMPRoadmap/roadmap/wiki/Branding

**Comment by mirkh** [comment]
Hi, @briri, 
Thanks for pointing me to branding documentation! I did a test, copying
`app/views/layouts/_footer.html.erb` to `app/views/branded/layouts/_footer.html.erb` 
and changed the branded version. Is there anything else you have to do to make it be read? I did stop and start the roadmap service. The footer only changes if I edit the "original" one.

Also I often fail to restart the server, getting the following result:

```
$ sudo systemctl status roadmap
● roadmap.service - DMP roadmap service
   Loaded: loaded (/etc/systemd/system/roadmap.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Mon 2020-02-03 17:19:59 CET; 13s ago
  Process: 21268 ExecStart=/usr/local/roadmap/etc/roadmap.initd start (code=exited, status=0/SUCCESS)
  Process: 21279 ExecStop=/usr/local/roadmap/etc/roadmap.initd stop (code=exited, status=0/SUCCESS)
 Main PID: 21274 (code=exited, status=0/SUCCESS)

feb 03 17:19:57 dmp roadmap.initd[21268]:   Language Load (0.3ms)  SELECT  `languages`.* FROM `languages`
feb 03 17:19:59 dmp roadmap.initd[21268]:   IdentifierScheme Load (0.3ms)  SELECT `identifier_schemes`.*
feb 03 17:19:59 dmp roadmap.initd[21268]:   TokenPermissionType Load (0.3ms)  SELECT  `token_permission_t
feb 03 17:19:59 dmp roadmap.initd[21268]:   TokenPermissionType Load (0.4ms)  SELECT  `token_permission_t
feb 03 17:19:59 dmp roadmap.initd[21268]:   TokenPermissionType Load (0.2ms)  SELECT  `token_permission_t
feb 03 17:19:59 dmp roadmap.initd[21268]:   TokenPermissionType Load (0.3ms)  SELECT  `token_permission_t
feb 03 17:19:59 dmp roadmap.initd[21268]: success
feb 03 17:19:59 dmp systemd[1]: Started DMP roadmap service.
feb 03 17:19:59 dmp roadmap.initd[21279]: $Stopping roadmap.initd: failure
feb 03 17:19:59 dmp systemd[1]: roadmap.service: Succeeded.
```

Do you recognize that?

**Comment by briri** [comment]
Hi @mirkh,

I'm not sure what you mean when you say "changed the branded version". The logic that allows files in that `app/branded/` folder to override the regular files is pretty straightforward and lives in the `app/controllers/application_controller.rb` file in the `prepend_view_paths` function. The location of your footer file looks correct and that should be all you need for it to get picked up and used.

Check your production deployment to make sure that the branded file was deployed properly and lives in that `app/views/branded/layouts` folder.

It may be helpful to have a look at the [DMPTool branding](https://github.com/CDLUC3/dmptool/tree/master/app/views/branded). We have a lot of changes to the public facing pages in that code base.

As for the systemd error you're receiving, we aren't able to offer support for local installations of the code. So we can't really help you with things like systemd or passenger/puma/apache/nginx configurations. 
Sometimes those failures happen when you've got a missing pid file or a rogue instance of the app running that was started outside of systemd. I would try a `ps aux | grep ruby` or something similar to manually nil any processes and then trying to start the service via systemd again.

**Comment by mirkh** [comment]
Hi @briri,

I did the following

1. copied `app/views/layouts/_footer.html.erb` to `app/views/branded/layouts/_footer.html.erb`
2. made changes to `app/views/branded/layouts/_footer.html.erb`
3. restarted the app

still getting the version from `app/views/layouts/_footer.html.erb`
This might not be strange as I'm totally new to ruby and how to deploy it. But did I do the correct steps? Thanks!

**Comment by briri** [comment]
Yes, that should do it, so I think there must be something else going on.

Can you attach the code from your `_footer.html.erb` (the branded one)?  We can have a look at it and see if there's maybe an issue there.

If you're running on your local development machine then you shouldn't need to restart the app since Rails will auto-reload files. If its deployed and running in a non-development mode you would need to restart the app.

My only other suggestion would be to check the log files to see if any errors are being raised and to see which files are being rendered. For example:
`I, [2020-02-03T21:07:26.310334 #882]  INFO -- :   Rendered home/_welcome.html.erb (0.5ms)`

**Comment by mirkh** [comment]
Hi @briri, 
Today I understood that my deployment was wrong in some way making the branding not working.
Thank you for trying to help me, it's not easy, there are many details that can go wrong :)

**Comment by briri** [comment]
Glad you got it working @mirkh!
