### ISSUE TITLE
Problem generating usage statistics

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#2285]
Reported on #1243 and  #1301 by @Ebrahim1010

https://user-images.githubusercontent.com/47170940/69637953-6543c100-1062-11ea-9898-615544fe0221.png

** Problem ** 
> Updated API access on the user admin section. But I still see the notification about the API when trying to generate the stats.
> we updated the Update the db/seeds.rb and now have access to run my own filter but cannot generate any stats.

**Comment by xsrust** [comment]
Hi @Ebrahim1010,

There are a few things that need to be in place before the usage-statistics dashboard will work for a given user.
1) Their org needs to have access to the `statistics` `TokenPermissionType`
This can be added through the rails console with: (assuming `org` is an `Org` object)
`org.token_permission_types << TokenPermissionType.STATISTICS`
2) Their account needs to have the api permission: (assuming `user` is a `User` object)
`user.perms << Perm.use_api`
3) You need to populate the statistics tables.  This can be acomplished by running `rake stat:build` (outwith the rails console).  This needs  to be re-run monthly to keep the data in-sync.

Let me know if that fixes your problem, and we can capture the above information in a Wiki page

**Comment by Ebrahim1010** [comment]
Hi @xsrust,

How do we set org to a value. it's currently a variable. 
receiving error undefined local variable org.

**Comment by xsrust** [comment]
hi @Ebrahim1010 

Yep, org and user are variables.
you will need to assign them to an Org/User object before you can use those variables.
They will both be unassigned(and undefined) until you give them a value.

As I don't know your users/orgs/who your trying to give API access to, I can't assist with selecting those.  

Are you asking generically about how to select an object from the DB?
If you know the ID associated, you can use `find` https://guides.rubyonrails.org/active_record_querying.html#find.
Or if you just know some properties of the object, you can use `find_by` https://guides.rubyonrails.org/active_record_querying.html#find-by
