### ISSUE TITLE
Changes to an Organization's Shibboleth identifier does not save

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2288]
Please complete the following fields as applicable:

This was discovered in the DMPTool [issue260](https://github.com/CDLUC3/dmptool/issues/260). It is only applicable to installations that filter the list of organisations that can be used for institutional login (as opposed to directing the user to a federation's organisation selector)

**Expected behaviour:**
When an application has the `shibboleth_use_filtered_discovery_service` in their config/application.rb set to true, the super admin's 'Edit Organization' page displays a 'Shibboleth entity id' and 'Shibboleth domain' field.
You should be able to change these values multiple times.

**Actual behaviour:**
The initial entries into these fields are properly saved, but any subsequent changes do not get saved.

**Steps to reproduce:**
- Make sure your config/application.rb `shibboleth_use_filtered_discovery_service` is set to true. (requires a restart of the application)
- Login as a super admin
- Navigate to the Admin -> Organisations page
- Edit one of your organizations
- Add an entry into the Shibboleth fields and save
- Try to change these values and click save (you will receive a success message but the Ship fields will retain their original value

**Comment by sjDCC** [comment]
One for you to test @mariapraetzellis

**Comment by briri** [comment]
this appears to be working now. 

@mariapraetzellis is out until Friday so am going to close so that we can get the release out. Will reopen a new ticket if necessary

**Comment by mariapraetzellis** [comment]
Looks like this bug is back. When trying to edit the `Shibboleth - entityID` changes are not saved when I navigate back to the page.

**Comment by mariapraetzellis** [comment]
Confirming that I can now edit shib info successfully.
