### ISSUE TITLE
 ‘Assign’ plans to particular people

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2291]
This originally came from TUDelf. It will be nice if organisational admins could ‘assign’ plans to particular people within the org admins group. And then the admins could see the name of this person in the org admin plans overview: https://dmponline.tudelft.nl/org_admin/plans (adding an extra column ‘Assigned to’ and showing names).

**Comment by magdalenadrafiova** [comment]
Raised this on the roadmap - https://github.com/DMPRoadmap/roadmap/issues/2291 
closing out here

**Comment by magdalenadrafiova** [comment]
also see #2313

**Comment by sjDCC** [comment]
Covered by https://github.com/DMPRoadmap/roadmap/issues/2365
