### ISSUE TITLE
Check new one-click plan creation feature from OPIDoR

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2296]

**Comment by sjDCC** [comment]
This looks good, but I encountered a few issues:

1. It's not obvious to the user what the buttons do and the hovertext and accessibility note overlap. Should we rename the column "Create plan"
![Picture1](https://user-images.githubusercontent.com/6169940/70072323-ac93f980-15ee-11ea-85df-83b2506ec5fc.png)

2. When I click to create a plan or copy the link into a new window, I get the right pop-up notification but clicking "Yes" doesn't work. A new window opens instead. No plan is created. 
![capture-2](https://user-images.githubusercontent.com/6169940/70072389-d0573f80-15ee-11ea-80e5-ca9b41a2fffc.PNG)

**Comment by briri** [comment]
thanks @sjDCC will have a look at this today

**Comment by briri** [comment]
I updated the column header to read 'Create a new plan' and added a tooltip for the copy icon that reads 'Copy link to create a new plan'.

@sjDCC the overlap with the 'opens in a new window' and the create plan confirmation window appear to be specific to DMPonline. I cannot repeat them with the vanilla Roadmap code. Here are the screenshots of what I'm seeing:
<img width="1386" alt="Screen Shot 2019-12-03 at 3 43 32 PM" src="https://user-images.githubusercontent.com/1204467/70099814-ce887e80-15e4-11ea-8e73-1c8afef630c1.png">
<img width="582" alt="Screen Shot 2019-12-03 at 3 44 00 PM" src="https://user-images.githubusercontent.com/1204467/70099815-ce887e80-15e4-11ea-900a-e3894c8fe5f1.png">
<img width="683" alt="Screen Shot 2019-12-03 at 3 43 50 PM" src="https://user-images.githubusercontent.com/1204467/70099816-ce887e80-15e4-11ea-82f9-25a41ff3f437.png">

**Comment by benjaminfaure** [comment]
Thank you for your feedback @sjDCC. If we contribute again in the near future, I will try to pay more attention to the accessibility.  We mostly rely on the work you did :) . Do you have some guidelines that we could follow, something that you could put in the Contribute wiki page maybe ? (If it's not already there !)

**Comment by sjDCC** [comment]
Don't worry @benjaminfaure I think these accessibility features are new so you won't have seen them. They're not deployed yet.

@briri Thanks for the change to the column title - looks good. We're you deploying from -dev as those accessibility features should be common, not specific to DMPonline branding. And were you getting an issue with popup not generating a plan? @xsrust could you check if anything is down to our deployment

**Comment by briri** [comment]
@benjaminfaure we will try to write up some accessibility guidelines in the near future

@sjDCC I was running against the development branch. 

@xsrust Those 'opens in a new window' messages look like they will only appear if the link will send you to a different domain, so I'm not sure why @sjDCC was seeing that.

**Comment by raycarrick-ed** [comment]
Seems to be down to an error in getting the current HOSTNAME in app/views/layouts/application.html.erb. Then the link is checked against this value to see if the link is local or not. If it isn't local then it gets opened in a new window but since it always thinks everything is non local .........

**Comment by mariapraetzellis** [comment]
This may have a one-line bug but would be a quick fix. Waiting till the New Year to review with Sam.

**Comment by sjDCC** [comment]
@raycarrick-ed to check the one-line hostname fix is in and then move to UAT

**Comment by mariapraetzellis** [comment]
This is likely part of the conditional questions issue https://github.com/DMPRoadmap/roadmap/issues/1772. @raycarrick-ed to confirm.

**Comment by magdalenadrafiova** [comment]
@xsrust I am not sure whether I am looking at the right thing - but it seems I am missing loads of things Sarah can see 
![image](https://user-images.githubusercontent.com/47178106/73654811-82a99280-4684-11ea-9c16-52606b510d40.png)

**Comment by magdalenadrafiova** [comment]
https://dmponline-dev.dcc.ac.uk/public_templates > the page opens well 

![image](https://user-images.githubusercontent.com/47178106/73665142-88a96e80-4698-11ea-9e07-1bcf53c3fa6a.png)

& when I click on create a new plan a new window opens 
![image](https://user-images.githubusercontent.com/47178106/73665225-a7a80080-4698-11ea-9d98-c30e4fe5225b.png)

works well closing this
