### ISSUE TITLE
Issue with display of 'Opens in new window' tooltip when viewing guidance

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2305]
Please complete the following fields as applicable:

**Expected behaviour:**
The 'Opens in new window' tooltip is visible/readable

**Actual behaviour:**
If the guidance has a link at the bottom, the tooltip is obscured by the surrounding container.

**Steps to reproduce:**
- Login
- Create a new plan based on the default template (click 'no research org' and 'no funder')
- Make sure that the DMPTool/DCC guidance is selected
- Go to the 'Write Plan' tab
- Expand the 'Selection and Preservation' section
- Click on the DMPTool/DCC guidance tab of the 1st question
- Expand the 'Preservation' themed guidance
- Hover your mouse over the last hyperlink in the guidance

**Comment by briri** [comment]
Sample of this issue from:
<img width="700" alt="Screen Shot 2020-01-07 at 8 49 45 AM" src="https://user-images.githubusercontent.com/1204467/71912717-e47ce800-312a-11ea-9cd8-121bfe6dd5a8.png">

**Comment by mariapraetzellis** [comment]
Brian to take a look this week.

**Comment by martaribeiro** [comment]
test

**Comment by sjDCC** [comment]
Tooltips don't always display in mobile phone. Maybe use 'title' in html file instead?

**Comment by magdalenadrafiova** [comment]
Toolitp was visible and appeared over the text on which I hovered. Worked well.

**Comment by mariapraetzellis** [comment]
Looks good to me as well

**Comment by sjDCC** [comment]
Tooltip is wrapping for me too. Closing out
