### ISSUE TITLE
Cannot change/update permissions for sharing plan

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#231]
I can share a plan with designated Co-owner, Editor, or Read only permissions. But when I attempt to change the permissions using the drop-down it only updates to the new selection if I choose a higher level of permission, so e.g. I can successfully change from Editor to Co-owner but cannot downgrade permissions. 

Each time I select a new permission level I receive a "Sharing details successfully updated" message whether they have been updated or not

![screen shot 2017-04-10 at 8 15 52 pm](https://cloud.githubusercontent.com/assets/12703638/24891521/27474aba-1e2b-11e7-8276-a82798636df0.png)

**Comment by briri** [comment]
The email message it sends out also has a spacing issue. Add a space between 'have' and the permission level:
"Your permissions relating to"stability test (Horizon 2020 DMP)" have changed. You now haveco-owner access."

**Comment by stephaniesimms** [comment]
This is working as expected. Remaining issues w/permissions #219 and #220 Closing this issue.
