### ISSUE TITLE
Faculty names - populating by admins

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2313]
@xsrust @raycarrick-ed @martaribeiro 
 
this might relate to #2292 - https://github.com/DMPRoadmap/roadmap/issues/2292 we have received a request from TUDelft with the following points: 

- Is there a way how we, as admins, can populate the faculty names instead of asking this to our users?
- Would it be possible to add the faculty name to the details of the PI in the ‘Project details’ section?
- Will the faculty name be added to the new, full content API so we can perform searches in which the faculty name is included?

**Comment by sjDCC** [comment]
Covered by API on schools and departments
