### ISSUE TITLE
Warn Org admin when Funder Template is updated

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#232]
We need to notify Org admins when the Funder Template that they've customised changes. This leaves their customisation as is but should give them a warning.

1. Red text warning them of change on the Org admin:Templates:Customisations page.
2. Email notification when this system has been implemented.

**Comment by stephaniesimms** [comment]
@sjDCC I like the suggestion to flag changes to funder templates somewhere in the Admin UI, but I would like this to be a Super Admin function where we have control over the flag. I often make very minor changes like updating links that don't warrant a flag and so I don't want an automatic trigger. Currently, I notify admins of significant changes via blog and email comms. Funder changes are so infrequent that this approach has worked fine to date.

I prefer not to include an email notification w/in the system and just continue to do this manually owing to infrequency and reasons above. Thoughts?

**Comment by stephaniesimms** [comment]
update: spoke w/UX about including an email notification that a Super Admin can trigger manually to notify Org Admins of significant changes to funder templates

**Comment by stephaniesimms** [comment]
will be addressed as part of global notifications work. closing issue.
