### ISSUE TITLE
Adding glossary definitions as mouseovers

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#233]
On DMPTuuli, the consortium have added a glossary of terms. Ideally the definitions would appear as mouseover popups when these terms are used. Currently they link out to each definition box under: http://libraryguides.helsinki.fi/rdm/glossary#s-lg-box-wrapper-16688424 

![capture](https://cloud.githubusercontent.com/assets/6169940/24913381/ecab874c-1ec8-11e7-9c4a-f1deebdeec8a.PNG)

**Comment by briri** [comment]
Do these tips appear when editing a template, plan, both or somewhere else entirely? At what point would they be displayed (e.g. after the user has finished typing and saves their changes? While they are typing the text?)

**Comment by sjDCC** [comment]
It's on the front end for end users when they're creating a plan. I expected them to be in the question area, but currently the links are in the guidance text. That may be because it's the only place they could add them for now though. 

Will double check exactly what was needed, but I suspect it's in static text presented in the template (specifically question area and maybe guidance?), not anything the text that the user types to create the plan e.g. 
![capture](https://cloud.githubusercontent.com/assets/6169940/24921330/57058750-1ee2-11e7-962d-3e3c8271a66b.PNG)

**Comment by sjDCC** [comment]
Description of the mouse-over function from the Finns:

End-user perspective: Difficult terms are underlined and when you put mouse cursor over the term a short description will popup (like this: http://www.wickham43.net/hoverpopups.php) There is also available a list of short descriptions used in the DMPtool  as a glossary (it can be a tab like there are “Home”, “About”, “Help”.

Admin perspective: You can choose which term you choose and create a short description.  If there are already description available you can choose it from the list. You will control when the description box is available an when not.  You can determine the language of the term and description. The system will automatically create a glossary of terms (your input is the term and description). Every language available in the tool will get a glossary of their own. 

It would be nice, if we could link terms meaning the same thing together. So you could see the term and description in many languages. At the glossary page there are short intro where we explain how the glossary is generated and the nature of descriptions (not definitions of the terms but brief explanation or example.) 

Comment from @sjDCC: think we would need to define one glossary per instance so admin functionality would be at super admin level not org admin. Maybe options to turn on/off full glossary or selected terms at org_admin level though depending on their user experience and needs?

**Comment by magdalenadrafiova** [comment]
@pherterich @mariapraetzellis @dsisu I think from our usability testing the feedback was that some of the terminology is not clear for the administrators (and that might potentially apply to users) 
We might: 
- reconsider how we call certain things in DMPonline
- or/and add explanation to these e.g. explaining to administrators what are the phases in the template, etc.
