### ISSUE TITLE
Upgrade/Unpeg yarn dependencies

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2332]
We have specific versions pegged in the `package.json` file which is preventing us from upgrading to the latest. For example Tinymce is pegged at 4.8.3 and 5.1.4 is the latest. 

I noticed this when researching a deprecation warning in Firefox for a method call within tinymce's JS. https://github.com/tinymce/tinymce/issues/5083

We should do this either before or during the Rails 5 upgrade

**Comment by xsrust** [comment]
I'd like to leave this to after Rails5 and go through the upgrade instructions for each package we upgrade.
