### ISSUE TITLE
Make flash[:notice] display as html

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#234]
Make sure all of the pages are displaying the contents of `flash[:notice]` as either `raw` or `.html_safe`. The new generic errors messaging uses line breaks to separate issues. E.g. `Unable to create the plan<br/>The title is a required field`

originally reported in #172

**Comment by briri** [comment]
related to #236

**Comment by stephaniesimms** [comment]
@briri I no longer see html but the error message is not populating the field with the incorrect input in the example below. Is this what it's supposed to do?

![screen shot 2017-04-24 at 5 53 02 pm](https://cloud.githubusercontent.com/assets/12703638/25364405/2640d158-2917-11e7-9bf6-eee29005608f.png)

**Comment by briri** [comment]
I'm not sure what you mean when you say "not populating the field with the incorrect input". Its reporting that you did not provide a valid email address.

**Comment by vyruss** [comment]
@briri I think it refers to `contact_email` not receiving the value `bogus@email.com` ?

**Comment by stephaniesimms** [comment]
@briri yes, what @vyruss said.
contact_email not receiving the value bogus@email.com

**Comment by stephaniesimms** [comment]
Working as expected. Closing issue.
