### ISSUE TITLE
guidance on project details page

### ISSUE THREAD

**Issue by Ebrahim1010** [DMPRoadmap/roadmap#2340]
Please complete the following fields as applicable:

Can the guidance on the fields in the project details page be changed for specific templates with the DMP tool or will changing it become the default for each template?

![project-details-page](https://user-images.githubusercontent.com/47170940/71898272-90412a80-3161-11ea-89da-40d1273923fc.png)

**Comment by briri** [comment]
Hi @Ebrahim1010 those are `tooltips` and changing them would be global (for all templates/plans). Guidance selections typically appear on the right hand side of that page and it looks like you may not have any defined yet. 

You can refer to the following guides to help determine how to setup guidance:
- https://github.com/CDLUC3/dmptool/wiki/creating-guidance
- https://github.com/CDLUC3/dmptool/wiki/themes

Note that guidance uses the concept of `themes` to connect your guidance to relevant questions on a template. The themes listed on the link above are specific to our installation and your's may differ. You can check out the Admin Features -> Themes section of your site (must be logged in as a super admin) for your specific themes.

**Comment by Ebrahim1010** [comment]
Hi @briri thank you for the swift response. I've been trying but I don't think I've really cracked how the guidance works.
Is it possible to add additional guidance to the project details section of a template?

**Comment by briri** [comment]
Hi @Ebrahim1010 if you want to change the tooltips (text in those black boxes) then you should:
- Make a copy of the `app/views/plans/_edit_details.html.erb` file and place it into `app/views/branded/plans/_edit_details.html.erb`. The code is designed to look for files. This gives you the opportunity to override the core code without worrying about it being overridden any time you pull down the latest version of DMPRoadmap.
- Open your copy of the file, search for the text you want to change and then update it. 

Note that you may need to restart your server.
