### ISSUE TITLE
Agreement to T&Cs not enforced

### ISSUE THREAD

**Issue by raycarrick-ed** [DMPRoadmap/roadmap#2341]
Please complete the following fields as applicable:

**Expected behaviour:**
When creating an account, if you don't tick the "I accept the terms and conditions" checkbox you should get an error.

**Actual behaviour:**
Just goes ahead and creates the account.

**Steps to reproduce:**
Create new account and don't check the T&Cs box.

**Comment by raycarrick-ed** [comment]
Found this when investigating the rogue account creation issue on Tuuli. The account were being set up even though the T&Cs were not ticked.
Fixed in:

https://github.com/DMPRoadmap/roadmap/tree/issue2341

**Comment by sjDCC** [comment]
@xsrust Has this been deployed to test? Doesn't seem to be working
