### ISSUE TITLE
Improvements to the Usage Statistics page and graphs 

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2343]
The current Usage Statistics page layout is not intuitive and it is not obvious that the filter is not connected to the graphs below. 

We propose that the filter lets the admin define settings which are then visualized in graphs, with possibility to click through to get more information / interrogate the underlying data. 

![Usage Graph](https://user-images.githubusercontent.com/27511575/72103529-3dd94880-32de-11ea-85ab-dacc266c2eee.png)

This involves:
1. linking the filter and graphics below
2. Remove the "Topic" from the filter. Users will then only be able to select a date span. 
3. Investigate JS library through which charts are created to see if we can offer a click through experience to investigate the underlying data

This issue builds on https://github.com/DMPRoadmap/roadmap/issues/1678.

**Comment by sjDCC** [comment]
Agreed actions on 31/03 call

- remove filter as stats are gathered monthly
- add a filter to the user / plans page tables
- try to give a click though from graph to user / plans page (investigate javascript library)

**Comment by mariapraetzellis** [comment]
We will break out filter to the user / plans page tables & click through to separate tickets

**Comment by sjDCC** [comment]
Filter removed which was main work left in this ticket so closing out
