### ISSUE TITLE
Changes to downloading usage reports 

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2345]
We would like organizational admins to have the ability to download **all usage reports** in a single location and/or CSV file. 

A prior ticket (https://github.com/DMPRoadmap/roadmap/issues/1690) discussed including the following stats:

- Org users per month
- Org plans per month
- Org plans by template #1679
- Org plans downloads and shares #1745
- Org plans for which feedback was requested #1759

Should cover all historical data for the org, numbers/month

Please Investigate gems to see if we could have one downloadable CSV with tabs for each report.

Alternatively, we could have a dropdown list of reports within the application. 

Additionally, **please remove the ability to "Download global usage" CSV from the web application for organizational admins**. **This feature should only be present for Super Admins**. We can replace the "Download global usage" button with a new "Download usage" button that only contains the statics above related to the specific organization. 

![screenshot-docs google com-2020 01 09-14_07_43](https://user-images.githubusercontent.com/27511575/72108897-73cffa00-32e9-11ea-8489-471a44ae6838.png)

**Comment by briri** [comment]
We will need to verify that the `exported_plans` table is collecting all plan downloads. My production table just has 'pdf' entries (it could be that our users aren't downloading in other formats). We do not collect historical statistics on # of shares, so would need to add that.

**Comment by xsrust** [comment]
Re: `explorted_plans` only having PDF entries
This is the same on our services as well from early 2018.  I had a look to see where we create the entries, and the helper-function looks ok:
https://github.com/DMPRoadmap/roadmap/blob/84eb63fad24d6d4d67aee388e58b429949c3beaf/app/models/concerns/exportable_plan.rb#L177-L189
So I dug a bit deeper, and it's only being called in the above `prepare(coversheet: false)` method
Which is called from both the `as_pdf` and `as_csv` methods. 
These get called from the `plan_exports_controller` 
https://github.com/DMPRoadmap/roadmap/blob/84eb63fad24d6d4d67aee388e58b429949c3beaf/app/controllers/plan_exports_controller.rb#L30
with a second call for CSV exports in:
https://github.com/DMPRoadmap/roadmap/blob/84eb63fad24d6d4d67aee388e58b429949c3beaf/app/controllers/plan_exports_controller.rb#L55
But they all get a format of PDF from the final call in the concern.

We should do a quick refactor to ensure we aren't double-generating, and that we pass through the format for recording properly.

**Comment by xsrust** [comment]
Unfortunately, we'd need to use something like Excel formatting to support Tabs, or use multiple documents to express the tabs, which could then be imported as different 'sheets'.

I think we could do most of this in CSV though with the following format, and all data but the month being counts:
`month, new plans, new users, downloads, org plans shared, plans shared with users`
The last two are the count of users your org's plans have been shared with, and the number of plans shared with users belonging to your org.  They're subtly different, so let me know if only one is needed.

I've left the count for `feedback_requested` off until we refactor the review process.  We don't currently track any historical data on the feedbacks, and can only tell whether or not a plan is currently requesting feedback.

I also left out the plans_by_template view out for now, as this would likely benefit from being a separate download next to the corresponding chart.  We can also do the same with the funder-chart added in #1682 for the usage of organisational templates

**Comment by xsrust** [comment]
Added in models/services/tasks for the `StatSharedPlan` and `StatExportedPlan`.

Looks like the `rake stat:build` task is now taking 40+ mins locally for a full re-build:
```
# time rake stat:build

real	41m50.335s
user	7m11.850s
sys	1m13.110s
```

**Comment by magdalenadrafiova** [comment]
Works well - I downloaded the csv, I tried all three downloads and it worked well for all. 
I am just not sure what the first empty row stands for. 
https://github.com/DMPRoadmap/roadmap/projects/5

**Comment by mariapraetzellis** [comment]
@xsrust I checked on dmponline-test and dev but I don't see this feature to UAT. Is it deployed?

**Comment by xsrust** [comment]
Hi @mariapraetzellis  
This is deployed to DMPonline-dev to UAT.  
The CSV can be downloaded from the `Download Monthly Usage` Button on the usage-dashboard:
![Screenshot_20200324_100407](https://user-images.githubusercontent.com/7352616/77413294-021b2e80-6db7-11ea-8f98-990023f07aa5.png)

This should have the fields `Month`, `New Plans`, `New Users`, `Downloads`, and `Plans Shared`.  The dataset should range from the creation of the organization through to the last month.

**Comment by sjDCC** [comment]
The download monthly usage button works fine for me though I wonder if we should rename it. They get data per month but it is for all time e.g. a year of more, not just one month. Should we call it something like "Download usage overview" Thoughts @magdalenadrafiova @mariapraetzellis 

A couple of other questions / comments:

1. What is the csv download field separator? I couldn't understand this.
![what-is-this](https://user-images.githubusercontent.com/6169940/77415868-fd587980-6dba-11ea-8f29-539022be002e.PNG)

2. We said we should remove the 'Download global usage' option for most users. We really only want super-admins to get the comparison across organisations

3. The first tab "Statistics on your template" always had no data to display. This may be because -dev data is out of data or perhaps we need to set the default to last 12 months?
![Capture](https://user-images.githubusercontent.com/6169940/77415760-d732d980-6dba-11ea-9f0b-93f229a46ed3.PNG)

**Comment by raycarrick-ed** [comment]
By default the CSV file is a set of comma separated fields (that's a a kinda obvious statement really!) e.g.

field one, field two, field three

someone had requested the ability to use a different separator. This is quite a common thing with CSV files - it's handy for people to be able to use different field separators -  and so the menu allows you to choose between a set of the most commonly used field separators. So if you choose # the data will look like

field one#field two#field three

**Comment by sjDCC** [comment]
Sorry @raycarrick-ed Hadn't realised you'd replied. Just edited my earlier comment to remove things I realise are now defunct. 

Have figured out what CSV separator was via ticket #2375 and realised the download global usage is displaying correctly. I was logged in as super admin but when I tested as org admin this was removed. Have taken out those two questions and just left the one remaining valid one

Thanks all :)

**Comment by xsrust** [comment]
@sjDCC the lack of data is indeed because of the lack of sync of DMPonline and DMPonline-dev's Databases.  
I'll have a look today about refreshing the data and re-running the statistics generation task.  I have defaulted this to 12 months and left no way to change this at the moment as I don't expect a single organisation to have too many templates to make sense of.

**Comment by sjDCC** [comment]
ok, I figure this can be closed out then? Main issue is working
