### ISSUE TITLE
Create a super admin view of the Plans report 

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2346]
Currently it is difficult to get a high level view into all plans being created via the application. 

It would be very helpful to quickly get a report of all plans created. I think this can be done simply by creating a new Super Admin view for the Plans page that generates the same table but with data from all Organizations. 
![screenshot-dmptool org-2020 01 09-14_55_15](https://user-images.githubusercontent.com/27511575/72111731-7da92b80-32f0-11ea-9b1b-92925a6826a1.png)

**Comment by sjDCC** [comment]
Download would list the same column options as existing download plan export for normal org admins

**Comment by mariapraetzellis** [comment]
Download all plans would take too long and take too much server capacity. So skipping that feature.

**Comment by mariapraetzellis** [comment]
When we move to rails 5 we could generate the all plans report download 1/day

**Comment by sjDCC** [comment]
Plans page on DMPonline-test gives a 404 so can't test this curently

![Capture](https://user-images.githubusercontent.com/6169940/80207864-e9589f80-8626-11ea-862b-29f80fb5b7d7.PNG)

**Comment by xsrust** [comment]
@sjDCC The 404 is resolved and the page should now load.

**Comment by sjDCC** [comment]
Page now loads but reading back up ticket I'm assuming there isn't a change to check as we didn't add a super-admin download button?

Having columns for created and updated dates looks good now @briri

**Comment by briri** [comment]
Right. The download button only appears for Org Admins. It was taking too long to generate the full list of users. A note was made above to revisit after we've moved to Rails 5. It has some new features that would facilitate us pre-generating the full report nightly so that it is downloadable for Super Admins

**Comment by sjDCC** [comment]
Ok, will close now and add a new ticket to generate a super admin download post rails 5

**Comment by briri** [comment]
just added #2498 to keep track @sjDCC
