### ISSUE TITLE
User view error

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#235]
This is the error I mentioned I get when trying to view my profile and rights
![error-user-view](https://cloud.githubusercontent.com/assets/6169940/24920782/64524af8-1ee0-11e7-84bc-98160b669886.PNG)

**Comment by stephaniesimms** [comment]
I also get this error when I click Edit user in the Super Admin area. Moving this back @vyruss

**Comment by vyruss** [comment]
@jollopre can you please look at c7bca5f87b0974f7ca6599ba81d81b499f62711a , 183c315359e4e372b527e2f02b00e9426b8f95ae ?

**Comment by jollopre** [comment]
done! Ready for PR

**Comment by stephaniesimms** [comment]
Working as expected. Closing out.
