### ISSUE TITLE
Add Orcid/Shibboleth display to admin display of user-accounts

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#2353]
Currently, it is not possible for an org/super-admin to tell if a user has connected their shibboleth or ORCiD accounts to their profile.

We should add either a display of this information, or a display with the ability to modify/remove (if that's desired), to the admin view of editing the user-profile.

**Comment by raycarrick-ed** [comment]
https://github.com/DMPRoadmap/roadmap/tree/issue%232353_display_user_identifiers

adds an "identifier" column which displays and user identifiers both scheme name and actual identifier

**Comment by raycarrick-ed** [comment]
Now checked in with:

https://github.com/DMPRoadmap/roadmap/tree/issue_2353

add user identifiers to the user admin table

**Comment by sjDCC** [comment]
I can't see this on DMPonline-test. There's no identifiers column in the user table, nor do I see it in their profile page. Can you point me to where I should be looking?

![identifiers-column](https://user-images.githubusercontent.com/6169940/80208150-81568900-8627-11ea-8d1c-ef541b2c9909.PNG)
![user](https://user-images.githubusercontent.com/6169940/80208152-81ef1f80-8627-11ea-8c9b-72f4b1637751.PNG)

**Comment by briri** [comment]
@raycarrick-ed changes were likely impacted by the change to the way Identifiers are stored in the database. I will have a look today

**Comment by sjDCC** [comment]
I don't see this on -test or -dev so it may need a dev check

**Comment by sjDCC** [comment]
I see this in the table view now as below.
![shib](https://user-images.githubusercontent.com/6169940/83777002-cdfa9e80-a680-11ea-82c4-42230974337f.PNG)

There isn't an ability for admins to modify/remove it as it doesn't show on the profile page we see for users, but I'm not sure that's needed.
![profile](https://user-images.githubusercontent.com/6169940/83777293-23cf4680-a681-11ea-9774-7dc0b7f3f9f2.PNG)


Thoughts @mariapraetzellis @magdalenadrafiova

**Comment by mariapraetzellis** [comment]
I don't think we'd ever need to edit a Shib ID, or actually to view the full ID at all. Knowing that a user has enabled shib for their account is good information though.

 I was wondering if we could just note that their account is utilizing Shibboleth in the table? This could be a y/n column or we could keep the Identifiers column and just make a link to the Shib id and display text that reads "Shibbolized" . What do you think @sjDCC ?

The ORCID information is appearing and is helpful to include in the table, but I noticed it's formatted to display in the center of the cell. Would be best to left justify so we use less space.

**Comment by raycarrick-ed** [comment]
The above rgu example is "correct". They have a shibboleth identifier listed which is the same as their email. Digging into it a little further there are 487 users where the users email is the same as their shib identifier.
