### ISSUE TITLE
Default language on user-account-edit differs from application default

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#2362]
When a new user to the tool first updates their profile, the language box will default to the first  returned from the database.  

Our logic for this page's default language is:
`current_user.language.nil? ? Language.id_for(FastGettext.default_locale) : current_user.language.id`

The `id_for` function is defined as:
`Language.where(abbreviation: abbreviation).pluck(:id).first`

**Comment by xsrust** [comment]
It looks like this is once-again due to the fast-get-text vs i18n discrepancy in naming schemes
the default_locale according to gettext is en_GB, whereas the abbreviation is en-GB.

Given we  have  a  `Language.default` column in the database, I'm going to swap to pulling this in, rather than attempting to use  the  language configured in Gettext.

**Comment by magdalenadrafiova** [comment]
I am not sure whether this is the desired behaviour 
![image](https://user-images.githubusercontent.com/47178106/73654512-d23b8e80-4683-11ea-8a5f-ff33461901f8.png)

**Comment by magdalenadrafiova** [comment]
sam to look at still

**Comment by magdalenadrafiova** [comment]
works well - thank you - created new account and the language was this time set up as English 
![image](https://user-images.githubusercontent.com/47178106/74328367-a1dfa880-4d85-11ea-8489-05a85b719625.png)

**Comment by sjDCC** [comment]
Good for me
