### ISSUE TITLE
Utrecht user group - Plan ownership issue 

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2368]
@xsrust 
The current logic behind the ownership of the plan is that when a user leaves/changes the institution in their profile, any DMPs also transfer as they are owned by the original creator. This means the plans will disappear from institutional statistics and administrator view permissions are lost. Institutions would like to have access to the plan, even when the user changes their affiliation, since the data may still be stored there and the plan approvals and funding assignment is linked to the institution the researcher was based at when they created the plan. In order to do this, we will need to update the terms and conditions for our users to make clear that affiliated institutions will retain access.

**Comment by briri** [comment]
This should be fairly easy to do. We already have a text field to store the plan id and a funder id. It would be good to just make them associations to actual org records rather than free text fields that the user enters

**Comment by mariapraetzellis** [comment]
Need to look at terms and conditions that users agree to when using the application to see if we need to modify t&c in light of this new feature.

**Comment by briri** [comment]
easy to add the link but need to investigate side affects of this across the site (e.g. feedback, stats, etc.). Basically need to evaluate every place where we get the org from the owner and determine whether we should be using the user's org or the this new plan org.

**Comment by briri** [comment]
adding the org_id to the plans table for the ROR/Fundref ticket

**Comment by pherterich** [comment]
This seems to describe the same issue as #2112 so maybe these tickets can be merged.

**Comment by briri** [comment]
Yes. Thanks for noting that @pherterich. We added the connection between plans and orgs as part of the maDMP changes.
