### ISSUE TITLE
Hide language switcher in Edit Profile if only one language installed

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#237]
Related to #110 - We should also hide the language switcher or remove this field entirely from the Edit Profile page if only one language is installed (screenshot below). Also note that there is no closed parenthesis in English (GB...

![screen shot 2017-04-11 at 2 35 42 pm](https://cloud.githubusercontent.com/assets/12703638/24931988/51483966-1ec4-11e7-86bc-04a38d9bc1ff.png)

**Comment by briri** [comment]
Just copied over the logic @jollopre added to the navigation bar's language dropdown

**Comment by stephaniesimms** [comment]
Tested w/assistance from @briri on backend and working as expected. Closing out.
