### ISSUE TITLE
inconsistent "Template" name upon export

### ISSUE THREAD

**Issue by Falco-KUB** [DMPRoadmap/roadmap#2371]
When exporting a DMP, some of the information on the printed cover page seems inconsistent.

**Expected behaviour:**
When exporting a DMP, the printed "Template" name on the cover page should match the name of the template used when creating the DMP.

**Actual behaviour:**
In some cases, the funder or the organisation is printed as "Template" name instead of the actual template.

**Steps to reproduce:**
See e.g. the following public DMP's:
- "Students Behaviour towards Research" (should be Population Research Committee Template but prints "Mr Dimakatso Pilusa")
- "Deep Reinforcement Learning for Robot Hand-Eye Coordination" (should be DCC template but prints "Edge Hill University")
- "FARSYD - FArming SYstems as tool to support policies for effective conservation and management of high nature value farmlanDs" (should be DCC template but prints "European Regional Development Fund (FEDER) & the Portuguese Science Foundation (FCT)")

**Comment by rosiehigman** [comment]
We are experiencing this bug as well. I think the desired behaviour for us is that the funder and template are both printed on the coversheet with the correct labels assigned to each.

**Comment by sjDCC** [comment]
Changed and looks good. Doesn't work retrospectively for old plans but that's fine.

Thanks for flagging @Falco-KUB and @rosiehigman 

![Capture](https://user-images.githubusercontent.com/6169940/74167626-6ecfd480-4c20-11ea-8b3c-83481cf3edcc.PNG)
