### ISSUE TITLE
Delimiter to pipe in usage statititics instead of comma 

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2375]
is it possible to change the delimiter in the export of the usage statistics to,for example a ‘pipe’ | instead of comma

**Comment by sjDCC** [comment]
@magdalenadrafiova to check if this is a duplicate ticket and reopen if necessary

**Comment by sjDCC** [comment]
@briri @xsrust was this one done or should we move to in progress?

**Comment by xsrust** [comment]
This has not been worked on.

**Comment by raycarrick-ed** [comment]
Moving to review

**Comment by magdalenadrafiova** [comment]
I like the fact that now when I sign in as an org admin I am able to choose field separator. This works well. 

A point: download global usage statistics is still available even when I log in just as an administrator. I think this should be only limited now to super admins.

**Comment by briri** [comment]
@xsrust addressed the issue of org admins being able to see the 'global usage stats' download button in a different ticket. I'm not sure if he has deployed that yet though

**Comment by mariapraetzellis** [comment]
Looks to be working as expected. As an org admin I am able to define the separator and successfully download the stats w/ the character in place.

**Comment by sjDCC** [comment]
I now know what this field is for ;-)

Works well. Closing out
