### ISSUE TITLE
Add an deactivate option to the notification system

### ISSUE THREAD

**Issue by martaribeiro** [DMPRoadmap/roadmap#2382]
There isn't an option to deactivate the notification once one has finished the downtime. Therefore the notification needs to be delete it instead.

One way to fix the issue would be to set an hour for the notification to expire, but it can be a problem with the time stamp in the server. Might be simpler to just had an active/inactive flag that can be changes as needed.

**Comment by sjDCC** [comment]
Waiting til Wednesday to merge to run Mart through process

**Comment by mariapraetzellis** [comment]
Brian will take a look and review this.

**Comment by sjDCC** [comment]
All works fine. Closing out
