### ISSUE TITLE
Do you have a recommended deployment method for production?

### ISSUE THREAD

**Issue by mirkh** [DMPRoadmap/roadmap#2386]
Hello,

As a newbie to rails (I work mostly in Perl and PHP) I would love to get information about one or two recommended deployment methods for running DMP roadmap in production. 

At the moment when I run rails server with the `--daemon` option it doesn't read the branded templates. Without that option, it reads the branded templates.

Are there any examples on how someone else is running it?

Thanks! / Maria

**Comment by briri** [comment]
Hi Maria,
We use [Capistrano](https://capistranorb.com) to manage our deployments for the [DMPTool](https://github.com/CDLUC3/dmptool). I highly recommend this tool along with a pattern of storing any sensitive config info (e.g. your `config/database.yml` file, config/initializers/devise.rb file, etc.) in a private Git repo and then letting Capistrano splice those files in during deployment.

On the server side we have a load balancer which sends traffic to Apache (https web server) running on each host which handles all incoming traffic and then reverse proxies the requests to an Nginx+Passenger (app server) that runs our Rails app. 

I've heard good things about Puma as an alternative to Passenger and it seems to be the way Rails is moving by default in versions 5+. We will likely be moving in that direction later this year.

**Comment by sjDCC** [comment]
Hi @mirkh Hope @briri's response helps. I'm going to close this out but let us know if the issue wasn't addressed. All best. Sarah
