### ISSUE TITLE
Build out API v1 - Phase one

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2390]
Phase one of the API v1 changes involves setup of the basic infrastructure and a few initial endpoints.

### Infrastructure:
- Introduce JSON Web Token (JWT) security for system to system communications. Which will use a `client_id` and `client_secret` for initial auth and then a JWT in further requests.
- Create a new `api_client` table to handle JWT machine to machine security
- Allow access to the API for both ApiClients (systems) and Users
- Create new views that follow the [RDA common metadata standard for DMPs](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard/tree/v1.0)
- Create views that output the RDA common metadata standard for DMPs

### Endpoints
- Build out `POST /api/v1/authenticate` - to authenticate the user and return a JWT
- ~~Build out `GET /api/v1/plans` - to retrieve a list of DMPs~~ This one will come later
- Build out `GET /api/v1/plans/[:id]` - to retrieve a DMP
- Build out `POST /api/v1/plans` - to create a DMP

**Comment by briri** [comment]
This ticket will also provide a `GET /api/v1/templates` endpoint that returns the titles, descriptions, versions and owning organization names for all public templates.

Will create further tickets for carrying the existing API v0 functionality into API v1 (e.g. full text API, etc.)

**Comment by briri** [comment]
The v1 API uses JWT authorization and allows both the existing User `email` + `api_token` or the new ApiClient (for systems that need to communicate with DMPRoadmap) `client_id` + `client_secret`.

**Comment by sjDCC** [comment]
Deployed out to DMPtool stage for testing with RAMS

**Comment by sjDCC** [comment]
Is this one the devs can approve please @xsrust Need a tutorial on APIs to do this myself!

**Comment by sjDCC** [comment]
Closing this based on dev check
