### ISSUE TITLE
Create ability to merge duplicate organizations 

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2398]
With the new ability for users to add organizations to the database when creating their account or modifying their profile (https://github.com/DMPRoadmap/roadmap/issues/2339) will also come the creation of duplicate entries for organizations. We will need a new means for super admins to merge duplicate orgs in the database. This new feature could be modeled after the existing feature to merge user accounts (https://github.com/DMPRoadmap/roadmap/issues/2245).

**Comment by briri** [comment]
Allow Super Admins to update ROR and Fundref ids

**Comment by briri** [comment]
@mariapraetzellis can we close this out?
