### ISSUE TITLE
Customise export for questions

### ISSUE THREAD

**Issue by raycarrick-ed** [DMPRoadmap/roadmap#240]
Need to allow for site wide customisation of whether questions and answres are exported or just answers.

**Comment by sjDCC** [comment]
Consensus from consultation with user group so far is that the user should be given the option on export settings. We may wish to implement a default so boxes are (un)checked automatically. Perhaps do that per template or just site wide? See discussion at: https://www.jiscmail.ac.uk/cgi-bin/webadmin?A1=ind1704&L=DMPONLINE-USER-GROUP&X=59F7745C19A8B246AD&Y=sarah.jones%40glasgow.ac.uk

**Comment by vyruss** [comment]
I believe it should become an option on the export page which can be ticked/unticked by default per installation.

**Comment by briri** [comment]
@xsrust and @JEK-III if this has been resolved by the work done in #498 then please close otherwise consider addressing it as part of that ticket

**Comment by xsrust** [comment]
This appears to be addressed in #498
