### ISSUE TITLE
Conditional questions - editing template on test site 

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2405]
Please complete the following fields as applicable:

**Expected behaviour:**
When going to dmponline-test I would expect to be able to edit the template

**Actual behaviour:**
When I tried to edit the template the following error message appeared
<img width="1920" alt="Screenshot 2020-02-25 at 14 35 19" src="https://user-images.githubusercontent.com/47178106/75257686-3a8e1380-57dd-11ea-9335-eb064994eb71.png">
When I clicked on re-order section the above message appeared and I was not able to go back to the template to edit 

**Steps to reproduce:**
If possible to make it 're-order' sections not sensitive - when this button is pressed it is not possible to go back and do further edits. When I go completely out of the template and restart the editing I am able to edit. It is only when I hit re-order sections when I am unable to apply any changes to the template

**Comment by sjDCC** [comment]
Which template did this apply to? I was able to login fine and add conditions

**Comment by magdalenadrafiova** [comment]
I was able to log in fine and add conditions too - this only appeared when I clicked on re-order sections

**Comment by raycarrick-ed** [comment]
Looking at the logs it seems like in the process of reordering it hit an unprotected nil. Not sure where it is coming from so if it recurs we may need to dig in further.
Guard added in:
https://github.com/DMPRoadmap/roadmap/commit/3f03f8e074fccf19a9523df035971c22c77e045a

**Comment by sjDCC** [comment]
Template edit and section reordering all working fine now

Closing out
