### ISSUE TITLE
Check token validation / expiration on plan sharing

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2407]
Some users encounter issues when a plan has been shared with them and they don't follow the link to sign up to the tool.

If they come to register later, the tool doesn't allow them to sign up as they haven't followed the invitation link.

The invitation should expire OR if they come up to register not via the invitation, this action should invalidate the invitation and remove any access permissions to the shared plan

The user should always be able to register

**Comment by sjDCC** [comment]
Same issue as #2422. Think it may be fixed as creating an account is possible now when a previous unused plan share invite has been issued.

Close out both?

**Comment by mariapraetzellis** [comment]
We're not sure if this is still an issue. @briri will check and update the issue.
