### ISSUE TITLE
Update Project Details to accommodate contributors

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2408]
A new table, `contributors`, was added as part of #2349. 

The new Contributors model uses the [CRediT Taxonomy](https://casrai.org/credit/) for contributor role types.

We need to add a new section that allows a user to identify additional contributors to their project. The section should work similar to the 'links' section on the Org details page with a button/link to add another and 'x' buttons to remove them as needed.

Generate an upgrade task that converts existing PIs and Data Contacts into Contributors.

We will also need to update any code that creates or copies a new plan and have it assign the owner/creator as the Data Contact (aka `data_curation` role) and Author (aka `writing_original_draft` role).

We must either update the existing Share tab and have it manage contributor records for the following (add/remove/change role):
- Co-owner --> `writing_original_draft`
- Editor --> `writing_review_editing` (possibly?)
- Commenter --> No contributor role
OR we should consolidate the the contributor section on the Share tab with the new Contributors tab.

Also need to determine if a 'Feedback' reviewer should be assigned the `writing_review_editing` contributor role.

**Comment by briri** [comment]
Here is a screenshot of a proposed new tab that allows researchers to define contributors:
<img width="1329" alt="Screen Shot 2020-03-16 at 3 14 56 PM" src="https://user-images.githubusercontent.com/1204467/76804193-eac9b900-6798-11ea-9c58-1a70e50e5328.png">

We will need a blurb at the top that explains who these contributors are and why they should tell us about them.

First though, we need to determine whether 'contributors' are defined as 'the people working on/with the DMP itself', 'the people involved with the project' or some combination of the 2.

Who can add/edit/remove contributors? I have it set to owners and co-owners only for now.

**Comment by mariapraetzellis** [comment]
@sjDCC @magdalenadrafiova @mariapraetzellis To come up with text that explains to users who needs to be added to the Contributors list to make it clear what we're looking for.

**Comment by mariapraetzellis** [comment]
Considering "Please list the project’s Principle Investigator(s) and those responsible for data management." @sjDCC what do you think?

**Comment by sjDCC** [comment]
I think the PI should be auto-listed as the person who created the plan. They can then edit if they have another role. Better to avoid them having a completely blank table at first.

If we roll this in with the plan co-authoring feature, perhaps text like:

"Please list project collaborators to ensure credit for contributions and assign authoring / viewing permissions for the DMP"

**Comment by briri** [comment]
consolidated the PI change with the list on #2481

**Comment by sjDCC** [comment]
Request captured in new ticket so closing out
