### ISSUE TITLE
Add Start and End dates to Project Details

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2409]
The [RDA Common Standard](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard/tree/v1.0#funding_tree) includes a Project start and end date. The fields have been added to the table as part of #2390.

We should add fields to the Project Details page to capture this information from users.

**Comment by sjDCC** [comment]
Looks good @briri 

I have a couple of suggestions about layout of this page but they're most likely best addressed in future when we do usability rework. We're planning to move guidance configuration so I think this page would work best as two columns if that's not probelmatic. All the project metadata could stay on the left where it is and the IDs from DMP ID downwards could shift to the right in place of guidance. This would avoid too much scroll for the user

Can the funder be pre-populated too? Especially if we have asked that to choose the template

![Capture](https://user-images.githubusercontent.com/6169940/80208589-705a4780-8628-11ea-86dc-48b61df3d80a.PNG)

**Comment by briri** [comment]
Moving the guidance selection sounds like a good approach.

The funder should pre-populate when the user creates the plan (if the template owner is a funder). It uses the new Identifier database records. I will spend some time today making sure our upgrade scripts back-fill these for existing plans.

**Comment by briri** [comment]
See #2482 for the layout changes

**Comment by sjDCC** [comment]
Closing out as new layout is covered in new ticket

**Comment by Falco-KUB** [comment]
The project details (Project Start, Project End, ID and Grant Number / URL) do not seem to appear on the coversheet when exporting the DMP - I think it would be great if they were included.
