### ISSUE TITLE
Answer is not editable unless you created it

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#241]
The policy behind the answer editing only allows the user who created the answer to edit. We want anyone who has been givien the editor role to be able to change answers.

@sjDCC verified that the collaborators should be able to edit

**Comment by briri** [comment]
Ok, so further research into this shows some issues with the presence of user_id as a foreign key on the answers table.

Here's the scenario:
- User A creates a plan and answers question 1 of that plan
- User A then shares that plan with User B and allows them to edit the plan
- User B logs in and sees User A's answer to the question.
- User B amends the question and saves it.
- User A reloads the plan page but does not see User B's amendment
- User A then makes their own amendment to the question and saves it
- User B reloads the screen and sees their amendment but does not see User A's new changes

When User A answers the question a record is added to the answers table with their user_id populated.
When User B opened the plan (before they made changes) it gave them User A's record. When they made changes and saved though it created a new record in the answers table with their user_id.
Each subsequent reload of the page grabs the logged in user's copy of the answer.

I think we could fix this by simply removing the foreign key relationship between users and answers. We don't have a need to store the history of an answer, so having only a single answer (per question) on the plan should be fine.

@raycarrick-ed  does this sound reasonable? If so I will tackle it tomorrow. I'll also add an integration test for this complex workflow.

**Comment by vyruss** [comment]
@briri I don't think it's a foreign key issue at all - after all they're there to ensure referential integrity not access to objects. I discussed it with @xsrust and he found that the `update` action in `answers_controller` is: 
```ruby
@answer = Answer.find_by(
                       plan_id: plan_id,
                       user_id: user_id,
                       question_id: question_id)```
whereas the answer should be identified just by `plan_id` and `question_id` without `user_id` (only useful for showing who answered). Therefore removing `user_id` from the `.find_by` should be an easy fix which won't require a migration unless we're missing something.

**Comment by xsrust** [comment]
the way this is meant to be implemented is by having a single answer per plan.  I think that it is likely the logic in the answers_controller that is bugged.  The answer is selected by:
`@answer = Answer.find_by(
                        plan_id: plan_id,
                        user_id: user_id,
                        question_id: question_id)`
and if there is no answer found for that, a new one is created.  
answers should in fact be selected just based off of plan and question id's, and the user_id is just for display on the frontend.
It seems like a logic issue rather than a foreign key one

**Comment by sjDCC** [comment]
@briri In response to: "We don't have a need to store the history of an answer, so having only a single answer (per question) on the plan should be fine."
I think Marta kept a record of each answer intentionally to support versioning but we hadn't implemented this and I'm not sure it needs to be done at a question level anyhow so assume it's safe to go

**Comment by briri** [comment]
Ok. I'll give that a try. I'll make sure that the user_id gets updated each time so that the "updated # by so and so" message is accurate.

**Comment by briri** [comment]
that worked @xsrust. Thanks. 

I noticed while testing that the policy wasn't firing so I updated the policy file so that it gets picked up now. Also tweaked the end user notification so that the text area they see when a lock happens is wider and the text messaging is localised

**Comment by briri** [comment]
While building out the integration tests realized that it is not catch race conditions on create (its working now on update). Will finish up tomorrow.

**Comment by briri** [comment]
Ok everything should be working now. Added integration tests for answer race conditions and fixed functional answers_controller test

**Comment by stephaniesimms** [comment]
Working as expected. Closing out.
