### ISSUE TITLE
RSS news feed is broken

### ISSUE THREAD

**Issue by benjaminfaure** [DMPRoadmap/roadmap#2411]
Hello everyone, 

DMP OPIDoR have been using the RSS feed for our own news. It seems to be broken since Feedjira 3.0.
The `Feed.fetch_and_parse` method has been removed in this version. 

https://github.com/DMPRoadmap/roadmap/blob/a54f85a85ddd50d5d0e0a0814c120d6d8dc6d1f8/app/controllers/static_pages_controller.rb#L5-L12

There is two ways of fixing this : 
1. Fixing the gem version to V2.2.0
2. Include the HTTParty gem and change the code as shown in the README : https://github.com/feedjira/feedjira/blob/master/README.md 

I tested the second solution, it seems to work without too much changes. 
Should I send you a PR ?

**Comment by briri** [comment]
Hey @benjaminfaure 
I just took a look and noticed that the RSS feed isn't even used anymore on that un-branded about_us page. I submitted a PR #2412 to remove Feedjira and that code block

**Comment by mariapraetzellis** [comment]
@briri are we good to close this issue?

**Comment by briri** [comment]
yes. thanks
