### ISSUE TITLE
usage_controller throws fatal error

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#2413]
Please complete the following fields as applicable:

**Expected behaviour:**

**Actual behaviour:**

When accessing the route `/usage`, the controller
returns the error:

```
NoMethodError at /usage
undefined method `strftime' for nil:NilClass
```

pointing to this line https://github.com/DMPRoadmap/roadmap/blob/master/app/controllers/usage_controller.rb#L157

I guess the method `first_plan_date` returns nil.

**Steps to reproduce:**

**Comment by briri** [comment]
Hi @nicolasfranck, 
The usage page relies on a statistics table that gets updated by one of the rake tasks in `lib/tasks/stat.rake`. 

It sounds like your table is empty so you will need to run `rake stat:build`. It will scan through your database and generate monthly statistics. Note that this may take quite a while to run depending on how much data you have in your database.
 
Once tat table has been initialized we recommend setting up a job that runs the `rake stat:create_last_month` task on the first day of each month. It will generate all of the statistics for the prior month.

**Comment by xsrust** [comment]
I actually ran into this yesterday and submitted a patch with:https://github.com/DMPRoadmap/roadmap/pull/2403#discussion_r385810145 

That should be in development now.

But the above about running rake `stat:build` still applies to get everything working.
We should have a look at the setup-documentation and see if we point out to call that rake task

**Comment by nicolasfranck** [comment]
ok, understood. Thanks for your quick response! But why not simply show an error like "nothing show here, please run .."?

**Comment by briri** [comment]
agreed @nicolasfranck. see @xsrust PR mentioned above. It will be pulled into the next release which should be out in a week or two
