### ISSUE TITLE
Org admins cannot view plans explicitly shared by a user of another org

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#2415]
**Expected behaviour:**
When a user of any organisation shares a plan with any other user, they should be able to view the plan.

**Actual behaviour:**
When an org-admin has a plan shared by a user of another organisation, they do not have permissions to view the plan.

**Happening Because:**
Plan.readable_by(u_id) is defined below
```
def readable_by?(user_id)
    current_user = User.find(user_id)
    if current_user.present?
      # If the user is a super admin and the config allows for supers to view plans
      if current_user.can_super_admin? &&
          Branding.fetch(:service_configuration, :plans, :super_admins_read_all)
        true
      # If the user is an org admin and the config allows for org admins to view plans
      elsif current_user.can_org_admin? &&
          Branding.fetch(:service_configuration, :plans, :org_admins_read_all)
        owner_and_coowners.map(&:org_id).include?(current_user.org_id)
      else
        commentable_by?(user_id)
      end
    else
      false
    end
  end
```
As you can see, if the user is an org-admin, we don't check if the plan is shared with them to determine access.  I'll move that up to a guard-statement, and see if I can simplify the logic.

This is happening on live-services, so it should probably be submitted as a patch to Master

**Comment by magdalenadrafiova** [comment]
I am not sure whether I am doing something wrong, 

I am testing this on dmp-dev. I am pretending to be a user from Glasgow University, writing a plan for University of Edinburgh. 
I enabled request feedback for Edinburgh University but I still cannot see 'request feedback' tab for plan which I am creating as a Glasgow University researcher for Edinburgh University. 

Did I misunderstand the logic or am I testing this wrongly?

**Comment by mariapraetzellis** [comment]
I tried sharing a plan as a University of Manchester org admin w/ the York University org admin (both accounts I made). Got an error message:

<img width="1046" alt="sharing" src="https://user-images.githubusercontent.com/27511575/77102277-cdcdf980-69d5-11ea-9206-ccac95e35fbc.png">

<img width="789" alt="rejected" src="https://user-images.githubusercontent.com/27511575/77102290-d292ad80-69d5-11ea-8114-8e082132addc.png">

**Comment by xsrust** [comment]
Sorry for not explaining this one clear enough.  Previous Behavior was:
- `User` John from `Org` John's Uni shares a plan with `User` Alice from `Org` Alice's Uni.
- Alice is an org-admin.
- When alice goes to view the shared plan, she gets a 'permission denied' message

The sharing 404 is unrelated, but possibly a bug with the plan-sharing workflow so if you can reproduce it please open a new issue to address it.

**Comment by mariapraetzellis** [comment]
I _think_ this is working now. I shared a plan as a regular user with an org-admin from another university and was able to view the shared plan when I logged in as the org-admin. https://dmponline-dev.dcc.ac.uk/plans/35663

@sjDCC @magdalenadrafiova passing to you to verify

**Comment by sjDCC** [comment]
This is working. I shared a plan from me as Edge Hill uni to me as an admin at Glasgow uni and I could see plan fine.

Closing out

![working](https://user-images.githubusercontent.com/6169940/77418118-5c6bbd80-6dbe-11ea-85cd-aa2c1f83941b.PNG)
