### ISSUE TITLE
Change "Make a copy" to "Copy" in plan actions list

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2418]
Under the dropdown for actions to take on a DMP, all bar one is a verb.

Please change "Make a copy" to "Copy" for consistency

![copy](https://user-images.githubusercontent.com/6169940/76097444-9e73c180-5fbf-11ea-8fe7-22e46310507d.png)

**Comment by mariapraetzellis** [comment]
Looks good to me. Passing to @sjDCC @magdalenadrafiova to verify

**Comment by sjDCC** [comment]
Looks perfect. So much neater. Thanks @martaribeiro Closing out.
![perfect](https://user-images.githubusercontent.com/6169940/77417658-95576280-6dbd-11ea-8081-44ed60870234.PNG)
