### ISSUE TITLE
plan.funder_name not specified for all funder templates

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2419]
We recently changed the DMP cover page to list the funder name and the template name. See #2371 This is working in most cases but occassionally the funder_name attribute is not always specified

According to @xsrust this gets dynamically set on plan-creation. It'd be good to get a dev to have a look at why that might not have been set. The dev can create a rake:task to clean up our data.

**Comment by sjDCC** [comment]
May no longer be needed after @briri recent work on RoR.

Devs to check and close

**Comment by briri** [comment]
Updated to use the name of the Org who owns the Template if the user has not supplied a Funder on the Project Details page and the Org is a funder.
Added fix to the existing project-start-end PR since it is built off of the plan.funder relationship instead of the old plan.funder_name string

**Comment by sjDCC** [comment]
All seems good. Closing out
