### ISSUE TITLE
Ability to disable user accounts

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#243]
* Right now `destroy` action is disabled in Super Admin mode with the route (correctly) taken out for some models (esp. `user` and `org`).
* However we need some way to disable user accounts that:
  * Allows users to sign up with the same email as the disabled account
  * Maintains referential integrity by not deleting the disabled user - leaving their data alone.

**Comment by stephaniesimms** [comment]
@vyruss to clarify: we want to enable to users to disable their own accounts. but per our discussion last week we don't want to permit admins to disable accounts. so this action would be implicated in the Edit Profile area, not in the admin UI.

**Comment by stephaniesimms** [comment]
added ability for Super Admins to deactivate user accounts in v.1.0.1. closing this issue.
