### ISSUE TITLE
Add a JSON export to the download tab

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2438]
Allow users to download their plan as JSON - use the new `api/v1/plans/:id` JSONP functionality

**Comment by pherterich** [comment]
Works for me, though I haven't checked the json in detail for completeness or anything.

**Comment by mariapraetzellis** [comment]
Confirming that I am able to download plans as json. It does not currently include narrative components of the plan.

**Comment by magdalenadrafiova** [comment]
Can I just check - what are exactly the fields from the DMP that we were hoping to appear in the JSON download?

**Comment by briri** [comment]
We are following the new [metadata standard for DMPs](https://rda-dmp-common.github.io/RDA-DMP-Common-Standard/) outlined by the RDA working group for maDMP functionality. 

As we begin to use the new standard for the FAIR Island project, we are starting to identify gaps between the standard and what we need for DMPRoadmap to function properly. 

For example, there is a place to add narrative elements for things like the preservation, security and privacy statements but at an individual dataset level. We do not yet have the ability to accommodate that level of granularity though until we begin capturing multiple dataset info.

We have a ticket open to port over the functionality currently available in the v0 of the API #2567 but in order to do so we are also working on [RDA-Common-Standard issue #27](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard/issues/27) to determine the best way to fill those gaps 

We will likely have a hybrid solution over the next month or two where we stuff the narrative into a `dmproadmap-narrative` extension to the common standard.
