### ISSUE TITLE
Run the initial upgrade of the codebase

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2449]
- Compare config after the upgrade to the demo Rails5 app
- Document any diffs and share with the team, especially new files like `master.key` and `credentials.yml.enc`
- Edit `Gemfile` and `yarn.lock` to unpeg dependencies and set new Ruby version.
- Update the application.rb and environment files
  - Changed `config.server_static_files` to `config.public_file_server.enabled`
  - Changed `config.static_cache_control` to `config.public_file_server.headers`
- Update any scripts or files that contain a `rake` command to use `rails` instead. For example use `rails test` instead of `rake test` 
- Clean up routes.rb
  - Replace use of :controller and :action with the `controller#action` string
- DCC make sure you are on Postgres > 9.1! (Update our README and wiki to reflect this!)

**Comment by mariapraetzellis** [comment]
Estimating 3+ days of work.

**Comment by briri** [comment]
Here are a list of tasks done to get from 5.0 to 5.2 (including the step to 5.1):
- Updated the Gemfile to unpeg all gems and bumped rails to 5.2. Then ran `bundle update`
- Converted use of `::HashWithIndifferentAccess` to `ActiveSupport::HashWithIndifferentAccess`
- Ran `rake app:update` add diffed changes to splice our custom config back in
- Consolidated old `application.rb` config,  `config/initializers/constants.rb` and `branding.yml.sample` into `config/initializers/dmproadmap.rb` to group them all together (and get them out of the base Rails config) and to use the newer `Rails.configuration.x.` format

**Comment by briri** [comment]
Next steps:

Ensure all tests are running. It looks like we will need to add `optional: true` to many of the `belongs_to` rellationships

**Comment by briri** [comment]
Ran through and got all tests passing. Need the following adjustments:
- Updated `requests` and `controller` tests. Rspec switched to named arguments for http requests. (e.g. went from `get :index, org: { id: 123 }` to `get :index, params: { org: { id: 123 } }`
- Updated several other models to use `optional: true` on `belongs_to` relationships
- Updated ApplicationController to not use `hash_with_indifferent_access` since Request params are no longer a Hash and allow both string and symbol access

**Comment by briri** [comment]
NOTE: that the way Rails handles app credentials has changed in 5.2. There is no longer a `config/secrets.yml` file. It has been replaced by a `config/credentials.enc` file and a `config/master.key` file.

Everyone should read this blog post: https://medium.com/cedarcode/rails-5-2-credentials-9b3324851336

We will need to update all of our deployment strategies to work with these new files
