### ISSUE TITLE
Generic text: replace UC3 with CDL throughout DMPRoadmap

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#245]
On homepage and throughout we need to disambiguate and change all mentions of UC3 to CDL:

**Welcome.**
DMPRoadmap - STAGE has been jointly developed by the the Digital Curation Centre (DCC) and the California Digital Library (CDL) to help you write data management plans.

**Comment by jollopre** [comment]
@stephaniesimms UC3 appears mentioned in two places:

- The logo in the home page which links to http://www.cdlib.org/uc3/
- and the README.md (not relevant for the site)

If you have the new logo and URL I can make the changes.

**Comment by stephaniesimms** [comment]
@jollopre we can retain the UC3 logo for now and address generic branding after the MVP. It's ok just to update the generic text on Homepage and About with California Digital Library in the short term. people get confused otherwise.

**Comment by sjDCC** [comment]
@vyruss this doesn't appear to have been fixed. All references to UC3 have been removed on DMPonline-test, not replaced with CDL. Annotated screengrabs below.
![homepage](https://cloud.githubusercontent.com/assets/6169940/26111347/c04c38be-3a4c-11e7-8e82-971bdc88809d.PNG)
![about-page](https://cloud.githubusercontent.com/assets/6169940/26111356/c95a6c14-3a4c-11e7-9963-77384681b208.PNG)
![future-plan](https://cloud.githubusercontent.com/assets/6169940/26112800/c6fa6524-3a50-11e7-9ace-a70a544309a1.PNG)
![terms-of-use](https://cloud.githubusercontent.com/assets/6169940/26112810/cbbadf3a-3a50-11e7-87e9-fb85d6f45106.PNG)

@stephaniesimms Does this catch all references?

**Comment by vyruss** [comment]
@sjDCC these references come from `branding.yml`, installation-specific file - which is yet to be finalised for `dmponline-test`. All other references to UC3 in the code have been replaced with CDL

**Comment by stephaniesimms** [comment]
This is all the references for now @sjDCC - we can finalize the branding.yml file w/all generic text before final MVP
