### ISSUE TITLE
Conditional questions on customisable templates

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2451]
Hi Ray. We’ve spent some time trying to break this and most works well, but we hit a few errors noted below.

**1. Delete question button missing**
We noticed a difference between live site and -dev. The “delete” question button is missing.
![dev-site](https://user-images.githubusercontent.com/6169940/78777790-16078880-7992-11ea-9605-e408e5b90205.PNG)
![live-site](https://user-images.githubusercontent.com/6169940/78777794-16a01f00-7992-11ea-9b1c-61d51e2cb9b1.PNG)

**2. Error when deleting question option with conditions**
After publishing a template and verifying that all conditions worked as expected. We tried to re-edit this. When attempting to delete a question option which had a condition attached, we hit an error. 
![error-when-deleting-option-with-conditions](https://user-images.githubusercontent.com/6169940/78777838-2b7cb280-7992-11ea-98cb-0a38b83c5bf4.PNG)
As a fix, we should have an error message that “The question option can not be deleted as it has a condition attached. Please delete the condition first”. On re-testing, no error is thrown when the condition is removed first.

**3. Incorrect spacing in confirmation message**
This is a very minor thing,  but we noticed odd spacing in the confirmation message below
![weird-spacing](https://user-images.githubusercontent.com/6169940/78777873-3cc5bf00-7992-11ea-9804-8d65df37e1cc.PNG)

**4. Internal server error**
We saw a message on the front-end UI about an “Internal server error”. We assume this was due to an email notification not being able to be sent. We’ll test more to try and replicate to see if it’s a common error when editing and republishing a template which has existing conditions.
![Error-due-to-email](https://user-images.githubusercontent.com/6169940/78778003-7696c580-7992-11ea-87d4-d07915e14a7d.PNG)

**5. Error when editing conditions AND text box display**
This second error occurred when we edited existing conditions, added a new condition and removed the comment area. When we went back to this question, it had removed all the conditions and the comment area. It seems the comment area change was the only thing saved. Perhaps error is associated with that combination?
![error-2](https://user-images.githubusercontent.com/6169940/78778026-7bf41000-7992-11ea-9f75-b282d4949119.PNG)

**6. Error on section re-ordering - don't permit when there are conditional questions**
We can reorder the sections added by an institution but it is not recognising the save as a new version and flagging that there are unpublished changes. After reordering, we could set conditions to remove questions that had previously been in first place and had existing conditions on them. This threw a 404 error as shown below.
![error-3](https://user-images.githubusercontent.com/6169940/78778045-83b3b480-7992-11ea-816c-470e0f2d1ed0.PNG)
When there are conditional questions, it should not allow the admin to re-order the section. We need an error message to say “You can not re-order sections with conditional questions. Please remove conditions to re-order”

Whenever we hit a 404 error it jumps to the historical version of the template so you can’t edit.

**Comment by raycarrick-ed** [comment]
Looking at each of these in turn...

1. the code for the Save/Delete/Cancel buttons is exactly the same on live and -dev which suggests the difference is in the state. The condition for the the delete button being displayed is:
  - if the question has previously been saved (at any time in the past) and
  - if it is not published

if those 2 conditions are met then the delete button is displayed otherwise not. Could this account for the difference you are seeing? and do these conditions seem correct?

**Comment by raycarrick-ed** [comment]
2. question_option deletion where there is a condtion on it

We'd already taken a slightly different approach which is:
  - if you delete an option, the also delete any conditions which depend on it
rather than forcing the user to work through the same process themselves. Unfortunately there was a bug in there connected to versioning which is not sorted and should be able to be tested.

**Comment by raycarrick-ed** [comment]
3. incorrect spacing. Messages weren't handling questionoptions properly. Fixed now.

**Comment by raycarrick-ed** [comment]
4. Internal server error

I think this was due to an empty or invalid email address. The email address in the condition notification form wasn't being verified at all. Should be now.

**Comment by raycarrick-ed** [comment]
5. Error on conditions and text box

I *think* this is the same root cause as the earlier ones so I'm hoping this won't be able to be recreated now! Certainly I can't! but have a go and let me know if it's still there.

**Comment by sjDCC** [comment]
1. The logic is wrong. If someone has a published template and goes in to edit, this should allow them to delete a question in the new version. A user shouldn't have to unpublish their existing template to get the delete button as users may still be using this earlier version. Can it be changed please?

2. Overall we’re successfully deleting question options which have conditions on them, but we hit a few 404s which we’ve struggled to identify an exact pattern for this. We tried various variables e.g. different questions types, having defaults set, different condition types, having text box on/off etc. It seemed to occur on checkboxes and email notifications typically, but doesn’t always happen and when we retested on this specifically it worked. We tested for c.1 hr but couldn’t find any conclusive pattern. A couple of screengrabs are below in case links help identify what is wrong.
![email-error](https://user-images.githubusercontent.com/6169940/79242283-07c2dc00-7e6c-11ea-816c-c08071e7dfdd.PNG)
![error-on-option-removal](https://user-images.githubusercontent.com/6169940/79242288-085b7280-7e6c-11ea-9bba-6f8f0de670ce.PNG)

3. Perfect, thanks @raycarrick-ed

4. How is the email being validated? We tried saving a partial email “sarah.jones@glasgow.ac.” and it worked and didn’t throw an error. We also tried emails without @ and it still saved. We did once get the email validation error but can’t recall the exact scenario as it was part of earlier testing. It was on a secondary save i.e. we hadn't just edited the email condition. It had previously been saved successfully but when we edited something else in that question, it flagged the bad email and removed this condition. We also noticed that the page didn’t jump to top so the message was easily missed.
![Email-validation](https://user-images.githubusercontent.com/6169940/79242251-fa0d5680-7e6b-11ea-93dc-99d5a0dfaffd.PNG)


5. Seems to be fixed. Removing text box worked each time for us too.

You’ll be delighted to know we also found two other issues:

**7. It is possible to delete all question options, even though this is a mandatory field. We should have a validation to prevent that.** 
![is-possible-to-delete-all-options](https://user-images.githubusercontent.com/6169940/79242171-dea24b80-7e6b-11ea-801c-09247e31ef02.PNG)
![allows-delete-all-options](https://user-images.githubusercontent.com/6169940/79242169-de09b500-7e6b-11ea-99ae-c8d8cda7d1ec.PNG)

**8. We spotted some weird numbering on sections which had conditional questions**
![weird-numbering](https://user-images.githubusercontent.com/6169940/79242124-d2b68980-7e6b-11ea-8951-2b86b3952fe0.PNG)

**Comment by sjDCC** [comment]
Hi @raycarrick-ed  I played around with this again today as I thought the error on deleting questions with conditions may be linked to versioning. One the first version of the template all deleted well. One the second the same occurred and then on the third or fourth I hit one error. Others deleted fine. Here are links to the template in question and error in case that helps troubleshoot.

https://dmponline-dev.dcc.ac.uk/org_admin/templates/5830
https://dmponline-dev.dcc.ac.uk/org_admin/templates/5833/phases/6966/edit?section=41534

**Comment by raycarrick-ed** [comment]
1. Delete Question button was only being shown if not published. This was probably a leftover from before template versioning. Remove link to published status and just show it always. Done in:

55183946850bd09235f3a4364486f86c5a54836c

**Comment by sjDCC** [comment]
Just done UAT again

- Validated that delete button is now always showing - thanks @raycarrick-ed 
- Email validation is working and we saw error message when @ or end stem was missing
- You can no longer remove all options
- We've haven't been able to generate a 404 by deleting question options

Nearly there... :-)

**Comment by sjDCC** [comment]
All looks good on latest testing. No numbering issues or errors being thrown.

**Comment by sjDCC** [comment]
The final point on reordering uni sections on a funder template customisation is now also working. I generated this error on publishing
![Capture](https://user-images.githubusercontent.com/6169940/80203855-bced5500-861f-11ea-9a46-68a87f85ef5d.PNG)

Closing out
