### ISSUE TITLE
Move assets into the asset pipeline

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2466]
Remove all of our old yarn/webpacker asset configuration in favor of the standard Rails5 pipeline config.

https://guides.rubyonrails.org/asset_pipeline.html

Also clean out any unused assets in `app/assets` and `public`. 

The pipeline is not currently 'watching' files for changes (meaning if I update a JS file, webpacker does not recompile when I refresh the page).

**Comment by xsrust** [comment]
I don't know if the move away from webpacker would be a smart move.
Rails 6 is using Webpacker for all javascript compilation, and what we have should be largely compatible with Rails 5

**Comment by briri** [comment]
ok. Agreed. I wasn't suggesting we ditch Webpack entirely, just going through the official asset pipeline docs to make sure we're doing it the Rails way instead of a hybrid approach.

**Comment by xsrust** [comment]
Ahh cool, sorry for misunderstanding.
Optimistically the `Rails way` will be simpler :crossed_fingers:

**Comment by briri** [comment]
add `bootstrap-select` to the Gemfile and update the import statement accordingly in the application.scss file.

**Comment by briri** [comment]
made these changes directly to the rails5 branch.

Rails 6 is technically when Rails makes the official migration to using Webpack for JS management. We're ahead of the game on that front. 
- I built out a demo Rails6 app and copied over some of the config into our own
- Went through the Gemfile and did some cleanup of gems that are no longer relevant (or part of core Rails ... e.g. puma) and also did a little re-org to group gems together in categories. 
- Updated our session_store config to use `"sameSite": "lax"`. The default is `none` but browsers are beginning to throw deprecation warnings since this is CSRF vulnerability
- added some rails JS dependencies to Yarn (based on the Rails6 demo)
- Ran `bundle update` and `yarn upgrade`
