### ISSUE TITLE
Ensure that any JSON fields are properly serialized to/from the DB

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2469]
In Rails 5.0, how JSON/JSONB attributes are serialized and deserialized changed. Now, if you set a column equal to a String, Active Record will no longer turn that string into a Hash, and will instead only return the string. This is not limited to code interacting with models, but also affects :default column settings in db/schema.rb.

It is recommended that you do not set columns equal to a String, but pass a Hash instead, which will be converted to and from a JSON string automatically.

Make sure that the `/spec/models/pref_spec.rb` tests pass.

**Comment by briri** [comment]
the `spec/models/pref_spec.rb` test is failing on the following line:
`it { is_expected.to serialize(:settings) }`

It may be related to this serialization change

**Comment by raycarrick-ed** [comment]
I think this is now resolved. Tested everywhere I could find JSON serialization.
For UAT check:
 - links to orgs
 - template creation and editing
 - conditions on questions
 - user prefs for mail
 - stats (by template for example)
