### ISSUE TITLE
Revise generic text on About page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#247]
https://uc3-roadmap-stg.cdlib.org/about_us

Generic text for Roadmap About page in Google doc:
https://docs.google.com/document/d/1keGHmgXXvJfoprtxqc-5Nt5emVsJ8_2n89o1nkKhmb0/edit

**Comment by sjDCC** [comment]
Can you clarify the intention of this text @stephaniesimms? I think it works well in terms of pre-loaded text on the DMPRoadmap code as it helps to clarify the aims of the project, but I think the 'about us' page on our actual services needs more of an end user focus. 

The current [about us](https://dmponline.dcc.ac.uk/about_us) page on DMPonline explains how the tool works and how to get started and I wouldn't want to lose that. This text could certainly be included under additional info though to give broader context on the code and collaboration that underpins the service. I'm also happy for it to be the only generic text provided on the code when others download and install it.

**Comment by stephaniesimms** [comment]
@sjdcc Generally, the About page is meant for telling a story (about us and about our users) + contact details. It often lives in the footer—I favor moving it there and prelim UX wireframes do too. My goal for this was to keep it short and engaging, but after reviewing some best practices and our current pages I think we should insert a couple of sentences about what the tool is for. We should also add more explicit contact details (mailing and email for each org).

Most of what lives in the current DMPonline About page should probably go in the Help menu, which is definitely important content that will remain in the top nav.

**Comment by sjDCC** [comment]
Ok @stephaniesimms. Can we draft all these pages on googledocs and post on here once agreed?

The text you have is fine for explaining Roadmap and our collaboration, but I think we each need something introductory to explain the tool and what it does.

**Comment by stephaniesimms** [comment]
yes @sjDCC -Google docs sounds good. This draft was a slapdash effort in light of your previous release timeline.

**Comment by sjDCC** [comment]
Googledoc - https://docs.google.com/document/d/1keGHmgXXvJfoprtxqc-5Nt5emVsJ8_2n89o1nkKhmb0/edit?usp=sharing

**Comment by stephaniesimms** [comment]
transferred to global issue for generic text on static pages #668
