### ISSUE TITLE
Update mailer(s)

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2471]
The default Rails5 installation has a `mailer.html.erb` and `mailer.text.erb` in the `app/views/layouts` directory.

We should investigate the Rails5 docs for mailer setup/config and then update our user_mailer and devise mailers to use these layout files. We can move a lot of the duplicative variable initialization and email_signature into these layout files

**Comment by mariapraetzellis** [comment]
@martaribeiro will be setting up mail catcher on her local machine to test this out.
