### ISSUE TITLE
Replace all use of `uniq` on ActiveRecord queries with `distinct`

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2473]
This is a breaking change, so needs to be done now.

I discovered a couple while getting the tests to pass. There are likely others that we have not found yet. Do a search for `uniq` and if its in a query replace it with `distinct`

Add or update tests!

**Comment by raycarrick-ed** [comment]
The fixes I put in where wrong. There are NO instances of uniq which are part of queries. They all come in array contexts.

**Comment by raycarrick-ed** [comment]
I also deleted the branch I had pushed the incorrect fixes in.
