### ISSUE TITLE
Amend "Add conditions" button once one condition is added

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2476]
There is a usability issue with conditional questions which we should fix before deployment.

The orange button to "Add conditions" is greyed out once a first condition has been added. People see this more than the blue link text otherwise. 

We could either shift the "Add Conditions" button down the page and not grey it out or remove it. I think we should try to keep a standard look and feel to other settings so blue link like “Add option” may be best

![Picture1](https://user-images.githubusercontent.com/6169940/80193645-24e86f00-8611-11ea-86ef-2fe22efdcf54.png)

**Comment by raycarrick-ed** [comment]
c55cff30bd0e5846126b744c4638f0d90feb58d2

fixes this. I tried just removing the button when the conditons are shown but that just looks strange. They need some sort of separation between the options and the conditions so I changed it from saying "Add Conditions" to just "Conditions" and disabled it so it no longer looks like a button. That should do for now and we can restyle later if wanted.

**Comment by sjDCC** [comment]
Great. Let me know when deployed and I'll UAT and take screengrabs for guide

**Comment by sjDCC** [comment]
Hi @raycarrick-ed  I'm testing this but it doesn't seem to work as intended. The greyed out button doesn't change text from "Add conditions" to just "Conditions" (it stays the same) and now when you first click the button, it doesn't open up the first condition to enter. You need to click the blue link highlighted below so in effect the user is double-clicking to do the action

![Capture](https://user-images.githubusercontent.com/6169940/80476620-89256e80-8942-11ea-80ab-7ec0414d1052.PNG)

**Comment by sjDCC** [comment]
It was a javascript asset issue. Getting the button change now as planned so closing out.

Thanks @raycarrick-ed
