### ISSUE TITLE
Plan details page - data contact person to be empty rather than ticket 

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2477]
Currently on the plans details page the data contact person is ticket as 'same as principal investigator' 
<img width="594" alt="Screenshot 2020-04-24 at 10 15 16" src="https://user-images.githubusercontent.com/47178106/80196071-bd342300-8614-11ea-800d-5832eb5903ae.png">

It was suggested that it will be better to be empty by default.

**Comment by xsrust** [comment]
ToDo: Think about this ticket in the context of the new contributors model.

**Comment by sjDCC** [comment]
Going to close this one out as the new contributors model covers it
