### ISSUE TITLE
Fix filter plans button and settings

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#248]
On My plans page, I can filter plans by typing into the box. However, the 'Filter plans' button and settings cogwheel don't do anything. @sjDCC Do we even need these? I suggest removing them as filtering functionality is sufficient as is. I actually find it confusing and unnecessary to be able to filter by different fields as in DMPonline (second screenshot below).

DMPRoadmap My plans page
![screen shot 2017-04-14 at 10 15 00 am](https://cloud.githubusercontent.com/assets/12703638/25050282/6a09780a-20fb-11e7-9d6c-1229000bffc6.png)

DMPonline filter plans settings options
![screen shot 2017-04-14 at 10 20 02 am](https://cloud.githubusercontent.com/assets/12703638/25050383/0be7affc-20fc-11e7-8646-51ed6a5ad604.png)

**Comment by sjDCC** [comment]
It was added by Leeds Uni to help admins who have access to lots of plans but has been a bit buggy and has broken regularly. I'll check how much it's in use but am in favour of removing on the whole

**Comment by briri** [comment]
removed the filter button and cog wheel from the view plans page. I did not remove any of the underlying settings code from the controllers/models/db. I also left the views for the settings partial in place. We can remove them post MVP0.3

Will merge this into development and then as a PR once @sjDCC has confirmed with Leeds Uni that it is ok to remove the functionality

**Comment by sjDCC** [comment]
Leeds have confirmed they are happy for this to be removed, so let's take it out @briri

**Comment by stephaniesimms** [comment]
Working as expected. Closing issue.
