### ISSUE TITLE
Progress bar on "write plan" shows as partially completed 

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2480]
Currently when user starts writing plan the progress bar appears as partially completed even nothing has been answered. 
<img width="798" alt="Screenshot 2020-04-24 at 10 22 28" src="https://user-images.githubusercontent.com/47178106/80196803-c07bde80-8615-11ea-8d69-947250d0cc1f.png">

Would it be possible to have this empty when nothing has been answered and for the bar to gradually fill when more questions were answered?

**Comment by pherterich** [comment]
This is now empty for me, checked both in Chrome and Firefox, so will close out.
![DMPonline_planprogress](https://user-images.githubusercontent.com/8457675/175321228-572fd27f-5533-464d-bba0-f29f79422d7b.png)
