### ISSUE TITLE
Change the date column in admin/plans table

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2492]
Can we amend the plans table to show date created rather than date updated, or perhaps both? 

![date-created](https://user-images.githubusercontent.com/6169940/80419357-e254ba00-88d0-11ea-87af-c8152a4bc2e7.PNG)

**Comment by briri** [comment]
I added the 'Created' column as part of the changes for the new Month + Year search filter and the click-through from the usage dashboard.

**Comment by sjDCC** [comment]
Ah excellent. This can close out then
