### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2497]
Review and update the README.md and Wiki pages as needed.

**Comment by briri** [comment]
Request for “Service Description” for clients covering basic architecture and services used (discuss, joint or individual, who to start).

**Comment by xsrust** [comment]
New Documentation needing writtten:
- Wiki-Page on Translation.io
- Release Notes for Rails5
Other Wiki pages needing updated:
- [Guidance on Translation,](https://github.com/DMPRoadmap/roadmap/wiki/Translations) both via releases, and via the [Pot/Po files](https://github.com/DMPRoadmap/roadmap/wiki/Translations-directly-through-the-app.po-files)
- Docker/Vagrant Instant [Development Environment](https://github.com/DMPRoadmap/roadmap/wiki/Developer-guide) Potentially either remove, or provide a 'default DMPRoadmap docker container'?
- [Get-involved Translations section](https://github.com/DMPRoadmap/roadmap/wiki/Get-involved#4-translations)
- [Installation Instructions](https://github.com/DMPRoadmap/roadmap/wiki/Installation) 
- [Data Model](https://github.com/DMPRoadmap/roadmap/wiki/Data-model) This can maybe be removed as it's not the current model

**Comment by briri** [comment]
Updated the branding wiki page to reflect move away from placing custom code in the `lib/` dir

**Comment by xsrust** [comment]
I've updated the Translation guidance and referenced out to the changed wiki-page from the v3 release notes.
