### ISSUE TITLE
Implement recaptcha to avoid rogue account creation

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2502]
We had some fake accounts being created on the Tuuli service so implemented a recaptcha. We think we should add this into the main codebase as configurable on/off so we could easily prevent a similar issue on any other deployments. Having removed the email verification means we are open to bots

**Comment by briri** [comment]
👍 related to: #2281 

@mirkh would you be willing to share the changes you made to your installation?

**Comment by sjDCC** [comment]
Thanks @briri Didn't realise there was a related ticket.

@raycarrick-ed  put this in place for Tuuli and we thought we should add to common codebase in case so pinging him here

**Comment by briri** [comment]
ah perfect. I think it will be useful for everyone.

**Comment by mirkh** [comment]
> 👍 related to: #2281
> 
> @mirkh would you be willing to share the changes you made to your installation?

I'm sorry @briri I seem to have missed this. But we didn't go for that solution. Instead we removed the registering of accounts and made it mandatory to log in using institutional credentials.

**Comment by briri** [comment]
no worries @mirkh. Thanks for letting us know :)

**Comment by briri** [comment]
Should be relatively straightforward to put a Recaptcha on the account creation window @sjDCC

**Comment by sjDCC** [comment]
Thanks. We can pull in @raycarrick-ed fix for Tuuli

**Comment by raycarrick-ed** [comment]
this is implemented on Tuuli test and should be fairly easy to pull into the main codebase

**Comment by briri** [comment]
@mirkh would you be willing to share how you went about setting your implementation up so that the only login option is via institutional credentials?

**Comment by magdalenadrafiova** [comment]
@briri is this something we are still considering to work on? we have received question about implementing re-captcha and I am just trying to follow up and see how far we got with this one. Thank you!

**Comment by briri** [comment]
This has been implemented so will close the ticket. The recaptcha will appear if:
- It is enabled here: https://github.com/DMPRoadmap/roadmap/blob/576ea69fb783170ae2da37f69c35593b8866419f/config/initializers/_dmproadmap.rb#L203
- The recaptcha API keys are stored in the the credentials file: https://github.com/DMPRoadmap/roadmap/blob/576ea69fb783170ae2da37f69c35593b8866419f/config/initializers/recaptcha.rb#L8

<img width="604" alt="Screen Shot 2021-03-24 at 7 07 33 AM" src="https://user-images.githubusercontent.com/1204467/112324123-ac01f500-8c6f-11eb-8759-172d411767d8.png">

**Comment by magdalenadrafiova** [comment]
Thank you!!! :)

**Comment by raycarrick-ed** [comment]
We have it set up and even have keys already (they'll need checking to see if they are still correct after the upgrade) but it is currently switched off. It requires switching on and testing. It's on the todo list but not anywhere near the top at the moment. But hopefully it's not a big deal when we get to it.
