### ISSUE TITLE
inconsistency in wiki

### ISSUE THREAD

**Issue by robertgiessmann** [DMPRoadmap/roadmap#2513]
Dear team,

this issue did not fit the template. 

When visiting https://github.com/DMPRoadmap/roadmap/wiki/API-Documentation-V1#get-apiv1heartbeat -- I see that the title is "GET ..." but the actual curl action is "POST". Maybe you can adjust either one to whatever is correct?

Did not know how to change it myself, I am sorry for that. :(

Best,
   Robert

**Comment by briri** [comment]
Good catch @robertgiessmann and thanks for reporting it. I have updated the documentation.
