### ISSUE TITLE
Bugs on editing organisation page

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2514]
Under the admin organisation page, there are a couple of bugs with editing

1. Any change (amending names, links etc) strips out existing logo uploads
![logo-delete](https://user-images.githubusercontent.com/6169940/82067698-fb2edf00-96c8-11ea-8aed-3879603a1fe5.PNG)

2. If a contact email is already saved, this doesn't display in the top menu until another link is added. Links and helpdesk should show irrespective of one another
![admin](https://user-images.githubusercontent.com/6169940/82067716-ff5afc80-96c8-11ea-81ba-f2b9c2f7eb10.PNG)

**Comment by briri** [comment]
seems to no longer be an issue
