### ISSUE TITLE
Cannot Edit customization for NIH template

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#252]
I was successfully editing customizations for the NIH template...then navigated away from the page. When I returned to the main templates page and clicked Edit customization for the NIH template, I got the following error:
![screen shot 2017-04-14 at 12 14 33 pm](https://cloud.githubusercontent.com/assets/12703638/25053407/f3dea996-210b-11e7-8fe2-89b4993e2c2e.png)

**Comment by briri** [comment]
This happens when a template has multiple phases defined

**Comment by stephaniesimms** [comment]
Now working as expected. Closing out.
