### ISSUE TITLE
integration tests - account creation

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2523]
Refer to the [manual UAT script](https://docs.google.com/document/d/1cCCqgH_nRhVZ5Fr-sKbbiReFGyz3_6lij38KJ-S98gY/edit) for details.

- Account creation via email+password signup
- Account creation via omniauth
- Also check Org creation when user selects a ROR org or types in a name not in the list

**Comment by mariapraetzellis** [comment]
Closing this as the DMPTool and DMPonline account creation workflows are specific to their implementations.

**Comment by mariapraetzellis** [comment]
Closing this issue since most Roadmap instances have custom account creations.
