### ISSUE TITLE
Migrating legacy themed guidance

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#253]
When we implement the new DMP themes into DMPonline and DMPTuuli, we will need some kind of temporary admin interface to help institutions manage any redundant data. For example existing guidance for themes that have now been deleted or merged into others will need to be flagged and suggestions made as to where this could be merged. I think it will be a manual step for organisational administrators to review all their existing guidance though and decide what to include / write into other themes or delete.

**Comment by stephaniesimms** [comment]
@sjDCC - just to clarify: you want to support the original set of themes for now (v0.3)? and we can reduce to the revised set of 14 by v1.0?

**Comment by sjDCC** [comment]
@stephaniesimms Yes, I would rather focus on the code migration and getting that working first, then migrate existing guidance to new themes when you are migrating your data and users at MVP release. Doing it now will delay the v.0.3 release and have knock-ons for your MVP timeframe. I thought it was best for us to schedule this concurrently with your data migration.
The Finns are revising their guidance following the Academy of Finland Spring call so could be an early trial run of this, and then do our main DMPonline themed guidance migration once we have the full MVP release out. It also lets us give users more advance notice as it will require org-admins allocate time to check and update their content.

**Comment by sjDCC** [comment]
Related to #186

**Comment by stephaniesimms** [comment]
this is specific to DMPonline services and should be tracked separately (not part of Roadmap work)

**Comment by vyruss** [comment]
Done (see PR #1287 and https://github.com/DMPRoadmap/roadmap/wiki/Themes)
