### ISSUE TITLE
Accordion plus signs do not change

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2558]
- The accordion +/- signs do not change when the panel is expanded/collapsed. Doesn't seem to be a JS function for this anymore. Should be easy to add to the existing `app/javascript/src/utils/accordion.js`
- The 'expand all' and 'collapse all' links are not working.

**Comment by briri** [comment]
related to #1298

**Comment by raycarrick-ed** [comment]
Fixed in:
https://github.com/DMPRoadmap/roadmap/tree/issue_2558

**Comment by mariapraetzellis** [comment]
This looks good now. The icon is small but this is being tracked in #2646
