### ISSUE TITLE
Cannot create plan if user has no org

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#257]
Users who do not have an organisation defined will be unable to create a plan in the roadmap codebase.

After running a migration, I re-seeded the database with the super_admin account and didn't give it an organisation.  upon trying to create a plan, i was given the following error:

![image](https://cloud.githubusercontent.com/assets/7352616/25225573/c294066c-25b9-11e7-8acf-c21920c514fc.png)

It looks as if the plan creation code relies on having a User.org relationship.
A quick check of the database shows that there are users who have signed in recently and have no organisation

**Comment by stephaniesimms** [comment]
Working as expected although see new issue #285 . Closing this one.
