### ISSUE TITLE
Evaluate Thread issue on ResearchProjectsController

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2579]
The `Thread.new` seemed to be behind our issues with Puma occasionally hanging. It is commented out for now. 

Read through the latest docs for `Thread` and see if we can do something to get it working properly OR this may be a good candidate for `ActionCable` web sockets.

**Comment by xsrust** [comment]
I did a quick benchmark between running this in a new spawned thread vs running this on the thread of the initial request:
```
irb(main):010:0> Benchmark.bm do |x|
irb(main):011:1*   x.report {10.times do ; ExternalApis::OpenAireService.search(funder: ExternalApis::OpenAireService.default_funder) ; end}
irb(main):012:1>   x.report {10.times do ; Thread.new {ExternalApis::OpenAireService.search(funder: ExternalApis::OpenAireService.default_funder)}.value ; end}
irb(main):013:1> end
       user     system      total        real
   3.596776   0.137933   3.734709 ( 18.262244)
   3.250293   0.087720   3.338013 ( 21.685482)
```

It looks like there's a not-insignificant overhead involved with creating that thread, and I'm not sure what the benefit is of creating the additional thread.  Puma already has multiple workers/threads handling requests, so is this necessary?

**Comment by briri** [comment]
Ah interesting. I'm not sure why we were spawning that thread either. I think maybe to get a quicker initial page load for the user to provide a web-socket-esque experience. I had noticed when adding the project start/end dates to the Project Details page that the page would load but there was a delay before the grant id field's typeahead was rendering results.

Agree that the overhead caused by spawning that thread is undesirable and unnecessary in this case. I also agree that the download/refresh of the source file involved is a good candidate for ActiveJob.
