### ISSUE TITLE
Clarify permissions to be granted

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#259]
For usability, I think it would be good to add some help text to clarify what each permission allows. I've suggested some below but please correct these if wrong:

Grant permissions - this allows the user to assign permissions to other users within the same organisation. Users can only assign permissions they own themselves _(is that right?)_

Modify templates - this allows the user to create new institutional templates, edit existing ones and customise funder templates

Modify guidance - this allows the user to create and edit guidance

Change organisation details - this allows the user to amend the organisation details (name, URL etc) and add basic branding such as the logo 

API rights - this provides the user with an API token and grants rights to harvest information from the tool

These text could display within question mark icon popups or could perhaps be included in the table. Whatever works best display wise. 

I think the table headings should display as single words too, not text strings like "grant_permissions"

![capture](https://cloud.githubusercontent.com/assets/6169940/25233980/998fef8c-25d8-11e7-9550-5628b1663e3a.PNG)

**Comment by stephaniesimms** [comment]
@sjDCC your clarification text might be sufficient to add as tooltips for now. I added a UX tag to this issue so we can confer about it this week. Permissions work is on their roadmap too so I just want to cross-reference.

**Comment by vyruss** [comment]
Added tooltips and strings as described. Table looks ugly because of inherited CSS classes but let's leave that to UX team post-v0.3 :)

**Comment by sjDCC** [comment]
This is fine for now, but I think some kind of question mark or other icon should appear so people know there is a tooltip if they hoverover. We should try to be consistent with how it's handled elsewhere in tool for usability. UX can hopefully make a suggestion
![capture](https://cloud.githubusercontent.com/assets/6169940/26487991/9ff9f0ce-41f9-11e7-93bd-f91b8d32b009.PNG)

**Comment by sjDCC** [comment]
Fine for now. Closing out
