### ISSUE TITLE
ruby version 2.7 not supported

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#2590]
Please complete the following fields as applicable:

**Expected behaviour:**

ruby 2.7 should be supported as stated in README,
or the version of big_decimal should be specified in the Gemfile

**Actual behaviour:**

**Steps to reproduce:**

* switch to ruby 2.7
* run migration step `rake upgrade:v2_0_0_part_1``
* fails with:

```
/usr/local/rvm/gems/ruby-2.7.1/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
  rake aborted!
  NoMethodError: undefined method `new' for BigDecimal:Class
  /home/install/roadmap/vendor/bundle/ruby/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/object/duplicable.rb:111:in `<class:BigDecimal>'
```

See also https://github.com/rails/rails/issues/34822#issuecomment-608265387

**Comment by magdalenadrafiova** [comment]
@briri @xsrust we received this comment, should we add this to backlog project?

**Comment by briri** [comment]
Apologies for the incorrect ruby version support specified on the Readme @nicolasfranck. The current release of DMPRoadmap 2.x supports ruby 2.4.x.

We will be moving to ruby 2.6.3 along with the upcoming upgrade to Rails 5.2 (due out later this summer)

**Comment by nicolasfranck** [comment]
thanks
