### ISSUE TITLE
Allow OgAdmin to enable/disable DOI minting

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2598]
If an installation allows for DOI minting (in the global config settings) then an Org Admin should be able to enable/disable it for their users.

@mariapraetzellis @magdalenadrafiova and @pherterich I have a few questions about how we want to handle a few things:

Should OrgAdmins be able to provide their own specific configuration as well? For example with Datacite, the DOI shoulder to use along with any info required so that they incur any fees from the minting authority.

Should users belonging to an "unmanaged" Org (one that was created via the new ROR integration and has no OrgAdmin defined) be allowed to publish their DMPs? If so, would we use the default configuration so that the application/service incurs any related fees?

**Comment by briri** [comment]
see parent issue #2351

**Comment by mariapraetzellis** [comment]
@briri: For now I don't think we'll support org specific configurations for DOIs- perhaps down the road but best to stick with only EZID for now.

Users should belong to a managed account within the DMPTool and that org would need to have the DOI minting feature enabled in order to get DOIs for their DMPs.

**Comment by mariapraetzellis** [comment]
We realized this feature will not work as we will have users from various organizations submitting DMPs as part of our work with FAIR Island.

**Comment by magdalenadrafiova** [comment]
@mariapraetzellis does this mean DOI will not be possible at all?
