### ISSUE TITLE
Super admins are not able to search for 'all templates' - it throws an error

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2603]
When super admins go to search 'all templates' it does not work on live site and test site. If as a super admin one looks up for e.g. BBSRC template we should be able to see this but instead this is throwing a message  'page not found' error.
<img width="1246" alt="Super-admins-all-template-page-step-1" src="https://user-images.githubusercontent.com/47178106/87054449-069b1400-c1fb-11ea-84fb-8976262bac27.png">
<img width="1240" alt="Super-admins-all-template-page-step-2-throwing-an-error" src="https://user-images.githubusercontent.com/47178106/87054461-0bf85e80-c1fb-11ea-8b4f-82787dc2935d.png">

**Comment by pherterich** [comment]
This currently works for me again, so must have been resolved in the meantime. I will close and a new ticket can be created should the issue re-occur.
