### ISSUE TITLE
Integration with re3 Data Registry 

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2605]
We have discussed utilizing the [re3 Registry of research data repositories](https://www.re3data.org/api/doc) and FAIRSharing. For this piece of work we will work with the re3 registry since this tool has already been built and the API is public. Once we get keys for FAIR sharing we should add this as an option as well.

To be discussed:

- Should we use the recommender tool built by AGU? Do we want to model it after the metadata standard selector tool already in Roadmap?
- Where does this question type live in the UI? Should it automatically be added to all templates, or be a question type that an administrator has to add to a template?

**Comment by briri** [comment]
take a look at https://repositoryfinder.datacite.org/

**Comment by mariapraetzellis** [comment]
Ready for QA; select multiples; remove them; there is no limit right now. Consider where the generalist filter should live- maybe a radio button- this might also be good for when we extend functionally to include admin recommendations for specific repositories.
