### ISSUE TITLE
Bug with merging users 

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2619]
I'm trying to merge user accounts for an org admin who accidentally created two accounts for herself (https://dmptool.org/super_admin/users/29374/edit). 

I am able to select the account to merge, the dialog box with the explanation of what is being moved and which account will be deleted displays as expected, however, after clicking Ok the application gives a 500 error.

**Comment by xsrust** [comment]
Just confirmed this is working on our live service, but we have v2.1.7 deployed, not 2.2.0.

**Comment by mariapraetzellis** [comment]
This is working now
