### ISSUE TITLE
Any documentation about the steps of the new plan structure in branch dmponline4_upgrade_step2?

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#2627]
I've iterated through the migration leading from DMPOnline_v4 all the
way to v2.2.0.

I've noticed this:

* most of the migrated templates have attribute `archived` set to `true` which makes them unselectable. I learned from migration `20180807120926_add_default_value_to_archived_on_notes.rb` that `archived` used to be called `migrated`, and that it was filled during migration in `20161122152339_new_plan_template_structure.rb`. That last migration only has the attribute `migrated` in branch dmponline4_upgrade_step2 by the way.

* due to constant duplication of Template in that migration, the attribute `is_default` is not unique anymore. To be fixed manually?

I'm just wondering if there is some documentation about the decisions made in migration `20161122152339_new_plan_template_structure` from branch `dmponline4_upgrade_step2`.

This is what I've understood by reading the code:

* in roadmap, every time a published template is to be updated, a new template record is created,
  and all data attached to it copied. In dmponline the old structure of a template was only recorded
  in project.plans, so that explains why this migration creates templates by iterating over the projects.
  The Template created here is considered "legacy" (attribute "migrated"="true"), why?

* there is a second iteration where templates are created without setting "migrated" to true. What is the difference?

Thanks in advance.

**Comment by xsrust** [comment]
Hi @nicolasfranck 

> Due to constant duplication of Template in that migration, the attribute `is_default` is not unique anymore.  To be fixed manually?
Yep, we reduced this so only one `family_id` of templates will have the `is_Default` flag during the data-cleanup migration. (upgrade to 2.0.0)

> Documentation on decisions made when in the migration `20161122152339_new_plan_template_structure` from branch `dmponline4_upgrade_step2`.
Unfortunately I don't think we generated any documentation on that.  Your description above is pretty spot on, and I can clarify a few points below.

Basically, we were flipping the storage of template versioning.  In DMPOnline_v4, There were Templates which had Phases (tabs in the UI) which each had phase-versions.  There was also a `plan` object attached to the `project` object to map over which `phase-versions` within the `template` the plan was based on.
We wanted to get to a place were `Templates` belong to a `family` and have `versions`, and both the `phases` and the `projects`(renamed to  `plans`).  We also needed to have a new, valid Template for each of the combinations of `versions` used in each `plan`.
To generate the templates for plans, we just created any used combinations of `phase-versions`, and set what you refer to as the "legacy" flag (now `archived`).  This flag just hides the templates from the administrative side of the UI.
Finally, we did a final pass on all the most-recent `version` of each `phase` of each `template`, and generated a fresh `Template` record without this flag set to true, which became the first `version` of that template `family`.

Let me know if there's anything I've missed out or can explain further.

**Comment by nicolasfranck** [comment]
Thanks, exactly what I had in mind.

What I've also noticed: the attribute `customization_of` in migration `20161122152339_new_plan_template_structure ` is set to the value of the old
dmptemplate id. So for these templates the values become unusable, as they do
not refer anymore to existing templates anymore? Most of them are `archived` (where this would be reasonable), but
not all. Or is this value just a flag?

**Comment by xsrust** [comment]
This value is used for the `customized` templates.  Effectively, it holds the `family_id` of a funder template to form a link to each organisation's `customized` version of this template.  In the latter, organizations can add custom annotations (example-answers and guidance) along with their own sections on top of an existing template in the tool.

We also converted these over from the old codebase.  Previously, Sections had an optional `org_id` which, it if matched the `version_id` and `org_id` found in the `plan` objects, would connect these custom sections onto the UI.
