### ISSUE TITLE
Text boxes are missing from answers area and comments box when creating a plan

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2629]
When creating a new DMP the text box that the user writes in the answers to questions is missing from the page. For example, https://dmponline-test.dcc.ac.uk/plans/56048/edit?phase_id=5924.
![screenshot-dmponline-test dcc ac uk-2020 08 06-10_41_35](https://user-images.githubusercontent.com/27511575/89564355-bc915800-d7d1-11ea-8551-24952ea012ae.png)

The text box is also missing from the Comments section within a plan.
![screenshot-dmponline-test dcc ac uk-2020 08 06-10_48_19](https://user-images.githubusercontent.com/27511575/89564830-738dd380-d7d2-11ea-9864-42dc5d927151.png)

This issue appears to affect all areas of the application that involve text boxes. Just noticed the problem when trying to customize a plan as well.

**Comment by pherterich** [comment]
Project details are editable, they ate the only working text boxes I've found so far.

**Comment by pherterich** [comment]
@xsrust and @raycarrick to document fix here on tinyMCE for further consideration

**Comment by raycarrick-ed** [comment]
The problem was a change from v4 to v5 of tinymce. As a temporary fix we pinned tinymce at v4 and took the
app/javascript/src/utils/tinymce.js.erb
from the old rails 4 system and put it in place and it seems to work ok. At some future point we need to upgrade to v5 and work through the issues.

**Comment by mariapraetzellis** [comment]
Looks good now.
