### ISSUE TITLE
Unable to share a plan 

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2630]
I created a plan and tried to invite collaborators via the Share tab. Was directed to a Page unavailable page.

I see that the system did save the collaborator to the plan, however I did not receive an email confirming the plan was shared with me. 

![screenshot-dmponline-test dcc ac uk-2020 08 06-10_55_21](https://user-images.githubusercontent.com/27511575/89565430-6d4c2700-d7d3-11ea-90b8-385dfad2888f.png)

**Comment by xsrust** [comment]
Had a look at the logs around this bug and it looks like the mailer was throwing an error due to the way I'd configured the mail-container.

**Comment by xsrust** [comment]
This should now be resolved (no PR as the change was made to the production-configuration rather than codebase)

**Comment by pherterich** [comment]
Worked for me today but didn't send an email which might be a Rails5 unrelated issue.

**Comment by mariapraetzellis** [comment]
Just tried to share a plan and got the Page Not Available message again. Tried it on this plan https://dmponline-test.dcc.ac.uk/plans/56065/share

**Comment by xsrust** [comment]
Page unavailable error still seems related to the mailer configuration.
Re-navigating to the page shows that the plan is shared with the user.

**Comment by xsrust** [comment]
Fixed the problem causing the mailer to fail (This was in our config, rather than the DMPRoadmap codebase)
I don't think the mail is actually being sent from DMPonline-test at the moment, but it's no longer throwing a 500 when it tries to.

**Comment by mariapraetzellis** [comment]
Should we be receiving emails for shared plans now @xsrust ? I think I was able to share the plan successfully but I didn't receive an email

**Comment by pherterich** [comment]
Just tested and email ended up in the inbox that @raycarrick-ed made available. I'd be happy to close this, @mariapraetzellis do you want to check again?
