### ISSUE TITLE
"View all" link under Customizable Templates is broken 

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2631]
In the Templates section > go to "Customizable Templates" tab> click on the "View all"> no plans are listed.

![screenshot-dmponline-test dcc ac uk-2020 08 06-11_09_29](https://user-images.githubusercontent.com/27511575/89566666-5e667400-d7d5-11ea-86ca-6feca93ddbb9.png)

**Comment by pherterich** [comment]
None of the filters work for me, but the list shows when just clicking on the tab and search works, too.

**Comment by raycarrick-ed** [comment]
Wasn't pulling html out of the AJAX payload correctly. One word fix so just merged in rather than having a separate branch.

68b5e4b0d5b98da21ddb30e153d157dce535eded

**Comment by mariapraetzellis** [comment]
Looks good. @pherterich or @magdalenadrafiova do you want to confirm?

**Comment by magdalenadrafiova** [comment]
works well now - 
![Uploading Screenshot 2020-09-07 at 09.11.39.png…]()
