### ISSUE TITLE
Edit profile - notification preferences don't display

### ISSUE THREAD

**Issue by pherterich** [DMPRoadmap/roadmap#2632]
**Expected behaviour:**
Notification preferences offer me a list of tick boxes to select email notification preferences from. 

**Actual behaviour:**
Nothing is displayed there, but it shows an error " Error: No default preferences found (should be in dmproadmap.rb initializer)."
![Edit profile notificstion issue](https://user-images.githubusercontent.com/8457675/89794165-94ca2900-db1e-11ea-938f-d1929dc7ff6a.png)

**Steps to reproduce:**
Go to "edit profile" and click on the notification preferences tab. I'm using Chrome as browser. The other tabs in that section are functional.

**Comment by pherterich** [comment]
Still an issue after tinyMCE fix.

**Comment by mariapraetzellis** [comment]
Might be javascript or preferences in the default setting for the application. Ray will take a look.

**Comment by raycarrick-ed** [comment]
Preferences hash structure had changed slightly.
Fixed in:
https://github.com/DMPRoadmap/roadmap/tree/issue_2632

**Comment by pherterich** [comment]
They display now but it doesn't seem to save any changes though it displays the message
"Notice: Successfully saved the preferences."

**Comment by mariapraetzellis** [comment]
Tested this and it does not save preferences.

**Comment by raycarrick-ed** [comment]
Wasn't saving due to changes in prefs and pref structure.
Fixed in:
https://github.com/DMPRoadmap/roadmap/tree/save_email_prefs

**Comment by mariapraetzellis** [comment]
Looks good now. @pherterich do you want to verify?

**Comment by pherterich** [comment]
All good 👍
