### ISSUE TITLE
Downloading plans as PDF does not include answers to questions

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2636]
When downloading a plan to PDF the answers to the specific questions do not export and are listed as "Question not answered." The answer is saved in the application and displays as normal within the application.

For example, this Horizon 2020 test plan: https://dmponline-test.dcc.ac.uk/plans/56054/

**Comment by mariapraetzellis** [comment]
might be related to the tiny mce boxes problem?

**Comment by xsrust** [comment]
NB. Showing "not answered" for answered questions, and nothing for unanswered

**Comment by raycarrick-ed** [comment]
Fixed in commit:
https://github.com/DMPRoadmap/roadmap/commit/0989ab184269ca5af6b469e3320b26803fb3ba60
if !blank put "Question unanswered" else .....
just pushed to dev since it's a one character fix.

**Comment by pherterich** [comment]
Looks all good to me now!

**Comment by mariapraetzellis** [comment]
Looks good to me too :)
