### ISSUE TITLE
Sort icons on tables not functioning 

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2639]
The sort icon on the Templates and Plans table is not functioning. When I click on the sort icon the entire table disappears. 

The sort icon is working as expected on the Public DMPs table. 

For example, clicking on the sort icon in this table:
![screenshot-dmponline-test dcc ac uk-2020 08 17-16_35_22](https://user-images.githubusercontent.com/27511575/90454369-da9b6a00-e0a7-11ea-81b5-1de677b11964.png)

Removes the table all together: 
![screenshot-dmponline-test dcc ac uk-2020 08 17-16_37_04](https://user-images.githubusercontent.com/27511575/90454390-f0a92a80-e0a7-11ea-8de4-b823ee48950d.png)

**Comment by pherterich** [comment]
It works on the guidance table and on users.

**Comment by pherterich** [comment]
Can confirm that this works now, thanks @raycarrick-ed

**Comment by mariapraetzellis** [comment]
Confirmed; looks good :)
