### ISSUE TITLE
Recaptcha broken on live DMPonline site

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#264]
See https://dmponline.dcc.ac.uk/contact-us

**Comment by briri** [comment]
This is likely just an issue with the server configuration in `config/initializers/recaptcha.rb`. @vyruss you should be able to just copy over what you have out on the live DMPonline instance

**Comment by sjDCC** [comment]
Thanks @briri

**Comment by vyruss** [comment]
`recaptcha.rb` hasn't been touched since Sep 30, 2013. Maybe Google has changed their Recaptcha API.

**Comment by briri** [comment]
You just need to set the following in your `config/initializers/recaptcha.rb`
```ruby
Recaptcha.configure do |config|
  config.site_key  = 'MY_SITE_KEY'
  config.secret_key = 'MY_SECRET_KEY'
  #config.proxy = 'http://someproxy.com:port'
end
```
FYI, recaptcha won't appear if you access the contact us page when you're logged in. You need to be logged out to see it.

**Comment by vyruss** [comment]
@briri that's the new syntax and it won't work with the recaptcha v0.4.0 gem on the live service. I wonder whether that got deprecated by Google and stopped working?

**Comment by briri** [comment]
Ah. didn't realize this was on the live service. Thought we were talking about your Roadmap test server. 
Yes, they may have deprecated it. Might be worth updating the gem

**Comment by vyruss** [comment]
Nah, the keys had expired after all for some reason (google recaptcha admin panel inactivity?). I replaced them with new ones and it works now...
