### ISSUE TITLE
Guidance text boxes showing markup when in edit view

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2640]
When editing existing guidance the text boxes require you to input the html markup rather than the displaying the usual wysiwyg editor. You are able to edit the text and as long as you use html it does work as expected.

For example:
![screenshot-dmponline-test dcc ac uk-2020 08 17-16_51_47](https://user-images.githubusercontent.com/27511575/90455353-b55c2b00-e0aa-11ea-9365-699871c235cd.png)

**Comment by mariapraetzellis** [comment]
probably related to the tinyMCE boxes

**Comment by mariapraetzellis** [comment]
Looks good to me. @pherterich / @magdalenadrafiova do you want to confirm?

**Comment by magdalenadrafiova** [comment]
when it goes to the guidance list I can see for a split second the html code bu then it jumps to the text:
<img width="897" alt="Screenshot 2020-09-17 at 09 12 55" src="https://user-images.githubusercontent.com/47178106/93439073-ffad1380-f8c5-11ea-94a5-3bdb9eac3cec.png">
