### ISSUE TITLE
Missing tool tips 

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2641]
When creating new Guidance groups, if the user mouses over the "Published" or "Optional subset" check boxes a tool tip should appear. In the Rails 5 version the tool tip does not appear. I will check to see if this is a problem in other areas where tool tips should appear. 

![screenshot-dmponline-test dcc ac uk-2020 08 17-17_40_23](https://user-images.githubusercontent.com/27511575/90457573-c7d96300-e0b0-11ea-8648-ee172b7c5d0e.png)

**Comment by mariapraetzellis** [comment]
might need a fontawesome upgrade

**Comment by mariapraetzellis** [comment]
Looks good. @pherterich/ @magdalenadrafiova do you want to confirm?

**Comment by magdalenadrafiova** [comment]
looks good closing here 
- published: 
<img width="674" alt="Screenshot 2020-09-17 at 09 10 50" src="https://user-images.githubusercontent.com/47178106/93438820-b9f04b00-f8c5-11ea-898b-a878923dcffa.png">

-optional subset: 
<img width="688" alt="Screenshot 2020-09-17 at 09 10 54" src="https://user-images.githubusercontent.com/47178106/93438842-bf4d9580-f8c5-11ea-93de-174098148789.png">
