### ISSUE TITLE
One click plan creation points to a 404

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2642]
I'm not sure if this is just how the test site is configured, but clicking on the "Create a New Plan" icon from the DMP Templates page (https://dmponline-test.dcc.ac.uk/public_templates) goes to a 404

**Comment by pherterich** [comment]
Potential knock on issue from org issue, as no defaults set

**Comment by mariapraetzellis** [comment]
This looks good to me. @pherterich or @magdalenadrafiova do you want to confirm?

**Comment by magdalenadrafiova** [comment]
Works well!
