### ISSUE TITLE
Deleting old plan causes validation error

### ISSUE THREAD

**Issue by raycarrick-ed** [DMPRoadmap/roadmap#2643]
Please complete the following fields as applicable:

**Expected behaviour:**
Should be able to remove plan on dashboad

**Actual behaviour:**
if it's an old plan which doesn't have an org associated then it fails validation

**Steps to reproduce:**
On system with plan created prior to orgs being associated with plans, delete plan from dashboard.

**Comment by mariapraetzellis** [comment]
@raycarrick we're not sure how to UAT this. Can you recheck this on the plan that you originally saw this issue with?

**Comment by raycarrick-ed** [comment]
@mariapraetzellis @pherterich - I don't think you can really UAT this. I've tested and it looks fine now. So I'll close.
