### ISSUE TITLE
Plan review not working due to 404

### ISSUE THREAD

**Issue by pherterich** [DMPRoadmap/roadmap#2645]
**Expected behaviour:**
As an admin, for the plans submitted for feedback, I expect to be able to click on a plan - click the write plan tab and provide feedback

**Actual behaviour:**
Example from TU Delft e.g. https://dmponline-test.dcc.ac.uk/plans/49413/edit?phase_id=7287 leads to a 404 error.

Related to mailing, trying to complete a review requests results in the following error " Error: Unable to notify user that you have finished providing feedback." - probably because mailing isn't set up yet.

**Steps to reproduce:**
Assign yourself TU Delft affiliation, go to Plans (https://dmponline-test.dcc.ac.uk/org_admin/plans) and click on any of the examples submitted for review and try to provide feedback.

**Comment by raycarrick-ed** [comment]
Passing user object rather than user id in a couple of places
Fixed in:
https://github.com/DMPRoadmap/roadmap/tree/issue%232645

**Comment by mariapraetzellis** [comment]
This looks good to me now. @pherterich do you want to verify?

**Comment by pherterich** [comment]
Works as expected now 😄
