### ISSUE TITLE
Template editing - no dragging arrows displayed

### ISSUE THREAD

**Issue by pherterich** [DMPRoadmap/roadmap#2646]
**Expected behaviour:**
When editing sections in templates, there should be arrows displayed that allow me to re-arrange added/customised sections by dragging.

**Actual behaviour:**
The only icon displayed is the + to expand the section - there is no arrow and added/customised questions cannot be re-arranged.

**Steps to reproduce:**
Add a new section to a template (e.g. https://dmponline-test.dcc.ac.uk/org_admin/templates/6277/phases/7524/edit?section=44829) and try to move it around.

**Comment by pherterich** [comment]
Might be javascript or Font Awesome

**Comment by raycarrick-ed** [comment]
Fixed in:
https://github.com/DMPRoadmap/roadmap/tree/issue_2646
change of arrows name in fontawesome.
Also fixed the longstanding issue with the open/close section arrow which for a URL with a section param was initialized wrongly and therfore in the wrong state for evermore.

**Comment by pherterich** [comment]
Can confirm that they are there and working now but they are also really close to the + / - , not sure if that needs fixing in any way.
![template_arrows](https://user-images.githubusercontent.com/8457675/91712630-0d516200-eb80-11ea-9f42-2e34c402e4a2.png)

**Comment by mariapraetzellis** [comment]
Also confirming that the icons are now working as expected. They are too small though. I wonder if this is related to: https://github.com/DMPRoadmap/roadmap/issues/2667 ?

**Comment by mariapraetzellis** [comment]
I'm not seeing the increased gap between drag sign and plus/minus. Is this in the test environment? @martaribeiro 

![screenshot-dmponline-test dcc ac uk-2020 09 16-13_36_45](https://user-images.githubusercontent.com/27511575/93389902-b6a38380-f821-11ea-8562-49b63e4f8272.png)

**Comment by mariapraetzellis** [comment]
Can you check to see if this was deployed and deploy if not? @xsrust

**Comment by xsrust** [comment]
Appologies, I didn't realise I'd been pinged on this on this ticket.

I can confirm this is deployed out now:
![Screenshot_20200921_153929](https://user-images.githubusercontent.com/7352616/93780959-b55ac800-fc20-11ea-9807-175b1759e129.png)

**Comment by mariapraetzellis** [comment]
Looks good to me 👍
