### ISSUE TITLE
User with any admin rights needs access to admin area

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#265]
I ticked the permissions boxes for editing Org details and granting privileges to other users (screenshot below).
![screen shot 2017-04-24 at 5 46 32 pm](https://cloud.githubusercontent.com/assets/12703638/25364293/2f4c9d0a-2916-11e7-8da2-d1e00daf5179.png)

When I signed in with this account, I was presented with the option to navigate to the Admin area in the upper right drop-down...however, I couldn't actually navigate there and received the message "You are not authorized to perform this action" (screenshot below). 

The expected behavior is that a user w/admin privileges should be able to enter the Admin area but only edit the appropriate areas (in this case, I should see the Org details and Users tabs in the Admin area).

![screen shot 2017-04-24 at 5 42 39 pm](https://cloud.githubusercontent.com/assets/12703638/25364329/7f5a411c-2916-11e7-9529-9e95cf1b20a7.png)

**Comment by vyruss** [comment]
@xsrust could you look into this?

**Comment by stephaniesimms** [comment]
This seems to be fixed now. I can access the Admin area with at least one set of admin privileges. And now I can grant the same permissions to others that I hold myself. This functionality will undergo some changes after UX work is implemented for larger MVP (i.e., some permissions may be bundled together) but for now I think it's working as expected. Closing issue.
