### ISSUE TITLE
PG::UndefinedFunction  when executing migrate_contributors task

### ISSUE THREAD

**Issue by benjaminfaure** [DMPRoadmap/roadmap#2653]
Hello everyone, 

I've been working on migrating my local instance to DMPRoadmap V2.2.0 and I had this error : 

```
ActiveRecord::StatementInvalid: PG::UndefinedFunction: ERROR:  function lower(integer) does not exist
LINE 1: ...ntifier_schemes"."active" = $4 AND (LOWER(name) = LOWER(2)))...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
: SELECT  "identifiers".* FROM "identifiers" WHERE "identifiers"."identifiable_id" = $1 AND "identifiers"."identifiable_type" = $2 AND "identifiers"."identifiable_type" = $3 AND "identifiers"."identifier_scheme_id" IN (SELECT "identifier_schemes"."id" FROM "identifier_schemes" WHERE "identifier_schemes"."active" = $4 AND (LOWER(name) = LOWER(2)))  ORDER BY "identifiers"."id" ASC LIMIT 1
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql_adapter.rb:637:in `prepare'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql_adapter.rb:637:in `prepare_statement'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql_adapter.rb:596:in `exec_cache'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/activerecord-4.2.11.3/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/activerecord-4.2.11.3/lib/active_record/querying.rb:39:in `find_by_sql'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/bullet-6.1.0/lib/bullet/active_record42.rb:26:in `find_by_sql'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/activerecord-4.2.11.3/lib/active_record/relation.rb:639:in `exec_queries'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/activerecord-4.2.11.3/lib/active_record/association_relation.rb:32:in `exec_queries'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/activerecord-4.2.11.3/lib/active_record/relation.rb:515:in `load'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/activerecord-4.2.11.3/lib/active_record/relation.rb:243:in `to_a'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/bullet-6.1.0/lib/bullet/active_record42.rb:58:in `to_a'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/activerecord-4.2.11.3/lib/active_record/relation/finder_methods.rb:500:in `find_nth_with_limit'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/activerecord-4.2.11.3/lib/active_record/relation/finder_methods.rb:484:in `find_nth'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/activerecord-4.2.11.3/lib/active_record/relation/finder_methods.rb:127:in `first'
/home/ubuntu/Documents/DMPOPIDoR/app/models/user.rb:236:in `identifier_for'
/home/ubuntu/Documents/DMPOPIDoR/lib/tasks/upgrade.rake:1079:in `block (3 levels) in <top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/parallel-1.19.2/lib/parallel.rb:508:in `call_with_index'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/parallel-1.19.2/lib/parallel.rb:361:in `block (2 levels) in work_in_threads'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/parallel-1.19.2/lib/parallel.rb:519:in `with_instrumentation'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/parallel-1.19.2/lib/parallel.rb:360:in `block in work_in_threads'
/home/ubuntu/.rvm/gems/ruby-2.4.9/gems/parallel-1.19.2/lib/parallel.rb:211:in `block (4 levels) in in_threads'

```

It seems to be coming from this line : 
https://github.com/DMPRoadmap/roadmap/blob/e391c74f090430585a2b9b56e2f0c665d03fe5f6/lib/tasks/upgrade.rake#L1079

and possibly this one too : 
https://github.com/DMPRoadmap/roadmap/blob/e391c74f090430585a2b9b56e2f0c665d03fe5f6/lib/tasks/upgrade.rake#L1106

It is caused by the `orcid` variable which is passed all the way to : 
https://github.com/DMPRoadmap/roadmap/blob/29737cea7b2c5de1c21ce97049a0c16c7ba2906a/app/models/identifier_scheme.rb#L44

`value` is supposed to be a string, `orcid` being an object, I suppose Rails casts it into an integer which cause the bug I mentioned. 

I seems this error is specific to PostgreSQL which in why it hasn't been found sooner (If I recall you are all using MySQL ?).

It can be easily fixed by changing `owner.identifier_for(orcid)` to `owner.identifier_for(orcid.name)`

**Comment by xsrust** [comment]
Good catch @benjaminfaure 

We're using PostgreSQL at the DCC but haven't migrated any instances to V2.0.0 so hadn't hit this issue yet.
Downgraded my local-environment from Rails4 to the Master branch and I'm now experiencing the same issue.
I've submitted a PR (referenced above) which will ensure the value passed is a string and should fix the issue.

@briri, you did all the initial build-out of the feature (with mySQL) so would you mind double-checking that the above makes sense in the context of that work. 
_sidenote_ It might be worthwhile having a pass over these to see if we can make the call-chain a bit more homogeneous. It looks like the `identifier_for_scheme` method on the `identifiable` concern already handled that conversion, but some of the `identifiable` objects have their own selection-logic for which the difference seems to be whether the filtering happens in the database or ruby.

**Comment by briri** [comment]
The Identifier model has a scope called `by_scheme_name(value:, identifiable_type:)` which retrieves any identifiers for the specified identifier scheme and identiable_type (e.g. `Identifier.by_scheme_name(value: 'orcid', identifiable_type: 'User')`)

You could potentially handle that scope directly within the IdentifierScheme model (e.g. `IdentifierScheme.by_name(name: 'orcid').identifiers`) but, Identifier is polymorphic so in some situations where an IdentifierScheme may be applicable to multiple identiable_types you would not get the correct results. The `identifier_scheme` value on this table can also be set to nil if it doesn't belong to a specific scheme (e.g. a plan's grant id if its a URL or a value like '1234').

The Identifiable concern has an instance method called `identifier_for_scheme(scheme:) which returns the target model's identifier for the specified scheme (e.g. `user.identifier_for_scheme(scheme: 'orcid')`). 

We may want to reevaluate the data model at some point. The IdentifierScheme concept may be become a hindrance going forward as we continue to add external identifiers to the system. Perhaps we would be better served storing them as a simple enum value like I have done on a [separate project](https://github.com/CDLUC3/dmphub/blob/main/app/models/identifier.rb)
