### ISSUE TITLE
Active admin bug

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#266]
If I try to edit anything on my profile via super admin it throws an error. I tried changing language preference and organisational affiliation. The error below is from the second case.
![edit-user](https://cloud.githubusercontent.com/assets/6169940/25379314/89deb8aa-29a4-11e7-97d6-04e52406876e.PNG)

This may just be a display error as when I've logged in again it seems to have changed me to DCC...

Having just checked that I can edit other users ok, it seems this is something that only occurs on editing my own account via super admin

**Comment by vyruss** [comment]
@sjDCC I cannot replicate the error on dmponline-test

**Comment by sjDCC** [comment]
Have just checked and it's working for me on dmponline-test but not on staging. Let's raise this on the call today as both should be working the same

**Comment by stephaniesimms** [comment]
Update: this is not yet working on Roadmap stage.

**Comment by sjDCC** [comment]
All works fine on staging too now. Closing out
