### ISSUE TITLE
Font is smaller and margins are bigger in Rails 5 version 

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2667]
It looks like the default font size for the Rails 5 version is smaller than 4.2. Also noticed that the margins look bigger in 5. It makes it hard to read and creates a lot of wasted white space.

Rails 5
![screenshot-dmponline-test dcc ac uk-2020 09 04-12_09_53](https://user-images.githubusercontent.com/27511575/92277373-a7c6e380-eea7-11ea-9664-0923766d41f1.png)

Rails 4.2
![screenshot-dmptool-stg cdlib org-2020 09 04-12_10_11](https://user-images.githubusercontent.com/27511575/92277382-aeedf180-eea7-11ea-9ca3-ec37c502b2cd.png)

**Comment by pherterich** [comment]
@xsrust to try and reduce white space in general and see if that has knock on effects

**Comment by mariapraetzellis** [comment]
After discussion, we'll also look at widening margins if possible. @martaribeiro will take a look

**Comment by xsrust** [comment]
https://dmptool-stg.cdlib.org/ (server for comparison)

**Comment by martaribeiro** [comment]
I had a look at both css (rails 4 and rails 5), I used 3 different browsers (Firefox, Safari and Chrome) and the fontsize was the same. 
@mariapraetzellis  could you please check it again and maybe check if the zoom is 100% in both.

**Comment by mariapraetzellis** [comment]
You're right @martaribeiro, sorry about that.
