### ISSUE TITLE
Create plan error

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#267]
I've just tried creating a plan and got the error below
![capture](https://cloud.githubusercontent.com/assets/6169940/25383401/ddf5537c-29b3-11e7-8bef-e743adc0170b.PNG)

This was on an account I have just created by sharing a plan with my personal account, so perhaps it's because there is no organisation or any other affiliation to draw in automatically?

When I shared the plan and logged in under the new account, I was taken straight to the my plans table, not edit profile as a usual first time login would be directed.

**Comment by sjDCC** [comment]
This must be linked to a user not having an organisation. I added a university affiliation to this account and plans now create fine.

**Comment by vyruss** [comment]
Possible duplicate of #257

**Comment by sjDCC** [comment]
Yes, looks like it is. Thanks for spotting @vyruss

**Comment by jollopre** [comment]
This issue has been solved in #257

**Comment by stephaniesimms** [comment]
Working as expected, although see new issue #285 . Closing this one.
