### ISSUE TITLE
Add new field for "Field of Science" classification system

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2673]
As recommended and implemented by DataCite (described here: https://blog.datacite.org/power-of-pids/) we should add a new field to define the "field of science" for which a DMP is being created. This will allow for more granular search queries and allow us to use filters for content search.

I think this would be best on the Project Details page but we can discuss.

The Field of Science and Technology classification is described here: https://www.oecd.org/science/inno/38235147.pdf

**Comment by briri** [comment]
We have added a subset of this into the re3data repository search. It would be better to add it as described above to help pre-filter searches.
