### ISSUE TITLE
Share plan giving error

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#268]
The share plan function is throwing an error when you click to add a collaborator. This is only happening on the DMPonline test site (not UC3 staging) and occurs for old existing plans as well as brand new ones
![share-plan](https://cloud.githubusercontent.com/assets/6169940/25383604/c2f47110-29b4-11e7-91e3-65749aecdea0.PNG)
![share-plan-error](https://cloud.githubusercontent.com/assets/6169940/25383611/c7e64b08-29b4-11e7-9389-dca06381d76b.PNG)

**Comment by vyruss** [comment]
dab559a0865b4a5de2ed4f9923e5adc75f3f049a

**Comment by vyruss** [comment]
Please @sjDCC @stephaniesimms, can you confirm whether the invitee should get both the invitation (to register) email and the plan sharing notification email when they are not registered?

**Comment by sjDCC** [comment]
Fixed. Works on both test sites so closing out
