### ISSUE TITLE
Cannot set org.managed to true in orgs_controller#admin_update

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#2682]
Please complete the following fields as applicable:

**Expected behaviour:**

Being able to set the flag `managed` of an organisation to `true` in `orgs_controller#admin_update`

**Actual behaviour:**

Results always in `managed` being set to `false`

Reason: one rule is evaluated twice:

https://github.com/DMPRoadmap/roadmap/blob/master/app/controllers/orgs_controller.rb#L38 : now the value is true
https://github.com/DMPRoadmap/roadmap/blob/master/app/controllers/orgs_controller.rb#L54 : now the value is back false

Remove rule 54?

**Steps to reproduce:**

**Comment by xsrust** [comment]
Good catch @nicolasfranck 

I'll submit a patch to `master`  later on today for this.
