### ISSUE TITLE
orgs_controller#shibboleth_ds view expects list of Org, not Identifier 

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#2686]
Please complete the following fields as applicable:

**Expected behaviour:**

**Actual behaviour:**

* `orgs_controller#shibboleth_ds` selects a list of `Identifier` and stores it in `@orgs`
    (which crashes btw because it cannot sort on `name`): https://github.com/DMPRoadmap/roadmap/blob/master/app/controllers/orgs_controller.rb#L92

* `app/views/orgs/shibboleth_ds.html.erb` uses `@orgs` as if they are organisations ("Select your organisation")

Unused code?

**Steps to reproduce:**

* checkout version 2.2.0
* logout
* make sure there are Identifier of type `Org` and scheme `shibboleth`
* go to `/orgs/shibboleth`

**Comment by briri** [comment]
fixed and will be included as part of v3.0.1
