### ISSUE TITLE
Display issue under 'plan details'

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#269]
The plan summary display under 'plan details' tab is incorrect. I think the first issue is related to a migration error and the second is separate.

1. The summary text under "This plan is based on" suggests that the funder chosen is the person who has customised the template and that the organisation I'm based at is the funder. These roles have been mixed up. It should also be 'customised by' not 'customised from'.

2. The AHRC template sections are displaying in the wrong order
![display error](https://cloud.githubusercontent.com/assets/6169940/25386348/01b36762-29bf-11e7-9cd4-ea7a5c88c9bb.PNG)

**Comment by jollopre** [comment]
- The summary text now is correctly displaying Funder and Institution
- The sections are ordered by number when retrieved from db

**Comment by stephaniesimms** [comment]
@sjDCC can you test this and make sure it looks okay to you? I'm not familiar enough w/the data to be sure I can see if all is fixed.

**Comment by sjDCC** [comment]
All looks good. Closing issue
