### ISSUE TITLE
Unable to complete a feedback request

### ISSUE THREAD

**Issue by pherterich** [DMPRoadmap/roadmap#2692]
**Expected behaviour:**

When being done with providing feedback, clicking the "complete" action in the notification overview should send an email to the user and remove the plan from the overview

**Actual behaviour:**
Getting the following error message
" Error: Unable to notify user that you have finished providing feedback."

**Steps to reproduce:**
Click the "complete" button for any of the plans submitted for feedback on https://dmponline-test.dcc.ac.uk/org_admin/plans

**Comment by xsrust** [comment]
Think this is actually due to the plan->org_id link that propagated up from the Master branch (so a data-issue with DMPonline-test)
I'm running the rake:task that came along with that work and will re-ping for testing once that's finished running

**Comment by xsrust** [comment]
That's done running now

**Comment by pherterich** [comment]
Works for me, @magdalenadrafiova do you want to confirm and close?

**Comment by magdalenadrafiova** [comment]
comments and hitting feedback complete worked well. closing :)
