### ISSUE TITLE
Merging users leads to 404

### ISSUE THREAD

**Issue by pherterich** [DMPRoadmap/roadmap#2693]
Please complete the following fields as applicable:

**Expected behaviour:**
When merging 2 users, I would expect to see a successful user profile page that has the DMPs from the merged account added to it 

**Actual behaviour:**
After confirming the merge, I end up with a "page unavailable" message

**Steps to reproduce:**
I tried to merge https://dmponline-test.dcc.ac.uk/super_admin/users/40384/merge with the hotmail address account for Rosie.

**Update**
I do think the plan was moved across - the user now has 8 plans and the account that was merged into it doesn't have a record associated any longer.

**Comment by xsrust** [comment]
This looks like the merge action didn't get refactored fully to the identifier code.

**Comment by xsrust** [comment]
appologies for ticket noise, I didn't mean to close

**Comment by pherterich** [comment]
Merging seems to work, search for email seems to have issues, but search for last name seems to pull up the list of emails, so nothing major. @magdalenadrafiova do you want to double check and close?

**Comment by magdalenadrafiova** [comment]
Merging threw me an error message - I did not have problem to search for emails: 
<img width="833" alt="Screenshot 2020-10-07 at 09 47 49" src="https://user-images.githubusercontent.com/47178106/95308793-3c937700-0882-11eb-9c95-bb4675501470.png">

**Comment by xsrust** [comment]
@magdalenadrafiova I've Confirmed the error related to merging.  It looks like there's issues if there are leftover user-identifiers on the account.

@pherterich   Would you be able to slack me with the substring your searching for and the email you expect to appear?

**Comment by pherterich** [comment]
@xsrust It worked now when I tried it again. I might have been blind and not realised that the system turned my search into a result 🤦
