### ISSUE TITLE
Unable to switch on "request feedback"

### ISSUE THREAD

**Issue by pherterich** [DMPRoadmap/roadmap#2694]
Please complete the following fields as applicable:

**Expected behaviour:** 
Go to organisation info -> Request feedback -> toggle on button -> Add message -> click save -> Get a success message confirming it's switched on

**Actual behaviour:**

When clicking the save button, I get redirected to the 404 error page. Unlike with #2693 it doesn't seem to save the action and before showing the error.

**Steps to reproduce:**
I've tried with the "University of Birmingham" as I know they don't have it enabled yet.

**Comment by xsrust** [comment]
Needed to run the new `rails upgrade:column_defaults` task.
This resolved the initial errors, but now we're running into a new 404 thrown by dragonfly

**Comment by xsrust** [comment]
Looks like the new issues are caused by validating the presence of the logo.

we are going to need to re-add the dragonfly pre-save check for the logo file to avoid issues like this if the logo has not been found (i.e. moved from S3 or the filestore)

**Comment by pherterich** [comment]
This one works now, but we're back to the re1uest feedback tab for the user leading to a 404 :( (e.g. https://dmponline-test.dcc.ac.uk/plans/56073/request_feedback)
