### ISSUE TITLE
Editing rails5 template throws 'page unavailable' error when saving new changes

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2697]
I have put together a new template on https://dmponline-test.dcc.ac.uk/ for University of Exeter. I forgot to associate themes with my questions so I went back to edit this to my new guidance will appear there, but when I hit save it threw 'page unavailable' message.

When I did not hit save it seemed to save the 'theme' without a problem.

**Comment by xsrust** [comment]
I've not been able to reproduce this behavior on either the Exeter template nor another new template.
I can save questions both with and without themes.  I'm also not sure how the system would persist data in the case of "When I did not hit save it seemed to save the "theme" without a problem".

Could there be another part of the template workflow that was triggered here, like the funder-customizations?

**Comment by xsrust** [comment]
@magdalenadrafiova I think I may have re-created the bug.

DId you publish the template immediately before going back to add the themes?
Publishing a template followed by editing it throws a 404 the first-time it's edited for me

**Comment by magdalenadrafiova** [comment]
Yes!

**Comment by pherterich** [comment]
Hmm, I can edit on top of @magdalenadrafiova 's template without issues and save by hitting the button.
