### ISSUE TITLE
System messages displaying in "Current privileges" column for users 

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2698]
I am not sure whether this is rails5 bug or whether this is actually how the logic of dmponline-test works, but I do not see the 'edit' privileges tab in the dmponline-test at all.

**Comment by pherterich** [comment]
It's there, but it's hiding behind loong weird system messages

![priviledges](https://user-images.githubusercontent.com/8457675/95085995-da1e6780-0717-11eb-9906-e3eff09f4f4e.png)

**Comment by magdalenadrafiova** [comment]
so is this how it is going to be managed? On the 'main' interface it is one extra column: 
<img width="1297" alt="Screenshot 2020-10-05 at 14 35 38" src="https://user-images.githubusercontent.com/47178106/95086186-194cb880-0718-11eb-9f14-386c1c324630.png">

**Comment by pherterich** [comment]
Makes sense to me, no need for 2 columns for that, especially as we added the identifier column.

**Comment by pherterich** [comment]
Renamed to the things that's still an issue, assigning privileges worked fine for me.

**Comment by xsrust** [comment]
Sorry for not cathing this earlier.

This is related to the Translation.io upgrade ( it does not like to translate the empty string`""` )
@briri has already caught this and fixed it in: https://github.com/DMPRoadmap/roadmap/pull/2696/files#diff-da8699dd5cc68fd9857aa35f34f54d5dL6

**Comment by pherterich** [comment]
Looks good now, thanks for fixing 😄
