### ISSUE TITLE
Remove the ROR link in the contributors tab 

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2705]
John requested that we remove the ROR link in the contributors tab as it is potentially confusing to users and unnecessary to display.

![screenshot-dmptool.org-2020.10.09-14_46_50.png](https://images.zenhubusercontent.com/5f04b83738cdcf7d7c00e2e1/04998247-fa30-4ded-9c85-a781b8c1fa26)

**Comment by briri** [comment]
submitted as an update to DMPRoadmap in [PR 2717](https://github.com/DMPRoadmap/roadmap/pull/2717)

**Comment by mariapraetzellis** [comment]
Looks good.
