### ISSUE TITLE
Fix redirect warnings

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2710]
Brakeman detected the following vulnerabilities. 
```shell
Confidence: High
Category: Redirect
Check: Redirect
Message: Possible unprotected redirect
Code: redirect_to("#{shib_login_url}?#{shib_callback_url}&#{"entityID=#{Identifier.by_scheme_name("shibboleth", "Org").where(:identifiable => Org.where(:id => shib_params["shib-ds"][:org_id])).first.value}"}")
File: app/controllers/orgs_controller.rb
Line: 126

Confidence: High
Category: Redirect
Check: Redirect
Message: Possible unprotected redirect
Code: redirect_to(Plan.deep_copy(Plan.find(params[:id])), :notice => success_message(Plan.deep_copy(Plan.find(params[:id])), _("copied")))
File: app/controllers/plans_controller.rb
Line: 364
```

See the following for possible solutions: https://brakemanscanner.org/docs/warning_types/redirect/

**Comment by xsrust** [comment]
I've inspected the first redirect and I'm confident it's not unprotected.
The `shib_login_url` comes from the request's URL plus `/Shibboleth/SSO/` and the `shib_callback_url` and the only user-input data is used to select a relevant organisation from the db's IDP url (and is in the querystring of the redirect)

We also used to have it in our `config/brakeman.ignore`, but the line number has changed.

**Comment by xsrust** [comment]
the 2nd redirect should also be protected.

The user-supplied credentials here is the `params[:id]` and the redirect occurs after the authorization check.
It was also in the existing ignore file but the line had moved.

**Comment by briri** [comment]
👍 Cool. thanks for investigating. Looks like we just need to update that brakeman.ignore file then
