### ISSUE TITLE
Remove/move table formatting toolbar

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#272]
If I add a table while creating a new template, a table formatting toolbar pops up that obscures the entire editor. Clicking anywhere in the table causes the toolbar to display. 

We should either display the toolbar below the table consistently, as in the plan creation and share note editors (screenshots below). Or if possible it would be better to remove the table formatting toolbar completely. What do you think @sjDCC ?

![table-edit-toolbar](https://cloud.githubusercontent.com/assets/12703638/25391203/92ace214-298a-11e7-83de-890963208e99.png)

![screen shot 2017-04-25 at 7 44 51 am](https://cloud.githubusercontent.com/assets/12703638/25391532/4cec15f0-298b-11e7-8290-2315863a8131.png)

**Comment by sjDCC** [comment]
I think it's an edge case for a table format to be needed in guidance, but it is possible (I can think of one concrete example already based on MRC) so best to leave it in but ensure it displays below like in screenshot 2

**Comment by sjDCC** [comment]
The formatting bar still appear right over the table and obscures the view in the admin interface
![still-in-way](https://cloud.githubusercontent.com/assets/6169940/26488524/b26463b4-41fb-11e7-9613-776a7a41f530.PNG)

**Comment by jollopre** [comment]
The formatting toolbar changes have been made to the following views:

- Template: add/edit
- Guidance: add/edit
- Phase: add/edit
- Section: add/edit
- Question: add/edit

**Comment by sjDCC** [comment]
Hi @jollopre The issue @stephaniesimms flagged doesn't appear to be fixed. If I go to add a table on the admin interface, the formatting toolbar displays over the table that has been inserted so it can't easily be worked on. It's not possible to drag the toolbar out of the way so we need it to display elsewhere e.g. below the edit box.

Here's an example where it still obscures the view. It's taken when editing a template, adding a section description. I'm using chrome. Haven't checked other browsers.
![bar-obscuring-view](https://user-images.githubusercontent.com/6169940/26874806-e2b20326-4b76-11e7-8fa5-c229db0e158d.PNG)

**Comment by vyruss** [comment]
Where does this happen? I'm getting the proper display: ![image](https://user-images.githubusercontent.com/18707439/26876302-764204a0-4b7d-11e7-869b-acb25233c5a8.png)

Could it be a browser issue? I've used both Chrome and Firefox

**Comment by sjDCC** [comment]
I think this may be an issue with me or my machine. Have tried clearing cache as @jollopre suggested and tried in IE, Chrome and Firefox. Got same issue in each.

Suggest @dsisu and @stephaniesimms test, and if it displays fine for them just close out.

**Comment by stephaniesimms** [comment]
If I create a new table, the toolbar now displays at the bottom of the editor (screenshot 1). But as soon as I type anywhere inside the table, the toolbar moves to the top and obstructs everything (screenshot 2). This happens for me in Chrome and Firefox. 

If this is difficult to resolve, could a short-term fix be to deactivate the toolbar @sjDCC  (I personally don't find it very useful and don't mind creating a brand new table if I need to make changes)? How often do admins create tables in templates anyway? We plan to implement the Substance editor first thing after MVP so it might not be worth the effort to fix this now.

![table-toolbar](https://user-images.githubusercontent.com/12703638/26901805-e9369ec2-4b8b-11e7-8226-982617af6b66.png)

![screen shot 2017-06-07 at 2 14 02 pm](https://user-images.githubusercontent.com/12703638/26901812-ebd93720-4b8b-11e7-8c38-88b7645717ee.png)

**Comment by sjDCC** [comment]
I am not fussed either way. It's rare people use tables so if this is more than a 30 min fix I would deactivate the toolbar. If it's quick an easy, then just get it to remain below the table. As you say, we're implementing substance soon so not worth much effort now.

@jollopre your call on which approach you want to take to fix it

**Comment by sjDCC** [comment]
Actually, doing a quick test myself, the toolbar displays beneath the table and stays there when I'm typing. This is on Chrome.
![capture](https://user-images.githubusercontent.com/6169940/26924126-60cc6286-4c3c-11e7-841c-ffcccd1f3f99.PNG)

@jollopre if you can't replicate the bar obscuring the table, let's just close out. It's going to be so rare (potentially even never) that this happens and it will be replaced soon anyhow.

**Comment by jollopre** [comment]
The quick and easy way would be disabling the table options if it is causing problems and it is rarely used. It should be a minute job, hopefully (https://www.tinymce.com/docs/plugins/table/#table_appearance_options)

**Comment by dsisu** [comment]
Hi all, I get the same as @sjDCC, formatting toolbar appears under the table, in both Firefox and Chrome. It keeps moving down if you insert rows so it is consistently displayed under the table. You can't control all aspects of the display anyway. For example, if you click on the table properties button, this opens up a box of editing options. The box opens right on top of the table, although  you can drag that to the side too so you can see the table (assuming you work out that you can drag it, that is). The only thing that I dislike about the table is the format in which it appears when inserted - narrow cells, you can barely click inside the cell you want. I agree that we should close this for now and worry about it if users bring it up too often. 

![tableedit](https://user-images.githubusercontent.com/2138956/26938568-74fd9448-4c6c-11e7-86d2-3cf2d1b8b2d0.JPG)

**Comment by vyruss** [comment]
Even if the toolbar does cover the table, one can always click outside the table and get rid of it. Apparently this was a known issue for TinyMCE and is marked as resolved in their latest release (tinymce/tinymce#2494). Close this one and re-examine if any users complain in the future?

**Comment by sjDCC** [comment]
Agree
