### ISSUE TITLE
Update template migration

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#273]
@jollopre noted on #151 that the `org_id` should not be necessary for the 3 helper functions I added to the Template model. I agree with his assessment, but the migrated data requires it to be in pplace to correctly identify customizations (see SQL below).

We have several issues with the templates table. Some of the issues were introduced during the migration process and others were created by logic errors in the code.

When we migrated, customizations of funder templates were given the same dmptemplate_id as the parent funder template. Each organisation's customization should have a unique dmptemplate_id. The customization_of field correctly contains the parent funder template's dmptemplate_id.

The code (which has been fixed) was creating a new version every time the template was updated.

The versioning issue has been addressed but we should also correct the migration and then re-migrate the data or at the very least run some scripts to clean it up.

```sql
mysql> select id, org_id, dmptemplate_id, customization_of, version, created_at from templates where dmptemplate_id = 1;
+-----+--------+----------------+------------------+---------+---------------------+
| id  | org_id | dmptemplate_id | customization_of | version | created_at          |
+-----+--------+----------------+------------------+---------+---------------------+
|   1 |      3 |              1 |                1 |       0 | 2016-01-18 12:33:52 |
|   2 |      1 |              1 |             NULL |       0 | 2016-01-18 12:33:52 |
|   3 |      5 |              1 |                1 |       0 | 2016-01-18 12:33:52 |
|   4 |     13 |              1 |                1 |       0 | 2016-01-18 12:33:52 |
| 117 |      1 |              1 |             NULL |       1 | 2017-03-20 20:35:45 |
| 118 |      1 |              1 |             NULL |       1 | 2017-03-20 20:36:21 |
| 125 |      1 |              1 |             NULL |       1 | 2017-03-21 21:50:54 |
| 128 |      1 |              1 |             NULL |       2 | 2017-03-27 19:43:53 |
| 129 |      1 |              1 |             NULL |       2 | 2017-03-27 19:43:55 |
| 130 |      1 |              1 |             NULL |       3 | 2017-03-27 19:44:10 |
| 131 |      1 |              1 |             NULL |       3 | 2017-03-27 19:44:12 |
| 141 |      1 |              1 |             NULL |       4 | 2017-04-14 19:01:15 |
| 142 |      1 |              1 |             NULL |       4 | 2017-04-14 19:01:16 |
+-----+--------+----------------+------------------+---------+---------------------+
13 rows in set (0.00 sec)
```

**Comment by briri** [comment]
@xsrust I know you made some recent adjustments to the migration scripts for handling the dmptemplate_id field. Can you check to see if that id is being shared across customizations? If so, please update it so that the custmizations have unique values. I'll rerun the migrations afterward

**Comment by xsrust** [comment]
When was the last time you migrated the dataset?  I believe this should be fixed by:
https://github.com/DMPRoadmap/roadmap/commit/d20471cba51a917aa16665d4e4fd5b1dbb183239#diff-2e48120f2164bb2a4e84dbe6462c5646

**Comment by briri** [comment]
I last migrated towards the beginning of March. Thanks for checking into it. I updated #274 which is about cleaning up these template changes but they can be addressed post MVP0.3.

**Comment by briri** [comment]
re-migrated on my local machine and can confirm that this issue was resolved by the commit referenced by @xsrust above
