### ISSUE TITLE
Unable to add links on Org details page

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2737]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
v3.0.0

**Expected behaviour:**
Links are saved when you add them on the Org Details page

**Actual behaviour:**
You receive a 'Successfully saved the Organization' message but the link is not saved. 

I suspect that the params are coming into the controller differently after we upgraded to Rails 5 with strong parameters. It would be beneficial to add some tests around this to catch issues in the future

**Steps to reproduce:**
- Log in as an admin.
- Click 'Organisations' in the admin menu
- Edit an Org 
- Add a link (you may also need to add a contact email for unmanaged Orgs)
- Click save

**Comment by pherterich** [comment]
Saves links for me now

**Comment by mariapraetzellis** [comment]
Confirming that I am able to add org links now.
