### ISSUE TITLE
ApiClient#last_access should be of type datetime instead of date?

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#2742]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

v3.0.0

**Expected behaviour:**

Attribute `last_access` should be of type `datetime`, not `date`.
Otherwise there is no use assigning `Time.now`, or using `@api_client.last_access.utc.to_s` (which crashes)

https://github.com/DMPRoadmap/roadmap/blob/master/app/views/super_admin/api_clients/_form.html.erb#L50
https://github.com/DMPRoadmap/roadmap/blob/master/app/views/super_admin/api_clients/_form.html.erb#L50
https://github.com/DMPRoadmap/roadmap/blob/master/db/migrate/20200207212113_create_api_clients.rb#L11

**Actual behaviour:**

**Steps to reproduce:**

**Comment by briri** [comment]
yes indeed.
