### ISSUE TITLE
Unable to set plan visibility to organization 

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2745]
An admin user reported that plans that they have set to be visible on the organization dashboard do not appear. I was able to recreate this issue in my own account.

For example, this plan is set to be available for the UCOP org: https://dmptool.org/plans/56493

But does not appear on University of California, Office of the President (UCOP) Plans table.

**Comment by xsrust** [comment]
I remember we had this behavior reported as an error recently.
The logic currently enforces that a plan must be `complete` and have either `organisational` or `public` visibility to be displayed on that 2nd dashboard table.

It would be quite trivial to change the logic there if this is no longer the desired behavior.
Another option would be to prevent the plan from being set to either of these visibility settings until after the plan is `complete` and can thus be displayed.

**Comment by briri** [comment]
I did some research into this and found that the plan referenced above has more than 50% of its questions answered but for some reason the `complete` flag was still false. I suspect that there may be an issue in `Plan.no_questions_matches_no_answers` which is called by the `Answer.set_plan_complete` callback

**Comment by briri** [comment]
going to address this on Monday

**Comment by pherterich** [comment]
This works for me.
