### ISSUE TITLE
Org selection is not calling out to the external ROR API

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2746]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
v3.0

**Expected behaviour:**
When you type in the 'Organisation' typeahead box on the 'Create Account' form it should search the local DB for results and call out to the ROR API

**Actual behaviour:**
It only checks the local DB

This appears to be related to the switch over to Strong Params during the Rails 5 upgrade. The incoming data in the POST come through as: 
```
Processing by OrgsController#search as */*
  Parameters: {"org"=>{"name"=>"National"}, "funder_only"=>"false", "type"=>"combined"}
```
But the controller is expecting the :funder_only and :type to be encapsulated in the Strong Params: `{"org"=>{"name"=>"National","funder_only"=>"false","type"=>"combined"}`

**Comment by pherterich** [comment]
Works for me - looks initially at the local institutions I'd expect to show up and then comes up with a very long list from ROR.

**Comment by mariapraetzellis** [comment]
When searching for orgs in the contributors tab I'm seeing orgs not already in the db, so can confirm that it is working.
