### ISSUE TITLE
"Link credentials" on profile page opens a new window

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#2752]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

3.0.0

**Actual behaviour:**

The links "link to your orcid" or "link your institutional credentials" are opened
in a new window where all authentication happens, and after a successfull login
you're redirected to your profile page.

But meanwhile there is still an outdated profile page open. Confusing?

I've seen this behaviour in applications that use this technique to shield
themselves from the authentication layer, but at the end of the authentication
a piece of javascript sends a signal to the opening page, and closes itself.
But that is not the case here.

**Comment by xsrust** [comment]
That seems to be an un-intended consequence of an accessibility feature that was added to signal to end-users when following a link would take them away from the domain where DMPRoadmap is hosted.

The best way to fix this is likely to create an opt-out for the "opens in new window" text/behavior and apply it to both of these links.

**Comment by briri** [comment]
fixed and will be part of the v3.0.1 release.
