### ISSUE TITLE
Configure ORCID authentication

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#276]
The ORCID authentication link under 'edit profile' won't work until we connect our services. 

Need to do this before testing DMPonline

**Comment by vyruss** [comment]
@briri can you advise on Orcid login capability?

**Comment by briri** [comment]
You need to make sure 'orcid' appears in the identifier_schemes table. Once that's in place you should just need to make sure your devise.rb has it defined as well
```ruby
config.omniauth :orcid, 'client_id', 'client_secret', {'scope': '/authenticate'}
```
You need to register your DMPonline app with them in order to get the API keys

**Comment by vyruss** [comment]
Thanks, already registered a 'sandbox' account with ORCiD.

**Comment by sjDCC** [comment]
Works in DMPonline test and staging. Closing out

**Comment by Ebrahim1010** [comment]
@briri 
Referring to your answer above 'You need to register your DMPonline app with them in order to get the API keys' - please advise.

**Comment by xsrust** [comment]
@Ebrahim1010 

I think ORCiD explains their side of it better than we could:
https://members.orcid.org/api/oauth

As for how we're configuring this with rails, check out the config page for the gem we're using, `omniauth-orcid`:
https://github.com/datacite/omniauth-orcid

Between the two of those, you should be able to request an API key from ORCiD, and then get this setup in your application.  

We also have a wiki page of documentation about how the application side handles things:
https://github.com/DMPRoadmap/roadmap/wiki/OAuth-Providers
