### ISSUE TITLE
RSS News Feed for the DMPonline website

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#2788]
Hi, this has been outstanding for a while and it's impacting on the DCC website outstanding issues board as well.

This page https://dmponline.dcc.ac.uk/about_us#News is meant to retrieve the RSS news feed for DMPonline-related news published on the DCC website.

As far as I know, the RSS feed has been fixed and the code is available at https://www.dcc.ac.uk/news/dmponline/feed .

Has anybody tried to put it in place?

Diana

**Comment by pherterich** [comment]
@raycarrick-ed @martaribeiro is this something that needs to go into roadmap or part of our local implementation?

**Comment by raycarrick-ed** [comment]
I think this is local but I am not 100% sure. If treat it as local and find otherwise we can always push it back to roadmap.

**Comment by pherterich** [comment]
Closing this one here as we're addressing this locally in DMPonline.
