### ISSUE TITLE
Update the v1 API to expose a public version of the plan 

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2796]
We will be using the v1 API as a landing page for the DMP ID (DOI). We need to:

- [ ] Define what information is ok to reveal to an unauthenticated user (e.g. if the DMP is privately visible we still need to show something for someone who loads the DOI in their browser ... right now it will produce an Unauthorized error)
- [ ] Update the permissions on the controller to display the default public version

**Comment by mariapraetzellis** [comment]
closing as this is no longer relevant
