### ISSUE TITLE
Create a complimentary JSON schema for DMPRoadmap specific extensions to the RDA common standard

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#2797]
We need to add a new repo to this organization that will host a JSON schema that can be used to enable/define extensions to the RDA Common metadata standard.

For the detailed discussion, see: https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard/issues/27

The schema should be shared with the larger community in an effort to solicit feedback.

Once complete we will need to update the API to use the new schema instead of our current use of `extensions`

**Comment by mariapraetzellis** [comment]
The WG is moving away from the JSON scheme so we need to hold off on this until we have more details.
