### ISSUE TITLE
Set plan visibility at end of writing process

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#280]
For MVP we need a solution for managing the Public DMPs list to ensure that only complete plans are displayed. Future discussions about plan status should involve machine-actionable use cases (see related issue #87). Short-term solution is to prompt users to set plan visibility at the end of the writing process, when a plan is (presumably) complete. 

The default visibility for new draft/in progress plans should be "Private," but when a user reaches the end and clicks "Export" they should get a modal asking them to select:
- Public: anyone can view, copy, and/or download the plan. Your DMP will appear on the Public DMPs page of this site. 
- Institutional: anyone logged in from your institution can view, copy, and/or download the plan.
- Private: only owners, co-owners, and others to whom you granted access can view the plan. Administrators at your organisation can view all plans for program development purposes. See Terms of Use.

The selection will then trigger an email notice about the plan's visibility. We can consider other (additional or alternative) points for asking a user to select/confirm visibility but this seems the most obvious one to me. @sjDCC ?

![screen shot 2017-05-08 at 12 47 58 pm](https://cloud.githubusercontent.com/assets/12703638/25822169/9c5b6dbe-33ec-11e7-8917-e7af478d943f.png)

**Comment by sjDCC** [comment]
Either, or may both? Do people typically come back to the overview page where the done button is? If not, a prompt at export would be good too

**Comment by stephaniesimms** [comment]
@sjDCC Had a good consult w/UX about this and will update the issue for your (new) consideration.

**Comment by stephaniesimms** [comment]
@briri noting here that the default visibility setting for a new plan should be Private - currently it defaults to Institutional

**Comment by briri** [comment]
related to #417. Whoever works on the share tab and export tabs should also handle this ticket

**Comment by briri** [comment]
closing because this has morphed into the plan share/export revisions
