### ISSUE TITLE
can you create a plan from a publicly visible template when not logged in?

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#2804]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

`3.0.1`

**What happens:**

When you access the page `/public_templates`,
it not only lists the public templates from which you
can create a new plan in one click, it always shows
a "create plan" link. But that link cannot work if
you are not logged in. Better remove it if not logged in?

**Comment by briri** [comment]
Yes, good catch @nicolasfranck!

I think a check with the `user_signed_in?` Devise helper method should work here. If you have a chance can you submit a PR? We hope to create a new release over the next few weeks and it would be good to include this patch. Thank you!
