### ISSUE TITLE
`bin/setup` fails on fresh install

### ISSUE THREAD

**Issue by yjarosz** [DMPRoadmap/roadmap#2805]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
"master"

**Expected behaviour:**
"bin/setup" exit without failure

**Actual behaviour:**

```
root@86eda16fbefa:/srv/roadmap# bin/setup

[....] removed working installation steps

Post-install message from httparty:
When you HTTParty, you must party hard!

== Copying sample files ==
Traceback (most recent call last):
	5: from bin/setup:12:in `<main>'
	4: from /usr/local/lib/ruby/2.7.0/fileutils.rb:139:in `cd'
	3: from /usr/local/lib/ruby/2.7.0/fileutils.rb:139:in `chdir'
	2: from bin/setup:24:in `block in <main>'
	1: from bin/setup:24:in `each'
bin/setup:25:in `block (2 levels) in <main>': undefined local variable or method `new_file' for main:Object (NameError)
```

**Steps to reproduce:**
Fresh install, git clone and `bin/setup` as per the installation docs.

**How to fix**

Replacing l.25 in `bin/setup` by `new_file = file.gsub('.sample', '').gsub('.example', '')` worked for me.

**Comment by yjarosz** [comment]
Not sure if I should open a PR for that :)

**Comment by briri** [comment]
Hi @yjarosz. Thanks for reporting this. Yes, a PR would be great! 

Please submit one to the `development` branch. We will be creating a new release from the changes there over the next two weeks and it would be good to include this fix :)
