### ISSUE TITLE
gettext gem

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#281]
Add `gettext` gem which lets us run 
```ruby
rake gettext:find
```
This is going to be essential to keep code in sync with translation (portal) efforts.

**Comment by jollopre** [comment]
This command permits finding any translation conforming to _('any message'). 
It automatically marks with #, fuzzy any string that is suspicious of being translated correctly. In addition, automatically removes entries from .pot and .po files that no longer appear in code.

**Comment by vyruss** [comment]
Works OK. No UI components so no UAT, closing.
