### ISSUE TITLE
Add a related identifiers field to project details page

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2815]
Following feedback from the FAIR Island Project testing, we need to add a new "Related Identifiers" field to the project details tab. This will allow users to connect specific outputs to the record and gives us another route to connect planned outputs to their completed/published versions

- this should apply to all different output types
- will require a tool tip to define the field 
- we will need talk w/ DataCite about how we can make assertions to the identifiers included here

**Comment by mariapraetzellis** [comment]
@mariapraetzellis need to add tooltip text and ideas for additional related work types
<img width="338" alt="Screen Shot 2021-09-15 at 11 27 00 AM" src="https://user-images.githubusercontent.com/27511575/133489427-13857f43-3db6-46dd-84e8-8cf3b776e362.png">

**Comment by mariapraetzellis** [comment]
There should be an option to include related works on the project details page for a downloaded PDF of the plan.

**Comment by mariapraetzellis** [comment]
In production and working well!

**Comment by dsisu** [comment]
@mariapraetzellis @briri , we are in principle happy with implementing this but we need to look at implementing Research Outputs first. One issue we can spot now is 'too many identifiers' on the project details page.

**Comment by pengyin-shan** [comment]
sorry for the late input...Is the 'Related Identifiers' the exact word on UI? Any explanation of it?
