### ISSUE TITLE
All DMPs have the same edited date

### ISSUE THREAD

**Issue by icvandijk** [DMPRoadmap/roadmap#2819]
After the update on 19-02-2021, all DMPs have the same edited date (19-02-2021). This makes it impossible for our research support staff to easily find the most recent DMPs.

**Comment by pherterich** [comment]
Thanks for the report @icvandijk - we are aware that this is an issue in DMPonline only and we have tracked that in our private to do list https://github.com/DigitalCurationCentre/DMPonline-Service/issues/442 to be addressed soon.

**Comment by pherterich** [comment]
This is now fixed on DMPonline
