### ISSUE TITLE
Cannot delete selections on Edit Profile page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#284]
When I click the "x" in the dropdowns for Org and Language nothing happens. Expected behavior is that it should delete my selection. In addition, the dropdown list for 'Organisation' should contain an option for No Org.

![screen shot 2017-05-01 at 9 45 54 am](https://cloud.githubusercontent.com/assets/12703638/25586316/a4bfbc10-2e53-11e7-9454-994c19e0ccc1.png)

**Comment by vyruss** [comment]
This will be fixed by #124

**Comment by stephaniesimms** [comment]
@vyruss Not completely. The jquery selector is only needed for long lists (say more than a dozen options). So we should use if for the Organisation dropdown but it's not necessary for Language. And the Org list needs an option for "No Organisation." Also Language defaults to Deutsch, but it should be English (GB). I'll create a separate issue for that.

You can ping @briri to see how he implemented the new jquery selector.

**Comment by vyruss** [comment]
Thanks. Waiting for #230 PR

**Comment by dsisu** [comment]
I don't know whether I should raise this here but when it comes to shibboleth, I think the message 'Your account is linked to your institutional credentials. Unlink your institutional credentials' is clearer than 'Your account has been linked to UK Access Federation.'

**Comment by vyruss** [comment]
@dsisu this issue is unrelated

**Comment by sjDCC** [comment]
It is unrelated to this ticket but still important. Can you change the text back please @vyruss? I had the same thought as @dsisu but hadn't had chance to raise a ticket. People are familiar with the term institutional credentials.

Otherwise this all works. Closing out
