### ISSUE TITLE
mimemagic (0.3.5) has been yanked from rubygems.org

### ISSUE THREAD

**Issue by yjarosz** [DMPRoadmap/roadmap#2842]
`bundle install` does not finish installation correctly.

```
RUN cd roadmap && gem install bundler --conservative && bundle install:
#14 10.40 Fetching gem metadata from https://rubygems.org/.......
#14 15.74 Your bundle is locked to mimemagic (0.3.5), but that version could not be found
#14 15.74 in any of the sources listed in your Gemfile. If you haven't changed sources,
#14 15.74 that means the author of mimemagic (0.3.5) has removed it. You'll need to update
#14 15.74 your bundle to a version other than mimemagic (0.3.5) that hasn't been removed
#14 15.74 in order to install.
```

The version used in `Gemfile.lock` has been yanked couple of days ago: [see here](https://rubygems.org/gems/mimemagic/versions)

I have updated My `Gemfile.lock` file from

```
  mimemagic (0.3.5)
``` 

to 

```
    mimemagic (0.4.2)
      nokogiri (~> 1)
      rake (>= 0)
```

and the `bundle install` is finishing correctly, but I am not sure that if would not cause any other issues down the road.

Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
master

**Expected behaviour:**
 gem install bundler finish without errors

**Actual behaviour:**
 gem install bundler finish with errors

**Steps to reproduce:**
Fresh install

**Comment by briri** [comment]
Thanks for reporting this @yjarosz 

https://www.theregister.com/2021/03/25/ruby_rails_code/

It looks like the mimemagic team released some temporary updates late Thursday to address an issue with their gem, and the Rails team is working on a longer-term fix.

For now, on most Linux systems, you can simply `bundle update mimemagic`
But on OSX, you will need to first run (assuming you use brew to manage dependencies): `brew install shared-mime-info`
