### ISSUE TITLE
Suggestion to add RTF output 

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2853]
We received a suggestion from a user - could we add an output in an RTF or word format as well as PDF?

**Comment by pherterich** [comment]
Any opinions on adding RTF or should we just close this issue? @raycarrick-ed @mariapraetzellis

**Comment by raycarrick-ed** [comment]
I think given we offer Word, I'd close this until more than one person asks for RTF
