### ISSUE TITLE
User should not be able to share a plan with him/herself

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#286]
I accidentally invited myself to collaborate on a plan (same user account) and was able to do so. Now I receive two email notices for every action taken on the plan. I cannot remove myself (this is working as expected, but I should not be able to invite myself in the first place). In addition, I have two copies of the same plan on My Plans page (second screenshot).

![auto-share](https://cloud.githubusercontent.com/assets/12703638/25588829/dbd024a0-2e5e-11e7-8898-89cfae4d0ec5.png)

![2-plans](https://cloud.githubusercontent.com/assets/12703638/25594488/a918d3b0-2e75-11e7-9e33-80df2b15bd0e.png)

**Comment by stephaniesimms** [comment]
Working as expected. Closing issue.

**Comment by stephaniesimms** [comment]
accidentally closed

**Comment by jollopre** [comment]
The message provided when user tries to share plan with (him|her)self is:

> Impossible sharing plan with someonw@somewhere.com since that email matches with the owner of the plan

**Comment by stephaniesimms** [comment]
on Roadmap stage I just shared another plan with myself (screenshot below)

![screen shot 2017-05-02 at 10 32 04 am](https://cloud.githubusercontent.com/assets/12703638/25630635/a98655a4-2f22-11e7-9821-11d383bf9f57.png)

**Comment by sjDCC** [comment]
Fixed on both dmponline-test and staging. Generates correct error message
