### ISSUE TITLE
Preview button gets a 500 error when in a template

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2864]
A user reported (and I was able to reproduce) that when they're editing a template and select the Preview button they are directed to a 500 page.
![screenshot-dmptool org-2021 04 12-09_50_09](https://user-images.githubusercontent.com/27511575/114431696-a57ee300-9b74-11eb-83b1-a1852403ecb3.png)

**Comment by briri** [comment]
fixed and deployed to stage

**Comment by mariapraetzellis** [comment]
Checked and looks to be working now.
