### ISSUE TITLE
Change password not working as expected

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#287]
I received a variety of different errors and weird system behaviors each time I changed my password (screenshots below). The most frequent error is that I get kicked out of the system after clicking to 'Save' the new password (second screenshot), but when I attempt to login again my password is updated with the new one.

It looks like my new password is recorded/updated each time but nothing else works as expected. I should just receive a message that my password has been updated. @sjDCC can you confirm this and whether I should also remain signed in?

First errors had messages like this. I checked with and without entering my First and Last Name and that made no difference:
![screen shot 2017-05-01 at 11 12 50 am](https://cloud.githubusercontent.com/assets/12703638/25589077/05e66564-2e60-11e7-933f-91d02a18e978.png)

Then I got this error repeatedly and could not reproduce the above error:
![screen shot 2017-05-01 at 11 14 13 am](https://cloud.githubusercontent.com/assets/12703638/25589098/1ea1763e-2e60-11e7-9bca-35549428e10f.png)

**Comment by vyruss** [comment]
It says the translation that's missing is for "password too short" so @jollopre perhaps it's simply a missing i18n string issue?

**Comment by jollopre** [comment]
I don't think so. It seems something more complex since changing password signs you out. In addition, when signed in with the new password does not redirect to /plans.

**Comment by briri** [comment]
We removed the confirmation email requirement from Devise which could be contributing to this issue. There's a private method in the `registrations_controller` that's likely the issue. It determines what message goes out

**Comment by sjDCC** [comment]
Just to confirm, the password change should just give a confirmation message not log you out

**Comment by sjDCC** [comment]
Password now saves correctly on both DMPonline test and staging and keeps user on same 'edit profile' page. However the action of saving changes resets the language preference to German. Is this linked to #293?

Does this ticket need to be left open or a new one generated @vyruss @briri It seems #293 will be fixed as part of #230 which should be pulled in soon so maybe close this ticket for now?

**Comment by vyruss** [comment]
Yes, I'd say close it. There's​ #293 for the default Language issue.
