### ISSUE TITLE
User invite during "share" should not assign org of current_user

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#2875]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

`3.0.2`

**Expected behaviour:**

**Actual behaviour:**

The `org` of the `current_user` is attached to the new user record.
See https://github.com/DMPRoadmap/roadmap/blob/master/app/controllers/roles_controller.rb#L39
This can be problematic if that user is from outside of the organisation.

Then again, where should one supply the (required!) organisation?

**Steps to reproduce:**

* go to tab share of a plan
* enter an email address that does not yet in the user table

**Comment by briri** [comment]
When a user clicks on the link in the invitation they're able to indicate which Org they belong to. I think the User record requires an Org id. You could update it to use a default Org if its problematic for your installation
