### ISSUE TITLE
Adding red asterisk next to the organisation field since it is required field?

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2889]
@mariapraetzellis @briri 

Could we mark the organisation field with a red asterisk since it is a required field when creating an account?
It has been suggested by the user that this would be useful.

**Comment by briri** [comment]
Yes that is an easy fix. @raycarrick-ed or @martaribeiro I'm not sure which repository would be applicable here the shared DMPRoadmap/roadmap codebase has it set to be a required field already.

Here's the line in your fork. Just change `required` to `true`:
https://github.com/DigitalCurationCentre/roadmap/blob/73dde973a055dca7a5cf3526641e78d18b6f1199/app/views/shared/_create_account_form.html.erb#L19

**Comment by johnpinto1** [comment]
@pherterich As @briri as said this appears fixed in Roadmap. Also I can't see issue on Live sites e.g.,
![Selection_019](https://user-images.githubusercontent.com/8876215/133239162-80de9af4-9ca8-4a81-b766-05773dc8f912.png)
![Selection_020](https://user-images.githubusercontent.com/8876215/133239353-506eaa4f-fadd-4a7d-827d-0d2b475c42c8.png)

**Comment by magdalenadrafiova** [comment]
@johnpinto1 strange :) seems to be be deployed now - except one of our customers on their own instance. I have raised an internal ticket for that one missing client and closing this here as all seems to work well :)

**Comment by dsisu** [comment]
Initially the organisation wasn't a required field. We felt that anybody, including people in-between jobs, recent graduates, etc could use the tool. In practice, organisations are driving the requirement for DMPs and the way the tool has evolved makes it easier if we ask for an organisation of some sort. Remember we also have organisation 'Other' but it seems to be a well kept secret.
