### ISSUE TITLE
Error while trying to share a plan with an invalid email

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#289]
An undefined method is raised while trying to save a new role for an invalid user.

See snapshot:
![snapshot](https://cloud.githubusercontent.com/assets/7393044/25624418/39361ce2-2f51-11e7-80e2-bcdad2b28fbb.png)

**Comment by vyruss** [comment]
Broken by 7357cc46b61623d2b86c91e1dd019ed9179c65a6 - fixed.

**Comment by sjDCC** [comment]
@vyruss can you clarify what I need to test here. By an "invalid user" does @jollopre mean that an incorrect email address was submitted into the share plan email field? e.g. sarah.jones@glasgow.uk?

**Comment by vyruss** [comment]
@sjDCC something which cannot be an email address, such as "gibber.ish"

**Comment by stephaniesimms** [comment]
Testing on roadmap-stage I could not reproduce the error message you got @sjDCC . The only requirement seems to be that you include an "@" (see screenshot below). As long as that is met you can successfully invite any bogus address. If it's straightforward to prevent this we should fix it, but if not I don't think it poses a major problem. I can always remove the user if I mistype, etc.

![screen shot 2017-05-16 at 10 16 56 am](https://cloud.githubusercontent.com/assets/12703638/26119236/6e0c5a3c-3a21-11e7-8e79-a19588b99d31.png)

**Comment by briri** [comment]
Some of the error messaging that you're seeing could be tied to the particular browser you're using. We're using the HTML 5 email field type and unfortunately not every browser handles them in the same way.

**Comment by sjDCC** [comment]
I suspect it may be hard to ensure the email is valid so think it's fine as is now. I get the same error message as Steph and think it looks good. Suggest closing out
