### ISSUE TITLE
RAILS_RELATIVE_URL_ROOT not always taken into account

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#2897]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

`3.0.2`

**Expected behaviour:**

Routes should use the prefix from the environment variable `RAILS_RELATIVE_URL_ROOT`

**Actual behaviour:**

the prefix from the environment variable `RAILS_RELATIVE_URL_ROOT` is only used in some
cases:

* asset paths
* omniauth paths

**Steps to reproduce:**

* `export RAILS_RELATIVE_URL_ROOT=/roadmap`
* setup a proxy pass in  apache: `ProxyPass /roadmap http://localhost:3000/`
* go to `http://localhost/roadmap`

**Comment by nicolasfranck** [comment]
This seems to do the trick (`config.ru`):

```
-run DMPRoadmap::Application
+map ENV['RAILS_RELATIVE_URL_ROOT'] || "/" do
+  run DMPRoadmap::Application
+end
```

You'll have to recompile your assets  with the environment variable set.

**Comment by briri** [comment]
this seems very dependent on a specific method for deploying and managing your instance of the application. 

what is the specific use case?

**Comment by nicolasfranck** [comment]
is it uncommon to deploy a rails application to a subdirectory ;-)?
