### ISSUE TITLE
Can't create new user account

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#290]
I tried to register for Roadmap stage as I can't login currently. This threw an error - see below.
![capture](https://cloud.githubusercontent.com/assets/6169940/25624428/41f5e452-2f51-11e7-8459-f7be72c24aca.PNG)

A similar issue exists in DMPonline. See screengrab 
![capture2](https://cloud.githubusercontent.com/assets/6169940/25624433/4708e8b8-2f51-11e7-9b8f-0342c919cdde.PNG)

**Comment by sjDCC** [comment]
This is not fixed on roadmap staging. I get this error
![capture](https://cloud.githubusercontent.com/assets/6169940/26006111/2da07e10-3733-11e7-99a0-a8c2732cb2e9.PNG)

@stephaniesimms can you test out on dmponline-test? I've used up all email accounts I have already ;-)

**Comment by stephaniesimms** [comment]
@sjDCC I just tested both roadmap stage and dmponline-test with no errors creating new accounts. I used the Sign Up route w/no Shib pathways. It worked with and without choosing a org. Although I did get an error message about an invalid email address that is in fact valid (screenshot below)

![screen shot 2017-05-10 at 8 35 07 am](https://cloud.githubusercontent.com/assets/12703638/26006607/e72a7116-36f1-11e7-9949-f6de352a70de.png)

**Comment by sjDCC** [comment]
Ok, have re-tried and managed to create an account without error. I suspect the fault was that I tried to register a new account with an email address I had shared a plan with and not validated or followed up. When I checked the backend there was a stem account for s.jones@arts that is showing to have not accepted terms yet.

@stephaniesimms Could you maybe try to replicate that and see if you get the same error? If not, I'm happy to close out. It could just be something random that was wrong with my email in the system as we're trialling it so much?

**Comment by stephaniesimms** [comment]
@sjDCC let me try to reproduce the error before closing. because we def don't want users to get this ugly error message.

**Comment by stephaniesimms** [comment]
@sjDCC I confirmed your suspicions by testing on Roadmap-stage. I invited a user to co-author a plan. Then I tried to create a new account for that user (instead of accepting the email invitation) and received the error below. This is a bug - somehow we need to allow the user to follow either path to create an account. 

![screen shot 2017-05-16 at 9 44 11 am](https://cloud.githubusercontent.com/assets/12703638/26117774/6d285666-3a1c-11e7-9305-7e49aa655152.png)

**Comment by sjDCC** [comment]
@vyruss do you want to pull this back to pending or start a new ticket? We definitely need a better fix than that error page when someone who has an unvalidated stem account tries to sign up. 

At minimum we need an error message to say their email address is already taken, but if they don't have the email invite to follow the relevant link they're stuck, so a better workflow / solution is needed. Ideally allow them to just set a password for the unvalidated account?

**Comment by vyruss** [comment]
Can you close this and describe the issue in another ticket please?

**Comment by sjDCC** [comment]
Done. See ticket #322
