### ISSUE TITLE
Co-owners shouldn't be able to adjust their own rights

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#291]
People given co-owner access to a plan shouldn't be able to adjust their own rights. They could easily reduce own rights (e.g. to read-only) and then not be able to reset. 

In the screengrab below, my s.jones account should show as greyed out (like the original owner - sarah.jones@glasgow).
![co-owners-edit-rights](https://cloud.githubusercontent.com/assets/6169940/25661574/20ef4c90-3009-11e7-8882-2c9279fe44ad.PNG)

This picks up on issue raised by @stephaniesimms in ticket #220

**Comment by stephaniesimms** [comment]
This is working as expected now on roadmap-dev.

**Comment by stephaniesimms** [comment]
Retested on dev and stage and all works as expected for plan sharing functions. Closing issue.
