### ISSUE TITLE
Add new field for Funding Status

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2920]
We need a field that tracks the status of funding. 

- We can put this in the Project Details page
-  titled "Funding Status" 
- with the drop down options of: Granted, Planned, Rejected

**Comment by briri** [comment]
Run through user group to see what to name/call the values perhaps "not funded" instead of "rejected"

**Comment by raycarrick-ed** [comment]
see

https://github.com/DMPRoadmap/roadmap/issues/2922

which suggests the funding status may be more complex
