### ISSUE TITLE
Failure to catch empty email on share plan

### ISSUE THREAD

**Issue by raycarrick-ed** [DMPRoadmap/roadmap#2923]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
v3

**Expected behaviour:**
if someone shares a plan and does not enter an email address they should get an error

**Actual behaviour:**
falls over with 
NoMethodError (undefined method `email' for nil:NilClass):
 app/controllers/roles_controller.rb:47:in `create'

**Steps to reproduce:**
don't put in an email address on the share plan page and hit submit

**Comment by briri** [comment]
Probably related to PR #2874 which was an attempt to require the email address.

**Comment by briri** [comment]
think this is fixed. At least the controller has a nil check now
