### ISSUE TITLE
Language should default to English in Edit Profile

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#293]
At present the Language dropdown on the Edit Profile page defaults to Deutsch (the first in the alphabetical list) on first login. It should default to English (GB). Also, clicking on the "x" in the dropdown should delete the selection and/or the "x" should be removed.

![screen shot 2017-05-05 at 1 50 06 pm](https://cloud.githubusercontent.com/assets/12703638/25763936/5ba07318-319a-11e7-8972-5ad7f329b12d.png)
.

**Comment by briri** [comment]
fixing as part of #230

**Comment by briri** [comment]
Fix will be pulled in with new create plan workflow because it relies on jquery accessible dropdown

**Comment by sjDCC** [comment]
Working on staging and DMPonline-test. There's no longer an 'x' by the language choice as it's a proper dropdown but the x against organisation clears the choice. Closing out
