### ISSUE TITLE
Update role permissions after deactivation of role creates confusion

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#2951]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

`2.0.3`

**Expected behaviour:**

If a user "removes" a plan, the plan isn't really removed.
Merely the associated "role" is internally flagged as "active=false".

The user no longer has access to the plan, but..

..other users that still have access still see this "role" in the share tab,
and they have no way of knowing that the role has been deactivated.
So they may alter the permissions, and unintentionally send
notifications to a user that lost interest?

Not sure about this

**Comment by briri** [comment]
Good catch @nicolasfranck. We should update that query to to only include active roles

**Comment by nicolasfranck** [comment]
and make sure that `RolesController#create` reuses the old deactivated `Role` record?
Otherwise an insert would fail

**Comment by briri** [comment]
@nicolasfranck would this be something you have the time to patch?

**Comment by nicolasfranck** [comment]
Some points:

* Apparently user uniqueness is not enforced on model level (Role), only in the `RolesController`. This controller skips `Plan#add_user!` altogether.
* [Plan#add_user(user_id, access_type = :commenter)](https://github.com/DMPRoadmap/roadmap/blob/master/app/models/plan.rb#L445) already reuses the old role, but does not activate it. Add this? Otherwise the reused role would not be visible. Although I do not see any places where this could happen, as this method is only used during  creation of plans in `PlansController#create` and `PlansController#duplicate`

**Comment by nicolasfranck** [comment]
Similar question: it is not allowed to delete yourself in the share tab,
but you are allowed to deactivate your role using the link "remove",
which has basically the same effect. Intended?

**Comment by nicolasfranck** [comment]
What is actually for using inactive roles in the first place? History?

**Comment by briri** [comment]
Yes, history and an edge-case scenario:

User A creates a plan and so becomes the 'owner' of the plan (creates the initial role record).
User A then invites user B to work on the plan as a 'co-owner' / 'administrator' (creates a role record)
User B invites user C to work on the plan as an 'editor' (creates a role record)
User A decides that the plan is 'complete' and makes its visibility public
After a year, user A decides to 'remove' the plan because they are tired of seeing it (deactivates the role)
User B also decides to do the same (deactivates the role)

Someone tries to download/view the public version of the plan.

When the plan is viewed/downloaded it needs to provide the Owner's info. If we delete the role records we cannot find that information.

**Comment by nicolasfranck** [comment]
Mm, but the public plan export uses the same code as the internal plan export, and that only takes active roles into account. See for example [Plan#owner](https://github.com/DMPRoadmap/roadmap/blob/master/app/models/plan.rb#L435) and [Plan#owner_and_coowners](https://github.com/DMPRoadmap/roadmap/blob/master/app/models/plan.rb#L435). Am I missing something?

**Comment by briri** [comment]
correct, but there are places though where code like `plan.owner.name` and `plan.owner.org` are used and the nil causes errors. It also makes it impossible from a maDMP standpoint to determine the author of the DMP once everyone has been removed.

**Comment by nicolasfranck** [comment]
> correct, but there are places though where code like `plan.owner.name` and `plan.owner.org` are used and the nil causes errors. It also makes it impossible from a maDMP standpoint to determine the author of the DMP once everyone has been removed.

`plan.owner.name` uses a filter on attribute `active` (see my link above), so it is already nil..

**Comment by briri** [comment]
if you feel this is an issue, have bandwidth and would like to patch it then please do so. It is not something that we will have time to address in the near future
