### ISSUE TITLE
Download option "unanswered questions" does opposite

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#2958]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

`3.0.2`

**Expected behaviour:**

On the download page of a plan, if you uncheck the box "unanswered questions",
these questions shouldn't be included

**Actual behaviour:**

The questions are still included. The only difference is that the text below
the questions is now empty, and there is no "Question not answered" anymore.

**Comment by nicolasfranck** [comment]
Maybe the label text is wrong and it should read "leave empty answers empty"?
That is the way it is treated now. BTW why would anyone want to download
the results of the questionnaire if it not completed yet?

**Comment by briri** [comment]
Some researchers just download the empty plan as a DOCX and then write their DMP outside the interface.

**Comment by johnpinto1** [comment]
@johnpinto1 Working on this now.
