### ISSUE TITLE
Export bug on H2020 template due to invalid html

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#297]
Plan written with the H2020 template won't export due to html in the question area. This is particularly on phase 1. See discussion and notes in ticket #217

**Comment by jollopre** [comment]
The current gem for exporting to docx does not support strong tag as ancestor of li tag when converting from html to docx (see https://github.com/karnov/htmltoword/blob/master/lib/htmltoword/xslt/base.xslt#L184).

This fix takes into account this limitation, however any question text exported to .docx no longer has its text bold.

**Comment by sjDCC** [comment]
Exports fine now. Closing out
