### ISSUE TITLE
Not possible to add funder once the creation plan wizard page is completed

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2980]
It would be expected that when I first select that I have no funder, but then realise that I have might made a mistake and go back to the plan and edit the 'project details' page and add the funder it will appear here. 

However it is not possible to get the drop down menu and even when i type the funder and hit save it remains empty, see below

<img width="912" alt="Screenshot 2021-07-26 at 15 30 50" src="https://user-images.githubusercontent.com/47178106/127006698-1ec72a44-2d02-413c-b166-2ec472704233.png">

@mariapraetzellis @briri could you check whether this is an issue on your end too?

**Comment by briri** [comment]
This is working for us on our end.

**Comment by magdalenadrafiova** [comment]
@briri thank you! closing here @raycarrick and opened internal ticket 584
