### ISSUE TITLE
possible to add contributor without a name - even though it appears as compulsory field

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#2983]
@raycarrick @briri 
I am testing on DMPonline-dev the latest 3.3 release. Not sure 
The contributor name appears as compulsory field but when I left it empty it was alright to save: 
<img width="989" alt="Screenshot 2021-07-28 at 14 53 06" src="https://user-images.githubusercontent.com/47178106/127334418-123747a1-8956-48e2-b9fa-f57bd2a58579.png">

See contributor without a name: 
<img width="1009" alt="Screenshot 2021-07-28 at 14 53 42" src="https://user-images.githubusercontent.com/47178106/127334501-95de505f-ee37-4922-bf9e-94a602975c31.png">

**Comment by briri** [comment]
The logic in the code requires one or the other (name or email). Should we actually require both or is one more important?

Whoever addresses this ticket should also remove the phone number per #2941

**Comment by johnpinto1** [comment]
Will look at https://github.com/DMPRoadmap/roadmap/issues/2941 next. Have a PR see above.

**Comment by magdalenadrafiova** [comment]
@johnpinto1 both still appears as compulsory fields on dev follow up with @dsisu once fixed so she can re-test and close 
<img width="853" alt="Screenshot 2022-03-01 at 14 54 45" src="https://user-images.githubusercontent.com/47178106/156191897-e07bdbfb-63d1-4b47-8f3d-1467224d4fb5.png">

**Comment by johnpinto1** [comment]
The view is displaying wrong info. The code saves either name or email, but view shows incorrectly that both name and email are required.

**Comment by johnpinto1** [comment]
Trivial fix done and PR created https://github.com/DMPRoadmap/roadmap/pull/3120
![Selection_058](https://user-images.githubusercontent.com/8876215/156759056-e8cb2eef-6367-4af7-9271-290fb374c8c9.png)

**Comment by pherterich** [comment]
Just catching up with things as part of trying to understand what the latest release covered: how is it obvious to a user in this new version that either name or email needs to be provided? Do we provide a meaningful error message if it isn't? Should we add a sentence saying that one of the two fields needs to be filled?

**Comment by raycarrick-ed** [comment]
This is a good point. @johnpinto how easy would it be to add a message to that effect? Fill in at least one of these fields?

**Comment by johnpinto1** [comment]
@raycarrick-ed & @pherterich It should be trivial. Famous last words. Its just adding an text.

**Comment by pherterich** [comment]
"Please provide either Name or Email in addition to the fields indicated as mandatory using *"

Other suggestions on how to phrase this @dsisu @mariapraetzellis ?

**Comment by dsisu** [comment]
If the logic makes this easy to implement, I would say make both name and email address fields mandatory (and marked as such). 

From the users' perspective, as readers, it looks much better if all contributors are named. The email address can be very different from the name and give no obvious indication who the contributor is. 

From the user's perspective as the form-filler (the author of the plan), it's not a lot of information to ask of them. They must have spoken to their contributors so they will probably have their name and email address close to hand.

If we don't make both fields mandatory, then we Patricia's suggested wording is fine.

**Comment by johnpinto1** [comment]
@dsisu CDL requires either name and email address fields , so it would be better to not require both mandatory.
