### ISSUE TITLE
Flag for featured public DMPs

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2988]
The DMPTool is building a new Public Plans page that will facilitate faceted search on publicly available plans. New searches include research organization, funder, area of study, and language. As part of this, we will be sorting search results so that "Featured" plans rise to the top. This will allow us to surface exemplars and give users quick access to curated plans. Wireframes of this new page are available here:https://qvr42y.axshare.com/#id=9p2b3e&p=explore__public_dmps_cards_scroll-box&fn=0&dp=0&c=1

To allow for the "Featured plans" tool, we need to add a flag on plans so that admins can tag them as Featured. This should be available to all organizational administrators.

**Comment by mariapraetzellis** [comment]
- This should also be for org admins
- This flag should be set on the Plans table as a column that an admin can toggle on/off. We do this currently on My Dashboard for the Test column

**Comment by raycarrick-ed** [comment]
It would be great if, in doing this work, it was made easy for us to restrict the result to a given org. It's something we need to do for the MT. If we could build in something like a "restrict_to_org" variable that by default was nil and did nothing but if set would only show plans for that org then that would allow us to get the MT codebase one step closer roadmap which would be great. Happy to discuss.
