### ISSUE TITLE
partial shared/accessible_combobox referred to, but removed

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#2993]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

`3.0.2` or `3.0.3` (in both)

**What happens:**

If you open the url http://localhost:3000/orgs/shibboleth,
it crashes:

```
Missing partial shared/_accessible_combobox with {:locale=>[:"en-GB"], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder, :haml]}
````

Seems to be removed since https://github.com/DMPRoadmap/roadmap/commit/64ef2794e779dda2a347fa7fd4c278ae030c4f2f

**Comment by briri** [comment]
Part of some cleanup work I'll be doing on the sign in / create account workflows

**Comment by briri** [comment]
I just did a scan of the current release and do not see this partial referenced anywhere so am closing.
