### ISSUE TITLE
log level too high in production environment

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#3004]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

`3.0.3`

**Expected behaviour:**

Log level should be configurable

**Actual behaviour:**

Log level is statically set to `:debug`

**Steps to reproduce:**

See [config.log_level = :debug](https://github.com/DMPRoadmap/roadmap/blob/master/config/environments/production.rb#L56)

**Comment by briri** [comment]
agreed, this should be configurable either by an env variable or we should switch the different environment files to be:
- development: `:debug`
- production: `:info`
