### ISSUE TITLE
app.mo for 'tr-TR' is not generated in source tree from /config/locales.

### ISSUE THREAD

**Issue by hbayindir** [DMPRoadmap/roadmap#3007]
Hello,

We have been working on installing, translating and adapting DMPRoadmap for our organization, and everything's going pretty well so far. With help, we've setup a translation pipeline and translated DMPRoadmap to Turkish (thanks Brian for first reply, and accommodating on-boarding, that's greatly appreciated).

We've completed most of the translation and it seems that `/config/locales` tree has been synced with the translations pretty well, but the `config/locale/tr_TR` has not been caught up with the changes. `app.mo` file is pretty bare.

What we can do to compile the assets ourselves, and generate the `app.mo` file, or do we need to do anything further for cooperation?

Thanks a lot & regards.

**Comment by raycarrick-ed** [comment]
should be fixed in:
https://github.com/DMPRoadmap/roadmap/pull/3008

**Comment by briri** [comment]
@hbayindir this has been merged into the `master` branch. Be sure to do a pull down to your local.

**Comment by hbayindir** [comment]
@briri Just did, thanks for the heads up!

**Comment by hbayindir** [comment]
I've just pulled the translations in and changed the default language. Everything is working as it should.

Thanks again. Closing this ticket since everything is as it should be.
