### ISSUE TITLE
Investigate actions that make the browser flicker

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#301]
When I Share Note and click Save, the browser flickers a few times (just something to note, not a fatal flaw)

When I advance to answering questions in a new section w/o saving and click through the modal that prompts me to Save previous answers, I observe the same browser flickering

**Comment by briri** [comment]
@stephaniesimms is this still an issue with now that we have redesigned the page?

**Comment by stephaniesimms** [comment]
nope. not that i've noticed in the past few weeks of testing at least. if you don't see flickering either it's probably safe to close @briri

**Comment by sjDCC** [comment]
Haven't noticed any flickering either. Closing out
