### ISSUE TITLE
Issues searching through plan tables

### ISSUE THREAD

**Issue by pherterich** [DMPRoadmap/roadmap#3012]
Coming out of search hick-ups reported for DMPonline (https://github.com/DigitalCurationCentre/DMPonline-Service/issues/496), this has now been mainly covered by #3000

**Comment by johnpinto1** [comment]
Will look at this next.

**Comment by johnpinto1** [comment]
The code for OR https://github.com/DigitalCurationCentre/roadmap-extension/pull/218 has not been merged yet by @raycarrick-ed. Hopefully that Roadmap-extension changes sort issue. Will double check after the merge and deployment to DEV.
