### ISSUE TITLE
Questions w/ radio buttons do not allow user to Save answer

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#302]
For the radio button question on NIH template I cannot save my answer. Nothing happens when I click Save (no timestamp save confirmation) and when I navigate away from the page and return my selection is not saved.

![screen shot 2017-05-10 at 8 35 07 am](https://cloud.githubusercontent.com/assets/12703638/25907287/e1d777dc-355b-11e7-8ae1-87ecb0ae69ff.png)

**Comment by jollopre** [comment]
The commit pushed only fixes the problem for those users that are owner or have edit privileges into a plan that includes radio button. For read only users in a plan, see #352

**Comment by sjDCC** [comment]
You can save answers now, but the recorded values don't appear to be sticking. See issue noted in #355

**Comment by jollopre** [comment]
Fixed as part of the work done in #355

**Comment by sjDCC** [comment]
This is working. Closing out
