### ISSUE TITLE
Revise UX wireframe for email notifications

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#304]
http://h90c3m.axshare.com/#g=1&p=profile__first_login
@JEK-III Please revise wireframe above to reflect the following list of notifications (related issue #146 ):

**All users**
- [ ] New permissions granted to me
- [ ] A new comment has been added to my DMP

**DMP authors and co-owners**
- [ ] My DMP's visibility has changed
- [ ] I have been made co-owner of a DMP

**DMP administrators**
- [ ] An organisational template is published
- [ ] An organisational template is unpublished

**Comment by briri** [comment]
what does 'activated' mean?

**Comment by JEK-III** [comment]
I'm guessing activated=published– if so, we should definitely align that language.

**Comment by stephaniesimms** [comment]
that would be me confusing DMPTool speak with the new system. I edited the original issue description accordingly (above).

**Comment by stephaniesimms** [comment]
wireframes look good. thanks @JEK-III . closing
