### ISSUE TITLE
Step 1: Create account and sign in changes

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#305]
UX wireframes @JEK-III : http://h90c3m.axshare.com/#g=1&p=home

Replace "Sign Up" with "Create Account"
No ORCID sign in support for MVP (this is a future enhancement unless it requires no additional work to implement now)

Select Organisation page: http://h90c3m.axshare.com/#g=1&p=select_partner_institution
Blue notepad contains functional specs. Use jquery selector for DMPTool and DMPonline lists.

Once a user selects their Org they are directed to Shib login page (if configured for their Org) or generic sign in page as in DMPTool

**Comment by vyruss** [comment]
To enable ORCID login, it only requires a new link in `app/views/shared/_login_form.html.erb` and a couple of lines to be commented out in `users/omniauth_callbacks_controller.rb` & `test/functional/users/omniauth_callbacks_controller_test.rb`.

**Comment by briri** [comment]
@JEK-III this has been deployed out on roadmap-dev.cdlib.org. Please review and let me know if you have any changes. 
I'm not thrilled with the look of the JS error messaging. We will be converting them to this standardized approach though as we update pages. That means we can make a decision on how they should appear and only need to make the change in one spot.

FYI. I am still working on the Shibboleth org selection page and the modal version of the login/register forms is not properly executing client side JS.

**Comment by stephaniesimms** [comment]
this is looking great, except i think we need to make the "Sign in" button turn orange as soon as a user begins typing in the password field (not after they tab off as it is now)

![screen shot 2017-06-05 at 1 50 44 pm](https://cloud.githubusercontent.com/assets/12703638/26802642/19fe50d2-49f6-11e7-8124-cc0af689f626.png)

**Comment by briri** [comment]
Ok. I updated the fields so that the submit button will be enabled as the user types (assuming the input is valid). The modal/dialog versions of the forms are also working.

I'll start working on the new custom Shib discovery page tomorrow

**Comment by briri** [comment]
I've created a separate ticket for the Shib discovery page

**Comment by JEK-III** [comment]
I agree that this looks great!

I have a few visual recommendations:
* The "Your Organization" button is fixed-width and right-aligned, while the email and password fields scale with the browser window. This gets weird well within the range of browser widths that you might see on the desktop. (see below) I don't think it's a big deal whether the button scales or is fixed-width, but it should be narrower and centered.
![dmproadmap - dev 1](https://user-images.githubusercontent.com/6305223/26893811-56c4f7d8-4b71-11e7-82c3-60d6f4a9248a.png)
* I also notice that the footer isn't getting pushed far enough down the page to be out of the way of the sign-in box.
* The "remember email" and "show password" checkbox labels hang a little bit past the email and password entry fields. It would feel tidier if they were precisely right-aligned with the input fields.
* There is a little too much whitespace at the bottom of the panel. (maybe half as much would do)

A couple of accessibility issues:
* All of the sign in and create account form field labels seem to be doubled-up. WAVE picks it up as an error, and VoiceOver reads, e.g., "emailemailemail" when I tab to that field.
* The Sign In and Create Account tabs are read as links, which is not really how they function. There are a set of ARIA roles (tablist, tabpanel, etc) that _should_ take care of that, but

**Comment by briri** [comment]
ok thanks @JEK-III I'll make the adjustments.

**Comment by briri** [comment]
@JEK-III I've updated the styling and accessibility of the tabs. Please review them and let me know if all looks good now.

I'm not sure how to handle the weird doubled/tripled reading of the labels. I suspect there might be an issue with the way Rails names forms and input fields. Both the sign in and create account forms have an id of 'new_user' and each has a 'user_email' and 'user_password'. Can you verify that the first name, last name and recovery emails on the create account page only read the label once?

**Comment by stephaniesimms** [comment]
For consistency and because users are familiar w/the concept of institutional credentials, please change "Sign in with your Organisation" to "Sign in with Your Institution"

The rest looks excellent @briri!

**Comment by stephaniesimms** [comment]
I'm going to note this here and in related issue #424 (General layout/styling issues). Another place where message placement in the upper right doesn't jive w/overall page layout:

![screen shot 2017-06-19 at 12 58 04 pm](https://user-images.githubusercontent.com/12703638/27303305-3e2bf244-54ef-11e7-9035-1b629e6ad479.png)

**Comment by sjDCC** [comment]
I'm happy with the two tab look here and think UK users will like having a more prominent institutional sign in. @vyruss we'll need to run through a few use cases before deploying this. My concern is what happens when people who have an existing account but haven't linked this to shib, use this new button. It's much more inviting so I think that will happen. If the process creates a new account, we need to intervene to check they don't have one already. Can we do this by getting email from UK Access Federation and cross-checking with our database.

Other thing I noticed is that we've lost the organisational field under 'create account' completely now. We don't force people down the SSO route so want to capture it in other tab too.

The sign on workflow is something we can do consultation on with UK users

**Comment by vyruss** [comment]
@sjDCC user email is not being shared by UK AF. With the currently deployed code on DMPonline if they attempt login via (unlinked) shibboleth credentials they get the text saying - if you have an account do this, if you don't have an account, create one now

**Comment by briri** [comment]
We need to keep what we have for the moment. Just need to clean up the look/feel of the organization dropdown (use the autocomplete box from the create plan page) and other_org textbox

**Comment by vyruss** [comment]
Adding what was discussed on Tue 11/7 during meeting:

When user clicks on "Sign in w/ Shib/orcid" :
- Their credentials are known to _dmproadmap_ -> They're logged right in
- Their credentials are not recognised -> They get a screen split down the middle where they are asked a clear question and have 2 choices (exact wording can be decided on later):
    - Do you already have an account with _dmproadmap_? Sign in using your email to link these credentials
    - If you do not have an account with us, please fill in your name & email to create an account and link it to these credentials 

![image](https://user-images.githubusercontent.com/18707439/28219391-b9b4b64e-68b3-11e7-88fa-7c14911346b1.png)

**Comment by vyruss** [comment]
Currently implementing above generalised flowchart, here's a quick preview:

![image](https://user-images.githubusercontent.com/18707439/35284412-a6a73270-0052-11e8-9875-1881ae6af88a.png)

**Comment by sjDCC** [comment]
This page popups up for me. It threw the correct error when I tried to create an account with an existing known email and linked properly when I logged into existing account.
![capture](https://user-images.githubusercontent.com/6169940/36609081-add766d0-18c3-11e8-8f0e-af10ecd26d5f.PNG)

Work well and two options are much clearer to end users now. Thanks @vyruss Closing out
