### ISSUE TITLE
Step 2 (Shib): Present modal on first login to capture required profile info

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#306]
UX wireframes @JEK-III : http://h90c3m.axshare.com/#g=1&p=my_plans__first_login

When a user logs in for the first time using Shib/institutional credentials, they are presented w/a modal where they are required to input: 
- First and Last Name
- Recovery email
- Select language (optional, and only if system is configured for multiple languages)
They cannot save or proceed w/o required fields and should receive messages to that effect. Once they complete the required info and click Save and Continue, they arrive at the My plans page.

Note blue notepads w/functional specs to pre-populate fields if info is available via Shib.

**Comment by briri** [comment]
I don't think this is necessary any longer. The new workflow requires these fields for users signing up via the create account form, and if they create their account via shib they are also brought to a page that asks them to finish the registration process.

**Comment by stephaniesimms** [comment]
@briri - you're right. I revised the ticket w/the correct workflow for users creating an account via Shib. this includes UX wireframe for the modal where we capture the required profile info.

**Comment by sjDCC** [comment]
Fields are captured in registration form. Closing out
