### ISSUE TITLE
Configuration option restrict_orgs does not fully restrict assignable organisations/funders in plan update controller

### ISSUE THREAD

**Issue by nicolasfranck** [DMPRoadmap/roadmap#3064]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

`3.0.4`

**Expected behaviour:**

If you set the configuration option `config.x.application.restrict_orgs = true`,
one should not be able to create an unmanaged organisation, not?

**Actual behaviour:**

[This line](https://github.com/DMPRoadmap/roadmap/blob/master/app/controllers/plans_controller.rb#L270)
allows you to create a new (unmanaged) organisation.

Now we have a long list of unmanaged organisations of type "organisation",
because people tend to fill in a custom name in the field "funder" on the
"project details page". Afterwards they cannot find their name in the lookup
because that custom organisation was not marked as funder (and also because
it is unmanaged).

Not sure if that is intended behaviour?

These unmanaged organisations tend to pollute the list of organisations.
Is it worthwhile to add an organisation that is only used in one plan?

**Comment by briri** [comment]
Hi @nicolasfranck we were just discussing this issue last week. You are correct, the code on this page should be using the 'restrict_orgs' flag. I think we just missed it when implementing.

We have not yet issued a patch for this. 

If you need to clean up any orgs that were created due to this issue, you can run a query like this to identify any Orgs created via the Funder field on the Project Details page 
```SQL
SELECT * FROM orgs 
WHERE managed = false AND id IN (SELECT DISTINCT funder_id FROM plans) 
  AND id NOT IN (SELECT DISTINCT org_id FROM plans WHERE org_id IS NOT NULL) 
  AND id NOT IN (SELECT DISTINCT org_id FROM users WHERE org_id IS NOT NULL) 
  AND id NOT IN (SELECT DISTINCT org_id FROM contributors WHERE org_id IS NOT NULL)
  AND id NOT IN (SELECT DISTINCT org_id FROM templates WHERE org_id IS NOT NULL) ;
```

**Comment by raycarrick-ed** [comment]
this is known and is unintended behaviour. In dmponline we are patching in the meantime to stop it. @briri is currently working on a more comprehensive solution to this issue as there are multiple options for orgs and funders related to user and plan creation.

**Comment by raycarrick-ed** [comment]
Possibly connected to: https://github.com/DigitalCurationCentre/DMPonline-Service/issues/650

**Comment by mariapraetzellis** [comment]
This has been fixed and in latest release.
