### ISSUE TITLE
Invitees should only get one email, not two (Plan Sharing)

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#307]
When sharing plans, (unregistered) invitees should only get the invitation (to register) email and not a second plan sharing notification email as well.

**Comment by vyruss** [comment]
Slightly related to #268 so will go into same PR

**Comment by sjDCC** [comment]
This works and only one email comes out. 

The email notification was missing the application name in the title though, despite it being entered in the email text. Is this seeding from a different place? 
![307-email](https://cloud.githubusercontent.com/assets/6169940/26822937/b432ec8c-4aa3-11e7-989d-5aeafcbf0198.PNG)

If you can ensure this is entered then all is good to close out.

**Comment by vyruss** [comment]
This is fixed now

**Comment by sjDCC** [comment]
This is correct on the email when a plan is shared with an existing user but not on the email sent when someone is invited to register.

@stephaniesimms could you share plan with an unknown account to double-check please? Email still gave me %{application name} in title

**Comment by vyruss** [comment]
I just tested on dmponline-test and it has the correct behaviour.

**Comment by stephaniesimms** [comment]
This is working as expected now. Closing out.

![screen shot 2017-06-07 at 2 26 15 pm](https://user-images.githubusercontent.com/12703638/26902228-4f238136-4b8d-11e7-87ef-bb0397bf3a91.png)
