### ISSUE TITLE
Make share tab visible to super admins too 

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#3076]
based on https://github.com/DMPRoadmap/roadmap/issues/2090 org admins can view the share tab - but do not have editing rights. It would make sense adding this to super admins too 

@briri @raycarrick Would that be complicated to add?

**Comment by magdalenadrafiova** [comment]
We spoke with @pherterich and @mariapraetzellis and see this as useful - would it be possible to add?

**Comment by pherterich** [comment]
with DMPTool, this seems to be visible as the "manage collaborators" is now in the contributors tab and it shows up there - @raycarrick-ed is this locally disabled for us?

**Comment by raycarrick-ed** [comment]
It's not locally disabled for us. We are running the vanilla roadmap code and there are no overrides in this area. I'll dig into what the story is.

**Comment by raycarrick-ed** [comment]
@magdalenadrafiova @pherterich 
looking at the roadmap code you get the "Share" tab if:
- you can administer the plan (so own or edit or similar) or
- you are an org admin or super admin and the plan belongs to the same org as you
that looks to me like what the current live system is doing.
So what's different in DMPTool?

**Comment by magdalenadrafiova** [comment]
@raycarrick-ed so the second point _you are an org admin or super admin and the plan belongs to the same org as you
that looks to me like what the current live system is doing._
This one is actually not working. For example I am logged in as a super admin for University of Exeter and I cannot see the share button and with whom the plan has been shared with

**Comment by magdalenadrafiova** [comment]
Works for us too! closing the ticket
