### ISSUE TITLE
Org visibility plan will appear in the public DMPs only if filled 100%

### ISSUE THREAD

**Issue by magdalenadrafiova** [DMPRoadmap/roadmap#3086]
Currently when the researcher wants to make their plans visible, it says in the description that it has to be filled at least 50%, however, it is not true as a plan will not appear unless it is 100% filled. 
Could we change this back to 50% percent of the plan has to be filled as appears in the text for the researchers? 

@briri @raycarrick

**Comment by nicolasfranck** [comment]
The problem is also: 50% of what? There can be multiple phases..

**Comment by johnpinto1** [comment]
The fix in PR https://github.com/DMPRoadmap/roadmap/pull/3172

**Comment by pherterich** [comment]
Closing here as this is now included in release 3.1.1
