### ISSUE TITLE
Update user leads to error screen

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#312]
Hi all

I had to assign permissions to a user on dmponline-test. When I hit 'update' button, the error screen enclosed below appeared. I hat to hit the back arrow on the browser to get back to the dmponline screen. Permissions had been updated for user.
![errorscreen](https://cloud.githubusercontent.com/assets/2138956/26065243/2ff1361e-398b-11e7-9577-8b7d81acd5aa.JPG)

**Comment by vyruss** [comment]
@dsisu  I cannot replicate this on dmponline-test. Can you give me more details on what happens and if it still occurs after latest update?

**Comment by dsisu** [comment]
@vyruss It works now, thank you very much. I was still getting the error this morning. For the record the workflow was: find user -> click 'edit' -> make changes -> click 'update' - get error screen above. Hit the back key once, which took me back to the 'edit user' screen. Hit the back key again to get to my original screen, which could be the 'view/show user screen' or the result of a search. I would then hit the 'reload' key, which would put the user's new permissions on display. Hope this makes sense. If you're happy you have enough information for the record, you can close this now.

**Comment by vyruss** [comment]
Yes, thanks. Closing.
