### ISSUE TITLE
Tinymce initialization inconsistent

### ISSUE THREAD

**Issue by raycarrick-ed** [DMPRoadmap/roadmap#3138]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
3.0.6

**Expected behaviour:**
tinymce boxes should open in a cinsistent size

**Actual behaviour:**
tinymce boxes open with different sizes. Some too large, Some too small. When clicked on they correct to the proper size

**Steps to reproduce:**
open or create a a plan with multiple sections which have tinymce boxes in. Click to open and close them and tinymce boxes will be diferent sizes. Behaviour is also browser dependent e.g. Firefox and Chrome behave differently.

![image](https://user-images.githubusercontent.com/19663490/161273730-867e42e8-94e2-40ae-a3f2-a2532e564557.png)

**Comment by pherterich** [comment]
As this is addressed in the latest release, can we close the issue here?
