### ISSUE TITLE
Upgrade Ruby version

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#3139]
Upgrade Ruby from 2.6.3 to 2.7 or 3.x

See the release notes at: https://www.ruby-lang.org/en/

Related to #3103

**Comment by briri** [comment]
The big question here is whether or not we should consider upgrading to 3.0 or 3.1.

**Comment by benjaminfaure** [comment]
Seems like Rails 5 is not compatible with Ruby 2.7 according to these sources : 
https://www.fastruby.io/blog/ruby/rails/versions/compatibility-table.html
https://github.com/rails/rails/issues/38426

The official guide says 2.2.2 or newer : https://guides.rubyonrails.org/upgrading_ruby_on_rails.html

I tried switching from Ruby 2.6 to 2.7 on the roadmap code, basic features seems to be working fine, but I guess we can expect some side effects

**Comment by briri** [comment]
Upgraded to 2.7. Will open a new ticket for 3.0
