### ISSUE TITLE
Top right navigation menu does not work on touch screens

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#316]
Hi, options in top right corner navigation menu are not selectable on touch-screen devices. Valid on both live server and DMP-test. 
![cornernavmenu](https://cloud.githubusercontent.com/assets/2138956/26112316/86bb10e0-3a4f-11e7-8a1e-c008c8364340.JPG)

**Comment by sjDCC** [comment]
Works on phone. Closing out
