### ISSUE TITLE
Error downloading docx version of a plan

### ISSUE THREAD

**Issue by gjacob24** [DMPRoadmap/roadmap#3203]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
v3.1.1
**Expected behaviour:**
to open a downloaded copy docx version of a plan
**Actual behaviour:**
downloads the plan but throws an error when you try to open it in MS Word
<img width="431" alt="Screenshot 2022-08-10 at 15 25 25" src="https://user-images.githubusercontent.com/97518971/183926509-b4214351-3470-41e6-8d37-386bf7833fd9.png">

**Cause for error:**
The content of the plan contains Windows file path with slashes and digits which is being confused as code.

**Comment by gjacob24** [comment]
LibreOffice was helpful in showing error line in docx file with .zip and extracting `word\document.xml`

![LibreOffice_error](https://user-images.githubusercontent.com/97518971/183927978-975fc5d8-fa4c-4aba-af1b-0348e7287023.png)

The error was on the following line in `document.xml` created by malformed xml
![Selection_003](https://user-images.githubusercontent.com/97518971/183929038-0b9c641e-d55b-4f46-a3c9-730fcf940a42.png)

**Comment by gjacob24** [comment]
@johnpinto1 found the error and suggested a temporary solution: 

use `\\` for `\` in Windows paths.

**Comment by briri** [comment]
good catch @gjacob24! 

Have a look at the [config options for the wicked_pdf gem](https://github.com/mileszs/wicked_pdf). There might be something in there to help properly escape these. If anything, the `show_as_html: true` option might make it easier to debug or verify that your changes are working as expected. If not you may just need to address it in the view.

**Comment by johnpinto1** [comment]
@briri @gjacob24 It looks like issue affects only docx downloads too. But does not break the rendering:

Text should have this file path
> G:\Hematologie\Onderzoek\Studie Team Hematologie\Studies op alfabet\Aankomende studies\RODEO\00. DIGITAAL ISF\13. Case report Form (CRF)

Rendered  correctly as:

**HTML:**
![Selection_008](https://user-images.githubusercontent.com/8876215/184112407-fec5630b-284b-4d16-b5a2-c8df6c1cb625.png)
**TEXT**
![Selection_007](https://user-images.githubusercontent.com/8876215/184112413-0a6a2b8d-a927-4377-ac15-7e99c8d114aa.png)
**PDF**
![Selection_006](https://user-images.githubusercontent.com/8876215/184112415-6a540418-47b3-4065-a715-18bab7619fa2.png)

As htmtoWord gem uses the HTML to create the DOCX file. Need to escape characters at that stage I think.
