### ISSUE TITLE
Incorrect French abbreviation in seeding, making French translation unusable.

### ISSUE THREAD

**Issue by Sean-Stilwell** [DMPRoadmap/roadmap#3205]
**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
v3.1.1

**Expected behaviour:**
French translated version opens when changing language in the language toggle.

**Actual behaviour:**
Reverts to the default (en-GB for me) version. This does *not* occur with the Spanish, German, Turkish, or Portuguese translations (i.e it's exclusive to French).

**Cause:**
In [db/seeds.rb](https://github.com/DMPRoadmap/roadmap/blob/master/db/seeds.rb), the following is a value from the languages array:

```
{abbreviation: 'fr',
   description: '',
   name: 'Français',
   default_language: false},
```

The 'fr' abbreviation should be replaced by either 'fr-FR' or 'fr-CA'. Manually updating this value in my database to either abbreviation corrected this issue for me.

**Comment by briri** [comment]
Thanks @Sean-Stilwell would you be will to send a PR to update this for us?
