### ISSUE TITLE
Setting change needed to pre-select institutional guidance

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#326]
The selections made under the create plan wizard should preselect some guidance. The user should see any guidance that accompanies the template e.g. EC guidance for the H2020 template, plus any institutional guidance for their organisation. This is not pre-selected, but should be automatically ticked, with an option to uncheck. In the image below it should be St Andrew's that's checked.
![guidance-showing](https://cloud.githubusercontent.com/assets/6169940/26246614/fcce48a8-3c91-11e7-8d4f-347dd9ce25d6.PNG)

**Comment by vyruss** [comment]
@sjDCC Pre-select all Funder & Institutional guidance apart from Institutional-Optional?

**Comment by sjDCC** [comment]
Checked and works fine. Closing out
