### ISSUE TITLE
PR 3105 reverse for pagination?

### ISSUE THREAD

**Issue by pengyin-shan** [DMPRoadmap/roadmap#3278]
**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
v3.1.0 and v4.0.1 (current development branch)

**Expected behaviour:**
![Screenshot 2023-01-10 at 4 48 30 PM](https://user-images.githubusercontent.com/92752107/211669595-778a6636-be75-4888-94c9-104a70608ebd.png)

**Actual behaviour:**
![Screenshot 2023-01-10 at 4 49 04 PM](https://user-images.githubusercontent.com/92752107/211670095-cac2f9e6-d119-4835-922a-70ae18be8f99.png)

**No pagination anymore (1,2...are gone). Show all items in the `/org_admin/templates` page**

**Steps to reproduce:**
Navigate to `/org_admin/templates`.

A reverse of changes in: https://github.com/DMPRoadmap/roadmap/pull/3105 fixes the problem.  Thus, I'd like to confirm if this PR represents a universal change? Or there's supposed to be other changes with this PR to make pagination work correctly?

@johnpinto1 I saw you submitted the PR, do you have any context of this change?

**Comment by pengyin-shan** [comment]
I see. @johnpinto1 please pardon me if I'm wrong...the  `app/controllers/concerns/paginable.rb` is shared by all paginate parts right? So pagniation pages, such as `org_admin/plans` or `org_admin/templates` are also affected by this change. Do the DMPOnline's org admin pages have the correct pagination after this change?

@briri can you also verify if DMPTool has the correct pagination after applying PR3105? I'd like to check if I need to update DMP Assisant separately for this issue. Currently, I see pagination problems in both the 3.1.0 version (DMP Assisant fork) and 4.0.1 (development branch, roadmap).

**Comment by johnpinto1** [comment]
@pengyin-shan Yes it affects all pagination. 

Following your last comment, I just noticed "View all" appears for templates, but is missing for plans. @briri I think this might be a bug we missed, unless this was deliberate.

**Templates**
![Selection_061](https://user-images.githubusercontent.com/8876215/211853160-fb06b118-8365-4035-95d7-e129d0e05d8d.png)

**Plans**
![Selection_062](https://user-images.githubusercontent.com/8876215/211853517-e9dadfad-8c06-4536-a522-3bf12fd41a9e.png)

**Comment by briri** [comment]
@johnpinto1 I believe 'View All' was omitted (for Super Admins) from the Plans page due to the time it takes to render the page

**Comment by pengyin-shan** [comment]
@johnpinto1 @briri : thank you for the update! Just curious what's the `config.x.results_per_page` value on your side? For the DMP Assistant, I set it to 10 (i.e. 10 result maximum) per page, then I found the setting doesn't apply to pages (for example, /org_admin/templates has more than 10 results in one page), thus it reflects the pagination doesn't work.

**Comment by johnpinto1** [comment]
@pengyin-shan @briri Looks like the above change in requires **config.x.application.api_max_page_size**  
ahd is not using **config.x.results_per_page**

We are using
> config/initializers/_dmproadmap.rb
> 76:    config.x.application.api_max_page_size = 100
>

**Comment by johnpinto1** [comment]
@pengyin-shan  we have (but it does not seemed to be used)


> [dmp@dmp-live initializers]$ grep results_per_pag *
> _dmproadmap.rb:    config.x.results_per_page = 10

**Comment by pengyin-shan** [comment]
> @pengyin-shan we have (but it does not seem to be used)
> 
> > [dmp@dmp-live initializers]$ grep results_per_pag *
> > _dmproadmap.rb:    config.x.results_per_page = 10
> 
> and _dmproadmap.rb: config.x.application.api_max_page_size = 100

Ah thanks for this info! so based on what I observed from DMP Assistant so far, `config.x.results_per_page = 10` defines the pagination size on most of the *front-end pages*, such as the home page (plan dashboard), org_admin pages (such as `/org_admin/templates`.

Currently, the changes in PR 3105 seem to fix API0 pagination, but meanwhile, it deactivates the `results_per_page` setting, so the front-end pages lose the pagination effect. 

For now, I'm going to reverse PR 3105 for *DMP Assistant only*, since we only want users to see 10 results per time for convenience. @johnpinto1 @briri we can discuss later if we want a universal solution to make both API and front-end pagination work.

**Comment by briri** [comment]
Hmm. Pagination works for my API and the UI. I have `api_max_page_size = 100` and `results_per_page = 10`.

Looking at a diff between my paginable.rb and the one here I see a difference on [this line](https://github.com/DMPRoadmap/roadmap/blob/a803f43715b8174970dfcc5b6a9a103b36efe1e3/app/controllers/concerns/paginable.rb#L159). It references `api_max_page_size` and my copy has `results_per_page`. It should probably be the later.

**Comment by briri** [comment]
I'll submit a PR to fix this in the latest version

**Comment by pengyin-shan** [comment]
> Hmm. Pagination works for my API and the UI. I have `api_max_page_size = 100` and `results_per_page = 10`.
> 
> Looking at a diff between my paginable.rb and the one here I see a difference on [this line](https://github.com/DMPRoadmap/roadmap/blob/a803f43715b8174970dfcc5b6a9a103b36efe1e3/app/controllers/concerns/paginable.rb#L159). It references `api_max_page_size` and my copy has `results_per_page`. It should probably be the later.

Yes, I also use `results_per_page` after reversing the PR 3105 back.

**Comment by briri** [comment]
See if #3279 helps

**Comment by pengyin-shan** [comment]
I believe this problem has been fixed, so I'm going to close this ticket. We can re-open this one if the pagination problem come back
