### ISSUE TITLE
Allow user to delete account and remove all personal data from DMP systems

### ISSUE THREAD

**Issue by alexstuart** [DMPRoadmap/roadmap#330]
There should be the ability for someone to delete their account, and remove all personal data about themselves from your server. Preferably a button on the "edit profile" page, but if not, there should be a published method of how to inform the administrators of the system to request this.

I think this is different to https://github.com/DMPRoadmap/roadmap/issues/243, which looks like it requests the ability to disable an account, not delete it.

**Comment by briri** [comment]
This is a difficult problem to address. We would need to also remove all of their related records (e.g. plans, answers, roles). If a user removed their account under what circumstances should their plan also be removed? The plan could be public, or co-owned.
We will need to have a larger discussion of the use cases for this one before we can determine how to size it.

**Comment by vyruss** [comment]
@briri @jollopre according to our GDPR expert, their plans, answers & roles are not personal data and we are not required to remove them. All that is required is to anonymise the account (clear name and email in our case). 

Also we are not required to provide a button that allows the user to do this - all that is required is a statement somewhere on the website that goes "If you want to delete your account and all personal data, please contact our@email.address".

**Comment by stephaniesimms** [comment]
related issue #1489 supersedes this. closing.
