### ISSUE TITLE
Can't view template

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#331]
Hi, I was  checking whether UiT General Template had transferred correctly (all questions and sample answers) but can't edit the template on dmponline-test. Get University of Edinburgh page unavailable error screen. Not browser related, Firefox and Chrome behave the same. Template belongs to UiT The Arctic University of Norway and was created by user Philipp Conzett.

**Comment by sjDCC** [comment]
This still throws up an error page. See sequence in screengrabs below
![uit](https://cloud.githubusercontent.com/assets/6169940/26552562/9412f21e-447f-11e7-8cc9-a0c9a0391cd9.PNG)
![uit2](https://cloud.githubusercontent.com/assets/6169940/26552561/940ad390-447f-11e7-859c-f95208730758.PNG)

**Comment by dsisu** [comment]
Getting the same error message.

**Comment by sjDCC** [comment]
All working. Closing out
