### ISSUE TITLE
API internal server error 500

### ISSUE THREAD

**Issue by Danny-dK** [DMPRoadmap/roadmap#3315]
We (dmp.wur.nl) seem to be getting an internal server error 500 when querying the API v0 plans. 
We get the error with:

`"https://dmp.wur.nl/api/v0/plans?&per_page=100&template[]=1038574365&template[]=1182076051&created_after=2023-04-01"`
or
`"https://dmp.wur.nl/api/v0/plans"`

Querying statistics works without problem:

`"https://dmp.wur.nl/api/v0/statistics/plans"`

Any ideas what is causing this?

**Comment by gjacob24** [comment]
@Danny-dK thanks for letting us know. DMPonline is currently working on a fix for this and will have it rectified shortly. We will push the fix to the DMPRoadmap code base soon after.

**Comment by Danny-dK** [comment]
@dsisu  Yep, working again. Thanks!!!
