### ISSUE TITLE
Duplicate 'guidance' in guidance name

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#333]
The DCC guidance entries are showing with the word guidance twice e.g. 
![guidance-duplication](https://cloud.githubusercontent.com/assets/6169940/26287440/6ae27f7a-3e73-11e7-973a-11c15d3feab9.PNG)

This typically happens if the guidance group name is "Institution guidance" as this is then appended on to  text that reads "guidance on [theme name]. There used to be something in the code that removed duplicate entries of the word guidance so this perhaps needs to be reinstated?

**Comment by vyruss** [comment]
Which page does this appear on? Perhaps we can add a colon in between? 
Writing code to see if the person writing the guidance group name and the guidance name has included the same word at the end of one and the beginning of the other is bad practice IMHO as we'd be solving a problem which is not ours.

**Comment by vyruss** [comment]
@sjDCC how does this look? (on dmponline-test)

**Comment by sjDCC** [comment]
I would prefer it if we didn't have two entries of 'guidance' together. How about we remove the text 'guidance on' before the theme name. That should work whether or not the uni guidance group name includes the word guidance e.g.

Edinburgh guidance: data sharing
Edinburgh: data sharing

What do you think @stephaniesimms?

**Comment by vyruss** [comment]
@sjDCC this is clearly a data issue and not something for us to solve. If they want to avoid guidance: guidance then they should change their titles!

**Comment by sjDCC** [comment]
Yes, I know. My approach was just to try and reduce helpdesk tickets and avoid having to provide lots of user guidance. We used to have a rule that filtered the duplication out so people will be confused to see it again. 

Will see what @stephaniesimms prefers and we'll either add more user guidance or remove "guidance on". Either will work.

**Comment by vyruss** [comment]
@sjDCC we can always run a nice clean-up database query that will change all titles from "Guidance on tropical diseases" to "Tropical diseases"...

**Comment by stephaniesimms** [comment]
I keep going back and forth on this. Let me check with UX. Personally I prefer to keep our own Guidance header and instruct admins to remove it from their user guidance, but this could prove difficult in practice as @sjDCC noted. Maybe we can find a better, lightweight approach (e.g., a tooltip) to instruct admins as they're creating guidance...

**Comment by sjDCC** [comment]
Ok, let's rework the tooltip text on adding guidance groups and close this out. Can you do that today @vyruss?

Here's what it currently says:
![tooltip](https://cloud.githubusercontent.com/assets/6169940/26822216/32bade78-4aa1-11e7-9ab4-f8ad85f34ae2.PNG)

Let's replace with:

Add an appropriate name for your guidance group. This name will be used to tell the end user where the guidance has come from. It will be appended to text identifying the theme e.g. "[guidance group name]: guidance on data sharing" so we suggest you just use the institution or department name.

**Comment by vyruss** [comment]
Done

**Comment by sjDCC** [comment]
Tested and looks good. Closing out.
