### ISSUE TITLE
No checkbox in front of organisation name in guidance selection

### ISSUE THREAD

**Issue by StCyr** [DMPRoadmap/roadmap#3342]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**

4.1.0

**Expected behaviour:**

For a better layout, there should be a checkbox in front of the organisation name

**Actual behaviour:**

There's no checkbox in front of organisation name in the guidance selection box when creating a plan (see entry "Ghent University..." in screenshot hereunder):

![image](https://github.com/DMPRoadmap/roadmap/assets/8179031/b64f57fe-5fa6-4779-9d08-571a091e1f44)

This is ugly

**Comment by StCyr** [comment]
Here's the code that manage checkboxes value:

```js
   $('#priority-guidance-orgs').find('input[type="checkbox"]').click((e) => {
      syncGuidance($(e.target).closest('ul[id]'));
    });

   // Keep the modal window's guidance selections in line with selections on the main page
    const syncGuidance = (ctx) => {
      const currentList = $(ctx);
      const otherList = (currentList.attr('id') === 'priority-guidance-orgs' ? $('#other-guidance-orgs') : $('#priority-guidance-orgs'));
      const selections = currentList.find('input[type="checkbox"]:checked').map((i, el) => $(el).val()).get();
      otherList.find('input[type="checkbox"]').each((i, el) => {
        const checkbox = $(el);
        // Toggle the checked flag to match the current guidance list
        if (selections.indexOf(checkbox.val()) >= 0) {
          checkbox.prop('checked', true);
        } else {
          checkbox.prop('checked', false);
        }
      });
      toggleCheckboxes(selections);
    };


   // Toggle the disabled flags
    const toggleCheckboxes = (selections) => {
      $('#priority-guidance-orgs, #other-guidance-orgs').find('input[type="checkbox"]').each((i, el) => {
        const checkbox = $(el);
        if (selections.length >= getConstant('MAX_NUMBER_GUIDANCE_SELECTIONS')) {
          if (checkbox.is(':checked')) {
            checkbox.removeAttr('disabled');
          } else {
            checkbox.prop('disabled', true);
          }
        } else {
          checkbox.prop('disabled', false);
        }
      });
    };
```

Unfortunately, I don't understand what it's doing exactly, so I've hard time improving it.

Also, the exact functionality of the new checkbox that would be implemented is not defined. The simplest functionality would probably be to make this checkbox always disabled

**Comment by nicolasfranck** [comment]
@StCyr duplicate: https://github.com/DMPRoadmap/roadmap/issues/2945

**Comment by StCyr** [comment]
let's close it then
