### ISSUE TITLE
Several issues with institutional customisations of funder templates

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#335]
Is seems the data has gone awry when transferring institutional customisations of funder templates. There are several issues here so you may want to split these out into separate tickets, but I'm unsure how to untangle them.

Comparing live and test, St Andrew's haven't customised any funder templates, but when you check on the test site it suggested they've customised most. [On 2nd check, this may be a display error on DMPonline as looking at BBSRC and EPSRC, St Andrew's have at least added suggested answers to these if not more funders]
![funder-customisations](https://cloud.githubusercontent.com/assets/6169940/26287647/dd48dd44-3e77-11e7-8846-dbe9e84b40b8.PNG)
![funder-customisations-test](https://cloud.githubusercontent.com/assets/6169940/26287646/dd48e8b6-3e77-11e7-8003-d0bc7a11d972.PNG)

Clicking into these customisations raises several errors. The first is to do with the templates themselves. It seems the permissions are wrong on many. I'm presented with options to add phases and edit template details, when all institutions should be able to do is 1) add sections, 2) add suggested answers and 3) add guidance / annotations per question. It also suggests the template is unpublished which isn't the case - if it were it wouldn't be available to customise. It seems most say they're unpublished so the data is invalid.
![wrong-rights-customise](https://cloud.githubusercontent.com/assets/6169940/26287676/777b4032-3e78-11e7-8bd9-86aa3afefb47.PNG)

I can't see whether options to add sections, suggested answers and guidance / annotations are actually provided as each time I click the template page I get one of the following errors. I've not found one that opens yet.
![funder-customisation-error](https://cloud.githubusercontent.com/assets/6169940/26287666/56ac9acc-3e78-11e7-9f7b-be2b4841a05d.PNG)
![funder-customisation-error2](https://cloud.githubusercontent.com/assets/6169940/26287665/56a8e3dc-3e78-11e7-8466-98feec07d61f.PNG)

**Comment by vyruss** [comment]
The reason some templates appear as customised, is because we have had users from Org A use templates from Org B to create plans, which then causes legacy templates (combinations of phases/sections/questions valid at that point in time) to appear as customisations of Org B templates by Org A. @xsrust is aware of the issue and working on it

**Comment by sjDCC** [comment]
The main issue raised seems to be fixed so closing out. The problem with having additional edit rights when customising a funder template has been added to #373
