### ISSUE TITLE
Did we capture the latest versions of funder templates?

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#339]
Hi, Looking at the list of templates for University of Salford, it seems that dmponline-test doesn't have the latest versions of the templates. For example, on the live server, the AHRC template is dated 11-07-2016 and on the test server it is dated 29-04-2016. To be fair the status message says 'Original funder template has changed!'.

There is also a slight mismatch in the list of templates. On the live server the list of templates displays both the ZonMW templates (English and Dutch, one unpublished) on the test server we have the list includes the DCC template. The list on the test server makes more sense; I can't see why Salford would include the Dutch version of the template rather than the English one but that's their choice.  The bottom line is the lists don't match.

**Comment by vyruss** [comment]
Cause identified by @xsrust

**Comment by sjDCC** [comment]
I think we still have mistakes in the template versions. On the live site, the version of ESRC being customised is dated 28-10-2015, whereas on test it's 16-09-2013. The set of questions is different too. First screengrab is live site and second test.
![live-esrc](https://cloud.githubusercontent.com/assets/6169940/26532436/a4b4a888-43f8-11e7-8f9b-d9c66cc65089.PNG)
![test-esrc](https://cloud.githubusercontent.com/assets/6169940/26532437/aa36cc64-43f8-11e7-886e-27beff9c67eb.PNG)

I've logged in as ESRC to check the template history as this isn't visible under the customisation view. There are 4 versions of the template. What is showing in the first screengrab above is the final 4th version which is published. The one we're making available to customise now on test seems to match version 3
![current-live-esrc](https://cloud.githubusercontent.com/assets/6169940/26532442/e40a34d0-43f8-11e7-938e-5ba4bdbcd9c7.PNG)

**Comment by vyruss** [comment]
@sjDCC you are referring to a version of a template from 28-05-2017 which hadn't made it into the data dump which was from a few days back...

**Comment by sjDCC** [comment]
No... the date on the live site is 28-10-2015. The latest funder version will be in your data dump but for some reasons we're presenting an out of date version for customisation. Incorrect migration?

**Comment by xsrust** [comment]
This is currently solved on dmponline-test
![screen shot 2017-05-31 at 10 44 56 am](https://cloud.githubusercontent.com/assets/7352616/26626148/3ae997f4-45ee-11e7-9d1c-a156a77e0933.png)

**Comment by sjDCC** [comment]
All fixed. Closing out
