### ISSUE TITLE
API v0 wiki documentation update

### ISSUE THREAD

**Issue by StCyr** [DMPRoadmap/roadmap#3393]
https://github.com/DMPRoadmap/roadmap/wiki/API-V0-Documentation

**Expected behaviour:**

"When you're granted the "Use API" privilege, the <API_TOKEN> is found on the 'Edit Profile' page. This is used to authenticate the user, and determine which API endpoints they have access to."

**Actual behaviour:**

"The <API_TOKEN> is found on the 'Edit Profile' page. This is used to authenticate the user, and determine which API endpoints they have access to."

**Comment by gjacob24** [comment]
Hi @StCyr thank you for raising this. 

I think there may be a misunderstanding regarding how the tool is used. When a user creates an account they will have access only to the basic functionalities of the tool (for example: create, edit, share a plan). Only an org or super admin will have access to other features of the tool like creating a template, using the API etc. and they in turn can grant access to the same privileges to other users. 

Therefore, the user would have to be 'granted permission' to 'Use API'. I have attached a screenshot of what the list of permissions for an org and super admin looks like. If you have anymore questions, please let us know.

<img width="1073" alt="screenshot_admin_priv" src="https://github.com/DMPRoadmap/roadmap/assets/97518971/00044106-511d-4031-94c0-355b4e7336a3">

**Comment by StCyr** [comment]
That's exactly my point: This is not correctly documented in https://github.com/DMPRoadmap/roadmap/wiki/API-V0-Documentation

BR,

Cyrille

**Comment by gjacob24** [comment]
Hi @StCyr apologies again for the misunderstanding. I have made the change to the documentation as you suggested. Once you confirm, I will close the issue, or feel free to close it yourself after checking. Thanks!
[https://github.com/DMPRoadmap/roadmap/wiki/API-v0-Documentation](https://github.com/DMPRoadmap/roadmap/wiki/API-v0-Documentation)

**Comment by StCyr** [comment]
looks good to me. Thanks @gjacob24 gj
