### ISSUE TITLE
Unordered org list on admin interface

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#340]
The organisation list on the admin interface is unordered and the search/filter is not clever e.g. 'Glasg' finds the first closest entry, not all possible options. Please put in alphabetical order as it's so unwieldy I can't find things.
![active-admin](https://cloud.githubusercontent.com/assets/6169940/26287868/ded51174-3e7b-11e7-8ab1-2b8f62aa171b.png)

**Comment by vyruss** [comment]
related to thoughtbot/administrate#386

**Comment by sjDCC** [comment]
Looks good. Closing out
