### ISSUE TITLE
up and down arrow for sorting

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#342]
Was it a deliberate decision to remove the up/down arrows for sorting ascending/descending from the title row?
DMPonline-test screen grab:
![capture1](https://cloud.githubusercontent.com/assets/2138956/26288043/633a54f2-3e80-11e7-9c0d-ebf144869513.JPG)

DMPonline live screen grab - see highlight:
![capture2](https://cloud.githubusercontent.com/assets/2138956/26288056/c727cada-3e80-11e7-9ccc-a75bc7369ce3.JPG)

**Comment by vyruss** [comment]
@dsisu As far as I can see the table columns are still sortable if you click on the title. It's just the two arrows that have gone missing somehow.

**Comment by dsisu** [comment]
That's right, the sorting still works. We have to get the arrows back, though, otherwise it won't be obvious to users that the tables are sortable. A bit of a pain but I hope it's easy to fix.

**Comment by sjDCC** [comment]
Showing again and works fine. Closing out
