### ISSUE TITLE
Creating a plan for H2020 gives me different version of template (institutional customisation error?)

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#343]
As noted in #334, when I create a plan for EC H2020 and Sheffield Hallam Uni, I get an old, unpublished version of the template. You can tell this as it asks people to describe things on a 'dataset by dataset' level.

Checking the H2020 template on the admin interface, all seems well. The previous versions are showing in the history table as unpublished. Unfortunately I can't view these to check content as clicking to do so brings up the Edinburgh error message. 
![h2020-template-history](https://cloud.githubusercontent.com/assets/6169940/26288233/6a36a062-3e85-11e7-8877-fd3d6c29defe.PNG)

The strange thing is that if I create a H2020 plan with no organisation, I get the correct, current version of the template. Could the fact that Sheffield Hallam have added a section be the cause of users getting the wrong version? It shouldn't be as they've added their section to both new and old versions of the template on the live site so data for both cases should have transferred.

There are display issues with the H2020 template (when the right version comes up). The phases are out of sequence and the progress bar is calculating on all questions, rather than by phase which would make more sense. Again I can't view this on the admin side as I get a 404 so I don't know if the phase is mis-numbered or if this is a data migration issue.
![h2020-published-test-site](https://cloud.githubusercontent.com/assets/6169940/26288251/b293d5f0-3e85-11e7-83bd-a0e1779ce898.PNG)

**Comment by xsrust** [comment]
This bug is most likely due to the plan creation interaction selecting an old, customized template.  It was originally the intention that out of date (funder has published a newer version) customizations would not get selected by the create plan page.

**Comment by sjDCC** [comment]
The correct template seems to be being pulled in all cases now, but there are still a couple of outstanding issues. 
1. Any sections added from any org are presented, not just your own (screengrab 1)
2. The guidance from SHU is listed as 'EC guidance' This doesn't seem to occur for KU Leuven so maybe a one-off? (screengrab 2)
![ec-1](https://cloud.githubusercontent.com/assets/6169940/26550615/69e139a0-4476-11e7-9444-905caa63c0f8.PNG)
![ec-2](https://cloud.githubusercontent.com/assets/6169940/26550619/6ec2ccea-4476-11e7-9c0f-5a5f5062ee2b.PNG)

**Comment by xsrust** [comment]
Additional sections issue fixed on dmponline-test as of last migration

**Comment by sjDCC** [comment]
Closing out. The outstanding issue that SHU guidance is being mislabelled as EC is being addressed by @xsrust in #371
