### ISSUE TITLE
Show number of users

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#346]
Hi all

Please provide some on-screen statistics for org_admin users. For example, when they click in the 'Users' tab, they should be able to see the total number of users. Could work the same with templates and guidance but those are easier to count at a glance. I know org_admins have asked to see total number of users and plans so we could start with that.

Thank you!

**Comment by briri** [comment]
@sjDCC and @stephaniesimms can this be closed out now that we have the Admin -> Users page and the statistics page?

**Comment by stephaniesimms** [comment]
yes i think we can close this now
