### ISSUE TITLE
Metadata for https://dmponline-test.dcc.ac.uk/shibboleth registered in the UK federation omits some capability

### ISSUE THREAD

**Issue by alexstuart** [DMPRoadmap/roadmap#347]
The automatically-generated metadata at https://dmponline-test.dcc.ac.uk/Shibboleth.sso/Metadata shows that your SP supports more encryption methods than are registered in metadata. The administrative contact for the test SP should contact the UK federation helpdesk and ask for them to include these additional encryption algorithms:
```
      <md:EncryptionMethod Algorithm="http://www.w3.org/2009/xmlenc11#aes128-gcm"/>
      <md:EncryptionMethod Algorithm="http://www.w3.org/2009/xmlenc11#aes192-gcm"/>
      <md:EncryptionMethod Algorithm="http://www.w3.org/2009/xmlenc11#aes256-gcm"/>
```

If you don't know who the administrative contact is, just drop the helpdesk an email and they can let you know / advise you.

The reason this is important is that these encryption methods are considered more secure than the ones you currently advertise, and also that the [draft InCommon deployment profile requirements](https://spaces.internet2.edu/display/DPWG/Deployment+Profile+Requirements+Text) state that SPs MUST support the AES-GCM cipher for this encryption.

**Comment by vyruss** [comment]
Thanks, will let administrative contact know.

**Comment by alexstuart** [comment]
Cheers. I have a suspicion that the registered admin contact for the SP has left DCC, and if so you'll need to get one of the Management Contacts for Edinburgh Uni to appoint one or more new admin contacts. You should probably get this done for the production SP, too.

**Comment by vyruss** [comment]
Request made to UK Fed.

**Comment by briri** [comment]
@vyruss please close this one out if you've heard back from the UK Federation

**Comment by stephaniesimms** [comment]
closing as this pertains to dmponline
