### ISSUE TITLE
View plan for an user with read_only permission does not work

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#352]
If the plan to view includes questions such as radiobutton, checkbox, etc, the following error is raised: 
![snaphost](https://cloud.githubusercontent.com/assets/7393044/26354116/315f4514-3fbb-11e7-890a-fa77a0d9e6f4.png)

**Comment by sjDCC** [comment]
@jollopre Could you share a NERC plan as read-only to s.jones@arts.gla.ac.uk please so I can test this?

**Comment by jollopre** [comment]
done! Please try to see if you can edit anything related to plan's answer

**Comment by sjDCC** [comment]
I can't edit anything in read-only mode (text areas or dropdowns etc) I can leave a note though.

All seems right and no errors are thrown so closing out
