### ISSUE TITLE
Answered <TIME> ago by <USER> at plan edit

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#355]
The Answered <TIME> ago by <USER>snippet under each answer only works when it is updated the text within the tinyMCE component, i.e. for radiobutton, checkbox questions... if only changes the options selected that snippet never get updated.

**Comment by sjDCC** [comment]
I don't think this is fixed @jollopre I went into the NERC template to test changes and answered two questions - one radio button and one dropdown. They saved correctly saying they were last edited less than 1 min ago by me. I refreshed the page a few minutes later to test updates but both then recorded as not having been answered, although answers were clearly still recorded. 
![nerc-1](https://cloud.githubusercontent.com/assets/6169940/26485906/c2d67f4e-41f0-11e7-95b8-0eb05e4b7056.PNG)
![nerc](https://cloud.githubusercontent.com/assets/6169940/26485907/c2d84248-41f0-11e7-8b91-4e5aa3a6d06b.PNG)

I went to export to check whether answers are being saved and no format I tried would export. Don't know if this is related or linked to other changes currently being made. Will hold off raising a ticket for now until we're sure

**Comment by jollopre** [comment]
I'm not able to replicate what you are describing. 

Regarding the export, it's broken, see issue #364

**Comment by sjDCC** [comment]
Just tested again and this is still happening for me. You edit an answer and it records correctly then you refresh the page or navigate away and return and it says not answered yet

Thanks for raising export issue separately

**Comment by sjDCC** [comment]
Fixed. Closing out
