### ISSUE TITLE
Sign out raises an error related to shibboleth

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#359]
This error is raised on developer's machine.

![snaphost](https://cloud.githubusercontent.com/assets/7393044/26444073/ca67bde0-4132-11e7-9bde-a0730c5aeba3.png)

**Comment by vyruss** [comment]
Not a bug, you just don't have a Shibboleth SP running on your machine. Set 
```ruby
config.shibboleth_enabled = false
```
in your `config/application.rb`.
