### ISSUE TITLE
Email invite on sharing plan has incorrect link

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#363]
While trying to test #352, I shared a plan as read-only with an existing account I have (sarahjones28@hotmail.com)

I checked my email and had received this invite to register.
![Uploading invite.PNG…]()

The link within this doesn't resolve. It points to an old, outdated URL it seems

**Comment by vyruss** [comment]
@sjDCC the email is not the same in the screenshot

**Comment by sjDCC** [comment]
Just realised that! Must have shared with a typo previously. Going to re-test sharing and then will close out

**Comment by sjDCC** [comment]
Am going to edit original issue description as there seem to be two issues with this that still need fixing:
1. the email invite link is wrong and doesn't resolve
2. when I login to an account I created under this email, I don't see the plan that has been shared

**Comment by vyruss** [comment]
@sjDCC Server configuration got overwritten while checking out latest code. Please re-test, confirm and close.

**Comment by sjDCC** [comment]
Yes, seems to be working. Closing out
