### ISSUE TITLE
Additional sections (customisations of funder templates) are not filtering correctly

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#371]
Any sections added by institutions to funder templates are displaying all the time it seems, not just for those within the given institution.

The following is a screengrab of a plan created for MRC by a user based at the University of Glasgow. Sheffield Hallam's section and another (IGT) is displaying on the front end.
![mrc-template](https://cloud.githubusercontent.com/assets/6169940/26531586/ec884d6e-43e3-11e7-9e45-873e24a64f3e.PNG)

The same occurs on the admin interface. If I go in to customise a funder template, I see content belonging to other institutions which shouldn't display. 
![institutional-sections](https://cloud.githubusercontent.com/assets/6169940/26531602/25b18bdc-43e4-11e7-8433-a51c8165d37b.PNG)

**Comment by xsrust** [comment]
This is fixed in the update to the migration step 2

**Comment by xsrust** [comment]
![screen shot 2017-05-29 at 5 35 49 pm](https://cloud.githubusercontent.com/assets/7352616/26556904/546c8006-4495-11e7-867b-c3d8378aebce.png)

**Comment by xsrust** [comment]
https://github.com/DMPRoadmap/roadmap/commit/7ab8039a4bd05445a3113d48ba7c6c456d5fc13a

**Comment by xsrust** [comment]
@vyruss if you've re-migrated the data since the 29th, this should be ready for UAT

**Comment by sjDCC** [comment]
This is fixed now. Only the relevant sections are displaying based on the user org / selection in create plan wizard.

I did spot one issue. The guidance added by the org in its own section of the custom template is being mislabelled as by the funder / template owner. I'm sure I've recorded this somewhere else so this may be good to close out. Or if not, start a new ticket?
![misnamed-guidance](https://cloud.githubusercontent.com/assets/6169940/26633988/10b388ea-460d-11e7-962d-5c0c6ee73ec7.PNG)

**Comment by xsrust** [comment]
I have identified the cause of that issue and am fixing it later today with another change to the migration.

**Comment by xsrust** [comment]
I can confirm this is fixed by the above change.
![screen shot 2017-06-05 at 9 59 39 am](https://cloud.githubusercontent.com/assets/7352616/26777596/baaa2658-49d5-11e7-9c5c-fa3cd69e630a.png)

**Comment by sjDCC** [comment]
All working. Closing out
