### ISSUE TITLE
Suggested answers: transferred but not displaying

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#372]
It seems example / suggested answers have transferred correctly and are being affiliated with the correct institution, but they aren't displaying on the front end.

Here is the view for EPSRC + St Andrew's on the live site
![live-site](https://cloud.githubusercontent.com/assets/6169940/26531696/747cd9a4-43e6-11e7-922b-8545c9cc8d08.PNG)

And the same on test. Note that the example answer is missing.
![test-site](https://cloud.githubusercontent.com/assets/6169940/26531697/785609e2-43e6-11e7-9bec-7e11c9113d3c.PNG)

Looking on the admin interface, this has transferred but is now called guidance. See related issue #374 
![changed-placement-labelling-suggested-answers](https://cloud.githubusercontent.com/assets/6169940/26531706/e2ccafc4-43e6-11e7-9c46-1798879c9f7c.PNG)

Is it a form of question annotation? How is it different from guidance by question in that case and what happens to each type of content? Where will this display? I can't tell via the admin interface as the 'preview' button gives a 404

**Comment by xsrust** [comment]
This should be a simple fix.  The Guidance/Example Answer is defined as an ENUM in the annotations model.  I must have switched the order which they were defined in between the migration and when i committed the file on the live code

**Comment by xsrust** [comment]
https://github.com/DigitalCurationCentre/roadmap/commit/e9651bb00202edd3bfe4833e34997acc8839dd71

**Comment by sjDCC** [comment]
Yay! All working. Closing out
