### ISSUE TITLE
Permissions to create or edit existing template customisations

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#373]
The button to edit existing content added to a funder template is missing. I have an option to add a section but not amend suggested answers or questions added to a section previously etc. Screengrabs from current live and test
![edit-customisation](https://cloud.githubusercontent.com/assets/6169940/26531721/2bf3b94a-43e7-11e7-8c45-18fc80a2f258.PNG)
![edit-missing](https://cloud.githubusercontent.com/assets/6169940/26531720/2bf2feb0-43e7-11e7-8e71-72a189f63b93.PNG)

**Comment by sjDCC** [comment]
An update to this. The functionality to edit a section previously added seems to be working. I have now logged in as Brighton who added the "Project and funder details" section and see this in edit mode. The two issues are that:
1. No questions display the button to add an example / suggested answer
2. Sections added by other orgs are also visible (though not editable)
![customisation-functionality](https://cloud.githubusercontent.com/assets/6169940/26532042/f81949ca-43ee-11e7-8d37-ecf83ead9c9e.PNG)

**Comment by sjDCC** [comment]
Adding another point from #335 as this is related.

The edit rights on customisations of funder templates should be:
1. Add example or suggested answers
2. Add guidance / question annotations
3. Add sections
4. Edit any of the above details when added.

Currently users are being given an option to add a phase and edit template details, neither of which they should be able to do
![permissions](https://cloud.githubusercontent.com/assets/6169940/26550281/d70bd8d4-4474-11e7-9686-760338610ad4.PNG)

**Comment by xsrust** [comment]
The following screen shots depict the interface implimented.  This feature needed to be re-written.
In particular, the 'Add/Edit Annotations' text may need re-worked as of UAT.  The button allows the user to edit both suggested_answer and guidance from one form.

![screen shot 2017-06-06 at 4 20 30 pm](https://user-images.githubusercontent.com/7352616/26837010-3e20e7a2-4ad4-11e7-93bd-8e97855e98d0.png)
![screen shot 2017-06-06 at 4 20 55 pm](https://user-images.githubusercontent.com/7352616/26837009-3e1cf66a-4ad4-11e7-96d3-414c5a16092a.png)

**Comment by sjDCC** [comment]
The buttons to add and edit annotations appear but clicking them doesn't open up an editable area, either on existing customisations or when trying to add new ones. Effectively i can't get @xsrust's second screengrab to show. Adding sections does open up an editable box though.

**Comment by vyruss** [comment]
@sjDCC please try again - I hadn't precompiled the javascript changes on the server.

**Comment by xsrust** [comment]
It seems to be working for me on dmponline-test

**Comment by sjDCC** [comment]
Yay! this is working. closing out

**Comment by dsisu** [comment]
If you clikc on 'add annotations' but then decide to hit 'cancel, it doesn't close the field; you are thrown further up the page but the 'add annotations' procedure remains open.

**Comment by sjDCC** [comment]
Have checked and I experience this too. It also lets you save with nothing entered in the box. The overview table then shows the template as having being customised although no guidance or suggested answers are saved or show up on the front end though...

I've added an actual suggested answer and it's not showing on the front end either. I'm on a call now, but @dsisu could you do more testing adding content through annotations and checking they show up on front end please.

**Comment by sjDCC** [comment]
Ignore me. I missed the publishing step. All is working :)

Only thing is @dsisu's point that the box doesn't close when you cancel

**Comment by sjDCC** [comment]
Working fine now. Cancel closes the boxes. Closing out
