### ISSUE TITLE
Mismatch between guidance and example answers

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#374]
Something has gone wrong in transferring guidance and examples on templates. Here is an example of a University of Brighton template called "EPSRC". What was recorded as guidance on live, is now showing as example answers
![brighton-epsrc-on-live](https://cloud.githubusercontent.com/assets/6169940/26531990/c33622a6-43ed-11e7-9e67-4e78e7cc240c.PNG)

![brighton-epsrc-on-test](https://cloud.githubusercontent.com/assets/6169940/26532013/7e7069e6-43ee-11e7-8717-e820cb96fe6a.PNG)

The guidance fields are blank

**Comment by sjDCC** [comment]
Having tested this on an institutional section I added to a funder template, I can confirm that guidance and example answers have been switched in the migration. Screengrabs below of question added on admin side and what displays on front end
![ku-test](https://cloud.githubusercontent.com/assets/6169940/26532635/0b39494c-43fe-11e7-8fc7-40e2f622d4a6.PNG)
![capture](https://cloud.githubusercontent.com/assets/6169940/26532637/1f09122c-43fe-11e7-8053-88cd36ebeb4e.PNG)

**Comment by xsrust** [comment]
This is the same issue as 372.

Will be fixed by switching the enum in app/annotaions.rb

**Comment by xsrust** [comment]
https://github.com/DigitalCurationCentre/roadmap/commit/e9651bb00202edd3bfe4833e34997acc8839dd71

**Comment by vyruss** [comment]
Closing as duplicate
