### ISSUE TITLE
Institutional logos are missing from the top banner

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#375]
Logos files have not been transferred. Here's the banner for Salford on live and on test.
![salford-live](https://cloud.githubusercontent.com/assets/6169940/26532482/b691ce9a-43f9-11e7-9215-10ee8bfd9d8a.PNG)
![salford-test](https://cloud.githubusercontent.com/assets/6169940/26532485/bb4e5674-43f9-11e7-8d93-15e32eafe305.PNG)

The logo is not showing on the admin interface either under 'org details' though the file upload option is available

**Comment by vyruss** [comment]
Weiwei's addition of logo uploads means we can't use the on-disk filenames anymore and have to re-upload for those orgs.

**Comment by sjDCC** [comment]
I have the files to upload so this can effectively be closed.

Two things to check:
1. Should I upload them all now or will the data be changed / replaced before we push out to test?
2. Do we need to place an image resolution limit as one I uploaded looks very grainy. On the live site it displays much smaller
![sterling-test](https://user-images.githubusercontent.com/6169940/26875241-e74a6066-4b78-11e7-8e4e-341238e8b1d2.PNG)
![sterling-live](https://user-images.githubusercontent.com/6169940/26875247-ecc8122c-4b78-11e7-8c24-fa14c3f7f973.PNG)

**Comment by vyruss** [comment]
This will be down to the header CSS scaling the image to 100 pixels height or something like that. I don't know how we can fix this besides disabling scaling

**Comment by sjDCC** [comment]
I've searched and found a better image to replace this with. It was the only one that caused any grief so far so happy to leave as is, especially as people will be uploading themselves so can check result.

Should I upload all now or will the data change again before testing? I guess it will change due to the suggested answer issue so I should hold off for now?

Closing out as main issue fixed

**Comment by vyruss** [comment]
@sjDCC we will re-migrate so don't upload yet. Cheers
