### ISSUE TITLE
Can't get past the 'Create a new plan' page

### ISSUE THREAD

**Issue by jdddog** [DMPRoadmap/roadmap#376]
Hi

I'm having trouble with version: v0.2.6.

When I try to create a new plan and fill in all of the details (project title, primary research organisation and funding organisation), and click  "Create Plan", I get a tool-tip that says "You cannot continue until you have filled in all of the required information". It doesn't matter if I check the "My research organisation is not on the list or no research organisation is associated with this plan" or "No funder associated with this plan". 

Here's an image: http://imgur.com/sPg3s1f

This was working in version v0.3.3, but someone deleted it and or renamed all of the other releases, which is a bit annoying. Which current release corresponds to v0.3.3?

Thanks for your help

Jamie

**Comment by sjDCC** [comment]
Looking at the screengrab, I suspect the issue may be that the funder 'government agency' isn't one of the options in the dropdown list. These boxes have a number of pre-defined values based on the templates available in the instance of the tool. If the text entered isn't in the list, it probably records it as unanswered.

**Comment by jdddog** [comment]
I did select 'Government Agency' from the list of options in the search box, same with 'University of Exampleland'

I get the same error if I check those two checkboxes, which should mean I don't have to enter anything anyway: http://imgur.com/DS29yFs

**Comment by weiweishi** [comment]
I wonder if this issue has been solved yet. We have just started a sandbox instance on the latest master and get the same message, and can't pass the plan creation page. 
![image](https://user-images.githubusercontent.com/2047614/32026713-bd97cdf6-b9a2-11e7-9b9a-908e7a58d162.png)

**Comment by briri** [comment]
Hi @weiweishi, make sure that one of the templates in your database is marked as the default template. The logic behind this page queries the DB for appropriate templates for the specified funder/research org. When it cannot find any it will use the default template

**Comment by briri** [comment]
We have a ticket for updating documentation, #771, that I will add this to. We should have it both in the troubleshooting section as well as the seeds.rb file and migration instructions.

**Comment by weiweishi** [comment]
thank you @briri maybe I've done something incorrect? I've set one of the template as default:
```
=> #<Template id: 1, title: "My Curation Center's Default Template", description: "The default template", published: false, org_id: 1, locale: nil, is_default: true, created_at: "2017-10-25 22:31:02", updated_at: "2017-10-25 22:46:04", version: 0, visibility: 1, customization_of: nil, dmptemplate_id: 1, migrated: false, dirty: false>
```
And still got the same issue?
![image](https://user-images.githubusercontent.com/2047614/32027123-9d7493b8-b9a4-11e7-97dd-54eb8fb3447c.png)

**Comment by briri** [comment]
The `set_creation_defaults` callback on the `templates` model was overriding the `published` and `is_default` values specified in the seeds.rb file. The fix for this will appear in the next release. 

@jdddog and @weiweishi you can get this working before the release comes out by editing the database table manually via these commands (assuming you still have those seed file templates in your database):
```sql
UPDATE templates SET is_default = 1 WHERE id = 1;
UPDATE templates SET published = 1 WHERE id IN (1, 3);
``` 
apologies for the very long delay in addressing this one @jdddog

**Comment by stephaniesimms** [comment]
default template for creating new plans is working as expected on roadmap stage. closing issue. 

a separate issue related to creating new plans w/funder templates #777 is in progress and should be fixed soon.
