### ISSUE TITLE
Can't edit my existing plans

### ISSUE THREAD

**Issue by dsisu** [DMPRoadmap/roadmap#385]
Hi, I can create plans but can't go back and edit them. Get 'page unavailable' error.

**Comment by dsisu** [comment]
I thought I'd add a further comment, in case it helps. I can edit some plans but not others. There is no logic to it. The older plans seem to be less accessible than the newer ones. However, I did create a couple of plans today, which I was unable to edit once I saved them. Sam was here and saw that. I'm talking about dmponline-test.

**Comment by sjDCC** [comment]
I have experienced this too. Screengrab with url example in case that helps
![capture](https://cloud.githubusercontent.com/assets/6169940/26646122/5ffef644-4632-11e7-881f-09fdc169a91a.PNG)

**Comment by sjDCC** [comment]
Have tried various plans on various accounts including previous offending ones and all seem to open and edit fine now so closing this out
