### ISSUE TITLE
Can't edit existing plans

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#389]
Related issue for DMPOnline test #385 - I can create a new plan and answer questions but not edit anything for existing plans. Creating a separate issue for now because it's unclear to me whether DMPonline test and Roadmap are in sync.

On My plans page, clicking the plan title or Edit produces this error
![screen shot 2017-05-31 at 1 40 13 pm](https://cloud.githubusercontent.com/assets/12703638/26653117/fd1a62fa-4606-11e7-9c24-670aade01b59.png)

**Comment by sjDCC** [comment]
Can't re-create this on DMPonline test but will leave to check on staging

**Comment by stephaniesimms** [comment]
This is working on roadmap stage now. Closing issue.
