### ISSUE TITLE
Profile page should display ORCID iD number

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#390]
Previously the ORCID iD field displayed the number. Unless ORCID considers it best practice to state that "Your account has been linked..." I think we should keep the number here as that's also a field we want to auto-populate in the Plan details. Even though it's a long 16-digits that no one would memorize, users should get accustomed to seeing it written out next to the green ORCID logo. Ideally it should appear as a full URL (second screenshot)

![screen shot 2017-06-01 at 2 17 58 pm](https://cloud.githubusercontent.com/assets/12703638/26701455/0ac48870-46d6-11e7-83cf-2a755dd502b5.png)

![screen shot 2017-06-06 at 11 46 58 am](https://user-images.githubusercontent.com/12703638/26846282-09d3b770-4aae-11e7-8ad8-bd9ebeb54f3a.png)

**Comment by stephaniesimms** [comment]
i'm not sure what's happening now, but the functionality to connect ORCID doesn't appear to work at all anymore:

- I clicked the button to "Create or connect your ORCID ID"
- this took me to the ORCID login page where I entered my credentials and Authorized connection
- which sent me back to the Edit Profile page where it looks like nothing happened (no auth message, no ORCID ID no displayed)
- now each time I click the "Create or connect your ORCID ID" button again, and it just reloads the profile page

**Comment by bhavi** [comment]
error message added and deployed to dev.

**Comment by stephaniesimms** [comment]
closing this unresolved issue and replacing with #580
