### ISSUE TITLE
Welcome emails not being issued

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#399]
I have created new account on DMPTuuli test (directly created) and on DMPonline test via a plan sharing invite, and in neither case was the welcome email issued.

Users should receive an email that states:

Email title: Welcome to [TOOL NAME]
Welcome to [TOOL NAME], someone@tester.org!

[TOOL NAME] will help you to develop your Data Management Plan. If you have any queries or feedback as you use the tool, please contact us on [INSERT HELPDESK EMAIL]
All the best
The [TOOL NAME] team

**Comment by sjDCC** [comment]
@vyruss can you clarify why this won't be fixed please?

There should be a welcome email issued on account creation

**Comment by vyruss** [comment]
dmptuuli-test server configuration issue - unrelated to the code

**Comment by sjDCC** [comment]
but they're not being issued from DMPonline-test either so please check configuration on both. Ta

**Comment by vyruss** [comment]
@sjDCC I just signed up on dmponline-test and received one instantly
