### ISSUE TITLE
Questions mis-ordered on DMPTuuli

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#402]
Questions are displaying in the wrong order on Tuuli. Again, I assume this is a config issue as not occuring on DMPonline test.

Tekes template on live
![tekes-live](https://cloud.githubusercontent.com/assets/6169940/26825825/6a7847e4-4aae-11e7-925b-54deec8a89a8.PNG)

Tekes template on test
![tekes-test](https://cloud.githubusercontent.com/assets/6169940/26825840/78c6102e-4aae-11e7-8891-aed71533cd45.PNG)

**Comment by vyruss** [comment]
Actually a code issue. Phases and questions were never ordered by `.number` (intended). It just happened that the database returned them in the correct order (`.number` was not checked).

**Comment by sjDCC** [comment]
All working. Closing out,
