### ISSUE TITLE
Allow for a custom Shibboleth discovery service page

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#405]
The DMPTool allows us to filter the list of institutions that appear in the InCommon list. This is accomplished by storing the the institution's Shib IdP entityID in the database. The use selects their institution and a call is passed through to the Shib SP that redirects them to the institution's IdP.

![screen shot 2017-06-07 at 8 14 45 am](https://user-images.githubusercontent.com/1204467/26886226-ad62ff58-4b59-11e7-9c78-b55cc34fec3b.png)

We will need to add the same functionality to Roadmap but it should be done in a way that is configurable so that an installation can default to using their federation's standard discovery service (the DCC approach).

related to #305

**Comment by briri** [comment]
![screen shot 2017-06-07 at 2 53 03 pm](https://user-images.githubusercontent.com/1204467/26903192-2e4315d6-4b91-11e7-997a-b59765b67d91.png)

**Comment by briri** [comment]
Hey @JEK-III,
I've added the custom shibboleth discovery service on dev. Please take a look when you have a moment. I have it set so that it shows you the accessible autocomplete textbox instead of the dropdown right now. I will change it to display the regular dropdown when there are less than 10 institutions.

Please note the following: 
- I'm having trouble getting the 'Go' button to display to the right of the autocomplete (partially due to the clear 'x' button that appears). Is it ok to leave as is? 
- I can't really change the sort order of the items in the autocomplete or highlight the text the user has entered within the selections without tampering with the widget's code. We can do that if we deem it to be necessary but it will take some time and would ideally be contributed back to the widget author so we aren't maintaining a one-off version
- UCOP is the only one that will actually drive you out to an IdP. I don't know the entity ids of the UK federation ones. I just added them here sp to give an idea of what the list would look like

Here are some screenshots of what the normal dropdown will look like if there are 10 or fewer institutions (the go button is to the right here ... shouldn't be confusing to users as they would typically only ever see the dropdown or autocomplete not both):
![screen shot 2017-06-08 at 12 39 00 pm](https://user-images.githubusercontent.com/1204467/26954068-e3864806-4c62-11e7-8a37-f06e57b5a498.png)

![screen shot 2017-06-08 at 12 39 18 pm](https://user-images.githubusercontent.com/1204467/26954070-eb55c610-4c62-11e7-9148-d31b8b1fd96f.png)

And here are some views of other column layouts. I have it set to display one column if there are 55 orgs or less, two columns if its between 55 and 110 and three columns if its greater than 110 orgs. Its easy to change those thresholds
![screen shot 2017-06-08 at 2 26 46 pm](https://user-images.githubusercontent.com/1204467/26954078-f2aebf34-4c62-11e7-8f6f-92b7dfc9563c.png)

![screen shot 2017-06-08 at 2 27 10 pm](https://user-images.githubusercontent.com/1204467/26954094-fba2ea98-4c62-11e7-8e2c-b6adff0cdaa9.png)

**Comment by stephaniesimms** [comment]
@JEK-III is the authority on @briri 's questions above, but I wanted to contribute my $0.02 - 
- I like (and definitely think we need to offer) the ability to display the full list of institutions
- we should change it to say "See the full list of participating institutions" (not "partner")
- terms are inconsistent. on main Sign In page we should change "Organisation" to "Institution" (I'll note in the appropriate issue)

**Comment by briri** [comment]
done and deployed on dev

**Comment by JEK-III** [comment]
@briri 
* The "Go" button below is fine by me, but it could probably be twice as wide as it is. 
* Highlighting and sort-order are definitely things that can be postponed (perhaps forever)

**Comment by stephaniesimms** [comment]
@briri On the line below "See the full list of participating institutions" please change text to read: "Institution not in the list? Create an account with any email address"

![screen shot 2017-06-19 at 1 21 23 pm](https://user-images.githubusercontent.com/12703638/27304275-581fa29c-54f2-11e7-9066-032972924521.png)

**Comment by stephaniesimms** [comment]
Shib is no longer working on either dev or stage (see related issue #510). For this page, just two minor changes/questions @briri @JEK-III 
- the "x" button to cancel my selection drifts far to the right of the box when I maximize the window in different browsers. can you anchor the x closer to the edge of the box?
- it seems weird to have the Sign In button at the top right of the page. when I click it I get a modal that loops me back through the process. I get that we display the Sign In button on other public pages but I wonder if it would be better to remove it here? 

![sign-in](https://user-images.githubusercontent.com/12703638/28139267-81244918-6708-11e7-8fc5-14d8773b4f94.png)

**Comment by stephaniesimms** [comment]
@briri two changes I requested from above that got overlooked:
- change it to say "See the full list of participating institutions" (not "partner"). we use partner to mean various different things in connection w/the DMPTool and it's become confusing for all involved.

![screen shot 2017-07-17 at 8 31 56 am](https://user-images.githubusercontent.com/12703638/28276043-a180df76-6aca-11e7-88b4-06992478616e.png)

- and the line below that should read: "Institution not in the list? Create an account with any email address"

![screen shot 2017-07-17 at 8 32 10 am](https://user-images.githubusercontent.com/12703638/28276049-a6b41c7e-6aca-11e7-8f13-ef5eeb39656c.png)

**Comment by sjDCC** [comment]
Looks good, although I couldn't find the "Institution not in list?" entry. This is probably because you need to type so if filters choices and doesn't give you whole list.

Suggest you either:
a) include this entry at bottom of all filtered lists i.e. so it's always visible irrespective of what's typed
b) include it as a standalone link like the 'See the full list of participating institutions" one

**Comment by stephaniesimms** [comment]
I agree that the Institution not in list option needs to be more prominent. Moving this issue back to In Progress pending comprehensive revision of the sign-on workflow for DMPTool. Also noting here that we can switch to using "Other" to designate the Org for non-affiliated accounts as in DMPonline (currently we use "Not in list" for DMPTool data).

**Comment by briri** [comment]
Ok. We'll need to do write some JS to override the behavior of the jquery accessible autocomplete box. 
**Dev notes:** 
- Looks like we could just append to `$("div[role='listbox']")` (and likely need to remove at the beginning of the search so that they don't stack).
- The selection of that 'not in list' option should trigger the display of the other org textbox

**Comment by briri** [comment]
Moving this off the project board for now until we get back into the separate signin/create work

**Comment by briri** [comment]
Closing out. This has been handled via a DMPTool specific customization
