### ISSUE TITLE
Patch devise gem to handle invitations to share plans properly

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#407]
Related issue #397 

Scenario:
- User shares a plan with an email address that does not have an account.
- The person that the plan was shared with does not get or see the email
- The person that the plan was shared with registers their account directly without following the link in the email
- The person enters their new account and does not find the shared plan because the link to it has been deleted (a brand new account overwrites the stem account w/link to plan)

The desired behavior is to preserve the link to the shared plan regardless of the path the user follows to create an account. Otherwise the user has to request that the original plan owner re-invite them to the plan. Devise gem should be patched to support this use case as it is probably common and desired by others.

**Comment by briri** [comment]
the devise and devise_invitable gems are separate projects. The devise_invitable gem creates the user record when the plan is shared. If the user creates an account before accepting the invitation it looks like the devise gem overwrites the record created by devise_invitable.

We may have to send one of them a PR to patch this behavior, or monkey patch it on our end.

**Comment by vyruss** [comment]
@briri I've coded this behaviour in the registrations controller (destroy stem account - this also gets rid of the role (plan sharing)). The gems' default behaviour is to not let the user register (because their email is known to the system - there is a stem acccount with it) and this is what was annoying our users.

**Comment by sjDCC** [comment]
Ideally we'd have the position @stephaniesimms outlines i.e. user can still create account (an unfollowed token invite / stem account shouldn't prevent this) AND they'd have access to shared plan. I don't think it's possible to have the two though, so we opted for being able to register as being more important

**Comment by briri** [comment]
@vyruss fixed this. I just confirmed.
