### ISSUE TITLE
Adjust layout on Create plan page per wireframe

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#408]
Move the text and tick boxes from below the bottom two entry fields over to the right. This cleans up real estate and gives the impression of a shorter form/first step in plan creation. 
See UX wireframes @JEK-III - http://h90c3m.axshare.com/#g=1&p=create_plan 

Current implementation
![screen shot 2017-06-07 at 4 29 58 pm](https://user-images.githubusercontent.com/12703638/26905878-b2cf8eb2-4b9e-11e7-970c-5a999f8707ee.png)

**Comment by rhu001** [comment]
I'll be talking with @briri this afternoon about putting together a first draft of a different color scheme. So in this case it would be using a dark green outline for the box with a gray drop shadow to make the "boxes" with the different form fields stand out against a white background. Another thing to change would be to make the headers a dark green as well.

**Comment by briri** [comment]
I'm not sure I understand the issue correctly @stephaniesimms. I just added some whitespace to the left of the orange headings/questions and deployed to dev. Let me know if that is what you were after.

**Comment by stephaniesimms** [comment]
yes, I meant add whitespace to the left of the orange headings. thanks @briri - looks good. and the other questions re colors are more related to accessibility. it sounds like UX is on the case.

**Comment by stephaniesimms** [comment]
looks good. moving this issue along.

**Comment by sjDCC** [comment]
Look at this page critically now, I have a few suggestions. I've attempted to mock these up in the annotated screengrab:
- Should the big questions and the guidance and boxes all be in one line. This would mean indenting the questions by a fraction more
- Our question/title and the smaller text question/guidance below essentially say the same thing in each case. Can we condense into one instruction per box/dropdown to save real estate further? e.g.
1. What is the title of the the research project you are planning?
2. Select the primary research organisation
3. Select the primary funder
- Could the 'if applying for funding...' guidance, go in the box as greyed out text like 'Begin typing to see a filtered list'
![create plan](https://user-images.githubusercontent.com/6169940/27614660-f9c183be-5b9a-11e7-908f-4917798f7d37.PNG)

Ignore the question marks on q2+3 btw - just realised they aren't phrased as questions.

**Comment by stephaniesimms** [comment]
@briri Now that I'm reviewing on stage w/new style things:
- please add more whitespace above the question text for the 3 large question boxes
- the "x" to cancel Org selection needs to be replaced next to the selection box (it drifted below)

![screen shot 2017-06-27 at 4 26 21 pm](https://user-images.githubusercontent.com/12703638/27614653-dc7e2214-5b57-11e7-9c17-9a18894a4cdb.png)

**Comment by JEK-III** [comment]
I agree with all of @sjDCC 's suggestions except moving 'if applying for funding...' into the text field. That kind of guidance should be used with care because it goes away as soon as you start to fill in the field. It only works for the funding question because the filtered list appears right away when you start typing so the instruction isn't needed anymore.

We could still clean up the page by doing the opposite and just showing the guidance on focus in one of those black speech balloons. Which, now that I look, is what we do now on the Plan Details page.
![plan_creation_guidance](https://user-images.githubusercontent.com/6305223/27615114-d7fef8f0-5b5a-11e7-96c3-0ab180446112.png)

**Comment by briri** [comment]
I have made these adjustments and deployed to stage. The tooltips have a new CSS styling and should now be generic going forward (all appearing and behaving in the same manner). @JEK-III and @rhu001 please let us know if the old dark grey box is still the best way to present these.

**Comment by stephaniesimms** [comment]
@briri please also adjust per @sjDCC comments above:
- delete "Project title" from above box 1
- revise tooltip to include the word project: "If applying for funding, state the project title exactly as in the proposal"
- delete explanation text above boxes 2 and 3 and revise main headings: "Select the primary research organisation" and "Select the primary funding organisation"

![screen shot 2017-06-29 at 11 02 02 am](https://user-images.githubusercontent.com/12703638/27702913-86d4b288-5cba-11e7-835a-4b2b09a0aaab.png)

**Comment by briri** [comment]
Changes made and deployed to dev and stage

**Comment by stephaniesimms** [comment]
the new layout looks great, much cleaner! two tiny adjustments:
- Now that we're not asking 3 questions, please adjust the instructions at the top of the box per wireframe: "Before you get writing, we need some information about your research project to set you up with the best DMP template for your needs."
- in the funder field the warning message appears as soon as I type anything into the box, including a valid funding org. expected behavior is to receive this msg only when i move focus away from the field and have not entered a valid funding org.

![screen shot 2017-07-03 at 10 28 32 am](https://user-images.githubusercontent.com/12703638/27802799-d4431096-5fda-11e7-8746-8c19e4b6c92f.png)

**Comment by briri** [comment]
made recommended adjustments and deployed to dev and stage

**Comment by stephaniesimms** [comment]
Looks great except for one tiny behavior w/the error message in the Org and Funder selection boxes. When I type in the box and make my selection, a truncated half of the error message appears below the box. It only disappears when I tab away from the box. Can you make that not happen @briri ?

![screen shot 2017-07-12 at 2 09 31 pm](https://user-images.githubusercontent.com/12703638/28140162-0fdca71a-670c-11e7-961e-e075af4cfe2f.png)
![screen shot 2017-07-12 at 2 09 17 pm](https://user-images.githubusercontent.com/12703638/28140167-131ee686-670c-11e7-8a92-1eb126845192.png)

**Comment by briri** [comment]
error message is now only visible when user is typing in the auto-complete boxes. Need to make sure it remains visible when the focus changes.

**Comment by stephaniesimms** [comment]
the problem I described previously is resolved. but now I'm getting some other strange/inconsistent error message behavior that doesn't provide a clear indication of what info is invalid (screenshots below). overall the behavior is correct in that i can't create a plan if all fields aren't validated. but if possible, we want to highlight which field(s) is invalid.  

1- if I type a word "University" that exists in the filtered list but is not a complete Org name, I don't get an error msg for the Org field. But I do get an error when I try to click Create plan - this doesn't indicate which field is invalid
![org-incorrect](https://user-images.githubusercontent.com/12703638/28387415-e0248c7c-6c83-11e7-9489-3f1bb2fe3765.png)

2- if I type "NASA" or "NERC" I sometimes get the field error message and other times am able to tab through it without a message. on a couple of occasions, i got the field error message after typing NERC and selecting "National Environmental Research Council (NERC)" from the list - I could not proceed until i cleared the field and started over

![screen shot 2017-07-19 at 1 16 30 pm](https://user-images.githubusercontent.com/12703638/28387938-d0687440-6c85-11e7-9430-687c75139211.png)
![funder-list](https://user-images.githubusercontent.com/12703638/28387959-e2fd08aa-6c85-11e7-81e8-7c31f3ee17e9.png)

**Comment by sjDCC** [comment]
Yeah, I've done some testing and get the same issues as @stephaniesimms 

A warning appears in the org and funder field when you type something that mismatches with values from the dropdown list, but it's very easy to keep typing and tab through this. The error that then displays when clicking the 'create plan' button doesn't indicate where the change is needed.

I noticed that we do highlight the box in red (screengrab 1) when the first error message appears, so suggest that the second error message highlights the field(s) with bad data and also appends the text from the earlier error message e.g.

"You cannot continue until you have filled in all of the information required. You must select an organisation and funder from the dropdown lists, or check the box for none"

![error](https://user-images.githubusercontent.com/6169940/28414663-a3dd86bc-6d44-11e7-9572-b7b2a432b4a1.png)

![error2](https://user-images.githubusercontent.com/6169940/28414669-a955017e-6d44-11e7-877c-64b51bcdcf02.png)

@stephaniesimms I couldn't recreate the problem of typing / selecting NERC and still getting the error. Tried several times and always generated plan fine.

One small styling point I noticed is that we should probably align the heading / title with the boxes, but that's probably for another ticket?

**Comment by briri** [comment]
Error messages should be working now @sjDCC and @stephaniesimms. The error message appears while typing and remains when you move to a different box.

The indentation of the title and page description are at a sitewide level in most cases so I' will update and address on #424

**Comment by sjDCC** [comment]
Looks good. Thanks @briri Definitely better to just leave the warning up as this stops users ignoring it

Closing out
