### ISSUE TITLE
Revise tabs for plan editing pages

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#417]
UX wireframes @JEK-III - http://h90c3m.axshare.com/#g=1&p=write_plan

@JEK-III can you revise the wireframes to have plan/square tabs instead of arrows? I like the look but it's not exactly a directional process (i.e., Share does not follow from writing a plan)

**Comment by stephaniesimms** [comment]
tab shape is good now. @JEK-III is making some additional revisions to the Project Details and Export/Download pages per our mtg on 19 Jun.

**Comment by briri** [comment]
We will need to break this ticket into multiple sub tickets. I think perhaps one per tab along with a separate one to handle the new Guidance/Notes section.

**Comment by briri** [comment]
closing. replaced by new Revise Plan tickets
