### ISSUE TITLE
Revise My plans table layout

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#418]
UX wireframes @JEK-III - http://h90c3m.axshare.com/#g=1&p=my_plans__ideal

Revise My plans table to include columns for Template, Visibility, Test checkbox, and the revised list of actions (includes Duplicate plan)

**Comment by briri** [comment]
Updated column layout to match wire frame.
![screen shot 2017-06-13 at 10 38 54 am](https://user-images.githubusercontent.com/1204467/27096049-a298774a-5024-11e7-861c-c516f14c9000.png)

**Comment by stephaniesimms** [comment]
@briri - please change first column to read "Plan Title" 

@JEK-III are you working on a dropdown for the Actions? the table is pretty cramped and displays funny in most browsers. The Test column gets squished and Actions text wraps (screenshot), neither of which are great

![screen shot 2017-06-16 at 1 51 43 pm](https://user-images.githubusercontent.com/12703638/27244363-0dd088fe-529b-11e7-9033-09c54960a353.png)

**Comment by JEK-III** [comment]
@stephaniesimms Sure am!
I put three solutions up on Axshare: http://h90c3m.axshare.com/#g=1&p=my_plans_table
1. replace the action labels with icons
2. move the actions into a dropdown (together with status and visibility).
3. remove most of the actions from the My Plans table. This adds a click or two for the removed actions, but streamlines the table greatly, and I don't expect users to have any extra difficulty finding the moved items.

**Comment by briri** [comment]
@stephaniesimms the column name has been changed to 'Project Title' and is now out on the stage server

**Comment by stephaniesimms** [comment]
@JEK-III per our mtg on 19 Jun - please revise wireframes to include a functional spec to make the Project Titles a hyperlink that opens the plan editing page.

For the actions, let's try Option 2 w/revisions that we discussed:
- Rename "Menu" to "Actions"
- Remove "Mark as:" status section from actions menu
- Should we replace the table heading for now "Select an Action" ?

**Comment by JEK-III** [comment]
@stephaniesimms 
Done!  (http://h90c3m.axshare.com/#g=1&p=my_plans__ideal)

Having a visible column header for the "Actions" column strikes me as unnecessary clutter; I added a spec annotation for an invisible header for screen-reader accessibility.

**Comment by stephaniesimms** [comment]
@JEK-III this looks marvelous. one small change: under Visibility, "My Inst." should just be "Institutional" or "Inst."

@briri wireframe is ready for you now (w/exception of one change noted here).

**Comment by stephaniesimms** [comment]
@briri - see wireframe:
- add Actions dropdown menu
- swap Test and Visibility columns

**Comment by stephaniesimms** [comment]
this looks great on stage @briri . will move it along and wait for feedback from @sjDCC

**Comment by sjDCC** [comment]
Looks good. The dropdown was playing up for me before and not staying open but is now. Perhaps worth some more checks to ensure it's ok on all browsers?

At moment the 'share' 'download' and 'duplicate' buttons are all throwing errors.

The change of language from 'export' to 'download' was a surprise, but I guess it's a clearer term. Something to check with users again.

**Comment by briri** [comment]
@sjDCC and @stephaniesimms  The dropdown should be more consistent now. I also finished applying the new CSS rules to the plan edit/share/download pages so you should be able to view them now.
I have started working on the Project Details tab but am not yet finished so saving changes on that form may or may not work depending on what you have changed.
I only gave the other tabs some basic styling since we will be reviewing their layouts so that they adhere to the new wireframes

**Comment by stephaniesimms** [comment]
@briri the My plans page and table layout look great. Actions menu works smoothly for me and takes me to the appropriate pages. Closing this issue.
