### ISSUE TITLE
Review wiki documentation for Upgrading from DMPonline v.4

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#419]
Test the upgrade process and make any necessary refinements/revisions to the documentation on Github wiki. We should aim to have this ready by MVP v0.3.

https://github.com/DMPRoadmap/roadmap/wiki/Upgrading-from-DMPonline_v4

**Comment by xsrust** [comment]
Testing by running through an upgrade on a newly installed environment with only dmponline_v4 gems and following the wiki directions to the letter.

**Comment by xsrust** [comment]
The only issue i encountered was a missing `bundle install` which I have now added to the wiki documentation.

**Comment by vyruss** [comment]
Steps & documentation verified while running the DMPonline service migration.
