### ISSUE TITLE
Create wiki documentation for Pootle portal

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#420]
Create a wiki page to advise users about the process for creating an account and contributing translations for DMPRoadmap via the Pootle portal. @sjDCC and i can test when ready, ideally in time for v0.3 release.

**Comment by vyruss** [comment]
Adding screenshot ![image](https://user-images.githubusercontent.com/18707439/27284341-242b9e2a-54f0-11e7-8aff-e05840e39c5e.png)

**Comment by vyruss** [comment]
Screenshot ![image](https://user-images.githubusercontent.com/18707439/27284442-a826bb60-54f0-11e7-8277-571e032f2805.png)

**Comment by vyruss** [comment]
Screenshot ![image](https://user-images.githubusercontent.com/18707439/27284688-baf16b18-54f1-11e7-838f-c22214a2cf86.png)

**Comment by vyruss** [comment]
Screenshot 
![image](https://user-images.githubusercontent.com/18707439/27285050-3065d068-54f3-11e7-8f04-315694130058.png)

**Comment by vyruss** [comment]
Wiki page added. https://github.com/DMPRoadmap/roadmap/wiki/Translations

**Comment by stephaniesimms** [comment]
thanks @vyruss - now @sjDCC and I can test it out

**Comment by dsisu** [comment]
@vyruss I will take a look at it too

**Comment by sjDCC** [comment]
I've taken a quick look at pootle again and I find it a bit difficult to navigate. 

Is there a simple way someone can get a list of all the terms they need to translate and click through these one by one? We maybe need to add a few basic intructions on how to get into and process a translation.

I also noticed that some of the text will need updating (maily static pages e.g. DMP help). We should re-load these once Stephanie and I have agreed a final set.

**Comment by stephaniesimms** [comment]
I've been playing with the Tutorial and can't figure out how to contextualize the words and phrases that need translating, which makes it difficult to provide an accurate translation. This could be related to @sjDCC request above about getting a complete list of terms to translate.

**Comment by vyruss** [comment]
@sjDCC as soon as you enter Translate mode, you can scroll through all the translations using `CTRL+down` (or `+up`). You can increase the number of items on screen by going to _Settings -> Translation -> Number of rows_ (adding this to Wiki). 

@stephaniesimms we can add contextual tags in our source code which explain the context to the translator. I'll look into this and detail how it can be done to the devs. We'd rather people didn't work on the pofiles directly because it's easy to make the files unusable by missing out a single or double quote.

**Comment by stephaniesimms** [comment]
thanks for the explanation @vyruss
these changes/revisions to the documentation sound good

**Comment by vyruss** [comment]
Context will appear like so (adding to Wiki too) ![image](https://user-images.githubusercontent.com/18707439/27587465-69c72da8-5b3c-11e7-963d-99c10247ac6c.png)
