### ISSUE TITLE
Review installation documentation on wiki

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#421]
@bhavi will run through the documentation for a new installation of DMPRoadmap and make notes about any necessary revisions. The team will review on 20 Jun and update the documentation prior to MVP v0.3 release.

https://github.com/DMPRoadmap/roadmap/wiki/Installation

**Comment by bhavi** [comment]
The installation process of DMPRoadmap was pretty smooth.  Below are my observations:

1.  Ran into bundler issues with gem json v1.8.3  when installing  with ruby2.4 and rails5.1 versions.  Had to downgrade to ruby2.2.  Might work if json gem to upgraded to >1.8.5 
(https://github.com/rails/rails/issues/27450)

2. The gem initializer files under config/locales( ***static.yml files** ) seemed to have been renamed in the current repo. Need to update that part of the documentation.

**Comment by stephaniesimms** [comment]
@bhavi updated documentation. reopening issue just to read through and confirm all changes are straightforward.

**Comment by vyruss** [comment]
Wiki edited, added max supported versions and note about testing ruby 2.4/rails 5.0 in the future.
