### ISSUE TITLE
Recover account and unlink/link workflow

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#426]
- user clicks on 'recover account' enters either their old login email or recovery email (same page layout as forgot password page)
- user clicks on link in recover your account email
- user is brought to a new edit profile-like page where they can change the main email address, unlink and relink institutional creds

- if they have linked the account the box is greyed out (they cannot change it) but they can click 'unlink'
- if they unlink they can select a new org from the list
- if the org has shib enabled (or in the case of DCC where they don't track it) we display the 'link your account' link
- which drives them out to the IdP
 
not sure how best to handle DCC who have some orgs with no shib but they have no idea which ones

**Comment by briri** [comment]
Removing this from the MVP label since we have decided to postpone the functionality for now since this is an edge case.

**Comment by stephaniesimms** [comment]
closing this since we are unlikely to address in the near term. we get infrequent requests for account recovery.
