### ISSUE TITLE
Allow Org Admins to view their user's plans & notifications about plans

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#434]
UX wireframe @rhu001 - "DMP All Org Plans (Admin View)"
screenshot below

- Provide Org Admins with a list of all plans created by users at their Org that they can view in a read-only (read and comment) mode. Add this page as "Plans" in Admin dropdown menu. 
- Add search box above table
- When a user requests feedback on their DMP, admins need a notification/marker for which plans are awaiting feedback. If plans are awaiting feedback, a Notifications area should appear at the top of the Plans page. 
- Clicking on the link to a plan (e.g., "Plan Title A") takes the user to the write plan view where they can read and add comments.
- Plans should remain in the notifications area until the user/Admin signals that they are done providing feedback by clicking "done" in the modal dialog box #728 

![screen shot 2017-11-07 at 7 39 14 am](https://user-images.githubusercontent.com/12703638/32502145-d60f5796-c38e-11e7-9737-f707d557b436.png)

**Comment by briri** [comment]
Refer to the 'DMP All Org Plans (Admin View)' page from the wireframe above.
**Dev Notes:**
- Add a new 'Plans' link to the Admin menu that brings you to the new page
- Create a plans page that
  - Displays notifications at the top. Notifications currently only consist of plans that have had a request for feedback (see #727)
  - Displays a list of all of the Org's plans. The user should not be able to click through to the plan from this table, just view the contents of the table

**Comment by sjDCC** [comment]
This looks good, thanks @briri 

Two minor points based on John's wireframe:
1. We may want to change the 'filter' function to a search box above the table, though perhaps this is happening as a global change across all tables via another ticket?
2. On the dev notes it says "The user should not be able to click through to the plan from this table, just view the contents of the table" but the wireframe suggests each plan title will be a link to the plan in read-only mode. What was the rationale for changing this? I thought we were giving admins access to plan content too?

**Comment by stephaniesimms** [comment]
@sjDCC #1 is being addressed in another ticket, yes.
#2 is incorrect in the wireframe. or maybe i'm forgetting if we agreed to provide org admins access to plan contents? currently, we only give them a list of plan names and metadata via the DMPTool API and this is sufficient for their needs. plan owners can opt to request feedback to provide admins w/access to the plan contents. the privacy policy probably makes it ok to provide all plan details but my sense is this implementation meets user needs (both owner and admin).

**Comment by sjDCC** [comment]
Hi @stephaniesimms There is some confusion over point 2. I'd understood we were giving access to the content of plans not just the metadata as there have been a lot of requests for this from DMPonline admin users. The T&Cs were written to allow for this and I think it's something we need to offer soon, if not now. Perhaps we need to build in some checks and balances around this though e.g. like linking it to plan status as originally envisaged?

Note that this is also related to #876 about revising terminology to make it clear who has access to plans when. If we don't provide access to the content of plans now, we probably need to readjust that again.

**Comment by stephaniesimms** [comment]
sorry, i got confused. @sjDCC is correct that yes, we do want to make the plan name a link to enable org admins to open & read the plan. per our discussion on the check-in call, we need to create an exception in the code that enables admins to see plan content but not comment or perform any actions (a true read-only access w/no commenting privileges). admins should only have the ability to provide comments when a plan owner has requested feedback.

**Comment by briri** [comment]
ok. Made the plan title clickable and updated the plan so that a super admin or an org admin (org admin must belong to the owner or one of the co-owners orgs ... so if I created and @sjDCC was a co-owner an org admin from either UCOP or DCC would be able to read it). Let me know if that is what we want to do here.
Also updated the comments section so that I am unable to edit/remove my own notes if the plan is no longer shared with me and is not in the feedback review process.
![screen shot 2017-12-06 at 2 05 16 pm](https://user-images.githubusercontent.com/1204467/33688039-fe094bfa-da8e-11e7-876e-8c34607bfd50.png)

**Comment by stephaniesimms** [comment]
@briri everything looks good except one thing. as an admin, when I click the link on my notifications dashboard to open the plan and then navigate to the Write plan page I get the error below. expected behavior is to be able to open the plan in read only mode and leave comments.

![screen shot 2017-12-11 at 3 51 51 pm](https://user-images.githubusercontent.com/12703638/33860033-91c4f48e-de8b-11e7-8e46-85d4018a0ccd.png)

**Comment by briri** [comment]
should be fixed by #940

**Comment by stephaniesimms** [comment]
error is fixed and entire comments/feedback process works as expected now. closing issue.
