### ISSUE TITLE
Create cover page for Public DMPs PDFs

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#436]
Related issue #300 
DMPs that appear in the Public DMPs list should include a copyright statement on the cover sheet (statement below copied from DMPTool public DMPs cover sheet):

Copyright information: The above plan creator(s) have agreed that others may use
as much of the text of this plan as they would like in their own plans, and customize
it as necessary. You do not need to credit the creators as the source of the
language used, but using any of their plan's text does not imply that the creator(s)
endorse, or have any relationship to, your project or proposal.

**Comment by xsrust** [comment]
The above text has been previously added to the public dmp export.

The default admin-details section has been removed according to comments in #492 .

@sjDCC @stephaniesimms, Which admin details, and what information(other than the above) should be included on the coverpage for the public PDF export?

**Comment by sjDCC** [comment]
@stephaniesimms is out at a wedding til next so week so I suggest we just go with the existing DMPTool model for now. I've included a screengrab below, but you can see other examples at: https://dmptool.org/public_dmps

![public-dmp-cover-page](https://user-images.githubusercontent.com/6169940/28420220-58d23e32-6d59-11e7-85c4-2c7e0bfb68a2.PNG)

So I figure we need to include:
- Title
- Plan creator + co-owners (if any)
- Institution (from controlled dropdown list OR value from 'other org' field, OR 'Non Partner Institution' for US examples where they don't have a name recorded)
- Last modified (@briri does this mean the public DMP is automatically updated / regenerated any time changes are made?)
- Copyright notice (text already added)

I would be inclined to make a couple of additions / changes:
- I'd capitalise DMP in the provenance label to reinforce the acronym i.e. 'A Data Management Plan created using {TOOL_NAME}'
- I'd add the funder if there is one OR record the template name so it's clear what set of requirements it's based on
- I would add grant ID if this field has been completed to help link together outputs
- Possibly include the 'project abstract / plan description' if this has been filled in to give people an overview before reading plan

Build it as per DMPTool for now and @stephaniesimms can confirm preferences on other suggestions later. Thanks @xsrust

**Comment by xsrust** [comment]
For the Affiliation: section, Which institution should be listed? Just that of the creator, or those of all co-owners?

**Comment by sjDCC** [comment]
I would say just that of the creator. What do you think @stephaniesimms

**Comment by stephaniesimms** [comment]
@sjDCC and @xsrust - I agree that just the creator's affiliation should be listed.

and sarah's suggestions so far are all fine w/me. this issue got ahead of me in that i wanted to do some quick research on accessible PDFs (which are apparently a thing) and make sure we're compliant. i think it mainly has to do w/the file format itself. i also agree that we should put some thought into the layout and content for project details on the main cover page since we want to think about this as the "Minimum Viable Metadata" for a project and the baseline info for machine-actionable DMPs. 

ideally you can go ahead and build the functionality now @xsrust. then @sjDCC and i can tinker w/the content and formatting and apply it to all exported PDFs (public as well as other plans) in the next week or two as a separate issue.

to address one question above re "last modified": the public DMPs and the exported funder templates are both generated dynamically. @briri can explain how that works in dmptool.

**Comment by xsrust** [comment]
All implimented as-per @sjDCC's suggestions above.
logic behind psudo-code below:
 - if the template creator is a funder, displays "Funder: " and the name of the funding organisation
 - If template creator not a funder, displays "Template: " template_name "Customized by: " org.name
 - If the plan has a grand number/description, these are displayed
```
    <% if @template.org.funder? %>
      <p><%= _("Funder: ") + @template.org.name %></p>   <br>
    <% else %>
      <p><%= _("Template: ") + @template.title + " Customised By: " + @customizer.name %></p><br>
    <% end %>
    <% if @plan.grant_number.present? %>
      <p><%= _("Grant Number: ") + @plan.grant_number %></p> <br>
    <% end %>
    <% if @plan.description.present? %>
      <p><%= _("Description: ") + @plan.description %></p>  <br>
    <% end %>
````

**Comment by sjDCC** [comment]
Thanks @xsrust 

One quick question / comment: Does the 'customised by' string come in if they've added guidance and example answers, or only if they added a custom section with their own questions?

In this context, customised by probably only makes sense to add when there are additional questions not belonging to the main template e.g. Uni X questions added to an ESRC template. Neither the guidance or examples export, so saying something has been customised by may be misleading otherwise.

If we can restrict this to displaying only when there's a custom section / question added, then I would leave it in and also apply to the funder template logic. This is where it's most likely to occur and we agreed to export any custom institutional sections as part of public plans. The only example I can think of for the second scenario is Template = DCC or Default DMP + customiser being any uni

Does that make sense?

**Comment by xsrust** [comment]
Sure, I've restricted it to only templates where an answered, customized, question exists.  

As per the applying it to funder templates, if the `@template.org.funder?`, the template is not customized as funders cannot customize templates.
The `Template <TITLE> Customized By: <ORG>` applies to any customized templates (funder/dcc), any org template.  The `Customized By: <ORG>` will be excluded if there are no customizations

**Comment by briri** [comment]
Found issue after deploying. Seems as though the Pundit policy requires a second argument. The page is open to the public so just removing the policy for now. Submitted in PR 

@xsrust you can add back later if you feel its necessary.
![screen shot 2017-07-27 at 2 48 15 pm](https://user-images.githubusercontent.com/1204467/28693742-214e3830-72db-11e7-9def-79bd1f118d89.png)

**Comment by stephaniesimms** [comment]
closing this issue and transferring formatting changes to #712
