### ISSUE TITLE
Popup when answers are not saved for a section

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#438]
During the process of cleaning up JS files. I have noticed that the popup telling the user that the answers have not been saved, it is not triggered. This popup should be triggered any time a section from a plan is collapsed with answers not saved.

I have checked this behaviour on the live service and although the popup appears, there is not text displayed. Do we still want this behaviour? @sjDCC, @stephaniesimms 

Perhaps we can auto-save by triggering a function in a debounced mode. This is less distressing for the user...

**Comment by jollopre** [comment]
Agreed in meeting held 20-06-2017 that we should implement an auto-save functionality.

**Comment by stephaniesimms** [comment]
@jollopre thanks for noting that we discussed this and yes please, implement the auto-save. i agree that the pop-up is unnecessary and users are accustomed to auto-save by now. we also talked about implementing auto-save elsewhere in the tool (e.g. for guidance selections) so this should become a consistent practice.

**Comment by jollopre** [comment]
The auto-saving functionality works as follows:

For each html form in the page, i.e. each question/answer from a plan phase, a function is registered that delays the auto-saving until after 5 seconds of non-consecutive changes made at either its answer or comment.

Note, that auto-saving is robust enough to detect whenever a conflicting answer wants to be auto-saved, so that it cancels that and it is resumed whenever the user explicitly saves her/his changes that resolve the conflict.

**Comment by sjDCC** [comment]
This looks good and is more user friendly. Thanks @jollopre
