### ISSUE TITLE
Organisation vs. Institution - clarify and standardize language

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#441]
I'm confused by "Organisation" vs. "Institution" terminology within the tool; will confer w/ @sjDCC to make sure we clarify what's what and use consistent language; possibly compromise to use term "Affilliation"?

So far we seem to agree that "Institutional credentials" make the most sense to end users (Org creds aren't really a thing). So it follows that a user selects an "Institution" to sign in via this route. But elsewhere we consider Institutions to be a type of Org and instead refer to Org affiliations, Org guidance, etc. 

Org is more inclusive to encompass funders, disciplinary orgs and data centers, etc. But for end users it might make more sense to just stick with "Institution" since that's the term that is most familiar to them.

I'm happy to be convinced either way, but right now it's confusing.

**Comment by stephaniesimms** [comment]
per discussion w/ @sjDCC on 22 Jun we agreed to refer to "Institutions" in the plan interface (e.g., institutional credentials, institutional visibility, etc). 

TBD on the admin side of things. there it might make sense to retain the concept of an Institution as a type of Org. For now I'll move this off the project board and keep in a holding position to reassess at a later date.

**Comment by stephaniesimms** [comment]
flip-flopping on the previous decision after deeper consideration of future machine-actionable use cases and integrations. i think it's better to retain Org throughout the tool (as you currently have in DMPonline) and just be careful and clear with language about "institutional credentials." 

i would prefer to keep Org and test w/DMPTool users. if they're not confused by it we can expand the notion of Orgs to include disciplinary communities, etc.

@briri @JEK-III @rhu001 @sjDCC if you're all in agreement, please standardize wireframes and language in UI to refer to "Organisation" (e.g., visibility, etc). the one exception is where we need to refer to "institutional credentials" (profile page, sign in).

**Comment by sjDCC** [comment]
Sure, I'm happy either way. I don't think any of these changes had worked into current code yet, but just pinging @vyruss here to make sure we hadn't done any replacement of 'Organisation' with the term 'Institution' If so, revert back ;-)

**Comment by vyruss** [comment]
Haven't changed anything yet.

**Comment by sjDCC** [comment]
Went for org across board so closing out
