### ISSUE TITLE
Global email notifications update

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#442]
related issue #146 
https://docs.google.com/document/d/1Zt3QfPZ2q6yMOCVFOevXviwRX-XbZeGSxAAvbRa9w-M/edit

Google doc contains complete list of email notifications:
- 2 from devise gem
- existing email text
- new email text to add

Some are implicated in related issue above, but all need to be updated with revised and standardized text in doc. One exception is Recover account email - workflow for this is not yet resolved and so neither is email text.

Create separate issues for the following email notices (at end of doc):
- CUSTOMIZABLE NOTICE WHEN USER REQUESTS FEEDBACK ON A PLAN
- FUNDER TEMPLATE UPDATED

**Comment by stephaniesimms** [comment]
Welcome email text is missing the contact email (blank in screenshot below):

![screen shot 2017-06-19 at 1 24 05 pm](https://user-images.githubusercontent.com/12703638/27304347-9d2eb4d6-54f2-11e7-97fd-3ec80ff6e6c7.png)

**Comment by vyruss** [comment]
@stephaniesimms it needs `application.email` to be filled in in `branding.yml` to display the correct email.

**Comment by briri** [comment]
let me know what email I should use @stephaniesimms

**Comment by stephaniesimms** [comment]
for DMPTool service we should use uc3@ucop.edu
for DMPRoadmap i think it's currently set up for the dmponline helpdesk. @sjDCC mentioned elsewhere that we might create something new for Roadmap. i don't have strong opinions one way or another.

**Comment by sjDCC** [comment]
I think it's worth us having a generic DMPRoadmap email for code queries or to use in cases like this. That way we're both kept informed.

**Comment by stephaniesimms** [comment]
I just recalled that we set up a roadmap project email list a year ago and haven't really used it. we could repurpose it here if all are amenable?
ROADMAP-L@listserv.ucop.edu

**Comment by stephaniesimms** [comment]
closing this issue to replace with #731 . new email text will be incorporated into relevant issues for new features.
