### ISSUE TITLE
Text box when answering questions is now a static size - it should grow or have options to drag it bigger

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#448]
This issue was reported by the Finns but applies to the main codebase
![text-area](https://user-images.githubusercontent.com/6169940/27435901-6e955548-5755-11e7-8dd5-658937e088a6.png)

**Comment by xsrust** [comment]
tinymce supports this, just a 1 liner to enable.
We can change the bottom padding, but I've reduced it from the example you see on the left as this was a lot of un-used whitespace

**Comment by sjDCC** [comment]
Excellent, thanks Sam. Let me know when deployed and I can test

**Comment by sjDCC** [comment]
This formats really weirdly now. Esentially the text doesn't wrap and the box just gets a secondary scroll bar.
![capture](https://user-images.githubusercontent.com/6169940/27448386-8ea9dc9c-577c-11e7-8315-00de3b4fb407.PNG)

The way we had it before made it bigger down the way. Can we reinstate that, as in the Tuuli screengrab?

**Comment by xsrust** [comment]
That's odd.  I'm not seeing the 2nd scroll bar unless the text is within a table.
Word wrap seems to be functioning fine
![tinymce](https://user-images.githubusercontent.com/7352616/27455536-8975425c-5795-11e7-8c0c-05be0bdcb162.jpg)

**Comment by sjDCC** [comment]
Just done some more tests and I think this is a browser issue. I assume you were on Safari which is fine. I tried it on Chrome and wrap worked fine. The two that don't work are firefox (screengrab 1) and IE (screengrab 2)
![capture](https://user-images.githubusercontent.com/6169940/27471402-9da7ca92-57ef-11e7-89c0-ca02df2d0cac.PNG)
![ie-no-wrap](https://user-images.githubusercontent.com/6169940/27471408-a66271aa-57ef-11e7-8a47-f118d4def438.PNG)

**Comment by vyruss** [comment]
@sjDCC to be honest nobody should be typing such long lines in their questions :) But if they do, it's a way to make them realise what they're doing? ;)

**Comment by xsrust** [comment]
Ahh, thanks.  I was on Chrome but i'll look into incompatabilities with the tinymce's autoresize gem and firefox/ie.

**Comment by sjDCC** [comment]
Retested and this is definitely a user test error. If there are spaces between words then it wraps fine and the box grows down the way. Users won't ever be entering text like I was so safe to close out. No work needed @xsrust
