### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#452]
@sjDCC , @stephaniesimms :
GitHub suggests adding a Code of Conduct to our project. I'm pretty sure the GitHub project ranking algorithm is affected by this so I think it's best we adopt one for optimum project visibility/discoverability. The template they suggest using is the following:

https://github.com/DMPRoadmap/roadmap/community/code-of-conduct/new?template=contributor-covenant

**Comment by sjDCC** [comment]
Yeah, I'm happy to include a code of conduct. Good to get that in place before the MVP release as that's when we'll be encouraging others to contribute. Maybe add to Tuesday call for other comments?

The contact email in here reminds me that we should setup a DMPRoadmap email that feeds through to our two helpdesks. When I was editing the pootle page on wiki the other day I just added dmponline@dcc.ac.uk but I think it would be good to have a generic one that covers both teams

**Comment by stephaniesimms** [comment]
fine by me too. just to clarify @sjDCC - are you referring to the larger roadmap MVP release? if you want it in time for your v0.3 release i just want to note that we have a holiday next Tues and would need to work on it via other comms.

**Comment by sjDCC** [comment]
I think the main release in August is fine schedule wise as that's when we'll be opening it up to the world and encouraging other devs to migrate and join with us. The only ones who are likely to migrate sooner are Weiwei and Benjamin as test cases and we're already liaising with them so less need for a code of conduct

**Comment by stephaniesimms** [comment]
still need to update Contact email and verify that this is ready to go

**Comment by sjDCC** [comment]
I think the ROADMAP-L@listserv can only be posted to by members (seem to recall we had a helpdesk issue about this as we'd forgotten to switch out details). Happy for DMPonline@dcc.ac.uk to be used, or we could have a mail address that alerts both helpdesks if desired?

**Comment by stephaniesimms** [comment]
yes, you're right about posting to ROADMAP-L listserv @sjDCC 
it would be great to alert both helpdesks to jive with our current workflows. i guess we can just include both email addresses in the Code? if that's messy we can just use dmponline@dcc.ac.uk

**Comment by sjDCC** [comment]
Or setup a mailbox like dmproadmap@dcc.ac.uk that directs to both?

**Comment by stephaniesimms** [comment]
i'd say go ahead with dmponline@dcc.ac.uk rather than complicate things
we can always confer about code of conduct stuff as needed

**Comment by sjDCC** [comment]
Have just added dmponline@dcc.ac.uk for now as I couldn't find an email for your helpdesk (just webform). By all means add it through and resend PR

**Comment by stephaniesimms** [comment]
one email address should be sufficient and we can consult on any queries that come through together. PR looks good to me. closing issue.
