### ISSUE TITLE
Create account: view issues

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#455]
The French flagged a few items here, and I noticed that we've lost the other org field:

- The x doesn’t clear your choice of organisation although you can switch it by selecting another. Perhaps remove the x or make sure it clears the choice?

- ‘Other’ used to be top of the list for visibility. Reinstate it here?
 
- If ‘other’ is picked or the user clicks the ‘my org is not listed’ link, they are no longer given a box to enter the name of the organisation. I would prefer that we reinstate this. @stephaniesimms  was there a reason to take it out or are you happy to capture org name too?

- When you click the ‘my org is not listed’ link, the boxes overlap. Ideally the white space would be retained.

![create-account-view-issues](https://user-images.githubusercontent.com/6169940/27515855-732258e8-59a5-11e7-85b8-bf69a5c47205.png)

**Comment by stephaniesimms** [comment]
- Brian checked and "Other" still exists in the database so it shouldn't be a problem to reinstate
- None of the new Sign in/Create account workflow changes that Brian is working on have been implemented yet, except for the language (Sign Up > Create account) so we're not sure how/when these changes came to pass
- we still need to meet @sjDCC to discuss how new workflows should work, but whatever suits your needs is fine in the interim
-we want to be sure that users w/SSO option are finding that route so prefer to foreground the Sign in with Institution button somehow, but can discuss options

**Comment by sjDCC** [comment]
Other isn't top of the list, but otherwise all looks good. The 'my org is not listed' link is sufficient for people to find an alternative so closing out.
