### ISSUE TITLE
Create plan: better error messaging needed

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#457]
Users often get confused on the create plan page as they start to type the org or funder and then may complete their typing rather than selecting an actual term from the dropdown list. Can we:
a) Highlight the field which is incorrect and preventing plan creation , advising the user to select an entry from the dropdown list instead
b) Disallow typed entries to be saved, if possible

![create-plan-user-error](https://user-images.githubusercontent.com/6169940/27515870-d6d605ec-59a5-11e7-8af1-494f79c49774.png)

**Comment by xsrust** [comment]
@sjDCC Having gone through the MVP board, can you advise if this work is needed now, or if it is covered within the better error messaging/create plan workflow changes being implemented by CDL?

**Comment by sjDCC** [comment]
I don't know. @stephaniesimms can you advise? will move it to overall MVP board anyhow and we can either address there or close out

**Comment by briri** [comment]
I've updated the MVP codebase to display an error if the user hasn't selected an item from the list.
How does this text look @sjDCC? 

![screen shot 2017-06-29 at 9 55 03 am](https://user-images.githubusercontent.com/1204467/27700037-34ff313a-5cb1-11e7-9640-9e25a32a1676.png)

The position and styling of the messages will change once we decide on a standard approach to displaying error messages

**Comment by stephaniesimms** [comment]
@briri @sjDCC I think the addition of this error message solves part of the issue - we can optimize styling later to make it crystal clear to users.

the part that remains to be solved is that many users are going to input abbreviations for both Org and Funder fields. we either need to add abbreviated names to the name field or provide guidance about typing out the full name.

I can already attest to the fact that it's annoying to have to type out "University of C..." before i find my institution in the list. It would be nicer if I could just type "UCOP." But maybe this would all get wiped out when we implement FundRef and Org IDs..?

**Comment by briri** [comment]
Yes, we'd need to manually add the acronyms to the existing names in order for users to be able to find them that way. 
These new boxes though search the entire string so typing 'Cali' will find 'University of California'

**Comment by sjDCC** [comment]
Super, I hadn't seen this error message @briri. Yes, please do apply it so we can add to live code. It seems to be a pretty common user error so we may need to add more usability fixes/prompts in future.

@stephaniesimms Yes, I agree, it's really annoying to have to type out full name not acronym and is not typical user behaviour. I've fixed this for our funders by adding their acronyms in brackets at end of org name. We should probably do the same for unis e.g. "University of California (UCOP)" Like @briri says, this will be found with Cali, but most people will type ucop so it'll drop from the list straight after the U currently. Its should be less of a concern as user's org field will autofill based on edit profile value so they'll be searching for this far less than funder names. Would definitely recommend you have acronyms on all your funders pre-deployment though

**Comment by stephaniesimms** [comment]
Yes, I plan to manually add the abbreviated funder names and probably also Org names for now. We can reassess when it comes time for FundRef integration. DMPTool users have even reported trouble finding the correct template when the entire list is visible, e.g., looking for NASA but the template is called "National Aeronautics and Space Administration"

**Comment by briri** [comment]
related to #175

**Comment by briri** [comment]
closing this as its related to and now covered by #408
