### ISSUE TITLE
Bullets are not displayed

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#458]
This seems to affect various sections of the template as noted in the below screengrabs. These are:

- Template details
- Phase description
- Question (in preview on screengrab 1 and in reality in screengrab 2)
- Section description
- Example answers

They only seem to display correctly in guidance and the main answer box

![missing-bullets-1](https://user-images.githubusercontent.com/6169940/27515891-2a601b62-59a6-11e7-9d59-acaaa609f9c7.PNG)
![missing-bullets-2](https://user-images.githubusercontent.com/6169940/27515893-2b710f16-59a6-11e7-8908-22d20b901036.PNG)

**Comment by xsrust** [comment]
It seems that TinyMCE's bullet option simply creates a `<ul><li></li></ul>`.  With no additional styling, these will not appear as a bulleted list outside of the editor, which applies it's own styling.

**Comment by xsrust** [comment]
Possibly related to #464

**Comment by xsrust** [comment]
This should be fixed as long as the bullet options circle disc or square are selected.  This will mean that all templates(and answers) with bullets will need to be updated with this option and saved.

**Comment by sjDCC** [comment]
Is there any way to run a query to apply this change or do we have to ask individual admins to do it?

**Comment by sjDCC** [comment]
Just tested and this works well enough so closing out. The admin preview could look better in terms of alignment, and I guess 'disc' bullets are the original ones from TinyMCE as these don't display on front end. Ideally we'd disable them if that's the case but can add guidance to suggest people don't use them.

![preview-admin](https://user-images.githubusercontent.com/6169940/27699437-325611c4-5cf2-11e7-97e9-aae514826fac.PNG)
![bullets-front-end](https://user-images.githubusercontent.com/6169940/27699443-37999c28-5cf2-11e7-96a7-ad869bd5815e.PNG)
