### ISSUE TITLE
Error saving guidance associated with an institutional template

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#460]
Testers at Inist CNRS have had an issue with saving guidance. They were presented with an error message that the guidance couldn’t be saved because “annotations.org could not be blank”. They were updating their own template. I’ve only managed to replicate this on that particular template and that particular phase (DMP_Inist_Test_20170620 – phase 1). Adding or editing existing questions elsewhere seems to work fine. Perhaps this is down to testing being done when servers were in flux or something has gone wrong data wise with that template?

![annotations-warning](https://user-images.githubusercontent.com/6169940/27515908-6afbf524-59a6-11e7-9e0d-8131b3135597.png)

**Comment by xsrust** [comment]
I cant seem to find this template on DMPonline.  Did this crop up from test?
On this template on -test, I still cannot reproduce.  can you advise what section/question was saved to generate this?

**Comment by sjDCC** [comment]
Yes this is on the test site for Inist CNRS. Have added screengrab with URL in case that helps.
![test-inist-cnrs](https://user-images.githubusercontent.com/6169940/27535466-d8edc6d6-5a62-11e7-8a93-cdc92c6f9699.PNG)

Just tried again to add guidance under section 2 "Description des données" on q3 which has no guidance. Same error message occurred. I haven't seen it anywhere else so may be an issue with this template or this org.

**Comment by xsrust** [comment]
Looks like this was an error on the logic for the controller to update questions.  theirs was just an edge case.

**Comment by sjDCC** [comment]
Working now. Closing out.
