### ISSUE TITLE
Institutional custom section on a funder template: enable this to display in 1st position

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#463]
Manchester uni raised an issue about their custom section display. They’d like to place this in the first position on all templates but it doesn’t seem possible to do that consistently. Sometimes the admin interface displays it there but the front end doesn’t or vice versa. There is also one case where their custom section isn’t displaying at all despite being published.

I’ve gone through all their customisation data and summarised what’s happening below:
**Admin interface**
- 8 templates are showing as having the University of Manchester section as 1st position. These are: BBSRC, EPSRC, ESRC, H2020, NSF, Population Research Committee, STFC, Wellcome Trust
- 4 templates are showing as having the University of Manchester section as 2nd position. These are: AHRC, MRC, NERC & CRUK

**Front end – user interface**
The UoM section displays on all bar the Population Research Committee template. This is a secondary template for Cancer Research UK. Other than that, there’s nothing different about it and the customisation is showing as published so it’s unclear why it’s not displaying.
The position of the UoM section varies and is not consistent with what shows on the admin view. Here are the discrepancies:
- H2020 template suggests 1st position on admin side but displays second to end users
- STFC template suggests 1st position on admin side but displays second to end users
- Wellcome Trust suggests 1st position on admin side but displays as final section to end users
- AHRC, NERC & CRUK all suggest the UoM section is in second position on admin side but it displays first where they want it…

So it does seem possible to get the Uni section in first position, but I don’t know how we can make that consistent. Perhaps this is a data issue?

**Comment by xsrust** [comment]
@sjDCC would allowing customizers to have a section with order of display = 0 be a sufficient solution?  This would allow them to always set their section to come first.  Template owners would have their section numbers start at 1 so there should be no confusion.

**Comment by sjDCC** [comment]
Yes, I think that would work. Currently the dropdown for ordering sections starts at 1.

Only thing to watch is that if we re-start the ordering from 0, we don't want any newly added funder templates to have their sections ordered from 0 too. This should be reserved for customisations. Hope that makes sense!

**Comment by xsrust** [comment]
Yes, that makes perfect sense. Only customizers will be able to reduce a section number to 0, they will start at 1 on own templates.

**Comment by sjDCC** [comment]
Perfect, looks great. Will let Manchester know this is fixed
