### ISSUE TITLE
Formatting issues in docx export

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#464]
The Finns have noted that tables aren’t showing gridlines in docx. See example below from a NERC template.
![word-export-formatting](https://user-images.githubusercontent.com/6169940/27515973-9b942430-59a7-11e7-8768-85e52f915889.PNG)
Bullets are also replaced with symbol marks and the overall layout is a bit odd and unlike pdf e.g. questions are inset

**Comment by xsrust** [comment]
For the table export, The fix I added will only work on new tables to give them a default of having a border.  For old tables, Users will need to go to Table properties and set Border to 1 to enable table borders. 

I am investigating the cause of bullet display, but likely this is a styling issue with the user content.

**Comment by xsrust** [comment]
With Bullet option for square or disc added, and newly generated tables, or tables with border=1, this functionality should be working.
![screen shot 2017-06-26 at 1 44 17 pm](https://user-images.githubusercontent.com/7352616/27539790-bb94bf96-5a75-11e7-8730-92b18d4f653b.png)

**Comment by xsrust** [comment]
As for questions being inset, this is because question writers are including a `<p> </p>` around their questions text, or it is added by tinymce when the question is saved

**Comment by vyruss** [comment]
@xsrust bulletted lists are indented by default nearly everywhere

**Comment by sjDCC** [comment]
Looks much better - thanks @xsrust. Closing out
