### ISSUE TITLE
Inconsistencies in error message / notification display

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#475]
We seem to be placing error messages in different places. Mostly they're at the top right now, but when testing mandatory first name / last name, the error came up next to the save button
![message-bar](https://user-images.githubusercontent.com/6169940/27614921-858b66de-5b9c-11e7-9c62-3a7a91bb8f90.PNG)
![warning](https://user-images.githubusercontent.com/6169940/27614922-86819b30-5b9c-11e7-917a-7dcaea557089.PNG)

I preferred it when we used colours to differentiate notifications from warnings too. The tick and cross makes it less obvious to me whether I'm being told something good or bad. Can we colour them again. We may want to think about sizing too so they're not missed.

**Comment by vyruss** [comment]
Agreed about colours which I miss too, generally UX guidance says we should not *rely* on colours to convey the message/intent, but it doesn't say that there shouldn't be any - unless of course they are garish/distracting/low contrast :)

**Comment by briri** [comment]
error/info message placement and colors are in the process of being standardized with the overall accessibility work and css redesign. We should be able to change the coloring and placement now with just a few lines of css code that will update them globally.
related to #175

**Comment by briri** [comment]
closing this now that #175 has closed
