### ISSUE TITLE
Define Organisation <-> User relationship through user table

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#48]
Currently, the relationship between an organisation and it's various users is defined through the User_org_roles table.  We would like this relationship to be defined through the organisation_id field of the User table.  This means we need to:
- [ ] change the data access to reflect the new relationship path (in both models and views)
- [ ] ensure any logic for this relationship(as it was complex before) is removed from views
- [ ] create a function to convert our data from the old system to the new system
- [ ] include above function in the migration which removes user_org_roles table

**Comment by briri** [comment]
Hey @xsrust I did some work on this front from an abandoned branch a while ago that was also an attempt to introduce some unit testing (I think before you had gone through and added your unit tests). Feel free to use any of it if it makes sense:
https://github.com/DMPRoadmap/roadmap/compare/master...CDLUC3:refactor-models-and-unit-tests
