### ISSUE TITLE
Move users.prefs to a separate table

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#481]
Move the existing `users.prefs` column into a separate table. The data should be stored as a JSON string. The site runs queries against the users table for every request. Moving this data to a join table will prevent it from being loaded unless needed.

We should also update the logic so that its only storing deviations from the default preferences.

related to: #146

**Comment by xsrust** [comment]
- New Prefs table is created
- Users have_one Pref; Prefs belong_to User
- Existing prefs stored under `user.pref.settings[:email]`
- New types of prefs can be stored in `user.pref.settings[:key]`, e.g export preferences
- Users will not have a pref until they manually save a change from the default. (i.e. ensure you check for nil, or use the helper function `get_preferences(key)` in user to access them.

**Comment by xsrust** [comment]
This Work will require the following actions before it can be deployed:
- Rake db:migrate 
- Updating branding.yml to follow the pattern of example_branding.yml

**Comment by stephaniesimms** [comment]
Closing this as there doesn't seem to be anything to test in the UI
