### ISSUE TITLE
Allow admins to configure default plan visibility for their Org

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#485]
Noting here that @sjDCC received a request to allow admins to configure the default visibility setting for plans created by users at their Org. UK unis are interested in making the default "Organisational." Based on US/DMPTool admin feedback we will go with "Private" as default visibility for MVP. 

Future enhancement: make this a setting in the admin area.

**Comment by briri** [comment]
default visibility is stored in the app's config. We could simply add a column to the org table to store their selection. Default it to 'private' and remove the config variable

**Comment by magdalenadrafiova** [comment]
@pherterich @mariapraetzellis I think this needs to stay to be a decision of the users due to our terms and conditions and I am suggesting to close this issue (?) 
Users can currently select whether the plan is private, public or org. view

**Comment by pherterich** [comment]
Would agree and close this for now. If that gets raised again, we can always open a new issue 😄
