### ISSUE TITLE
Error generating Public DMP export for plans with multiple phases

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#492]
The current `public_export` method in the plans_controller generates an error if you try to export a plan whose template has multiple phases (e.g. Horizon2020 - see "Jose's Plan" on roadmap-stg). The method attempts to loop through the phases and generate a pdf for each one which results in the following error from the controller:
` AbstractController::DoubleRenderError in PlansController#public_export `

@sjDCC @stephaniesimms How do we want to handle the export of a public DMP with multiple phases (e.g. Horizon2020)? The plan export for logged in users allows them to select which phase they want to export and a PDF is generated for a specific phase. The public DMPs page though doesn't currently offer this. Do we want to just generate one PDF that contains all phases?

related to #84

**Comment by stephaniesimms** [comment]
For multi-phase templates the visibility setting should apply to all phases (we can add messaging to make this clear). So it makes sense to me that we would provide a single PDF that contains all completed phases in the public DMPs list. @sjDCC what do you think?

**Comment by sjDCC** [comment]
Yes, I think if there is more than 1 completed phase we should include them all in public DMP. 

When funders ask the same questions at each phase (i.e. when it's more a case of different versions of the same thing / an evolving, living plan) we may  want a different approach, but we can review this when we add proper versioning post MVP. For now these examples (e.g. H2020) are represented as phases too.

**Comment by xsrust** [comment]
@sjDCC @stephaniesimms You've both mentioned that all 'completed' phases should be exported.  As far as I know, we dont have any way to track what the user has and hasn't completed other than checking what they have answered.  Should the default behavior be to export all phases, or only those with answered questions?

Also, given the rework of Downloads in #498, What settings apply to public DMP export.  i.e. should we export questions as headings, do we export unanswered questions with the text "question unanswered" for the answer, Do we export the project details, and should we export customized sections?

**Comment by sjDCC** [comment]
Like you say, there's not currently a marker or flag of completeness, and I think the progress bar is an accumulation of all questions over all phases so that's not a useful indication either... 

With that in mind, I would only export phases with answered questions (not automatically all phases) and would apply the following settings:
- do not include plan details as some of these will be added on the cover page #436 
- export section headings and questions (when answered)
- don't export unanswered questions if they can be easily filtered out
- do include cutomised sections since this is a public DMP not response to funder

What do you think @stephaniesimms?

**Comment by stephaniesimms** [comment]
we do still have an open question regarding how to define plan completeness, especially for adding things to the Public DMPs list #87 (e.g., ideas include only adding plans that have some percentage of questions answered). 

for this issue, @sjDCC 's proposal sounds good to me. let's try it and see.

**Comment by sjDCC** [comment]
Yes, I think we can start with a binary value. If a phase has some questions answered then lets export it. In future we may want to apply a percentage (e.g. 70 or 80% answered), or status indicators could help if we introduce them.

**Comment by stephaniesimms** [comment]
Tested a variety of export formats and phases and this appears to be working as expected. Noted a related bug #541 for tab display names on plan writing pages. Closing this issue.
