### ISSUE TITLE
Revise Share plan page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#497]
UX wireframe @JEK-III - http://h90c3m.axshare.com/#g=1&p=write_plan
Related issues for other write plan tabs #494 #495 

- Add plan visibility settings to top of page; blue notepad mentions outstanding need to determine threshold for adding "public" and "org" DMPs to list - TBD
- Revise Manage collaborators table
- Revise Invite collaborators section

**Comment by briri** [comment]
The plan visibility section should be copied over from the edit plan details page. This section should be disabled if `plan.is_test?`.

**Comment by briri** [comment]
Just need to wire up the JS logic for the visibility section. 

![screen shot 2017-07-11 at 3 59 57 pm](https://user-images.githubusercontent.com/1204467/28094533-13d2042e-6652-11e7-9270-90cf8ee5f4d5.png)

**Comment by stephaniesimms** [comment]
Functionality works as expected w/exception of related issue #516 for test plans

@JEK-III please confirm or add to the list of style changes:
- Remove boldface for field names
- Remove colons for field names
- Align everything on this page w/the "Add collaborator" button at the bottom (so all headings, text, table should shift to the right
- Font size for headings should be smaller (refer to wireframes)

**Comment by sjDCC** [comment]
There are still colons when sharing a plan but I guess these may be addressed as part of global styling so safe to close out here?

I also wonder if we should change 'Read Only' to lower case 'o' since that seems to be our norm elsewhere

Page looking good though

![capture](https://user-images.githubusercontent.com/6169940/28475524-8493d8e6-6e44-11e7-8557-d7a8116227ab.PNG)

**Comment by stephaniesimms** [comment]
I concur w/ @sjDCC suggestions above re 
- removing boldface and colons 
- and changing to "Read only"

These are documented in the general styling ticket so maybe only the second item needs to be addressed here.

**Comment by stephaniesimms** [comment]
@JEK-III and @briri - please update wireframe and application to say "Read only"

@briri - align all elements on this page per wireframe (to the inner rule established by the radio buttons and Email box below) 

![screen shot 2017-07-27 at 10 44 13 am](https://user-images.githubusercontent.com/12703638/28684263-9cfa1fd0-72b8-11e7-9529-8ebd53433e86.png)

**Comment by briri** [comment]
Need to change the logic of when the visibility section is enabled. We are now requiring that 50% of the plan's questions have an answer before allowing that section to be enabled. See the new Help documentation for details: https://docs.google.com/document/d/12MH0c8ow1gQ8_tvE1T02DUYYEys6gaMiEF_hmaLxyQY/edit#heading=h.vre1agcio86y

**Comment by briri** [comment]
closing. work was completed prior to Bootstrap
