### ISSUE TITLE
reCAPTCHA needs integration with the contact_us form

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#501]
We use reCAPTCHA and contact_us gems for the contact_us form however integrating them seems rather cumbersome and currently does NOT work.

reCAPTCHA gem integrates with Rails controllers by invoking verify_recaptcha (see https://github.com/ambethia/recaptcha#rails-installation) however we can't integrate that with contact_us (another gem) unless we modify that gem.

An investigation about how google's reCAPTCHA works (https://developers.google.com/recaptcha/intro) should help us to determine whether or not we should remove the Ruby gem and use directly that library instead.

**Comment by briri** [comment]
I agree with you we should remove the contact_us gem entirely. It would be a pretty simple form to implement and we would then not have to worry about the interaction between the two.

**Comment by vyruss** [comment]
@jollopre what do you mean by "does not work" on master or development? It appears to work on the live services.

**Comment by jollopre** [comment]
@vyruss I mean that although reCAPTCHA works in isolation, it is not needed to confirm that you are not a robot in order to send a form with data to the server.
That's mainly because the verification of the reCAPTCHA is not done in the controller...

**Comment by briri** [comment]
removing this from the board since its included now in v1.0.4
