### ISSUE TITLE
Shibboleth broken on dev and stage

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#510]
Shib stopped working on both dev and stage (error messages below). On stage I get the error immediately after selecting UCOP from the list of institutions. I can still sign in without Shib using the default password, but it seems strange that I'm able to do so when my profile is linked to Shib...

On dev I am taken to the UCOP Shib page, input my credentials, and then it throws the error below.

Stage error
![shib-error-stage](https://user-images.githubusercontent.com/12703638/28139016-918e36d4-6707-11e7-9c16-c4f61c1603cf.png)

Dev error
![shib-error-dev](https://user-images.githubusercontent.com/12703638/28139025-9b5abf5c-6707-11e7-924b-367a02c632fc.png)

**Comment by briri** [comment]
for some reason shibd was not running on either server. Started it back up manually. 

shibd is in /etc/init.d so it should be starting up automatically on restart. Will check after the next deploy to make sure its not going down as part of the deployment.

**Comment by stephaniesimms** [comment]
all good now. thanks @briri !

**Comment by vyruss** [comment]
@briri shibd has the unfortunate tendency to crash! Make sure that you allocate at least 1GB of RAM for the Shib metadata on top of everything else running in the server to make crashing less likely.

**Comment by jimvanderveen** [comment]
shibd wasn't in system startup on roadmap-stg. (It had been pending on getting shibboleth setup finalized.) I've submitted a ticket to IAS to set that up for us. Shibboleth shutdown happened right before the system was rebooted yesterday morning, so I'm pretty sure the problem is solved on stage.
