### ISSUE TITLE
Removing "test" flag should enable normal plan visibility settings

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#516]
When I uncheck the box for "test" plan on the Project details page and click Save I would expect to be able to set the visibility and treat it as a normal plan. But when I navigate to the Share page, visibility settings remain grayed out (screenshots below)

![screen shot 2017-07-18 at 1 19 44 pm](https://user-images.githubusercontent.com/12703638/28338044-749f9b08-6bbc-11e7-991e-06587c84ea2a.png)

![screen shot 2017-07-18 at 1 27 04 pm](https://user-images.githubusercontent.com/12703638/28338145-d59e9684-6bbc-11e7-9e26-21efc561e952.png)

**Comment by briri** [comment]
does the plan have answers? I added a check to correspond to the messaging. Its not the best test of whether a plan is legitimate or not since you could just type 'test' into the answer and save it

**Comment by stephaniesimms** [comment]
ah, now I see that I have to answer at least one question. so this isn't a bug but a matter of messaging. i think it should be fine to wait and test this later. will close for now.
