### ISSUE TITLE
Provide organizational DMPs in My Dashboard list 

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#517]
Related issue #84 for
My Organization's DMPs...

In DMPTool currently, when a user is logged into the tool, the Public DMPs page includes an additional table below the main list of Public DMPs with Organizational DMPs. These are all the plans marked w/Org visibility if the user has an Org affiliation (screenshot below from DMPTool). We want to make it easier for users to find these sample plans and asked for UX input on adding them to the My Dashboard area.

The use case is to provide access to more sample plans. The table can be the same as for Public DMPs w/downloadable PDFs. Many users are more comfortable sharing plans within their institution than with the whole world (Org vs. public visibility).

Another related, separate issue will provide Org admins with a list of all plans (all visibility settings) created by users at their Org somewhere in the Admin area.

![screen shot 2017-07-18 at 2 40 54 pm](https://user-images.githubusercontent.com/12703638/28341147-3aec7e7a-6bc7-11e7-9506-ba41cdfa019d.png)

**Comment by briri** [comment]
Should we place that under the 'My plans' portion of the dashboard page instead or add an institutionalDMPs page? I don't remember if we wanted them to do anything beside download the plans in the new system.

**Comment by stephaniesimms** [comment]
the goal is to provide download access for users at the same Org to consult for samples. the use case is the same as that for public DMPs; this just provides an opportunity for users to share plans within a more restricted circle (not the whole world). i think we should organize it as a public resource page, although only visible when logged in. 

a separate issue will address providing access to institutional plans for Org admins. we want to do this in the Admin area.

**Comment by JEK-III** [comment]
The My Plans wireframe (http://h90c3m.axshare.com/#g=1&p=my_dashboard__plans___ideal) has been updated with an institutional DMP table based on the DMPTool table.

I added an Updated date column because that seems like useful information. I removed the Institution column because all of the plans in the table will be from the same institution.

I removed the Visibility column on the assumption that users in a institution are unlikely to care whether someone else's plan is fully public or limited to their institution. Along those lines, I'd suggest that the table include public plans from that organization in addition to the limited visibility ones.

**Comment by sjDCC** [comment]
One point that got raised when I mentioned institutional visibility in a UK event was whether admins have any way to configure this and put a list of suggested examples plans at top of table. Is this something we could perhaps add (even if post MVP). I guess at the moment it's just an unfiltered list that users can search

**Comment by stephaniesimms** [comment]
we've had requests for this as well and consider it to be a post-MVP top priority @sjDCC . it would be good to open a community discussion now or in the near future to collect more input about how to enable others to curate both the public DMPs and institutional/Org DMP lists.

**Comment by sjDCC** [comment]
Post MVP is good for me @stephaniesimms. Agree it would be good to start discussion now though. Perhaps something to raise in next blog post and then seed via user groups?

**Comment by stephaniesimms** [comment]
replaced by issue #752 . closing this one.
