### ISSUE TITLE
"Save unsuccessful" on Edit Profile page

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#524]
On `roadmap-stg`, I get "Save unsuccessful" on Edit Profile page when I try to change my organisation. The organisation is indeed changed, but the notification is wrong.

**Comment by sjDCC** [comment]
I've just created a ticket that covers this (#533) with screengrabs so am marking this one as duplicate and closing out. If the issue you've uncovered @vyruss isn't covered by mine, then open up again or add to
