### ISSUE TITLE
Revise Org details page to include all branding info

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#525]
Related issue #565 for top banner display
UX wireframe @rhu001 - http://h90c3m.axshare.com/dmp_organizational_profile__admin_view_.html

Make sure all Org branding fields are represented:
- Org full name
- Org abbreviated name (not for display in banner)
- Org URL (e.g., http://cdlib.org/services/uc3)
- Org URL label name  (e.g., UC3)
- Administrator contact email (e.g., uc3@ucop.edu)
- Admin contact email label/name (e.g., UC3)
- Org logo file upload

For plan commenting functionality:
- Button/switch that allows admins to turn on function for users to request comments/feedback on plans
- Text field for admins to create an auto-email message sent to users who request feedback

DMPTool Institutional Info page and branding displayed in banner
![screen shot 2017-08-18 at 10 14 01 am](https://user-images.githubusercontent.com/12703638/29469642-109b73b6-83fe-11e7-8b5f-13b69442f5af.png)

**Comment by stephaniesimms** [comment]
@sjDCC at some point I think we talked about removing the text editor for Top banner text. Is it okay to remove this and just display the Org name in the banner as in DMPTool? also thinking about the proposed tagline "A data management planning tool" that we want to display by default...

**Comment by sjDCC** [comment]
I don't recall that discussion @stephaniesimms, but I'm happy for the 'top banner text' field to go. I'd actually always wanted icons for the RDM webpages and the helpdesk like you have. The only other thing I think people flag in this text is their local RDM policy. Perhaps we could figure out an icon for that, capture the 3 links in text fields under 'org details' and when populated, display them in the header area?

@vyruss, could you pull me the existing data for this field to check my assumption is right please? I'd like to check we're not going to lose anything significant before removing it.

I'm not sure we want to include the institutional name in the header, particularly if we replace the DMPonline / DMPTool logo with the uni logo. It may seem a bit odd in this case. The strapline may make more sense there instead so it's clear what the tool is about

The link to the wireframe is giving a 404 but that would be a good way to mock up different options and and decide

**Comment by vyruss** [comment]
@sjDCC we have 9 institutions with `banner_text`:

| name | banner_text |
|---|---|
| Bath Spa University                                    | <p>Bath Spa University Data Management Planning</p> |
| Manchester Metropolitan University                     | <p>Manchester Metropolitan University provides help on all aspects of Data Management Planning. <a href="mailto:data-space@mmu.ac.uk" target="_blank">Contact us</a>&nbsp;or consult our<a href="http://libguides.mmu.ac.uk/c.php?g=580018&amp;p=4010872" target="_blank"> LibGuide</a> for support.</p> |
| Cape Peninsula University of Technology (South Africa) | <p>&nbsp; Cape Peninsula University of Technology (CPUT) Data Management Plan template</p> |
| University of Birmingham                               | <p>For general guidance, see <a href="https://intranet.birmingham.ac.uk/rdm" target="_blank">our research data management pages</a>.</p><p>In case of questions, contact <a href="mailto:research-data@contacts.bham.ac.uk" target="_blank">research-data@contacts.bham.ac.uk</a></p> |
| Lancaster University                                   | <p>The Guidance you find here is informed by&nbsp;Lancaster University's&nbsp;<a href="http://www.lancaster.ac.uk/library/rdm/policy" target="_blank">Research Data Management Policy</a>.&nbsp;Please also look&nbsp;at our <a href="http://www.lancaster.ac.uk/library/rdm" target="_blank">RDM webpages</a>.</p> |
| London School of Economics and Political Science       | <p>Support for Data Management Plans is provided by LSE Library. Contact <a href="mailto:datalibrary@lse.ac.uk" target="_blank">LSE data library</a> or look at our <a href="https://www.lse.ac.uk/Library/Research-support/Research-Data-Management" target="_blank">Research Data Management at LSE</a>&nbsp;webpages for more information.</p> |
| University of Salford                                  | <p>The University of Salford has a <a href="http://www.salford.ac.uk/__data/assets/pdf_file/0009/674208/ResearchDataManagementPolicy.pdf" target="_blank">Research Data Management Policy</a> and a <a href="http://www.salford.ac.uk/research/research-data-management/" target="_blank">dedicated website</a> with lots of support and guidance. If you have any queries, please <a href="mailto:researchdata@salford.ac.uk" target="_blank">contact us</a></p> |
| University of St Andrews                               | <p>The University provides services to support research data management and sharing. For more information visit the <a href="http://researchdata.wp.st-andrews.ac.uk/" target="_blank">RDM webpages</a> or contact the <a href="mailto:research-data@st-andrews.ac.uk" target="_blank">Research Data team</a>.</p> |
| University of Edinburgh                                | <p>The University has a&nbsp;<a href="http://www.ed.ac.uk/schools-departments/information-services/about/policies-and-regulations/research-data-policy" target="_blank">Research Data Management policy</a>&nbsp;and provides many services to support data&nbsp;management and sharing. See the&nbsp;<a href="http://www.ed.ac.uk/schools-departments/information-services/research-support/data-management/data-management-home" target="_blank">RDM webpages</a>&nbsp;for more information.</p> |

**Comment by briri** [comment]
We're going to need to introduce a new `template_links` table for MVP. That sounds like a good candidate perhaps for the links in your `banner_text` fields. We use it in DMPTool to connect templates with external funder links and sample plans.

You can see some examples on our export template page:
https://dmptool.org/guidance

**Comment by sjDCC** [comment]
Thanks @vyruss. Yes, the data policy is the only other significant thing people are mentioning.

**Comment by stephaniesimms** [comment]
UX wireframe for Org details page now enables admins to provide up to 3 links and names - this should satisfy requirement for data policy field. Need to accommodate the three links in the top banner display for related issue #565

**Comment by stephaniesimms** [comment]
CUSTOMIZABLE NOTICE WHEN USER REQUESTS FEEDBACK ON A PLAN

(Grayed-out example) Email title: [TOOL NAME] Your plan has been submitted for feedback

Hello [USER NAME]

Your plan “[PLAN NAME]” has been submitted for feedback from an administrator at your organization. Someone will respond to your request within 48 hours. If you have questions pertaining to this action, please contact us at [ORG CONTACT EMAIL].

**Comment by stephaniesimms** [comment]
transferred to #726 and #729 - closing UX issue
