### ISSUE TITLE
Two answers saved for single question (Race?)

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#530]
We found 18 instances of duplicate answers for the same question - this shouldn't happen in the code because we update existing answers. [Observed on DMPonline live service.]

**Comment by briri** [comment]
@vyruss do the timestamps on the records indicate that this is something new since the prod release?

**Comment by vyruss** [comment]
@briri yes, it seems to be present in Roadmap code as no such instances exist for migrated answers

**Comment by stephaniesimms** [comment]
I'm not sure how to test this w/o insight into the database. It sounds like @sjDCC should also test on DMPonline to make sure it's resolved?

**Comment by sjDCC** [comment]
I was only aware of 1 case which came through helpdesk but I don't have permissions to view that plan. @vyruss can you advise how this can be UAT-ed please?

**Comment by vyruss** [comment]
Investigated and handled in #798 , closing
