### ISSUE TITLE
Replace "raw" & "html_safe" with "sanitize" for security reasons

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#532]
For security reasons (elimination of XSS attacks) we should replace `raw` & `html_safe` instances with `sanitize` which has very sane defaults out of the box:

https://apidock.com/rails/ActionView/Helpers/SanitizeHelper/sanitize

**Comment by briri** [comment]
So blog posts about how to deal with `html_safe` and `raw`
https://product.reverb.com/stay-safe-while-using-html-safe-in-rails-9e368836fac1
http://www.jasonwieringa.com/Learning-About-XSS-Attacks-in-Rails/

**Comment by vyruss** [comment]
We can call `ActionController::Base.helpers.sanitize(`stuff`)` from within our controllers to process incoming unsafe html.

**Comment by briri** [comment]
Could possible be handled as part of the #826 Ruby upgrade

**Comment by stephaniesimms** [comment]
@briri noted that this may not be relevant after upgrading to Rails 5. will leave open and low priority pending further investigation.

**Comment by sjDCC** [comment]
If this has been done properly we shouldn't notice anything on UAT. Otherwise we may spot a <p> tag

**Comment by stephaniesimms** [comment]
can't UAT but if anything isn't working properly we may see html tags <p> on random pages (e.g. Question tags)

**Comment by sjDCC** [comment]
Not spotted any html on random pages so assume this is good to close out
