### ISSUE TITLE
Error on edit profile page when saving changes

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#533]
When I try to change certain fields on edit profile e.g. name, organisation, I hit an error and it says save has been unsuccessful. Two fields are highlighted in yellow (recovery email and password) suggesting these need to be re-entered. That's not the desired functionality though so this is a bug.

It's possibly something that was introduced when we were adding new tabs for email notifications so have added in to that milestone to link up.

![capture](https://user-images.githubusercontent.com/6169940/28471611-9f3e2ffc-6e35-11e7-8981-0d086f6a468d.PNG)

**Comment by vyruss** [comment]
@sjDCC the yellow highlighting may be the browser's autocomplete function

**Comment by xsrust** [comment]
Some comments/questions about the intended functionality of this page:
- Should recovery email be mandatory? i.e. does it need to be filled in before the user saves their profile?  It seems odd to require a user enter 2 emails on their profile.
- Should the password field be mandatory on this page?  
  - When I last worked on this page, it was only needed to edit the email field
  - If it is only mandatory for some edits, we need to make this clear to the user, perhaps by show/hiding the field
- Should organisation be mandatory? I believe yes as a user needs to have an organisation for some of the assumptions the code makes.

**Comment by xsrust** [comment]
Also is the intended behavior of the Org-not-listed button to select other from the list of organisations and to show a text field for a user to input their org name?  Currently it just clears out your selection.

**Comment by sjDCC** [comment]
@briri - do you guys need recovery email to be mandatory? It's less important in our context afaik, but I think you may need it to enable SSO unlinking? Maybe it's just mandatory when they unlink or is that too late as they've often lost access to institutional email then?

@xsrust I think we now make first name, last name, email, org, and password mandatory. These are all details that we want every account to have, but I don't think we should be asking anyone to re-enter anything to save changes.

I think we need a mandatory org, even just to state 'other' and enter freetext name

Other views?

**Comment by xsrust** [comment]
The password is mandatory to have with a user account, but the goal of the password field on that page is to verify the identity of the user by entering their current password when doing sensitive actions such as changing the account's email.

There is a separate tab for changing password.

**Comment by sjDCC** [comment]
Ok, thanks for clarifying @xsrust 

I think we want to limit the number of changes that require the password to be entered. I'm happy with that for changing email, but originally it seemed to be needed for any change (e.g. first name or org) which isn't necessary

**Comment by xsrust** [comment]
Your correct, it's currently being required for all changes and i thought it was strange behavior.


I wolnt have time to complete this ticket before I'm away on holiday so un-assigning myself

**Comment by sjDCC** [comment]
Thanks @xsrust 

@briri confirmed via Slack that it shouldn't be asking for the password to save any changes before I raised the ticket

One of us can pick this up while you're away - happy holidays!

**Comment by briri** [comment]
Thanks Sam. Yes we went back and forth on whether or not to require the recovery email. The last conversation we had we decided to make it not required just haven't gotten around to changing it yet.

**Comment by briri** [comment]
And yes the other org box should display. We seem to be missing the JS piece to that

**Comment by briri** [comment]
@sjDCC we were thinking along those lines. Make the recovery email and passwords mandatory in certain situations like when the user unlinks their account. That will happen though on our version of the login/create account/manage profile workflow.

@xsrust yes, we want to make sure that password isn't required to change things like email address unless its vital to your particular workflow (I don't think it is). We can't require it for ours because we want users to create accounts via Shib and not have to worry about a password here.

There is another ticket #518 for the org/other org functionality

**Comment by sjDCC** [comment]
Given that the password change is on a separate tab, should we only have the password field appear when it needs to be entered to save sensitive changes? Having it display in the full list as normal is confusing currently. To me it suggests this field is editable like the others.

**Comment by jollopre** [comment]
The password should not appear at all as field within that tab. Typically, you modify any information (sensitive or not) and before submitting an intermediate screen or popup asks for password to confirm these changes. Screenshot from github, for instance:
![screen shot 2017-08-03 at 09 44 22](https://user-images.githubusercontent.com/7393044/28913519-3e08cbca-7830-11e7-9b74-7869b1753382.png)

**Comment by briri** [comment]
Added modal dialog to obtain the user's password when  they change their email address.
![screen shot 2017-10-27 at 11 11 47 am](https://user-images.githubusercontent.com/1204467/32118805-e2ef6382-bb07-11e7-8cd1-ca082e1e80d0.png)

Added a comment to #746 to deal with the button alignment seen in the screenshot above

**Comment by sjDCC** [comment]
Modal box is being generated and looks good. It threw an error though when i tried to change the email. The first error was shown when I tried to change it to another email known by the system (s.jones@arts.gla.ac.uk) and the second showed when i changed to a new, unknown email. It doesn't seem the save is changing in either case.

![error](https://user-images.githubusercontent.com/6169940/32377361-493fe70a-c09f-11e7-902c-8f87125e47f2.PNG)

![save-unsuccessful](https://user-images.githubusercontent.com/6169940/32377364-4c1c1ad4-c09f-11e7-9871-7542d6f48c54.PNG)

**Comment by stephaniesimms** [comment]
@jollopre - I changed my email address and clicked to Save the changes. The modal popped up as expected and after entering my pw  I received a message that the system "successfully saved my password" (screenshot 1). Desired message and behavior is that it "successfully updated my profile information." When I navigated away from my profile and then returned to it my changes had not actually been saved - it still listed my original email (screenshot 2).

![screen shot 2017-11-13 at 12 23 12 pm](https://user-images.githubusercontent.com/12703638/32747460-9fecf7fc-c86d-11e7-9279-c7ba70b93ed1.png)

![screen shot 2017-11-13 at 12 23 49 pm](https://user-images.githubusercontent.com/12703638/32747537-e38424a4-c86d-11e7-8091-63eb8d671166.png)

**Comment by briri** [comment]
I tried again to replicate this in Chrome and Firefox and it always shows me the correct message. Can you try again @stephaniesimms and let me know if you are still experiencing it?

**Comment by stephaniesimms** [comment]
@briri - now it's working for me in Chrome and Firefox. But I can only achieve the desired results with the following steps:
- change email
- click Save
- enter pw into modal
- click Save again
- then it displays the correct message and saves my changes

desired behavior is that user should not have to click Save a second time or at least they need some indication that this step is required

**Comment by briri** [comment]
ok. makes sense.

**Comment by sjDCC** [comment]
All works fine - closing out
