### ISSUE TITLE
Missing or misformatted cancel buttons on admin area

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#534]
Cancel buttons seem to be missing in the guidance section in the admin area and misformatted elsewhere (they're links under template pages)

![missing-cancel](https://user-images.githubusercontent.com/6169940/28471841-5ee24e6a-6e36-11e7-8c90-22c26adebf62.PNG)
![missing-cancel-2](https://user-images.githubusercontent.com/6169940/28471848-625c0f72-6e36-11e7-97d2-c48a0f6abf55.PNG)
![cancel-misformat](https://user-images.githubusercontent.com/6169940/28471856-6997aec2-6e36-11e7-8a1e-a6ee1cf2769a.PNG)

**Comment by briri** [comment]
Add a Cancel button back onto these pages. It should just bring the user back to the Guidances page

**Comment by stephaniesimms** [comment]
working as expected on Guidance pages. 

Cancel button still appears as a link on Template page (screenshot below). 
a new issue: the Description field should be a text editor. remove the form field that displays over the editor (see correct version from DMPonline screenshot below).
 
![screen shot 2017-10-24 at 11 34 29 am](https://user-images.githubusercontent.com/12703638/31935610-8ca30498-b8af-11e7-8313-dfeb7a13aef3.png)
![screen shot 2017-10-24 at 11 36 57 am](https://user-images.githubusercontent.com/12703638/31935720-d81ba15a-b8af-11e7-9c09-7b2e145476b6.png)

**Comment by briri** [comment]
Created a new ticket #772 for the text field in the description box bug

**Comment by bhavi** [comment]
The template page cancel button has been fixed as a part of the commit:  "re-bootstrap the admin_new view for templates - DMPRoadmap/roadmap#772". Hence, closing this ticket.

**Comment by stephaniesimms** [comment]
all cancel buttons where expected. closing issue.
