### ISSUE TITLE
DMP summary removed from project details page

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#536]
I've just realised that we've lost the plan summary in the revisions to the 'project details' page. This used to give an overview to all questions and sections at a glance e.g. 

![summary-dmp-requirements](https://user-images.githubusercontent.com/6169940/28476356-b3a9c7be-6e47-11e7-9527-450ad276eda0.PNG)

Admittedly it never sat well on plan details page, but we introduced this based on requests from researchers. They got frustrated that you couldn't easily get an overview of all questions to be asked, especially as funders can ask similar questions in subsequent sections. Sometimes they answered in full at the start, only to find they were answering things that were asked later on. I think this section also serves as a useful reference out to the specifics of each funder's requirements e.g. links to their policy, details of page limits etc, which aren't covered elsewhere.

Is there any chance we can reinstate it @stephaniesimms @JEK-III? Perhaps as a tab called 'Summary of requirements'? 

Also, could you give me a heads-up before things like this are removed in the future please. I hadn't spotted it when reviewing the wireframe, but guess you'd taken a decision to remove it when you reviewed that page from each tool. Perhaps you thought it was unnecessary or covered elsewhere?

Thanks

**Comment by stephaniesimms** [comment]
Happy to reinsert the plan summary. My guess is that it got lost as we tried to foreground project details and guidance selections. It could either go back on this page, although users would have to scroll down, or we could add a tab. @JEK-III thoughts?

**Comment by sjDCC** [comment]
Great, thanks. I suspect another tab may be best, perhaps called 'Summary' or something of that kind. The save button is already quite low down and easy to miss (see #535) so adding more here may make it too much scroll

**Comment by JEK-III** [comment]
A separate tab sounds like a great idea to me– I'm thinking "Plan Overview" as a label.

**Comment by JEK-III** [comment]
Added to the wireframes. 

The plan overview content and functionality (i.e., show/hide at the phase level only) is substantially the same as the current application. I did replace the table layout with a structured list that (with appropriate HMTL) will be easier to navigate with a screen-reader.

**Comment by stephaniesimms** [comment]
Created #546 to add Plan Overview per wireframe. Closing this issue.
