### ISSUE TITLE
Fix tab name display behavior for templates w/multiple phases (H2020)

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#541]
For templates w/multiple phases (e.g., H2020) all tabs for phases on the plan writing page display the name of the tab that is currently active. They should not change regardless of where the user navigates.  See screenshots below.

All tabs say "Initial DMP"
![screen shot 2017-07-26 at 4 19 15 pm](https://user-images.githubusercontent.com/12703638/28648039-bb8189c8-721f-11e7-89ae-8c345f192f43.png)

All tabs say "Detailed DMP"
![screen shot 2017-07-26 at 4 19 01 pm](https://user-images.githubusercontent.com/12703638/28648044-cd53cd3c-721f-11e7-87b9-3432d0bac87f.png)

All tabs say "Final review DMP"
![screen shot 2017-07-26 at 4 19 25 pm](https://user-images.githubusercontent.com/12703638/28648048-d3e1a5a2-721f-11e7-8e1b-91161056dd94.png)

Normal tabs - from Project Details tab
![screen shot 2017-07-26 at 4 20 26 pm](https://user-images.githubusercontent.com/12703638/28648052-df631654-721f-11e7-9727-2cac511166fd.png)

**Comment by briri** [comment]
Closing as this no longer seems to be an issue. 
![screen shot 2017-10-16 at 1 16 42 pm](https://user-images.githubusercontent.com/1204467/31633154-572780f0-b274-11e7-9fa3-4389cde4a938.png)
