### ISSUE TITLE
Replace "Shared?" column in plans table

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#545]
UX wireframe @JEK-III - http://h90c3m.axshare.com/#g=1&p=my_dashboard__plans___ideal
It was helpful to be able to see which plans have been shared w/others at a glance (screenshot below). Can you cram that column back into the plans table @JEK-III ? or recommend another approach?

![screen shot 2017-07-27 at 8 15 29 am](https://user-images.githubusercontent.com/12703638/28678634-bda030b6-72a5-11e7-8e9c-cdebcd3fac07.png)

**Comment by JEK-III** [comment]
Crammed!

**Comment by stephaniesimms** [comment]
i think just a simple Yes or No is best here @bhavi - you can remove the parenthetical w/number of users plans has been shared with. the use case is to see which plans are being co-authored at a quick glance.

![screen shot 2017-11-30 at 7 03 48 am](https://user-images.githubusercontent.com/12703638/33437455-dab68b64-d59c-11e7-9e57-587a03e2f4d2.png)

**Comment by briri** [comment]
Yes, reviewer role counts towards being shared

**Comment by stephaniesimms** [comment]
working as expected now. closing issue.
