### ISSUE TITLE
Add "Plan Overview" tab to plan writing pages

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#546]
UX wireframe @JEK-III - http://h90c3m.axshare.com/#g=1&p=write_plan

This follows on related issue #536. We want to retain the overview summary of all questions in a template but move it from the current location at the bottom of plan/project details to its own tab. The plan overview content and functionality (i.e., show/hide at the phase level only) is substantially the same as the current DMPonline application. But replace the table layout with a structured list that (with appropriate HMTL) so it's easier to navigate with a screen-reader and attach labels to input fields.

Note blue notepad functional specs for multiphase plans (e.g. Horizon2020):
- Hide phase title and open/close control in single-phase plans; always show summary.

**Comment by JEK-III** [comment]
@stephaniesimms 
Oops– that annotation came along for the ride when I copy-pasted the Write Plans tab. We definitely only want one Plan Overview tab containing all the phases.

**Comment by stephaniesimms** [comment]
thanks for clarification @JEK-III - makes sense now.

**Comment by JEK-III** [comment]
The wireframes on axshare have now been updated.

**Comment by stephaniesimms** [comment]
just a few tweaks to request:
- The wireframe is designed for a complex H2020 template w/multiple phases. For templates that only have one phase, please remove the phase title and open/close accordion control and just display the full summary of questions. 

Formatting suggestions for the summary: 
- Number section titles and make them bold (in screenshot below 1. Data areas and data types, 2. Standards and metadata...)
- increase spacing between numbered sections
- anything else @sjDCC ? i know DMPonline has a table here but the accessibility test nixed tables bc screenreaders can't handle them.

![screen shot 2017-12-07 at 12 08 43 pm](https://user-images.githubusercontent.com/12703638/33736624-28a7d7e6-db48-11e7-9e34-e2e907c087db.png)

**Comment by sjDCC** [comment]
Mostly sounds good but please don't number sections. 

We let template owners assign numbers in the question text as needed. This is because everyone uses a different system. Some funders specify numbers and letters (e.g. AHRC 2a, 2b,) while others like MRC start numbering at 0 and have sub-points (e.g. 4.1, 4.2), but most make things easy and just use bullets ;-)

If we apply numbers it gets really confusing so we intentionally leave them blank.

**Comment by jollopre** [comment]
- Plan overview considers now plans with just one section.
- Margin bottom (e.g. 5px) added to each section in order to visually separate them.

**Comment by sjDCC** [comment]
This looks good - thanks @jollopre 

I think it would be good to add an 'answer questions' button to help navigate people through from this overview to the actual tabs for answering. That's not essential for MVP so closing out, but pinging @stephaniesimms so she can comment in New Year on preference

![add answer questions buttons](https://user-images.githubusercontent.com/6169940/34113662-5d078ea0-e408-11e7-85c8-31f3cd8334f2.PNG)

And what we have on DMPonline overview 
![examples-dmponline](https://user-images.githubusercontent.com/6169940/34113677-66a31484-e408-11e7-8562-f10049ce24e1.PNG)

**Comment by stephaniesimms** [comment]
happy to add an Answer questions button, or maybe call it "Write plan" to correspond w the name of the tab for all single-phase templates. i'll create a new issue.
