### ISSUE TITLE
Refactor CSS/JS on 'My Dashboard' (Core page)

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#553]
Refactor the My Dashboard page to use Bootstrap.

This page will serve as an example/reference for how to implement tables on our other pages.
http://getbootstrap.com/css/#tables

Remove or replace the functionality in `lib/assets/stylesheets/dmproadmap/tables.css` and `lib/assets/javascripts/dmproadmap/tables.js`

**Comment by briri** [comment]
Bootstrapped the My Dashboard page.

![screen shot 2017-08-11 at 12 27 48 pm](https://user-images.githubusercontent.com/1204467/29228924-a76cf9cc-7e90-11e7-9654-968a17fead4a.png)

**Comment by stephaniesimms** [comment]
visual inspection on stage. closing issue.
