### ISSUE TITLE
Refactor CSS/JS on 'Contact Us' page (Core page)

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#554]
Refactor the Contact Us page to use Bootstrap.

This page will serve as an example/reference for how to implement forms on our other pages.
http://getbootstrap.com/css/#forms
http://getbootstrap.com/css/#buttons

Remove or replace the functionality in `lib/assets/stylesheets/dmproadmap/forms.css` and `lib/assets/dmproadmap/javascripts/forms.js`

**Comment by stephaniesimms** [comment]
visual inspection on stage. closing issue.
