### ISSUE TITLE
Refactor CSS/JS 'About Us' page (Core page)

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#555]
Refactor the About Us page to use Bootstrap.

This page will serve as an example/reference for how to implement tabs on our other pages.
http://getbootstrap.com/javascript/#tabs
http://getbootstrap.com/components/#nav

Remove or replace the functionality in `lib/assets/stylesheets/dmproadmap/tabs.css` and `lib/assets/javascripts/dmproadmap/tabs.js`

**Comment by briri** [comment]
Setup tabs on the page to use Bootstrap.
Added custom css to overrides.scss to override Boostrap's standard look and feel so that we can match what's currently in production

Bootstrap standard styling:
![screen shot 2017-08-09 at 3 41 37 pm](https://user-images.githubusercontent.com/1204467/29147008-49c3db10-7d19-11e7-863e-70a60b3b5cbe.png)

After custom css:
![screen shot 2017-08-09 at 3 39 23 pm](https://user-images.githubusercontent.com/1204467/29147017-506ce7cc-7d19-11e7-9977-cdbadbd2c121.png)

**Comment by stephaniesimms** [comment]
visual inspection on stage. closing issue.
