### ISSUE TITLE
Refactor CSS/JS for Terms and Help pages

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#557]
Refer to the work done in #555

**Comment by briri** [comment]
- Terms page has no tabs so did not require any special changes for bootstrap. 
- Updated the roadmap (future plans) and help pages to use bootstrap tabs.
- Overall Bootstrap layout changes are attached to PR #583 (added `<div class="row><div class="col-md-12">` around the `<h1>` tag)

**Comment by stephaniesimms** [comment]
visual inspection on stage. closing issue.
