### ISSUE TITLE
Refactor CSS/JS for navigation menus

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#565]
Refactor the main navigation bar and the edit profile/language nav sections to use Bootstrap.

http://getbootstrap.com/components/#navbar
http://getbootstrap.com/javascript/#dropdowns

**Comment by vyruss** [comment]
PR #594 updates the header. Has temporary placeholders in place for #525.

**Comment by stephaniesimms** [comment]
visual inspection on stage. closing issue.
