### ISSUE TITLE
Refactor CSS/JS for Modal dialogs

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#566]
Replace the Jquery-UI CSS and JS on the `lib/assets/javascripts/dmproadmap/modal.js` and `lib/assets/stylsheets/modal.scss` with Bootstrap's version of modal.
http://getbootstrap.com/javascript/#modals

Then verify that all of the site's modals are properly implemented (e.g. the sign in/create account forms triggered from the `app/views/layouts/_signin_signout.html.erb`)

**Comment by stephaniesimms** [comment]
visual inspection on stage. closing issue.
