### ISSUE TITLE
Refactor CSS/JS for accordions

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#567]
Replace the Jquery-UI CSS and JS on the `lib/assets/javascripts/dmproadmap/accordion.js` and `lib/assets/stylsheets/accordion.scss` with Bootstrap's version of collapse.
http://getbootstrap.com/javascript/#collapse

Then verify that all of the site's accordions are properly implemented (e.g. the plan write page)

**Comment by stephaniesimms** [comment]
visual inspection on stage. closing issue.
