### ISSUE TITLE
Refactor CSS/JS for alerts, tooltips and popovers

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#568]
Replace the custom CSS and JS currently controlling the alerts, tooltips and popovers from `lib/assets/javascripts/dmproadmap/utils.js`, `lib/assets/stylesheets/dmproadmap/base.scss` with Bootstraps' implementation:
http://getbootstrap.com/javascript/#tooltips
http://getbootstrap.com/javascript/#popovers
http://getbootstrap.com/javascript/#alerts

Then find all of the places they are used and make sure they are properly implemented.

This should be fairly straightforward. The custom css/js was using the same `data-toggle` attribute that Bootstrap uses.

**Comment by stephaniesimms** [comment]
visual inspection on stage. closing issue.
