### ISSUE TITLE
Create Plan Page not removing options by filtering

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#57]
There is an additional dropdown that appears when funders (or unis) have more than one template for users to select from. This is always displaying now, even when there is only one choice.

Also, an option called ‘My organisational guidance’ is showing in the optional guidance dropdown. Is this due to automatically creating a guidance group for each org? I don’t know why it’s appearing and expect it shouldn’t be.

**Comment by briri** [comment]
Hey @xsrust It was easier for me to just disable the templates dropdown when there is only one option available. It could easily be changed to do something else though if we want. Check out the reloadTemplateData function in projects.js. 

I don't see a 'My organisational guidance' option. Perhaps its just some test data that got entered?

**Comment by vyruss** [comment]
Please be aware that Diana has informed me that some users are being
confused by the fact that their org does not appear in the drop down list
(if there is no relevant item from there). Perhaps we can inform them with
a message that their own org does not have a template/whatever.

**Comment by sjDCC** [comment]
This isn't fixed unfortunately. The additional template dropdown doesn't show up every time (which is great) but it also doesn't show up when it should.

When either a funder or uni has more than one template, it should introduce this dropdown so you select which one to use. Both Cancer Research UK and now Glasgow Caledonian Uni have two published templates so it should display for them.
