### ISSUE TITLE
Refactor CSS/JS for generic footer

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#573]
Update the generic footer to work with bootstrap

**Comment by briri** [comment]
Updated the layout of the footer to work with Bootstrap.

Updated the definition of the menu in the footer so that its role is "navigation"

![screen shot 2017-08-08 at 1 47 50 pm](https://user-images.githubusercontent.com/1204467/29093900-4e8d6ca8-7c40-11e7-889d-8f16772da45c.png)

**Comment by stephaniesimms** [comment]
visual inspection on stage. closing issue.
