### ISSUE TITLE
Define "completeness" for adding public plans to list

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#575]
Related issue #84 
To manage the public DMPs list we need to identify some threshold of plan "completeness" without introducing formal status indicators just yet. A percentage of questions answered (>1 question) but something pretty low as @sjDCC suggested (45%) is looking like the best option. The goal is to avoid cluttering the public list with blank/test plans.

**Comment by briri** [comment]
recently set to 50% in #713
