### ISSUE TITLE
Unlock gem versions from Gemfile

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#579]
In order for the site's gems not to fall behind and get outdated, we need to unlock their versions at some point before MVP release.

**Comment by briri** [comment]
Can happen post MVP

**Comment by briri** [comment]
this will be done as part of #826 Ruby upgrade

**Comment by stephaniesimms** [comment]
is this issue redundant now @vyruss @briri now that @bhavi is working on #826 ? if so we can close it.

**Comment by bhavi** [comment]
This ticket handled as part of ticket #1421

**Comment by stephaniesimms** [comment]
closing issues that can't be tested in the UI
