### ISSUE TITLE
DCC Guidance not displaying

### ISSUE THREAD

**Issue by raycarrick-ed** [DMPRoadmap/roadmap#58]
If you select to view DCC guidance as part of your plan, the confirmation shows this has been picked but no guidance displays. Guidance I’ve added for the institution (GCU) is pulling through so it’s maybe an error with the DCC or default setting?

**Comment by raycarrick-ed** [comment]
@sjDCC can you check this again? seems to work from a quick test. I tried the following:

- create plan based on Horizon 2020
- tick box for DCC guidance
- go into "initial DMP" section 1 "Data Summary"

and I can see 3 sets of DCC guidance on "Existing Data", "Data Volumes" and "Data Format"

Can you either close this as ok now or give further details to chase it. Thanks.

**Comment by sjDCC** [comment]
All fixed - thanks
