### ISSUE TITLE
Profile page should display ORCID iD number

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#580]
related/unresolved issue #390 
Profile page should display a hyperlink to "Create or connect your ORCID iD"
Once a user makes the connection it should then display a hyperlinked URL for the user's ORCID iD 

Replace the original implementation for this functionality from ca. Feb 2017 (screenshots below from IDCC17 presentation)

![screen shot 2017-08-10 at 10 01 22 am](https://user-images.githubusercontent.com/12703638/29182211-e532444e-7db2-11e7-9d9b-edffb1affb5a.png)

![screen shot 2017-08-10 at 10 01 36 am](https://user-images.githubusercontent.com/12703638/29182229-f68915ec-7db2-11e7-90e8-850dcf8fc439.png)

**Comment by stephaniesimms** [comment]
@vyruss - here's what my profile displays when I connect my ORCID (screenshot below). please make it look like the screenshot above that displays the green ID logo next to the complete URL for the id.

![screen shot 2018-01-16 at 8 05 02 pm](https://user-images.githubusercontent.com/12703638/35025170-a5b82d60-faf8-11e7-9f8a-243d14d8037c.png)

**Comment by vyruss** [comment]
@stephaniesimms that's easy to fix, you'll need to insert `'https://orcid.org'` and `'http://orcid.org/sites/default/files/images/orcid_16x16.png'` as ORCID's `user_landing_url` and `logo_url` respectively in the `identifier_schemes` table in your database (values are not hardcoded)

**Comment by stephaniesimms** [comment]
got it @vyruss - can you take a look at this @briri ?

**Comment by briri** [comment]
should be all set @stephaniesimms 

@vyruss we should double check the dmponline_v3 migration scripts to make sure those values are set for anyone migrating over.

**Comment by stephaniesimms** [comment]
all pretty now. thanks both. closing issue.
