### ISSUE TITLE
Introducing Webpack to handle assets pipeline

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#587]
Since JS ecosystem is mature enough nowadays to bundle all front-end assets (e.g. javascripts, stylesheets, images, etc). It is best to replace the sprockets assets pipeline from Rails with task bundler like Webpack. 

There are many advantages by moving towards a JS run bundler:
- Easy integration of new JS features from ES6 (modules, const, let, arrow functions, etc)
- Easy integration of unit and integration JS test
- More active community to solve problems or issues
- Easy splitting of file bundlers, for instance per page if the current JS bundled (application.js) grows considerably
- and many more...

**Comment by briri** [comment]
This is complete. Closing since there is no UAT component
