### ISSUE TITLE
Migration issue during Upgrade Step 1

### ISSUE THREAD

**Issue by benjaminfaure** [DMPRoadmap/roadmap#595]
Hello,

I've been testing the migration process on my development machine, it looks really solid, I only encountered a minor issue.

During the Upgrade Step 1 when I'm launching this command `rake migrate:data_integrity` I get the following error :
`ActiveRecord::StatementInvalid: Mysql2::Error: Table 'roadmap.Sections' doesn't exist: UPDATE Sections SET title = 'TITLE' WHERE title = '' OR title IS NULL`

It comes from some mysql queries having the table name with the first char in uppercase. Maybe you have not encountered this issue if you are using Postgres (If I recall correctly, pg consider "Sections" and "sections" being the same thing) .

Nothing major, but for the sake of consistency (and not having to edit a file) I guess it should be corrected :)

If you need a pull request I can provide you one. 

Benjamin

**Comment by vyruss** [comment]
Thanks @benjaminfaure, I added commit ec830069663263385a88a6eefd773f500d020b78 which should fix the issue (made table names all-lowercase).
