### ISSUE TITLE
Generic text for Help page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#597]
Generic text for Roadmap Help page in Google doc:
https://docs.google.com/document/d/12MH0c8ow1gQ8_tvE1T02DUYYEys6gaMiEF_hmaLxyQY/edit

**Comment by dsisu** [comment]
I suggest we write instructions in bullet points. We should not use abstract terms like 'select options' but specify more descriptive terms to correspond to what users see on screen. Use terms like button, tab, name the fields, etc. For example, 'Create a plan' could be:

- Click on 'My Plans' tab [can't remember if it's a tab or a menu item and the server is down just now]
- Select the 'Create plan' button [again can't remember if it's a button or a tab]
- Enter plan name
- Enter research organisation and funding body. This will determine what questions and guidance you will be presented with.'

I hope you see what I mean. I presume there is more time to edit this information and, if so, is there a deadline? Thanks.

**Comment by stephaniesimms** [comment]
all Generic text is adapted from existing DMPonline content. my preference is for shorter content along the lines of what you currently have, and assuming that users understand how to follow a wizard. @sjDCC and I have made passes at editing this. feel free to suggest any additional changes. it would be good to finalize all generic text in the next week or two so devs can replace it on static pages while they're bootstrapping.

**Comment by stephaniesimms** [comment]
transferred to global issue for generic text on static pages #668
