### ISSUE TITLE
Replace gemfile for front-end translations with the underlying Jed library

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#599]
As part of moving all the assets to Webpack, the gem "gettext_i18n_rails_js" has to be replaced with Jed library directly. A separated issue to deal with this will allow progressing on the ticket #587

**Comment by briri** [comment]
move JS constants to hidden input elements on the page so that the regular GetText can be used for translation. Then update JS to pull in the values when needed.

**Comment by briri** [comment]
picking this one up @jollopre as we want to get translation files out to a few people. Will add the constants to the `views/layouts/application.html.erb` file and tie them in via the `lib/assets/constants.js`

**Comment by stephaniesimms** [comment]
can't test in UI. closing issue.
