### ISSUE TITLE
Funder customizations not showing up on the front end

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#60]
I customised the CRUK standard template for GCU, adding an example answer to the first question and an additional section. Neither display on the front end when I create a plan for CRUK standard template with GCU selected in org. This is possibly related to bug 3 if something has gone awry with the logic for selecting templates and guidance?

**Comment by xsrust** [comment]
error turned out to be connected to plan creation.  the latest version of a phase was being incorrectly identified by the latest_published_version function in the model for phase.  any past created plans will still have this bug for templates which have multiple versions, but newly created plans will behave as intended

**Comment by sjDCC** [comment]
Fixed
