### ISSUE TITLE
Refactor ES5 scripts to ES6

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#601]
In order to take advantage of the Webpack module bundler, already in place. It is best to translate our ES5 scripts to a modular approach provided by ES6. All our ES5 scripts are loaded through the following partial:
https://github.com/DMPRoadmap/roadmap/blob/CDL-MVP/app/views/layouts/_es5_scripts.html.erb

The steps for each file should be:

- Transcribe to ES6
- Determine whether or not is possible to remove the javascript_include_tag entry at the above mentioned partial.
- Determine whether or not is possible to remove object at webpack configuration file located at lib/assets/webpack.config.js (Lines from 78 to 93). Note, these lines serve to copy the ES5 files located at lib/assets/javascripts to public/javascripts

**Comment by stephaniesimms** [comment]
ongoing. handled in individual tickets per page. closing issue.
