### ISSUE TITLE
Database migration failure when dropping indexes

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#607]
Unable to drop indexes when running `db/migrate/20170702012742_ensure_indexes_in_place.rb`.
MySQL requires the foreign keys be dropped before the indexes are removed.
- users_perms
- questions_themes
- answers_question_options

**Comment by briri** [comment]
added lines to the migration file to drop and then re-add the foreign keys on the tables listed above

**Comment by briri** [comment]
fix has been merged into development. Will be moved into master during the next release

**Comment by stephaniesimms** [comment]
can't test. closing issue.
