### ISSUE TITLE
Local setup of RDA API

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#620]
Currently not being hosted, so a local installation is required at the moment.

Setup according to:
https://github.com/rd-alliance/metadata-catalog-dev

**Comment by xsrust** [comment]
Needed to add the following to migrate.py to allow it to run:
Line 71:
`n = dict()`

All other instructions seem to be correct.

**Comment by briri** [comment]
can this one be closed out @xsrust?

**Comment by briri** [comment]
closing this out since the RDA work has finished. Please reopen if its still applicable @xsrust
