### ISSUE TITLE
Add backend structures needed

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#622]
### How to store/demarcate the Questions?
 - New `QuestionFormat` for pulling rda-metadata in on specific question.

Need to make this extensible for other api-like questions (Biosharing, ect). @sjDCC @stephaniesimms,  Do we know how many other such integrations we are expecting down the line?  If it's just the two, it probably makes sense to make two different `QuestionFormat`s and leave the API's address in the description field, which is currently unused.  If we think this may be expanded down the line, we may want only one 'API' `QuestionFormat`, and have a table or some other mechanism for determining which API to access.

### How to store the answers?

@sjDCC @stephaniesimms Do we want free-text in addition to storing the chosen record?  Records will be recorded by their unique id given by the external API.

### How to get the data

This will be requested in JS from the API.  Instead of storing the external integration, we simply search for the stored record uid, and build page display

**Comment by sjDCC** [comment]
Hi @xsrust There will definitely be re3data too, but possibly more so probably worth planning for several

If there's a freetext response, I think this should be stored in the main answer box and focus here on the chosen record

**Comment by stephaniesimms** [comment]
per UX meeting comments:
- ideal scenario would be to plan for other integrations (re3data, etc)
- yes, we probably need to be able to record free text answers

**Comment by xsrust** [comment]
In order to be able to save multiple standards and an optional comment, the selections will be stored as JSON in the Answer.text field, in the following format:
```
{
    standards: {'msc:m15'=>'msc:m15'},
    text: "my comment here"
}
```

Note that all keys must be accessed by strings after using `JSON.parse(answer.text)`
ex. `parsed_answer["standards"]`

**Comment by xsrust** [comment]
added ability to store user-generated standards.  For these, the key and value will both be the title of the standard.
Made the decision to change the 'msc:m__' standards to have the value be the title of the standard.  this way we don't need to query the API for export

**Comment by sjDCC** [comment]
Looks good and works for selected standards and ones added by user. Closing out
