### ISSUE TITLE
Add question display (& functionality)

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#623]
## UI wireframes:
Admin: In progress 
Public User: In progress

## Decide on and implement a front end.
Data is structured by subject area as shown in picture below
![screen shot 2017-09-05 at 2 47 20 pm](https://user-images.githubusercontent.com/7352616/30064670-63e2823a-924a-11e7-88ff-9305118139ca.png)

### Display currently planned is:
 - Request this list from an extension to the API, (see #621 )
 - Display a dropdown box for each layer of narrowing, and one to select a specific metadata scheme
 - Update all boxes based on current state of selection, may need more/less depending on the tree.
 - Store only the identifier, ex. m28, within the question

### Other Considerations:
Planned display may change based on comments in #622

**Comment by xsrust** [comment]
see #621 for an idea of the data available for each record.

it's likely useful to display links/descriptions if available for the selected record.

**Comment by sjDCC** [comment]
We probably need to include a description field too to help people select relevant standards. They may not know them by name, or understand the difference if presented with a list of options.

The summaries you see on [this page](http://rd-alliance.github.io/metadata-directory/standards/) may be useful, though we perhaps need shorter ones depending on display

**Comment by xsrust** [comment]
Multidisciplinary

Countries and country groupings

Culture
  Cultural policy and planning
  History & Archaeology
  Visual arts & Architecture

Education

Information and communication
  Information technology (software)


Politics, law and economics
  Agriculture
  Civil, military and mining engineering
  Economics
  Legal systems & Law
  Manufacturing and transport engineering
  Materials and products
  Politics and government

Science
  Biology
  Chemical sciences
  Earth sciences
  Environmental sciences and engineering
  Geography and oceanography
  Hydrology
  Mathematics and statistics
  Medical sciences
  Meteorology
  Natural resources
  Natural sciences
  Pathology
  Physical sciences
  Space sciences

Social and human sciences
  Human settlements and land use
  Population
  Social policy and welfare
  Social sciences

**Comment by xsrust** [comment]
Implemented frontend as per below:

![screen shot 2017-09-19 at 12 41 35 pm](https://user-images.githubusercontent.com/7352616/30590759-f1f37cda-9d37-11e7-81d7-70d170752443.png)

**Comment by xsrust** [comment]
Changes since last update:
Search box added next to 'Select a Subject'

Standard not listed link added
When clicked, allows a user to input free text for their standard title.
User-generated standards are stored as 'standard_name': 'standard_name' in the DB.  this allows us to differentiate between these and standards from the API.
![screen shot 2017-10-20 at 12 15 03 pm](https://user-images.githubusercontent.com/7352616/31818605-bf520c12-b590-11e7-9562-aca134d175a6.png)

**Comment by stephaniesimms** [comment]
ready for testing on dmponline-test @sjDCC

**Comment by sjDCC** [comment]
Search box works well, and 'add your own' Thanks @xsrust Closing out
