### ISSUE TITLE
Answering plans is slow

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#634]
Plans that have multiple phases, sections and questions are not performant to be answered currently. At a first glance, I have spotted that we are eager loading a plan filtered by id instead of plan id and phase id.

(see code at https://github.com/DMPRoadmap/roadmap/blob/master/app/models/plan.rb#L993). 

This issue has been through our help desk support.

**Comment by stephaniesimms** [comment]
tested and saving is reasonably fast. this appears to be fixed so closing. reported a separate issue #710 involving autosave not working for certain question types.
