### ISSUE TITLE
Wrong error message when creating account for existing email

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#638]
When a user tries to create an account for an email already taken in the system, but using a different mix of upper and lowercase lettering, the wrong error is thrown:

![create-account-error](https://user-images.githubusercontent.com/6169940/30483600-5426c93c-9a1f-11e7-8b98-8148d14bfeae.PNG)

They only get the correct error that the email is taken when the case sensitivity matches.
![correct-error](https://user-images.githubusercontent.com/6169940/30483614-66e6e85e-9a1f-11e7-923d-2166550c63e3.PNG)

This is related to #550

**Comment by briri** [comment]
seems to have been fixed along with #550.

**Comment by briri** [comment]
@sjDCC can you verify that this is fixed in production? It seems to be working in CDL-MVP. I'd like to make sure that the fix made it into production though before closing

**Comment by sjDCC** [comment]
No, this is still throwing the wrong error on production.

I tested this by trying to register with Sarah.Jones@glasgow.ac.uk. If I do the same with lowercase (i.e. sarah.jones@glasgow.ac.uk) I get the correct 'email address already registered' notice.

@vyruss can we deploy this fix before closing please?

**Comment by jollopre** [comment]
@sjDCC now the tool should not allow you to create an account for an existing email anymore. You can test it whenever is deployed

**Comment by stephaniesimms** [comment]
tested on roadmap stage and working as expected. closing.
