### ISSUE TITLE
Define Org logo size constraints

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#639]
As part of Bootstrap phase 2 styling work, need to define the appropriate size and dimensions for Org logos in secondary header.

**Comment by briri** [comment]
reduced the size of images from a height of 165px to 95px. The aspect ratio is retained so the width of the logo fluctuates. 

![screen shot 2017-10-12 at 9 09 04 am](https://user-images.githubusercontent.com/1204467/31506908-adf41960-af2d-11e7-8c88-f212d56b824e.png)

Added a rake task that will run through and resize any existing logos. `bundle exec rake logos:resize_all`

**Comment by stephaniesimms** [comment]
tested and closing.
