### ISSUE TITLE
utf8 type not safe in MySQL

### ISSUE THREAD

**Issue by par4dise** [DMPRoadmap/roadmap#652]
On homepage, instructions say:
> Create your database. Select UTF-8 Unicode (utf8) encoding.

It is now widely settled that utf8 type is not safe, especially because it allows corruption using Unicode characters. Furthermore the fix is easy: use utf8mb4 instead of utf8.

References:
https://speakerdeck.com/mathiasbynens/hacking-with-unicode?slide=98
https://medium.com/@adamhooper/in-mysql-never-use-utf8-use-utf8mb4-11761243e434

**Comment by mxsstrong** [comment]
thank you for noting this.  We can put a ticket in our backlog to address this and perform some testing to ensure the new type is read/written properly by the application.

**Comment by vyruss** [comment]
Closed by #738 and updated in wiki - Thanks
