### ISSUE TITLE
Bootstrap template questions

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#655]
During the process of editing a template, three partials could be involved regarding questions:

- app/views/questions/_add_question.html.erb
- app/views/questions/_edit_question.html.erb
- app/views/questions/_show_question.html.erb

Currently, the rendering of these partials was commented out in the issue #643 since the issue was long enough to be addressed there. To enable the above mentioned partials, check for them in the files:

- app/views/sections/_show_section.html.erb
- app/views/sections/_edit_section.html.erb

**Comment by stephaniesimms** [comment]
visual inspection on stage. closing.
