### ISSUE TITLE
Bug on admin preview

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#677]
On the template preview on the admin area, the guidance text is being displayed in both guidance and example answer fields. This is incorrect. it should only show in the guidance panel.

If there is no guidance and an example answer is added it displays correctly, however if guidance exists, this overrides any entry in the example answer field. I'm sure this is only happening on the admin preview as I haven't seen any errors on the front end.

![admin-preview-error](https://user-images.githubusercontent.com/6169940/31391277-fb50c354-adcd-11e7-948a-a13d852bd5fe.PNG)

**Comment by dsisu** [comment]
Any news on this issue? I received user enquiry.

**Comment by jollopre** [comment]
After speaking with @sjDCC last Thursday, it has been agreed to be fixed in CDL-MVP branch. The preview functionality will be an attempt to view the template as if the admin user was writing a plan for that template.

**Comment by sjDCC** [comment]
Just tested and looks good - closing out
