### ISSUE TITLE
Shibboleth DS page JS error

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#680]
Remnant of an old call to an ES5 JS file is causing and error.
Log out of the tool and then click on 'Your Institution' button on the Sign in form to replicate the error:
```
 Showing /apps/dmp/apps/roadmap/releases/20171010182816/app/views/orgs/shibboleth_ds.html.erb where line #1 raised:

undefined method `javascript' for #<#<Class:0x00562fa1141348>:0x00562f9edd2240>
```

Log indicates that its using an HTTP GET instead of POST now.

**Comment by briri** [comment]
related to #685

**Comment by stephaniesimms** [comment]
working as expected. closing.
