### ISSUE TITLE
Create plan - blank message

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#682]
When you select a research org or funder on the create plan page, a blank notice appears at the top of the page. Need to update the JS to not display this when its returning template options. It should only be setting the flash notice when the plan is created.

**Comment by briri** [comment]
related to #684

**Comment by stephaniesimms** [comment]
While trying to test this I discovered I can't create a plan @briri . When I made selections I didn't notice any blank message so maybe this is fixed...?
but I did get the following weird json output after clicking "Create plan" 

![screen shot 2017-10-12 at 5 11 57 pm](https://user-images.githubusercontent.com/12703638/31524800-d968b978-af70-11e7-88fe-d82483289b76.png)

**Comment by stephaniesimms** [comment]
@briri - so now i can create a new plan and the correct message is displayed. but there's a new bug that displays a secondary template drop-down for every funder even if there's only one template (see screenshot).

![screen shot 2017-10-17 at 2 31 03 pm](https://user-images.githubusercontent.com/12703638/31690647-362f3b66-b348-11e7-915d-202b66dc9fc0.png)

**Comment by stephaniesimms** [comment]
@briri - functionality is back to normal for dropdowns and creating the plan, but the message is weird (screenshot below). i assume this is because we need to display the name for subtemplates, but for funders w/only 1 template it should only say:

"This plan is based on the Wellcome Trust template"

![screen shot 2017-10-20 at 1 29 09 pm](https://user-images.githubusercontent.com/12703638/31840680-4b67c606-b59b-11e7-8d5c-5abea5510332.png)

**Comment by briri** [comment]
I had updated it to display: "This plan is based on the [Organization Name]: '[Template Name]' template" per an earlier ticket. 
Do we want to clean up the template names or try to introduce logic that determines how best to structure the message. That could get messy though.

**Comment by stephaniesimms** [comment]
we definitely want to clean up the template names. can the message display: This plan is based on the [Template Name]: [Subtemplate Name]? so e.g., Department of Energy: Office of Science template

**Comment by briri** [comment]
We don't really have a concept of sub-templates in Roadmap. We have Organization and Template so in the example above, [Organization name]: [Template Name] would be "Department of Energy (DOE): Department of Energy (DOE): Office of Science"We'd ideally remove the 'Department of Energy (DOE)' from the template name. 
I think that approach would be ok in most situations. All of the tables that list templates also list the funder/org name. The only place where I could see an issue is in lists of plans. We display the template names there but not the org name. So you'd see something like: 
- Plan: 'Impact of autonomous vehicles on the price of tomatoes' Template: 'Office of Science'

**Comment by sjDCC** [comment]
I agree this approach will work. We may need to adjust some data on our side as most template names also include the funder name, but we can change this as needed.

**Comment by stephaniesimms** [comment]
@briri - just confirming that it sounds like we can resolve this by adjusting template names. no tricky logic necessary.

**Comment by briri** [comment]
alright. do we feel comfortable closing this out then?

**Comment by stephaniesimms** [comment]
sure thing. i'll confer w/ @sjDCC  to make sure we understand how to curate template names so we display a sensible message.
