### ISSUE TITLE
Reset password has blank notice

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#684]
I entered 2 mismatched passwords and clicked the submit button. the form validation worked properly but a blank notice message appeared at the top. 
![screen shot 2017-10-10 at 1 16 56 pm](https://user-images.githubusercontent.com/1204467/31408462-83b65c38-adbd-11e7-9618-92c6f34abf95.png)

**Comment by briri** [comment]
JS code behind the 'is test' checkbox on the my dashboard page had a selector that was not specific enough. Added an id to the table and updated the JS specificity

**Comment by stephaniesimms** [comment]
working as expected. closing issue.
