### ISSUE TITLE
Error on log out

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#685]
Getting this error on logout. 

![screen shot 2017-10-10 at 1 22 40 pm](https://user-images.githubusercontent.com/1204467/31408669-35d4055a-adbe-11e7-8b70-077c9ec80752.png)

**Comment by briri** [comment]
Rails restful links (links that use HTTP methods other than GET) are no longer working now that we have removed the ES5 code which included JQueryUI. HTML does not support links with methods like DELETE and POST. Need to add some JS to handle this functionality.

**Comment by stephaniesimms** [comment]
working as expected. closing issue.
