### ISSUE TITLE
No error when attempting to create a new account for an email that is already registered

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#686]
If you fill out the create account for and use an email address that already exists and click submit you are not presented with any information. The home page reloads but no error message is displayed.

Log indicates that its using an HTTP GET instead of DELETE now.

**Comment by briri** [comment]
related to #680

**Comment by stephaniesimms** [comment]
@briri I can't test this because of a new bug that doesn't recognize if I tick the box to accept Terms (screenshot below)

![create-account](https://user-images.githubusercontent.com/12703638/31628857-c09c0e6a-b266-11e7-86cc-a3f9e3cde3e3.png)

**Comment by stephaniesimms** [comment]
displays appropriate error msg now. closing
