### ISSUE TITLE
AJAX mixed content issue

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#689]
`Blocked loading mixed active content “http://roadmap-stg.cdlib.org/plans/16434/set_test”[Learn More]`

For some reason rails is using 'http' instead of 'https' when generating the url from the following:
```ruby
<%= form_for plan, url: set_test_plan_url(plan), html: {method: :post, id: 'update-test-plan'} do |f| %>
```

**Comment by briri** [comment]
Switching to use `set_test_plan_path` instead of `set_test_plan_url` seems to resolve the issue.

**Comment by stephaniesimms** [comment]
can't test. closing issue.
