### ISSUE TITLE
Double sign-up allows hijacking of accounts

### ISSUE THREAD

**Issue by vyruss** [DMPRoadmap/roadmap#69]
Actions: Try to sign up, and try to sign up with the same email before confirming your account.
Problem: You get logged straight into that account's edit profile page.

**Comment by raycarrick-ed** [comment]
In the registrations controller, it looked like the intent was that if someone tried to register with an email that was in the DB but no password was set and it was not confirmed then confirm them and set the password. But the code for checking the password was not set was wrong so passwords would get reset and the user confimed. Now you just get a straight error.

**Comment by vyruss** [comment]
Fixed in e60039
