### ISSUE TITLE
System does not "Remember email" on Sign in 

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#691]
upon signing in I ticked the box to "Remember email" - 
after signing out and returning to the Sign in page the system does not remember my email

![screen shot 2017-10-11 at 9 02 20 am](https://user-images.githubusercontent.com/12703638/31452155-fb1afdd8-ae62-11e7-991c-a68d9a51f52b.png)

**Comment by briri** [comment]
Added js-cookie to the npm package. Added JS handler to store/load the users email from the browser's cookie store. Unchecking the box deletes the cookie if one exists. Defaulted to 14 day cookie expiration.

**Comment by stephaniesimms** [comment]
working as expected. closing.
