### ISSUE TITLE
Add search box to Public DMPs page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#693]
Add search box to Public DMPs page 
Use same box as My Dashboard, DMP Templates, other lists

**Comment by briri** [comment]
The table has a search box, but it only becomes available if there are more than 10 public plans.
The 10 row limit is set globally. We can reduce it to 5 (or 1 even) if we want it to always be visible, but it would end up working that way for all tables across the site.

@stephaniesimms let me know if the 10 row limit is alright

**Comment by stephaniesimms** [comment]
thanks for the reminder. 10 rows still sounds sensible to me. closing issue.
