### ISSUE TITLE
Problems with Comments functionality

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#706]
- Change button to read "Add Comment" (remove "a")
- Default should be to display a text editor under "Comments" - user should not have to click to "Add Comment" to get to the editor
- "Add Comment" button should appear below any existing comments
- Button below the editor should say "Save" (not "Create")
- Clicking "Edit" opens a huge text editor (screenshot 1); it should be the same/standard size as question area text editor
- Clicking "Remove" doesn't do anything; it should delete/remove the comment.
- When I click to add a comment for Question/Phase 2 the comments for Q1 above disappear (screenshot 2)

Screnshot 1
![screen shot 2017-10-12 at 2 42 47 pm](https://user-images.githubusercontent.com/12703638/31521414-53f46bdc-af5e-11e7-821a-7162915bd1c3.png)

Screenshot 2
![screen shot 2017-10-12 at 2 42 11 pm](https://user-images.githubusercontent.com/12703638/31521454-76f7a9a0-af5e-11e7-90e9-23063bb72a3a.png)

**Comment by stephaniesimms** [comment]
For consistent UI language on My Dashboard and Write plan areas please revise the following (see screenshot):

- Change "Delete" action link to "Remove"
- revise message: "Are you sure you want to remove this comment?"

![screen shot 2017-10-16 at 1 21 02 pm](https://user-images.githubusercontent.com/12703638/31633341-ec6f6830-b274-11e7-82e1-2073b6e45a29.png)

After adding more than 2 comments, the text editor box is truncated and I cannot save new comments. If I click away from the box and come back to it sometimes the editor expands to normal size and then I am able to save (screenshots below). Desired behavior is to always open the full text editor below the most recent comment.

Truncated box, can't save comment
![screen shot 2017-10-16 at 1 27 09 pm](https://user-images.githubusercontent.com/12703638/31633755-3b386524-b276-11e7-8294-48a9c5f393f1.png)


![screen shot 2017-10-16 at 1 31 25 pm](https://user-images.githubusercontent.com/12703638/31633786-54e6f54e-b276-11e7-97a3-212533b21678.png)

**Comment by vyruss** [comment]
Do we want emails here? I'm thinking it would be better with real names.

**Comment by sjDCC** [comment]
Names are probably clearer (and shorter?) than email, but we don't always have a real name. Empty fields were replaced with FIRSTNAME LASTNAME in DMPonline, as this didn't used to be mandatory. Perhaps easiest to stick with email unless we can differentiate?

**Comment by stephaniesimms** [comment]
good point @sjDCC - we have some legacy accounts that lack first and last name (fields are blank) so best just to stick w/email

**Comment by jollopre** [comment]
Note we have a method in place to display email in case firstname and surname are empty...
