### ISSUE TITLE
Fix formatting for "Public DMPs" PDF files

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#712]
related issue #436 (closed but referenced here just in case)

On the cover page:  
- Change "Funder" to "Template" (since not all templates are based on funder reqs)
- Change "Last updated" to "Last modified"
- IF info was provided in either field by user, include "Grant ID" and/or "Project abstract" between "Template" and "Last modified" 

![screen shot 2018-01-05 at 9 06 22 am](https://user-images.githubusercontent.com/12703638/34619695-dcdf2d02-f1f7-11e7-93cd-aeeee31547a9.png)

On the plan pages that follow the cover page:
- The Project Title should appear at the top of the first page (replace "Data Management Plan" with the Project Title in screenshot below)
- Display Section headings but NOT Questions - this creates too much clutter; users can export the template if they want to see all the question detail (remove second line of boldface text, e.g. "Types of data, samples, physical...")

![screen shot 2018-01-05 at 9 06 40 am](https://user-images.githubusercontent.com/12703638/34619960-c098cf26-f1f8-11e7-8562-e74850a165e1.png)

**Comment by briri** [comment]
@stephaniesimms I updated the cover page according to your instructions above. The layout of the abstract though looked strange since it contains HTML and did not display nicely (multiple lines, tables, lists, etc.). To solve this issue I bumped it down below the 'Project abstract:' label and indented it. I did the same with the longer 'Copyright information:' section as well to keep things consistent.

Let me know if that's ok or you'd like to take a different approach
![screen shot 2018-01-19 at 2 19 07 pm](https://user-images.githubusercontent.com/1204467/35174401-1f75c964-fd24-11e7-9b2a-d7c5b3a9c140.png)

**Comment by briri** [comment]
Updated the answers page as well (see screenshot) the 'Data Management Plan' text was the name of the phase for the template you were testing (we used that as a default during our data migration). I have updated it to show the 'project title' or 'project title - phase title' if the template has multiple phases (e.g. Horizon2020)

![screen shot 2018-01-19 at 2 26 30 pm](https://user-images.githubusercontent.com/1204467/35174683-1f1d1c5a-fd25-11e7-85fe-1e4fa6f8f6d9.png)

**Comment by stephaniesimms** [comment]
I think your solution for the abstract looks good and agree re indenting the copyright statement too. I just want to test w/bullets, italics, other formatting to make sure it doesn't go wonky (or let me know if you already did so @briri ). the answers page looks good too.

if possible can you switch to a sans serif font, ideally the same we use for PDF export?

**Comment by briri** [comment]
I'm not going to be able to insert line breaks within long sections of text @stephaniesimms since we just show whatever the user has entered in the answer/question/guidance through the tool.

**Comment by stephaniesimms** [comment]
i didn't want to or expect that we could mess w/formatting for user-provided text @briri - it's just hard to tell the root cause of various formatting issues (user or text editor/html weirdness). we can standardize the template and question formatting though i hope.

**Comment by briri** [comment]
Glad to hear it @stephaniesimms :) 
I'm able to format the PDFs as requested. I was able to do the same with the DOCX files to some extent. I cannot seem to manipulate the indentation of any of the text in DOCX unless we start using a different gem

**Comment by stephaniesimms** [comment]
overall PDF formatting is looking good @briri . after some more testing and comparison w/DMPTool I have more changes to request:
- reduce left and right margins slightly (whatever they are on DMPTool is good) to fit more text on the page
- reduce font size for answer text (again whatever we use for DMPTool is a nice guide)
- revise footer text and remove it from the cover page. page 1 should be the first page of the plan, after the cover page. new text: "Created using the %ApplicationName%. Last modified %Date%"
- i like the lines we use at top and bottom of cover page and plan pages for DMPTool (screenshot). if it's not too fussy, please add them here. at minimum we should add a line to separate the footer.

![screen shot 2018-01-24 at 3 12 44 pm](https://user-images.githubusercontent.com/12703638/35362397-083c4558-011a-11e8-9314-235353127fee.png)

![screen shot 2018-01-24 at 3 12 59 pm](https://user-images.githubusercontent.com/12703638/35362401-0d5cfe06-011a-11e8-9dca-c53dfdbf7f84.png)

**Comment by stephaniesimms** [comment]
two small change requests @briri -
- revise footer text: "Created using the %ApplicationName%. Last modified %Date%"
- if possible, page 1 should be the first page of the plan, after the cover page

**Comment by stephaniesimms** [comment]
there's a funny line in the middle of the NSF EAGER PDF but that appears to be bad/old data. downloading newly created public plans looks good. closing issue.

**Comment by sjDCC** [comment]
I got these lines too in Jose's plan and the COMET one I've just published - I think it's the border for top and bottom of page floating elsewhere.

I created a completely new plan though and the lines were where they should be so assuming it's applying this to old data. Removing from board.
