### ISSUE TITLE
Remove account recovery workflow 

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#714]
this requires more time and thought. it should be a post-MVP enhancement. it's also an edge case as users don't contact us that often to recover plans from old accounts that they can no longer access.

Remove (or comment out) recovery email field from: 
Create Account page
Edit profile page

**Comment by briri** [comment]
will remove the HTML elements so that it is no longer on each page. Will leave the column in the database table for now though since we will need to revisit at a later date.

**Comment by stephaniesimms** [comment]
visual inspection indicates removal success. closing
