### ISSUE TITLE
Functionality to get around email failing

### ISSUE THREAD

**Issue by raycarrick-ed** [DMPRoadmap/roadmap#72]
Emails frequently seem to go astray. There are 2 main scenarios we need to support: confirming a new user and resetting password. Both of these should probably be added to the admin interface (or superadmin). In the meantime I have added a function to the user model 'reset_password_link' which will generate a new link for the user and can then be emailed to them. So something like:
rails c
u = User.find_by(email: "foo@bar.com")
u.reset_password_link
"/users/password/edit?reset_password_token=ABCDEFGHIJK"
that can then be sent to the user prepended by the host (obvs) and it should work for them. This is just a utility till it gets done right.

**Comment by vyruss** [comment]
Closed by #132
