### ISSUE TITLE
Revise Org Details page 

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#726]
UX wireframe @rhu001 http://h90c3m.axshare.com/#g=1&p=dmp_organizational_profile__admin_view___tab_versi
Related issue #729  to display up to three links in Org banner

Update the Org branding fields as displayed in wireframe:

- Org full name
- Org abbreviated name (not for display in banner)
- Org URL (e.g., http://cdlib.org/services/uc3)
- Org URL link text (e.g., UC3) - up to 3 links for e.g. data policy...
- Administrator contact email (e.g., uc3@ucop.edu)
- Admin contact email link text (e.g., UC3)
- Org logo file upload
- "Organisational Configuration Information" box should be displayed only for Orgs that have configured Shib (disregard blue notepad functional spec: this should say that the text cannot be edited by Org Admins; it can be edited by Super Admins in the Super Admin area) 

For plan commenting functionality add tab section "Request Feedback" with:

- Radio button that allows admins to turn on function for users to request comments/feedback on plans
- Email subject field and message field for admins to create an auto-email message sent to users who request feedback
- Include grayed-out example text below 

Subject: [TOOL NAME] Your plan has been submitted for feedback

Message: Hello [USER NAME]. Your plan “[PLAN NAME]” has been submitted for feedback from an administrator at your organisation. If you have questions pertaining to this action, please contact us at [ORG CONTACT EMAIL].

**Comment by briri** [comment]
See #727 for Dev notes and the workflow for the Feedback process

**Comment by briri** [comment]
Updated details tab. Moved the org logo section to the top so that it appears above the URLs and contact email. It looked lonely when placed at the bottom.

Note that the 'Add an additional URL' link is not visible in the screenshot because there are already 3 URLs defined.

Updated the org branding bar at the top to use these new links

![screen shot 2017-10-25 at 11 47 24 am](https://user-images.githubusercontent.com/1204467/32017426-81714acc-b97b-11e7-9c0e-2ecd605b97fd.png)

**Comment by briri** [comment]
Added Request Feedback section. Question though regarding what the default email should be (OR do we want to require them to enter a subject and message). I am also unclear on who the intended audience is and at what point the email should get delivered.
The DMPTool uses these values for an email that is sent the owner of the plan when they click 'request feedback'. We haven't identified the need though for a similar email in Roadmap. We do want to email the Org admins (and org admin contact) when a user clicks 'Request Feedback' and another when the admin indicates that they are done providing feedback (that's 2 separate emails, so which one are we allowing them to override here?

**Comment by stephaniesimms** [comment]
@briri - page looks great. re the email, the text entered here is sent to plan owners when the click the button on Share page to Request expert feedback. at the same time a separate email is sent to Org admins and admin contact email to notify them that a user has requested feedback. that second email is being added as part of issue #727

**Comment by briri** [comment]
ok thanks for the clarification @stephaniesimms

**Comment by stephaniesimms** [comment]
@briri  - a few changes:
- Top banner should display Org name and Admin contact link text - this will be handled in related issue #729 
- Update tooltip for "Org Configuration Info" area to say: "This information can only be changed by a system administrator. Contact the Help Desk if you have questions or to request changes."
- On the "Request feedback" tab, insert the following as grayed out (sample) text:

Subject: [TOOL NAME] Your plan has been submitted for feedback

Message: Hello [USER NAME]. Your plan “[PLAN NAME]” has been submitted for feedback from an administrator at your organisation. If you have questions pertaining to this action, please contact us at [ORG CONTACT EMAIL].

**Comment by briri** [comment]
default email content changed as part of #727. Still need to update the tooltip as described above

**Comment by stephaniesimms** [comment]
@briri - all working as expected w/minor exceptions related to the auto-email:
- On the "Request feedback" tab, insert the following as grayed out (sample) text:

Subject: [TOOL NAME] Your plan has been submitted for feedback

Message: Hello [USER NAME]. Your plan “[PLAN NAME]” has been submitted for feedback from an administrator at your organisation. If you have questions pertaining to this action, please contact us at [ORG CONTACT EMAIL]. 

- the email I received from the system has HTML formatting (screenshot below). Please fix.

![screen shot 2017-11-14 at 2 22 29 pm](https://user-images.githubusercontent.com/12703638/32808589-6f9d846e-c948-11e7-9565-7d3642d58795.png)

**Comment by sjDCC** [comment]
Sample text looks good @stephaniesimms 

I assume this is what we'll send out by default too if the org-admin doesn't specify their own text?

**Comment by briri** [comment]
I am going to use '%{user_name}' and '%{plan_name}' in the tooltip instead of '[USER NAME]' and '[PLAN NAME]'. The code will automatically convert those keywords to the correct values. Is that alright?

**Comment by sjDCC** [comment]
Sounds good to me

**Comment by stephaniesimms** [comment]
yes @briri - by all means use the correct values.

**Comment by sjDCC** [comment]
Tooltip looks good. It would be nice if people could easily copy/paste it but I guess this can't be achieved as it's a hover-over

Closing out

**Comment by sjDCC** [comment]
Re-opening as I just spotted a related issue on testing.

The email out to users is still showing html

<p>Hello s.jones@arts.gla.ac.uk.</p><p>Your plan "test" has been submitted for feedback from an administrator at your organisation. If you have questions pertaining to this action, please contact us at test@test.ac.uk.</p>

**Comment by stephaniesimms** [comment]
@briri - ditto on html in the email. moving back to in progress.

**Comment by stephaniesimms** [comment]
email formatting looks good now. closing issue.
