### ISSUE TITLE
Add "Request expert feedback" to Share plan page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#727]
UX wireframe @rhu001 http://h90c3m.axshare.com/#g=1&p=write_plan (see Share tab)

- Add "Request expert feedback" section at bottom of page
- This is an optional feature that should only appear if an Org Admin has turned it on (from the Org details page - related issue #726 )
- Add auto email text below; trigger when user clicks button to "Request feedback"

Email title: [TOOL NAME]: [USER NAME] requested feedback on a plan

Hello [USER NAME]

[USER NAME] has requested feedback on a plan [“PLAN TITLE”]. To add comments, please visit the ‘Plans’ page under the Admin menu in [TOOL NAME] and open the plan. 

All the best
The [TOOL NAME] team

You may change your notification preferences on your profile page. Please do not reply to this email. If you have any questions or need help, please contact us at [HELPDESK EMAIL] or visit [CONTACT US URL].

**Comment by briri** [comment]
**Dev Notes:**
- This will require a way for us to store whether or not this feature is on/off on the `orgs` table.  
- We will also need a place to store a feedback status enum on the `plans` model table.  Statuses needed: Off/nil, Feedback pending, Feedback in progress, Feedback complete (see below for workflow)
- The org details page will need to allow the org_admin the ability to set this value
- Add the button to the write plan page and trigger the email notification. 

**Workflow:**
_Assuming the org admin has enabled this feature in the org details screen_
1. User creates a plan and fills out their answers. 
2. User clicks the 'Request expert feedback' button on the Share plan page (should only be visible to owner/co-owners)
3. Email is sent to the Org Admins for that user's org. The plan's feedback status is set to 'pending'.
4. Org Admin receives email (will also see a notification on their dashboard ... in an future ticket)
5. Org Admin reviews the plan (commenting only ... not editing answers) and provides comments. 
6. When Org Admin attempts to leave the page a modal opens asking them to indicate whether they are still reviewing or have completed the feedback process (see #728) Which sets the `plans.feedback` status to either in progress or complete.
7. If the Org Admin has finished providing feedback an email (see #728) is sent to the owner/co-owners

**Comment by briri** [comment]
We need to determine what email is being overridden on the Org Admin's Org details page. They we will need to make sure that the hooks are put into place to send out the appropriate emails. See PR #776 
Possible emails: 
- Email to plan owner(s) explaining feedback process (triggered when they click 'request feedback')
- Email to Org Admins and Org's admin contact to let them know that a plan was submitted for feedback (triggered when they click 'request feedback')
- Email to plan owner(s) when Admin has finished providing feedback

**Comment by stephaniesimms** [comment]
@briri 
#776 should trigger the first email in this list, when a user clicks to "request feedback"
#727 (this ticket) should trigger the second email in the list to notify Org admins that feedback was requested
#728 modal for Admin to indicate they are "done" providing feedback should trigger third email

each of these issues contains the appropriate email text. let me know if i should rearrange or clarify anything.

**Comment by briri** [comment]
@stephaniesimms, who should be able to see/click the request feedback button? The owner or can co-owners request it as well?

**Comment by stephaniesimms** [comment]
@briri - owner and co-owners. as long as they are affiliated w/an org that has enabled the request feedback option in Org details. so the request gets routed to the org admin contact for whomever clicks the button.

**Comment by briri** [comment]
Added button to bottom of share plan page. Button is only visible to Plan owners/co-owners and if the Org has enabled this functionality.
Clicking the button updates a new flag on the plan record `plans.feedback_requested` which will be used to display plans needing feedback to the org admins on their Admin -> Plans page. When the admin finishes their review and confirms the modal from #728 this flag will be set back to false

**Comment by stephaniesimms** [comment]
hooray @briri - this is working as expected w/the minor exception of email formatting. it's coming through w/unsightly HTML (screenshot below).

![screen shot 2017-11-14 at 2 22 15 pm](https://user-images.githubusercontent.com/12703638/32808311-72bb4362-c947-11e7-9d11-7d09a89a9dfa.png)

**Comment by sjDCC** [comment]
All worked fine for me too. html now fixed on emails out to admins - closing out
