### ISSUE TITLE
Update existing email notifications text

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#731]
Existing email notifications that need to be updated with revised and standardized text in doc:
https://docs.google.com/document/d/1Zt3QfPZ2q6yMOCVFOevXviwRX-XbZeGSxAAvbRa9w-M/edit

- 2 from devise gem
- existing email text

**Comment by briri** [comment]
Also make sure that we are checking the user's preferences before sending the message!

**Comment by jollopre** [comment]
The email messages have been modified accordingly. @stephaniesimms, you can preview all, except devise related, at:

- `<YOURDOMAIN>/rails/mailers/user_mailer/welcome_notification`
- `<YOURDOMAIN>/rails/mailers/user_mailer/sharing_notification`
- `<YOURDOMAIN>/rails/mailers/user_mailer/permissions_change_notification`
- `<YOURDOMAIN>/rails/mailers/user_mailer/api_token_granted_notification`

**Comment by stephaniesimms** [comment]
@jollopre - updated email text looks good, but [HELPDESK EMAIL] value is missing in final line of each email (see screenshot). "...please contact us at [HELPDESK EMAIL] or visit..."  For roadmap stage the helpdesk email address should be uc3@ucop.edu

![screen shot 2017-11-13 at 12 13 44 pm](https://user-images.githubusercontent.com/12703638/32747028-60f05996-c86c-11e7-9746-a212c6c34e07.png)

**Comment by briri** [comment]
this is a configuration setting in the branding.yml file. I just added the helpdesk_email. It should be working now @stephaniesimms

**Comment by stephaniesimms** [comment]
yes now it's working as expected. thanks @briri . closing issue.
