### ISSUE TITLE
Add email notice for new Comments (not admin feedback)

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#733]
Email title: [TOOL NAME]: A new comment was added to [PLAN TITLE]

Hello [USER NAME]

[COMMENTER NAME] has commented on the plan [“PLAN TITLE”]. To view the comments, please visit the My Dashboard page in [TOOL NAME] and open your plan. 

All the best
The [TOOL NAME] team

You may change your notification preferences on your profile page. Please do not reply to this email. If you have any questions or need help, please contact us at [HELPDESK EMAIL] or visit [CONTACT US URL]

**Comment by jollopre** [comment]
I have assumed that the owner of the plan is the one who receives the mail regarding a new comment. The view can be tested at <HOSTNAME>/rails/mailers/user_mailer/new_comment

**Comment by stephaniesimms** [comment]
you assumed correctly @jollopre!  i'll wait for the PR to test

**Comment by stephaniesimms** [comment]
I can't add or save comments to test this now. When I create a new plan the Comments field will only display if there is no Guidance (screenshot - first question show Comments tab highlighted but no editor field). Where there is a Comments field, I can enter text but clicking Save does nothing (screenshot - second question can't save comment).

![screen shot 2017-11-13 at 3 59 16 pm](https://user-images.githubusercontent.com/12703638/32755762-a361b99a-c88b-11e7-9e85-ad6d707ef8cb.png)

**Comment by jollopre** [comment]
@stephaniesimms, I have fixed that problem, not related to the issue though, so you should be able to add a comment and see whether or not ONLY the owner receives an email.

**Comment by briri** [comment]
Same thing as #732 

contact_us_url is not in the branding.yml file nor should it have to be if the installation wants to use the application's built in contact us page. This line overrides Rails' built-in url helper: `contact_us_url = Rails.configuration.branding[:organisation][:contact_us_url]`

I updated this line in the other mailers to use Rails' built-in helper if an override is not defined in the yaml file. Will submit a PR to correct this one.

**Comment by jollopre** [comment]
@briri, I think it would be easier to change the local variable contact_as_url to something that that not override any url helper from Rails. At least it's safer.

**Comment by sjDCC** [comment]
Yes, seems to just be emailing out to the owner as expected. Closing out

**Comment by stephaniesimms** [comment]
sorry i missed your note earlier @jollopre to clarify who should receive emails - it should be the plan owner and all co-owners. please update to include co-owners.
