### ISSUE TITLE
Broken links in institutional header

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#735]
The links to the RDM policy and RDM info don't resolve anywhere. They shouldn't show if nothing has been added.
![broken links](https://user-images.githubusercontent.com/6169940/31662512-8bc5217e-b336-11e7-89c3-5f224966cd94.PNG)

**Comment by vyruss** [comment]
These are just placeholders for now. I'll add in the code to make them functional (duplicate of #729 )
