### ISSUE TITLE
Template filtering issue?

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#736]
Too many templates are being presented as options to select from when creating a CRUK plan. Is it missing a filtering step to only show published versions perhaps?

![template-selection](https://user-images.githubusercontent.com/6169940/31662656-38128dea-b337-11e7-90e9-3dc20e218c61.png)

**Comment by briri** [comment]
Yes, I noticed this when addressing another issue on this page and fixed. The correction was just deployed, please retest and let me know if it looks ok now.

**Comment by sjDCC** [comment]
Looks good @briri, except it brings up the additional template dropdown in all cases. This should only present when there is more than 1 to select from.

Thanks for this though - speedy work!

**Comment by stephaniesimms** [comment]
second dropdown displays 2 CRUK templates now, consistent w/DMP Templates list. issue seems to be resolved. closing.
