### ISSUE TITLE
Standardize functionality to Select an Org

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#740]
The same functionality to select an org should be used on Create Account and Edit Profile pages

- Initial step should prompt user to either Begin typing to see a filtered list (grayed out text in box) OR present a link to "Select an organisation from the list" 
- Clicking "Select an org..." should open the full list - currently clicking the link does nothing
- "My organisation isn't listed" should appear at the top of the list
- If user selects "My org isn't listed" the field should auto-populate with "Other" 

On Create Account page:

![screen shot 2017-10-11 at 9 47 13 am](https://user-images.githubusercontent.com/12703638/31454152-5046895c-ae69-11e7-8a92-c5d2ae721203.png)

On Edit Profile page:

![screen shot 2017-10-11 at 9 50 12 am](https://user-images.githubusercontent.com/12703638/31454253-b270ce8a-ae69-11e7-94c7-88ac8718b503.png)

**Comment by briri** [comment]
**Dev notes:**
There seems to be something wrong with the linkage between the autocomplete dropdown box and the 'other org' textbox on the create plan page. 

Use the setup on the edit profile page as an example. The link should be 'My organisation isn't listed' when the autocomplete box is available. When the user clicks this, the autocomplete should be hidden and the other org textbox should become visible and the link should change to read 'Select an organisation from the list'

**Comment by stephaniesimms** [comment]
@briri When I click "My org is not in the list" I get a different link that says "Select an org from the list" - and when I click this link it switches back to "My org is not in the list" - I never get a box prepopulated with "Other"

This behavior occurs on both the Create account and Edit profile pages. At least it's consistent.

**Comment by briri** [comment]
Hi @stephaniesimms, perhaps I was unclear on how this org/other org should work, or maybe its just confusing or unclear with the current implementation. The autocomplete box and textbox do look very similar.
Here is how I set it up:
If the user opens the page and they already have an 'Organization' defined they will see:
![screen shot 2017-10-26 at 8 25 45 am](https://user-images.githubusercontent.com/1204467/32061877-bcad0200-ba27-11e7-8b9b-897db8c4c13c.png)
If the user opens the page and they already have an 'Other Organization' they will see:
![screen shot 2017-10-26 at 8 26 17 am](https://user-images.githubusercontent.com/1204467/32061934-e8a69466-ba27-11e7-9ef5-1a9842a72255.png)

The 1st one is the autocomplete box, and the entry must match one of the items in the list. The selection has significance in the database (link to templates, plans, etc.).
The 2nd one is a regular textbox, whose entry can be anything. That one has no real significance in the database. They unfortunately need to be separate controls.

I decided to toggle between the two when the user clicks on the link. Perhaps the language is just confusing or there's a better approach.
Would adding the 'Other' text to the textbox (Other Organization) version be helpful along with some wording changes on the 'Select the organization from a list' link? What that link really does is swap the autocomplete box back in.

**Comment by briri** [comment]
Hey @stephaniesimms so the 2 links 'My org is not in the list' and 'Select an org from the list' currently allow you to toggle back and forth between the 'Other Org' textbox and the 'Org' autocomplete box. Both of the controls are identical though so its not very intuitive.

I can add a default of 'Other' to the other org box and we can change the name of the 'Select an org from the list' to something that makes it a bit clearer that its switching back to the autocomplete.

I really wish we could just use one box that served both purposes there. There would be no way to determine though if the text the user entered was a legitimate other organization or if they had just started typing but didn't select an item from the list (e.g. if you start to type 'UCOP' and then tab off without actually selecting 'University of California - Office of the President (UCOP)'.

**Comment by sjDCC** [comment]
Is there a reason why we're not using what is currently in the MVP 0.3 release?

Current functionality on DMPonline is to select the org from the dropdown. If the user clicks that "My organisation isn't listed" it defaults to 'Other' and gives them a text box to enter.

See two screengrabs below:

![step1](https://user-images.githubusercontent.com/6169940/32378510-d6b3a754-c0a2-11e7-8964-2209eff045a8.PNG)
![step2](https://user-images.githubusercontent.com/6169940/32378512-d6cb77c6-c0a2-11e7-9fc3-eb53a5b1fcf2.PNG)

**Comment by briri** [comment]
No, and I'll be changing it back. DMPTool is going to just default the other org value to 'Other' so I was trying to come up with a solution that would work in both scenarios. After some trial and error here we have decided that we'll just need to default it and hide the link/textbox on our installation. I'll be setting this back to the way it currently works (hopefully later next week)

**Comment by sjDCC** [comment]
Great, sounds good. Thanks @briri

**Comment by sjDCC** [comment]
Looks good @briri 

Two things I noticed, but not sure if this needs any action:
- The organisation field doesn't default to 'Other' when the user clicks 'My organisation isn't listed' but I guess this is just the nature of the box style as it's not a dropdown. I assume the value is still recorded on the backend?
- I noticed we asked them to type their password twice on DMPonline. Is it worth retaining this in case of typos? We often had people saying they'd not received the validation email only to find that they'd misspelled their address

![password-confirmation](https://user-images.githubusercontent.com/6169940/33025962-3c8981f4-ce07-11e7-926e-d730245b55c3.PNG)

**Comment by sjDCC** [comment]
@stephaniesimms could you confirm your preferences on this - should the password be entered twice on account creation? 

@vyruss I expect the dropdown can't default to 'Other' give the new box type we have so this is maybe fine to close out as is currently?

**Comment by briri** [comment]
Yeah, @vyruss is correct. The autocomplete box can't default to 'Other' since its not a value in the list. We could add it to the list but it's unlikely that users would know to start typing 'Other' to get the other organisation box to appear

**Comment by stephaniesimms** [comment]
the "Show pw" toggle (screenshot below) is there to allow users to check what they typed and prevent errors. general UX recs are not to ask users to enter the pw twice so if you're okay with it my preference is to keep things simple.

![screen shot 2017-11-27 at 12 57 04 pm](https://user-images.githubusercontent.com/12703638/33288848-7bda3914-d372-11e7-9e78-ad01852cd2bf.png)

**Comment by sjDCC** [comment]
Sounds fine. Closing this out then
