### ISSUE TITLE
Remove "question not answered yet" message

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#742]
- Remove yellow message bar beneath each question "question not answered yet"
- Only display a blue timestamp message once a user enters text or makes a selection for another question type (radio button) and the system auto-saves it

![screen shot 2017-10-17 at 2 35 47 pm](https://user-images.githubusercontent.com/12703638/31690763-88f9020a-b348-11e7-9c61-56e22b822a4e.png)

**Comment by stephaniesimms** [comment]
the issue w/"question not answered" message is resolved @jollopre 

but now I receive an autosave "question answered" message even if I don't enter anything into the text editor (screenshot below). desired behavior is to only autosave and generate a message if user enters something.

![screen shot 2017-10-22 at 4 33 43 pm](https://user-images.githubusercontent.com/12703638/31862955-234d00d4-b747-11e7-94d7-d49b0e8a6535.png)

**Comment by stephaniesimms** [comment]
tested again and i'm still getting a "question answered" autosave message even if I don't enter anything into the text editor (screenshot below). desired behavior is to only autosave and generate a message if user enters something. 

a new issue is that the message begins counting the seconds since i "answered" the question. i'm not sure what interval it used before (minutes?) but the second counter is distracting and not necessary.

![screen shot 2017-10-24 at 11 21 01 am](https://user-images.githubusercontent.com/12703638/31934963-dcd7dc4c-b8ad-11e7-8cb9-d25ad18edb63.png)

**Comment by jollopre** [comment]
@stephaniesimms I have replaced the seconds counter message by a more static one 'less than a minute ago'. In regards to autosaving an empty question, this could be related to the issue #530 which I'm going to tackle at some point.

Could you create a new plan in order to see if that behaviour still remains for you? I could not replicate it.

**Comment by stephaniesimms** [comment]
thanks for replacing the seconds counter @jollopre 

i created new plans in different browsers (Chrome, Firefox) and w/different accounts. all of them exhibit the same issue. when i click inside the text editor and then move focus away it triggers autosave even if i haven't entered anything into the box

![screen shot 2017-10-24 at 5 26 55 pm](https://user-images.githubusercontent.com/12703638/31952432-de35193c-b8e0-11e7-8a8b-00d787e33253.png)
 (screenshot)

**Comment by jollopre** [comment]
@stephaniesimms that makes more sense! The auto-save is triggered whenever the editor loses the focus but does not check whether or not the text is empty.

**Comment by stephaniesimms** [comment]
glad my explanation is clearer now. if you can make the editor check to see if the user inputs text (or for radio buttons and check boxes if they make a selection) that would be super! if the user does nothing then the system should not autosave (since there's nothing to save).

**Comment by stephaniesimms** [comment]
glad i was able to explain the issue more clearly now @jollopre . if you can make the editor check to see if the user inputs text (or for radio buttons and check boxes if they make a selection) that would be super! if the user doesn't input anything as an answer then the system shouldn't trigger autosave (since there's nothing to save).

**Comment by stephaniesimms** [comment]
the time counter is fixed (no more seconds) but the autosave issue is not fixed. when i click inside an empty text editor and then move focus away it still generates an autosave message (screenshot). i can't test on a new plan at the moment owing to #777 

![screen shot 2017-10-26 at 9 35 11 am](https://user-images.githubusercontent.com/12703638/32041054-1aa5c44a-ba33-11e7-8b0f-939d1762d35c.png)

**Comment by jollopre** [comment]
@stephaniesimms the autosaving blank is not fixed yet, the PR only fixed the seconds. I will let you know when is done. Thanks.

**Comment by jollopre** [comment]
@stephaniesimms now it should not autosave unless the content within the editor has changed.

**Comment by stephaniesimms** [comment]
everything working as expected now! thanks @jollopre - closing issue.
