### ISSUE TITLE
CSS refinements

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#746]
Now that the Bootstrap overrides are in place on roadmap-stg we should begin another round of review. @dsisu, @sjDCC and @stephaniesimms please take a look at the site now and record any refinements to color, fonts, borders, spacing, alignment, etc. in this ticket.

**Comment by stephaniesimms** [comment]
- Action menus in tables are cut off on right and bottom of page when user clicks to open the menu (screenshots 1-3)
- When resizing pages on different browsers/devices, the footer wraps and obscures things at bottom of page (e.g., Save, Cancel buttons on Template editing pages, screenshots 4-5) 
- Template editing pages/workflow in Admin area need help - not sure what the desired behavior is but they are extremely confusing (create separate issue for this)

1- Guidance page - Actions menu cut off at bottom of table
<img width="1173" alt="screen shot 2017-10-18 at 12 35 42 pm" src="https://user-images.githubusercontent.com/12703638/31790232-aad9ee48-b4c9-11e7-9170-35051e41d343.png">


2- Guidance page - Actions menu cut off at bottom and side of table, need more space between table and footer
<img width="1189" alt="screen shot 2017-10-18 at 12 36 31 pm" src="https://user-images.githubusercontent.com/12703638/31790247-ae0b4c10-b4c9-11e7-9d49-a094fa4a9cc9.png">


3- Templates page - same problems with Actions menu and footer
<img width="1219" alt="screen shot 2017-10-18 at 12 37 37 pm" src="https://user-images.githubusercontent.com/12703638/31790254-b0961adc-b4c9-11e7-88de-ffcfce89b468.png">


4-5 Templates page - Save, Cancel buttons obscured by footer when resizing page
<img width="800" alt="screen shot 2017-10-19 at 10 59 21 am" src="https://user-images.githubusercontent.com/12703638/31790470-6b5eadca-b4ca-11e7-99de-c307893b8c1c.png">

<img width="747" alt="screen shot 2017-10-19 at 10 59 35 am" src="https://user-images.githubusercontent.com/12703638/31790476-6fa908d0-b4ca-11e7-9fb5-2b49332da30b.png">

**Comment by briri** [comment]
Looks like `btn-default` and `btn-primary` have different top margin settings. They should be the same
![screen shot 2017-10-27 at 11 12 35 am](https://user-images.githubusercontent.com/1204467/32118877-315e8c64-bb08-11e7-892d-bf4c65732027.png)

**Comment by briri** [comment]
This is happening in Chrome on my laptop. not sure if its happening in other browsers. I have not noticed it on my large iMac monitor. 
It looks like when the text in the footer is long and causes the navbar to wrap. This causes the footer to sit on top of the bottom portion of the page hiding the 'Save' button

![screen shot 2017-10-27 at 2 57 02 pm](https://user-images.githubusercontent.com/1204467/32126802-7412af08-bb27-11e7-91d4-8d4602be4245.png)

This should be easily reproducible by manually resizing your browser window

**Comment by briri** [comment]
Update colors of notice/alert messages to match those on the current DMPonline site.

**Comment by briri** [comment]
the error message on the forgot password page is not the correct color (any color) when you enter an email that is not in the system

**Comment by bhavi** [comment]
Wud it makes sense to either use btn-default or btn-primary across the app? We are overwriting the styling anyway.

**Comment by briri** [comment]
yeah we should use those two classes across the site.

**Comment by jollopre** [comment]
@bhavi for the refactor I made, I used btn-default since it is colourless

**Comment by stephaniesimms** [comment]
@bhavi - some minor tweaks:
- left justify the tooltip text (instead of current centered format)
- footer still wraps and obscures action menu items at bottom of page when you resize the window even slightly in Chrome and Firefox (screenshot for My Dashboard). not sure if any more can be done about this? the action buttons (Save) remain visible at least.

![screen shot 2017-11-22 at 2 03 21 pm](https://user-images.githubusercontent.com/12703638/33151718-1a39110e-cf8e-11e7-875a-56a9d3eb36a4.png)

**Comment by sjDCC** [comment]
Can anything be done to make the actions in the write plan banner look more like tabs or buttons? Perhaps introduce a line between each?
![tab](https://user-images.githubusercontent.com/6169940/33172510-649f87e0-d048-11e7-8023-0c6bd7312bb3.PNG)
![tabs](https://user-images.githubusercontent.com/6169940/33172518-68655fc6-d048-11e7-8740-d618fb56eaaf.PNG)

**Comment by sjDCC** [comment]
A couple of other minor things I noticed - some spacing on the create plan page

![create-plan](https://user-images.githubusercontent.com/6169940/33173015-4a9468f0-d04a-11e7-961c-c88a4a7b37aa.PNG)

And guidance / comments boxes could do with some visual boundaries
![testing-phases-2](https://user-images.githubusercontent.com/6169940/33173024-5e70f38e-d04a-11e7-916c-49f6f7b8ae39.PNG)

**Comment by sjDCC** [comment]
I think the spacing could be improved on the edit / write plan page

![spacing](https://user-images.githubusercontent.com/6169940/33173466-2d4e1fe6-d04c-11e7-9027-de6564da2929.PNG)

**Comment by sjDCC** [comment]
We are likely to reinstate a grey background to keep the look and feel as close to DMPonline currently as possible. Trying to visualize this, it seems all the content within each page is much to close to the edge to allow a line to be drawn. Can each page shift in a small margin and a border be displayed please?

![picture1](https://user-images.githubusercontent.com/6169940/33174670-ead27fe0-d050-11e7-924a-8efd0e65bd22.png)
![picture2](https://user-images.githubusercontent.com/6169940/33174671-eae68986-d050-11e7-9d0b-aef172c5a284.png)

**Comment by sjDCC** [comment]
Can the logos in the footer be transparent white ones rather than coloured blocks please? Here's a white version of the DCC one.

![dcc logo cmyk white gif](https://user-images.githubusercontent.com/6169940/33175240-007aff14-d053-11e7-81e2-66d20c3f0683.gif)

**Comment by briri** [comment]
Yes absolutely. @stephaniesimms do we have a white version of the UC3 logo?

**Comment by stephaniesimms** [comment]
@sjDCC I created a new issue to capture new requests and transferred your comments #867 - we can all continue adding to it for a new round of customizing bootstrap.

@bhavi after you make the minor changes I noted above we can close this one out.

**Comment by stephaniesimms** [comment]
the two changes noted above still haven't been made. @bhavi please:

- left justify the tooltip text (instead of current centered format)
- footer still wraps and obscures action menu items at bottom of page when you resize the window even slightly in Chrome and Firefox (screenshot for My Dashboard). not sure if any more can be done about this? the action buttons (Save) remain visible at least.

![screen shot 2017-11-22 at 2 03 21 pm](https://user-images.githubusercontent.com/12703638/33151718-1a39110e-cf8e-11e7-875a-56a9d3eb36a4.png)

**Comment by stephaniesimms** [comment]
looks good on roadmap stage. closing issue.
