### ISSUE TITLE
Add notifications section to My Dashboard

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#755]
Wireframe: http://h90c3m.axshare.com/#g=1&p=my_dashboard

Add the notifications section to the top of the My Dashboard page. This will require us to begin recording when notifications have been sent out. Once the plan associated with a notification has been viewed by the user we should stop displaying that notification.

**Comment by briri** [comment]
Likely related to #760

**Comment by stephaniesimms** [comment]
global notifications feature added. closing issue.
