### ISSUE TITLE
Place all third party libraries into vendor.js

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#756]
There are some third party libraries that we are loading them in application.js:

- tinymce
- timeago.js
- jquery-ujs (unobtrusive JS for rails) 

Ideally we should move them to vendor.js which should not change often and therefore can be cached by the browser. These changes should be made at lib/assets/webpack.config.js

**Comment by briri** [comment]
@jollopre I think we can close this one out but wanted to verify with you first. if its all done go ahead and close this

**Comment by briri** [comment]
this is no longer relevent
