### ISSUE TITLE
Add a job queue system to handle email digests

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#760]
Introduce a job queuing tool like Resque or Sidekiq and create a Rails job to send out email digests.
- Select a queuing backend (allow it to be customizable per installation)
- Create email digest job(s)
- Create the email digest mailer
- Determine if the work done here can be tied into the 'My Dashboard' notifications section as described in #755 (A notifications table would likely be useful for this)
- Allow users to define whether they want to receive emails in a digest format or individually. The default would be to use the digest. Is it safe to just have one 'daily' option rather than offering 'every 12 hours', 'weekly', etc.?

**Comment by briri** [comment]
tabling this until post-MVP

**Comment by magdalenadrafiova** [comment]
@briri is this still relevant? I thought administrators are receiving emails on a regular basis now

**Comment by briri** [comment]
this was an old ticket to update the system to send a digest style email at the end of the day instead of multiple emails throughout the day. Not sure if we still want to do that or not. It would be quite a bit of rework on our part.

**Comment by xsrust** [comment]
I think if we have other use-cases to add Rescue/sidekiq it'd be nice to re-do the emails as a digest,
But I'd not want to add the reddis dependency unless we were making other use of it.
