### ISSUE TITLE
Revise Edit user privileges functionality

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#761]
UX wireframe @rhu001 "DMP User Accounts (Admin View)" 
Additional privileges are visible to Super Admin users (related issue #794)
For example, an Org Admin at UCSF should see a list of UCSF users in the table. When the admin clicks the Edit link she's presented with the modal in the screenshot below and can assign Org admin privileges to any user. 

![screen shot 2017-10-30 at 12 42 48 pm](https://user-images.githubusercontent.com/12703638/32191942-f8d8f6d0-bd6f-11e7-845d-d9185b6ea4ee.png)

DMP Edit User Role - modal 
![screen shot 2017-11-02 at 12 55 59 pm](https://user-images.githubusercontent.com/12703638/32347800-0cf2f90c-bfcf-11e7-8560-209cde6c5d9c.png)

- Update page heading to "User accounts"
- Add search box above table (this will be done as part of #815)
- Table functional spec: limit visibility to 10 rows, thereafter implement pagination (also #815)
- Update column names as in wireframe
- Add column for "Current privileges" before "Edit" column
- For display purposes in the "Current privileges" column there are two buckets: 1) Org admin privileges, 2) Super admin privileges. If a user has any individual privileges in either of these buckets, then display the high-level bucket name in this column. So, e.g., if I can "Manage user templates" then this column should say that I have "Org admin privileges." If I can also "Grant API access" then this column should also say that I have "Super admin privileges"
- For users with no Org or Super admin privileges, the "Current privileges" column should be blank
- Blue notepad functional spec: Clicking on Edit link should open a modal that allows admins to assign privileges to other users (second UX wireframe screenshot above)
- Ticking the first box for "Org admin privileges" should automatically tick all boxes below it; these can then be deselected individually if desired
- Note: add one more privilege tickbox at the end of the Org Admin column to "Use API" (missing from wireframe)

For clarity, here are the descriptors currently used in the database, grouped by the two roles; these should be mapped to the language in the modal screenshot above:

**Org admin**
Grant_permissions
Modify_templates
Modify_guidance
Change_org_details
Use_api

**Comment by stephaniesimms** [comment]
main functionality is working as expected @bhavi - i just have some minor changes to request:
- after user clicks either the "Save" or "Back" button on the modal please reload the main User Accounts page to the "View All" expanded list. current behavior takes me back to the paginated list and I have to click View All, then search for the user to confirm the changes to privileges.
- remove the line breaks/shrink the space between tickboxes in the modal to tighten things up (screenshot)
- only capitalize first word for modal heading "Edit user privileges" (screenshot below)
- in "Current privileges" column for the main users table, change text to "Organisational Admin" and "Super Admin" (remove "privileges" to save space, but spell out Organisational)
- spell out "Organisational" in the modal also - Organisational admin privileges (screenshot)

![screen shot 2018-01-22 at 10 10 56 am](https://user-images.githubusercontent.com/12703638/35236550-9722859e-ff5c-11e7-821a-9d40d5193062.png)

**Comment by sjDCC** [comment]
hi @stephaniesimms @bhavi. Can we reconsider using a modal here please? In the original functionality the 'edit' link took you to a separate page where you could assign privileges for that user and save changes. This redirected you back to the user page and confirmed changes had been saved.
![user-privileges](https://user-images.githubusercontent.com/6169940/35269593-6307ea56-0024-11e8-8627-ebf2c61bb603.PNG)

Modal windows are considered a bad practice and only used for rare occasions so it'd be better to stick with the original functionality. The confirmation notification would provide what you're looking for on page reload too and allow us to present the typical paginated view rather than load all users, which could be a performance drain, particularly in the case of super-admin changes.

**Comment by stephaniesimms** [comment]
modals are intended to reduce interruption when performing quick tasks such as this, but only if designed well. this is why i asked to reload the page with the expanded list of users so it's easy to confirm at a glance that the privileges are granted. devs confirmed that there is no performance concern. but if we can't achieve a quick and easy workflow then i'm fine with going back to using a separate page.

**Comment by stephaniesimms** [comment]
repeating this comment here so you don't have to scroll up. main functionality is working as expected @bhavi - i just have some minor changes to request:
- after user clicks either the "Save" or "Back" button on the modal please reload the specific page in the User Accounts list where that user appears. current behavior takes me back to the beginning of the paginated list and I have to click View All, then search for the user to confirm the changes to privileges. desired behavior is to be able to quickly glance and see that the privileges were added. 
- remove the line breaks/shrink the space between tickboxes in the modal to tighten things up (screenshot)
- only capitalize first word for modal heading "Edit user privileges" (screenshot below)
- in "Current privileges" column for the main users table, change text to "Organisational Admin" and "Super Admin" (remove "privileges" to save space, but spell out Organisational)
- spell out "Organisational" in the modal also - Organisational admin privileges (screenshot)

![screen shot 2018-01-22 at 10 10 56 am](https://user-images.githubusercontent.com/12703638/35236550-9722859e-ff5c-11e7-821a-9d40d5193062.png)

**Comment by jollopre** [comment]
@bhavi note that if the controller action behind Save is ajaxable, you will not need to refresh the list of users page in the position where the user privileges where edited.

**Comment by stephaniesimms** [comment]
The same weird behavior is happening when I try to grant top-level Org Admin privileges as an Org Admin (described in related issue #794 ). After the first attempt, all subsequent changes behave as expected.

One change specific to editing privileges as an Org Admin:
- I should not be able to click and edit privileges for a Super Admin. Please remove/disable the Edit link next to records for Super Admin users (screenshot below)

![screen shot 2018-02-01 at 10 09 27 am](https://user-images.githubusercontent.com/12703638/35695142-80d2b3fc-0738-11e8-9854-97a84804de29.png)

**Comment by briri** [comment]
updating so that Org Admins cannot change privileges for a super admin and an Org Admin can only grant/revoke privileges they themselves have. For example if an Org Admin is setup to only administer templates, then they cannot give permission to another user to administer guidance.

**Comment by stephaniesimms** [comment]
everything working as expected for Org Admin privileges. closing issue.
