### ISSUE TITLE
Create a test that verifies configuration elements

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#77]
Create a test that checks for the existence of all the initializer and yaml config files. 

It should also check to ensure that any magic strings in the locale files match the values in the database.

**Comment by briri** [comment]
Can't effectively test for magic string values or identifier scheme values since we run against a test DB. Could add checks for this to the app startup but since we cannot guarantee that the underlying tables exist at run time we could encounter errors during the 'rake db:migrate' process. 

I saw this when attempting to put IdentifierScheme checks into the application.rb. When trying to install the system on a clean instance the system was unable to run the db migration scripts because it was attempting to check for the tables before they had been created.

**Comment by vyruss** [comment]
Should close as it is mostly covered by missing translation check and near-elimination of magic strings?

**Comment by briri** [comment]
agreed. this test is in place
