### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#771]
Updates required for:
- wiki docs to include webpack instructions and importance of removing the asset pipeline from local `config/environments/*.rb` files
- docs to recommend using utf8mb4 for mysql. Also update the database.yml example to recommend this too

**Comment by briri** [comment]
Also need to add the need to have a default template discussed in the docs as well (see #376). We should add this to the troubleshooting document, the seeds.rb to ensure that it's template is marked as default and then confirm that its either handled in the db migration scripts from DMPOnline_v4 or at least mentioned as a manual process

**Comment by stephaniesimms** [comment]
documentation on translation process in Pootle needed: how do we get the translations out of Pootle and into the system so people understand the workflow (i.e., if they make changes in Pootle why doesn't it appear immediately in Roadmap?)

**Comment by briri** [comment]
- updated the installation guide
- translation pages created 
-added language maintenance to the admin guide 
- updated the branding guide

**Comment by stephaniesimms** [comment]
documentation is looking good @briri - thank you mucho
