### ISSUE TITLE
Template description shows both textbox and tinymce

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#772]
the Description field should be a text editor. remove the form field that displays over the editor (see correct version from DMPonline screenshot below).

Roadmap: Create New Template page 
![screen shot 2017-10-24 at 11 34 29 am](https://user-images.githubusercontent.com/12703638/31935610-8ca30498-b8af-11e7-8313-dfeb7a13aef3.png)

DMPonline: Create New Template page
![screen shot 2017-10-24 at 11 36 57 am](https://user-images.githubusercontent.com/12703638/31935720-d81ba15a-b8af-11e7-9c09-7b2e145476b6.png)

**Comment by stephaniesimms** [comment]
working as expected. closing issue.
