### ISSUE TITLE
No templates available to create a new plan

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#777]
I can click through the wizard to create a new plan but no template is served up. When I tick the box that no funder is associated I should get the default template but there is no Write Plan tab (screenshot 1). If I select a funder template I get a json message w/the template ID (screenshot 2).

![screen shot 2017-10-26 at 9 36 20 am](https://user-images.githubusercontent.com/12703638/32040558-91776bfc-ba31-11e7-95a8-1b6c19cb9022.png)

![screen shot 2017-10-26 at 9 37 14 am](https://user-images.githubusercontent.com/12703638/32040569-98e101dc-ba31-11e7-84e3-c5f7e893b1a6.png)

**Comment by briri** [comment]
This seems to be working for me now. I think one of the other PRs must have broken and then fixed it again. Please check again on stage

**Comment by stephaniesimms** [comment]
@briri this is still not working for me. i get the same kinds of errors noted above for default template and just some json info for any other template.

**Comment by stephaniesimms** [comment]
copying our slack comments over - default template is working now but the issue persists w/funder templates. based on the screenshot of the Template page below (note N/A status) it looks like a separate piece of template work may be causing the issue...

![screen shot 2017-11-01 at 2 27 34 pm](https://user-images.githubusercontent.com/12703638/32300116-49583782-bf15-11e7-8c19-adad5c3ee311.png)

**Comment by stephaniesimms** [comment]
this is working as expected now. closing issue.
