### ISSUE TITLE
Customise funder templates issues

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#791]
I spotted a couple of issues when customising a funder template. Users are given the option to add a phase but this shouldn't exist. They can only add sections and annotations. 

The 'Show phase' button here should perhaps be rephrase as 'Edit' or 'Customise' so people know where to click to customise?
![phase-add](https://user-images.githubusercontent.com/6169940/32337964-550f2442-bfeb-11e7-995c-9c44a8482e2c.PNG)

Also, the buttons to add annotations (example answers and guidance) are missing. Guidance isn't showing in the panel to the right. This usually shows on the edit mode when customising.
![missing buttons](https://user-images.githubusercontent.com/6169940/32338127-cfcd5794-bfeb-11e7-8c84-6fc7044e66d3.PNG)
![annotations-button](https://user-images.githubusercontent.com/6169940/32338133-d3a1ebd2-bfeb-11e7-9009-c9b140accd74.PNG)

The section heading areas are also missing + or - icons so people may not realise you click to open

**Comment by bhavi** [comment]
Currently "Add new phase" appears only if the user is org_admin. So the "new phase" shud be removed from there completely?

**Comment by sjDCC** [comment]
Yes, i think for now we want to remove the ability for anyone to 'add phase' when customising a template. We may revisit this in future when we rework the way we approach versioning and phases to make DMPs more 'active' and updated, but for now i'd stick with existing functionality / practice.

**Comment by sjDCC** [comment]
Sounds good - thanks @xsrust

**Comment by stephaniesimms** [comment]
all original points are addressed except the section heading areas are still missing + or - icons - this appears to be the case for all template editing and customization pages. please reinstate these @xsrust .

some additional points noted when testing: 
- when I click to Add Annotations, the text editors for Example Answer and Guidance are tiny (screenshot 1). they should be the same size as other TinyMCE editors on the Question editing page, e.g. (screenshot 2)  
- Save-Delete-Cancel buttons should appear beneath the editors, aligned to the right. Currently there is only Save-Cancel.
- after I create an annotation, I get a weird array of buttons (screenshot 3). there should only be Save-Delete-Cancel.
- if I click either of the duplicate buttons to "Delete Example Answer" I get the error message in screenshot 4

1
![add-annotations](https://user-images.githubusercontent.com/12703638/33866588-734c3fd2-deac-11e7-84c4-0b1edbcb303d.png)

2
![screen shot 2017-12-11 at 7 51 21 pm](https://user-images.githubusercontent.com/12703638/33866686-fad0d4c2-deac-11e7-8319-9842a22a657f.png)

3
![del-annotations](https://user-images.githubusercontent.com/12703638/33866597-7bdb6b50-deac-11e7-9c78-2190b77d16aa.png)

4
![delete-error](https://user-images.githubusercontent.com/12703638/33866607-85258da8-deac-11e7-9cb9-2566ae3ed93f.png)

**Comment by stephaniesimms** [comment]
+/- icons addressed in issue #1011 

looking back up to @sjDCC's  original request in this ticket, the following details still need attention:
-  if a user clicks to Customize a template, it's not apparent where they can take action to do so on the Template details page (screenshot 1 below). I suggest that the default behavior should be to expand the first phase accordion, in this case the "AHRC Technical Plan," for the template so the "Customize Phase" button is visible
-  Guidance still isn't showing in the panel to the right. This usually shows on the edit mode when customising.

1 - current view of page when user clicks to Customize a template
![screen shot 2018-01-11 at 12 41 59 pm](https://user-images.githubusercontent.com/12703638/34846643-a9922168-f6cd-11e7-971a-d2e85f1623c8.png)

2 - expand first phase accordion to display "Customize Phase" button 
![screen shot 2018-01-11 at 12 43 21 pm](https://user-images.githubusercontent.com/12703638/34846683-c87dd82e-f6cd-11e7-82d9-5595ac2d0bcb.png)

3-4 - missing guidance
![missing buttons](https://user-images.githubusercontent.com/6169940/32338127-cfcd5794-bfeb-11e7-8c84-6fc7044e66d3.PNG)
![annotations-button](https://user-images.githubusercontent.com/6169940/32338133-d3a1ebd2-bfeb-11e7-9009-c9b140accd74.PNG)

**Comment by stephaniesimms** [comment]
all bugs appear to be fixed and other issues are related to usability. i'll leave it to @sjDCC to transfer remaining work to a new post MVP issue since she noticed these things initially and is more familiar with the admin functionality.

**Comment by sjDCC** [comment]
The main aspects of this have been addressed but the themed guidance is still missing from display. I have created a new ticket for this #1209 and am closing this one out. I added 1209 to the current board as it should really be done before pushing into production, but it can become post-MVP if needed
