### ISSUE TITLE
Edit User privileges as a Super Admin

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#794]
UX wireframe @rhu001 "DMP User Accounts (Super Admin View)" 
![screen shot 2017-11-02 at 1 20 41 pm](https://user-images.githubusercontent.com/12703638/32348348-b76ff802-bfd0-11e7-8162-cb7c3c264fb6.png)

DMP Edit User Role - modal 
![screen shot 2017-11-02 at 12 57 06 pm](https://user-images.githubusercontent.com/12703638/32348221-52ae222c-bfd0-11e7-8e2a-356e160abc56.png)

- all functionality should be the same as that implemented in #761 except if a user has Super Admin privileges the modal will contain additional items as in the second screenshot above 
- Blue notepad functional spec: Clicking on Edit link should open a modal that allows admins to assign privileges to other users. For example, I'm a Super Admin and should see a list of all users in the User Accounts table. If I click the Edit link I'm presented with the modal below and option to assign any privileges to any user.
- Ticking the first box for "Org admin privileges" should automatically tick all boxes below it; these can then be deselected individually if desired. The same behavior applies if a user ticks the second box for "Super admin privileges"
- Note: add one more privilege tickbox at the end of the Org Admin column to "Use API" (missing from wireframe)

For clarity, here are the descriptors currently used in the database, grouped by the two roles; these should be mapped to the language in the modal screenshot above:

**Org admin**
Grant_permissions
Modify_templates
Modify_guidance
Change_org_details
Use_api

**Super admin**
Add_organisation
Change_org_affiliation
Grant_api_to_orgs

**Comment by sjDCC** [comment]
For clarity, here are the descriptors currently used in the database, grouped by the two roles:

**Org admin**
Grant_permissions
Modify_templates
Modify_guidance
Change_org_details
Use_api

**Super admin**
Add_organisation
Change_org_affiliation
Grant_api_to_orgs

**Comment by stephaniesimms** [comment]
some things are fixed (layout for modal and only reloading current page w/user displayed). but the behavior is not quite right. 

- As a Super Admin when I click to Edit privileges then select the top level "Org Admin" box to check all org admin privileges and click Save it reloads the page but doesn't display a message or reflect the changes in the user table (screenshot 1). 
- When I click to Edit the same user's privileges I see the modal with some Org admin boxes unchecked (it's always the top level and the bottom box).
- If I recheck these boxes and click Save then it behaves as expected - I receive a Success message at the top of the page and the table shows that the user has "Org Admin" privileges (screenshot 2)

![screen shot 2018-02-01 at 9 49 53 am](https://user-images.githubusercontent.com/12703638/35694506-6c190a12-0736-11e8-9dcb-feb139a50851.png)

![screen shot 2018-02-01 at 9 50 37 am](https://user-images.githubusercontent.com/12703638/35694510-72715bda-0736-11e8-86e3-d82bd297e7b5.png)

**Comment by briri** [comment]
This doesn't seem to be an issue anymore @stephaniesimms. At least I'm not able to reproduce the problem anymore on roadmap-stg

**Comment by stephaniesimms** [comment]
there seems to be a bug that prevents the modal from appearing when I click the Edit link next to any user account @briri

**Comment by sjDCC** [comment]
I am struggling to edit user privileges as a super admin too. When I click 'edit' the whole page greys out. Perhaps this is the same bug @stephaniesimms experienced which was blocking the modal.

Does it help to do this outside of a modal instead? e.g. on a user page?

**Comment by stephaniesimms** [comment]
the bug that was blocking the modal is fixed now. all working as expected. closing issue.

**Comment by sjDCC** [comment]
Modal popups up now and looks good - thanks@briri
