### ISSUE TITLE
Revise Templates page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#803]
Templates page in Admin area needs some minor changes for consistency w/other pages:
- rename "Own Templates" table heading to "[Org Name] Templates"
- next table should be "Default template" (singular)
- then "Funder templates" table
- add pagination to tables w/more than 10 items
- standardize table layout so all column widths match across 3 tables
- add search box? if so do we need one above each table? only if more than 10 items?

**Comment by briri** [comment]
@stephaniesimms can this one be closed. It seems like everything is covered by either #900 or #815

**Comment by stephaniesimms** [comment]
yessir @briri - closing this issue.
