### ISSUE TITLE
Typo in language dropdown CSS (bootstrap_and_overrides.css.less)

### ISSUE THREAD

**Issue by benjaminfaure** [DMPRoadmap/roadmap#804]
Hello,

I found a typo in the **bootstrap_and_overrides.css.less** file located in **lib/assets/stylesheets/**
On line **178** `lang-dropdown-link:hover` should be `.lang-dropdown-link:hover`.

However, it will not solve this blue box "issue" (not sure it's intended) : 
![screenshot-2017-11-8 dmponline](https://user-images.githubusercontent.com/18717040/32542648-8f0c0c78-c473-11e7-89ca-c91738ea28b5.png)

`background-image: none;` should be added in the CSS rule.

If you are interested I can make a pull request with these changes.

B. Faure

**Comment by briri** [comment]
Hello @benjaminfaure 

The `bootstrap_and_overrides.css.less` file will soon be replaced by a new scss file in early 2018 (see the CDL-MVP branch's [overrides.scss](https://github.com/DMPRoadmap/roadmap/blob/CDL-MVP/lib/assets/stylesheets/overrides.scss) file). 

If you have time and would like to send a PR though to fix the current production codebase, please submit a PR to the `contributions` branch and we will review and include it in the next patch.

**Comment by benjaminfaure** [comment]
Hello @briri , 
Sorry for the late answer. 
I have a PR ready but it seems the `contributions `branch is not up to date with the `development `branch. Is that ok if I send a PR with the latest changes of the dev branch or should I wait for you to sync the contributions branch ? :)

**Comment by briri** [comment]
Hi @benjaminfaure the contributions branch is now in sync with development.

**Comment by benjaminfaure** [comment]
Thanks !
Created PR #875
