### ISSUE TITLE
Create Super Admin Templates page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#813]
UX wireframe @rhu001 http://h90c3m.axshare.com/#g=1&p=dmp_all_templates__super_admin_view___org_template

Create "Templates" page in Super Admin dropdown menu. This is where Super Admins can manage funder and default templates (first tab) and Organisation templates (second tab). 
- add Table for each tab w/layout and content in screenshots below
- functional spec: Template names are links that take the user to the template editing page
- add Search box above table and pagination if either table exceeds 10 items

Templates page in Super Admin dropdown menu
![screen shot 2017-11-13 at 11 27 03 am](https://user-images.githubusercontent.com/12703638/32744818-9fbc08fc-c865-11e7-98bc-a5c717b3300e.png)

Funder & Default Template (rename heading)
![screen shot 2017-11-13 at 11 21 27 am](https://user-images.githubusercontent.com/12703638/32744663-23fc06fe-c865-11e7-9918-a3ca49a24e85.png)

Organisation Templates
![screen shot 2017-11-13 at 11 25 10 am](https://user-images.githubusercontent.com/12703638/32744750-6e4e7200-c865-11e7-862f-0a6ba74cc5c8.png)

**Comment by sjDCC** [comment]
Tabbed approach looks fine to me @stephaniesimms We could apply this to the general org-admin templates page too for consistency but I don't think that's essential for MVP

**Comment by dsisu** [comment]
@stephaniesimms Please, let's focus on features essential only for MVP. Also, whenever we plan to add a feature it's important that we think of the use case for it, we don't just add things because they can be done. Once we have a use case, we present it to the developers and let them think about how it fits into the process.

**Comment by stephaniesimms** [comment]
thanks for the confirmation @sjDCC - as we discussed last week we need to prioritize some template/guidance dev work so that this functionality is available for manual data curation. we're beginning on 4 Dec to audit all US funder templates and hired a contractor to help as it's a huge task.

**Comment by briri** [comment]
This is an ajax call that could have been impacted by the https -> http confusion with the server configuration. Jim updated our puppet script. I will test today to see if the issues have been resolved

**Comment by stephaniesimms** [comment]
this looks good on roadmap stage and is working as expected. closing issue but will leave it on the board for @sjDCC to confirm.
