### ISSUE TITLE
Date filtering error

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#817]
Filtering the plans table on My Dashboard by the last "Edited" date field produces weird outcomes (screenshots below). Make sure date format is set correctly. 

![date-sort-error](https://user-images.githubusercontent.com/12703638/32756074-1b3fa2c8-c88d-11e7-83ae-4984fc4b0f92.png)

![date-sort-error2](https://user-images.githubusercontent.com/12703638/32756077-1e5288f4-c88d-11e7-9a7b-e617f0176a70.png)

**Comment by briri** [comment]
Should be fixed as part of #815

**Comment by jollopre** [comment]
should be fixed as part of #1027

**Comment by stephaniesimms** [comment]
this is working now. closing issue.
