### ISSUE TITLE
Add a "test" flag to plans

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#83]
UPDATED: UX wireframes @JEK-III 
http://h90c3m.axshare.com/#g=1&p=my_plans__blank 
First-time login Dashboard - Add 'Create test plan' option next to 'Create plan' button

http://h90c3m.axshare.com/#g=1&p=my_plans__ideal 
My plans - add tick box for 'test' which always corresponds w/'private' visibility 

Allow users to mark their plan as a 'test'. 

Test plans will be excluded from statistical calculations and will not be visible to other users (only owners and with those that the owner has shared the plan)

We will need to add a new boolean field to the projects table

**Comment by briri** [comment]
Decided to store 'is_test' and 'is_public' as separate boolean values to the projects table rather than as a value from a separate 'visibility_types' table like we have in the DMPTool codebase. 

A plan can have the following visibilities: 
- Test - visible only to the owner and specified collaborators
- Public - the plan will be available on the new Public DMPs page and accessible/exportable by anyone
- Organisational - the plan is neither Test or Public and is available to the owner, collaborators and admins

I'm handling the logic to prevent a plan from being marked as both public and test at the same time in the model and UI code.

Took an initial stab at the UX workflow for this and the new 'test' flag (see screenshots).
![screen shot 2017-01-03 at 1 46 05 pm](https://cloud.githubusercontent.com/assets/1204467/21625494/cc0bb6ec-d1c0-11e6-843f-4befc99e032c.png)
![screen shot 2017-01-03 at 1 46 28 pm](https://cloud.githubusercontent.com/assets/1204467/21625493/cc08fdc6-d1c0-11e6-87a5-61fb5543a1ff.png)
![screen shot 2017-01-03 at 1 46 44 pm](https://cloud.githubusercontent.com/assets/1204467/21625492/cc067cf4-d1c0-11e6-9c7a-338807589e71.png)

**Comment by briri** [comment]
Decided to switch to a visibilities table after discussion with @stephaniesimms. There are some nuances between making a plan 'test' and 'private' so we will need 4 visibility settings: test, private, organisational (default) and public

**Comment by briri** [comment]
related to #84

**Comment by stephaniesimms** [comment]
adding reference to Pivotal ticket for test flags: https://www.pivotaltracker.com/story/show/120867001

we can discuss whether to use this approach or the DMPTool radio buttons approach with 4 visibility settings (public, org, private, test).

**Comment by briri** [comment]
Added test checkbox to view plans table. Only owners and coowners can change whether or not a plan is designated as a test. Making a plan 'test' will automatically change the visibility to 'Private' in the UI (the test flag is treated the same as the other visibilities in the database)
![screen shot 2017-06-13 at 10 38 54 am](https://user-images.githubusercontent.com/1204467/27096198-1604f26c-5025-11e7-894a-ec2de952b4ec.png)

**Comment by stephaniesimms** [comment]
test flag functionality works as expected. I can either create a Test plan at the outset, or tick the "Test" box in My plans or Plan details pages, which defaults the plan to private visibility. moving this issue along.

**Comment by sjDCC** [comment]
Looks good. Can create a test plan from scratch and easily adjust setting in table. This seems to autosave as just need to check box and entry is retained, which fits well with how we're implementing it elsewhere. Good to close out.
