### ISSUE TITLE
Upgrade rubyzip gem to >= 1.2.1

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#834]
The htmltoword gem is using rubyzip >= 1.0 and we just got notified by GitHub that the dependency has a security vulnerability.

Update both gems, rubyzip to >= 1.2.1 (specify in gemfile if needed) and htmltoword to >0.7.0

![screen shot 2017-11-17 at 7 43 22 am](https://user-images.githubusercontent.com/1204467/32955717-9b84c482-cb6b-11e7-9e20-7f7db1b46e0c.png)

**Comment by stephaniesimms** [comment]
the security message hasn't disappeared. @briri will ping @vyruss to merge the patch into master.

**Comment by stephaniesimms** [comment]
security message is gone so i'll assume this is done. closing.
