### ISSUE TITLE
Error when sharing plan

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#839]
When testing i tried to share a plan with myself and encountered the following error:
![share-plan](https://user-images.githubusercontent.com/6169940/33033660-170f9c0e-ce1d-11e7-849d-d39606163eb7.PNG)

The plan shared properly the second time i tried the action

**Comment by briri** [comment]
A fix for this was put into place for the UserMailer emails. It was not added for these Devise based emails though. See PR #827 `_new_comment.html.erb`

**Comment by stephaniesimms** [comment]
working as expected now. closing issue.
