### ISSUE TITLE
Allow users to make their plan "public"

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#84]
Allow users to mark their plan 'public'.

Public plans will be visible and exportable by everyone regardless of whether or not they have an account in the system.

We will need to add a new boolean field to the projects table

**Comment by briri** [comment]
Decided to store 'is_test' and 'is_public' as separate boolean values to the projects table rather than as a value from a separate 'visibility_types' table like we have in the DMPTool codebase. 

A plan can have the following visibilities: 
- Test - visible only to the owner and specified collaborators
- Public - the plan will be available on the new Public DMPs page and accessible/exportable by anyone
- Organisational - the plan is neither Test or Public and is available to the owner, collaborators and admins

I'm handling the logic to prevent a plan from being marked as both public and test at the same time in the model and UI code.

Took an initial stab at the UX workflow for this and the new 'test' flag (see screenshots).
![screen shot 2017-01-03 at 1 46 05 pm](https://cloud.githubusercontent.com/assets/1204467/21625494/cc0bb6ec-d1c0-11e6-843f-4befc99e032c.png)
![screen shot 2017-01-03 at 1 46 28 pm](https://cloud.githubusercontent.com/assets/1204467/21625493/cc08fdc6-d1c0-11e6-87a5-61fb5543a1ff.png)
![screen shot 2017-01-03 at 1 46 44 pm](https://cloud.githubusercontent.com/assets/1204467/21625492/cc067cf4-d1c0-11e6-9c7a-338807589e71.png)

**Comment by stephaniesimms** [comment]
@briri Circling back to confirm that visibility settings are:
- Public
- Organizational / Institutional
- Private

'Test' plans are handled separately in the UI, not sure what this means on the back end.

**Comment by briri** [comment]
Right now we're storing it in the same place in the database. The 'test' designation ultimately controls how and where the plan is visible (statistics, Ui pages, etc.). We can handle it in whatever way you feel is appropriate within the UI.

**Comment by briri** [comment]
Plan visibility is now controllable from the edit plan details page. Once a plan has been made public it appears on the new 'Public DMPs' page which is accessible from the main navigation bar
![screen shot 2017-06-16 at 11 03 11 am](https://user-images.githubusercontent.com/1204467/27238911-98b7faa0-5283-11e7-87cc-c7d60212a460.png)

**Comment by stephaniesimms** [comment]
- first column should say "Plan Title"
- the "Owner" column should display First and Last Name (not email).
- this is another area where I'm confused by "Organisation" vs. "Institution" terminology; will confer w/ @sjDCC to make sure we clarify what's what and use consistent language; possibly compromise to use term "Affilliation"?
- the downloadable PDF will get reformatted w/a cover page, etc (related issues #300, #436, screenshot of example from DMPTool )  

![screen shot 2017-06-16 at 1 23 34 pm](https://user-images.githubusercontent.com/12703638/27243579-72e0e30a-5297-11e7-8f0c-145fdeaad64c.png)

**Comment by briri** [comment]
@stephaniesimms all of your requests above have been deployed to stage except for the Organisation vs Institution debate. We can create a separate ticket for that once you confer with @sjDCC on the issue. We will need to update the language throughout the site.

The copyright info is in the PDF now. I did not modify the formatting though since we're addressing it in another ticket

**Comment by stephaniesimms** [comment]
"Project Title" instead of "Plan Title" for first column head @briri 
The rest looks good for now.

**Comment by stephaniesimms** [comment]
- "Project Title" instead of "Plan Title" for first column head
- "Institution" instead of "Organisation" (this is another place to evaluate whether this change is ok w/you @sjDCC )

![screen shot 2017-06-27 at 4 26 21 pm](https://user-images.githubusercontent.com/12703638/27614280-6a4d3448-5b55-11e7-85f7-7071426f9a69.png)

**Comment by sjDCC** [comment]
Language is fine with me @stephaniesimms i.e. 'institution' instead of org and 'project title' instead of 'plan title' FYI, the table isn't showing me institution column currently
![missing-institution-column](https://user-images.githubusercontent.com/6169940/27615126-04cbebd4-5b9e-11e7-8622-838ad9325f52.PNG)

Visibility also looks good. I'll sound a few folk out tomorrow that a default of institutional visibility works in UK too, but assume that will be fine. I couldn't change visibility, perhaps as plan has no content, but expect researchers should be able to make a new draft private if desired. Here's the error it threw when trying to reset to private:
![visibility-error](https://user-images.githubusercontent.com/6169940/27615171-5297cb9e-5b9e-11e7-9bf7-7a291ea6c80d.PNG)

If we can hold off on the PDF export change, I'd like to sound out some UK funders and institutions about this first page. Many here are bolshie about page limits so this may be a problem.

**Comment by sjDCC** [comment]
Just noticed table is missing 'institution' column because of #418 We're cramming a lot into table now so happy for this one to be removed. Is a bit redundant

**Comment by briri** [comment]
Updated the column names for the public DMPs page. @sjDCC you will no longer receive an error when saving the plan but its not yet recording any changes you make to the visibility setting.

@JEK-III How should the visibility be handled for a test plan? Should they be disabled? If so do we need a place to allow the user to turn the 'test' status off on the plan details page? Otherwise the user needs to go back out to the 'view plans' table to click the 'test' box

**Comment by JEK-III** [comment]
@briri working on this today–

My current thinking is to move plan visibility to the Share panel (which is a pretty standard label under which to find that kind of thing) and– as you suggest– add a checkbox for test status to the Plan Details panel. 

Visibility would then be locked at Private for test plans and, at a minimum, plans with 0 questions answered. I know many users will leave some questions blank, so we can't require 100% completion before making your plan, but perhaps we could find a reasonable threshold.

**Comment by sjDCC** [comment]
Good call @JEK-III Plan visibility settings do align better with the sharing tab.

Regarding when to share within institution or make public - perhaps a threshold of 80% completion? Or could we have a pop-up that queries users e.g. "Your plan looks like it's nearly finished. Is it complete?" Ones with a 'done' status could be shared/public.

@stephaniesimms I mentioned the visibility settings at Jisc meeting and then realised during questions that I don't 100% know how they work in DMPTool. You have the default as 'institutional'. What does this mean in practice in terms of how plans are shared and when? Do they only become visible to others when 'done' or as soon as they've been started? And are all plans just there to view or use in some way? I think previously people could create a new plan from an existing one that belonged to anyone in the institution, but this is being removed so they can only copy their own plans now isn't it?

The question I got asked was about what controls admins had on display. Can they promote / preference a subset of chosen examples so there are a couple of good ones for each discipline / faculty? Or is your display just a list of all institutional plans? Any way to help researchers filter or search this?

**Comment by stephaniesimms** [comment]
@JEK-III i just peeked at the wireframes and i like this very much. 

@sjDCC default used to be private visibility for dmptool. it's set to institutional in roadmap currently for no particular reason - testing/feedback maybe - but i would suggest we make the default private. we changed dmptool to require users to choose a visibility setting as a way to get more info about how open they are to being more public. now that time has passed and we have more feedback and stats, i don't think we are in a position to force the public issue. also, public as a default setting was hugely unpopular among multiple stakeholders. our role is just to help people write good DMPs and enable them to share them if they want to.

plans only appear in the dmptool public list when a user clicks "Done" on the final DMP preview page, which triggers the status change. we're not ready to figure out plan status for roadmap just yet so @JEK-III is working hard to get the system to infer when a plan is done or mostly there. the main reasons for this are 1) to help us manage the public DMPs list and 2) to optimize filtering for test and practice plans.

all public plans are available to download and reuse in any way per the copyright statement on the cover page (below). they're displayed in chronological order based on creation date/ID. going forward users will only be able to copy their own plans, correct. and re the last question, we do want to enable users (not just admins) to promote good plans from the public list but haven't worked it out for MVP. i'd say this is a high-priority post-MVP issue.
 
Copyright information: The above plan creator(s) have agreed that others may use
as much of the text of this plan as they would like in their own plans, and customize
it as necessary. You do not need to credit the creators as the source of the
language used, but using any of their plan's text does not imply that the creator(s)
endorse, or have any relationship to, your project or proposal.

**Comment by stephaniesimms** [comment]
Public DMPs page is looking good. Setting visibility and formatting exported PDF of public plans will be addressed in separate issues. Moving this one along.

**Comment by sjDCC** [comment]
Reopening this and moving back as I don't seem to be able to change visibility setting in roadmap stage. All the options are greyed out for me.

![grey-out](https://user-images.githubusercontent.com/6169940/28473460-8f062b6a-6e3c-11e7-9747-f7208d63bdc0.PNG)

It also took me a minute to remember where this was located so I wonder if we can make it easier to access via my dashboard e.g. have the entries in the 'visibility' column be links to the config area, or have an entry in the actions dropdown to 'Change visibility'

![change-visibility](https://user-images.githubusercontent.com/6169940/28473499-c3805c1c-6e3c-11e7-928f-7c5e15d07a1a.PNG)

**Comment by sjDCC** [comment]
Ignore my first point. I know see why they were greyed out!

I've answered a question and done some testing and wonder if we already have a ticket to improve the public DMP process?

My plan went public with only 1 question answered. I though it was only 'complete' plans that went live. Could we introduce a notification that it will only go public when 80%+ questions are answered, or grey out the public plan option until we have some notion of it being complete?

**Comment by briri** [comment]
Hey @sjDCC 
I don't know if we determined a good way to determine a level of completeness with regard to allowing plans to be made public. For the short term we're just requiring one answer but we don't do any assertions about its length or content. For example the single word, 'test' is enough right now.

Organizational visibility means that anyone in the user's organization can view the template. @JEK-III is still working on the wireframes for this. Its slated to appear below the list of plans on the user's dashboard in a separate section.

@stephaniesimms has struggled with people making plans public when they're clearly tests or incomplete. We're going to add a process that allows super admins to remove them from the public list. We should come up with a better vetting algorithm though for sure!

**Comment by sjDCC** [comment]
I think we want some proportion of completeness, even if it's pretty low e.g, 45%

**Comment by stephaniesimms** [comment]
I agree. we've tossed around various ideas about how to identify "completeness" without introducing formal status indicators just yet. a percentage of questions answered (>1 question) but something pretty low as @sjDCC suggested (45%) is looking like the best option.

**Comment by stephaniesimms** [comment]
Public visibility function added and working as expected. Created new issue #575 to address "completeness" of plans. Closing this issue.
