### ISSUE TITLE
Add autosave to share plan collaborators table

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#840]
The share plan collaborators table needs to be on auto-save
![autosave](https://user-images.githubusercontent.com/6169940/33034878-2c14867e-ce21-11e7-9375-a5414f55bcd1.PNG)

At present this doesn't seem to be the case so there's no way to change permission without removing and re-granting access

**Comment by jollopre** [comment]
Related to issue #857 and fixed in PR #861

**Comment by sjDCC** [comment]
The autosave works now thanks. I noticed that removing rights jumps you to top of page so you see notice about saved changes (as popup to confirm choice is raised) but just changing permissions doesn't obviously reload page so you can easily miss notice that changes have saved unless you scroll up.

![autosave](https://user-images.githubusercontent.com/6169940/33481945-a33205ea-d68e-11e7-80d0-55fa36bd6809.PNG)

Do we want to reload and jump to top? It would be helpful here, but annoying perhaps on other autosave pages so happy to close this out if not desired.

**Comment by jollopre** [comment]
@sjDCC, we can jump to the top of the page when a change is made at any collaborator.

**Comment by sjDCC** [comment]
Ok, it's probably worth doing that to make sure people notice it's saved and see the notification.

Do you want to pull back to 'in progress' to implement?

**Comment by jollopre** [comment]
yes, I will make that tweak

**Comment by sjDCC** [comment]
Looks perfect, thanks @jollopre
