### ISSUE TITLE
Add visibility to Template details page for Funders

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#845]
This issue was uncovered while working with migrated DMPTool data. 

Some funders like the USGS have normal funder templates but they also have users who create DMPs and have templates for internal use. Right now the public facing 'DMP Templates' page displays any published funder template. We need a way for a funder's Org Admin to identify whether the template is for users applying for a grant with their organisation or if the template is for their internal users. 

The templates table has a `visibility` (INT) column that is no longer in use after we converted the codebase over to publishable versions. We can use this column to identify these internal templates. By default we would set the value to 'zero' (organisational visibility). Funder Org Admin's could then change this value via a checkbox to 'one' (public visibility). (We should run a rake task that sets any existing funder templates to 'one' automatically).

The public facing 'DMP Templates' page should then be updated to only collect the funder templates whose `visibility = 1`. The create plan page would also need to be updated to consider this value in the ajax endpoint in the `templates_controller` that collects available templates for the research org and funder combo (research org templates `visibility = 0` and funder templates `visibility = 1`. The Org Admin templates page would also need to be updated to check for `visibility = 1` when generating the list of customizable templates for non-funder orgs.

**Comment by sjDCC** [comment]
So if I'm understanding the use case right @briri, the logic that we'd need to apply on the create plan page is that:

1) If user is affiliated with funder and selects funder from the organisation dropdown, present the internal funder template

2) If the user is affiliated with funder and selects funder from the organisation dropdown AND funder dropdown, present the internal funder template, not public one? Currently the logic does the opposite as funder templates take precedence over institutional ones so we'd need an exception here for when the org affiliation is a funder

3) If a user affiliated with a non-funder selects a funder in the org dropdown, present the funder guidance not internal funder template as these templates are just for internal funder use?

I assume this is related to ticket #665 to ensure funders display in the org dropdown

**Comment by stephaniesimms** [comment]
@briri's assumptions above are correct. we tested on DMPonline and existing logic/workflow should meet the need w/#665 . there's no need to keep USGS org templates private. the use case relates to the difference between intramural and extramural research at US federal agencies. a lot of researchers are employed directly by the agencies and have internal requirements for data mgmt (Org Templates) but don't need to apply for funding (Funder Template meant for external researchers).

**Comment by sjDCC** [comment]
Ok great, even better if no logic needs to be changed in the 'create plan' workflow.

You may want to share guidance with those funders that their internal users should just pick them from org dropdown and select 'no funder' as @briri outlines in option 2. If the user picked them in both dropdowns, they'd get the public template not the private one I think as the funder selection takes precedence over any organisational templates. Or perhaps the template selector would be presented automatically since both are actually funder templates? 

If the latter is the case, it might be that you need to have some guidance for general users about the difference between intra- and extramural templates so they know which is the public template to choose.

**Comment by stephaniesimms** [comment]
If I select USGS as my Org and as the Funder I believe I get both the individual Org templates and public/funder template  (intra and extramural). Template names will clarify which to select as intramural folks usually know what they're looking for (very specific programs like USGS Aquatic eDNA). Users who apply for extramural funding are most likely to use their own (non-USGS) affiliation and therefore won't see the intramural templates at all.

**Comment by sjDCC** [comment]
On reflection I suspect the template selector would be presented automatically if USGS is picked in either one or both of the two selectors. The intra- and extramural templates will both be classed as funder templates by the system as the owning org type is a funder. Best to just test it with real data though and see what happens.

**Comment by briri** [comment]
Added the logic to change the template's visibility setting if the template is from a funder.

![screen shot 2017-12-04 at 3 15 04 pm](https://user-images.githubusercontent.com/1204467/33581695-aed2dca6-d906-11e7-91ec-f4349dc474be.png)

by default, a template is organisationally visible.
The message displayed to the user when they view the template are (the 'once published' portion only shows if the template is unpublished:
 
![screen shot 2017-12-04 at 3 13 50 pm](https://user-images.githubusercontent.com/1204467/33581769-08f198da-d907-11e7-9a52-42665468ad58.png)

![screen shot 2017-12-04 at 3 19 11 pm](https://user-images.githubusercontent.com/1204467/33581770-0908622c-d907-11e7-96e5-35b20749e915.png)

**Comment by sjDCC** [comment]
Hi @briri. Will this visibility setting apply on all templates or just funder ones? If it's all we perhaps need to add some tooltips as I think org-admins will get confused about what the difference is between internal use only and available to the public. We don't restrict the visibility or use of organisational templates - any user can select any org from the dropdown and receive their template - so saying something is 'internal only' doesn't work in this context.

**Comment by briri** [comment]
If we open this to allow regular Orgs like BCO-DMO to set the visibility does that also mean that we want Orgs public templates to appear in the 'funder' list on the create plan page as well as the public DMP Templates page?

**Comment by stephaniesimms** [comment]
if including Orgs like BCO-DMO gets messy then let's just stick w/funders. BCO-DMO has a public template but currently i switch the Org affiliation on the template from NSF when they need to edit it. or I do it for them. this is a super edge case so not necessary to include it here.

**Comment by jollopre** [comment]
@briri if org BCO-DMO is organisation type, a workaround would be to add it as funder type too, that's the reason the bit flags are in place for org type.

**Comment by briri** [comment]
Indeed worth trying @jollopre. I don't see any issues with doing that after a quick search of the code for 'org_type'. To my knowledge though we don't currently have any Orgs with multiple Org types in the system. 

@stephaniesimms I don't see 'The Biological and Chemical Oceanography Data Management Office (BCO-DMO) ' in the DMPTool data anywhere. I'd like to try this approach out.

**Comment by briri** [comment]
ok @stephaniesimms Woods Hole is now an Organization and a funder on dmp2-stg. Give it a try and let me know if it works for you

**Comment by stephaniesimms** [comment]
@briri this works ok on the template side now. but I no longer see Org/Funders in the Org list when I try to create a plan (e.g. Woods Hole and USGS are missing). to be clear, i'm testing on dmp stage. 

from an user perspective, the important thing to distinguish here is public templates from org/internal templates. so e.g. as an admin i would expect to find the internal USGS templates in my Org templates list. and we don't want to have to grant Super Admin privileges to admins from any Org like USGS that has multiple research sites managing their own internal templates. i think this one requires more discussion...

**Comment by sjDCC** [comment]
It's not possible for me to test this as the data on DMPRoadmap stage is DMPonline content not US, so I don't think there are any orgs like BCO-DMO or USGS. Any ideas @briri

**Comment by stephaniesimms** [comment]
@sjDCC - sounds good to stick w/terminology for Funder templates v Org templates. I don't anticipate this becoming more common and you're correct that the USGS internal templates are conceptually like Org templates.

after some more testing this is looking good to me. the appropriate templates appear in the appropriate lists now. #665 resolved the presentation of appropriate templates when creating a plan. i want to test a bit more as a USGS Org admin but that will have to wait until Mon. I'll leave this here for now.

**Comment by stephaniesimms** [comment]
after further testing on DMP stage w/USGS data I think everything is working as expected. I just question the need for the tickbox to designate a template for "internal use only" - this appears to be irrelevant since I get the appropriate list of templates regardless of whether I tick the box or not (screenshot below). The official "funder" USGS template is marked as such in the database and is the only one that appears for users with an affiliation other than USGS. 

is there a reason to keep the tickbox @briri ? if not, i'd prefer to remove it.

![screen shot 2018-01-08 at 1 19 58 pm](https://user-images.githubusercontent.com/12703638/34692914-a5f92cd0-f476-11e7-8954-50db0e785e26.png)

**Comment by briri** [comment]
@stephaniesimms if checked it prevents the template from appearing in the public DMP templates page

**Comment by stephaniesimms** [comment]
aha. in that case it serves a purpose and we should keep it indeed. thanks @briri . i propose adding a question mark popover next to "Visibility" with the following text:

"Checking this box prevents the template from appearing in the public list of templates."

**Comment by stephaniesimms** [comment]
popover looks good. closing issue.

**Comment by sjDCC** [comment]
This is good to close out and remove from board. I raised a related question today though #1042 as I think this should only apply to funder templates not institutional ones
