### ISSUE TITLE
Verify that emails are using the proper user in message body

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#846]
The email sent out after sharing a plan is sent to correct recipient but the content of the message body is 'Hello [requestor email],'

E.g. userA@example.org owns the plan and invites userB@example.org to collaborate. The email message that userB receives says 'Hello userA@example.org,'.

Go through all of the emails (users_mailer and devise) to make sure that the correct user is referenced in the mail body.

**Comment by briri** [comment]
related to #1230, #1231, #1232

**Comment by stephaniesimms** [comment]
Request feedback emails were wonky. These should be fixed now. Just need to double check that all others are working as expected and probably we can close this issue.
