### ISSUE TITLE
Shibboleth linking / create account error

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#849]
When a user goes to sign in with Shibboleth but doesn't have these credentials linked to their account yet, they are prompted to either 1) create an account or 2) sign in on the page below

![shibboleth](https://user-images.githubusercontent.com/6169940/33124949-b423734e-cf76-11e7-97b1-a3cc52a69922.PNG)

If the user tries to create an account for an email address that already exists, the form just clears out on submission. No error message is generated. The user should be alerted to the fact that the email address is already taken and be prompted to sign-in instead. 

Please insert an error message along the lines of:

"Your email address is already in use. Please Sign in [LINK] so we can link your account to your institutional credentials."

**Comment by stephaniesimms** [comment]
doing some triage and found this issue. you might want to check if the bug still exists @sjDCC and move this over to the dmponline repo.

**Comment by vyruss** [comment]
@sjDCC I just tested on `dmponline-test which is based on the `development` branch and the issue appears to be fixed. 
![image](https://user-images.githubusercontent.com/18707439/36552296-6c2c944e-17f1-11e8-860d-e8b4ce388152.png)
