### ISSUE TITLE
Interaction with Research Data Management Organiser?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [DMPRoadmap/roadmap#855]
The work at
https://github.com/rdmorganiser/rdmo
seems to overlap quite a bit with DMP Roadmap and the work on machine-actionable DMPs.

Are there any interactions between the two projects?

Also pinging their @jochenklar .

**Comment by sjDCC** [comment]
Yes, thanks Daniel. @stephaniesimms and I have spoken with Jens Ludwig previously and he's getting involved in the new RDA Common Standards WG. There is quite a bit of overlap / similar aims

**Comment by stephaniesimms** [comment]
closing this issue and adding topic to relevant discussion lists
