### ISSUE TITLE
Unable to change plan collaborator privileges

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#857]
A handful of related bugs to report:
1 - When I select a new level of privileges in the dropdown under Manage Collaborators I cannot save the change (screenshot 1). I assume it should autosave.
2 - As a co-owner I cannot remove collaborators. I receive the error message in Screenshot 2. Co-owners should have the same privileges as plan owners. They should only be prevented from removing themselves and the plan owner, but should be authorized to remove other collaborators. 
3 - This error message should be displayed on the Share plan page in cases where a user does try to perform an action that isn't allowed. Currently, it redirects me to My Dashboard.

![screen shot 2017-11-22 at 1 41 14 pm](https://user-images.githubusercontent.com/12703638/33151225-03a869b4-cf8c-11e7-8028-3a8e6cb93c71.png)

![screen shot 2017-11-22 at 1 41 33 pm](https://user-images.githubusercontent.com/12703638/33151227-05ca6724-cf8c-11e7-8d55-141d20880648.png)

**Comment by sjDCC** [comment]
This is related to ticket #840 which asks for autosave to be reinstated so permissions can be revised

**Comment by jollopre** [comment]
The PR #861 is addressing the list of issues encountered. Summarising:

- Autosaving when combobox (Coowner, Editor, Read only) changes
- Remove action is permitted for owners and coowners
- Action (update permission and destroy permission, i.e. combobox and remove link respectively) are only permitted for owner and coowners. Note, they cannot perform these actions on themselves.

**Comment by sjDCC** [comment]
All looks good:
1) autosave has been added and reload jumps to top to make user aware of notification
2) co-owners can be removed, but not yourself
3) messages display on share plan page and don't redirect

Closing out
