### ISSUE TITLE
Update Notification Preferences Page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#858]
No longer necessary to notify Org Admins that a template is published/unpublished. Remove those two tick boxes and descriptions from the Notification Preferences page menu for DMP Administrators  (screenshot below).

![screen shot 2017-11-22 at 2 40 17 pm](https://user-images.githubusercontent.com/12703638/33152746-2b7de2f0-cf93-11e7-864e-fd74bbcb09e8.png)

**Comment by sjDCC** [comment]
i also noticed that the DMP administrators checkboxes show irrespective of whether you're an admin or not. On this account I don't have admin rights as no extra menu items show, so this options to configure emails also shouldn't present.

![notification-preferences](https://user-images.githubusercontent.com/6169940/33172024-6744b0b2-d046-11e7-9d02-999546b4a945.PNG)

**Comment by stephaniesimms** [comment]
updated preferences look good. closing issue.
