### ISSUE TITLE
Update the seeds.rb file used to initialize a new installation

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#86]
Update the seeds file so that it populates all of the lookup tables, creates a super admin, org admin, and org user account. Creates an example template and an example plan.

The current seeds.rb does not adequately populate enough data to help someone install and test drive the new system.

**Comment by briri** [comment]
Started working on this but it makes sense to wait until after the DB refactor. Work was done in a branch on CDLUC3/roadmap

**Comment by vyruss** [comment]
Can we close this as done?
