### ISSUE TITLE
Switch 'added_as_coowner' email pref to 'plan_sharing'

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#865]
Please complete the following fields as applicable:

**Expected behaviour:**
System sends out emails when a plan is first shared with a user, when their permission changes, and also when the plan is un-shared with them. We should perform a pref check on this one pref for each of these scenarios.

**Actual behaviour:**
The system is sending out emails but only performs the check on the initial share and the un-share. 

**Steps to reproduce:**

**Comment by stephaniesimms** [comment]
emails are sent as expected. that's all i can confirm via testing. closing issue.
