### ISSUE TITLE
Convert links on Org Details page to use logic introduced in PR #863

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#866]
Update the Org details page and JS to make use of the new generic JSON link array handler introduced in PR #863

**Comment by jollopre** [comment]
orgs_controller.rb can execute multiple times redirect_to which leads to failing request. I'm assuming once the checking of link objects is using the concern will go away but for now. Consider that, passing a link object with empty link or text will execute one redirect and after will execute the begin rescue end clause too https://github.com/DMPRoadmap/roadmap/blob/CDL-MVP/app/controllers/orgs_controller.rb#L38

**Comment by briri** [comment]
Also add a migration to change orgs.links back to a VARCHAR.

**Comment by stephaniesimms** [comment]
can't test this in UI. closing issue.
