### ISSUE TITLE
CSS refinements #2

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#867]
Can something be done to make the actions in the write plan banner look more like tabs or buttons? Perhaps introduce a line between each? Or does this bar and the guidance/comments bar even have to stretch full length?

Screengrab 1
![tab](https://user-images.githubusercontent.com/6169940/33172510-649f87e0-d048-11e7-8023-0c6bd7312bb3.PNG)
![tabs](https://user-images.githubusercontent.com/6169940/33172518-68655fc6-d048-11e7-8740-d618fb56eaaf.PNG)

The same applies to the sign in / create account block. Is there a need for the tabs to stretch out beyond the button area? I think we need to reinstate the borders around blocks like this otherwise they look odd  / unfinished.

Screengrab 2 
![capture](https://user-images.githubusercontent.com/6169940/33175132-8d90a260-d052-11e7-8f0d-d565d00e4019.PNG)

**Comment by stephaniesimms** [comment]
A couple of other minor things I noticed @bhavi - some spacing on the create plan page

![spacing](https://user-images.githubusercontent.com/6169940/33173034-6b8ecfbe-d04a-11e7-80f9-010a3b7ab3c8.PNG)


And guidance / comments boxes could do with some visual boundaries. The + icons also seem overly large (can we make them smaller, narrower, less bold?), and they should be offset to the right on the guidance tabs as in the section headings.

![lines](https://user-images.githubusercontent.com/6169940/33173079-9ca72574-d04a-11e7-8b6e-ada098dd8142.png)

Also, i wonder if the create plan button should move on my dashboard so it's more prominent and doesn't get lost when users have multiple plans? What do you think @stephaniesimms 
![create-plan](https://user-images.githubusercontent.com/6169940/33173112-b7be792a-d04a-11e7-89f7-dff8ce8a74da.PNG)

**Comment by stephaniesimms** [comment]
I think the spacing could be improved on the edit / write plan page

- I don't think we need the tick box on the section banner. Saying (1/2) is sufficient to me to denote progress. I feel this icon just clutters it. If we do retain this, it should only show as ticked when all the question in the section are answered, not just 1
- The question text needs to come before the example answer and box
- More spacing or perhaps a line is needed between the individual questions. At the moment the gap between the two questions is tiny compared with the gaps between the answer box and save button. The "answered less than x minutes ago" also seems disproportionately large so it makes it hard visually to break down the page.
- I'm also not sure about the example answer label but have no brainwaves on how to improve yet. Perhaps it needs to be a bit bigger, or if the 'Answered x minutes ago' notice was changed to a narrow strip like this it would seem more in balance?

![spacing](https://user-images.githubusercontent.com/6169940/33173466-2d4e1fe6-d04c-11e7-9027-de6564da2929.PNG)

I've added a screengrab of this area in DMPonline as a comparison. I think the sizing and layouts are a bit easier to scan at a glance

![compare](https://user-images.githubusercontent.com/6169940/33173822-7bc3abf4-d04d-11e7-87ee-fa99e1eb6731.PNG)

**Comment by stephaniesimms** [comment]
We are likely to reinstate a grey background to keep the look and feel as close to DMPonline currently as possible. Trying to visualize this, it seems all the content within each page is much to close to the edge to allow a line to be drawn. Can each page shift in a small margin and a border be displayed please?

![picture1](https://user-images.githubusercontent.com/6169940/33174670-ead27fe0-d050-11e7-924a-8efd0e65bd22.png)
![picture2](https://user-images.githubusercontent.com/6169940/33174722-1b37d356-d051-11e7-9bba-15f927227688.png)

**Comment by stephaniesimms** [comment]
Can the logos in the footer be transparent white ones rather than coloured blocks please? Here's a white version of the DCC one.

![dcc logo cmyk white gif](https://user-images.githubusercontent.com/6169940/33175240-007aff14-d053-11e7-81e2-66d20c3f0683.gif)

**Comment by sjDCC** [comment]
One more I spotted. There's a misalignment of buttons on the template > phase edit page
![button-misalignment](https://user-images.githubusercontent.com/6169940/33600277-af0edbd0-d9a0-11e7-86f8-4d86c2e29046.PNG)

**Comment by sjDCC** [comment]
Hi @jollopre Here's a summary of tasks to be done with cross-references to images above

- Make the actions in the banners look more like tabs or buttons. This applies to the banner above the write plan area (screengrab 1), the sign in / create account block (screengrab 2) and the guidance panel (screengrab 4). I don't think the bar needs to stretch full length - it should be capped at the number of buttons - and you may want small gaps between them so they look like tabs

- Reinstate borders around active areas. This applies to the sign in / create account block (screengrab 2), guidance (screengrab 4) and main plan editing pages (screengrab 7)

- Adjust text within each page of the plan edit block (project details, overview, write plan, share, download) to ensure borders can be drawn. Everything needs to shift a few millimeters in (screengrab 7)

- Remove the circular tick icon progress indicators from each section banner (screengrab 6). The indication of how many questions have been answered is sufficient

- Ensure the question text comes before an example answer. Currently the example answer precedes the question (screengrab 6)

- Make the "Answered X mins ago" alert smaller - perhaps same size as 'Example Answer' label? - as it's disproportionately large (screengrab 6)

- Adjust the spacing or draw a line between questions to visually demarcate one from another better. See screengrab 6 and DMPonline comparison below 

- Ensure logos in footer are transparent white ones not coloured. DCC version provided above.

**Comment by jollopre** [comment]
The PR #1082 addressed all the bullets points from [comment](https://github.com/DMPRoadmap/roadmap/issues/867#issuecomment-358981329)  except the logos. Please, @stephaniesimms can you provide us a white version for UC3.

**Comment by stephaniesimms** [comment]
sure @jollopre - i placed svg and png files in the roadmap-docs repo. let me know if you need me to make any changes. https://github.com/DMPRoadmap/roadmap-docs/tree/master/logos

**Comment by sjDCC** [comment]
This looks great, thanks @jollopre!

The logos are still to change and I noticed one additional thing. The edit profile page is missing borders around the active area. It looks like the notification preference tab content here will need to shift in too to allow the border to be drawn.  

Leaving on board for @stephaniesimms to comment / check too.

**Comment by jollopre** [comment]
changes requested available at #1097

**Comment by stephaniesimms** [comment]
all looks good. closing issue.
