### ISSUE TITLE
Manage plan status

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#87]
https://www.pivotaltracker.com/story/show/120867115

Plan statuses include:
- draft
- in review (call it something else; loose status w/no controls; add alerts for users to leave feedback on plans/notify when they receive new feedback) 
- complete  

- submitted: future status to mark plans of record/submitted to funder; corresponds with lifecycle; used for integrations, e.g., with repositories 

Question about whether status changes can be done manually or whether they should only occur automatically (triggered by clicking a button e.g. "Export")

Note plan terms that correspond with the database:
- Type (is it a test plan? y/n)
- Status (draft...complete...)
- Visibility (public/organizational/private)

**Comment by sjDCC** [comment]
Perhaps 'under comment' for 'in review' or do we need to differentiate this one?

**Comment by stephaniesimms** [comment]
per discussions w/ @sjDCC and UX I think we just need an automatically triggered 'complete' status for MVP. this will help us manage the Public DMPs list (by only displaying 'complete' plans in the list #88) and potentially to manage the admin view into plans created by users at their org.

larger discussions about status/lifecycle should wait for maDMP future enhancements

**Comment by briri** [comment]
We now have a complete flag in the database table @sjDCC and @stephaniesimms. This flag gets set when > 50% of the questions have been answered. Should this ticket be closed?

**Comment by stephaniesimms** [comment]
yes let's close this stale issue. we have plan lifecycle/status indicators listed as a future enhancement on the wiki but it requires more discussion.
