### ISSUE TITLE
Add modal: are you sure you want to remove plan?

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#870]
It's easy for a user to "Remove" a plan accidentally by selecting the action item on the My Dashboard page (screenshot 1). When I select Remove, a modal flashes on the screen, then disappears and I receive the message in the second screenshot.

Desired behavior is to provide the user with a modal that asks: "Are you sure you want to remove this plan?" The user can click a button for OK or Cancel to complete or cancel the action. 

![remove](https://user-images.githubusercontent.com/12703638/33295208-ec7eab6c-d388-11e7-99f3-62a84ec90f59.png)

![notice-removed](https://user-images.githubusercontent.com/12703638/33295228-28006dc4-d389-11e7-9bac-cce3173622ce.png)

**Comment by sjDCC** [comment]
This works fine now. Thanks @briri Closing out
