### ISSUE TITLE
Admin Guidance page - revise publish action

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#871]
This is a stub issue - TBD once the Templates page is revised
Need to rethink the workflow for publishing Guidance
- add "Publish/Unpublish" to the Actions menus for Guidance group list and Guidance list (like on Templates page)
- change "Delete" to "Remove" in Actions menus
- Change "Published" column in Guidance group table to "Status" - status should be "Published" or "Unpublished" (same as Templates table)
- Add "Status" column to Guidance list table - place between "Guidance group" and "Last updated" columns 
- a guidance group should auto-publish once 1 piece of guidance in that group is published

![screen shot 2017-12-01 at 9 04 10 am](https://user-images.githubusercontent.com/12703638/33494386-f31e0cfa-d677-11e7-8926-3b87a027d45d.png)

![screen shot 2017-12-01 at 9 05 25 am](https://user-images.githubusercontent.com/12703638/33494585-8d3ace7c-d678-11e7-8071-c0010fb99d0c.png)

**Comment by sjDCC** [comment]
I think we definitely want to be able to publish individual pieces of guidance as there may be one in question / needing revision and the institution won't want to have to deactivate the whole group to temporarily unpubliah this

I think the guidance group should autopublish once 1 piece of guidance is published though

**Comment by stephaniesimms** [comment]
ok - guidance publishing logic sounds good to me @sjDCC

**Comment by stephaniesimms** [comment]
@bhavi - auto-publish works as expected when I select to "Publish" a piece of Guidance from the Actions menu. but if I tick the "Published" box on the main Guidance editing page, it does not automatically publish the associated Guidance group (see screenshot 1). desired behavior is to auto-publish the Guidance group whether I publish a piece of Guidance via the main page or the actions menu.

one more thing i noticed when testing: the "Published" tickbox for a Guidance group is not visible when I create a new group. it only appears when I click to go Edit the group from the actions menu (screenshot 2). desired behavior is to provide the Published tickbox on this page at all times.

![guidance-publish-logic](https://user-images.githubusercontent.com/12703638/33865884-9351fc3a-dea8-11e7-97d6-cf71f96f7f4f.png)

![gg-publish](https://user-images.githubusercontent.com/12703638/33865999-2414c842-dea9-11e7-9944-39b5687bdf2a.png)

**Comment by briri** [comment]
per our meeting, add an `after_create` callback to the Org model that creates a default Guidance Group after the Org record is created. Also add a rake task to create Guidance Groups for any Orgs without them. The default name should be the '[Org's abbreviation (short name)] Guidance'

**Comment by sjDCC** [comment]
One thing to check - should the guidance group name be:
'[Org's abbreviation (short name)] Guidance'
OR
'[Org's abbreviation (short name)]'

I have a feeling the auto-text we bring in with the theme is "guidance on [Theme name]" since we rationalised that it's easier for orgs to remove the term 'guidance' from their guidance group name.

Could you check so we avoid duplication i.e. 
![capture](https://user-images.githubusercontent.com/6169940/33899505-9c23e15a-df63-11e7-8f04-2fd5fa472ef2.PNG)

**Comment by briri** [comment]
@sjDCC you're correct, we should not add the word 'Guidance' to the end of the Guidance Group name when we auto-create it. 
The Guidance tab is a bit confusing since it combines themed guidance and annotations (guidance) that are specific to the question. 
The annotation guidance displays as '[Org abbreviation (or name if no abbreviation is present)] guidance'
The themed ones show up as ['Guidance group name]: guidance on [Theme]'

**Comment by briri** [comment]
@bhavi when you get back to this ticket, just add the `after_create` callback to the Org model and have it create a default Guidance Group with the Org's name. For example if the Org is called 'University of Somewhere' with an abbreviation of 'UoS' then you would create a Guidance Group called 'UoS'. If the Org has no abbreviation defined then just use the Org's name.

**Comment by sjDCC** [comment]
This looks good. The publish checkbox is displaying when you first create a guidance group. I think we should reinstate the tooltip for guidance group name as people might not know what to call it. Here's a suggestions based on what we had in DMPonline:

"Add an appropriate name for your guidance group. This name will be used to tell the end user where the guidance has come from. We suggest you use the institution or department name e.g. 'OU' or 'Maths & Stats'

The way we've merged org-admin and super-admin pages means there's now not a way for me to create a new organisation to test if the guidance group auto-creates. I only see the 'org details' page, not a full list or orgs or button to create them

![org-details](https://user-images.githubusercontent.com/6169940/34728312-7a0098c6-f551-11e7-9961-b728ead61b63.PNG)

**Comment by stephaniesimms** [comment]
@bhavi - almost all working as expected now, with one exception. If I unpublish all the individual pieces of guidance for a group, the group remains published and still appears in the Plan Guidance Configuration list when I create a new plan.

desired behavior is to automatically "Unpublish" a guidance group if there is no published guidance attached to it.

**Comment by stephaniesimms** [comment]
@bhavi - my last change request hasn't been implemented. and one more change from sarah:
- If I unpublish all the individual pieces of guidance for a group, the group remains published and still appears in the Plan Guidance Configuration list when I create a new plan. desired behavior is to automatically "Unpublish" a guidance group if there is no published guidance attached to it. So for example, if I unpublish the 1 piece of guidance attached to the "Koala bear" guidance group for Univ of Edinburgh, the entire guidance group should also "unpublish" and no longer be visible to users when they create a new plan.
- update the tooltip when a user creates a new Guidance group w/ @sjDCC suggested text: "Add an appropriate name for your guidance group. This name will tell the end user where the guidance has come from. We suggest you use the institution or department name e.g. 'OU' or 'Maths & Stats'"

**Comment by stephaniesimms** [comment]
these last changes were merged properly this round @bhavi - all working as expected now. closing issue.

**Comment by sjDCC** [comment]
Agree this all looks good. After_create action and publishing workflow all working. Thanks @bhavi 

Removing from board
