### ISSUE TITLE
Add download button for org plans in Admin area

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#873]
Add a "Download plans" button (suggestion to place in upper right, above table) to enable Admins to download a CSV file of the user plans info.

The CSV should only contain the plan details info (from this table) and not the full content of the plans.

![screen shot 2017-11-28 at 10 31 02 am](https://user-images.githubusercontent.com/12703638/33337261-479f7474-d427-11e7-8450-0d9a0973b70c.png)

**Comment by sjDCC** [comment]
Download should probably be restricted to plan details (i.e. the metadata in this table) rather than the full content of all plans

**Comment by briri** [comment]
Agreed. We should probably just export the contents of the table

**Comment by stephaniesimms** [comment]
this looks and works great @briri - the only thing I can see that might be useful is to add another column to the downloaded csv for "Owner name" and rename the current field "Owner email" but only if this is super easy. The Plans table lists the name under Owner and the csv lists the email/contact info. Org admins would likely want to have both.

**Comment by stephaniesimms** [comment]
looks good. closing issue.

**Comment by sjDCC** [comment]
Looks good to me too. Removing from board
