### ISSUE TITLE
Revise plan visibility terminology

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#876]
I think we need to revise the terminology around plan visibility to make it clear to end users that admins can see their plans at all stages. At present the descriptor suggests it's restricted to them and their collaborators but the works in #434 changes this, if I'm understanding the proposed functionality correctly. 

Few end users are likely to have read the bit of the T&Cs which says "Authorized officers of your home institution may access your plans for specific purposes...." so I think we should flag that admins have access on this visibility setting page. 

![visibility](https://user-images.githubusercontent.com/6169940/33428900-adcf5a1a-d5c2-11e7-98c8-8f58fba942be.PNG)

How about changing the first descriptor to: "Private: visible to you, specified collaborators and institutional administrators"

I think the other descriptors are fine as is as they're broader anyhow.

We may also want to flag somehow that plans will only be visible institutionally and publicly when 60% complete or more. Is that the cap we put on it?

**Comment by sjDCC** [comment]
Looks good, thanks @jollopre 

Will leave open for now just so @stephaniesimms can ok the wording too

**Comment by stephaniesimms** [comment]
@sjDCC - i would just suggest sticking w/ org terminology for consistency. so the new text would read:

Private: visible to you, specified collaborators and administrators at your organisation

![screen shot 2017-12-05 at 11 16 36 am](https://user-images.githubusercontent.com/12703638/33625870-de3958ba-d9ad-11e7-92de-6ff629f404cc.png)

**Comment by stephaniesimms** [comment]
looks good on stage. closing issue.
