### ISSUE TITLE
Display funder requirements and sample plan links on DMP Templates page

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#880]
We've added the ability for funders to include links to their requirements and sample plans (see #819) but this need to be displayed on the public DMP Templates page. This is how it looks on DMPTool and staging.
- move the 'Download' column to immediately after the 'Template Name' and add the funder requirements links and sample plans columns at the end (final two columns on rights as per DMPTool)

![32756578-b0fef05a-c88f-11e7-8c62-61f3fc50131d](https://user-images.githubusercontent.com/6169940/33481588-222a6c9a-d68d-11e7-8af9-337cce5f7665.png)

![stage](https://user-images.githubusercontent.com/6169940/33481604-383d5e48-d68d-11e7-8e9a-e3706feb5a36.PNG)

**Comment by briri** [comment]
Ok added the funder links and sample plans to the public DMP Templates page. 
Screenshot shows 2 funder links and 1 sample plan. The first funder link has no 'text' value
![screen shot 2017-12-06 at 3 08 14 pm](https://user-images.githubusercontent.com/1204467/33690197-67abfa96-da97-11e7-96d5-35d1acfa4fe6.png)

**Comment by stephaniesimms** [comment]
@briri - looks great. but can you also add a tooltip like we have for DMPTool (screenshot below); it's not necessary to add the parenthetical (if available) just the tooltip. i think it's important to clarify the source of the sample plans.

Tooltip text: "Sample plans are provided by a funder, an institution or a trusted party."

![screen shot 2017-12-11 at 11 40 57 am](https://user-images.githubusercontent.com/12703638/33850313-54065db8-de68-11e7-8996-138e2d8e8309.png)

**Comment by stephaniesimms** [comment]
this looks good @briri - closing issue. just a note here that it needs to be wired up w/#903 to populate the links in this table. assuming i should create a new issue for it.
