### ISSUE TITLE
Answer status always shows current user name and the wrong date

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#883]
Please complete the following fields as applicable:

**Expected behaviour:**
The answer status should show the name of the user associated with the answer along with the answer's updated_at value

**Actual behaviour:**
The answer displays the currently logged in user's name and the incorrect date.

**Steps to reproduce:**
log in as userA, open a plan and share it with userB as 'editor', then answer a question on that plan. Wait 5 minutes, log in as userB and open the same plan. It displays the answer status as saved '2 weeks ago by userB' instead of '5 minutes ago by userA'

**Comment by jollopre** [comment]
Related to issue #893.

**Comment by stephaniesimms** [comment]
working as expected now. closing issue.
