### ISSUE TITLE
Clicking the 'Cancel' button when editing a section's details deletes the section

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#890]
Please complete the following fields as applicable:

**Expected behaviour:**
Clicking the 'Cancel' button on the 'edit section details' view ends up deleting the entire section.

**Actual behaviour:**
Up for discussion (@sjDCC and @stephaniesimms). When you expand the section you are in edit mode by default. Should we simply remove the cancel button or have it collapse the section?

**Steps to reproduce:**
Log in as Org/Super Admin. Go to the Admin -> Templates page. Select one of your org's templates. Click on the phase tab. Expand one of the sections. Click 'Cancel'

**Comment by sjDCC** [comment]
Realise I've responded about questions not sections, but same principle applies.

I also wonder if we should have a popup when user clicks delete to check they actually want to delete the whole section or question

**Comment by stephaniesimms** [comment]
yes we appear to be missing a button. there should be 3: Save, Delete, Cancel when you click to edit a Section or Question. 

and yes we should add a modal to ask a user if they are sure they want to Delete something (same as the modal for confirming actions to Remove a plan or template).

**Comment by stephaniesimms** [comment]
all the buttons are there now and work as expected, but please change the order @briri to be consistent w/ DMPonline:

Save - Delete - Cancel (flip the last two, screenshot below)

![screen shot 2017-12-11 at 3 37 55 pm](https://user-images.githubusercontent.com/12703638/33859557-53dd46e6-de89-11e7-9d7d-ef8d3acca472.png)

**Comment by stephaniesimms** [comment]
button order is good now. but no confirmation message asking me if I'm sure I want to delete this question. please add the confirmation step @briri

**Comment by sjDCC** [comment]
Hi @briri  - I just managed to delete two sections without the modal being issued to confirm selection. See: https://roadmap-stg.cdlib.org/org/admin/templates/phases/5492/admin_show

Perhaps this is because it was an existing legacy template?

**Comment by briri** [comment]
Hey @sjDCC I get the confirmation message for existing sections and new ones I've created. I tried it as several different orgs. 
What org owns the ticket you're having trouble with?

**Comment by sjDCC** [comment]
Hi @briri I was editing one called "Copy of UoE DMP" owned by the University of Edinburgh. I've gone itnto edit that again, and other templates, and the modal is displaying. Perhaps it was a browser issue yesterday or something else in the setup? I'm at home on laptop now.

All seems to be working though so suggest closing out and putting this down to some quirk.
