### ISSUE TITLE
Clicking edit in templates actions produces error

### ISSUE THREAD

**Issue by dlowenberg** [DMPRoadmap/roadmap#891]
Please complete the following fields as applicable:

**Expected behaviour:**
Should be taken to the edit template screen.

**Actual behaviour:**
In selecting the math NSF template edit action, the following exception occurs
**Steps to reproduce:**
Select the math NSF template and click edit action.  We noticed that this template has a "Published" status.

https://dmp2-stg.cdlib.org/org_admin/templates/41/edit?edit=true 

![screen shot 2017-12-04 at 11 24 04 am](https://user-images.githubusercontent.com/25755963/33571796-030dd2a6-d8e6-11e7-812c-5553dd8da442.png)

**Comment by briri** [comment]
Appears to have been a data migration issue. A blank option (no text value) was carried over from the DMPTool database. There were also a few options that had no sort/order number.

Manually updated the data and will update the scripts to prevent it from happening again if we need to remigrate any template data.
