### ISSUE TITLE
Default answers being saved on plan creation

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#893]
If default answers exist (see for example NERC full plan which has tables to complete), these are autosaved on plan creation so a brand new plan shows as being partially complete

![default-answer](https://user-images.githubusercontent.com/6169940/33599045-c6a55a48-d99c-11e7-9830-e560d407925b.PNG)

**Comment by stephaniesimms** [comment]
tested and now I have to click Save button to save default answers. can you confirm that this is the desired behavior @sjDCC? if so this issue can be closed.

**Comment by jollopre** [comment]
@stephaniesimms, if we auto-save a question with the default text, the questions types that are just text (e.g. textfield, textarea) will count in the section and progress statuses and I think that was the reason @sjDCC raised the issue.

We could exclude questions that have default answer from the counts but I think that would be more confusing.

**Comment by stephaniesimms** [comment]
@jollopre I agree w/all you mentioned above and think the issue should be resolved now. I just wanted @sjDCC to confirm that she also agrees before closing the issue.

**Comment by sjDCC** [comment]
This is all working fine now. Previously it was saving on creation. Now if a question is answered in another section and autosaves, it doesn't save the default answers too so all good. Removing from board
