### ISSUE TITLE
Add section error

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#894]
Something seems to have gone wrong with template creation when a section is added. This only appear to happen on editing existing templates, not creating new ones. I encountered it by testing several existing templates belonging to the University of Edinburgh on roadmap-stage.

This is a screengrab of what I'm presented with. The lower-half where a section is opened to add a title and description is correct, but there's an additional section above which is formatted differently. 

If I click 'Title' here in the grey bar, it opens a section area to edit (like the one already unzipped) - see screengrab 2. I noticed on the order of display that these are two separate sections, so the creation process seems to be making 2 by default now.

![add-dection](https://user-images.githubusercontent.com/6169940/33601557-84c74d7c-d9a4-11e7-97f0-7324e27d4899.PNG)

![section-2](https://user-images.githubusercontent.com/6169940/33601636-bab297a2-d9a4-11e7-9214-c5108d6f32cb.PNG)

Once this is created, everything is zipped up so it's not clear where to go next. The most eyecatching button is to add another section, but what the user most likely needs is to navigate into the added section (in this screengrab 'test') where they will find the 'add question' button. It would be best for page reload to re-open this section and take the user back to where they were last editing.

![added-section](https://user-images.githubusercontent.com/6169940/33601546-7fa5a186-d9a4-11e7-9932-da5f4c967e23.PNG)

![add-question](https://user-images.githubusercontent.com/6169940/33601727-fcbc51f6-d9a4-11e7-9104-9879a68d9299.PNG)

**Comment by jollopre** [comment]
@sjDCC, the empty section creation has been removed. There was a piece of code to create a section for an empty phase and apparently that was used to allow the creation of a question without the new of creating a section first. 

Do you really want to allow users to create a question directly when a phase does not have any section? If that's the case, where do you want to display that action?

**Comment by sjDCC** [comment]
No, questions should always be placed within sections. it may mean artificially making one but that's better than standalone questions as the UI requires a header to zip up/down.

All looks good now
