### ISSUE TITLE
Duplicate email on DMP feedback request

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#895]
When users request feedback on plans, all existing org-admins and the specified contact address under 'organisational details' are emailed alerts. If the single org email specified is the same as an administrator contact address, this person receives the email twice.

Some unis may not have a generic helpdesk to specify under org details, so we should make sure emails aren't duplicated if a personal address is used.

**Comment by stephaniesimms** [comment]
working as expected now. closing issue.
