### ISSUE TITLE
More template layout adjustments

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#898]
- move Add Question button below last question for each section. clicking the button would then open the new question editing area in the expected location, below any existing questions.
- Align Add Section button and Add Question buttons (screenshot 2) - either lower right or left?
- Align all Save/Cancel and Save/Cancel/Delete buttons - need to review pages and choose lower left or right for consistency
- Currently, any time you save a change the page reloads and all sections/questions are zipped up. Desired behavior is to take the user back to the place they were last editing.

![screen shot 2017-12-01 at 11 58 42 am](https://user-images.githubusercontent.com/12703638/33501215-a34a46d0-d690-11e7-96e6-646eb5ac0365.png)

![screen shot 2017-12-01 at 12 12 34 pm](https://user-images.githubusercontent.com/12703638/33501351-1b374512-d691-11e7-89f0-d5550077375e.png)

![add-question](https://user-images.githubusercontent.com/6169940/33600877-7baa6226-d9a2-11e7-9d07-632444e34137.PNG)

The section and question boxes aren't in alignment
![section-question-not-aligned](https://user-images.githubusercontent.com/6169940/33600902-89a774d6-d9a2-11e7-966a-d8df3ef4966b.PNG)

We have duplicate 'add section' buttons. There should only be one.
![add-section-question](https://user-images.githubusercontent.com/6169940/33601268-9a648f1a-d9a3-11e7-8af5-565e6f7d8f66.PNG)

**Comment by jollopre** [comment]
"any time you save a change the page reloads and all sections/questions are zipped up. Desired behavior is to take the user back to the place they were last editing." fixed in PR #923. The alignment of button on the right part fixed in PR #930.

**Comment by stephaniesimms** [comment]
all the things look much better and work as expected/requested. closing issue.
