### ISSUE TITLE
Replace tinymce with substance-forms text-area

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#90]
Replace all of the existing tinymce text-areas with substance-forms rich-text-areas.

Use the new substance-rails gem to import substance editor and its dependencies and then use its helpers to update the pages.
https://github.com/CDLUC3/substance-rails

The above gem should load the substance-forms assets into Rails' asset pipeline

**Comment by briri** [comment]
Link to Substance-forms codebase: https://github.com/substance/forms

**Comment by briri** [comment]
Need to slice this up into multiple tickets and perhaps introduce to the UI in phases (e.g. phase 1 is just swapping out Tinymce with substance editor, phase 2 is adding in contextual commenting)

**Comment by xsrust** [comment]
I  guess PRs on our fork have begun to reference issues on Roadmap

**Comment by pherterich** [comment]
@briri can we close this or is it still relevant?

**Comment by mariapraetzellis** [comment]
Rails6 offers a replacement for this so closing out.
