### ISSUE TITLE
Fix double redirect error for links on Org details page

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#904]
Expected behavior: If I enter a URL on the Org details page and do not provide link text (or vice versa), I should receive an error message when I click Save that prompts me to enter something in the empty field.

Current behavior: If I click Save when either field is blank I receive the error message below.

![dbl-redirect](https://user-images.githubusercontent.com/12703638/33633959-70378d54-d9c7-11e7-8f4b-f66af190f967.png)

![screen shot 2017-12-05 at 2 16 45 pm](https://user-images.githubusercontent.com/12703638/33633964-7462b656-d9c7-11e7-885b-1a29d865db29.png)

**Comment by briri** [comment]
This will be fixed by #866.

**Comment by stephaniesimms** [comment]
working as expected now. please just revise the error message for clarity (screenshot below). 
new message should read: "Error: Unable to save your changes. Please provide a valid URL and Link text to display in the banner."

![screen shot 2017-12-07 at 12 37 44 pm](https://user-images.githubusercontent.com/12703638/33737680-e4f58026-db4b-11e7-99fe-cd8cfa32aed3.png)


![screen shot 2017-12-07 at 12 37 44 pm](https://user-images.githubusercontent.com/12703638/33737571-801cb26e-db4b-11e7-87d9-45646ee70833.png)

**Comment by stephaniesimms** [comment]
@briri - now when I input only a URL or only link text it doesn't save, but I receive a Save Successful message (screenshot 1). I should instead receive and error message: "Error: Unable to save your changes. Please provide a valid URL and Link text to display in the banner."

I should also receive this error message if I reverse the URL and link text accidentally. Current behavior allows me to save the reversed input and displays the URL in the banner (see screenshot 2).

1 - this should be an error msg
![no-success](https://user-images.githubusercontent.com/12703638/33850896-2f073c10-de6a-11e7-86cc-459ce843b0f3.png)

2 - this should also produce an error msg
![reverse](https://user-images.githubusercontent.com/12703638/33850885-2b9e1972-de6a-11e7-8bab-732c8387660b.png)

**Comment by sjDCC** [comment]
This seems to all work now so closing out - thanks @briri 

There's one related bug - a proper warning is not generated when the 'Link text' entry is too long - but I've raised this in ticket #729
