### ISSUE TITLE
Guidance creation/editing adjustments

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#906]
When I click to the button to Create guidance on the main Guidance page, I'm directed to a New Guidance page (screenshot 1). After entering guidance and clicking Save, a box appears around the guidance and the heading changes from "New Guidance" to "Guidance."

Desired behavior is:
- Remove "New" and always present a consistent heading "Guidance" for this page. This is also consistent w/ the page headings for creating a new Guidance group. 
- Do not introduce a box rule after clicking Save. The notification at the top of the page is sufficient (screenshot 2).

![screen shot 2017-12-05 at 2 42 58 pm](https://user-images.githubusercontent.com/12703638/33634987-0c226916-d9cb-11e7-95ef-98c3b86a068d.png)

![screen shot 2017-12-05 at 2 54 06 pm](https://user-images.githubusercontent.com/12703638/33635284-3819202c-d9cc-11e7-8b7e-9f67ceeccdb0.png)

**Comment by jollopre** [comment]
@stephaniesimms the changes requested are available at #929. I noticed that guidance group redirects to the list of guidances groups whenever a new guidance group is created/updated. Do we want the same behaviour for guidances?

**Comment by stephaniesimms** [comment]
@jollopre - I think it's okay to leave the user on the Guidance editing page after creating/updating it since there's more involved here than with creating a Guidance group and they may want to make multiple changes. It should be enough to reinstate the "View all guidance" button in the upper right (issue #908) to enable navigation back to the main list. @sjDCC - do you have a preference here? i can go either way.

all looks good to me. closing but leaving on the board pending confirmation from @sjDCC.

**Comment by sjDCC** [comment]
I think they should be redirected back to the full guidance page after creating a piece of guidance as it's unlikely they'll have further edits to do on that specific entry. From the overview page they can create more easily, see the full list of guidance or navigate elsewhere. 

If we leave them on here and add a "View all guidance" button we're forcing an extra click if they're not needing to do further edits, which I think it's unlikely right away. That 'View all guidance' button is definitely useful to have though to enable movement back and forth outwith the top menu

**Comment by stephaniesimms** [comment]
Sounds good to me @sjDCC . Fewer clicks is always better. So yes @jollopre - please implement the same behavior for guidance as for guidance groups, i.e., redirect to the list of guidance whenever a user clicks Save after creating/updating.

**Comment by stephaniesimms** [comment]
redirect back to main guidance list after editing is working as expected now. closing issue.
