### ISSUE TITLE
Remove "None" option for Themes and Guidance group

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#907]
"None" is not a valid input when creating new Guidance. Remove it from the lists for Themes and Guidance group (screenshots below). 

It is possible to have no themes for a Template question, but it's not necessary to make a selection for "None" - the system allows me Save even if I make no selection. Therefore, we should also remove "None" from the list of Themes on the template editing page.

![screen shot 2017-12-05 at 2 53 11 pm](https://user-images.githubusercontent.com/12703638/33635402-ae709b88-d9cc-11e7-837c-6b75585d651c.png)

![none-not valid value](https://user-images.githubusercontent.com/12703638/33635410-b2c29d30-d9cc-11e7-9147-37ac1cdf9259.png)

**Comment by stephaniesimms** [comment]
Now that I'm comparing the roadmap stage Guidance functionality w/DMPonline - the two appear to be inconsistent and I think I created problems by removing None options. http://www.dcc.ac.uk/sites/default/files/documents/tools/dmpOnline/DMPonline-admin-interface-guide.pdf

as far as I understand it's not possible to display guidance unless it's part of a Guidance group - is this correct @sjDCC ? in this case None isn't an appropriate option but it's not clear to me as a user that I have to create a Guidance group first. If I haven't completed that step, now nothing appears in the dropdown (see screenshot). 

but there's no longer a dropdown menu to apply Guidance by themes or by question (screenshot 2 from DMPonline). is this intentional or does it need to be added back in? 

![screen shot 2017-12-11 at 3 10 47 pm](https://user-images.githubusercontent.com/12703638/33859078-2e4cdd26-de87-11e7-87ae-c9b27d0a7242.png)

![screen shot 2017-12-11 at 3 24 07 pm](https://user-images.githubusercontent.com/12703638/33859114-5d53f992-de87-11e7-9f44-3beb5fd81067.png)

**Comment by sjDCC** [comment]
Yes, that's right. Guidance has to belong to a group so any 'new guidance' entry can't be saved by assigning it to 'none' which makes it unintuitive to have that as an option. 

We could disable the create guidance option until a group is created, or I guess we could auto-create the first main group for any institution using the uni/funder short name? e.g. "MRC" or "Edinburgh" or "LSE" 

The latter option would help users who aren't sure what the guidance group should be called. They then only really need to use this if they're creating more specific subset guidance e.g. "Dept of Physics." Taking that approach would have knock on effects for legacy data though so we need to clarify best option @vyruss  

We don't need to reinstate the 'guidance by: theme / question' dropdown as guidance is just themed now. Guidance by question is classed as an annotation and is added directly to templates (either when creating your own or customising a funder one). This is much more intuitive as trying to click through all the dropdowns to select the right phase, version, section, question etc was not good for end users

**Comment by stephaniesimms** [comment]
thanks for clarifications @sjDCC - in this case it sounds like the original request to remove None options is sound. the Guidance group will now automatically be populated with the default "Org short name" group as created in related issue #871. closing this issue as it's working as requested now.
