### ISSUE TITLE
Display full list of Themes & make it easier to select multiple

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#911]
It's difficult to scroll through the list of themes and make selections for guidance or templates. The current tooltip instructs users to select multiple themes w/CTRL but Mac users have to use Command - all users have to scroll up and down repeatedly to search and select. To improve usability we should display all 14 themes clearly. Remove None from the list in related issue #907

let's try laying them out in three columns (5x5x4) with tick boxes

![screen shot 2017-12-05 at 4 04 46 pm](https://user-images.githubusercontent.com/12703638/33637483-0cd12d38-d9d6-11e7-8d03-96168fd9d771.png)

**Comment by briri** [comment]
Switched to display the themes as checkboxes
![screen shot 2017-12-13 at 12 04 40 pm](https://user-images.githubusercontent.com/1204467/33959945-f33dd74e-dffd-11e7-8fc1-eaf9d23332f5.png)

**Comment by stephaniesimms** [comment]
I think this works to have all themes laid out w/checkboxes but will wait for @sjDCC to confirm. 

One thing that requires attention is the tooltip that seems to be creating display problems when i hover over the themes (see screenshot below) - especially w/the long list of 28 some groups of themes disappear depending on where i move focus. I think it would be better to implement a question mark/tooltip next to the word Themes here. we have popover/tooltip issues elsewhere and need to find a holistic solution.  

Proposed text based on DMPonline tooltip:
"Select one or more themes that are relevant to this question. This will display your generic institution-level guidance, as well as that from other sources e.g. the %{organisation_abbreviation} or any Schools/Departments that you provide guidance for."

![screen shot 2017-12-14 at 2 09 09 pm](https://user-images.githubusercontent.com/12703638/34017005-c6b656fc-e0d8-11e7-980b-6d12631fe7da.png)

**Comment by sjDCC** [comment]
Sounds good @stephaniesimms Tooltip is at high-level, not individual themes

**Comment by sjDCC** [comment]
The tooltip doesn't encourage now as much as it did before but it's a completely different style. Instead of propping up when you hover-over / scroll through this question area, you need to click the help icon which reloads the page and jumps you to the top. You only see the tooltip when you scroll back down.

![hover-over](https://user-images.githubusercontent.com/6169940/34525626-82bf647e-f097-11e7-9072-aaf9d24fd6d8.png)


Can it be implemented in the same style as the others i.e. black box offset to right which pops up automatically when question area is active?

**Comment by stephaniesimms** [comment]
I agree that we want consistent style and behavior @sjDCC . This raises an issue about tooltips vs. popovers that we're waiting for a future accessibility test to resolve for us. 

In the meantime, I believe we elected to go w/tooltips for consistency - they appear when you hover and also work on mobile devices (but correct me if I'm wrong @briri ). So in this case can you style the message w/white text on black box and make an additional message appear to the right of the themes when a user hovers over them?

**Comment by stephaniesimms** [comment]
looks good @briri - i'll close but leave here for @sjDCC to confirm if she's ok w/it too.

**Comment by sjDCC** [comment]
Looks fine. Removing from board
