### ISSUE TITLE
Only change template status if user edits and saves changes

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#912]
Currently, if I open a Template by selecting Edit from the Actions menu, the template status changes to Unpublished. Desired behavior is to only change the template status if I make any changes to the template. If I open the template but do not edit and save changes, the status should remain as Published.

![screen shot 2017-12-05 at 4 13 52 pm](https://user-images.githubusercontent.com/12703638/33637689-5ac17448-d9d7-11e7-95b0-cb343943f35a.png)

**Comment by briri** [comment]
was updated by #902. @xsrust pointed out that the code was no longer using the 'Unpublished changes' status. This may make things clearer to the user. Lets reassess once its merged and deployed

**Comment by stephaniesimms** [comment]
Now when I click to Edit a template and then return to the main Templates table without making any changes, the status is still "Published" - which is what I would expect. It also helps to distinguish status for "Unpublished" and "Unpublished changes." So now I would say this is working as we want it to. 

The only issue is the appearance of the "Publish" and "Publish changes" actions in the dropdown menu (screenshots below). Can you please fix it @briri to not be a hyperlink and look like the other menu items?

![publish-weird](https://user-images.githubusercontent.com/12703638/33858566-fa33a620-de84-11e7-951b-0c65ed8ec1dc.png)

![screen shot 2017-12-11 at 3 07 56 pm](https://user-images.githubusercontent.com/12703638/33858611-25b6890c-de85-11e7-9e7a-7bc563349e67.png)

**Comment by stephaniesimms** [comment]
action menus are pretty now and all working as expected. closing issue.
