### ISSUE TITLE
Request Feedback message conditional disabled

### ISSUE THREAD

**Issue by jollopre** [DMPRoadmap/roadmap#918]
Please complete the following fields as applicable:

**Expected behaviour:**
The request feedback message is not disabled, i.e. read-only when the request feedback is turned off.
**Actual behaviour:**
If the request feedback is turned off, the user still can introduce text, although this never gets persisted.
**Steps to reproduce:**
CASE 1:

- Go to request feedback tab for an organisation that has request feedback turned off
- Type anything and press save

CASE 2:

- Go to request feedback tab for an organisation that has request feedback enabled
- Turn off request feedback
- Type anything and press save

**Comment by briri** [comment]
this has been fixed during recent refactoring
