### ISSUE TITLE
Restrict registrations to a specifc domain

### ISSUE THREAD

**Issue by raycarrick-ed** [DMPRoadmap/roadmap#93]
or set of domains. This was requested by Peter Neish from Melbourne. Will need to be checked in terms of collaborations before we implement it.

**Comment by briri** [comment]
was the request to do this at the application level as a whole or to allow an Org basis?
Also, was it just registration specifically or login as well?

If its at the app level then this might be a viable approach (although this quite old so devise may have something better by now):
http://stackoverflow.com/questions/6448969/how-can-i-restrict-access-to-all-devise-controllers-by-ip-address

**Comment by vyruss** [comment]
Right now I've implemented this (uncommitted kludge) on DMPmelbourne site
as a check for org type = 4 in the registration org select box
