### ISSUE TITLE
Don't display "Other" Org in branding banner

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#932]
If a user has an Org affiliation the name (and any other brandin ginfo, e.g. logo, links etc) should always be displayed in the branding banner. But we need an exception for "Other" Org. Desired behavior is to leave the banner empty for users w/Other Org (see screenshot).

![screen shot 2017-12-11 at 11 23 12 am](https://user-images.githubusercontent.com/12703638/33849786-80e5170e-de66-11e7-9b79-5acdf7349566.png)

**Comment by briri** [comment]
Should be able to use `orgs.is_other === true` to find the org when the user has not associated themselves with an org from the list

**Comment by briri** [comment]
Since the user cannot be an Org Admin when they do not have an org affiliation we will just hide the secondary navigation bar (the light grey one).

**Comment by stephaniesimms** [comment]
this seems to work as expected now. closing issue.
