### ISSUE TITLE
Clicking cancel deletes Guidance from the list 

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#933]
When I select "Remove" from the Guidance actions menu I receive an "Are you sure..." message prompt as expected. However, my guidance is removed/deleted when I click the cancel button (screenshots below). Desired behavior is to only remove/delete guidance if user clicks Ok button.

![screen shot 2017-12-11 at 12 03 30 pm](https://user-images.githubusercontent.com/12703638/33851375-b5e174de-de6b-11e7-9038-27d25122ff10.png)

![screen shot 2017-12-11 at 12 06 59 pm](https://user-images.githubusercontent.com/12703638/33851425-d4836b54-de6b-11e7-8dbe-d0eb283451be.png)

**Comment by sjDCC** [comment]
Works fine now. Only removes entry when you confirm you wish to do so. Closing out
