### ISSUE TITLE
Plan write page no longer loading

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#940]
Some recent changes to the `annotations/_show.html.erb` file now prevent the write plan page from loading.
![screen shot 2017-12-12 at 10 41 45 am](https://user-images.githubusercontent.com/1204467/33902230-38d9ce96-df29-11e7-888c-3971f7b56c29.png)

**Comment by stephaniesimms** [comment]
this is fixed. closing issue.
