### ISSUE TITLE
Allow sharing of public DMP templates between installations

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#95]
It would be valuable for a new publicly accessible DMP to be available across all of the installations of DMP Roadmap (e.g. DMPTool, DMP Online's, DMP Tuuli, DMP Assistant, etc.).

There are several ways to handle this (and perhaps others I'm not seeing):

1. A list of installations could be maintained and an API developed that provides public DMP template data (as JSON). A scheduled rake task could then be run that runs through the list of installations and calls their API to retrieve the latest plans (ActiveJob is a good candidate for this). 

2. Someone or a group of people can be assigned to manage the list of public DMP templates in an online repository. A mechanism could then be built to retrieve public DMP templates from this location rather than the local database. The information could perhaps be made accessible via an RSS feed or JSON/XML. Submissions of new templates would need to be made to the designated maintainers of the list.

2. We could begin storing publicly accessible DMP templates as files and allow them to become part of the Git repository. Then each time a plan is made public the institution could submit a Pull Request and once merged a notification can be sent out to all of the repositories watchers asking them to pull down the new template. This option could get messy though ... perhaps best managed in a separate repository.

**Comment by vyruss** [comment]
I think option 3 is the easiest to implement. Agreed about the separate repository though.

**Comment by sjDCC** [comment]
Two comments:
- DMPonline doesn't have the concept of public and private templates. All are public, so we need to check that works for your users and if not add a ticket to your MVP list
- There's definitely demand for subscribing to template update feeds and I like the sound of option 2. My only concern is that we don't want to encourage lots of separate installations. We've charged the Finns an annual subscription for additional templates we maintain on their behalf, so perhaps we should charge for this, but that becomes messy if we're not the only ones maintaining public templates. In the US it's much more of a community effort right? Perhaps that's the way we need to go here too?

**Comment by stephaniesimms** [comment]
nope. we should close this and discuss if this is ever something we want to be able to do in light of dmponline subscription.
