### ISSUE TITLE
Error saving template when not a funder Org

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#953]
Receive an error on the empty Links hash when trying to create a new template as a non-funder org.
![screen shot 2017-12-14 at 9 54 47 am](https://user-images.githubusercontent.com/1204467/34006955-0006d4be-e0b5-11e7-9a54-8c18d6da3c4e.png)

**Comment by sjDCC** [comment]
All seems to work fine now. Could create a template for Edinburgh. Closing out.
