### ISSUE TITLE
Tie into the Fundref list of funder organisations

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#96]
We need to tie the Crossref's Fundref registry into DMP Roadmap to provide us with an authoritative list of funders. This will be a part of the plan creation process as well as the Org details page (to allow a funding organisation to select themselves from the list).

It would probably make sense to create a table/model structure similar to our 'identifier_schemes <--> user_identifiers <--> users' setup to manage this and any other systems we want to begin tying into in the future.

More info about [Fundref](https://www.crossref.org/services/funder-registry/).

**Comment by briri** [comment]
We may prefer to use the new Research Organization Registry (ROR) once its online and ready for use

**Comment by pherterich** [comment]
Closing this one now that #2389 is merged - a new one can be opened if any further work is needed.
