### ISSUE TITLE
Add RDA Backend to MVP Branch

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#960]
- New Question Type - `:rda_metadata`
 - Add Rake task to create the question in the DB
 - Add Set/Parse functions to answers model for JSON backended rda questions

**Comment by xsrust** [comment]
Also add a new route to QuestionFormatsController to grab the API address from QuestionFormat's description field

**Comment by briri** [comment]
closing this out since the RDA work has finished. Please reopen if its still applicable @xsrust
