### ISSUE TITLE
Add rda question view to plans

### ISSUE THREAD

**Issue by xsrust** [DMPRoadmap/roadmap#963]
- Pull in interface from old version
    - Add links out to RDA Directory
    - Increase size of 'Your Selected Standard'
    - Increase size and change text of 'Comments' to 'Additional Info and Comments'
 - Update JS to ES6
 - Handle for RDA_questions in Answers_controller using helper methods from model
 - ensure rda question refreshes status after autosave.

**Comment by briri** [comment]
closing this out since the RDA work has finished. Please reopen if its still applicable @xsrust
