### ISSUE TITLE
Remove access to plans under review when org affiliation changes

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#972]
The 'request feedback' functionality works by adding a new role/association to the plan. When the user clicks' the 'Request Feedback' button the system links their org admins to the plan. If that org admin switched org affiliations it would remain with them.

When org admins changed their affiliation, they lose admin rights. At the same time they should also lose access to any plans they have been granted permission to provide feedback on

**Comment by briri** [comment]
is this one still an issue @sjDCC?

**Comment by magdalenadrafiova** [comment]
I went through the following steps, 

1,I logged in as magdalena.drafiova@glasgow.ac.uk and I requested feedback with my account magdalena.drafiova@glasgow.ac.uk to DMPonline Tutorials - account magdalena.drafiova@ed.ac.uk
2, logged in as magdalena.drafiova@ed.ac.uk and I could see the feedback requested from amgdalena.drafiova@glasgow.ac.uk
3, I changed my affiliation - as a result lost my admin privileges and lost access to the requested plans 

this seems to be working well now can we close @briri ?
