### ISSUE TITLE
Add FastGetText localization for I18n 

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#98]
Add the FastGetText gem to allow us more easily manage our localization files and will also ensure rapid retrieval of translations for the end user.

Some of the tasks should include:
- Add new po file formats
- Remove config/initializers/locale.rb
- Move all branded content out of localization files
- Switch en-UK and en-US to en_UK and en_US in file names and DB languages table

**Comment by jollopre** [comment]
- .pot file and .po files for (de, en_GB, en_US, es and fr) are added under config/locale

- config/inititializers/locale.rb has getters/setters to point at FastGettext (locale getter needed, otherwise setting locale to en_GB or en_US ends up replaced as en-GB or en-US).

- en-UK and en-US have been renamed as en_GB and en_US respectively.

**Comment by jollopre** [comment]
- Replaced views conforming to (t(['|"]|\st(['|"]) with gettext library. All changes are pushes to development and also to DMPRoadmap/roadmap#98 branch at DigitalCurationCenter/roadmap

TODO:

- Replacing I18n.t(...) from models and views.
- Replace parametrised .yaml keys (e.g. t("helpers.settings.plans.margins.#{pos}"))
- translations.js (if used)

TEAM DISCUSSION BEFORE TAKING ANY ACTION:
- Views from external gems conforming to I18n (e.g. contact_us, devise, bootstrap)
- Views used for branding (e.g. static_pages)

**Comment by jollopre** [comment]
Two new issues have been derived (e.g. #166 and #167)

TODO:
- Replace parametrised .yaml keys (e.g. t("helpers.settings.plans.margins.#{pos}")). This involves some changes not only on views but potentially on models where constants are defined.

**Comment by jollopre** [comment]
TODO:
- Replacing the export plan views (e.g. t("helpers.plan.export.#{field}")). This depends on #174 in order to be finished.

**Comment by jollopre** [comment]
I suggest to remove the .yml files placed at config/locales/*.yml later on so that we avoid any confusion for external contributors. Meanwhile, it is safe to keep them there in case there are more lines such as I18n or t(...).

**Comment by briri** [comment]
agreed. I added the removal of the old .yml files to our #170 Post migration cleanup ticket

**Comment by stephaniesimms** [comment]
Not sure how to test this, but translation and localization functions all working as expected in the UI.
