### ISSUE TITLE
Add button to Plan Overview page to begin writing plan

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#990]
Add a 'Write plan' button as in DMPonline's 'Answer questions' button (see screenshots 1-2) to help navigate people through from this overview to the sections for answering. 'Write plan' keeps the language consistent with single-phase plans (screenshot 3), and makes sense even when a template has multiple phases.
- When a user clicks the Write plan button it should take them to the tab for the appropriate plan phase (e.g., Outline DMP or Full DMP in screenshot below).

1 - Button position at the top right of each phase
![add answer questions buttons](https://user-images.githubusercontent.com/6169940/34113662-5d078ea0-e408-11e7-85c8-31f3cd8334f2.PNG)

2 - DMPonline button (note: only add "Write plan" button, not "Export" button) 
And what we have on DMPonline overview 
![examples-dmponline](https://user-images.githubusercontent.com/6169940/34113677-66a31484-e408-11e7-8562-f10049ce24e1.PNG)

3 - Write plan
![screen shot 2018-01-02 at 4 05 54 pm](https://user-images.githubusercontent.com/12703638/34504964-e11568f0-efd6-11e7-90d2-776be5d0bd5f.png)

**Comment by sjDCC** [comment]
Yes, happy to label the proposed new button on the 'plan overview' tab as 'Write plan' Like you say, this keeps the language consistent.

When there is more than 1 phase, the 'Write plan' button should direct the user to the first phase. The phases will be named differently (as defined by the template owner) when there's more than one

**Comment by stephaniesimms** [comment]
the button and functionality look good to me. closing issue but leaving here for @sjDCC to test.

**Comment by sjDCC** [comment]
Agree this looks good. Removing from board.
