### ISSUE TITLE
Table filtering issues

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#991]
I'm finding it difficult to use the tables to find content on the admin interface. At present I'm trying to assign my secondary account org admin rights for Edinburgh. When I go to the list of users, I can sort the columns but this only works for the 10 entries in view. 
![users-filter](https://user-images.githubusercontent.com/6169940/34524766-9d8b38f8-f094-11e7-840d-d9a942819fdc.PNG)

When you click to view all, the column reorder option disappears and a search box is presented. This doesn't work however - a bug? Searching for my name returns me to the user list presented above.
![search](https://user-images.githubusercontent.com/6169940/34524845-df57df34-f094-11e7-8a3b-40455e9ab72f.PNG)

Can we ensure that both search and reorder options are available at all times?

It's not clear how the table is ordered. It's not by last login (which may be most useful) or alphabetical. We should perhaps standardise this and make it explicit too. Any preferences @stephaniesimms?

**Comment by briri** [comment]
This will be addressed as part of the work @jollopre is doing on #815 

All of the tables now share a common set of code, so correcting the sort/search/pagination issues in that ticket will apply to all of the tables on the site.

**Comment by sjDCC** [comment]
Great - I'll close this one out then
