### ISSUE TITLE
isActivePage function too generic

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#994]
The isActivePage function was changed to `includes?` instead of `==` to accommodate for selected tabs (e.g. `http://localhost:3000/plans/28521/phases/38/edit#guidance-424-192`). 

The Write Plan page however results in 2 tabs being marked as active, the project details and the write plan tab because the url for the project details page is: `http://localhost:3000/plans/28521` and the url for the write plan page is: `http://localhost:3000/plans/28521/phases/38/edit`.

We need to update the method to only allow for fuzzy matching in the last part of the url path or allow for an argument to be passed that specifies that the value must match exactly

**Comment by stephaniesimms** [comment]
can't test in UI. closing issue.
